### ISSUE TITLE
Frigate Addon won't start 

### ISSUE THREAD

**Issue by rusty-genius** [blakeblackshear/frigate#10443]
For some time now, my Frigate Addon from HACS won't start. I tried to uninstall and reinstall it and it didn't work.

The Logs show that there might be a problem in the config. Here is the log:

---------------------------------------------------------------------------------------------
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-03-14 09:56:09.300199532  [INFO] Preparing Frigate...
2024-03-14 09:56:09.300893525  [INFO] Starting NGINX...
2024-03-14 09:56:09.303061050  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-03-14 09:56:09.308659780  [INFO] Starting Frigate...
2024-03-14 09:56:09.324594025  [INFO] Got IP address from supervisor: 192.168.1.38
2024-03-14 09:56:09.344762968  [INFO] Got WebRTC port from supervisor: 8555
2024-03-14 09:56:09.510917384  [INFO] Starting go2rtc...
2024-03-14 09:56:09.568804125  10:56:09.568 INF go2rtc version 1.8.4 linux/amd64
2024-03-14 09:56:09.569152349  10:56:09.569 INF [api] listen addr=:1984
2024-03-14 09:56:09.569214477  10:56:09.569 INF [rtsp] listen addr=:8554
2024-03-14 09:56:09.569388269  10:56:09.569 INF [webrtc] listen addr=:8555
2024-03-14 09:56:10.247854606  [2024-03-14 10:56:10] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-03-14 09:56:10.247891166  [2024-03-14 10:56:10] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-03-14 09:56:10.263165815  *************************************************************
2024-03-14 09:56:10.263169001  *************************************************************
2024-03-14 09:56:10.263173309  ***    Your config file is not valid!                     ***
2024-03-14 09:56:10.263174942  ***    Please check the docs at                           ***
2024-03-14 09:56:10.263175884  ***    https://docs.frigate.video/configuration/index     ***
2024-03-14 09:56:10.263194880  *************************************************************
2024-03-14 09:56:10.263195682  *************************************************************
2024-03-14 09:56:10.263208406  ***    Config Validation Errors                           ***
2024-03-14 09:56:10.263209067  *************************************************************
2024-03-14 09:56:10.263209678  invalid literal for int() with base 10: 'undefined'
2024-03-14 09:56:10.263701418  Traceback (most recent call last):
2024-03-14 09:56:10.263702290    File "/opt/frigate/frigate/app.py", line 645, in start
2024-03-14 09:56:10.263702851      self.init_config()
2024-03-14 09:56:10.263703512    File "/opt/frigate/frigate/app.py", line 113, in init_config
2024-03-14 09:56:10.263704143      self.config = user_config.runtime_config(self.plus_api)
2024-03-14 09:56:10.263704804    File "/opt/frigate/frigate/config.py", line 1243, in runtime_config
2024-03-14 09:56:10.263705436      camera_config.objects.filters[object] = RuntimeFilterConfig(
2024-03-14 09:56:10.263706087    File "/opt/frigate/frigate/config.py", line 430, in __init__
2024-03-14 09:56:10.263706758      config["mask"] = create_mask(config.get("frame_shape", (1, 1)), mask)
2024-03-14 09:56:10.263707630    File "/opt/frigate/frigate/util/image.py", line 674, in create_mask
2024-03-14 09:56:10.263708181      add_mask(m, mask_img)
2024-03-14 09:56:10.263727748    File "/opt/frigate/frigate/util/image.py", line 685, in add_mask
2024-03-14 09:56:10.263728490      [[int(points[i]), int(points[i + 1])] for i in range(0, len(points), 2)]
2024-03-14 09:56:10.263729502    File "/opt/frigate/frigate/util/image.py", line 685, in <listcomp>
2024-03-14 09:56:10.263730183      [[int(points[i]), int(points[i + 1])] for i in range(0, len(points), 2)]
2024-03-14 09:56:10.263739220  ValueError: invalid literal for int() with base 10: 'undefined'
2024-03-14 09:56:10.263739801  
2024-03-14 09:56:10.263740422  *************************************************************
2024-03-14 09:56:10.263747045  ***    End Config Validation Errors                       ***
2024-03-14 09:56:10.263747686  *************************************************************
2024-03-14 09:56:11.416269129  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-03-14 09:56:11.425694722  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-03-14 09:56:11.465409737  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-03-14 09:56:11.467472726  exit with signal: terminated
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-03-14 09:56:11.471033893  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
---------------------------------------------------------------------

I am not a technical expert so I would appreciate if you could give me a hint about what to do to get it working again. 

-------------------------
Homeassistant:

Core 2024.3.0
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240306.0
------------------------

Frigate Version 0.13.2

If you need more information, just tell me. Thx

**Comment by hawkeye217** [comment]
This is not a feature request. Please open a discussion and paste your full Frigate config there.
