### ISSUE TITLE
[Detector Support]: rpi5+haos+coral m.2 not detected

### ISSUE THREAD

**Issue by gabriel403** [blakeblackshear/frigate#11363]
### Discussed in https://github.com/blakeblackshear/frigate/discussions/11302

<div type='discussions-op-text'>

<sup>Originally posted by **gabriel403** May  9, 2024</sup>
### Describe the problem you are having

I've got a rpi5 with a coral m.2 installed, the tpu seems to be loaded into haos ok as it shows as /dev/apex_0

My frigate config is

```
detectors:
  coral:
    type: edgetpu
    device: pci:0 #also tried pci
```

But I get an error when trying to start frigate

```
2024-05-09 01:20:31.696663810  [2024-05-09 02:20:31] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2024-05-09 01:20:31.698296405  [2024-05-09 02:20:31] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

There are a few other python logs but these seem the most relevant

If anyone could help if really appreciate it

### Version

0.13.3

### Frigate config file

```yaml
mqtt:
  enabled: False
  
detectors:
  coral:
    type: edgetpu
    device: pci:0

cameras:
  dummy_camera: # <--- this will be changed to your actual camera later
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant log output

```shell
2024-05-09 01:20:29.633900345  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2024-05-09 01:20:29.733857688  [INFO] Preparing new go2rtc config...
2024-05-09 01:20:29.742046107  [INFO] Starting Frigate...
2024-05-09 01:20:29.776375027  [INFO] Got IP address from supervisor: 192.168.0.178
2024-05-09 01:20:29.817211624  [INFO] Got WebRTC port from supervisor: 8555
2024-05-09 01:20:30.153963057  [INFO] Starting go2rtc...
2024-05-09 01:20:30.242194537  02:20:30.242 INF go2rtc version 1.8.4 linux/arm64
2024-05-09 01:20:30.243011464  02:20:30.242 INF [rtsp] listen addr=:8554
2024-05-09 01:20:30.243015890  02:20:30.242 INF [api] listen addr=:1984
2024-05-09 01:20:30.243095833  02:20:30.243 INF [webrtc] listen addr=:8555
2024-05-09 01:20:31.582826504  [2024-05-09 02:20:31] frigate.app                    INFO    : Starting Frigate (0.13.2-6476f8a)
2024-05-09 01:20:31.584005812  [2024-05-09 02:20:31] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-05-09 01:20:31.593065620  [tcp @ 0x1f832540] Connection to tcp://127.0.0.1:554?timeout=0 failed: Connection refused
2024-05-09 01:20:31.593542369  [ERROR:0@0.789] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-05-09 01:20:31.593547165  
2024-05-09 01:20:31.593556702  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://127.0.0.1:554/rtsp in function 'icvExtractPattern'
2024-05-09 01:20:31.593558517  
2024-05-09 01:20:31.593559109  
2024-05-09 01:20:31.623549510  [2024-05-09 02:20:31] peewee_migrate.logs            INFO    : Starting migrations
2024-05-09 01:20:31.628610365  [2024-05-09 02:20:31] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-05-09 01:20:31.635161449  [2024-05-09 02:20:31] frigate.app                    INFO    : Recording process started: 308
2024-05-09 01:20:31.638920721  [2024-05-09 02:20:31] frigate.app                    INFO    : go2rtc process pid: 99
2024-05-09 01:20:31.666656540  [2024-05-09 02:20:31] detector.coral                 INFO    : Starting detection process: 317
2024-05-09 01:20:31.670925171  [2024-05-09 02:20:31] frigate.app                    INFO    : Output process started: 319
2024-05-09 01:20:31.681460207  [2024-05-09 02:20:31] frigate.app                    INFO    : Camera processor not started for disabled camera dummy_camera
2024-05-09 01:20:31.681467151  [2024-05-09 02:20:31] frigate.app                    INFO    : Capture process not started for disabled camera dummy_camera
2024-05-09 01:20:31.696160654  Process detector:coral:
2024-05-09 01:20:31.696663810  [2024-05-09 02:20:31] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:0
2024-05-09 01:20:31.697653919  Traceback (most recent call last):
2024-05-09 01:20:31.697717103    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2024-05-09 01:20:31.697719177      delegate = Delegate(library, options)
2024-05-09 01:20:31.697720510    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2024-05-09 01:20:31.697721362      raise ValueError(capture.message)
2024-05-09 01:20:31.697721992  ValueError
2024-05-09 01:20:31.697722621  
2024-05-09 01:20:31.697723658  During handling of the above exception, another exception occurred:
2024-05-09 01:20:31.697728232  
2024-05-09 01:20:31.697729047  Traceback (most recent call last):
2024-05-09 01:20:31.697731973    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-05-09 01:20:31.697732769      self.run()
2024-05-09 01:20:31.697733880    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-05-09 01:20:31.697776583      self._target(*self._args, **self._kwargs)
2024-05-09 01:20:31.697778490    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-05-09 01:20:31.697779805      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-05-09 01:20:31.697780953    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-05-09 01:20:31.697794342      self.detect_api = create_detector(detector_config)
2024-05-09 01:20:31.697795564    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-05-09 01:20:31.697796397      return api(detector_config)
2024-05-09 01:20:31.697797546    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 41, in __init__
2024-05-09 01:20:31.697798601      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2024-05-09 01:20:31.697818527    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2024-05-09 01:20:31.697820193      raise ValueError('Failed to load delegate from {}\n{}'.format(
2024-05-09 01:20:31.697871711  ValueError: Failed to load delegate from libedgetpu.so.1.0
2024-05-09 01:20:31.697873211  
2024-05-09 01:20:31.698296405  [2024-05-09 02:20:31] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2024-05-09 01:20:39.628442175  [INFO] Starting go2rtc healthcheck service...
2024-05-09 01:20:51.957585334  [2024-05-09 02:20:51] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-05-09 01:20:51.974230571  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-05-09 01:20:52.041554930  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2024-05-09 01:20:52.045054318  [2024-05-09 02:20:52] frigate.app                    INFO    : Stopping...
2024-05-09 01:20:52.045482291  [2024-05-09 02:20:52] frigate.events.cleanup         INFO    : Exiting event cleanup...
2024-05-09 01:20:52.046130277  [2024-05-09 02:20:52] frigate.watchdog               INFO    : Exiting watchdog...
2024-05-09 01:20:52.046288181  [2024-05-09 02:20:52] frigate.record.cleanup         INFO    : Exiting recording cleanup...
2024-05-09 01:20:52.046750819  [2024-05-09 02:20:52] frigate.storage                INFO    : Exiting storage maintainer...
2024-05-09 01:20:52.046754930  [2024-05-09 02:20:52] frigate.ptz.autotrack          INFO    : Exiting autotracker...
s6-rc: info: service nginx-log successfully stopped
2024-05-09 01:20:52.047310159  [2024-05-09 02:20:52] frigate.stats                  INFO    : Exiting stats emitter...
2024-05-09 01:20:52.165727168  [2024-05-09 02:20:52] frigate.comms.ws               INFO    : Exiting websocket client...
2024-05-09 01:20:52.702795148  [2024-05-09 02:20:52] frigate.object_processing      INFO    : Exiting object processor...
2024-05-09 01:20:52.971427599  [2024-05-09 02:20:52] frigate.events.maintainer      INFO    : Exiting event processor...
2024-05-09 01:20:52.971632817  [2024-05-09 02:20:52] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2024-05-09 01:20:52.973932175  [2024-05-09 02:20:52] frigate.record.maintainer      INFO    : Exiting recording maintenance...
2024-05-09 01:22:52.080338407  [INFO] Service Frigate exited with code 256 (by signal 9)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-05-09 01:22:52.083301129  exit with signal: terminated
s6-rc: info: service frigate-log successfully stopped
2024-05-09 01:22:52.089227072  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Any other information that may be helpful

_No response_</div>

**Comment by DanielCastroNexo** [comment]
I'm having exactly the same problem.

**Comment by gabriel403** [comment]
@NickM-27 what does not planned mean?

**Comment by NickM-27** [comment]
issues are for feature requests, and you created a duplicate issue from the discussion
