### ISSUE TITLE
[Beta2] UI not always loading

### ISSUE THREAD

**Issue by tripelbit-dev** [blakeblackshear/frigate#11702]
**Describe what you are trying to accomplish and why in non technical terms**
Loading main page of UI or any individual camera feeds

**Describe alternatives you've considered**
Appears related to changes in Beta 2 as Beta 1 did not exhibit similar issues.

Main page loads, camera views populate but never show live footage, after 5 to 10 seconds the entire page goes blank.
Console log has the following errors:

```
index-DpjCrPa-.js:40  DOMException: Failed to execute 'querySelector' on 'Document': '#1livingroom-canvas' is not a valid selector.
    at a.initCanvas (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1272)
    at new B (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1101)
    at http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:12:64208
    at Pl (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:24263)
    at ka (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:42318)
    at p4 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:41166)
    at Sn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:40215)
    at Bu (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:36825)
    at Cn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:38:3274)
    at p4 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:41221)
xc @ index-DpjCrPa-.js:40
r.callback @ index-DpjCrPa-.js:40
lu @ index-DpjCrPa-.js:38
wu @ index-DpjCrPa-.js:40
k0 @ index-DpjCrPa-.js:40
c4 @ index-DpjCrPa-.js:40
p4 @ index-DpjCrPa-.js:40
Sn @ index-DpjCrPa-.js:40
Bu @ index-DpjCrPa-.js:40
Cn @ index-DpjCrPa-.js:38
p4 @ index-DpjCrPa-.js:40
Sn @ index-DpjCrPa-.js:40
y0 @ index-DpjCrPa-.js:40
W @ index-DpjCrPa-.js:25
N @ index-DpjCrPa-.js:25
index-DpjCrPa-.js:38  Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#1livingroom-canvas' is not a valid selector.
    at a.initCanvas (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1272)
    at new B (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1101)
    at http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:12:64208
    at Pl (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:24263)
    at ka (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:42318)
    at p4 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:41166)
    at Sn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:40215)
    at Bu (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:36825)
    at Cn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:38:3274)
    at p4 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:41221)
Cn @ index-DpjCrPa-.js:38
p4 @ index-DpjCrPa-.js:40
Sn @ index-DpjCrPa-.js:40
y0 @ index-DpjCrPa-.js:40
W @ index-DpjCrPa-.js:25
N @ index-DpjCrPa-.js:25
main-LGE90Fwm.js:12  WebSocket connection to 'ws://192.168.0.2:5005/ws' failed: Received a broken close frame containing a reserved status code.
```

If I refresh, I sometimes get errors regarding other cameras than #1livingroom but always the same type of error

If I try to access a specific camera, for example http://192.168.0.2:5005/#3driveway

I also get a blank page with the following errors:

```index-DpjCrPa-.js:40  DOMException: Failed to execute 'querySelector' on 'Document': '#3driveway-canvas' is not a valid selector.
    at a.initCanvas (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1272)
    at new B (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1101)
    at http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:12:64208
    at Pl (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:24263)
    at ka (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:42318)
    at Bu (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:36565)
    at Cn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:38:3274)
    at p4 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:41221)
    at Sn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:40215)
    at y0 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:35675)
xc @ index-DpjCrPa-.js:40
r.callback @ index-DpjCrPa-.js:40
lu @ index-DpjCrPa-.js:38
wu @ index-DpjCrPa-.js:40
k0 @ index-DpjCrPa-.js:40
c4 @ index-DpjCrPa-.js:40
p4 @ index-DpjCrPa-.js:40
Sn @ index-DpjCrPa-.js:40
Bu @ index-DpjCrPa-.js:40
Cn @ index-DpjCrPa-.js:38
p4 @ index-DpjCrPa-.js:40
Sn @ index-DpjCrPa-.js:40
y0 @ index-DpjCrPa-.js:40
W @ index-DpjCrPa-.js:25
N @ index-DpjCrPa-.js:25
index-DpjCrPa-.js:38  Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#3driveway-canvas' is not a valid selector.
    at a.initCanvas (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1272)
    at new B (http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:9:1101)
    at http://192.168.0.2:5005/assets/BirdseyeLivePlayer-Cf1dpXS5.js:12:64208
    at Pl (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:24263)
    at ka (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:42318)
    at Bu (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:36565)
    at Cn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:38:3274)
    at p4 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:41221)
    at Sn (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:40215)
    at y0 (http://192.168.0.2:5005/assets/index-DpjCrPa-.js:40:35675)
Cn @ index-DpjCrPa-.js:38
p4 @ index-DpjCrPa-.js:40
Sn @ index-DpjCrPa-.js:40
y0 @ index-DpjCrPa-.js:40
W @ index-DpjCrPa-.js:25
N @ index-DpjCrPa-.js:25
main-LGE90Fwm.js:12  WebSocket connection to 'ws://192.168.0.2:5005/ws' failed: Received a broken close frame containing a reserved status code.```

Network tab doesn't show any issues and ad-blockers are disabled for this IP

**Comment by NickM-27** [comment]
Thanks, this should be logged as a support not feature request.
