### ISSUE TITLE
Clips folder can not be opened in Home Assistant

### ISSUE THREAD

**Issue by SebbeM** [blakeblackshear/frigate#1341]
**Describe the bug**
After upgrading to Home Assistant 2021.6.6, I can no longer open the Clips folder in the media-browser of Home Assistant. Error log as below.

**Version of frigate**
0.8.4-5043040

**Config file**
Include your full config file wrapped in triple back ticks.
```
mqtt:
  host: 172.17.0.4
cameras:
  framsida:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://172.17.0.7:7447/5f04bbbae4b0a4695aeb1590_1
          roles:
            - detect
            - rtmp
        - path: rtsp://172.17.0.7:7447/5f04bbbae4b0a4695aeb1590_0
          roles:
            - clips
    width: 1024
    height: 576
    fps: 5
    motion:
      mask:
        - 0,21,162,21,162,0,0,0
    zones:  
      zone_0:
        coordinates: 176,576,884,576,1024,326,1024,78,755,0,537,0,0,246,0,331
    clips:
      # Required: enables clips for the camera (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of seconds before the event to include in the clips (default: shown below)
      pre_capture: 5
      # Optional: Number of seconds after the event to include in the clips (default: shown below)
      post_capture: 5
objects:
  track:
    - person
    - cat
clips:
  # Optional: Maximum length of time to retain video during long events. (default: shown below)
  # NOTE: If an object is being tracked for longer than this amount of time, the cache
  #       will begin to expire and the resulting clip will be the last x seconds of the event.
  max_seconds: 300
  # Optional: Retention settings for clips (default: shown below)
  retain:
    # Required: Default retention days (default: shown below)
    default: 10
    # Optional: Per object retention days
    objects:
      person: 20
detectors:
  coral:
    type: edgetpu
    device: usb
```

**Frigate container logs**
No event logged in Frigate container

**Home Assistant log**
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 98, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id"))
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 77, in async_browse_media
    return await _get_media_item(hass, media_content_id).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 79, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/frigate/media_source.py", line 125, in async_browse_media
    d['timestamp'] = int(DEFAULT_TIME_ZONE.localize(dt.datetime.strptime(d['day'], '%Y-%m-%d')).timestamp())
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'
```

**Computer Hardware**
 - OS: Synology
 - Install method: Docker Command
 - Coral Version: USB
 - Network Setup: Wired

**Comment by blakeblackshear** [comment]
See the changelog for the integration. There was a breaking change in home assistant.

**Comment by SebbeM** [comment]
Thanks for the quick reply. Sorry for not checking the changelogs properly before submitting!
