### ISSUE TITLE
Google Coral Dev Board EdgeTPU Not Detected

### ISSUE THREAD

**Issue by retrospectsecurity** [blakeblackshear/frigate#1389]
**Describe the bug**
edgetpu not detected on google coral dev board

**Version of frigate**
0.8.4-5043040

**Config file**
atabase:
  path: /media/frigate/frigate.db
detectors:
  coral:
    type: edgetpu
    device: pci
mqtt:
  host: 192.168.1.200
  port: 1883
  topic_prefix: frigate
  client_id: frigate

**Frigate container logs**
```
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0

```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
google linux build for coral deb board mini

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**

**Comment by retrospectsecurity** [comment]
nvm added '' as device

**Comment by pilievwm** [comment]
did you managed to enable the Coral Dev Board's TPU?
