### ISSUE TITLE
birdseye  crashed  processing loop

### ISSUE THREAD

**Issue by scooper1** [blakeblackshear/frigate#1429]
**Describe the bug**
birdseye crashed processing of camera streams

**Version of frigate**
version 9 running in docker 

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
config here
```

**Frigate container logs**
```
[2021-07-23 18:59:32] frigate.events                 DEBUG   : Event received: start f_front 1627063156.095146-tu3crs


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Cleaning up cached file f_doorbell-20210723185739.mp4


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Cleaning up cached file f_front-20210723185737.mp4


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Cleaning up cached file f_back-20210723185736.mp4


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Cleaning up cached file f_front-20210723185749.mp4


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Cleaning up cached file f_back-20210723185748.mp4


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Cleaning up cached file f_doorbell-20210723185748.mp4


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Event received: start f_back 1627063157.816176-fp314p


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Event received: end f_front 1627063156.095146-tu3crs


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Event received: start f_front 1627063164.342193-suybfq


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Event received: end f_back 1627063157.816176-fp314p


[2021-07-23 18:59:32] frigate.events                 DEBUG   : Event received: end f_front 1627063164.342193-suybfq


[2021-07-23 18:59:37] frigate.events                 DEBUG   : Event received: start f_back 1627063177.279034-xj8j09


[2021-07-23 18:59:37] frigate.events                 DEBUG   : Cleaning up cached file f_doorbell-20210723185757.mp4


[2021-07-23 18:59:38] frigate.events                 DEBUG   : Event received: start f_front 1627063177.956526-ov5ui3


[2021-07-23 18:59:40] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47880]


[2021-07-23 18:59:51] frigate.events                 DEBUG   : Event received: end f_front 1627063177.956526-ov5ui3


[2021-07-23 19:00:19] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:36656]


[2021-07-23 19:00:19] frigate.output                 DEBUG   : Changing layout size from 1 to 2


[2021-07-23 19:00:19] frigate.output                 DEBUG   : Clearing the birdseye frame


Process output_processor:


Traceback (most recent call last):


  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap


    self.run()


  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run


    self._target(*self._args, **self._kwargs)


  File "/opt/frigate/frigate/output.py", line 407, in output_frames


    if birdseye_manager.update(


  File "/opt/frigate/frigate/output.py", line 312, in update


    if self.update_frame() or (now - self.last_output_time) > 1:


  File "/opt/frigate/frigate/output.py", line 275, in update_frame


    self.copy_to_position(


  File "/opt/frigate/frigate/output.py", line 162, in copy_to_position


    frame = self.frame_manager.get(


  File "/opt/frigate/frigate/util.py", line 635, in get


    shm = shared_memory.SharedMemory(name=name)


  File "/usr/lib/python3.8/multiprocessing/shared_memory.py", line 102, in __init__


    self._fd = _posixshmem.shm_open(


FileNotFoundError: [Errno 2] No such file or directory: '/f_front1627060046.77826'


[2021-07-23 19:00:48] ws4py                          DEBUG   : Closing message received (1001) 'b'''


[2021-07-23 19:00:48] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47880]


[2021-07-23 19:00:48] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48468]


[2021-07-23 19:00:55] ws4py                          DEBUG   : Closing message received (1001) 'b'''


[2021-07-23 19:00:55] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48468]


```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: [e.g. Ubuntu, Windows]
 - Install method: [e.g. Addon, Docker Compose, Docker Command]
 - Virtualization: [e.g. Proxmox, Virtualbox]
 - Coral Version: [e.g. USB, PCIe, None]
 - Network Setup: [e.g. Wired, WiFi]

**Camera Info:**
 - Manufacturer: [e.g. Dahua]
 - Model: [e.g. IPC-HDW5231R-ZE]
 - Resolution: [e.g. 720p]
 - FPS: [e.g. 5]

**Additional context**

**Comment by blakeblackshear** [comment]
That's an old development commit for 0.9.0. This has already been fixed. There is a reason there are no published official builds yet. Thanks for reporting.

**Comment by scooper1** [comment]
FYI 
the docker image was palled only 4 days ago  from 9.0 so so should have had the birdseye fixes in it  unless there are more changes not updated yet
yep I understand its not ready for release yet

**Comment by blakeblackshear** [comment]
I don't have automated builds setup, so a build with the fix hasn't even been pushed.

**Comment by scooper1** [comment]
Ok my miss understanding I was thinking that it got pulled and built at time of requesting update of docker image  it seam to have the latest tabbed buttons
