### ISSUE TITLE
Browsing clips in HomeAssistant gives unknown error, AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'

### ISSUE THREAD

**Issue by paltskallen** [blakeblackshear/frigate#1460]
**Describe the bug**
Browsing clips in HA gives unknown error. Looking in HA logs shows:

```
2021-08-03 07:32:26 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139720213620480] Error handling message: Unknown error
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/media_source/__init__.py", line 98, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id"))
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/media_source/__init__.py", line 77, in async_browse_media
    return await _get_media_item(hass, media_content_id).async_browse()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/media_source/models.py", line 79, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/home/homeassistant/.homeassistant/custom_components/frigate/media_source.py", line 125, in async_browse_media
    d['timestamp'] = int(DEFAULT_TIME_ZONE.localize(dt.datetime.strptime(d['day'], '%Y-%m-%d')).timestamp())
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'
```

This has worked earlier, not sure when it stopped working

**Version of frigate**
0.8.4-5043040

**Config file**
```detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: -hide_banner -loglevel info

logger:
  default: error

objects:
  track:
    - person
    - car
    - dog
    - cat
    - motorcycle
    - bird
    - bicycle
  filters:
    person:
      min_area: 4000
      max_area: 100000
      threshold: 0.65

mqtt:
  host: ****

cameras:
  uppfart:
    ffmpeg:
      inputs:
        - path: rtsp://xx.zz@webcam1.lan/11
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 8
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      retain:
        default: 30
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: False
      retain_days: 30


  entre:
    ffmpeg:
      inputs:
        - path: rtsp://xx:zz@webcam5.lan:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 8
    motion:
      mask:
        - 561,111,672,91,754,275,466,359,352,161
        - 893,66,945,236,754,271,682,91
        - 1188,38,1200,193,909,195,882,55
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      retain:
        default: 30
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: False
      retain_days: 30


  garage:
    ffmpeg:
      inputs:
        - path: rtsp://xx:zz@webcam6.lan:554/11
          roles:
            - detect
            - rtmp
            - clips
    width: 1920
    height: 1080
    fps: 6
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      retain:
        default: 30
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 30
    record:
      enabled: False
      retain_days: 30

```

**Frigate container logs**
```
Nothing in the logs
2021-08-03T07:36:18.222542067Z  * Starting nginx nginx
2021-08-03T07:36:18.244501206Z    ...done.
2021-08-03T07:36:19.417866071Z Starting migrations
2021-08-03T07:36:19.418019469Z peewee_migrate                 INFO    : Starting migrations
2021-08-03T07:36:20.063847785Z There is nothing to migrate
2021-08-03T07:36:20.064011367Z peewee_migrate                 INFO    : There is nothing to migrate

```

**Frigate stats**
```j{
  "detection_fps": 0.2, 
  "detectors": {
    "coral": {
      "detection_start": 0.0, 
      "inference_speed": 90.26, 
      "pid": 29
    }
  }, 
  "entre": {
    "camera_fps": 7.9, 
    "capture_pid": 36, 
    "detection_fps": 0.0, 
    "pid": 32, 
    "process_fps": 7.9, 
    "skipped_fps": 0.0
  }, 
  "garage": {
    "camera_fps": 6.0, 
    "capture_pid": 37, 
    "detection_fps": 0.0, 
    "pid": 33, 
    "process_fps": 6.0, 
    "skipped_fps": 0.0
  }, 
  "service": {
    "storage": {
      "/dev/shm": {
        "free": 258.0, 
        "mount_type": "tmpfs", 
        "total": 268.4, 
        "used": 10.4
      }, 
      "/media/frigate/clips": {
        "free": 899727.8, 
        "mount_type": "nfs", 
        "total": 981402.3, 
        "used": 81674.5
      }, 
      "/media/frigate/recordings": {
        "free": 899727.8, 
        "mount_type": "nfs", 
        "total": 981402.3, 
        "used": 81674.5
      }, 
      "/tmp/cache": {
        "free": 1036.9, 
        "mount_type": "tmpfs", 
        "total": 1073.7, 
        "used": 36.8
      }
    }, 
    "uptime": 55, 
    "version": "0.8.4-5043040"
  }, 
  "uppfart": {
    "camera_fps": 8.1, 
    "capture_pid": 34, 
    "detection_fps": 0.2, 
    "pid": 31, 
    "process_fps": 8.1, 
    "skipped_fps": 0.0
  }
}
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: Ubuntu 20.04.2
 - Install method: docker
 - Virtualization: Proxmox
 - Coral Version: USB
 - Network Setup: Wired

**Additional context**

**Comment by paltskallen** [comment]
Ahh, yes it works much better after an update. Thanks
