### ISSUE TITLE
Green screen 

### ISSUE THREAD

**Issue by dnit71** [blakeblackshear/frigate#1597]
Hello,
I just get a green screen. I tried resolv the pb with the others issues opened  dealing with the same problem in vain. I tried with and without hardware accelaration  When I click on the camera I get indefinitely :
![image](https://user-images.githubusercontent.com/75902107/130592279-d4ef3529-9637-4e74-8557-c143c12d9561.png)

Below my configuration and the logs :

config.yml

```mqtt:
  host: 192.168.2.12
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
   Camera1:
    ffmpeg:
      global_args: -hide_banner -loglevel info
      inputs:
        - path: rtsp://admin:****@192.168.3.18/onvif1
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    objects:
      track:
        - person
        - car
```

debug
```
mqtt:
  host: 192.168.2.12
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
 # Name of your camera
  Camera1:
    ffmpeg:
      global_args: -hide_banner -loglevel info
      inputs:
        - path: rtsp://admin:*****@192.168.3.18/onvif1
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    objects:
      track:
        - person
        - car
```

docker logs frigate
```
 * Starting nginx nginx
   ...done.
frigate.app                    WARNING : Camera Camera1 has clips assigned to an input, but clips is not enabled.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
detector.coral                 INFO    : Starting detection process: 32
frigate.app                    INFO    : Camera processor started for Camera1: 35
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.app                    INFO    : Capture process started for Camera1: 37
Process detector:coral:
frigate.edgetpu                INFO    : No EdgeTPU detected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0

frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
ffmpeg.Camera1.detect          ERROR   : [rtsp @ 0x24d8700] Nonmatching transport in server reply
ffmpeg.Camera1.detect          ERROR   : rtsp://admin:****@192.168.3.18/onvif1: Invalid data found when processing input
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
```

I tested the stream with vlc and it works well. I increase the gpu mem to 128Mo.
thank you

**Comment by Sinamics** [comment]
Try adding a detector
https://blakeblackshear.github.io/frigate/configuration/detectors

```yaml
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

**Comment by dnit71** [comment]
Now the camera open immediately when I click on but the screen is still green 

logs 
```
ffmpeg.Camera1.detect          ERROR   : [rtsp @ 0xf74700] Nonmatching transport in server reply
ffmpeg.Camera1.detect          ERROR   : rtsp://admin:****@192.168.3.18/onvif1: Invalid data found when processing input
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
```

Debug

```
{
  "cameras": {
    "Camera1": {
      "best_image_timeout": 60,
      "clips": {
        "enabled": false,
        "objects": null,
        "post_capture": 5,
        "pre_capture": 5,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        }
      },
      "detect": {
        "enabled": true,
        "max_disappeared": 25
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel info -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:admin@192.168.3.18/onvif1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Camera1-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/Camera1 -r 5 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "rtmp",
            "clips"
          ]
        }
      ],
      "fps": 5,
      "frame_shape": [
        720,
        1280
      ],
      "height": 720,
      "motion": {
        "contour_area": 100,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 120,
        "mask": null,
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "required_zones": [],
        "timestamp": true
      },
      "name": "Camera1",
      "objects": {
        "filters": {
          "car": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": [],
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          }
        },
        "mask": null,
        "track": [
          "person",
          "car"
        ]
      },
      "record": {
        "enabled": false,
        "retain_days": 30
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": false,
        "crop": false,
        "enabled": false,
        "height": null,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": false
      },
      "width": 1280,
      "zones": {}
    }
  },
  "clips": {
    "max_seconds": 300,
    "retain": {
      "default": 10,
      "objects": {}
    },
    "tmpfs_cache_size": ""
  },
  "database": {
    "path": "/media/frigate/clips/frigate.db"
  },
  "detectors": {
    "cpu1": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    },
    "cpu2": {
      "device": "usb",
      "num_threads": 3,
      "type": "cpu"
    }
  },
  "environment_vars": {},
  "logger": {
    "default": "INFO",
    "logs": {}
  },
  "model": {
    "height": 320,
    "width": 320
  },
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.2.12",
    "port": 1883,
    "stats_interval": 60,
    "topic_prefix": "frigate",
    "user": null
  },
  "snapshots": {
    "retain": {
      "default": 10,
      "objects": {}
    }
  }
}
```

**Comment by Sinamics** [comment]
Verify that your resolution and fps is 100% correct. 
Open the rtsp stream in vlc and open view => codec info and use the same height / width / fps  in frigate

```yaml
width: 1280
height: 720
fps: 5
```

**Comment by blakeblackshear** [comment]
> rtsp://admin:****@192.168.3.18/onvif1: Invalid data found when processing input

The logs say your input path has invalid data. Post the ffprobe output of that url.

**Comment by dnit71** [comment]
@Sinamics I already check with vlc and the configuration is good.
@blakeblackshear below the output of ffprobe:

````
ffprobe rtsp://admin:****@192.168.3.18/onvif1
ffprobe version 4.1.6-1~deb10u1+rpt2 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm
  WARNING: library configuration mismatch
  avutil      configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avcodec     configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avformat    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avdevice    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avfilter    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avresample  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swscale     configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swresample  configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  postproc    configuration: --prefix=/usr --extra-version='1~deb10u1+rpt2' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-vout-drm --enable-v4l2-request --enable-libudev --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[rtsp @ 0x79ca00] max delay reached. need to consume packet
[rtsp @ 0x79ca00] RTP: missed 46 packets
[h264 @ 0x79fbb0] corrupted macroblock 62 39 (total_coeff=-1)
[h264 @ 0x79fbb0] error while decoding MB 62 39
[h264 @ 0x79fbb0] concealing 467 DC, 467 AC, 467 MV errors in P frame
[rtsp @ 0x79ca00] max delay reached. need to consume packet
[rtsp @ 0x79ca00] RTP: missed 7 packets
[h264 @ 0x79fbb0] corrupted macroblock 11 20 (total_coeff=-1)
[h264 @ 0x79fbb0] error while decoding MB 11 20
[h264 @ 0x79fbb0] concealing 2038 DC, 2038 AC, 2038 MV errors in P frame
Input #0, rtsp, from 'rtsp://admin:admin@192.168.3.18/onvif1':
  Metadata:
    title           : H.264 Video, RtspServer_0.0.0.2
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Baseline), yuv420p(progressive), 1280x720, 20 tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
``

**Comment by blakeblackshear** [comment]
A quick Google search for the other error message (`Nonmatching transport in server reply`) suggests that your camera might not support tcp for rtsp connections. See if there is a setting on the camera or a separate url for TCP connections. If not, you can modify the input_args to use UDP, but that comes with packet loss issues typically.

**Comment by dnit71** [comment]
I checked my camera and the port TCP/554 is open. But I try to add udp to inputs_args and I get theses errors:
```
ffmpeg.Camera1.detect          ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
ffmpeg.Camera1.detect          ERROR   :     Stream #0:0: Video: h264, yuv420p(progressive), 1280x720, 90k tbr, 90k tbn, 180k tbc
ffmpeg.Camera1.detect          ERROR   :     Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
ffmpeg.Camera1.detect          ERROR   : [NULL @ 0xf525a0] Unable to find a suitable output format for 'UDP'
ffmpeg.Camera1.detect          ERROR   : UDP: Invalid argument
frigate.video                  INFO    : Camera1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
frigate.video                  INFO    : Camera1: ffmpeg process is not running. exiting capture thread...
ffmpeg.Camera1.detect          ERROR   : [udp @ 0x15f8590] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.Camera1.detect          ERROR   : [udp @ 0x1608900] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.Camera1.detect          ERROR   : [udp @ 0x16194c0] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.Camera1.detect          ERROR   : [udp @ 0x1619210] attempted to set receive buffer to size 393216 but it only ended up set as 360448
ffmpeg.Camera1.detect          ERROR   : [rtsp @ 0x15f36a0] decoding for stream 0 failed
ffmpeg.Camera1.detect          ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
ffmpeg.Camera1.detect          ERROR   : Input #0, rtsp, from 'rtsp://admin:admin@192.168.3.18/onvif1':
ffmpeg.Camera1.detect          ERROR   :   Metadata:
ffmpeg.Camera1.detect          ERROR   :     title           : H.264 Video, RtspServer_0.0.0.2
ffmpeg.Camera1.detect          ERROR   :   Duration: N/A, start: 0.000000, bitrate: N/A
ffmpeg.Camera1.detect          ERROR   :     Stream #0:0: Video: h264, yuv420p(progressive), 1280x720, 90k tbr, 90k tbn, 180k tbc
ffmpeg.Camera1.detect          ERROR   :     Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s
ffmpeg.Camera1.detect          ERROR   : [NULL @ 0x16531a0] Unable to find a suitable output format for 'UDP'
ffmpeg.Camera1.detect          ERROR   : UDP: Invalid argument
````
below my config.yml:
```mqtt:
  host: 192.168.2.12
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
 # Name of your camera
  Camera1:
    ffmpeg:
      input_args:
        - UDP
      global_args: -hide_banner -loglevel info
      inputs:
        - path: rtsp://admin:admin@192.168.3.18/onvif1
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    objects:
      track:
        - person
        - car
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
``
I surely made a mistake somewhere...

**Comment by dnit71** [comment]
Ok I add it ti global_args but I see the two rtsp_transport arguments udp and tcp in the ffmpeg command:
```
"ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel info **-rtsp_transport udp** -c:v h264_v4l2m2m -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt **-rtsp_transport tcp** -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:****@192.168.3.18/onvif1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Camera1-%Y%m%d%H%M%S.mp4 -c copy -f flv rtmp://127.0.0.1/live/Camera1 -r 5 -f rawvideo -pix_fmt yuv420p pipe:",
```
I tested to run the command without the argument -rtsp_transport tcp and it seems to work ( no errors). 

config.yml:
```
mqtt:
  host: 192.168.2.12
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
cameras:
 # Name of your camera
  Camera1:
    ffmpeg:
      global_args: -hide_banner -loglevel info -rtsp_transport udp
      inputs:
        - path: rtsp://admin:*****@192.168.3.18/onvif1
          roles:
            - detect
            - rtmp
            - clips
    width: 1280
    height: 720
    fps: 5
    objects:
      track:
        - person
        - car
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

**Comment by lawm** [comment]
> Ok I added it ti global_args but I see the two rtsp_transport arguments udp and tcp in the ffmpeg command:

Change input_args, not global args

See defaults here

https://github.com/blakeblackshear/frigate/blob/42410a260cba711c6362d3433342ea8941b46e30/frigate/config.py#L66-L71


FYI make sure you copy/modify the default input_args, because your config will completely replace it.

**Comment by dnit71** [comment]
ok I added correctly input_args and it works now. Thank you
```
 Camera1:
    ffmpeg:
      input_args: -rtsp_transport udp
      global_args: -hide_banner -loglevel info
```
