### ISSUE TITLE
 No EdgeTPU detected - I installed in Google Board and have this error

### ISSUE THREAD

**Issue by vienkmt** [blakeblackshear/frigate#1718]
**Describe the bug**
frigate.edgetpu                INFO    : No EdgeTPU detected.

**Version of frigate**
0.9

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
mqtt:
  host: broker.mqttdashboard.com
cameras:
  Xuong:
    ffmpeg:
      inputs:
        - path: rtsp://admin:133@192.168.1.36:554/cam/realmonitor?channel=5&subtype=1
          roles:
            - detect
    width: 704
    height: 576
    fps: 15
    snapshots:
      enabled: True
      bounding_box: True

  SX:
    ffmpeg:
      inputs:
        - path: rtsp://admin:123@192.168.1.36:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    width: 704
    height: 576
    fps: 15
    snapshots:
      enabled: True
      bounding_box: True

detectors:
  coral:
    type: edgetpu
 ```

**Frigate container logs**
```
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

**Frigate stats**
```json
Output from frigate's /api/stats endpoint
```

**FFprobe from your camera**

Run the following command and paste output below
```
ffprobe <stream_url>
```

**Screenshots**

**Computer Hardware**
 - OS: Mendel
 - Install method: Docker Command
 - Virtualization: 
 - Coral Version: Coral Board
 - Network Setup: Wired

**Camera Info:**
 - Manufacturer: Dahua
 - Model:  IPC-HDW5231R-ZE
 - Resolution: 706
 - FPS: 15

**Additional context**

**Comment by vienkmt** [comment]
Updated
It worked by this way https://github.com/blakeblackshear/frigate/issues/1434#issuecomment-886249488
cmd
`docker run -d --name frigate --restart=unless-stopped --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --device /dev/apex_0:/dev/apex_0 -v /home/coral/fr:/frigate:ro -v /home/mendel/fr/config.yml:/config/config.yml:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:stable-aarch64`

config yml

`detectors:
  coral:
    type: edgetpu
    device: ''`

**Comment by ozett** [comment]
i updated my coral-dev board and tried to run with your cmd the frigate-container, 

but got a docker error.  any hints on this?

does this come from the container - or from my dev-board docker?

```docker: Error response from daemon: unable to find "net_cls" in controller set: unknown.```

```
root@elusive-calf:/usr/src# docker run --name frigate --restart=unless-stopped --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --device /dev/apex_0:/dev/apex_0 -v /usr/src/media:/frigate:ro -v /usr/src/frigate09.yml:/config/config.yml:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:stable-aarch64
docker: Error response from daemon: unable to find "net_cls" in controller set: unknown.
ERRO[0001] error waiting for container: context canceled
root@elusive-calf:/usr/src# docker -v
Docker version 18.09.1, build 4c52b90
root@elusive-calf:/usr/src# docker-compose -v
docker-compose version 1.21.0, build unknown
root@elusive-calf:/usr/src# cat /etc/mendel_version
5.2

```

**Comment by ozett** [comment]
i updated docker on the dev-board and now the error comes possibly from nginx in the containter:
``` 
root@elusive-calf:/usr/src# docker -v && docker-compose -v
Docker version 20.10.10, build b485636
docker-compose version 1.21.0, build unknown
root@elusive-calf:/usr/src# docker run --name frigate --restart=unless-stopped --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --device /dev/apex_0:/dev/apex_0 -v /usr/src/media:/frigate:ro -v /usr/src/frigate09.yml:/config/config.yml:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:stable-aarch64
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] mmap(MAP_ANON|MAP_SHARED, 536870912) failed (12: Cannot allocate memory)
nginx: [alert] munmap(FFFFFFFFFFFFFFFF, 536870912) failed (22: Invalid argument)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
root@elusive-calf:/usr/src#
```

**Comment by ozett** [comment]
running frigate 0.8.4 seems ok, i can confirm https://github.com/blakeblackshear/frigate/issues/1706
on 0.8.x no Dockerfile.nginx -> 
https://github.com/blakeblackshear/frigate/tree/v0.8.4/docker

but from frigate 0.9.x  there seems a break for nginx-config:
https://github.com/blakeblackshear/frigate/blob/v0.9.0-beta1/docker/Dockerfile.nginx

```
root@elusive-calf:/usr/src# docker run -m 1024m --privileged --shm-size=512M --name frigate --restart=unless-stopped --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --device /dev/apex_0:/dev/apex_0 -v /usr/src/media:/frigate:ro -v /usr/src/frigate09.yml:/config/config.yml:ro -v /etc/localtime:/etc/localtime:ro -p 5000:5000 -p 1935:1935 blakeblackshear/frigate:0.8.4-aarch64
Unable to find image 'blakeblackshear/frigate:0.8.4-aarch64' locally
0.8.4-aarch64: Pulling from blakeblackshear/frigate
19d658f3801a: Pull complete
28bdea3dddb1: Pull complete
8ae0c92402f4: Pull complete
9e087c2892df: Pull complete
0ee454ab5224: Pull complete
597dae287da6: Pull complete
f0070fb3ea3b: Pull complete
95894a9d2b2f: Pull complete
b7bd8a0601c5: Pull complete
4e94a65d99fc: Pull complete
3ed73e4c8d60: Pull complete
9348b9a85f39: Pull complete
5031924a8fb2: Pull complete
1f04d5b747f1: Pull complete
e954c603e6b2: Pull complete
1b427d8ac186: Pull complete
c7319127af30: Pull complete
2fba76b63b6b: Pull complete
Digest: sha256:a3b4abf13a7b0dd4d65e90f57218d15179ae1c4252f2adc8c0cc5587244320af
Status: Downloaded newer image for blakeblackshear/frigate:0.8.4-aarch64
 * Starting nginx nginx
   ...done.
Error parsing config: extra keys not allowed @ data['birdseye']
root@elusive-calf:/usr/src#
```

**Comment by ozett** [comment]
still trying to increase memory on the coral-dev board.  
maybe memory limit on the dev-board is causing nginx-error ??
hoping to catch this without the help of others...
but as a blind-man in the dark:

```
root@elusive-calf:/usr/src# ipcs -l

------ Messages Limits --------
max queues system wide = 32000
max size of message (bytes) = 8192
default max size of queue (bytes) = 16384

------ Shared Memory Limits --------
max number of segments = 4096
max seg size (kbytes) = 18014398509465599
max total shared memory (kbytes) = 18014398509481980
min seg size (bytes) = 1

------ Semaphore Limits --------
max number of arrays = 32000
max semaphores per array = 32000
max semaphores system wide = 1024000000
max ops per semop call = 500
semaphore max value = 32767
```

**Comment by limx59** [comment]
how to fix the issue that docker: Error response from daemon: unable to find "net_cls" in controller set: unknown.?

Thanks
