### ISSUE TITLE
Crashes after some time with OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by srirams** [blakeblackshear/frigate#177]
After a day or two, frigate crashes with this error:

```ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://live555proxyserverdocker/proxyStream-1 -f rawvideo -pix_fmt rgb24 pipe:,
Detection appears to be stuck. Restarting detection process,
Waiting for detection process to exit gracefully...,
Starting detection process: 3299,
No EdgeTPU detected. Falling back to CPU.,
No frames received from entrance_camera in 5 seconds. Exiting ffmpeg...,
Waiting for ffmpeg to exit gracefully...,
Exception in thread entrance_camera:,
Traceback (most recent call last):,
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner,
    self.run(),
  File "/opt/frigate/frigate/video.py", line 141, in run,
    frame_bytes = self.ffmpeg_process.stdout.read(self.frame_size),
ValueError: read of closed file,
,
eating ffmpeg process...,
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://live555proxyserverdocker/proxyStream-1 -f rawvideo -pix_fmt rgb24 pipe:,
No frames received from entrance_camera in 5 seconds. Exiting ffmpeg...,
Waiting for ffmpeg to exit gracefully...,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg process is not running. exiting capture thread...,
eating ffmpeg process...,
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://live555proxyserverdocker/proxyStream-1 -f rawvideo -pix_fmt rgb24 pipe:,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg didnt return a frame. something is wrong.,
entrance_camera: ffmpeg process is not running. exiting capture thread...,
eating ffmpeg process...,
ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -vsync drop -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://live555proxyserverdocker/proxyStream-1 -f rawvideo -pix_fmt rgb24 pipe:,
Exception in thread Thread-5:,
Traceback (most recent call last):,
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner,
    self.run(),
  File "detect_objects.py", line 126, in run,
    ffmpeg_process = start_or_restart_ffmpeg(camera_process['ffmpeg_cmd'], frame_size),
  File "/opt/frigate/frigate/video.py", line 114, in start_or_restart_ffmpeg,
    process = sp.Popen(ffmpeg_cmd, stdout = sp.PIPE, stdin = sp.DEVNULL, bufsize=frame_size*10, start_new_session=True),
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__,
    restore_signals, start_new_session),
  File "/usr/lib/python3.7/subprocess.py", line 1441, in _execute_child,
    errpipe_read, errpipe_write = os.pipe(),
OSError: [Errno 24] Too many open files,```

**Comment by blakeblackshear** [comment]
Closing. If this is still an issue with 0.7.0, please reopen.
