### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by twochannel** [blakeblackshear/frigate#18]
I recently switched models to improve processing time. I was not seeing object %'s like I should be seeing based on the bounding boxes.  I changed from faster_rcnn_inception_v2_coco_2018_01_28 to ssd_mobilenet_v2_coco_2018_03_29 and I now get the error below.  Some times the error happens right away, some times it will work fine for a bit and then error out.

I'm using mscoco_label_map.pbtxt label map

I've done some research on the models but still don't quite have a great grasp on the differences other than mobilenet requires less resources.  The error only occurs on  the image built from github.  Your image on dockerhub does not do this with either model.

My docker run command is 
```
docker run --rm  --name frigate \
-v /mnt/nfs/frigate/faster_rcnn_inception_v2_coco_2018_01_28/frozen_inference_graph.pb:/frozen_inference_graph.pb:ro \
-v /mnt/nfs/frigate/mscoco_complete_label_map.pbtxt:/label_map.pbtext:ro \
-v /mnt/nfs/frigate/config:/config:ro \
-v /mnt/hassio/config/frigatedebug:/lab/debug \
-p 5000:5000 \
-e RTSP_URL='rtsp://192.168.z.z:8554/unicast' \
-e REGIONS='460,50,50,5000,500,nomask.bmp' \
-e MQTT_HOST='192.168.z.zz' \
-e MQTT_TOPIC_PREFIX='cameras/1' \
-e DEBUG='0' \
blakeblackshear/frigate

camera resolution is 960x540, nomask.bmp is a white image.
```
Let me know if you need any additional info.
Thanks,

```
On connect called
capture_process pid  34
detection_process pid  35
motion_process pid  36
 * Serving Flask app "detect_objects" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-03-23 19:06:54.949810: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2098550000 Hz
2019-03-23 19:06:54.951714: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0xcdc0c50 executing computations on platform Host. Devices:
2019-03-23 19:06:54.951798: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-23 19:06:58.593049: W ./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0
2019-03-23 19:07:00.693914: W ./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/object_detection.py", line 108, in detect_objects
    objects = tf_detect_objects(cropped_frame_rgb, sess, detection_graph, region_size, region_x_offset, region_y_offset, debug)
  File "/opt/frigate/frigate/object_detection.py", line 62, in tf_detect_objects
    'name': str(category_index.get(value).get('name')),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by blakeblackshear** [comment]
That error means the detected object from the model was not in the label map. Somehow you have a mismatch between those two files. I am using the same model.

**Comment by twochannel** [comment]
What is odd is I do not get the error when using your docker hub image, only when using the image built from github.  I can try to rebuild from source, I see from the 0.1.0 release it requires coral for now?

I've tried both the complete and non complete label maps. Should either work?

**Comment by blakeblackshear** [comment]
I would think so. Did you build the container from the v0.0.1 release version of the code? Maybe the commit you have checked out has a bug.

**Comment by twochannel** [comment]
I thought I merged after the mqtt user/pass support commit. I just rebuilt from v0.0.1 tag and it seems better now.   Thanks!
