### ISSUE TITLE
EdgeTPU not recognized on updated docker image (frigate:0.9.0-rc5-amd64)

### ISSUE THREAD

**Issue by ipd-otto** [blakeblackshear/frigate#1890]
**Describe the bug**
After (accidently) updating to the latest docker image (frigate:0.9.0-rc5-amd64) the edge-tpu stopped working. I've updated the config for one camera according to the new docs and took the rest offline.
The docker container has the /dev/apex_0 passed through which worked on the older image before. Unfortunately I'm not sure, which version the previous container had.

**Version of frigate**
0.9.0-aa807d2

**Config file**
Include your full config file wrapped in triple back ticks.
```detectors:
#  cpu1:
#    type: cpu
  coral1:
    type: edgetpu
    device: pci:0
```

**Frigate container logs**
```[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2021-09-30 14:16:26] frigate.app                    INFO    : Starting Frigate (0.9.0-aa807d2),
Starting migrations,
[2021-09-30 14:16:26] peewee_migrate                 INFO    : Starting migrations,
There is nothing to migrate,
[2021-09-30 14:16:26] peewee_migrate                 INFO    : There is nothing to migrate,
[2021-09-30 14:16:26] frigate.mqtt                   INFO    : MQTT connected,
[2021-09-30 14:16:26] detector.coral1                INFO    : Starting detection process: 225,
[2021-09-30 14:16:26] frigate.app                    INFO    : Output process started: 227,
[2021-09-30 14:16:26] frigate.edgetpu                INFO    : Attempting to load TPU as pci:0,
Process detector:coral1:,
[2021-09-30 14:16:26] ws4py                          INFO    : Using epoll,
[2021-09-30 14:16:26] frigate.app                    INFO    : Camera processor started for terrasse-eg: 232,
[2021-09-30 14:16:26] frigate.app                    INFO    : Capture process started for terrasse-eg: 236,
[2021-09-30 14:16:26] ws4py                          INFO    : Using epoll,
[2021-09-30 14:16:39] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.,
Traceback (most recent call last):,
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate,
    delegate = Delegate(library, options),
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__,
    raise ValueError(capture.message),
ValueError,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap,
    self.run(),
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run,
    self._target(*self._args, **self._kwargs),
  File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector,
    object_detector = LocalObjectDetector(,
  File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__,
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config),
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate,
    raise ValueError('Failed to load delegate from {}\n{}'.format(,
ValueError: Failed to load delegate from libedgetpu.so.1.0,
,
[2021-09-30 14:16:46] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
```

**Frigate stats**
```
{"detection_fps":0.0,"detectors":{"coral1":{"detection_start":0.0,"inference_speed":10.0,"pid":225}},"service":{"storage":{"/dev/shm":{"free":58.7,"mount_type":"tmpfs","total":67.1,"used":8.4},"/media/frigate/clips":{"free":1315638.2,"mount_type":"ext4","total":1965559.2,"used":550004.5},"/media/frigate/recordings":{"free":1315638.2,"mount_type":"ext4","total":1965559.2,"used":550004.5},"/tmp/cache":{"free":990.6,"mount_type":"tmpfs","total":1000.0,"used":9.4}},"uptime":10,"version":"0.9.0-aa807d2"},"terrasse-eg":{"camera_fps":4.8,"capture_pid":236,"detection_fps":0.0,"pid":232,"process_fps":4.66,"skipped_fps":0.0}}
```

**Additional context**
I've checked the image for pci-devices via lspci with the device being found:

```
root@11401144e4d6:/opt/frigate# lspci -nn | grep 'Coral'
04:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
```

To be sure it's pci:0 I also tried:

```
root@11401144e4d6:/opt/frigate# lspci -s 0 -nn | grep 'Coral'
04:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
```

**Comment by blakeblackshear** [comment]
What version were you on before? Can you post your entire config?

**Comment by ipd-otto** [comment]
Finally I was able to track down the problem: 
I tried running one of the example programs from Coral, which threw an error, too. Even after a restart this did not work.
So I had to plug the whole server off the power, re-set everything while holding power for 10 seconds and then start up again. TPU was recognized by the host as well as the container and is now running fine again.
