### ISSUE TITLE
Regression between 0.9.0-rc6 and 0.9.0-stable

### ISSUE THREAD

**Issue by adampetrovic** [blakeblackshear/frigate#1921]
### Describe the problem you are having

Camera streams aren't loading via the WebUI when upgrading to the `stable-amd64` or `0.9.0-amd64` docker images.

No configuration changes have occurred between the two versions. When reverting back to `0.9.0-rc6-amd64` everything works as expected.

stable / 0.9.0 - https://i.ibb.co/prF6qVX/not-working.png (blurred for privacy)

0.9.0-rc6 - https://i.ibb.co/cCg2L3x/working.png (blurred for privacy)

In stable / 0.9.0 none of the camera stream's live view loads a video.

### Version

0.9.0

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

mqtt:
  host: hass.<redacted>.network
  port: 1883
  user: ''
  password: ''
  topic_prefix: frigate

cameras:
  side_walkway:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.55:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.55:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.22.30:554/live0
          roles:
            - detect
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  front_balcony:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.59:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.59:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 128,0,133,138,262,117,307,134,553,254,317,383,407,480,0,480,0,0
        person:
          mask:
            - 640,0,640,79,41,42,59,277,85,480,0,480,0,0
            - 146,0,640,0,640,164
    zones:
      front_door:
        coordinates: 137,234,168,229,221,341,377,480,118,480,98,426,81,389,73,317,53,187,46,54,128,39
      driveway:
        coordinates: 640,480,411,480,317,387,490,289,640,375
      parking_space:
        coordinates: 640,254,640,302,454,198,365,156,413,140,503,182
        filters:
          car:
            threshold: 0.8
    motion:
      mask:
        - 640,209,640,0,0,0,0,62,132,133,223,123,268,141,349,144,415,109
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        required_zones: ['front_door', 'driveway']
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      required_zones: ['front_door', 'driveway']
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
      required_zones: ['front_door', 'driveway', 'parking_space']
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.58:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.58:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
      filters:
        car:
          mask:
            - 127,80,284,81,315,114,367,131,640,416,640,480,0,480,0,98
    zones:
      driveway:
        coordinates: 509,154,640,291,640,363,616,402,553,326,504,265,489,266,427,193,387,153
      walkway:
        coordinates: 640,412,571,480,515,480,350,230,369,213,409,185
      front_grass:
        coordinates: 182,142,354,134,399,178,396,201,349,225,445,370,497,480,0,480,0,175
      parking_space:
        coordinates: 202,0,377,35,391,93,206,75,65,81,0,86,0,0
        filters:
          car:
            threshold: 0.8
    motion:
      mask:
        - 109,76,301,75,414,88,381,0,640,0,640,158,514,140,473,141,466,155,381,142,371,132,351,132,332,132,280,132,177,136,108,145,0,161,0,84
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        required_zones: ['walkway', 'driveway', 'front_grass']
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      required_zones: ['walkway', 'driveway', 'front_grass']
    mqtt:
      enabled: True
      timestamp: False
      crop: False
      required_zones: ['walkway', 'driveway', 'front_grass']
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.54:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.54:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
    zones:
      driveway:
        coordinates: 431,21,547,47,521,136,451,102,397,86
      parking_space: 
        coordinates: 334,92,512,151,490,284,210,157
      gym:
        coordinates: 160,480,534,480,541,452,178,249,107,295
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  office:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.53:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.53:554/Streaming/Channels/101/
          roles:
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  backyard:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.56:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.56:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  back_deck:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.57:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.57:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  utilities:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.52:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.52:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  laundry:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.61:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://frigate:{FRIGATE_RTSP_PASSWORD}@10.0.50.61:554/Streaming/Channels/101/
          roles:
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - dog
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:<redacted>@10.0.50.50:554/Streaming/Channels/102/
          roles:
            - detect
        - path: rtsp://admin:<redacted>@10.0.50.50:554/Streaming/Channels/101/
          roles:
            - record
            - rtmp
    detect:
      width: 704
      height: 576
      fps: 5
    objects:
      track:
        - person
        - dog
    record:
      enabled: True
      retain_days: 0
      events:
        pre_capture: 5
        post_capture: 1
        retain:
          default: 14
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
    mqtt:
      enabled: True
      timestamp: False
      crop: False
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-10-06 10:48:36] frigate.app                    INFO    : Starting Frigate (0.9.0-c492b30)
[2021-10-06 10:48:36] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-10-06 10:48:36] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-10-06 10:48:36] peewee_migrate                 INFO    : There is nothing to migrate
[2021-10-06 10:48:36] frigate.mqtt                   INFO    : MQTT connected
[2021-10-06 10:48:36] frigate.app                    INFO    : Output process started: 217
[2021-10-06 10:48:36] detector.coral                 INFO    : Starting detection process: 216
Process output_processor:
[2021-10-06 10:48:36] ws4py                          INFO    : Using epoll
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for side_walkway: 223
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for living_room: 226
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for front_balcony: 227
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for front_yard: 230
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for garage: 231
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for office: 233
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for backyard: 234
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for back_deck: 236
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for utilities: 237
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for laundry: 238
[2021-10-06 10:48:36] frigate.app                    INFO    : Camera processor started for doorbell: 239
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for side_walkway: 241
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for living_room: 242
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for front_balcony: 244
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for front_yard: 246
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for garage: 258
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for office: 261
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for backyard: 262
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for back_deck: 264
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for utilities: 267
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for laundry: 269
Traceback (most recent call last):
[2021-10-06 10:48:36] frigate.app                    INFO    : Capture process started for doorbell: 272
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/output.py", line 389, in output_frames
    birdseye_manager = BirdsEyeFrameManager(config, frame_manager)
  File "/opt/frigate/frigate/output.py", line 112, in __init__
    transparent_layer = frigate_logo[:, :, 3]
IndexError: index 3 is out of bounds for axis 2 with size 3
[2021-10-06 10:48:36] ws4py                          INFO    : Using epoll
[2021-10-06 10:48:36] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-10-06 10:48:39] frigate.edgetpu                INFO    : TPU found
[2021-10-06 10:48:56] ffmpeg.front_yard.record_rtmp  ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2021-10-06 10:48:56] ffmpeg.front_yard.record_rtmp  ERROR   : [flv @ 0x5574f8224ec0] Failed to update header with correct duration.
[2021-10-06 10:48:56] ffmpeg.front_yard.record_rtmp  ERROR   : [flv @ 0x5574f8224ec0] Failed to update header with correct filesize.
[2021-10-06 10:48:56] ffmpeg.front_yard.record_rtmp  ERROR   : Error writing trailer of rtmp://127.0.0.1/live/front_yard: Connection reset by peer
[2021-10-06 10:48:56] watchdog.front_yard            INFO    : Terminating the existing ffmpeg process...
[2021-10-06 10:48:56] watchdog.front_yard            INFO    : Waiting for ffmpeg to exit gracefully...
[2021-10-06 10:48:56] ffmpeg.back_deck.record_rtmp   ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2021-10-06 10:48:56] ffmpeg.back_deck.record_rtmp   ERROR   : [flv @ 0x560a63ca4ec0] Failed to update header with correct duration.
[2021-10-06 10:48:56] ffmpeg.back_deck.record_rtmp   ERROR   : [flv @ 0x560a63ca4ec0] Failed to update header with correct filesize.
[2021-10-06 10:48:56] ffmpeg.back_deck.record_rtmp   ERROR   : Error writing trailer of rtmp://127.0.0.1/live/back_deck: Connection reset by peer
[2021-10-06 10:48:56] watchdog.back_deck             INFO    : Terminating the existing ffmpeg process...
[2021-10-06 10:48:56] watchdog.back_deck             INFO    : Waiting for ffmpeg to exit gracefully...
[2021-10-06 10:48:56] ffmpeg.backyard.record_rtmp    ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2021-10-06 10:48:56] ffmpeg.backyard.record_rtmp    ERROR   : [flv @ 0x55f0cbe32200] Failed to update header with correct duration.
[2021-10-06 10:48:56] ffmpeg.backyard.record_rtmp    ERROR   : [flv @ 0x55f0cbe32200] Failed to update header with correct filesize.
[2021-10-06 10:48:56] ffmpeg.backyard.record_rtmp    ERROR   : Error writing trailer of rtmp://127.0.0.1/live/backyard: Connection reset by peer
[2021-10-06 10:48:56] watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
[2021-10-06 10:48:56] watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully...
[2021-10-06 10:49:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:40336]
[2021-10-06 10:49:06] ffmpeg.front_yard.record_rtmp  ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2021-10-06 10:49:06] ffmpeg.front_yard.record_rtmp  ERROR   : [flv @ 0x55d581c31140] Failed to update header with correct duration.
[2021-10-06 10:49:06] ffmpeg.front_yard.record_rtmp  ERROR   : [flv @ 0x55d581c31140] Failed to update header with correct filesize.
[2021-10-06 10:49:06] ffmpeg.front_yard.record_rtmp  ERROR   : Error writing trailer of rtmp://127.0.0.1/live/front_yard: Connection reset by peer
[2021-10-06 10:49:06] watchdog.front_yard            INFO    : Terminating the existing ffmpeg process...
[2021-10-06 10:49:06] watchdog.front_yard            INFO    : Waiting for ffmpeg to exit gracefully...
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : [segment @ 0x55f50f4d1a40] Non-monotonous DTS in output stream 0:0; previous: 6030, current: 6030; changing to 6031. This may result in incorrect timestamps in the output file.
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : [segment @ 0x55f50f4d1a40] Non-monotonous DTS in output stream 0:0; previous: 6031, current: 6031; changing to 6032. This may result in incorrect timestamps in the output file.
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : [segment @ 0x55f50f4d1a40] Non-monotonous DTS in output stream 0:0; previous: 6032, current: 6032; changing to 6033. This may result in incorrect timestamps in the output file.
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : [segment @ 0x55f50f4d1a40] Non-monotonous DTS in output stream 0:0; previous: 6033, current: 6033; changing to 6034. This may result in incorrect timestamps in the output file.
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : [flv @ 0x55f50f4d3300] Failed to update header with correct duration.
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : [flv @ 0x55f50f4d3300] Failed to update header with correct filesize.
[2021-10-06 10:49:06] ffmpeg.back_deck.record_rtmp   ERROR   : Error writing trailer of rtmp://127.0.0.1/live/back_deck: Connection reset by peer
[2021-10-06 10:49:06] watchdog.back_deck             INFO    : Terminating the existing ffmpeg process...
[2021-10-06 10:49:06] watchdog.back_deck             INFO    : Waiting for ffmpeg to exit gracefully...
[2021-10-06 10:49:06] ffmpeg.backyard.record_rtmp    ERROR   : av_interleaved_write_frame(): Connection reset by peer
[2021-10-06 10:49:06] ffmpeg.backyard.record_rtmp    ERROR   : [flv @ 0x56502e0a6cc0] Failed to update header with correct duration.
[2021-10-06 10:49:06] ffmpeg.backyard.record_rtmp    ERROR   : [flv @ 0x56502e0a6cc0] Failed to update header with correct filesize.
[2021-10-06 10:49:06] ffmpeg.backyard.record_rtmp    ERROR   : Error writing trailer of rtmp://127.0.0.1/live/backyard: Connection reset by peer
[2021-10-06 10:49:06] watchdog.backyard              INFO    : Terminating the existing ffmpeg process...
[2021-10-06 10:49:06] watchdog.backyard              INFO    : Waiting for ffmpeg to exit gracefully..
```

### FFprobe output from your camera

```shell
ffprobe version 3.4.2-2 Copyright (c) 2007-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu2)
  configuration: --prefix=/usr --extra-version=2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Input #0, rtsp, from 'rtsp://frigate:<redacted>@10.0.50.61:554/Streaming/Channels/102/':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.240000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 640x480 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 90k tbn, 50 tbc
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2385G1-I

**Comment by blakeblackshear** [comment]
Yep. 0.9.1 incoming

**Comment by adampetrovic** [comment]
tested and working on the 0.9.1 image 👍
