### ISSUE TITLE
[Support]: Cannot play Recordings "media playback was aborted"

### ISSUE THREAD

**Issue by Moondevil-ha** [blakeblackshear/frigate#1967]
### Describe the problem you are having

I cannot play Recordings from the Frigate UI since the upgrade. It appears to work (sporadically) on my RLC-410 called sideway, but not at all on the 511w (BACK_Garden). Any ideas what I've done wrong?

![Screenshot 2021-10-09 145548](https://user-images.githubusercontent.com/72937989/136660766-9e3a5845-11f5-4a11-a1a0-d95c486e3fe8.jpg)

### Version

0.9.1-800F33E

### Frigate config file

```yaml
{
  "birdseye": {
    "enabled": true,
    "height": 720,
    "mode": "continuous",
    "quality": 8,
    "width": 1280
  },
  "cameras": {
    "Back_Garden": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1920,
        "max_disappeared": 25,
        "width": 2560
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:Cthulhu1@192.168.1.180:554",
            "roles": [
              "detect",
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:Cthulhu1@192.168.1.180:554 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Back_Garden-%Y%m%d%H%M%S.mp4 -r 5 -s 2560x1920 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 237,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 320,
        "mask": [
          "0,540,795,638,891,1385,379,1920,0,1920"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "Back_Garden",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.8,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "cat",
            "dog"
          ],
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {
              "person": 15
            }
          }
        },
        "retain_days": 5
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    },
    "Sideway": {
      "best_image_timeout": 60,
      "detect": {
        "enabled": true,
        "fps": 5,
        "height": 1440,
        "max_disappeared": 25,
        "width": 2560
      },
      "ffmpeg": {
        "global_args": [
          "-hide_banner",
          "-loglevel",
          "warning"
        ],
        "hwaccel_args": [
          "-hwaccel",
          "vaapi",
          "-hwaccel_device",
          "/dev/dri/renderD128",
          "-hwaccel_output_format",
          "yuv420p"
        ],
        "input_args": [
          "-avoid_negative_ts",
          "make_zero",
          "-fflags",
          "+genpts+discardcorrupt",
          "-rtsp_transport",
          "tcp",
          "-stimeout",
          "5000000",
          "-use_wallclock_as_timestamps",
          "1"
        ],
        "inputs": [
          {
            "global_args": [],
            "hwaccel_args": [],
            "input_args": [],
            "path": "rtsp://admin:Nyar13th0t3p@192.168.1.226:554",
            "roles": [
              "detect",
              "record"
            ]
          }
        ],
        "output_args": {
          "detect": [
            "-f",
            "rawvideo",
            "-pix_fmt",
            "yuv420p"
          ],
          "record": [
            "-f",
            "segment",
            "-segment_time",
            "10",
            "-segment_format",
            "mp4",
            "-reset_timestamps",
            "1",
            "-strftime",
            "1",
            "-c",
            "copy",
            "-an"
          ],
          "rtmp": [
            "-c",
            "copy",
            "-f",
            "flv"
          ]
        }
      },
      "ffmpeg_cmds": [
        {
          "cmd": "ffmpeg -hide_banner -loglevel warning -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://admin:Nyar13th0t3p@192.168.1.226:554 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Sideway-%Y%m%d%H%M%S.mp4 -r 5 -s 2560x1440 -f rawvideo -pix_fmt yuv420p pipe:",
          "roles": [
            "detect",
            "record"
          ]
        }
      ],
      "live": {
        "height": 720,
        "quality": 8
      },
      "motion": {
        "contour_area": 177,
        "delta_alpha": 0.2,
        "frame_alpha": 0.2,
        "frame_height": 240,
        "mask": [
          "2538,1233,1300,176,1316,26,2536,0"
        ],
        "threshold": 25
      },
      "mqtt": {
        "bounding_box": true,
        "crop": true,
        "enabled": true,
        "height": 270,
        "quality": 70,
        "required_zones": [],
        "timestamp": true
      },
      "name": "Sideway",
      "objects": {
        "filters": {
          "cat": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "dog": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.5,
            "threshold": 0.7
          },
          "person": {
            "mask": null,
            "max_area": 24000000,
            "min_area": 0,
            "min_score": 0.8,
            "threshold": 0.7
          }
        },
        "mask": "",
        "track": [
          "person",
          "dog",
          "cat"
        ]
      },
      "record": {
        "enabled": true,
        "events": {
          "max_seconds": 300,
          "objects": [
            "person",
            "cat",
            "dog"
          ],
          "post_capture": 5,
          "pre_capture": 5,
          "required_zones": [],
          "retain": {
            "default": 10,
            "objects": {
              "person": 15
            }
          }
        },
        "retain_days": 5
      },
      "rtmp": {
        "enabled": true
      },
      "snapshots": {
        "bounding_box": true,
        "clean_copy": true,
        "crop": false,
        "enabled": true,
        "height": null,
        "quality": 70,
        "required_zones": [],
        "retain": {
          "default": 10,
          "objects": {}
        },
        "timestamp": true
      },
      "timestamp_style": {
        "color": {
          "blue": 255,
          "green": 255,
          "red": 255
        },
        "effect": null,
        "format": "%m/%d/%Y %H:%M:%S",
        "position": "tl",
        "thickness": 2
      },
      "zones": {}
    }
  },
  "database": {
    "path": "/media/frigate/frigate.db"
  },
  "detect": {
    "enabled": true,
    "fps": 5,
    "height": 720,
    "max_disappeared": null,
    "width": 1280
  },
  "detectors": {
    "coral_pci": {
      "device": "pci",
      "num_threads": 3,
      "type": "edgetpu"
    },
    "coral_usb": {
      "device": "usb",
      "num_threads": 3,
      "type": "edgetpu"
    }
  },
  "environment_vars": {},
  "ffmpeg": {
    "global_args": [
      "-hide_banner",
      "-loglevel",
      "warning"
    ],
    "hwaccel_args": [],
    "input_args": [
      "-avoid_negative_ts",
      "make_zero",
      "-fflags",
      "+genpts+discardcorrupt",
      "-rtsp_transport",
      "tcp",
      "-stimeout",
      "5000000",
      "-use_wallclock_as_timestamps",
      "1"
    ],
    "output_args": {
      "detect": [
        "-f",
        "rawvideo",
        "-pix_fmt",
        "yuv420p"
      ],
      "record": [
        "-f",
        "segment",
        "-segment_time",
        "10",
        "-segment_format",
        "mp4",
        "-reset_timestamps",
        "1",
        "-strftime",
        "1",
        "-c",
        "copy",
        "-an"
      ],
      "rtmp": [
        "-c",
        "copy",
        "-f",
        "flv"
      ]
    }
  },
  "live": {
    "height": 720,
    "quality": 8
  },
  "logger": {
    "default": "info",
    "logs": {}
  },
  "model": {
    "height": 320,
    "labelmap": {},
    "labelmap_path": null,
    "path": null,
    "width": 320
  },
  "motion": null,
  "mqtt": {
    "client_id": "frigate",
    "host": "192.168.1.248",
    "password": "Cthulhu1",
    "port": 1883,
    "stats_interval": 60,
    "tls_ca_certs": null,
    "tls_client_cert": null,
    "tls_client_key": null,
    "tls_insecure": null,
    "topic_prefix": "frigate",
    "user": "mqtt-user"
  },
  "objects": {
    "filters": null,
    "mask": "",
    "track": [
      "person"
    ]
  },
  "record": {
    "enabled": false,
    "events": {
      "max_seconds": 300,
      "objects": null,
      "post_capture": 5,
      "pre_capture": 5,
      "required_zones": [],
      "retain": {
        "default": 10,
        "objects": {}
      }
    },
    "retain_days": 0
  },
  "rtmp": {
    "enabled": true
  },
  "snapshots": {
    "bounding_box": true,
    "clean_copy": true,
    "crop": false,
    "enabled": false,
    "height": null,
    "quality": 70,
    "required_zones": [],
    "retain": {
      "default": 10,
      "objects": {}
    },
    "timestamp": false
  },
  "timestamp_style": {
    "color": {
      "blue": 255,
      "green": 255,
      "red": 255
    },
    "effect": null,
    "format": "%m/%d/%Y %H:%M:%S",
    "position": "tl",
    "thickness": 2
  }
}
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-10-09 14:42:14] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e)
[2021-10-09 14:42:17] frigate.app                    INFO    : Creating directory: /tmp/cache
[2021-10-09 14:42:17] frigate.app                    WARNING : Camera Back_Garden has rtmp enabled, but rtmp is not assigned to an input.
[2021-10-09 14:42:17] frigate.app                    WARNING : Camera Sideway has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
[2021-10-09 14:42:17] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-10-09 14:42:17] peewee_migrate                 INFO    : There is nothing to migrate
[2021-10-09 14:42:17] frigate.mqtt                   INFO    : MQTT connected
[2021-10-09 14:42:17] frigate.app                    INFO    : Output process started: 221
[2021-10-09 14:42:17] detector.coral_pci             INFO    : Starting detection process: 218
[2021-10-09 14:42:17] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2021-10-09 14:42:17] frigate.app                    INFO    : Camera processor started for Back_Garden: 227
[2021-10-09 14:42:17] frigate.app                    INFO    : Camera processor started for Sideway: 228
[2021-10-09 14:42:17] frigate.app                    INFO    : Capture process started for Back_Garden: 231
[2021-10-09 14:42:17] ws4py                          INFO    : Using epoll
W driver/beagle/beagle_kernel_top_level_handler.cc:131] Could not set performance expectation : 42 (Inappropriate ioctl for device)
[2021-10-09 14:42:17] frigate.app                    INFO    : Capture process started for Sideway: 245
[2021-10-09 14:42:17] frigate.edgetpu                INFO    : TPU found
[2021-10-09 14:42:17] ws4py                          INFO    : Using epoll
[2021-10-09 14:42:17] detector.coral_usb             INFO    : Starting detection process: 220
[2021-10-09 14:42:17] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-10-09 14:42:20] frigate.edgetpu                INFO    : TPU found
[2021-10-09 14:48:56] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35530]
[2021-10-09 14:51:27] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35530]

HA log output showing aiohttp errors (unsure if related)

Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:393
First occurred: 15:01:41 (2 occurrences)
Last logged: 15:01:48

Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1183, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 241, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 96, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1162, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1192, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 263, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
```

### FFprobe output from your camera

```shell
unsure
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink rlc 511w / 410w

### Any other information that may be helpful

This appears to be unrelated to sdpecific recording files. I can access the files directly from the media folders (see attachment).

Not sure if I have a camera option formatted incorrectly, or maybe incorrect ffmpag hardware arguments for my i3-6100U. I do occasionally get a green corrupted video stream that is only cured by rebooting.

![Screenshot 2021-10-09 150211](https://user-images.githubusercontent.com/72937989/136661019-48f60575-66a0-4134-a988-1d163c9f32e6.jpg)

**Comment by blakeblackshear** [comment]
Have you tried the recommended Reolink configuration? https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others

**Comment by blakeblackshear** [comment]
I don't have any Reolink cameras, so I am not entirely sure. The thread where those came from is linked in the docs.

**Comment by leadZERO** [comment]
@blakeblackshear DM me on Twitter (@leadZERO) if you'd like a Reolink camera. I recently replaced them with some others, happy to contribute one to the project.
