### ISSUE TITLE
[Support]: Shape mismatch with custom Tensorflow model

### ISSUE THREAD

**Issue by Curid** [blakeblackshear/frigate#1979]
### Describe the problem you are having

The model has a size of 420x280, widthxheight.

[CPU model](https://gitlab.com/Curid/TF-CCTV/-/raw/master/models/cctv1/cctv1_420x280.tflite)
[Labels](https://gitlab.com/Curid/TF-CCTV/-/blob/master/labels/cctv1-doods.txt)

Swapping model width and height swaps error.

```
ValueError: could not broadcast input array from shape (1,280,420,3)
into shape (1,420,280,3)
```

### Version

0.9.1-800f33e

### Frigate config file

```yaml
model:
  width: 420
  height: 280

cameras:
  back:
    ffmpeg:
      inputs:
        - path: "rtsp://"
          roles:
            - rtmp
            - detect
    detect:
      fps: 1
      width: 640
      height: 450
    motion:
```

### Relevant log output

```shell
frigate      | Process camera_processor:back:                                      
frigate      | Traceback (most recent call last):                                  
frigate      |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in
_bootstrap
frigate      |     self.run()
frigate      |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in
run
frigate      |     self._target(*self._args, **self._kwargs)                       
frigate      |   File "/opt/frigate/frigate/video.py", line 362, in track_camera   
frigate      |     process_frames(
frigate      |   File "/opt/frigate/frigate/video.py", line 519, in process_frames 
frigate      |     detect(
frigate      |   File "/opt/frigate/frigate/video.py", line 410, in detect         
frigate      |     region_detections = object_detector.detect(tensor_input)        
frigate      |   File "/opt/frigate/frigate/edgetpu.py", line 264, in detect       
frigate      |     self.np_shm[:] = tensor_input[:]                                
frigate      | ValueError: could not broadcast input array from shape (1,420,280,3)
into shape (1,280,420,3)
```

### FFprobe output from your camera

```shell
Duration: N/A, start: -0.693696, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 650x450 [SAR 1:1 DAR 13:9], 20 fps, 20 tbr, 90k tbn
  Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

local test feed.

**Comment by blakeblackshear** [comment]
Everything in Frigate is currently built around square detection models, so I dont think this will work without some significant updates.

**Comment by Curid** [comment]
It seems to actually work with the fix.

**Comment by Curid** [comment]
@blakeblackshear Just released a new custom model. Do you mind if I post about it in  `Custom Models #1043`?

**Comment by blakeblackshear** [comment]
That's fine. I don't have any intention of stopping others from developing models that work with Frigate.
