### ISSUE TITLE
[Support]: Recording issue with Vstarcam C8818WIP camera

### ISSUE THREAD

**Issue by Pavel-Arkhipov** [blakeblackshear/frigate#2042]
### Describe the problem you are having

Hello! 

I have an issue with recording events on a connected camera. So RTSP streaming is ok, object detection is also ok. 

When I'm trying to play a clip from the web GUI it gave me an error "The media could not be loaded, either because the server or network failed or because the format is not supported." The same error appears on the recording.

If I'm mounting the "recordings" folder, I'm able to locate the clip and play it with VLC.

Initially, when I install the new camera there was no recording at all until I've found that I need to change -segment format from default mp4 to avi. So it could be the root of the issue, but now I have no idea what to modify in config to have clips available in the web GUI. 

Please advice

Thanks!

Best regards,
Pavel 

### Version

0.9.1-800F33E

### Frigate config file

```yaml
mqtt:
  host: 192.168.51.24

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  mode: continuous

cameras:
  Cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:88888888@192.168.61.106:10554/tcp/av0_1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:88888888@192.168.61.106:10554/tcp/av0_0
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 7

  Cam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:888888889@192.168.51.7:10554/tcp/av0_1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:88888888@192.168.51.7:10554/tcp/av0_0
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format avi -reset_timestamps 1 -strftime 1 -c copy -an
    detect:
      width: 640
      height: 360
      fps: 7

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat

record:
  enabled: true
  retain_days: 0
  events:
    max_seconds: 300
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 5
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 5
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - cat
    retain:
      default: 30

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 30

detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

### Relevant log output

```shell
[2021-10-17 21:58:12] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59372],
[2021-10-17 21:59:17] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59372],
[2021-10-17 21:59:44] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59520],
[2021-10-17 21:59:48] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:36304],
[2021-10-17 22:00:02] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:36304],
[2021-10-17 22:00:04] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59520],
[2021-10-17 22:00:04] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59564],
[2021-10-17 22:00:08] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59564],
[2021-10-17 22:00:08] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59582],
[2021-10-17 22:01:17] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59582],
[2021-10-17 22:01:49] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59758],
[2021-10-17 22:03:00] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59758],
[2021-10-17 22:03:00] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59890],
[2021-10-17 22:03:02] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59890],
[2021-10-17 22:03:02] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59900],
[2021-10-17 22:03:12] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59900],
[2021-10-17 22:03:12] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59936],
[2021-10-17 22:03:22] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:59936],
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2021-10-17 22:04:55] frigate.app                    INFO    : Starting Frigate (0.9.1-800f33e),
Starting migrations,
[2021-10-17 22:04:55] peewee_migrate                 INFO    : Starting migrations,
There is nothing to migrate,
[2021-10-17 22:04:55] peewee_migrate                 INFO    : There is nothing to migrate,
[2021-10-17 22:04:55] detector.cpu1                  INFO    : Starting detection process: 217,
[2021-10-17 22:04:55] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.,
[2021-10-17 22:04:55] frigate.app                    INFO    : Output process started: 220,
[2021-10-17 22:04:55] frigate.mqtt                   INFO    : MQTT connected,
[2021-10-17 22:04:55] frigate.app                    INFO    : Camera processor started for Cam1: 223,
[2021-10-17 22:04:55] detector.cpu2                  INFO    : Starting detection process: 219,
[2021-10-17 22:04:55] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.,
[2021-10-17 22:04:55] ws4py                          INFO    : Using epoll,
[2021-10-17 22:04:55] frigate.app                    INFO    : Camera processor started for Cam2: 225,
[2021-10-17 22:04:55] frigate.app                    INFO    : Capture process started for Cam1: 227,
[2021-10-17 22:04:55] frigate.app                    INFO    : Capture process started for Cam2: 229,
[2021-10-17 22:04:55] ws4py                          INFO    : Using epoll,
Exception in thread recording_maint:,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner,
    self.run(),
  File "/opt/frigate/frigate/record.py", line 135, in run,
    self.move_files(),
  File "/opt/frigate/frigate/record.py", line 99, in move_files,
    duration = float(p.stdout.decode().strip()),
ValueError: could not convert string to float: 'N/A',
[2021-10-17 22:05:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60176],
[2021-10-17 22:05:07] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60176],
[2021-10-17 22:05:07] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60972],
[2021-10-17 22:07:05] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60972],
[2021-10-17 22:22:25] ffmpeg.Cam1.record             ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono,
[2021-10-17 22:22:25] watchdog.Cam1                  INFO    : Terminating the existing ffmpeg process...,
[2021-10-17 22:22:25] watchdog.Cam1                  INFO    : Waiting for ffmpeg to exit gracefully...,
[2021-10-17 22:22:35] ffmpeg.Cam1.record             ERROR   : [tcp @ 0x558e467bd480] Connection to tcp://192.168.61.106:10554?timeout=5000000 failed: Connection timed out,
[2021-10-17 22:22:35] ffmpeg.Cam1.record             ERROR   : rtsp://admin:HipRoot9@192.168.61.106:10554/tcp/av0_0: Connection timed out,
[2021-10-17 22:22:35] watchdog.Cam1                  INFO    : Terminating the existing ffmpeg process...,
[2021-10-17 22:22:35] watchdog.Cam1                  INFO    : Waiting for ffmpeg to exit gracefully...,
[2021-10-17 22:22:55] watchdog.Cam1                  INFO    : No frames received from Cam1 in 20 seconds. Exiting ffmpeg...,
[2021-10-17 22:22:55] watchdog.Cam1                  INFO    : Waiting for ffmpeg to exit gracefully...,
[2021-10-17 22:22:56] frigate.video                  INFO    : Cam1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures,
[2021-10-17 22:22:56] frigate.video                  INFO    : Cam1: ffmpeg process is not running. exiting capture thread...,
[2021-10-17 22:23:06] watchdog.Cam1                  ERROR   : FFMPEG process crashed unexpectedly for Cam1.,
[2021-10-17 22:23:06] watchdog.Cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2021-10-17 22:23:06] watchdog.Cam1                  ERROR   : You may have invalid args defined for this camera.,
[2021-10-17 22:23:06] ffmpeg.Cam1.detect             ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono,
[2021-10-17 22:23:06] ffmpeg.Cam1.detect             ERROR   : [flv @ 0x55fb293477c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly,
[2021-10-17 22:23:06] ffmpeg.Cam1.detect             ERROR   : [flv @ 0x55fb293477c0] Failed to update header with correct duration.,
[2021-10-17 22:23:06] ffmpeg.Cam1.detect             ERROR   : [flv @ 0x55fb293477c0] Failed to update header with correct filesize.,
[2021-10-17 22:23:36] ffmpeg.Cam1.record             ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono,
[2021-10-17 22:23:36] watchdog.Cam1                  INFO    : Terminating the existing ffmpeg process...,
[2021-10-17 22:23:36] watchdog.Cam1                  INFO    : Waiting for ffmpeg to exit gracefully...,
[2021-10-17 22:23:45] frigate.video                  INFO    : Cam1: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures,
[2021-10-17 22:23:45] frigate.video                  INFO    : Cam1: ffmpeg process is not running. exiting capture thread...,
[2021-10-17 22:23:46] watchdog.Cam1                  ERROR   : FFMPEG process crashed unexpectedly for Cam1.,
[2021-10-17 22:23:46] watchdog.Cam1                  ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2021-10-17 22:23:46] watchdog.Cam1                  ERROR   : You may have invalid args defined for this camera.,
[2021-10-17 22:23:46] ffmpeg.Cam1.detect             ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono,
[2021-10-17 22:23:46] ffmpeg.Cam1.detect             ERROR   : [flv @ 0x563c62167800] Failed to update header with correct duration.,
[2021-10-17 22:23:46] ffmpeg.Cam1.detect             ERROR   : [flv @ 0x563c62167800] Failed to update header with correct filesize.,
[2021-10-17 22:24:14] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:34960],
[2021-10-17 22:24:22] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:40046],
[2021-10-17 22:24:23] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:40046],
[2021-10-17 22:24:41] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:34960],
[2021-10-17 22:24:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35210],
[2021-10-17 22:24:41] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:40224],
[2021-10-17 22:24:44] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:40224],
[2021-10-17 22:24:46] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35210],
[2021-10-17 22:24:46] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35280],
[2021-10-17 22:26:06] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:35280],
```

### FFprobe output from your camera

```shell
Camera 1 which works ok
root@2ea1b1584d08:/opt/frigate# ffprobe rtsp://admin:8888888@192.168.61.106:10554/tcp/av0_0
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55891a736b80] CSeq 6 expected, 0 received.
^C  Last message repeated 24 times
root@2ea1b1584d08:/opt/frigate# ^C

Camera 2 which does not work:

root@2ea1b1584d08:/opt/frigate# ffprobe rtsp://admin:8888888@192.168.51.7:10554/tcp/av0_0
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x560c7a494a40] Invalid NAL unit 0, skipping.
[rtsp @ 0x560c7a490b80] CSeq 6 expected, 0 received.
^C  Last message repeated 38 times
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Mixed

### Camera make and model

Vstarcam C8818WIP

### Any other information that may be helpful

A camera that works ok: VStarcam C8817WIP

**Comment by blakeblackshear** [comment]
Changing the segment format to avi is breaking the recording maintainer because it cannot determine the segment lengths. I don't think that segment format will work with frigate. It doesn't look like ffprobe finished. It should show the codec information for your cameras.

**Comment by Pavel-Arkhipov** [comment]
Got it.

adding -rtsp_transport TCP to ffprobe I've got codec info from both cameras

Cam1: works ok
Input #0, rtsp, from 'rtsp://admin:888888@192.168.61.106:10554/tcp/av0_0':
  Metadata:
    title           : streamed by the VSTARCAM RTSP server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080, 7.50 fps, 14.99 tbr, 90k tbn, 15 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

Cam2: record fails
Input #0, rtsp, from 'rtsp://admin:88888888@192.168.51.7:10554/tcp/av0_0':
  Metadata:
    title           : streamed by the VSTARCAM RTSP server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 30 fps, 25 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

also removed segment avi from the config. Nothing changed yet...

**Comment by EchterAgo** [comment]
This is likely the same issue as #1632 @dscoular

I did some tests with `ffmpeg` and also got the `No start code is found.` when recording to `mp4`. I tried changing the container format to `ts` and the recordings were playable. Given that the master branch was recently changed to record in `ts` containers this might work now. I'll give master a try and will report back if it works.

**Comment by Pavel-Arkhipov** [comment]
Confirm that changing container to **ts** works. now videos are viewable in VLC

Could you please advise how to modify the config in the correct way?

My trials were: 
1) output_args:
        record: -f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy -an

But it writes mp4

2) output_args:
       record: -f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Cam2-%Y%m%d%H%M%S.ts

just adding mp4 on top of ts on the command line

-f segment -segment_time 10 -segment_format ts -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/Cam2-%Y%m%d%H%M%S.ts /tmp/cache/Cam2-%Y%m%d%H%M%S.mp4",

Thanks!

**Comment by blakeblackshear** [comment]
Unfortunately the switch to mpegts created problems for other users. 0.9.3 will revert this change.

**Comment by freeewilly** [comment]
@Pavel-Arkhipov: did you ever solve this issue? I just received a new VStarCam and I have the exact same problem.
My old VStarcams work fine, but the new one is only playable in VLC.
Thanks for assistance!

**Comment by parkhipov** [comment]
@freeewilly looks this issue is still present in 0.12.0-CF2466C, unfortunately. I've used old one 0.9.2 which was modified for this type of camera and woks perfect until now.

With my old camers it still possible to record the events, new one can do snapshot only. Playing video isnt possible.

Pavel
