### ISSUE TITLE
[Support]: Frigate WebUI won't start.

### ISSUE THREAD

**Issue by BlackBadPinguin** [blakeblackshear/frigate#2171]
### Describe the problem you are having

Frigate WebUI won't start.

### Version

None

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.115
  user: user
  password: passwd
database:
  path: /media/frigate/db/frigate.db
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
cameras:
  camera_1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}192.168.178.25:554/H264/ch1/main/av_stream # <----- Update for your camera
          roles:
            - detect
            - rtmp
    detect:
      width: 2560 # <---- update for your camera's resolution
      height: 1920 # <---- update for your camera's resolution
```

### Relevant log output

```shell
2021-11-02T21:16:34.468331014Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:17:31.499126947Z  * Starting nginx nginx

2021-11-02T21:17:31.513334096Z    ...done.

2021-11-02T21:17:32.235063861Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:18:38.082535016Z  * Starting nginx nginx

2021-11-02T21:18:38.098525858Z    ...done.

2021-11-02T21:18:38.798090018Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:19:44.547953162Z  * Starting nginx nginx

2021-11-02T21:19:44.559500669Z    ...done.

2021-11-02T21:19:45.300125491Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:20:51.206994480Z  * Starting nginx nginx

2021-11-02T21:20:51.215829796Z    ...done.

2021-11-02T21:20:51.935972584Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:21:57.730446949Z  * Starting nginx nginx

2021-11-02T21:21:57.743723430Z    ...done.

2021-11-02T21:21:58.440963457Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:23:04.211074212Z  * Starting nginx nginx

2021-11-02T21:23:04.224089175Z    ...done.

2021-11-02T21:23:04.943485415Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:24:10.766886731Z  * Starting nginx nginx

2021-11-02T21:24:10.776683475Z    ...done.

2021-11-02T21:24:11.495988092Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']

2021-11-02T21:25:17.326687308Z  * Starting nginx nginx

2021-11-02T21:25:17.333207018Z    ...done.

2021-11-02T21:25:18.054846302Z Error parsing config: extra keys not allowed @ data['cameras']['camera_1']['detect']['width']
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.178.25:554/H264/ch1/main/av_stream':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 15.247333, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2560x1920, 6 fps, 6 tbr, 90k tbn, 12 tbc
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

ANNKE C500

### Any other information that may be helpful

brand new install, followed https://github.com/blakeblackshear/frigate/discussions/1111

**Comment by BlackBadPinguin** [comment]
Ok, now i "fixed" the WebUI starting but get a lot of other crazy errors in the log
`  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector

    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)

  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__

    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate

    raise ValueError('Failed to load delegate from {}\n{}'.format(

ValueError: Failed to load delegate from libedgetpu.so.1.0


frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...

frigate.app                    INFO    : Stopping...

frigate.events                 INFO    : Exiting event processor...

frigate.record                 INFO    : Exiting recording maintenance...

frigate.object_processing      INFO    : Exiting object processor...

frigate.events                 INFO    : Exiting event cleanup...

frigate.watchdog               INFO    : Exiting watchdog...

frigate.stats                  INFO    : Exiting watchdog...

peewee.sqliteq                 INFO    : writer received shutdown request, exiting.

root                           INFO    : Waiting for detection process to exit gracefully...

frigate.video                  INFO    : back: exiting subprocess

 * Starting nginx nginx

   ...done.

Starting migrations

peewee_migrate                 INFO    : Starting migrations

There is nothing to migrate

peewee_migrate                 INFO    : There is nothing to migrate

detector.coral                 INFO    : Starting detection process: 90

frigate.edgetpu                INFO    : Attempting to load TPU as usb

frigate.mqtt                   INFO    : MQTT connected

frigate.edgetpu                INFO    : No EdgeTPU detected.

Process detector:coral:

frigate.app                    INFO    : Camera processor started for back: 93

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate

    delegate = Delegate(library, options)

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__

    raise ValueError(capture.message)

ValueError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap

    self.run()

  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector

    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)

  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__

    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate

    raise ValueError('Failed to load delegate from {}\n{}'.format(

ValueError: Failed to load delegate from libedgetpu.so.1.0


frigate.app                    INFO    : Capture process started for back: 95

frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...

frigate.app                    INFO    : Stopping...

frigate.record                 INFO    : Exiting recording maintenance...

frigate.object_processing      INFO    : Exiting object processor...

frigate.events                 INFO    : Exiting event cleanup...

frigate.events                 INFO    : Exiting event processor...

frigate.watchdog               INFO    : Exiting watchdog...

frigate.stats                  INFO    : Exiting watchdog...

peewee.sqliteq                 INFO    : writer received shutdown request, exiting.

root                           INFO    : Waiting for detection process to exit gracefully...

frigate.video                  INFO    : back: exiting subprocess

 * Starting nginx nginx

   ...done.

Starting migrations

peewee_migrate                 INFO    : Starting migrations

There is nothing to migrate

peewee_migrate                 INFO    : There is nothing to migrate

frigate.mqtt                   INFO    : MQTT connected

detector.coral                 INFO    : Starting detection process: 90

frigate.app                    INFO    : Camera processor started for back: 93

frigate.app                    INFO    : Capture process started for back: 95

frigate.edgetpu                INFO    : Attempting to load TPU as usb

frigate.edgetpu                INFO    : No EdgeTPU detected.

Process detector:coral:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate

    delegate = Delegate(library, options)

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__

    raise ValueError(capture.message)

ValueError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap

    self.run()

  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector

    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)

  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__

    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)

  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate

    raise ValueError('Failed to load delegate from {}\n{}'.format(

ValueError: Failed to load delegate from libedgetpu.so.1.0`

**Comment by ozett** [comment]
check your detectors config again. 
your error-log shows that your have configured a usb-type.
```
frigate.edgetpu                INFO    : Attempting to load TPU as usb
```

try to stick with CPU for testing first..
https://github.com/blakeblackshear/frigate/blob/master/docs/docs/configuration/detectors.md

**Comment by BlackBadPinguin** [comment]
Thanks, that worked now it works like a charm.
