### ISSUE TITLE
: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

### ISSUE THREAD

**Issue by vjmaz** [blakeblackshear/frigate#2437]
### Describe the problem you are having

Hi i just did the new update and my Frigate addon wont start anyone else or can someone guide me 

here is the log section:

Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:153
First occurred: 20:57:27 (2 occurrences)
Last logged: 20:57:28

Setup failed for frigate: Unable to import component: cannot import name 'HTTP_BAD_REQUEST' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Sorry to ask I'm not that expert but was using frigate heavily & wify loved using it 

from Frigate log 
Frigate NVR (Full Access)
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-13 20:57:49] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2021-12-13 20:57:49] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-12-13 20:57:49] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-12-13 20:57:49] peewee_migrate                 INFO    : There is nothing to migrate
[2021-12-13 20:57:49] frigate.mqtt                   INFO    : MQTT connected
[2021-12-13 20:57:49] frigate.app                    INFO    : Output process started: 214
[2021-12-13 20:57:49] detector.coral                 INFO    : Starting detection process: 213
[2021-12-13 20:57:49] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-12-13 20:57:49] ws4py                          INFO    : Using epoll
[2021-12-13 20:57:49] frigate.app                    INFO    : Camera processor started for Front_Yard: 217
[2021-12-13 20:57:49] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2021-12-13 20:57:49] frigate.app                    INFO    : Camera processor started for POOL_Area: 223
[2021-12-13 20:57:50] frigate.app                    INFO    : Camera processor started for Back_Yard: 225
[2021-12-13 20:57:50] frigate.app                    INFO    : Camera processor started for Court_Yard: 228
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for Front_Yard: 231
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for POOL_Area: 237
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for Back_Yard: 240
[2021-12-13 20:57:51] frigate.app                    INFO    : Capture process started for Court_Yard: 241
[2021-12-13 20:57:51] ws4py                          INFO    : Using epoll
[2021-12-13 20:58:11] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2021-12-13 20:58:11] frigate.app                    INFO    : Stopping...
[2021-12-13 20:58:11] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2021-12-13 20:58:11] frigate.record                 INFO    : Exiting recording maintenance...
[2021-12-13 20:58:11] frigate.stats                  INFO    : Exiting watchdog...
[2021-12-13 20:58:11] frigate.record                 INFO    : Exiting recording cleanup...
[2021-12-13 20:58:11] frigate.watchdog               INFO    : Exiting watchdog...
[2021-12-13 20:58:11] frigate.events                 INFO    : Exiting event cleanup...
[2021-12-13 20:58:18] frigate.object_processing      INFO    : Exiting object processor...
[2021-12-13 20:58:21] frigate.events                 INFO    : Exiting event processor...
[2021-12-13 20:58:21] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2021-12-13 20:58:21] root                           INFO    : Waiting for detection process to exit gracefully...
[cmd] python3 exited 0
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 18 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

### Version

latest 

### Frigate config file

```yaml
o have not changed it
```

### Relevant log output

```shell
Frigate NVR (Full Access)
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-13 20:57:49] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2021-12-13 20:57:49] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-12-13 20:57:49] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-12-13 20:57:49] peewee_migrate                 INFO    : There is nothing to migrate
[2021-12-13 20:57:49] frigate.mqtt                   INFO    : MQTT connected
[2021-12-13 20:57:49] frigate.app                    INFO    : Output process started: 214
[2021-12-13 20:57:49] detector.coral                 INFO    : Starting detection process: 213
[2021-12-13 20:57:49] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-12-13 20:57:49] ws4py                          INFO    : Using epoll
[2021-12-13 20:57:49] frigate.app                    INFO    : Camera processor started for Front_Yard: 217
[2021-12-13 20:57:49] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2021-12-13 20:57:49] frigate.app                    INFO    : Camera processor started for POOL_Area: 223
[2021-12-13 20:57:50] frigate.app                    INFO    : Camera processor started for Back_Yard: 225
[2021-12-13 20:57:50] frigate.app                    INFO    : Camera processor started for Court_Yard: 228
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for Front_Yard: 231
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for POOL_Area: 237
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for Back_Yard: 240
[2021-12-13 20:57:51] frigate.app                    INFO    : Capture process started for Court_Yard: 241
[2021-12-13 20:57:51] ws4py                          INFO    : Using epoll
[2021-12-13 20:58:11] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2021-12-13 20:58:11] frigate.app                    INFO    : Stopping...
[2021-12-13 20:58:11] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2021-12-13 20:58:11] frigate.record                 INFO    : Exiting recording maintenance...
[2021-12-13 20:58:11] frigate.stats                  INFO    : Exiting watchdog...
[2021-12-13 20:58:11] frigate.record                 INFO    : Exiting recording cleanup...
[2021-12-13 20:58:11] frigate.watchdog               INFO    : Exiting watchdog...
[2021-12-13 20:58:11] frigate.events                 INFO    : Exiting event cleanup...
[2021-12-13 20:58:18] frigate.object_processing      INFO    : Exiting object processor...
[2021-12-13 20:58:21] frigate.events                 INFO    : Exiting event processor...
[2021-12-13 20:58:21] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2021-12-13 20:58:21] root                           INFO    : Waiting for detection process to exit gracefully...
[cmd] python3 exited 0
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 18 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
not sure what this is
```

### Frigate stats

```json
Frigate NVR (Full Access)
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-13 20:57:49] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2021-12-13 20:57:49] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-12-13 20:57:49] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-12-13 20:57:49] peewee_migrate                 INFO    : There is nothing to migrate
[2021-12-13 20:57:49] frigate.mqtt                   INFO    : MQTT connected
[2021-12-13 20:57:49] frigate.app                    INFO    : Output process started: 214
[2021-12-13 20:57:49] detector.coral                 INFO    : Starting detection process: 213
[2021-12-13 20:57:49] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-12-13 20:57:49] ws4py                          INFO    : Using epoll
[2021-12-13 20:57:49] frigate.app                    INFO    : Camera processor started for Front_Yard: 217
[2021-12-13 20:57:49] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2021-12-13 20:57:49] frigate.app                    INFO    : Camera processor started for POOL_Area: 223
[2021-12-13 20:57:50] frigate.app                    INFO    : Camera processor started for Back_Yard: 225
[2021-12-13 20:57:50] frigate.app                    INFO    : Camera processor started for Court_Yard: 228
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for Front_Yard: 231
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for POOL_Area: 237
[2021-12-13 20:57:50] frigate.app                    INFO    : Capture process started for Back_Yard: 240
[2021-12-13 20:57:51] frigate.app                    INFO    : Capture process started for Court_Yard: 241
[2021-12-13 20:57:51] ws4py                          INFO    : Using epoll
[2021-12-13 20:58:11] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2021-12-13 20:58:11] frigate.app                    INFO    : Stopping...
[2021-12-13 20:58:11] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2021-12-13 20:58:11] frigate.record                 INFO    : Exiting recording maintenance...
[2021-12-13 20:58:11] frigate.stats                  INFO    : Exiting watchdog...
[2021-12-13 20:58:11] frigate.record                 INFO    : Exiting recording cleanup...
[2021-12-13 20:58:11] frigate.watchdog               INFO    : Exiting watchdog...
[2021-12-13 20:58:11] frigate.events                 INFO    : Exiting event cleanup...
[2021-12-13 20:58:18] frigate.object_processing      INFO    : Exiting object processor...
[2021-12-13 20:58:21] frigate.events                 INFO    : Exiting event processor...
[2021-12-13 20:58:21] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2021-12-13 20:58:21] root                           INFO    : Waiting for detection process to exit gracefully...
[cmd] python3 exited 0
/usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 18 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

China ( TianAnXum IP Camers model TAX-POE6003 )

**Comment by vjmaz** [comment]
The issue was my USB Coral died sorry team
