### ISSUE TITLE
[Support]: Coral USB not recognised

### ISSUE THREAD

**Issue by indo419** [blakeblackshear/frigate#2501]
### Describe the problem you are having

System is working well using 4 CPU detectors.
CORAL USB detector is not recognized and crashes the system when it is enabled in the config file.
I have tried 2 different CORAL USB devices on 2 different computers running CentOS9 and UBUNTU

### Version

0.9.4-26ae608

### Frigate config file

```yaml
#mqtt:
#  host: maqiatto.com
#  port: 8883
#  user: xxxx
#  password: xxxx
#  topic_prefix: xxxx

mqtt:
  host: xxxx.s1.eu.hivemq.cloud
  port: 8883
  user: xxxx
  password: xxxx

detectors:
  coral:
    type: edgetpu
    device: usb
  cpu1:
    type: cpu
    num_threads: 3


cameras:
  xxxx_Pallet_Wrapper: #########################################################
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxxx@xxxx.dynalias.org:xxxx/videoSub
          roles:
            - detect
            - rtmp
        - path: rtsp://xxxx:xxxx@xxxx.dynalias.org:xxxx/videoMain
          roles:
            - record
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    motion:
      mask:
        - 234,0,231,27,165,24,159,0
    objects:
      track:
        - person
        - car
        - bicycle
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 21
        objects:
          person: 31
          car: 31
          bicycle: 15
    record:
      enabled: True
#      retain_days: 0
      events:
#        max_seconds: 300
#        pre_capture: 8
#        post_capture: 8
        objects:
          - person
          - car
          - bicycle
        required_zones: []
#        retain:
#          default: 21
#          objects:
#            person: 31
#            car: 31
#            bicycle: 15




record:
  enabled: True
  retain_days: 20
  events:
    max_seconds: 300
    pre_capture: 10
    post_capture: 10
    objects:
      - person
    required_zones: []
    retain:
      default: 20
      objects:
        person: 30

rtmp:
  enabled: False

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

timestamp_style:
  position: "tr"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: shadow #solid None

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: warning
    frigate.app: warning
    ffmpeg.xxxx_Pallet_Wrapper.detect: error
    ffmpeg.xxxx_Pallet_Wrapper.rtmp: error
    ffmpeg.xxxx_Pallet_Wrapper.record: error
    detector.cpu1: warning
    detector.coral: warning
```

### Relevant log output

```shell
12:37 PM
[2021-12-22 12:37:08] ws4py INFO : Using epoll
conmon
12:37 PM
[2021-12-22 12:37:08] frigate.edgetpu WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
conmon
12:37 PM
[2021-12-22 12:37:08] ws4py INFO : Using epoll
conmon
12:37 PM
[2021-12-22 12:37:08] frigate.edgetpu WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
conmon
12:37 PM
[2021-12-22 12:37:08] detector.cpu4 INFO : Starting detection process: 229
conmon
12:37 PM
[2021-12-22 12:37:08] detector.cpu3 INFO : Starting detection process: 228
conmon
12:37 PM
[2021-12-22 12:37:08] frigate.edgetpu WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
conmon
12:37 PM
conmon
12:37 PM
ValueError: Failed to load delegate from libedgetpu.so.1.0
conmon
12:37 PM
raise ValueError('Failed to load delegate from {}\n{}'.format(
conmon
12:37 PM
File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
conmon
12:37 PM
edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
conmon
12:37 PM
File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__
conmon
12:37 PM
object_detector = LocalObjectDetector(
conmon
12:37 PM
File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector
conmon
12:37 PM
self._target(*self._args, **self._kwargs)
conmon
12:37 PM
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
conmon
12:37 PM
self.run()
conmon
12:37 PM
File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
conmon
12:37 PM
Traceback (most recent call last):
conmon
12:37 PM
conmon
12:37 PM
During handling of the above exception, another exception occurred:
conmon
12:37 PM
conmon
12:37 PM
ValueError
conmon
12:37 PM
raise ValueError(capture.message)
conmon
12:37 PM
File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
conmon
12:37 PM
delegate = Delegate(library, options)
conmon
12:37 PM
File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
conmon
12:37 PM
Traceback (most recent call last):
conmon
12:37 PM
[2021-12-22 12:37:08] detector.cpu2 INFO : Starting detection process: 225
conmon
12:37 PM
[2021-12-22 12:37:08] frigate.edgetpu ERROR : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
conmon
12:37 PM
Process detector:coral:
conmon
12:37 PM
[2021-12-22 12:37:08] frigate.edgetpu INFO : Attempting to load TPU as usb
conmon
12:37 PM
[2021-12-22 12:37:08] frigate.edgetpu WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
conmon
12:37 PM
[2021-12-22 12:37:08] detector.coral INFO : Starting detection process: 220
conmon
12:37 PM
[2021-12-22 12:37:07] peewee_migrate INFO : There is nothing to migrate
conmon
12:37 PM
There is nothing to migrate
conmon
12:37 PM
[2021-12-22 12:37:07] peewee_migrate INFO : Starting migrations
conmon
12:37 PM
Starting migrations
conmon
12:37 PM
[2021-12-22 12:37:07] frigate.app INFO : Starting Frigate (0.9.4-26ae608)
conmon
12:37 PM
[2021-12-22 12:37:03] frigate.record WARNING : Discarding a corrupt recording segment: ShowLow_Front-20211222123702.mp4
conmon
12:37 PM
[2021-12-22 12:37:03] frigate.video INFO : Sigma_Tool_Room: ffmpeg process is not running. exiting capture thread...
conmon
12:37 PM
[2021-12-22 12:37:03] frigate.video INFO : Sigma_Tool_Room: ffmpeg sent a broken frame. read of closed file
conmon
3
12:37 PM
[2021-12-22 12:37:03] frigate.video INFO : Sigma_Tool_Room: ffmpeg sent a broken frame. memoryview assignment: lvalue and rvalue have different structures
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR :
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [segment @ 0x55660dcda340] dimensions not set
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dd3ce80] Error decoding the extradata
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 2 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dd3ce80] Clipping illegal num_reorder_frames 6187
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Guessed Channel Layout for Input Stream #0.1 : mono
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Consider increasing the value for the 'analyzeduration' and 'probesize' options
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [rtsp @ 0x55660dcd0d00] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] watchdog.Sigma_Tool_Room INFO : Waiting for ffmpeg to exit gracefully...
conmon
12:37 PM
[2021-12-22 12:37:03] frigate.watchdog INFO : Detection appears to have stopped. Exiting frigate...
conmon
12:37 PM
[2021-12-22 12:37:03] watchdog.Sigma_Tool_Room INFO : No frames received from Sigma_Tool_Room in 20 seconds. Exiting ffmpeg...
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [rtsp @ 0x55660dcd0d00] CSeq 6 expected, 0 received.
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [rtsp @ 0x55660dcd0d00] CSeq 6 expected, 0 received.
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : Last message repeated 1 times
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] non-existing PPS 0 referenced
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] no frame!
conmon
12:37 PM
[2021-12-22 12:37:03] ffmpeg.ShowLow_Bedroom.detect ERROR : [h264 @ 0x55660dcd6700] decode_slice_header error
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Fiscam 9828P

### Any other information that may be helpful

I originally have this problem on a CentOS 9 Stream using PODMAN 
I then set up another PC with the latest Ubuntu, again using PODMAN.

I have not tried DOCKER

**Comment by hugalafutro** [comment]
Sorry no idea what podman is, but with docker I had to run the container as privileged to get it to recognize the tpu even the the usb bus was passed to the container.
