### ISSUE TITLE
[Support]: Observing SQL error in the purge_duplicates method

### ISSUE THREAD

**Issue by yury-sannikov** [blakeblackshear/frigate#2504]
### Describe the problem you are having

Periodically seeing an error message for the `purge_duplicates` code. Looks like an issue with the SQL. ~I'm not very familiar with SQLite but I have some doubts about the coma in this expression `round(start_time/5,0)*5` Will check my theory later today.~ wrong

### Version

0.9.4-26AE608 (branched from tag: v0.9.4)

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
Exception in thread event_cleanup:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: near "(": syntax error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/events.py", line 213, in run
    self.purge_duplicates()
  File "/opt/frigate/frigate/events.py", line 192, in purge_duplicates
    for event in duplicate_events:
  File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 4408, in next
    self.cursor_wrapper.iterate()
  File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 4319, in iterate
    row = self.cursor.fetchone()
  File "/usr/local/lib/python3.6/dist-packages/playhouse/sqliteq.py", line 109, in fetchone
    self._wait()
  File "/usr/local/lib/python3.6/dist-packages/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/usr/local/lib/python3.6/dist-packages/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 3167, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: near "(": syntax error
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other

### Install method

Docker CLI

### Coral version

Other

### Network connection

Wireless

### Camera make and model

n/a

**Comment by blakeblackshear** [comment]
I'm not sure how this could happen since its a fixed query. I can't reproduce this.
