### ISSUE TITLE
[Support]: No EdgeTPU was detected

### ISSUE THREAD

**Issue by goldiiii** [blakeblackshear/frigate#2517]
### Describe the problem you are having

Google Coral USB Accelerator is not found

Hardware: 
- Raspberry Pi 3
- Google Coral USB Acc

Software:
- Home Assistant 2021.12.5
- Home Assistant OS 7.0
- HACS 
- NVR Custom component 2.2.0
- Frigate NVR 2.3

### Version

0.9.4-26ae608

### Frigate config file

```yaml
mqtt:
  host: 192.168.7.37
  port: 1883
  user: mosquitto
  password: muecke2021
  topic_prefix: frigate
  client_id: frigate


detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False

cameras:
  haustuer: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.7.32:554/Streaming/channels/201 # <----- Update for your camera
          roles:
            - detect
            - rtmp
  terrasse: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.7.32:554/Streaming/channels/101 # <----- Update for your camera
          roles:
            - detect
            - rtmp
  # fahrzeuge: # <------ Name the camera
  #   ffmpeg:
  #     inputs:
  #       - path: rtsp://admin:pass@192.168.7.32:554/Streaming/channels/301 # <----- Update for your camera
  #         roles:
  #           - detect
  #           - rtmp

# detect:
#   # Optional: width of the frame for the input with the detect role (default: shown below)
#   width: 1920
#   # Optional: height of the frame for the input with the detect role (default: shown below)
#   height: 1080
#   # Optional: desired fps for your camera for the input with the detect role (default: shown below)
#   # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
#   fps: 5
#   # Optional: enables detection for the camera (default: True)
#   # This value can be set via MQTT and will be updated in startup based on retained value
#   enabled: True
#   # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
#   max_disappeared: 25

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - cat 
    - dog
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-12-24 09:33:45] frigate.app                    INFO    : Starting Frigate (0.9.4-26ae608)
[2021-12-24 09:33:45] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2021-12-24 09:33:45] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2021-12-24 09:33:45] peewee_migrate                 INFO    : There is nothing to migrate
[2021-12-24 09:33:45] frigate.mqtt                   INFO    : MQTT connected
[2021-12-24 09:33:45] detector.coral                 INFO    : Starting detection process: 215
[2021-12-24 09:33:45] frigate.app                    INFO    : Output process started: 217
[2021-12-24 09:33:45] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2021-12-24 09:33:45] ws4py                          INFO    : Using epoll
[2021-12-24 09:33:45] frigate.app                    INFO    : Camera processor started for haustuer: 220
[2021-12-24 09:33:45] frigate.app                    INFO    : Camera processor started for terrasse: 223
[2021-12-24 09:33:45] frigate.app                    INFO    : Capture process started for haustuer: 226
[2021-12-24 09:33:45] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 156, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 64, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2021-12-24 09:33:45] frigate.app                    INFO    : Capture process started for terrasse: 227
[2021-12-24 09:33:46] ws4py                          INFO    : Using epoll
[2021-12-24 09:34:06] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2021-12-24 09:34:06] frigate.app                    INFO    : Stopping...
[2021-12-24 09:34:06] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2021-12-24 09:34:06] frigate.stats                  INFO    : Exiting watchdog...
[2021-12-24 09:34:06] frigate.events                 INFO    : Exiting event cleanup...
[2021-12-24 09:34:06] frigate.record                 INFO    : Exiting recording cleanup...
[2021-12-24 09:34:06] frigate.watchdog               INFO    : Exiting watchdog...
[2021-12-24 09:34:06] frigate.object_processing      INFO    : Exiting object processor...
[2021-12-24 09:34:06] frigate.record                 INFO    : Exiting recording maintenance...
```

### FFprobe output from your camera

```shell
I think not relevant
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Hikvision

**Comment by goldiiii** [comment]
Had to plug it into the top left port on the raspberry and its working now

**Comment by finish06** [comment]
@goldiiii - I am glad you were able to solve this!  If resolved, please close the ticket with a brief explanation of what was the fix.
