### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by cdn4lf** [blakeblackshear/frigate#2612]
### Describe the problem you are having

Unable to play clip in Frigate UI.

![image](https://user-images.githubusercontent.com/49874417/148683009-8c975a75-51af-4b57-a2b9-51c94353d4f7.png)

### Version

0.10.0-Beta6

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
#    device: cpu

logger:
  default: debug

#ffmpeg:
#  hwaccel_args:
#    - -c:v
#    - h264_v4l2m2m

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: motion

detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25

record:
  enabled: true
  retain_days: 15
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    required_zones: []
    retain:
      default: 10
      objects:
        person: 15


snapshots:
  enabled: True
  timestamp: False
  bounding_box: False
  crop: False
  height: 175
  required_zones: []
  retain:
    default: 10
    objects:
      person: 15

objects:
  track:
    - person
  
rtmp:
  enabled: True

live:
  height: 720
  quality: 8
  
mqtt:
  host: X.x.x.x
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: xxxxxxxxx
  password: xxxxxxxxxx
  stats_interval: 60

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://frontdoor:xxxxxxxxxx@192.168.18.116/live
          roles:
            - detect
            - rtmp
            - record
    motion:
      mask:
        - 1110,0,1920,0,1920,1080,1335,1080,1376,924
    best_image_timeout: 30
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      required_zones: []


  walkway:
    ffmpeg:
      inputs:
        - path: rtsp://cam2:xxxxxxxxxxxx@192.168.18.114/live
          roles:
            - detect
            - rtmp
            - record
    motion:
      mask:
        - 606,283,634,326,771,315,971,478,1096,449,1089,0,418,0,283,0,338,308,431,237
    best_image_timeout: 30
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      required_zones: []
```

### Relevant log output

```shell
[2022-01-09 07:45:21] frigate.http                   ERROR   : Exception on /vod/event/1641681024.661998-3edowh [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.DatabaseError: database disk image is malformed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/frigate/frigate/http.py", line 711, in vod_event
    return vod_ts(event.camera, event.start_time, end_ts)
  File "/opt/frigate/frigate/http.py", line 650, in vod_ts
    for recording in recordings:
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 6851, in __iter__
    self.execute()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1898, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1969, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2141, in _execute
    cursor = database.execute(self)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3142, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 249, in execute_sql
    return self._execute(sql, params, commit=commit)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3136, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2902, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
peewee.DatabaseError: database disk image is malformed
```

### FFprobe output from your camera

```shell
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libfreetype --enable-libvidstab --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[rtsp @ 0x55e883619b80] UDP timeout, retrying with TCP
Input #0, rtsp, from 'rtsp://frontdoor:topsecret@192.168.18.116/live':
  Metadata:
    title           : Session streamed by the WYZE Media Server
    comment         : live
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuv420p(progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

Wyze V2

**Comment by cdn4lf** [comment]
It appears there was a problem with my volume mount. The db was present, but corrupt. I switched to a bind mount and new recordings play. The old db has been wiped out with the mount change.
