### ISSUE TITLE
[Support]: Division by zero at startup

### ISSUE THREAD

**Issue by Calimerorulez** [blakeblackshear/frigate#2758]
### Describe the problem you are having

Hi,

I just migrated my docker containers from one server to a new one.

When starting Frigate the following error is now displayed:

```
[2022-02-06 19:20:37] frigate.edgetpu                INFO    : TPU found
[2022-02-06 19:20:37] frigate.app                    INFO    : Capture process started for flex_sw: 256
[2022-02-06 19:20:37] ws4py                          INFO    : Using epoll
Process camera_processor:g4_instant:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/video.py", line 362, in track_camera
    process_frames(
  File "/opt/frigate/frigate/video.py", line 610, in process_frames
    detection_fps.value = object_detector.fps.eps()
  File "/opt/frigate/frigate/util.py", line 571, in eps
    len([t for t in self._timestamps if t > (now - last_n_seconds)]) / seconds
ZeroDivisionError: float division by zero
Process camera_processor:flex_sw:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/video.py", line 362, in track_camera
    process_frames(
  File "/opt/frigate/frigate/video.py", line 610, in process_frames
    detection_fps.value = object_detector.fps.eps()
  File "/opt/frigate/frigate/util.py", line 571, in eps
    len([t for t in self._timestamps if t > (now - last_n_seconds)]) / seconds
ZeroDivisionError: float division by zero
```

I can't seem to find out why...

### Version

0.9.4-26AE608

### Frigate config file

```yaml
detectors:
  coral_pci:
    type: edgetpu
    device: pci
mqtt:
  # Required: host name
  host: 192.168.1.8
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: frigate
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: frigate
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

cameras:

  flex_nw:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1080
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.4:7447/lt4UFRNGNfKb7rLG?enableSrtp
          roles:
            - detect
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
      filters:
        car:
          mask:
            - 530,522,473,205,0,276,0,626
    detect:
      width: 1920
      height: 1080
      fps: 5
    record: # <----- Enable recording
      enabled: True
    motion:
      mask:
        - 691,1080,492,707,0,813,0,1080
        - 630,0,803,329,524,408,384,289,191,0
        - 1760,0,1674,325,1445,329,1233,0
    zones:
      oprit:
        coordinates: 673,1080,1569,671,1258,652,547,856
      vooroprit:
        coordinates: 1012,618,1209,780,622,1000,478,772

  g4_instant:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 1512
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.4:7447/kn0msh8I7wjcExEt?enableSrtp
          roles:
            - detect
            - rtmp
            - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - cat
        - dog
    detect:
      width: 2688
      height: 1512
      fps: 5
    record:
      enabled: True

  flex_n:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 576
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.4:7447/Oyed89k7zkuKxlqz
          roles:
          - detect
          - rtmp
          - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - bicycle
        - dog
        - cat
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: True
    zones:
      zijoprit:
        coordinates: 564,576,981,478,855,306,21,377,71,576

  flex_sw:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.4:7447/eqFchgafmZoxHufA
          roles:
          - detect
          - rtmp
          - record
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 7
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - cat
        - dog
      filters:
        car:
          mask:
            - 982,396,967,234,651,214,589,347
            - 425,306,429,199,324,205,267,296
            - 189,177,186,257,118,271,21,266,24,197
    detect:
      width: 1024
      height: 576
      fps: 5
    record:
      enabled: True
    motion:
      mask:
        - 1024,0,1024,245,955,247,869,125,923,0
        - 841,108,813,163,781,159,765,105,801,70,784,69
        - 432,0,653,0,693,97,675,196,534,306,463,250,383,99
        - 872,576,865,450,197,312,79,461,329,576
        - 211,137,305,150,308,177,230,191,150,200,140,152
```

### Relevant log output

```shell
[2022-02-06 19:20:37] frigate.edgetpu                INFO    : TPU found
[2022-02-06 19:20:37] frigate.app                    INFO    : Capture process started for flex_sw: 256
[2022-02-06 19:20:37] ws4py                          INFO    : Using epoll
Process camera_processor:g4_instant:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/video.py", line 362, in track_camera
    process_frames(
  File "/opt/frigate/frigate/video.py", line 610, in process_frames
    detection_fps.value = object_detector.fps.eps()
  File "/opt/frigate/frigate/util.py", line 571, in eps
    len([t for t in self._timestamps if t > (now - last_n_seconds)]) / seconds
ZeroDivisionError: float division by zero
Process camera_processor:flex_sw:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/video.py", line 362, in track_camera
    process_frames(
  File "/opt/frigate/frigate/video.py", line 610, in process_frames
    detection_fps.value = object_detector.fps.eps()
  File "/opt/frigate/frigate/util.py", line 571, in eps
    len([t for t in self._timestamps if t > (now - last_n_seconds)]) / seconds
ZeroDivisionError: float division by zero
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Unifi G3/G4

**Comment by blakeblackshear** [comment]
Does this happen consistently? I have never seen that happen before. I can see how it could happen, but it seems like an edge case that would only occur rarely.

**Comment by Calimerorulez** [comment]
I've just upgraded to the latest beta to test it, and the error disappeared... :)

**Comment by blakeblackshear** [comment]
I think that was just by chance since the code related to this error hasn't changed. I will add a check to handle this edge case before the next release.

**Comment by Calimerorulez** [comment]
> I think that was just by chance since the code related to this error hasn't changed. I will add a check to handle this edge case before the next release.

I think it was related with copy/paste. I've just added a object mask to the config, generated by the web UI, and pasted it in the config via SSH/Putty. I restarted Frigate and the error showed again. I manually then typed the coordinates instead of pasting and the error was resolved...
