### ISSUE TITLE
`queue full` after moving view

### ISSUE THREAD

**Issue by jon102034050** [blakeblackshear/frigate#29]
Upon starting up frigate, I see image processing is working as it'll immediately recognize my car in frame (cam is in the garage). The moment I walk into frame, I see the following stacktrace:

```Capture process for garage: 29
 * Serving Flask app "detect_objects" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
On connect called
192.168.45.81 - - [06/May/2019 21:31:54] "GET /garage HTTP/1.1" 200 -
On connect called
On connect called
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/object_detection.py", line 55, in run
    self.cameras[frame['camera_name']].add_objects(parsed_objects)
  File "/opt/frigate/frigate/video.py", line 219, in add_objects
    y_location = min(int(obj['ymax']), len(self.mask)-1)
TypeError: object of type 'NoneType' has no len()
queue full. moving on
queue full. moving on
queue full. moving on
queue full. moving on
queue full. moving on
queue full. moving on
```

After I see this behavior, the container needs to be restarted in order for image processing to start working again. 
I have 1 camera (hikvision) with 1 zone. Camera is 1080p, 4fps, I Frame Interval of 4, max bitrate of 512.

I don't believe it's a usb3.0 vs usb2.0 problem based upon the following: 

```root@nuc:~# lsusb -v
Bus 003 Device 003: ID 18d1:9302 Google Inc.
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               3.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         9
  idVendor           0x18d1 Google Inc.
```
and
```root@nuc:~# lsusb -t
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 4: Dev 3, If 0, Class=Vendor Specific Class, Driver=usbfs, 5000M
```
Thoughts?

**Comment by jon102034050** [comment]
I believe I just resolved this myself.... literally right after I opened it - my mask file didn't exist.
