### ISSUE TITLE
[Support]: Cameras started triggering Birdseye without seeing an object

### ISSUE THREAD

**Issue by tinimark** [blakeblackshear/frigate#2922]
### Describe the problem you are having

After the latest update of Frigate including the lovelace card my cameras are now popping up in Birdseye randomly without the camera seeing or registering an object detection. This was working fine before the update. I've tried uninstalling and reinstalling and I also get the same behavior with the beta versions. Also seeing a lot of errors in the log file

### Version

0.10.0-BFECEE9

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.50
  user: admin
  password: xx
detect:
  max_disappeared: 5
  width: 1280
  height: 720
  fps: 5
record:
  enabled: True
  events:
    retain:
      default: 10  
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects  




cameras:
  front_drive:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:xx@192.xx.1.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
            - record
    detect:
      max_disappeared: 20
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 1920,0,1920,162,1565,447,766,387,594,455,0,498,0,393,0,0
    objects:
      track:
        - person
        - car
        - motorcycle
        - bicycle
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5



#  front_door:
#    ffmpeg:
#      hwaccel_args:
#        - -hwaccel
#        - qsv
#        - -qsv_device
#        - /dev/dri/renderD128
#      inputs:
#        - path: rtsp://admin:xx@192.xx.1.24:554/cam/realmonitor?channel=1&subtype=0
#          roles:
#           - rtmp
#           - record
#        - path: rtsp://admin:xx@192.168.1.24:554/cam/realmonitor?channel=1&subtype=1
#          roles:   
#            - detect
#    detect:
#      max_disappeared: 20
#      width: 640
#      height: 480
#      fps: 5
#    objects:
#      track:
#        - person
#        - cat
#        - dog
#    snapshots:
#      enabled: true
#      timestamp: true
#      bounding_box: true
#      retain:
#        default: 5



  rear_patio:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://ha:xx@192.xx.1.19:554/Streaming/Channels/101
          roles:
           - detect
           - rtmp
           - record

    detect:
      max_disappeared: 20
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5


  front_garden:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://ha:xx@192.xx.1.21:554/Streaming/Channels/101
          roles:
           - detect
           - rtmp
           - record

    detect:
      max_disappeared: 20
      width: 1920
      height: 1080
      fps: 5
    motion:
      mask:
        - 219,1080,325,820,55,601,0,185,400,138,730,386,1026,1080
        - 1920,86,1920,390,1370,400,1379,154,1497,90
    objects:
      track:
        - person
        - car
        - cat
        - dog
      filters:
        person:
          max_area: 700000
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5




  car_park:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://ha:xx@192.xx.1.20:554/Streaming/Channels/101
          roles:
           - detect
           - rtmp
           - record

    detect:
      max_disappeared: 20
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
  
  
  
  
  rear_balcony:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:xx@192.xx.1.25:554/Streaming/Channels/101
          roles:
           - rtmp
           - record
        - path: rtsp://admin:xx@192.xx.1.25:554/Streaming/Channels/102
          roles:   
            - detect
    detect:
      max_disappeared: 20
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5
    


  front_balcony:
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:xx@192.xx.1.26:554/Streaming/Channels/101
          roles:
           - detect
           - rtmp
           - record

    detect:
      max_disappeared: 20
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 5    
      
        
        
detectors:
  coral1:
    type: edgetpu
    device: pci:0
```

### Relevant log output

```shell
[2022-03-07 19:56:17] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:49830]
[2022-03-07 20:14:17] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:58330]
[2022-03-07 20:23:03] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:58330]
[2022-03-07 20:44:03] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39450]
[2022-03-07 20:54:04] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-03-07 20:54:04] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39450]
[2022-03-07 20:58:15] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:43924]
[2022-03-07 20:59:19] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44296]
[2022-03-07 20:59:24] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44296]
[2022-03-07 20:59:30] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:33960]
[2022-03-07 21:01:08] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:33960]
[2022-03-07 21:13:18] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-03-07 21:13:18] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:43924]
[2022-03-07 21:15:17] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:49604]
[2022-03-07 21:25:41] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:49604]
[2022-03-07 21:56:42] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:34408]
[2022-03-07 21:56:42] frigate.output                 WARNING : Unable to copy frame front_drive1646688337.739061 to birdseye.
[2022-03-07 22:07:31] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-03-07 22:07:31] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:34408]
[2022-03-07 22:13:48] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39872]
[2022-03-07 22:25:02] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-03-07 22:25:02] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:39872]
[2022-03-08 02:19:53] watchdog.front_drive           INFO    : No frames received from front_drive in 20 seconds. Exiting ffmpeg...
[2022-03-08 02:19:53] watchdog.front_drive           INFO    : Waiting for ffmpeg to exit gracefully...
[2022-03-08 02:19:59] frigate.video                  ERROR   : front_drive: Unable to read frames from ffmpeg process.
[2022-03-08 02:19:59] frigate.video                  ERROR   : front_drive: ffmpeg process is not running. exiting capture thread...
[2022-03-08 02:20:09] watchdog.front_drive           ERROR   : Ffmpeg process crashed unexpectedly for front_drive.
[2022-03-08 02:20:09] watchdog.front_drive           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-08 02:20:09] ffmpeg.front_drive.detect      ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
[2022-03-08 02:20:09] ffmpeg.front_drive.detect      ERROR   : [swscaler @ 0x565362f7c240] deprecated pixel format used, make sure you did set range correctly
[2022-03-08 02:20:09] ffmpeg.front_drive.detect      ERROR   : [h264 @ 0x565362bb6240] Increasing reorder buffer to 1
[2022-03-08 02:20:09] ffmpeg.front_drive.detect      ERROR   : [h264 @ 0x565362bb6240] Increasing reorder buffer to 15
[2022-03-08 02:20:09] ffmpeg.front_drive.detect      ERROR   : [flv @ 0x565362ad4340] Failed to update header with correct duration.
[2022-03-08 02:20:09] ffmpeg.front_drive.detect      ERROR   : [flv @ 0x565362ad4340] Failed to update header with correct filesize.
[2022-03-08 02:20:09] frigate.video                  ERROR   : front_drive: Unable to read frames from ffmpeg process.
[2022-03-08 02:20:09] frigate.video                  ERROR   : front_drive: ffmpeg process is not running. exiting capture thread...
[2022-03-08 02:20:19] watchdog.front_drive           ERROR   : Ffmpeg process crashed unexpectedly for front_drive.
[2022-03-08 02:20:19] watchdog.front_drive           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-08 02:20:19] ffmpeg.front_drive.detect      ERROR   : [tcp @ 0x5647a07ff700] Connection to tcp://192.168.1.22:554?timeout=5000000 failed: Connection refused
[2022-03-08 02:20:19] ffmpeg.front_drive.detect      ERROR   : rtsp://admin:xx@192.xx.1.22:554/cam/realmonitor?channel=1&subtype=0: Connection refused
[2022-03-08 02:20:19] frigate.video                  ERROR   : front_drive: Unable to read frames from ffmpeg process.
[2022-03-08 02:20:19] frigate.video                  ERROR   : front_drive: ffmpeg process is not running. exiting capture thread...
[2022-03-08 02:20:29] watchdog.front_drive           ERROR   : Ffmpeg process crashed unexpectedly for front_drive.
[2022-03-08 02:20:29] watchdog.front_drive           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-08 02:20:29] ffmpeg.front_drive.detect      ERROR   : [tcp @ 0x56419b625700] Connection to tcp://192.168.1.22:554?timeout=5000000 failed: Connection refused
[2022-03-08 02:20:29] ffmpeg.front_drive.detect      ERROR   : rtsp://admin:xx@192.xx.1.22:554/cam/realmonitor?channel=1&subtype=0: Connection refused
[2022-03-08 02:20:29] frigate.video                  ERROR   : front_drive: Unable to read frames from ffmpeg process.
[2022-03-08 02:20:29] frigate.video                  ERROR   : front_drive: ffmpeg process is not running. exiting capture thread...
[2022-03-08 02:20:39] watchdog.front_drive           ERROR   : Ffmpeg process crashed unexpectedly for front_drive.
[2022-03-08 02:20:39] watchdog.front_drive           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-08 02:20:39] ffmpeg.front_drive.detect      ERROR   : [tcp @ 0x562bd128d700] Connection to tcp://192.168.1.22:554?timeout=5000000 failed: Connection refused
[2022-03-08 02:20:39] ffmpeg.front_drive.detect      ERROR   : rtsp://admin:xx1@192.xx.1.22:554/cam/realmonitor?channel=1&subtype=0: Connection refused
[2022-03-08 02:20:39] frigate.video                  ERROR   : front_drive: Unable to read frames from ffmpeg process.
[2022-03-08 02:20:39] frigate.video                  ERROR   : front_drive: ffmpeg process is not running. exiting capture thread...
[2022-03-08 02:20:49] watchdog.front_drive           ERROR   : Ffmpeg process crashed unexpectedly for front_drive.
[2022-03-08 02:20:49] watchdog.front_drive           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-08 02:20:49] ffmpeg.front_drive.detect      ERROR   : [tcp @ 0x55dd91822700] Connection to tcp://192.xx.1.22:554?timeout=5000000 failed: Connection refused
[2022-03-08 02:20:49] ffmpeg.front_drive.detect      ERROR   : rtsp://admin:xx@192.xx.1.22:554/cam/realmonitor?channel=1&subtype=0: Connection refused
[2022-03-08 02:20:49] frigate.video                  ERROR   : front_drive: Unable to read frames from ffmpeg process.
[2022-03-08 02:20:49] frigate.video                  ERROR   : front_drive: ffmpeg process is not running. exiting capture thread...
[2022-03-08 02:20:59] watchdog.front_drive           ERROR   : Ffmpeg process crashed unexpectedly for front_drive.
[2022-03-08 02:20:59] watchdog.front_drive           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-03-08 02:20:59] ffmpeg.front_drive.detect      ERROR   : [tcp @ 0x560217bd9700] Connection to tcp://192.168.1.22:554?timeout=5000000 failed: Connection refused
[2022-03-08 02:20:59] ffmpeg.front_drive.detect      ERROR   : rtsp://admin:xx@192.xx.1.22:554/cam/realmonitor?channel=1&subtype=0: Connection refused
[2022-03-08 06:17:51] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:49632]
[2022-03-08 06:25:41] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:49632]
[2022-03-08 06:32:19] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:54196]
[2022-03-08 06:41:24] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:54196]
[2022-03-08 06:41:35] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57156]
[2022-03-08 06:47:01] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48460]
[2022-03-08 06:47:32] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48460]
[2022-03-08 06:50:58] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57156]
[2022-03-08 06:51:04] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:60292]
[2022-03-08 07:04:45] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:60292]
[2022-03-08 07:20:12] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:41222]
[2022-03-08 07:20:12] frigate.output                 WARNING : Unable to copy frame front_balcony1646723033.549084 to birdseye.
[2022-03-08 07:27:37] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-03-08 07:27:37] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:41222]
[2022-03-08 07:29:01] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:33616]
[2022-03-08 07:29:14] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:33616]
```

### FFprobe output from your camera

```shell
not sure how to do this but no camera settings have been changed since it was last working fine.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

dahua and hik

**Comment by tinimark** [comment]
Thanks. Has something changed with the sensitivity? The camera in debug mode is showing a lot of motion and bounding boxes for essentially a still scene. It was working very well before the last update.
Also, I'm interested to know more about frigate+ and how it will work when signed up.

**Comment by blakeblackshear** [comment]
Yes. The contrast is now adjusted dynamically. You can try increasing your threshold value in the motion settings. Several users have reported issues with the new dynamic contrast, and I am looking at options.

Frigate+ is free to setup an account and submit labeled images.

The complete launch plan is as follows:
1. Launch web version allowing manual upload of training examples and labeling. - **Done**
2. Integrate submission and labeling in Frigate. - **In Progress**
3. Launch Frigate optimized models. - **In Progress**
4. Launch individually optimized models.

The first 2 phases will be free. Optimized models will require a subscription.

**Comment by tinimark** [comment]
Just want to be clear this is working as designed. It's possible for the camera to trigger birdseye on a false positive but also not create an event?
Is it possible to have the birdseye only trigger when an event is triggered?

**Comment by blakeblackshear** [comment]
> It's possible for the camera to trigger birdseye on a false positive but also not create an event?

Yes. It is optimized to start showing video as soon as possible since it is a heads up display.

> Is it possible to have the birdseye only trigger when an event is triggered?

Not currently.
