### ISSUE TITLE
[Support]: Filters for multiple objects?

### ISSUE THREAD

**Issue by villasenor** [blakeblackshear/frigate#2957]
### Describe the problem you are having

I'm trying to add a threshold filter for multiple objects, but apparently, that is not permitted? Did I mess this up or is this a bug? I only see one object having filters applied in the docs.

### Version

0.10.1

### Frigate config file

```yaml
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - bear
    - cat

  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      # min_area: 5000
      # # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      # max_area: 100000
      # # Optional: minimum score for the object to initiate tracking (default: shown below)
      # min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
    dog:
      threshhold: 0.7
    bear:
      threshold: 0.7
    cat:
      threshold: 0.7
```

### Relevant log output

```shell
[2022-03-13 05:07:36] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
objects -> filters -> dog -> threshhold
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
objects -> filters -> dog -> threshhold
  extra fields not permitted (type=value_error.extra)

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

### Any other information that may be helpful

Only included the relevant parts of my frigate config. Let me know if you need more!

**Comment by blakeblackshear** [comment]
You spelled threshold wrong for dog.

**Comment by villasenor** [comment]
Wow. Yep totally works now. So sorry about that - probably should wait until the next day to re-read my code before I open issues :see_no_evil: Thanks so much @blakeblackshear.
