### ISSUE TITLE
[Support]: Latest 0.11 docker doesnt come up - no cameras connect

### ISSUE THREAD

**Issue by vertex-github** [blakeblackshear/frigate#3135]
### Describe the problem you are having

I tried updating to the latest Docker 0.11 image - none of my cameras came up.  Dropped back to the previous image which worked ok but it seems that the newer version made non backwards compatible changes to the internal DB.  I removed all stored data and the older version comes back just fine.  nothing in the docker logs jumped out at me as a cause.

### Version

0.11.0-eb39251

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
This is for the rollback SQL failure:

Exception in thread event_processor:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/events.py", line 67, in run
    Event.replace(
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 1911, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 1982, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2761, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2480, in _execute
    return self.handle_result(database, cursor)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2770, in handle_result
    return database.last_insert_id(cursor, self._query_type)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3249, in last_insert_id
    return cursor.lastrowid
  File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 88, in lastrowid
    self._wait()
  File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3167, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely
[2022-04-24 18:57:49] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:54066]
[cont-finish.d] executing container finish scripts...
```
```


### FFprobe output from your camera

```shell
n/a
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Amcrest,Reolink,Axis

**Comment by blakeblackshear** [comment]
There is no existing beta release for 0.11.0. I don't recommend trying random tags in docker hub from active development branches.

**Comment by vertex-github** [comment]
Then i won't try random tags in docker in future and give early feedback.
:-)
