### ISSUE TITLE
[Support]:  Installing MQTT + Frigate NVR on 2022.4.7 Causing reboot loops

### ISSUE THREAD

**Issue by Buster14** [blakeblackshear/frigate#3146]
### Describe the problem you are having

So as the title says,
1. setup mqtt addon, and user + password
2. install frigate, managed to get camera working, 
3. HA reboot 
4. After reboot, sidebar > frigate to check camera, HA reboot.
5. Only way to stop this is to stop frigate, HA stops rebooting once i stop it 
6. I also have another installation on 2022.4.6 with frigate + mqtt and it doesnt have this issue, so it led me thinking it has something to do with newer version.

### Version

3.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.100.21
  user: gowongan33
  password: gowongan33
cameras:
  Living_Room: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:pass@192.168.100.105:105/Streaming/Channels/2/# <----- Update for your camera
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    motion:
      mask:    
        - 0,71,408,62,407,25,0,25  
    zones:
      zone_0:
        coordinates: 0,538,29,571,93,632,117,668,139,673,200,673,315,678,447,680,559,681,636,668,774,663,896,663,1010,661,1075,646,1047,594,1051,520,1012,425,961,362,905,306,808,307,688,286,541,284,381,281,184,286
logger:
  default: info
  logs:
    watchdog.<camera_1>: debug
```

### Relevant log output

```shell
2022-04-26 11:05:11 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/automations.yaml contains duplicate key "alias". Check lines 1 and 20
2022-04-26 11:05:11 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/automations.yaml contains duplicate key "trigger". Check lines 5 and 21
2022-04-26 11:05:11 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/automations.yaml contains duplicate key "action". Check lines 13 and 26
2022-04-26 11:05:11 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dahua_vto which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-26 11:05:11 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-26 11:05:11 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-26 11:05:11 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-26 11:05:11 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2022-04-26 11:05:11 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=6 from 2022-04-26 04:02:39.075505)
2022-04-26 11:05:11 WARNING (MainThread) [homeassistant.components.lovelace] Lovelace is running in storage mode. Define resources via user interface
2022-04-26 11:05:18 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:18 Server Start Awaiting Signal
2022-04-26 11:05:28 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:28 Stream Try Connect rtsp://admin:gowongan33@192.168.100.33:554/cam/realmonitor?channel=1&subtype=1
2022-04-26 11:05:29 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:29 Stream Try Connect rtsp://admin:pass@192.168.100.104:104/Streaming/Channels/102/
2022-04-26 11:05:29 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:29 Set ICEServers [stun:stun.l.google.com:19302]
2022-04-26 11:05:29 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:29 WebRTC Ignore Audio Track codec not supported WebRTC support only PCM_ALAW or PCM_MULAW
2022-04-26 11:05:30 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:30 Set ICEServers [stun:stun.l.google.com:19302]
2022-04-26 11:05:32 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:32 websocket.JSON.Receive EOF
2022-04-26 11:05:32 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/26 - 11:05:32 | 200 | 3.309685223s | 127.0.0.1 | GET "/ws?url=rtsp://admin:pass@192.168.100.104:104/Streaming/Channels/102/"
2022-04-26 11:05:33 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/26 11:05:33 websocket.JSON.Receive EOF
2022-04-26 11:05:33 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/26 - 11:05:33 | 200 | 4.552848013s | 127.0.0.1 | GET "/ws?url=rtsp://admin:pass@192.168.100.33:554/cam/realmonitor?channel%3D1%26subtype%3D1"
```

### FFprobe output from your camera

```shell
Can't do this since HA always reboots
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision

### Any other information that may be helpful

There's also another error but i'm not sure if its related since it's pretty generic

Logger: aiohttp.server
Source: components/hassio/http.py:109
First occurred: 11:22:48 AM (1 occurrences)
Last logged: 11:22:48 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/hassio/http.py", line 73, in _handle
    return await self._command_proxy(path, request)
  File "/usr/src/homeassistant/homeassistant/components/hassio/http.py", line 109, in _command_proxy
    await response.prepare(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 131, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_writer.py", line 76, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Comment by NickM-27** [comment]
This sounds like an HA issue, not something that frigate can control especially if it is only happening in one HA instance and not another

**Comment by Buster14** [comment]
So is it related to new update, or that installation of mine is broken somehow?

`2022-04-26 11:05:11 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly`

This part of the log makes me think it's the later.. i'm gonna try reverting to older version to see if it fixes the issue.
The thing is, the reboot loop only happens when i activate frigate addon and debug a cam... Otherwise its running just fine until now.

**Comment by Buster14** [comment]
So i made partial backup, redownloaded HA image for vmware.
restore the backup to 2022.4.4. At first there is no reboot when i created the cam configs.
But then i created automation based on frigate motion detection, the automation doesnt kick in.
When i check back the frigate to see why, HA reboots throwing this error again

```
2022-04-27 05:42:01 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dahua_vto which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-27 05:42:01 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-27 05:42:01 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-27 05:42:01 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-27 05:42:01 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2022-04-27 05:42:02 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=143 from 2022-04-26 17:16:47.555684)
2022-04-27 05:42:02 WARNING (MainThread) [homeassistant.components.lovelace] Lovelace is running in storage mode. Define resources via user interface
2022-04-27 05:42:07 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:07 Server Start Awaiting Signal
2022-04-27 05:42:18 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:18 Stream Try Connect rtsp://admin:pass@192.168.100.33:554/cam/realmonitor?channel=1&subtype=1
2022-04-27 05:42:18 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:18 Stream Try Connect rtsp://admin:pass@192.168.100.104:104/Streaming/Channels/102/
2022-04-27 05:42:19 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:19 Set ICEServers [stun:stun.l.google.com:19302]
2022-04-27 05:42:19 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:19 WebRTC Ignore Audio Track codec not supported WebRTC support only PCM_ALAW or PCM_MULAW
2022-04-27 05:42:19 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:19 Set ICEServers [stun:stun.l.google.com:19302]
2022-04-27 05:42:21 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:21 websocket.JSON.Receive EOF
2022-04-27 05:42:21 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/27 - 05:42:21 | 200 | 2.684134383s | 127.0.0.1 | GET "/ws?url=rtsp://admin:pass@192.168.100.33:554/cam/realmonitor?channel%3D1%26subtype%3D1"
2022-04-27 05:42:21 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/27 05:42:21 websocket.JSON.Receive EOF
2022-04-27 05:42:21 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/27 - 05:42:21 | 200 | 3.341655384s | 127.0.0.1 | GET "/ws?url=rtsp://admin:pass@192.168.100.104:104/Streaming/Channels/102/
```"

Is it conflicting with webrtc? I'm using it to display front gate.

**Comment by NickM-27** [comment]
I don't really see how creating an automation would cause HA to entirely crash so seems something else is going on. If webrtc is running as an addon then perhaps they have conflicting ports.

**Comment by Buster14** [comment]
Ok i've disabled webrtc, will see if it crashes again.
Thing is, i need live view of 2 cams. And frigate with the second option i.e "Home Assistant (i.e. HLS, LL-HLS, WebRTC native)"
Is just too slow for live viewing.
But if i enable webrtc it could crash again.. any thoughts ?

**Comment by blakeblackshear** [comment]
What hardware are you running this on? I'm wondering if anything that generates sufficient load will cause a restart. I don't see any reason to suspect that Frigate specifically is at fault here.

**Comment by Buster14** [comment]
I5 8400 windows host + vmware workstation for running HA. I disabled the motion based automation and readded webrtc and it 's not crashing so probably it has something to do with hardware..

**Comment by Buster14** [comment]
Update : i noticed on my vmware workstation command line, HA keeps running out of memory, after increasing the memory to 8gb it doesn't seem to be happening again. So probably has something to do with memory.
