### ISSUE TITLE
[Support]: Hass Entity unavailable, and can't toggle recordings and snapshots.

### ISSUE THREAD

**Issue by FranticM3rcury** [blakeblackshear/frigate#3166]
### Describe the problem you are having

With camera everything works very good, but when I tried to add camera to HomeAssistant then I can see the picture, but none of the entities are working and buttons can't toggle.

When I googled this issue, I saw several with similar issue, but with them there was MQTT setting error, but with mine I can assure MQTT works perfectly. With MQTT Explorer I can see Frigate doing it's stuff, and I can Publish to turn off Recordings/Snapshots manually from there. (included pic below)

Additional info
Hass is on docker on an intel device with localip.13
Frigate is on docker on an intel device with localip.13
MQTT Broker is on docker on Synology NAS with localip.15

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: localip.15
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: password

ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

cameras:
  tapoc210:
    ffmpeg:
      inputs:
        - path: rtsp://tapoauser:userpassword@localip.49:554/stream2
          roles: 
            - detect
            - rtmp
        - path: rtsp://tapoauser:userpassword@localip.49:554/stream1
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    objects:
      track:
        - person
        - car
        - cat
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 0
      events:
        retain:
          default: 2
          mode: motion
```

### Relevant log output

```shell
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[2022-04-29 23:31:44] frigate.video                  ERROR   : tapoc210: Unable to read frames from ffmpeg process.
[2022-04-29 23:31:44] frigate.video                  ERROR   : tapoc210: ffmpeg process is not running. exiting capture thread...
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-04-29 23:31:49] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-04-29 23:31:49] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-04-29 23:31:49] peewee_migrate                 INFO    : There is nothing to migrate
[2022-04-29 23:31:49] frigate.app                    INFO    : Output process started: 219
[2022-04-29 23:31:49] frigate.app                    INFO    : Camera processor started for tapoc210: 221
[2022-04-29 23:31:49] ws4py                          INFO    : Using epoll
[2022-04-29 23:31:49] frigate.app                    INFO    : Capture process started for tapoc210: 223
[2022-04-29 23:31:49] detector.cpu                   INFO    : Starting detection process: 218
[2022-04-29 23:31:49] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-04-29 23:31:49] ws4py                          INFO    : Using epoll
[2022-04-29 23:46:52] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49090]
[2022-04-29 23:49:19] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49250]
[2022-04-29 23:49:20] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49250]
[2022-04-29 23:49:59] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49090]
```

### FFprobe output from your camera

```shell
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://tapouser:userpassword@localip.49:554/stream1':
  Metadata:
    title           : Session streamed by "TP-LINK RTSP Server"
    comment         : stream2
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 14 fps, 14.25 tbr, 90k tbn, 28 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Tapo C210

### Any other information that may be helpful

I can see snapshots and records in HA media browser. Also if I changed camera name or deleted Frigate integration from Hass, then detect sensors entities became unable to delete, couldn't figure out the fix for that as well.

<img width="664" alt="Screenshot 2022-04-29 at 23 35 12" src="https://user-images.githubusercontent.com/76600057/166068742-0c314c90-19c2-4479-bb8e-ca20e9a0d244.png">

<img width="598" alt="Screenshot 2022-04-30 at 00 06 29" src="https://user-images.githubusercontent.com/76600057/166069187-1464d4a4-97e9-4dda-9331-a0ad5a0941ee.png">

**Comment by blakeblackshear** [comment]
All the sensors that are unavailable are MQTT based. They go offline when the available message is not received for frigate. Do you see any errors in the home assistant logs?

**Comment by NickM-27** [comment]
What version of the integration are you on? 2.2.2 is the latest and fixed a break in HA 2022.3

**Comment by FranticM3rcury** [comment]
Yes, it gave me 4 errors:

1)

```
Logger: homeassistant.components.sensor
Source: custom_components/frigate/__init__.py:369 
Integration: Sensor (documentation, issues) 
First occurred: 00:35:31 (2 occurrences) 
Last logged: 00:35:31

Error adding entities for domain sensor with platform frigate
Error while setting up frigate platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 798, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/frigate/__init__.py", line 369, in async_added_to_hass
    self._sub_state = await async_subscribe_topics(
TypeError: async_subscribe_topics() takes 2 positional arguments but 3 were given 
```

2)

```
Logger: homeassistant.components.camera
Source: custom_components/frigate/__init__.py:369 
Integration: Camera (documentation, issues) 
First occurred: 00:35:31 (2 occurrences) 
Last logged: 00:35:31

Error adding entities for domain camera with platform frigate
Error while setting up frigate platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 798, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/frigate/__init__.py", line 369, in async_added_to_hass
    self._sub_state = await async_subscribe_topics(
TypeError: async_subscribe_topics() takes 2 positional arguments but 3 were given
```

3)

```
Logger: homeassistant.components.switch
Source: custom_components/frigate/__init__.py:369 
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22)) 
First occurred: 00:35:31 (2 occurrences) 
Last logged: 00:35:31

Error adding entities for domain switch with platform frigate
Error while setting up frigate platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 798, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/frigate/__init__.py", line 369, in async_added_to_hass
    self._sub_state = await async_subscribe_topics(
TypeError: async_subscribe_topics() takes 2 positional arguments but 3 were given
```

4)

```
Logger: homeassistant.components.binary_sensor
Source: custom_components/frigate/__init__.py:369 
Integration: Binary Sensor (documentation, issues) 
First occurred: 00:35:31 (2 occurrences) 
Last logged: 00:35:31

Error adding entities for domain binary_sensor with platform frigate
Error while setting up frigate platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 798, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/frigate/__init__.py", line 369, in async_added_to_hass
    self._sub_state = await async_subscribe_topics(
TypeError: async_subscribe_topics() takes 2 positional arguments but 3 were given
```

I hope this helps

**Comment by NickM-27** [comment]
Looks like that's the issue that was fixed, please check / update integration version. 

Commit for reference: https://github.com/blakeblackshear/frigate-hass-integration/pull/213/commits/8f1a5e9a010ca66a516c1cd823cdca4342729e74

**Comment by FranticM3rcury** [comment]
> What version of the integration are you on? 2.2.2 is the latest and fixed a break in HA 2022.3

2022.4.7 Hass but 2.2.1 Frigate integration

**Comment by FranticM3rcury** [comment]
> Looks like that's the issue that was fixed, please check / update integration version.
> 
> Commit for reference: [blakeblackshear/frigate-hass-integration@8f1a5e9](https://github.com/blakeblackshear/frigate-hass-integration/commit/8f1a5e9a010ca66a516c1cd823cdca4342729e74)

Sry if stupid question - how? isn't the latest 2.2.1?

**Comment by NickM-27** [comment]
Seems there may be a glitch with HACS but 2.2.2 is the latest: https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v2.2.2

**Comment by FranticM3rcury** [comment]
> Seems there may be a glitch with HACS but 2.2.2 is the latest: https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v2.2.2

Thx, yes this fixed it.

**Comment by NickM-27** [comment]
@FranticM3rcury Should be able to close this. If anything else comes up then a new issue can be created 👍

**Comment by spacebares** [comment]
top result on google for unavailable frigate camera entities.
for me, deleting & re-adding MQTT broker solved the problem, bringing all entities back online.

**Comment by roman-upv** [comment]
>

**Comment by roman-upv** [comment]
> All the sensors that are unavailable are MQTT based. They go offline when the available message is not received for frigate. Do you see any errors in the home assistant logs?

TRUE. In my case, DHCP had changed MQTT server IP... ;-)
(Rookie mistake. Better to use fixed IPs)

**Comment by Charlielx** [comment]
> > All the sensors that are unavailable are MQTT based. They go offline when the available message is not received for frigate. Do you see any errors in the home assistant logs?
> 
> TRUE. In my case, DHCP had changed MQTT server IP... ;-) (Rookie mistake. Better to use fixed IPs)

I am so glad you said this! Been slamming my head against this for a few days and just could not figure it out until I found this. Funniest part is it happened because I changed my IP Schema and just 100% blanked on the mqtt config in frigate 🤦
