### ISSUE TITLE
[Support]: Beta11 Can't Find FFMPEG

### ISSUE THREAD

**Issue by esmoyer** [blakeblackshear/frigate#3223]
### Describe the problem you are having

Looks like I'm getting green screens with the new beta build, which I assume is due to what you mentioned as I have not changed anything else with moving to the beta. Excited to get it going!

EDIT: Sorry my stats kept pasting weird. Let me know if you need more or other info!

### Version

0.11.0-beta2

### Frigate config file

```yaml
mqtt:
  host: 10.XXXX
  port: XXXX
  topic_prefix: frigate
  client_id: frigate
  user: XXXX
  password: XXXX
 
detectors:
  coral:
    type: edgetpu
    device: usb
    
database:
  path: /media/frigate/db/frigate.db

logger:
  default: info
  # logs:
    # frigate.event: debug

birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 4  # 1 is the highest quality, and 31 is the lowest.
  mode: motion

cameras:
########## CAMERAS
#################### DRIVEWAY
  Driveway:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX/live0 
        #- path: rtsp://XXXX/live0
          roles:
            - detect
            - record
      global_args: 
        -hide_banner 
        -loglevel error
      hwaccel_args: 
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args: []
          # -avoid_negative_ts make_zero 
          # -fflags +genpts+discardcorrupt 
          # -rtsp_transport tcp 
          # -stimeout 5000000 
          # -use_wallclock_as_timestamps 1
      output_args:
        record: 
          -f segment 
          -segment_time 10 
          -segment_format mp4 
          -reset_timestamps 1 
          -strftime 1 
          -c copy #-am

    detect:
      enabled: true 
      max_disappeared: 30
      width: 1920
      height: 1080
      fps: 5
      stationary:
        interval: 0
        threshold: 50
        # max_frames:
          # default: 3000
      
    objects: 
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_area: 1100
          max_area: 400000
          min_score: 0.68
          threshold: 0.74
          mask:
            - 22,328,107,324,118,292,21,305
        dog:
          min_area: 1000
          max_area: 50000
          min_score: 0.60
          threshold: 0.65
        car:
          min_area: 5000
          max_area: 250000
          min_score: 0.67
          threshold: 0.73
          mask:
            - 287,124,434,201,1019,204,1044,50,906,0,835,0,578,0,313,0
            - 1428,234,1735,321,1920,350,1834,244,1664,191,1537,184,1429,185
            - 1051,113,1294,139,1222,29,1047,0
            - 274,27,266,77,151,148,39,175,183,42

    motion:
      threshold: 25
      improve_contrast: true
      mask:
        - 1920,0,1920,54,1920,243,1310,60,1327,0
        - 1920,1080,1920,827,1920,428,1615,751,1723,1080
        - 165,63,190,55,390,0,0,0,0,137

    record:
      enabled: true
      retain:
        days: 14
        mode: all
      events:
        max_seconds: 600
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - car
        retain:
          default: 30
          objects:
            car: 14

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false 
      retain:
        default: 30
        
    rtmp:
      enabled: false

    timestamp_style:
      position: "bl"
      thickness: 2

    best_image_timeout: 30
    
    zones:  
      zone_driveway:
        coordinates: 872,1080,1513,1080,1920,1080,1920,746,1729,558,1622,463,1331,428,947,396
        
      zone_driveway_entry:
        coordinates: 947,324,1270,354,1543,392,1528,365,1225,328,938,307
      
      zone_front_lawn:
        coordinates: 916,375,554,365,236,367,0,380,0,712,364,852,815,955
      
      zone_front_sidewalk:
        coordinates: 0,365,274,348,683,341,1254,387,1759,456,1713,420,1472,376,1204,344,868,319,586,314,263,317,0,334
      
      zone_street:
        coordinates: 291,187,107,212,101,287,422,263,835,263,1412,326,1865,412,1832,332,1624,258,1308,202,952,165,559,159

      zone_neighbors_driveway_entry:
        coordinates: 93,188,128,166,33,183,0,204

      zone_adamally_driveway_entry:
        coordinates: 447,126,466,112,257,138,235,152

      zone_janejodi_driveway_entry:
        coordinates: 1036,122,1326,155,1316,145,1048,115        
      
################### DOORBELL
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX/realmonitor?channel=1&subtype=0&authbasic=64
        #- path: rtsp://XXXX/realmonitor?channel=1&subtype=0&authbasic=64
          roles:
            - detect
            - record
      global_args: -hide_banner -loglevel error
      hwaccel_args: 
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy #-an

    detect:
      enabled: true
      max_disappeared: 30
      width: 2560
      height: 1920
      fps: 5

    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_area: 2000
          max_area: 450000
          min_score: 0.67
          threshold: 0.74
        dog:
          min_area: 2000
          max_area: 100000
          min_score: 0.65
          threshold: 0.70

    motion:
      threshold: 25
      improve_contrast: true
      mask:
        - 830,950,654,1024,325,967,0,1013,0,0,520,0,858,0,1341,0,2560,0,2479,889,2490,1006,1309,914
        - 2281,1920,2443,1278,2302,1381,1786,1503,1657,1638,1664,1833,1700,1920
        - 779,1541,728,1299,487,1231,412,1519
        
    record:
      enabled: true
      retain:
        days: 7
      events:
        #max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
        retain:
          default: 21

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 21

    rtmp:
      enabled: false

    timestamp_style:
      position: "bl"
      thickness: 2
        
    best_image_timeout: 30
    
    zones:  
      zone_front_porch:
        coordinates: 858,1529,613,1615,561,1675,363,1669,41,1920,636,1920,2237,1920,1996,1577,1662,1618,1590,1814,1455,1825,1370,1721,1176,1694,1205,1557
        
      zone_front_sidewalk:
        coordinates: 281,1205,758,1273,1023,1296,1366,1305,1879,1276,2267,1230,2197,1217,2029,1241,1636,1271,1197,1271,852,1253,664,1236,459,1208,288,1179
      
      zone_driveway:
        coordinates: 2326,1471,2455,1246,2303,1241,1834,1313
      
      zone_front_lawn:
        coordinates: 1725,1297,1631,1314,1248,1330,843,1322,255,1215,199,1314,173,1442,377,1410,840,1503,1154,1527,1351,1554,1467,1463,1605,1465,1674,1559,2221,1470

################### SIDEDRIVE
  Sidedrive:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX/live0 
        #- path: rtsp://XXXX/live0
          roles:
            - detect
            - record
      global_args: 
        -hide_banner 
        -loglevel error
      hwaccel_args: []
        # - -hwaccel
        # - vaapi
        # - -hwaccel_device
        # - /dev/dri/renderD128
        # - -hwaccel_output_format
        # - yuv420p
      input_args: []
          # -avoid_negative_ts make_zero 
          # -fflags +genpts+discardcorrupt 
          # -rtsp_transport tcp 
          # -stimeout 5000000 
          # -use_wallclock_as_timestamps 1
      output_args:
        record: 
          -f segment 
          -segment_time 10 
          -segment_format mp4 
          -reset_timestamps 1 
          -strftime 1 
          -c copy #-am
  
    detect:
      enabled: true
      max_disappeared: 30
      width: 1920
      height: 1080
      fps: 5

    objects: # Optional: Camera level object filters config.
      track:
        - person
        - dog
      filters:
        person:
          min_area: 1500
          max_area: 200000
          min_score: 0.7
          threshold: 0.74
        dog:
          min_area: 3500
          max_area: 50000
          min_score: 0.65
          threshold: 0.70
          
    motion:
      threshold: 25
      improve_contrast: true
      mask:
        - 1920,0,1920,60,1643,56,1640,0
        - 0,791,27,792,106,408,242,171,0,0

    record:
      enabled: true
      retain:
        days: 10
      events:
        #max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
        retain:
          default: 14

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 14

    rtmp:
      enabled: false

    timestamp_style:
      position: "bl"
      thickness: 2

    best_image_timeout: 30

################### SIDEYARD
  Sideyard:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX/live0 
        #- path: rtsp://XXXX/live0
          roles:
            - detect
            - record
      global_args: 
        -hide_banner 
        -loglevel error
      hwaccel_args: []
        # - -hwaccel
        # - vaapi
        # - -hwaccel_device
        # - /dev/dri/renderD128
        # - -hwaccel_output_format
        # - yuv420p
      input_args: []
          # -avoid_negative_ts make_zero 
          # -fflags +genpts+discardcorrupt 
          # -rtsp_transport tcp 
          # -stimeout 5000000 
          # -use_wallclock_as_timestamps 1
      output_args:
        record: 
          -f segment 
          -segment_time 10 
          -segment_format mp4 
          -reset_timestamps 1 
          -strftime 1 
          -c copy #-am
  
    detect:
      enabled: true
      max_disappeared: 30
      width: 1920
      height: 1080
      fps: 5

    objects:
      track:
        - person
        - dog
        - car
      filters:
        person:
          min_area: 5000
          max_area: 110000
          min_score: 0.7
          threshold: 0.74
        dog:
          min_area: 1000
          max_area: 15000
          min_score: 0.65
          threshold: 0.70
          mask:
            - 1385,105,1418,362,1167,319,1166,140
        car:
          min_area: 2500
          max_area: 30000
          min_score: 0.65
          threshold: 0.70

    motion:
      threshold: 25
      improve_contrast: true
      mask:
        - 1920,0,1920,410,1812,480,1643,56,1640,0
        - 912,1080,1152,1080,1282,327,1244,293,1167,337
        - 427,828,477,1018,851,905,1301,729,1564,601,1477,501,1094,617,821,684

    record:
      enabled: true
      retain:
        days: 5
        mode: all
      events:
        max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
          - car
        retain:
          default: 7

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true 
      crop: false
      retain:
        default: 7

    rtmp:
      enabled: false

    timestamp_style:
      position: "bl"
      thickness: 2
        
    best_image_timeout: 30

################### BACKYARD
  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX/live0 
        #- path: rtsp://XXXX/live0
          roles:
            - detect
            - record
      global_args: 
        -hide_banner 
        -loglevel error
      hwaccel_args: []
        # - -hwaccel
        # - vaapi
        # - -hwaccel_device
        # - /dev/dri/renderD128
        # - -hwaccel_output_format
        # - yuv420p
      input_args: []
          # -avoid_negative_ts make_zero 
          # -fflags +genpts+discardcorrupt 
          # -rtsp_transport tcp 
          # -stimeout 5000000 
          # -use_wallclock_as_timestamps 1
      output_args:
        record: 
          -f segment 
          -segment_time 10 
          -segment_format mp4 
          -reset_timestamps 1 
          -strftime 1 
          -c copy #-am
  
    detect:
      enabled: true
      max_disappeared: 30
      width: 1920
      height: 1080
      fps: 5

    objects: # Optional: Camera level object filters config.
      track:
        - person
        - dog
      filters:
        person:
          min_area: 16000
          max_area: 165000
          min_score: 0.72
          threshold: 0.78
        dog:
          min_area: 2000
          max_area: 50000
          min_score: 0.55
          threshold: 0.70

    motion:
      threshold: 22 #lower higher sensitivity; higher lower sensitivity
      improve_contrast: true
      mask:
        - 1236,0,1090,0,1120,90,1231,114,1397,126,1452,129,1495,84,1547,75,1619,91,1660,150,1731,128,1920,147,1920,0
        - 922,85,1114,67,1084,0,911,0
        - 778,0,767,67,699,40,662,88,486,120,362,100,244,100,216,148,89,171,0,291,0,162,0,0,287,0

    record:
      enabled: true
      retain:
        days: 7
      events:
        #max_seconds: 600
        pre_capture: 5
        post_capture: 5
        objects:
          - person
          - dog
        retain:
          default: 14

    snapshots:
      enabled: true
      timestamp: true 
      bounding_box: true
      crop: false
      retain:
        default: 14

    rtmp:
      enabled: false

    timestamp_style:
      position: "bl"
      thickness: 2
        
    best_image_timeout: 30

################### GARAGE
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX/live0 
        #- path: rtsp://XXXX/live0
          roles:
            - detect
            - record
      global_args: -hide_banner -loglevel error
      hwaccel_args: 
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy #-an
  
    detect:
      enabled: true
      max_disappeared: 30
      width: 1920
      height: 1080
      fps: 5

    objects:
      track:
        - person
        - dog
      filters:
        person:
          min_area: 1100
          max_area: 400000
          min_score: 0.70
          threshold: 0.74
        dog:
          min_area: 1000
          max_area: 50000
          min_score: 0.60
          threshold: 0.70
          mask:
            - 1435,148,1876,285,1684,731,1316,422

    motion:
      threshold: 25
      improve_contrast: false
      mask:
        - 160,85,649,77,892,85,996,48,1003,0,0,0,0,146
        - 1920,0,1920,206,1725,234,1513,153,1255,94,1213,0

    record:
      enabled: true
      retain:
        days: 0
      events:
        #max_seconds: 300
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 7

    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      crop: false
      retain:
        default: 7

    rtmp:
      enabled: false

    timestamp_style:
      position: "bl"
      thickness: 2

    best_image_timeout: 30
```

### Relevant log output

```shell
[cont-init.d] executing container initialization scripts...

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2022-05-18 08:11:27] frigate.app                    INFO    : Starting Frigate (0.11.0-d2c3cdc)

Starting migrations

[2022-05-18 08:11:27] peewee_migrate                 INFO    : Starting migrations

There is nothing to migrate

[2022-05-18 08:11:27] peewee_migrate                 INFO    : There is nothing to migrate

[2022-05-18 08:11:27] detector.coral                 INFO    : Starting detection process: 214

Exception in thread Thread-4:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

    self.run()

  File "/opt/frigate/frigate/video.py", line 215, in run

    self.start_ffmpeg_detect()

  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect

    self.ffmpeg_detect_process = start_or_restart_ffmpeg(

  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg

    process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

Exception in thread Thread-4:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

    self.run()

  File "/opt/frigate/frigate/video.py", line 215, in run

    self.start_ffmpeg_detect()

  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect

    self.ffmpeg_detect_process = start_or_restart_ffmpeg(

  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg

    process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

Exception in thread Thread-4:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

Exception in thread Thread-4:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

    self.run()

  File "/opt/frigate/frigate/video.py", line 215, in run

    self.run()

  File "/opt/frigate/frigate/video.py", line 215, in run

        self.start_ffmpeg_detect()self.start_ffmpeg_detect()

  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect

  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect

    self.ffmpeg_detect_process = start_or_restart_ffmpeg(

  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg

    process = sp.Popen(

    self.ffmpeg_detect_process = start_or_restart_ffmpeg(

  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

Exception in thread Thread-4:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

    self.run()

  File "/opt/frigate/frigate/video.py", line 215, in run

    self.start_ffmpeg_detect()

  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect

    self.ffmpeg_detect_process = start_or_restart_ffmpeg(

  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg

    process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

Exception in thread Thread-4:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

    self.run()

  File "/opt/frigate/frigate/video.py", line 215, in run

    self.start_ffmpeg_detect()

  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect

    self.ffmpeg_detect_process = start_or_restart_ffmpeg(

  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg

    process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

[2022-05-18 08:11:27] frigate.app                    INFO    : Output process started: 215

[2022-05-18 08:11:27] frigate.edgetpu                INFO    : Attempting to load TPU as usb

[2022-05-18 08:11:27] frigate.app                    INFO    : Camera processor started for Driveway: 224

[2022-05-18 08:11:27] frigate.app                    INFO    : Camera processor started for Doorbell: 225

[2022-05-18 08:11:27] frigate.app                    INFO    : Camera processor started for Sidedrive: 226

[2022-05-18 08:11:27] frigate.app                    INFO    : Camera processor started for Sideyard: 227

[2022-05-18 08:11:27] frigate.app                    INFO    : Camera processor started for Backyard: 228

[2022-05-18 08:11:27] frigate.app                    INFO    : Camera processor started for Garage: 229

[2022-05-18 08:11:27] frigate.app                    INFO    : Capture process started for Driveway: 230

Process output_processor:

[2022-05-18 08:11:27] frigate.app                    INFO    : Capture process started for Doorbell: 233

[2022-05-18 08:11:27] frigate.app                    INFO    : Capture process started for Sidedrive: 236

[2022-05-18 08:11:27] frigate.app                    INFO    : Capture process started for Sideyard: 240

[2022-05-18 08:11:27] frigate.app                    INFO    : Capture process started for Backyard: 245

[2022-05-18 08:11:27] frigate.app                    INFO    : Capture process started for Garage: 247

[2022-05-18 08:11:28] ws4py                          INFO    : Using epoll

[2022-05-18 08:11:27] ws4py                          INFO    : Using epoll

Traceback (most recent call last):

  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap

    self.run()

  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/frigate/frigate/output.py", line 372, in output_frames

    converters[camera] = FFMpegConverter(

  File "/opt/frigate/frigate/output.py", line 36, in __init__

    self.process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

[2022-05-18 08:11:30] frigate.edgetpu                INFO    : TPU found
```

### FFprobe output from your camera

```shell
NOTE: this is my typical output for these cameras

ffprobe version 4.3.2-0+deb11u1ubuntu1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.1-20ubuntu1)
  configuration: --prefix=/usr --extra-version=0+deb11u1ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[tcp @ 0x56363a5e2dc0] Connection to tcp://10.0.0.40:554?timeout=0 failed: No route to host
rtsp://10.0.0.40/live0: No route to host
```

### Frigate stats

```json
{"Backyard":{"camera_fps":0.0,"capture_pid":245,"detection_fps":0.0,"pid":228,"process_fps":0.0,"skipped_fps":0.0},"Doorbell":{"camera_fps":0.0,"capture_pid":233,"detection_fps":0.0,"pid":225,"process_fps":0.0,"skipped_fps":0.0},"Driveway":{"camera_fps":0.0,"capture_pid":230,"detection_fps":0.0,"pid":224,"process_fps":0.0,"skipped_fps":0.0},"Garage":{"camera_fps":0.0,"capture_pid":247,"detection_fps":0.0,"pid":229,"process_fps":0.0,"skipped_fps":0.0},"Sidedrive":{"camera_fps":0.0,"capture_pid":236,"detection_fps":0.0,"pid":226,"process_fps":0.0,"skipped_fps":0.0},"Sideyard":{"camera_fps":0.0,"capture_pid":240,"detection_fps":0.0,"pid":227,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":214}},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":1072.9,"mount_type":"tmpfs","total":1073.7,"used":0.8},"/media/frigate/clips":{"free":981967.7,"mount_type":"ext4","total":1034677.7,"used":79.9},"/media/frigate/recordings":{"free":981967.7,"mount_type":"ext4","total":1034677.7,"used":79.9},"/tmp/cache":{"free":2000.0,"mount_type":"tmpfs","total":2000.0,"used":0.0}},"temperatures":{},"uptime":458,"version":"0.11.0-d2c3cdc"}}

```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Amcrest AD410 and Eufy C22

**Comment by NickM-27** [comment]
This looks like the error that was fixed by https://github.com/blakeblackshear/frigate/pull/3147/commits/9c4da5a14c5d73a1a9493346d82e577b493f108f, seems it can't find ffmpeg 

are you saying this doesn't happen when you remove hwaccel args? looking at the logs it seems this would happen regardless

**Comment by esmoyer** [comment]
Yes, it's happening regardless of the hwaccel args being commented out or not. Before the beta, I just had them commented out. But since installing the beta, I have tried a couple different variations. Am I missing something, wouldn't surprise me.

**Comment by blakeblackshear** [comment]
Can you confirm which architecture you are on? Were you previously pulling the amd64 image?

**Comment by NickM-27** [comment]
Okay cool, so the title isn't accurate. And no I don't think this is on you, seems something with the container. What CPU / arch are you running?

If you are able, it would be helpful if you could open a terminal inside the container and run `ffmpeg --help` and see if ffmpeg is available

**Comment by esmoyer** [comment]
Correct. I was kind of wondering about that.

**Comment by esmoyer** [comment]
I was previously on 0.10.1-amd64

I am assuming you mean docker container (I run in a proxmox container). When I run `ffmpeg --help` I get `bash: ffmpeg: command not found`

**Comment by NickM-27** [comment]
@blakeblackshear Seems like this may be related to proxmox? So far only proxmox users have reported this issue 🤔

**Comment by NickM-27** [comment]
Maybe having to do with this: https://jellyfin.org/docs/general/administration/hardware-acceleration.html#va-api-and-qsv-hardware-acceleration-on-lxc-on-proxmox

@esmoyer is the container that frigate runs in privileged?

**Comment by esmoyer** [comment]
It is a privileged container (as confusing as Proxmox states it)

![image](https://user-images.githubusercontent.com/17444085/169136302-c932ccfb-428c-4197-be59-7d03bd0f37ef.png)

**Comment by NickM-27** [comment]
Looks like what I linked is about hw_accel so may not be it

**Comment by Zunhammer** [comment]
I have the same issue, also running in a privileged Proxmox container. When attaching to the docker container I see:
`[2022-05-18 21:10:01] watchdog.Hauseingang           ERROR   : Ffmpeg process crashed unexpectedly for Hauseingang.
[2022-05-18 21:10:01] watchdog.Hauseingang           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : Assuming 131072kB available aperture size.
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : May lead to reduced performance or incorrect rendering.
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : get chip id failed: -1 [2]
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : param: 4, val: 0
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : [AVHWDeviceContext @ 0x55deececa980] libva: /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so init failed
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : [AVHWDeviceContext @ 0x55deececa980] Failed to initialise VAAPI connection: 18 (invalid parameter).
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : Device creation failed: -5.
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Input/output error
[2022-05-18 21:10:01] ffmpeg.Hauseingang.detect      ERROR   : Error parsing global options: Input/output error
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : Assuming 131072kB available aperture size.
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : May lead to reduced performance or incorrect rendering.
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : get chip id failed: -1 [2]
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : param: 4, val: 0
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : [AVHWDeviceContext @ 0x55de4dfbb8c0] libva: /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so init failed
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : [AVHWDeviceContext @ 0x55de4dfbb8c0] Failed to initialise VAAPI connection: 18 (invalid parameter).
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : Device creation failed: -5.
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Input/output error
[2022-05-18 21:10:01] ffmpeg.Hauseingang.record      ERROR   : Error parsing global options: Input/output error`

If I should provide more information let me know. Thanks for your support and all the work :)

**Comment by tmjpugh** [comment]
> @blakeblackshear Seems like this may be related to proxmox? So far only proxmox users have reported this issue thinking

Ubuntu 20.04 user having same issue "FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'"

**Comment by NickM-27** [comment]
@Zunhammer What you have there is not the same issue as ffmpeg is found it is just crashing with hw_accel args.

**Comment by Zunhammer** [comment]
OK, thanks. Then maybe my config helps as I assume I'm one step ahead (ffmpeg found but crashing)
![image](https://user-images.githubusercontent.com/18286310/169139022-680d10da-7f06-4082-b822-076a917b5324.png)

**Comment by NickM-27** [comment]
@Zunhammer I would recommend creating your own issue as we don't want to add clutter for those that are experiencing the ffmpeg not found issue.

**Comment by blakeblackshear** [comment]
Can someone post the output of `echo $PATH` from within the container? This seems like something is overwriting the PATH env variable in the container.

**Comment by esmoyer** [comment]
```
root@e886c4d68cd3:/opt/frigate# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@e886c4d68cd3:/opt/frigate# 
```

**Comment by tmjpugh** [comment]
FFMPEG is at /usr/lib/jellyfin-ffmpeg/ffmpeg in blakeblackshear/frigate:0.11.0-beta2 container.

**Comment by blakeblackshear** [comment]
Yea. That's not right. The dockerfile clearly [sets the PATH environment variable](https://github.com/blakeblackshear/frigate/blob/release-0.11.0/docker/Dockerfile#L96). Something is overwriting that value in the container.

**Comment by esmoyer** [comment]
Interesting. Want me to try doing a fresh install or anything else?

**Comment by jcastro** [comment]
I'm trying to follow up on the fix but I'm not as technical. I've checked portainer variables but there's no ENV variable? Would you guys mind expanding a bit on how to fix it? Thanks a lot!
<img width="977" alt="Screenshot 2022-05-21 at 09 37 12" src="https://user-images.githubusercontent.com/190036/169641300-b6e0e68d-ac44-452a-aebf-af2323ca0b2c.png">

**Comment by innuendoz** [comment]
I had the same issue using portainer, environment path value was wrong.  Originally my portainer was pulling blakeblackshear/frigate-amd65, now everything works without issue or editing after changing pull blakeblackshear/frigate
