### ISSUE TITLE
[Support]: video broadcast, object detection and recording are stopped. Exception in thread detected_frames_processor

### ISSUE THREAD

**Issue by AznKid45** [blakeblackshear/frigate#3272]
### Describe the problem you are having

Hi!
After the appearance of the object on the cameras (the last time I noticed that it was a person), the video broadcast, object detection and recording are stopped.
I found an error in the log (attached).
Presumably, the problem appeared after adding camera4 and camera5

P.S. thanks for your great work! Frigate is a really cool!

### Version

0.10.1-83481af

### Frigate config file

```yaml
mqtt:
  host: 192.168.127.11
  topic_prefix: frigate
  user: myuser
  password: mypass

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1280
  # Optional: Height of the output resolution (default: shown below)
  height: 720
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: motion

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 50
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for confirming stationary objects (default: shown below)
    # When set to 0, object detection will not confirm stationary objects until movement is detected.
    # If set to 10, object detection will run to confirm the object still exists on every 10th frame.
#    interval: 50
    interval: 0
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 100
    # Optional: Define a maximum number of frames for tracking a stationary object (default: not set, track forever)
    # This can help with false positives for objects that should only be stationary for a limited amount of time.
    # It can also be used to disable stationary object tracking. For example, you may want to set a value for person, but leave
    # car at the default.
    # WARNING: Setting these values overrides default behavior and disables stationary object tracking.
    #          There are very few situations where you would want it disabled. It is NOT recommended to
    #          copy these values from the example config into your config unless you know they are needed.
#    max_frames:
      # Optional: Default for all object types (default: not set, track forever)
#      default: 3000
      # Optional: Object specific values
#      objects:
#        person: 0

# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - motorcycle
    - bicycle
    - cat
    - dog
  # Optional: mask to prevent all object types from being detected in certain areas (default: no mask)
  # Checks based on the bottom center of the bounding box of the object.
  # NOTE: This mask is COMBINED with the object type specific mask below
#  mask: 
  # Optional: filters to reduce false positives for specific object types
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
#      min_area: 5000
      min_area: 100
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
#      max_area: 100000
      max_area: 1000000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
      # Optional: mask to prevent this object type from being detected in certain areas (default: no mask)
      # Checks based on the bottom center of the bounding box of the object
      #mask: 0,0,1000,0,1000,200,0,200

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 75
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
#  frame_height: 50
  frame_height: 55
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
#  mask: 0,900,1080,900,1080,1920,0,1920
#  mask: 0,1072,1920,1072,1920,0,0,0
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
#  improve_contrast: False
  improve_contrast: True

record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 720
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 10
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
#    mode: all
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    max_seconds: 3600
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 10
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 20
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
#      - person
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 60
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
#      mode: motion
      mode: all
      # Optional: Per object retention days
      objects: []
#        person: 30

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: False
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: False
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
#  height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 365
    # Optional: Per object retention days
#    objects:
#      person: 30

# Optional: RTMP configuration
# NOTE: Can be overridden at the camera level
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: True

# Optional: Live stream configuration for WebUI
# NOTE: Can be overridden at the camera level
live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 720
  # Optional: Set the encode quality of the live stream (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8

cameras:
#  camera1:
#    ffmpeg:
#      inputs:
#        - path: rtsp://192.168.127.50:554/cam0_0
#          roles:
#            - detect
#            - rtmp
#            - record
#    detect:
#      width: 1920
#      height: 1072
#    zones:
#      zone_0:
#        coordinates: 795,0,419,0,342,88,0,161,0,1072,1920,1072,1920,121,1740,76,1469,31,1184,0
#        # Optional: List of objects that can trigger this zone (default: all tracked objects)
##        objects:
##          - person
#        # Optional: Zone level object filters.
#        # NOTE: The global and camera filters are applied upstream.
##        filters:
##          person:
##            min_area: 5000
##            max_area: 100000
##            threshold: 0.7

  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.127.51:554/cam0_0
          roles:
            - record
        - path: rtsp://192.168.127.51:554/cam0_1
          roles:
            - detect
            - rtmp  
    motion:
      mask: []
#464,781,771,701,719,638,405,739
    detect:
      width: 1920
      height: 1072
    zones:
      zone_0:
        coordinates: 0,1072,1920,1072,1920,497,1644,0,621,0,341,150,373,497,0,531

  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.127.52:554/cam0_0
          roles:
            - record
        - path: rtsp://192.168.127.52:554/cam0_1
          roles:
            - detect
            - rtmp  
    detect:
      width: 1920
      height: 1072
    objects:
      filters:
        car:
          mask: []
    zones:
      zone_0:
        coordinates: 1920,1072,1920,0,886,0,783,396,0,391,0,1072

  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.127.53:554/live.sdp
          roles:
            - record
        - path: rtsp://192.168.127.53:554/live2.sdp
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 800
    objects:
      filters:
        car:
          mask: []
    zones:
      zone_0:
        coordinates: []

  camera5:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.127.54:554/live.sdp
          roles:
            - record
        - path: rtsp://192.168.127.54:554/live2.sdp
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 800
    objects:
      filters:
        car:
          mask: []
    zones:
      zone_0:
        coordinates: []
```

### Relevant log output

```shell
2022-05-28T11:51:55.526885232Z [2022-05-28 16:51:55] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
2022-05-28T11:51:55.565211065Z [2022-05-28 16:51:55] frigate.config                 WARNING : camera2: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2022-05-28T11:51:55.568143579Z [2022-05-28 16:51:55] frigate.config                 WARNING : camera3: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2022-05-28T11:51:55.569707536Z [2022-05-28 16:51:55] frigate.config                 WARNING : camera4: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2022-05-28T11:51:55.571782322Z [2022-05-28 16:51:55] frigate.config                 WARNING : camera5: Recording retention is configured for motion and event retention is configured for all. The more restrictive retention policy will be applied.
2022-05-28T11:51:55.578349681Z Starting migrations
2022-05-28T11:51:55.578363871Z [2022-05-28 16:51:55] peewee_migrate                 INFO    : Starting migrations
2022-05-28T11:51:55.851471836Z There is nothing to migrate
2022-05-28T11:51:55.851510774Z [2022-05-28 16:51:55] peewee_migrate                 INFO    : There is nothing to migrate
2022-05-28T11:51:55.872301918Z [2022-05-28 16:51:55] detector.cpu1                  INFO    : Starting detection process: 217
2022-05-28T11:51:55.876048934Z [2022-05-28 16:51:55] detector.cpu2                  INFO    : Starting detection process: 219
2022-05-28T11:51:55.879646770Z [2022-05-28 16:51:55] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2022-05-28T11:51:55.879680998Z [2022-05-28 16:51:55] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2022-05-28T11:51:55.880686245Z [2022-05-28 16:51:55] frigate.app                    INFO    : Output process started: 221
2022-05-28T11:51:55.884270738Z [2022-05-28 16:51:55] ws4py                          INFO    : Using epoll
2022-05-28T11:51:55.887217418Z [2022-05-28 16:51:55] frigate.app                    INFO    : Camera processor started for camera2: 225
2022-05-28T11:51:55.891320273Z [2022-05-28 16:51:55] frigate.app                    INFO    : Camera processor started for camera3: 226
2022-05-28T11:51:55.916329753Z [2022-05-28 16:51:55] frigate.app                    INFO    : Camera processor started for camera4: 229
2022-05-28T11:51:55.920238176Z [2022-05-28 16:51:55] frigate.app                    INFO    : Camera processor started for camera5: 231
2022-05-28T11:51:55.924620065Z [2022-05-28 16:51:55] frigate.app                    INFO    : Capture process started for camera2: 232
2022-05-28T11:51:55.928532827Z [2022-05-28 16:51:55] frigate.app                    INFO    : Capture process started for camera3: 234
2022-05-28T11:51:55.931825006Z [2022-05-28 16:51:55] frigate.app                    INFO    : Capture process started for camera4: 236
2022-05-28T11:51:55.942265744Z [2022-05-28 16:51:55] frigate.app                    INFO    : Capture process started for camera5: 239
2022-05-28T11:51:55.964327649Z [2022-05-28 16:51:55] ws4py                          INFO    : Using epoll
2022-05-28T11:51:58.935447012Z [2022-05-28 16:51:58] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47066]
2022-05-28T11:55:06.012143754Z [2022-05-28 16:55:06] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47066]
2022-05-28T15:12:08.177220844Z [2022-05-28 20:12:08] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47068]
2022-05-28T15:12:15.204265114Z [2022-05-28 20:12:15] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47068]
2022-05-28T15:12:16.246302103Z [2022-05-28 20:12:16] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47070]
2022-05-28T15:14:07.041864647Z [2022-05-28 20:14:07] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47070]
2022-05-29T05:10:47.311359119Z Exception in thread detected_frames_processor:
2022-05-29T05:10:47.313778185Z Traceback (most recent call last):
2022-05-29T05:10:47.313791950Z   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2022-05-29T05:10:47.313795531Z     self.run()
2022-05-29T05:10:47.313798658Z   File "/opt/frigate/frigate/object_processing.py", line 854, in run
2022-05-29T05:10:47.315369970Z     camera_state.update(
2022-05-29T05:10:47.315463441Z   File "/opt/frigate/frigate/object_processing.py", line 487, in update
2022-05-29T05:10:47.315847971Z     thumb_update, significant_update = updated_obj.update(
2022-05-29T05:10:47.315908764Z   File "/opt/frigate/frigate/object_processing.py", line 145, in update
2022-05-29T05:10:47.316096738Z     if cv2.pointPolygonTest(contour, bottom_center, False) >= 0:
2022-05-29T05:10:47.316815322Z cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-jhawztrk/opencv/modules/imgproc/src/geometry.cpp:103: error: (-215:Assertion failed) total >= 0 && (depth == CV_32S || depth == CV_32F) in function 'pointPolygonTest'
2022-05-29T05:10:47.316819479Z 
2022-05-29T05:31:54.326742912Z [2022-05-29 10:31:54] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47072]
2022-05-29T05:31:58.130058955Z [2022-05-29 10:31:58] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47072]
2022-05-29T05:31:58.747136404Z [2022-05-29 10:31:58] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47074]
2022-05-29T05:32:03.052977150Z [2022-05-29 10:32:03] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45122]
2022-05-29T05:32:12.644186543Z [2022-05-29 10:32:12] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45122]
2022-05-29T05:32:16.172011890Z [2022-05-29 10:32:16] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45124]
2022-05-29T05:32:57.584665210Z [2022-05-29 10:32:57] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45124]
2022-05-29T05:32:58.900886842Z [2022-05-29 10:32:58] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45126]
2022-05-29T05:33:08.138781529Z [2022-05-29 10:33:08] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45126]
2022-05-29T05:33:10.274643533Z [2022-05-29 10:33:10] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45128]
2022-05-29T05:33:11.547994126Z [2022-05-29 10:33:11] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47074]
2022-05-29T05:34:10.277130152Z [2022-05-29 10:34:10] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45128]
2022-05-29T05:34:51.988581956Z [2022-05-29 10:34:51] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:47076]
2022-05-29T05:34:53.535619705Z [2022-05-29 10:34:53] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45130]
2022-05-29T05:35:01.508016446Z [2022-05-29 10:35:01] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45130]
2022-05-29T05:35:01.659429478Z [2022-05-29 10:35:01] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45132]
2022-05-29T05:35:02.364141505Z [2022-05-29 10:35:02] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:45132]
```

### FFprobe output from your camera

```shell
*
```

### Frigate stats

```json
{"camera2":{"camera_fps":5.0,"capture_pid":232,"detection_fps":5.4,"pid":225,"process_fps":3.4,"skipped_fps":0.0},"camera3":{"camera_fps":5.0,"capture_pid":234,"detection_fps":5.7,"pid":226,"process_fps":1.0,"skipped_fps":0.0},"camera4":{"camera_fps":5.1,"capture_pid":236,"detection_fps":0.0,"pid":229,"process_fps":5.0,"skipped_fps":0.0},"camera5":{"camera_fps":5.0,"capture_pid":239,"detection_fps":3.2,"pid":231,"process_fps":3.5,"skipped_fps":0.0},"detection_fps":14.3,"detectors":{"cpu1":{"detection_start":0.0,"inference_speed":63.53,"pid":217},"cpu2":{"detection_start":1653803772.339573,"inference_speed":60.13,"pid":219}},"service":{"storage":{"/dev/shm":{"free":95.3,"mount_type":"tmpfs","total":134.2,"used":38.9},"/media/frigate/clips":{"free":467441.2,"mount_type":"fuseblk","total":2000397.9,"used":1532956.7},"/media/frigate/recordings":{"free":467441.2,"mount_type":"fuseblk","total":2000397.9,"used":1532956.7},"/tmp/cache":{"free":986.9,"mount_type":"tmpfs","total":1000.0,"used":13.1}},"temperatures":{},"uptime":65057,"version":"0.10.1-83481af"}}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

MD MDi6090FTDd, vivotek FD8136

### Any other information that may be helpful

OS: ubuntu server 22.04

**Comment by NickM-27** [comment]
First off just want to mention that copying the full reference config is not recommended.

If you are comfortable, can you provide a screenshot with your zones outlined? The polygon test occurs when trying to detect if an object is in the zone

**Comment by AznKid45** [comment]
Yes, you seem to be right.
I apologize for the long first post.
I reduced the detection resolution, redefined the zones, so far so good.
Thanks

**Comment by NickM-27** [comment]
Okay that makes sense 👍
