### ISSUE TITLE
[Config Support]: mapping values are not allowed here

### ISSUE THREAD

**Issue by acct412** [blakeblackshear/frigate#3365]
### Describe the problem you are having

I'm very inexperienced with linux/docker etc. but have run into this issue and am not sure where else to post for help.

Running (or trying to run..) frigate using docker-compose on ubuntu 20.04. Followed the frigate instruction docs but can't get frigate running. When I inspect the logs using portainer, I get the following config validation error: 

```
mapping values are not allowed here


  in "<unicode string>", line 10, column 11:


        ffmpeg:

              ^
```

It looks like a spacing issue or something after ffmpeg: but I can't figure it out. I copy/pasted the code from the instruction docs.

Thanks in advance.

### Version

frigate:0.10.1-amd64

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.x
  user: x
  password: x

#detectors: 

cameras:
  camera_1: poolcam
    ffmpeg:
      inputs:
        - path: rtsp://frig:x@192.168.x.x:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 3840
      height: 2160
```

### Relevant log output

```shell
*************************************************************


*************************************************************


***    Your config file is not valid!                     ***


***    Please check the docs at                           ***


***    https://docs.frigate.video/configuration/index     ***


*************************************************************


*************************************************************


***    Config Validation Errors                           ***


*************************************************************


mapping values are not allowed here


  in "<unicode string>", line 10, column 11:


        ffmpeg:


              ^


Traceback (most recent call last):


  File "/opt/frigate/frigate/app.py", line 312, in start


    self.init_config()


  File "/opt/frigate/frigate/app.py", line 77, in init_config


    user_config = FrigateConfig.parse_file(config_file)


  File "/opt/frigate/frigate/config.py", line 900, in parse_file


    config = yaml.safe_load(raw_config)


  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 162, in safe_load


    return load(stream, SafeLoader)


  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 114, in load


    return loader.get_single_data()


  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data


    node = self.get_single_node()


  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node


    document = self.compose_document()


  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 55, in compose_document


    node = self.compose_node(None, None)


  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node


    node = self.compose_mapping_node(anchor)


  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 133, in compose_mapping_node


    item_value = self.compose_node(node, item_key)


  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node


    node = self.compose_mapping_node(anchor)


  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 127, in compose_mapping_node


    while not self.check_event(MappingEndEvent):


  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 98, in check_event


    self.current_event = self.state()


  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key


    if self.check_token(KeyToken):


  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 116, in check_token


    self.fetch_more_tokens()


  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens


    return self.fetch_value()


  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 577, in fetch_value


    raise ScannerError(None, None,


yaml.scanner.ScannerError: mapping values are not allowed here


  in "<unicode string>", line 10, column 11:


        ffmpeg:


              ^



*************************************************************


***    End Config Validation Errors                       ***


*************************************************************
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
```yaml
cameras:
  camera_1: poolcam
```

Is incorrect, it is just a name not a mapping so needs to just be `camera_1:`

**Comment by acct412** [comment]
> ```yaml
> cameras:
>   camera_1: poolcam
> ```
> 
> Is incorrect, it is just a name not a mapping so needs to just be `camera_1:` (or whatever)

That's it, thanks!!
