### ISSUE TITLE
An exception in event processing loop terminates event processing

### ISSUE THREAD

**Issue by msekoranja** [blakeblackshear/frigate#337]
**Describe the bug/FR**
I was fiddling with the cache directory (shame on me!) and, of course, this resulted in an exception.
However this completely stopped event processing afterwards (e.g. no clips where created).
I guess more robust exception handling is missing, since this might happen when there is nobody messing the filesystem.

**Version of frigate**
0.8. beta

**Logs**
```
Exception in thread event_processor:
Traceback (most recent call last):
  File "/opt/frigate/frigate/events.py", line 156, in run
    event_type, camera, event_data = self.event_queue.get(timeout=10)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/events.py", line 159, in run
    self.refresh_cache()
  File "/opt/frigate/frigate/events.py", line 97, in refresh_cache
    os.remove(os.path.join(CACHE_DIR,f))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cache/entrance-20201208135413.mp4'```

**Comment by msekoranja** [comment]
Another minor issue.
Code expects only .yml and .json config_file extensions, however file can be configured via CONFIG_FILE env. variable.
If anything else is provided, the code fails with "config" variable not initialized but accessed. I would simply throw an exception for other extensions (as shown below).

frigate/config.py:770
```
        if config_file.endswith(".yml"):
            config = yaml.safe_load(raw_config)
        elif config_file.endswith(".json"):
            config = json.loads(raw_config)
        else:
            raise ValueError('unsupported config_file extension, must be .yml or .json')```
