### ISSUE TITLE
[Config Support]: 'ffmpeg' validation error

### ISSUE THREAD

**Issue by sometingrandom-MC** [blakeblackshear/frigate#3374]
### Describe the problem you are having

Frigate will not start and gives a validation error 'ffmpeg'.

### Version

3.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.195
  user: myuser
  password: mypassword

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.155:8080/h264_pcm.sdp
          roles:
            - detect
  detect:
    width: 1920
    height: 1080
    fps: 5

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 511, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 329, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 1022, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 856, in validate
    v, errors = self._validate_mapping_like(v, values, loc, cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 991, in _validate_mapping_like
    value_result, value_errors = self._validate_singleton(v_, values, v_loc, cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1064, in _validate_singleton
    value, error = field.validate(v, values, loc=loc, cls=cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 854, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1071, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1118, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/class_validators.py", line 313, in <lambda>
    return lambda cls, v, values, field, config: validator(v)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 676, in validate
    return cls(**value)
  File "/opt/frigate/frigate/config.py", line 548, in __init__
    if len(config["ffmpeg"]["inputs"]) == 1:
KeyError: 'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Your config is not formatted correctly. 

`detect` and everything directly under it needs to be indented by 2 spaces. Currently it sees `detect` as another camera, it needs to be indented so it is seen as a property of `camera_1`

**Comment by sometingrandom-MC** [comment]
Thank You! It works!
