### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by mstraus66** [blakeblackshear/frigate#3441]
### Describe the problem you are having

stream stops. detection does not work. ffmpeg errors. Websock terminates

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.214
  user: mqtt
  password: Brunhilde01

cameras:
  deurbel:
    mqtt:
      timestamp: True
      bounding_box: True
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -use_wallclock_as_timestamps 1
      output_args:
        record: 
          -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 
          -c:v libx264 -an
 #       rtmp: 
 #         -c:v libx264 -an -f flv
      inputs:
        - path: rtsp://marc:Brunhilde01@192.168.1.44:88/videoSub
          roles:
            - detect
        - path: rtsp://marc:Brunhilde01@192.168.1.44:88/videoMain
          roles:    
            - record
#            - rtmp
#            - clips
#            - snapshots
    rtmp:
      enabled: false
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
    snapshots:
      enabled: True
      timestamp: True
      retain:
        default: 1
    detect:
      width: 2560
      height: 1440
      fps: 20

  voordeur:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      inputs:
        - path: rtsp://marc:Brunhilde01@192.168.1.43:88/videoMain
          roles:
            - detect
            - record
#            - rtmp
#            - clips
#            - snapshots
    rtmp:
      enabled: false
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
    snapshots:
      enabled: True
      timestamp: True
      retain:
        default: 1
    detect:
      width: 1920
      height: 1080
      fps: 20
    objects:
      track:
        - person

  voortuin:
    mqtt:
      timestamp: True
      bounding_box: True
      crop: True
      quality: 100
      height: 500
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -use_wallclock_as_timestamps 1
      output_args:
        record: 
          -f segment 
          -segment_time 10 
          -segment_format mp4 
          -reset_timestamps 1 
          -strftime 1 
          -c:v libx264 -an
#        rtmp: 
#          -c:v libx264 -an 
#          -f flv
      inputs:
        - path: rtsp://marc:Brunhilde01@192.168.1.42:88/videoSub
          roles:
            - detect        
        - path: rtsp://marc:Brunhilde01@192.168.1.42:88/videoMain    
          roles:    
            - record
#            - rtmp
#            - clips
#            - snapshots
    rtmp:
      enabled: false
    record:
      enabled: True
      retain:
        days: 2
        mode: motion
    snapshots:
      enabled: True
      timestamp: True
      retain:
        default: 1
    detect:
      width: 1280
      height: 960
      fps: 20
    objects:
      track:
        - person
#        - motorcycle
#        - bicycle
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-07-08 14:27:06] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
[2022-07-08 14:27:06] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-07-08 14:27:06] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-07-08 14:27:06] peewee_migrate                 INFO    : There is nothing to migrate
[2022-07-08 14:27:06] frigate.app                    INFO    : Output process started: 215
[2022-07-08 14:27:06] detector.cpu                   INFO    : Starting detection process: 214
[2022-07-08 14:27:06] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2022-07-08 14:27:06] frigate.app                    INFO    : Camera processor started for deurbel: 218
[2022-07-08 14:27:06] frigate.app                    INFO    : Camera processor started for voordeur: 219
[2022-07-08 14:27:06] frigate.app                    INFO    : Camera processor started for voortuin: 220
[2022-07-08 14:27:06] ws4py                          INFO    : Using epoll
[2022-07-08 14:27:06] frigate.app                    INFO    : Capture process started for deurbel: 221
[2022-07-08 14:27:06] frigate.app                    INFO    : Capture process started for voordeur: 228
[2022-07-08 14:27:06] frigate.app                    INFO    : Capture process started for voortuin: 233
[2022-07-08 14:27:07] ws4py                          INFO    : Using epoll
[2022-07-08 14:31:25] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:35102]
[2022-07-08 14:31:30] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:35102
```

### FFprobe output from your camera

```shell
not available on HassOs
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Foscam VD1 and other Foscams

**Comment by NickM-27** [comment]
We're going to need more than this to be able to help. There are no errors in your logs meaning you either didn't wait long enough before copying or your camera stream is working well. Is there any behavior that leads you to believe there's an issue?

The websocket closed message is totally normal, it just means the user stopping watching a camera stream in the UI.

**Comment by mstraus66** [comment]
Well, the behavior observed is that there are no event recorden even though I danced before the camera's (and it was picked up by Foscam VMS) en in live view nothing moves. Doubletake does not receive snapshots. There seems to happen nothing at all

**Comment by NickM-27** [comment]
Okay, you mentioned ffmpeg errors, do you have logs of those?

**Comment by mstraus66** [comment]
No. I believe Frigate stopped this time before generating any. But I will restart to see if it goes any further this time.

**Comment by mstraus66** [comment]
It might just be Frigate is too much for my Tinkerboard...

**Comment by NickM-27** [comment]
Seeing the logs from start to finish if Frigate is crashing would also be helpful. 

Is your CPU being pinned at 100%?

**Comment by mstraus66** [comment]
![image](https://user-images.githubusercontent.com/84567691/178015177-5213647c-e840-4ec3-9178-1f2f7bc384dc.png)

**Comment by mstraus66** [comment]
![image](https://user-images.githubusercontent.com/84567691/178015353-a1e9d8b7-2f77-4f97-b7a2-20164d1c6df4.png)

**Comment by mstraus66** [comment]
Detection fps=0?

**Comment by mstraus66** [comment]
I am sorry if I give a poor desciption. My talents lie elsewhere ;-) I am not a programmer...

**Comment by NickM-27** [comment]
So cameras are being processed / frames are coming in. Detection fps will only go up as frigate detects something. 

So if you go in front of the camera while watching frigate feed on your phone, you see nothing change?

**Comment by mstraus66** [comment]
Correct

**Comment by mstraus66** [comment]
Probably my Frigate config is a big mess. Tried to incorporate the ffmpeg args from the documentation.

**Comment by NickM-27** [comment]
I would try deleting the `input_args` for all cameras so it uses the defaults. Users in other issues using foscam have not set those and they were working.

**Comment by mstraus66** [comment]
I will do that right away

**Comment by mstraus66** [comment]
no change. Shall I also disable the output args?

**Comment by NickM-27** [comment]
Your config shows you haven't set any output args for detect and it has its own process so it shouldn't matter at all if record output args are set

**Comment by mstraus66** [comment]
I spoke too soon :-). A detection has been made!! Thanks neighbor :-)

**Comment by NickM-27** [comment]
Oh okay good 👍

**Comment by mstraus66** [comment]
Still not sure why the fps is so low

**Comment by NickM-27** [comment]
Which fps?

**Comment by mstraus66** [comment]
All camera's. As per the debug screenshot. In the config I asked for 20 fps for all camera's. That is too high for detection (I know that). |Is there a way to improve fps in live or birdseye view?

**Comment by mstraus66** [comment]
After that I will leave you alone. You have already spent enough with this noob

**Comment by mstraus66** [comment]
The camera's all give 25

**Comment by mstraus66** [comment]
Does Frigate use the VideoSub for live view?

**Comment by NickM-27** [comment]
Yes it does

**Comment by mstraus66** [comment]
Ah. That explains. Those are 15 fps

**Comment by mstraus66** [comment]
still a way off though

**Comment by mstraus66** [comment]
Only the cam "voortuin"is keeping up

**Comment by NickM-27** [comment]
No, setting the `detect -> fps` is the only place that is needed. 

And are your cameras set to h264 or h265? Could also be output args as well

**Comment by mstraus66** [comment]
![image](https://user-images.githubusercontent.com/84567691/178028329-74caf10f-dd45-43fc-bffb-27e55fa62ae8.png)

**Comment by mstraus66** [comment]
Oh shoot. I said I would let you be. Sorry but I am quit enjoying this trobleshooting :-)

**Comment by NickM-27** [comment]
Looks correct, it is possible that it is lack of CPU resources to run fully otherwise I have no idea why it would not be pulling the full fps (also not 5 which is the default which backs this up)

**Comment by mstraus66** [comment]
Maybe my LAN is botched somewhere. Been having issues since I added the Tinkerboard en Jetson. No idea why but I will investigate.

**Comment by mstraus66** [comment]
LAN is ok.

**Comment by mstraus66** [comment]
[2022-07-10 01:41:19] frigate.video                  ERROR   : voortuin: Unable to read frames from ffmpeg process.
[2022-07-10 01:41:19] frigate.video                  ERROR   : voortuin: ffmpeg process is not running. exiting capture thread...
[2022-07-10 01:41:26] watchdog.voortuin              ERROR   : Ffmpeg process crashed unexpectedly for voortuin.
[2022-07-10 01:41:26] watchdog.voortuin              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : Guessed Channel Layout for Input Stream #0.1 : mono
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : More than 1000 frames duplicated
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : [rtsp @ 0x1317610] RTP: PT=60: bad cseq 6354 expected=3bb4
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : [rtsp @ 0x1317610] CSeq 12 expected, 0 received.
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   :     Last message repeated 5 times
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : Invalid UE golomb code
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : [h264 @ 0x134e2f0] cbp too large (3199971767) at 52 25
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : [h264 @ 0x134e2f0] error while decoding MB 52 25
[2022-07-10 01:41:26] ffmpeg.voortuin.detect         ERROR   : rtsp://marc:Brunhilde01@192.168.1.42:88/videoMain: corrupt decoded frame in stream 0
[2022-07-10 04:58:24] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49052]
[2022-07-10 04:58:34] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:52770]
[2022-07-10 04:58:40] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49052]
[2022-07-10 04:58:40] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:52770]
[2022-07-10 05:03:00] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49060]
[2022-07-10 05:03:06] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:48350]
[2022-07-10 05:04:08] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49060]
[2022-07-10 06:33:39] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-07-10 06:33:39] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:48350]
[2022-07-10 06:44:53] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:41130]
[2022-07-10 11:01:53] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-07-10 11:01:53] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:41130]
[2022-07-10 11:12:12] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:58512]
[2022-07-10 12:27:14] ws4py                          ERROR   : Failed to receive data
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ws4py/websocket.py", line 394, in once
    b = self.sock.recv(self.reading_buffer_size)
ConnectionResetError: [Errno 104] Connection reset by peer
[2022-07-10 12:27:14] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:58512]
[2022-07-10 12:39:11] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51148]
[2022-07-10 13:13:14] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:51148]
[2022-07-10 13:24:59] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:50182]
[2022-07-10 13:25:52] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48050]
[2022-07-10 13:25:55] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:53284]
[2022-07-10 13:25:59] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:53284]
[2022-07-10 13:26:04] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:59562]
[2022-07-10 13:26:41] frigate.object_processing      WARNING : Unable to create jpg because frame 1657452391.617895 is not in the cache
[2022-07-10 13:26:58] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:59562]
[2022-07-10 13:26:58] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48050]
