### ISSUE TITLE
[Support]: Coral TPU not detected in Frigate Home Assistant Addon 0.11-b5

### ISSUE THREAD

**Issue by Calimerorulez** [blakeblackshear/frigate#3483]
### Describe the problem you are having

Hi,

I just installed the latest HAOS 8.2, on a Proxmox VM. I installed the Coral M2 drivers in Proxmox, and the TPU is detected. I've passed through the Coral to the HAOS VM, and it is detected as `/dev/apex_0` in HA:

```
DEVNAME: /dev/apex_0
DEVPATH: /devices/pci0000:00/0000:00:10.0/apex/apex_0
MAJOR: '120'
MINOR: '0'
SUBSYSTEM: apex
```

I've installed the Frigate Full Access addon 0.11-b5, but the Coral isn't detected:

```
2022-07-17 15:09:56] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2022-07-17 15:09:56] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral_pci:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
```

My frigate.yml contains the following:

```
detectors:
  coral_pci:
    type: edgetpu
    device: pci
```

My CPU does support IOMMU groups in virtualisation. What am I missing?

Thank you for your help.

### Version

0.11.0-ef54cd6

### Frigate config file

```yaml
detectors:
  coral_pci:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
[2022-07-17 15:12:59] frigate.app                    INFO    : Starting Frigate (0.11.0-ef54cd6)
[2022-07-17 15:12:59] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-07-17 15:12:59] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-07-17 15:12:59] peewee_migrate                 INFO    : There is nothing to migrate
[2022-07-17 15:12:59] frigate.app                    INFO    : Output process started: 217
[2022-07-17 15:12:59] frigate.app                    INFO    : Camera processor started for flex_nw: 220
[2022-07-17 15:12:59] detector.coral_pci             INFO    : Starting detection process: 216
[2022-07-17 15:12:59] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2022-07-17 15:12:59] ws4py                          INFO    : Using epoll
[2022-07-17 15:12:59] frigate.app                    INFO    : Camera processor started for flex_n: 222
[2022-07-17 15:12:59] frigate.app                    INFO    : Camera processor started for flex_sw: 226
[2022-07-17 15:12:59] frigate.app                    INFO    : Capture process started for flex_nw: 230
[2022-07-17 15:12:59] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral_pci:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-07-17 15:12:59] frigate.app                    INFO    : Capture process started for flex_n: 231
[2022-07-17 15:12:59] frigate.app                    INFO    : Capture process started for flex_sw: 236
[2022-07-17 15:13:00] ws4py                          INFO    : Using epoll
[2022-07-17 15:13:20] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-07-17 15:13:20] frigate.app                    INFO    : Stopping...
[2022-07-17 15:13:20] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-07-17 15:13:20] frigate.watchdog               INFO    : Exiting watchdog...
[2022-07-17 15:13:20] frigate.stats                  INFO    : Exiting watchdog...
[2022-07-17 15:13:20] frigate.events                 INFO    : Exiting event cleanup...
[2022-07-17 15:13:20] frigate.record                 INFO    : Exiting recording cleanup...
[2022-07-17 15:13:20] frigate.events                 INFO    : Exiting event processor...
[2022-07-17 15:13:20] frigate.record                 INFO    : Exiting recording maintenance...
[2022-07-17 15:13:25] frigate.object_processing      INFO    : Exiting object processor...
[2022-07-17 15:13:25] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 12 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cmd] python3 exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Proxmox

### Install method

HassOS Addon

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Unifi G3 Flex

**Comment by Calimerorulez** [comment]
My bad...

Protection mode was on in the addon. Sorry for my confusion...
