### ISSUE TITLE
[Config Support]: ffmpeg error following update to latest HA. Working fine prior.

### ISSUE THREAD

**Issue by smcnab1** [blakeblackshear/frigate#3599]
### Describe the problem you are having

Updated last night and now getting 502: Bad Gateway with no change to config between (was working before).

Getting ffmpeg error in logs for addon.

### Version

3.1

### Frigate config file

```yaml
mqtt:
  host: 192.168XX
  port: 1883
  user: XXX
  password: XXX

detectors:
  cpu1:
    type: cpu

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous

detect:
  width: 1920
  height: 1080
  fps: 5
  enabled: True
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000

objects:
  track:
    - person
  mask: 1316,471,886,446,246,649,502,904,1448,663
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.7
      mask: 1316,471,886,446,246,649,502,904,1448,663

motion:
  threshold: 25
  contour_area: 30
  delta_alpha: 0.2
  frame_alpha: 0.2
  frame_height: 50
  mask: 1316,471,886,446,246,649,502,904,1448,663
  improve_contrast: True

record:
  enabled: true
  retain: 
    days: 0
    mode: all
  events:
    max_seconds: 300
    pre_capture: 5
    post_capture: 5
    objects:
      - person
    retain:
      default: 10
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: true
  timestamp: true
  bounding_box: false
  crop: false
  retain:
    default: 10
    objects:
      person: 15
  
live:
  height: 1920
  quality: 8
  
timestamp_style:
  position: tl
  format: "%d/%m/%y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: None

cameras:
  Hall:
    ffmpeg:
      inputs:
        - path: rtsp://XXX@192.168XXX/stream1
          roles:
            - record
        - path: rtsp://XXX@192.168XXX/stream2
          roles:
            - detect

  Living_Room:
    ffmpeg:
      inputs:
        - path: rtsp://XXX@192.168XXX/stream1
          roles:
            - record
        - path: rtsp://XXX@192.168XXX/stream2
          roles:
            - detect

  Bedroom:
    ffmpeg:
      inputs:
        - path: rtsp://XXX@192.168XXX/stream1
          roles:
            - record
        - path: rtsp://XXX@192.168XXX/stream2
          roles:
            - detect

  mqtt:
    enabled: true
    timestamp: true
    bounding_box: true
    crop: true
    height: 270
    quality: 70
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-08-07 10:16:17] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 511, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 329, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 1022, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 856, in validate
    v, errors = self._validate_mapping_like(v, values, loc, cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 991, in _validate_mapping_like
    value_result, value_errors = self._validate_singleton(v_, values, v_loc, cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1064, in _validate_singleton
    value, error = field.validate(v, values, loc=loc, cls=cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 854, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1071, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1118, in _apply_validators
    v = validator(cls, v, values, self, self.model_config)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/class_validators.py", line 313, in <lambda>
    return lambda cls, v, values, field, config: validator(v)
  File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 676, in validate
    return cls(**value)
  File "/opt/frigate/frigate/config.py", line 548, in __init__
    if len(config["ffmpeg"]["inputs"]) == 1:
KeyError: 'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by smcnab1** [comment]
Legend! All sorted thanks mate @NickM-27
