### ISSUE TITLE
[Camera Support]: Hikvision DS-2CD2023G0-I  -  Unable to read frames from ffmpeg process.

### ISSUE THREAD

**Issue by a1ekseev** [blakeblackshear/frigate#3601]
### Describe the problem you are having

During boot-up, first the screen is green, then the camera image appears.
Then the process in the container ends with an error:
```log
frigate  | [2022-08-07 13:47:34] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-08-07 13:47:34] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
```

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: mosquitto
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60

database:
  path: /media/frigate/frigate.db

rtmp:
  enabled: True

live:
  height: 720
  quality: 8

model:
  path: /edgetpu_model.tflite
  labelmap_path: /labelmap.txt
  width: 320
  height: 320

logger:
  default: debug

timestamp_style:
  position: "br"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 255
  thickness: 2

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

ffmpeg:
  global_args: 
   - -hide_banner 
   - -loglevel 
   - debug
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p


cameras:
  camera_1: 
    ffmpeg:
      inputs:
        - path: rtsp://user:password@10.10.10.51:554/ISAPI/Streaming/Channels/101
          roles:
            - detect
            - rtmp
    detect:
      width: 1920 
      height: 1080
```

### Relevant log output

```shell
⠿ Container frigate  Created                                                                                                                                                                                 0.0s
Attaching to frigate
frigate  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
frigate  | [s6-init] ensuring user provided files have correct perms...exited 0.
frigate  | [fix-attrs.d] applying ownership & permissions fixes...
frigate  | [fix-attrs.d] done.
frigate  | [cont-init.d] executing container initialization scripts...
frigate  | [cont-init.d] done.
frigate  | [services.d] starting services
frigate  | [services.d] done.
frigate  | [2022-08-07 13:28:32] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
frigate  | Starting migrations
frigate  | [2022-08-07 13:28:32] peewee_migrate                 INFO    : Starting migrations
frigate  | [2022-08-07 13:28:32] peewee                         DEBUG   : ('CREATE TABLE IF NOT EXISTS "migratehistory" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "migrated_at" DATETIME NOT NULL)', [])
frigate  | [2022-08-07 13:28:32] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."name", "t1"."migrated_at" FROM "migratehistory" AS "t1" ORDER BY "t1"."id"', [])
frigate  | There is nothing to migrate
frigate  | [2022-08-07 13:28:32] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | [2022-08-07 13:28:32] frigate.mqtt                   DEBUG   : MQTT connected
frigate  | [2022-08-07 13:28:32] frigate.app                    INFO    : Output process started: 219
frigate  | [2022-08-07 13:28:32] detector.cpu                   INFO    : Starting detection process: 217
frigate  | [2022-08-07 13:28:32] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | Process detector:cpu:
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
frigate  |     self.run()
frigate  |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
frigate  |     self._target(*self._args, **self._kwargs)
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector
frigate  |     object_detector = LocalObjectDetector(
frigate  |   File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
frigate  |     self.interpreter.allocate_tensors()
frigate  |   File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
frigate  |     return self._interpreter.AllocateTensors()
frigate  | RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.
frigate  | 
frigate  | [2022-08-07 13:28:32] frigate.app                    INFO    : Camera processor started for camera_1: 222
frigate  | [2022-08-07 13:28:32] ws4py                          INFO    : Using epoll
frigate  | [2022-08-07 13:28:32] frigate.app                    INFO    : Capture process started for camera_1: 223
frigate  | [2022-08-07 13:28:32] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-08-07 13:28:32] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-08-07 13:28:32] ws4py                          INFO    : Using epoll
frigate  | [2022-08-07 13:28:32] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)
frigate  | [2022-08-07 13:28:32] peewee                         DEBUG   : ('UPDATE "event" SET "end_time" = ("event"."start_time" + ?) WHERE ("event"."end_time" IS ?)', [30, None])
frigate  | [2022-08-07 13:28:52] watchdog.camera_1              ERROR   : Ffmpeg process crashed unexpectedly for camera_1.
frigate  | [2022-08-07 13:28:52] watchdog.camera_1              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | [2022-08-07 13:28:52] ffmpeg.camera_1.detect         ERROR   : Unrecognized option 'loglevel debug'.
frigate  | [2022-08-07 13:28:52] ffmpeg.camera_1.detect         ERROR   : Error splitting the argument list: Option not found
frigate  | [2022-08-07 13:28:52] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
frigate  | [2022-08-07 13:28:52] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
frigate  | [2022-08-07 13:28:52] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate  | [cont-finish.d] executing container finish scripts...
frigate  | [cont-finish.d] done.
frigate  | [s6-finish] waiting for services.
frigate  | [s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
ffprobe rtsp://user:password@10.10.10.51:554/ISAPI/Streaming/Channels/101
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, rtsp, from 'rtsp://admin:Cross551271@10.10.10.51:554/ISAPI/Streaming/Channels/101':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.240000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
  Stream #0:1: Data: none
Unsupported codec with id 0 for input stream 1
```

### Frigate stats

```json
{
    "camera_1": {
        "camera_fps": 3.35,
        "capture_pid": 224,
        "detection_fps": 0.0,
        "pid": 223,
        "process_fps": 0.0,
        "skipped_fps": 0.0
    },
    "detection_fps": 0.0,
    "detectors": {
        "cpu1": {
            "detection_start": 0.0,
            "inference_speed": 10.0,
            "pid": 217
        },
        "cpu2": {
            "detection_start": 0.0,
            "inference_speed": 10.0,
            "pid": 219
        }
    },
    "service": {
        "storage": {
            "/dev/shm": {
                "free": 122.5,
                "mount_type": "tmpfs",
                "total": 134.2,
                "used": 11.7
            },
            "/media/frigate/clips": {
                "free": 217711.7,
                "mount_type": "overlay",
                "total": 238601.4,
                "used": 8694.9
            },
            "/media/frigate/recordings": {
                "free": 217711.7,
                "mount_type": "overlay",
                "total": 238601.4,
                "used": 8694.9
            },
            "/tmp/cache": {
                "free": 2000.0,
                "mount_type": "tmpfs",
                "total": 2000.0,
                "used": 0.0
            }
        },
        "temperatures": {},
        "uptime": 2,
        "version": "0.10.1-83481af"
    }
}
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision DS-2CD2023G0-I

**Comment by NickM-27** [comment]
Please rerun without the logger set to debug. It is way too verbose and we don't need that information. 

Does the canners work without hwaccel defined?

**Comment by julianbadell** [comment]
Try installing Frigate beta - this solved the problem for me

**Comment by a1ekseev** [comment]
> Try installing Frigate beta - this solved the problem for me

It didn't work.

**Comment by a1ekseev** [comment]
> Please rerun without the logger set to debug. It is way too verbose and we don't need that information.
> 
> Does the canners work without hwaccel defined?

```log
[2022-08-20 12:23:29] detector.cpu1                  INFO    : Starting detection process: 215
[2022-08-20 12:23:29] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
Process detector:cpu1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 62, in __init__
    self.interpreter.allocate_tensors()
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.

[2022-08-20 12:23:29] frigate.app                    INFO    : Output process started: 218
[2022-08-20 12:23:29] frigate.app                    INFO    : Camera processor started for camera_1: 220
[2022-08-20 12:23:29] detector.cpu2                  INFO    : Starting detection process: 217
[2022-08-20 12:23:29] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
Process detector:cpu2:
[2022-08-20 12:23:29] ws4py                          INFO    : Using epoll
[2022-08-20 12:23:29] frigate.app                    INFO    : Capture process started for camera_1: 223
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 62, in __init__
    self.interpreter.allocate_tensors()
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 408, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: edgetpu-custom-op.Node number 0 (edgetpu-custom-op) failed to prepare.

[2022-08-20 12:23:30] ws4py                          INFO    : Using epoll
[2022-08-20 12:23:47] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60300]
[2022-08-20 12:23:50] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-08-20 12:23:50] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-08-20 12:23:50] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:60300]
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[2022-08-20 12:23:50] frigate.video                  ERROR   : camera_1: Unable to read frames from ffmpeg process.
[2022-08-20 12:23:50] frigate.video                  ERROR   : camera_1: ffmpeg process is not running. exiting capture thread...
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

```

**Comment by NickM-27** [comment]
Remove 

```yaml
model:
  path: /edgetpu_model.tflite
  labelmap_path: /labelmap.txt
  width: 320
  height: 320

```

from your config, you're manually setting it to use the edge tpu model when you don't have a coral.

**Comment by a1ekseev** [comment]
> Remove
> 
> ```yaml
> model:
>   path: /edgetpu_model.tflite
>   labelmap_path: /labelmap.txt
>   width: 320
>   height: 320
> ```
> 
> from your config, you're manually setting it to use the edge tpu model when you don't have a coral.

That helped, thank you.
