### ISSUE TITLE
Frigate NVR auto stops

### ISSUE THREAD

**Issue by itsboo07** [blakeblackshear/frigate#3634]
### Describe the problem you are having

0hi im new to this and trying to setup Frigate NVR . when i try to hit start from add on and open Frigate side bar . it asks me again to start , error (Add-on is not running. Please start it first).. sometimes when i open sidebar it gets into frigrate but all stays black except for logo. and by refreshing the webpage again it asks me to start. 
i tried to restart ha , addon and even reinstalled but nothing worked...can anyone help 

### Version

 version: 3.1 

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.203
  user: mqtt-user
  password: Boo123
  
camera:
  main_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:Boo@12345@192.168.0.170:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    width: 1440
    hight: 1620
    fps: 5
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-08-12 14:52:28] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
2 validation errors for FrigateConfig
cameras
  field required (type=value_error.missing)
camera
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
cameras
  field required (type=value_error.missing)
camera
  extra fields not permitted (type=value_error.extra)
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

PCIe

### Any other information that may be helpful

running home asssistant in vm in windows 11

**Comment by NickM-27** [comment]
The logs are indicating your config is invalid. In this case you called it `camera` but the top level field needs to be `cameras`

**Comment by NickM-27** [comment]
You also have added width and height without the `detect` header which will also fail

**Comment by blakeblackshear** [comment]
Please reference the current documentation. It looks like you are following an outdated video tutorial.
