### ISSUE TITLE
[Support]: FFMPEG not working (crashing) after upgrading packages - no camera feeds - Frigate 0.11 RC1

### ISSUE THREAD

**Issue by LaurenceGough** [blakeblackshear/frigate#3705]
### Describe the problem you are having

Hello,

After updating my packages using apt upgrade on my Raspberry Pi 4 (DietPi arm64 bit OS) my Frigate 0.11 RC1 container is no longer displaying camera feeds. If I restore my Pi to the time before installing the application upgrades (apt upgrade) all is fine.

I don't have stimeout set and this message isn't showing in the logs at all.

Output of the apt upgrade upgradable (apt list --upgradable) list below:

`base-files/stable 11.1+deb11u4 arm64 [upgradable from: 11.1+deb11u3]
bash/stable 5.1-2+deb11u1 arm64 [upgradable from: 5.1-2+b3]
containerd.io/bullseye 1.6.7-1 arm64 [upgradable from: 1.6.4-1]
curl/stable-security 7.74.0-1.3+deb11u2 arm64 [upgradable from: 7.74.0-1.3+deb11u1]
dirmngr/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
docker-ce-cli/bullseye 5:20.10.17~3-0~debian-bullseye arm64 [upgradable from: 5:20.10.16~3-0~debian-bullseye]
docker-ce/bullseye 5:20.10.17~3-0~debian-bullseye arm64 [upgradable from: 5:20.10.16~3-0~debian-bullseye]
dpkg/stable 1.20.11 arm64 [upgradable from: 1.20.10]
firmware-atheros/stable 1:20210315-3+rpt7 all [upgradable from: 1:20210315-3+rpt5]
firmware-brcm80211/stable 1:20210315-3+rpt7 all [upgradable from: 1:20210315-3+rpt5]
firmware-iwlwifi/stable 1:20210315-3+rpt7 all [upgradable from: 1:20210315-3+rpt5]
firmware-misc-nonfree/stable 1:20210315-3+rpt7 all [upgradable from: 1:20210315-3+rpt5]
firmware-realtek/stable 1:20210315-3+rpt7 all [upgradable from: 1:20210315-3+rpt5]
gnupg-l10n/stable,stable-security 2.2.27-2+deb11u2 all [upgradable from: 2.2.27-2+deb11u1]
gnupg-utils/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
gnupg/stable,stable-security 2.2.27-2+deb11u2 all [upgradable from: 2.2.27-2+deb11u1]
gpg-agent/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
gpg-wks-client/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
gpg-wks-server/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
gpg/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
gpgconf/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
gpgsm/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
gpgv/stable,stable-security 2.2.27-2+deb11u2 arm64 [upgradable from: 2.2.27-2+deb11u1]
libc-bin/stable 2.31-13+rpt2+rpi1+deb11u3 arm64 [upgradable from: 2.31-13+rpt2+rpi1+deb11u2]
libc-l10n/stable 2.31-13+rpt2+rpi1+deb11u3 all [upgradable from: 2.31-13+rpt2+rpi1+deb11u2]
libc6/stable 2.31-13+rpt2+rpi1+deb11u3 arm64 [upgradable from: 2.31-13+rpt2+rpi1+deb11u2]
libcurl4/stable-security 7.74.0-1.3+deb11u2 arm64 [upgradable from: 7.74.0-1.3+deb11u1]
libgnutls30/stable-security 3.7.1-5+deb11u2 arm64 [upgradable from: 3.7.1-5]
libldb2/stable-security 2:2.2.3-2~deb11u2 arm64 [upgradable from: 2:2.2.3-2~deb11u1]
libpam-modules-bin/stable 1.4.0-9+deb11u1+rpt2 arm64 [upgradable from: 1.4.0-9+deb11u1+rpt1]
libpam-modules/stable 1.4.0-9+deb11u1+rpt2 arm64 [upgradable from: 1.4.0-9+deb11u1+rpt1]
libpam-runtime/stable 1.4.0-9+deb11u1+rpt2 all [upgradable from: 1.4.0-9+deb11u1+rpt1]
libpam0g/stable 1.4.0-9+deb11u1+rpt2 arm64 [upgradable from: 1.4.0-9+deb11u1+rpt1]
libsmbclient/stable-security 2:4.13.13+dfsg-1~deb11u5 arm64 [upgradable from: 2:4.13.13+dfsg-1~deb11u3]
libssl1.1/stable 1.1.1n-0+deb11u3+rpt1 arm64 [upgradable from: 1.1.1n-0+deb11u2+rpt1]
libtirpc-common/stable-security 1.3.1-1+deb11u1 all [upgradable from: 1.3.1-1]
libtirpc3/stable-security 1.3.1-1+deb11u1 arm64 [upgradable from: 1.3.1-1]
libwbclient0/stable-security 2:4.13.13+dfsg-1~deb11u5 arm64 [upgradable from: 2:4.13.13+dfsg-1~deb11u3]
locales/stable 2.31-13+rpt2+rpi1+deb11u3 all [upgradable from: 2.31-13+rpt2+rpi1+deb11u2]
nano/stable 5.4-2+deb11u1 arm64 [upgradable from: 5.4-2]
openssh-client/stable 1:8.4p1-5+deb11u1 arm64 [upgradable from: 1:8.4p1-5]
openssh-sftp-server/stable 1:8.4p1-5+deb11u1 arm64 [upgradable from: 1:8.4p1-5]
openssl/stable 1.1.1n-0+deb11u3+rpt1 arm64 [upgradable from: 1.1.1n-0+deb11u2+rpt1]
python3-ldb/stable-security 2:2.2.3-2~deb11u2 arm64 [upgradable from: 2:2.2.3-2~deb11u1]
raspberrypi-bootloader/stable 1:1.20220811-1 arm64 [upgradable from: 1:1.20220331-1]
raspberrypi-kernel/stable 1:1.20220811-1 arm64 [upgradable from: 1:1.20220331-1]
rpi-eeprom/stable 13.16-1 arm64 [upgradable from: 13.14-1]
tzdata/stable-updates 2021a-1+deb11u5 all [upgradable from: 2021a-1+deb11u3]
unzip/stable-security 6.0-26+deb11u1 arm64 [upgradable from: 6.0-26]
wireless-regdb/stable 2022.04.08-2~deb11u1 all [upgradable from: 2020.04.29-2]`

Any ideas?

Thank you in advance

### Version

0.11.0-37325C7

### Frigate config file

```yaml
Not included for now (very basic config)
```

### Relevant log output

```shell
[2022-08-23 22:15:52] watchdog.Cam1             ERROR   : Ffmpeg process crashed unexpectedly for Cam1.
[2022-08-23 22:15:52] watchdog.Cam1             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-08-23 22:15:52] ffmpeg.Cam1.detect        ERROR   : [flv @ 0x559b29d820] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-08-23 22:15:52] watchdog.Cam2               ERROR   : Ffmpeg process crashed unexpectedly for Cam2.
[2022-08-23 22:15:52] watchdog.Cam2               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-08-23 22:15:52] ffmpeg.Cam2.detect          ERROR   : [segment @ 0x55948e3ee0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-08-23 22:15:52] ffmpeg.Cam2.detect          ERROR   : [segment @ 0x55948e3ee0] Non-monotonous DTS in output stream 0:0; previous: 0, current: 0; changing to 1. This may result in incorrect timestamps in the output file.
[2022-08-23 22:16:12] watchdog.Cam1             INFO    : No frames received from Cam1 in 20 seconds. Exiting ffmpeg...
[2022-08-23 22:16:12] watchdog.Cam1             INFO    : Waiting for ffmpeg to exit gracefully...
[2022-08-23 22:16:12] watchdog.Cam2               INFO    : No frames received from Cam2 in 20 seconds. Exiting ffmpeg...
[2022-08-23 22:16:12] watchdog.Cam2               INFO    : Waiting for ffmpeg to exit gracefully...
[2022-08-23 22:16:42] watchdog.Cam1             INFO    : FFmpeg didnt exit. Force killing...
[2022-08-23 22:16:42] frigate.video                  ERROR   : Cam1: Unable to read frames from ffmpeg process.
[2022-08-23 22:16:42] frigate.video                  ERROR   : Cam1: ffmpeg process is not running. exiting capture thread...
[2022-08-23 22:16:42] watchdog.Cam2               INFO    : FFmpeg didnt exit. Force killing...
[2022-08-23 22:16:42] frigate.video                  ERROR   : Cam2: Unable to read frames from ffmpeg process.
[2022-08-23 22:16:42] frigate.video                  ERROR   : Cam2: ffmpeg process is not running. exiting capture thread...
[2022-08-23 22:16:46] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:57696]
[2022-08-23 22:16:49] frigate.record                 WARNING : Discarding a corrupt recording segment: Cam2-20220823221556.mp4
[2022-08-23 22:16:52] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:36348]
[2022-08-23 22:16:52] watchdog.Cam1             ERROR   : Ffmpeg process crashed unexpectedly for Cam1.
[2022-08-23 22:16:52] watchdog.Cam1             ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-08-23 22:16:52] ffmpeg.Cam1.detect        ERROR   : [flv @ 0x55b831e820] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[2022-08-23 22:16:52] watchdog.Cam2               ERROR   : Ffmpeg process crashed unexpectedly for Cam2.
[2022-08-23 22:16:52] watchdog.Cam2               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-08-23 22:16:52] ffmpeg.Cam2.detect          ERROR   : [segment @ 0x55d4b6a360] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```

### FFprobe output from your camera

```shell
Not installed ffprobe but the cameras worked fine before - I can install it if needed!
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A for this issue I believe

**Comment by NickM-27** [comment]
Are you using hwaccel being used? If so, does it work without it?

**Comment by LaurenceGough** [comment]
> Are you using hwaccel being used? If so, does it work without it?

Yes, I am using:
ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m
    
    
    After testing without hardware acceleration enabled all is working fine even when fully updated although there was a crash at first for one camera and one camera was green (no feed of course) for 30-40 seconds or so. 
    
    All is working fine for now though. Hmmm, interesting, perhaps a Pi related update that's broken something?
   
    [2022-08-23 22:44:51] watchdog.Cam1               ERROR   : Ffmpeg process crashed unexpectedly for Cam1.
[2022-08-23 22:44:51] watchdog.Cam1               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-08-23 22:44:51] ffmpeg.Cam1.detect          ERROR   : [rtsp @ 0x55635a1e40] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
[2022-08-23 22:44:51] ffmpeg.Cam1.detect          ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[2022-08-23 22:44:51] ffmpeg.Cam1.detect          ERROR   : Output file #0 does not contain any stream
[2022-08-23 22:44:51] ffmpeg.Cam1.rtmp            ERROR   : [rtsp @ 0x559cbf9ce0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
[2022-08-23 22:44:51] ffmpeg.Cam1.rtmp            ERROR   : Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[2022-08-23 22:44:51] ffmpeg.Cam1.rtmp            ERROR   : Output file #0 does not contain any stream
[2022-08-23 22:44:51] watchdog.Cam1               INFO    : Terminating the existing ffmpeg process...
[2022-08-23 22:44:51] watchdog.Cam1               INFO    : Waiting for ffmpeg to exit gracefully...

**Comment by NickM-27** [comment]
As the other issue pointed out, something broke that affects the way the gpu is being passed to the container. 

If you want, you can try the upcoming build based on ffmpeg btbn 5.1 (perhaps it has some compatibility that is fixed), otherwise it may be a package that just shouldn't be updated. 

`crzynik/frigate:btbn-ffmpeg`

**Comment by LaurenceGough** [comment]
Yes, agreed, thanks so much for your help too. I'm just trying to work out how to uninstall that particular kernel update but I'm not having any luck yet.

raspberrypi-kernel/stable 1:1.20220811-1 arm64 [upgradable from: 1:1.20220331-1] I guess is the issue, so I was trying to revert back to 1:1.20220331-1 but perhaps easier to restore from backup and trying upgrading everything else, bit of a ballache :D

**Comment by krim404** [comment]
i can confirm that this issue is not a problem with the kernel, but with the ffmpeg version 4.3.4. Found a few reports that 4.3.4 has a bug on hardware decoding. With 4.3.3 everything works as it should.

Can you confirm, if hardwarencoding is working, when you use `image: blakeblackshear/frigate:0.11.0-3de1948` ?

**Comment by NickM-27** [comment]
@krim404 the user changed nothing but updating apt, so that claim doesn't make any sense considering the same ffmpeg / frigate version is used and a backup renders it working again. 

Also that Frigate RC1 uses ffmpeg 5.0.1 not 4.3.4

**Comment by krim404** [comment]
it looks a lot like the issue i have, evaluating if it is working with an older version of ffmpeg could not harm at all.
The issue seems to be since 4.3.4, including 5.0.1 from rc1.

Based on other bugtracker entries the bug first appeared in the master branch of ffmpeg with version number around 4.3.4.

**Comment by NickM-27** [comment]
> evaluating if it is working with an older version of ffmpeg could not harm at all.

The problem is reverting to the build you mentioned isn't just an ffmpeg change, it will not work with and potentially corrupt the database from rc1. rc1 also includes many other dependency changes for hwaccel (including a different build of ffmpeg).

**Comment by krim404** [comment]
true, didnt think about that. but maybe running on a new (clean) database just for testing purpose?

**Comment by NickM-27** [comment]
> true, didnt think about that. but maybe running on a new (clean) database just for testing purpose?

I don't think there's anything wrong with trying it on a clean setup, but the ramifications should be mentioned (like they now have been). 

I was just trying to point out that OP has been using RC1 / 5.0.1 for some time with hwaccel working; it only stopped after updating the apt dependencies listed above and both good and bad states are fully reproducible. So the suggestion that it is an isolated ffmpeg bug and 5.0.1 hwaccel is faulty doesn't hold water from my perspective.

**Comment by ccbadd** [comment]
I seem to be having the same problem with both versions 3.1 and beta 0.11.0 version from HACS.  Here is the log::
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-08-26 11:17:35] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1022, in pydantic.main.validate_model
  File "pydantic/fields.py", line 856, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 991, in pydantic.fields.ModelField._validate_mapping_like
  File "pydantic/fields.py", line 1064, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 854, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1071, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1118, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic/main.py", line 676, in pydantic.main.BaseModel.validate
  File "/opt/frigate/frigate/config.py", line 548, in __init__
    if len(config["ffmpeg"]["inputs"]) == 1:
KeyError: 'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
Was working fine Sunday but just stopped on Monday.  Same error with both versions.

**Comment by NickM-27** [comment]
> I seem to be having the same problem with both versions 3.1 and beta 0.11.0 version from HACS

@ccbadd No, this is not related at all. OP is talking about hardware acceleration issues meanwhile you have a formatting error in your config file. Please make your own issue and provide the config file.

**Comment by NickM-27** [comment]
We have a new build of ffmpeg in 0.11 RC2 so maybe give that a try

**Comment by krim404** [comment]
sadly RC2 did not help at all. issue persists.

**Comment by NickM-27** [comment]
@krim404 Thanks for checking, I would recommend trying to reconfigure your OS as I have been running this RC on my test Pi for 2 days with hwacel working. In the below screenshot you can see my OS information (including kernel version), frigate config, and that 108MB of GPU memory are currently allocated to frigate.

![Screen Shot 2022-08-28 at 08 52 55 AM](https://user-images.githubusercontent.com/14866235/187080438-f3a0bf83-b4c6-4438-bcd2-b5ed5c70607e.png)

**Comment by krim404** [comment]
as far as i can see it is an issue with one of the ffmpeg libraries, as i can get it running using the libraries and the binary from before and also with a different data stream.

this bug seems to be only in effect when streaming h264 videos which have a (not yet discovered) encoding configuration - so it will not affect all camera streams

**Comment by NickM-27** [comment]
> this bug seems to be only in effect when streaming h264 videos which have a (not yet discovered) encoding configuration - so it will not affect all camera streams. sadly i can reproduce it with a lot of expensive cameras like from axis, while its perfectly working with cheap cameras like from foscam.

I see, that is interesting, maybe some different input args could help. Another tip might be to try using rtsp-simple-server as a proxy for the cameras streams as it might provide a more compatible stream.

I have also seen more RPi improvements / fixes that are supposed come in future ffmpeg versions.

At this point we are bound to ffmpeg >= 5, so if those don't work then the solution may be to override the ffmpeg binary used in the container via docker volume mappings until it is fixed upstream.

**Comment by NickM-27** [comment]
There's another user that saw the same thing after updating kernel as well https://github.com/blakeblackshear/frigate/issues/3780

**Comment by krim404** [comment]
> There's another user that saw the same thing after updating kernel as well #3780

had a few free minutes.
i just checked by installing an older raspberry os version with the exact same kernel which you and @LaurenceGough were using (before his upgrade), the issue persists.

pretty sure it has nothing to do with the kernel itself.

**Comment by NickM-27** [comment]
> > There's another user that saw the same thing after updating kernel as well #3780
> 
> had a few free minutes. i just checked by installing an older raspberry os version with the exact same kernel which you and @LaurenceGough were using (before his upgrade), the issue persists.
> 
> pretty sure it has nothing to do with the kernel itself.

There can be multiple issues that have the same symptoms. 

Also, I think saying it has nothing to do with the kernel is a bit disingenuous as we now have multiple users that had a fully working setup which stopped working after updating the kernel. Not to mention that #3780 linked to multiple issues that have been created by other users which also found the kernel to be at fault.

Just because your specific case is kernel independent in no way means that it isn't causing issues for other users who had working hwaccel setups before updating.

**Comment by krim404** [comment]
> Just because your specific case is kernel independent in no way means that it isn't causing issues for other users who had working hwaccel setups before updating.

i evaluated it with the files supported by the people reporting it as an kernel error, not with my own streams. the problem seem to come from a bundled library, as it is indeed working when i use an older SD image. 

If it would've been a kernel problem it would never work inside a docker image, as these share the kernel.

**Comment by NickM-27** [comment]
Going to close as this issue with more information is covered in https://github.com/blakeblackshear/frigate/issues/3780
