### ISSUE TITLE
events stop working

### ISSUE THREAD

**Issue by vMeph** [blakeblackshear/frigate#3713]
### Describe the problem you are having

cant get events to work, was working before i try the beta, i have reverted back and now nothing 

### Version

0.10.1-83481af

### Frigate config file

```yaml
detectors:
  coral:
    type: edgetpu
    device: usb
    
mqtt:
  host: xxx.xxxx.xxx.xxxx
  port: 1883
  topic_prefix: xxx
  client_id: xxxx
  user: xxxxxxxxxxx
  password: xxxxxxxxxxxx
  stats_interval: 60

cameras:
  quintal:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxx:xxxxxxxxx@192.xxx.xxx.xxx:554/h264Preview_01_sub
          roles:
            - detect

    objects:
       track:
         - person
       filters:
         person:
           threshold: 0.7 
   
    detect:
      width: 2304
      height: 1296

    record:
      enabled: False
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 14
          mode: active_objects
      
  front_door:
    ffmpeg:

      inputs:
        - path: rtsp://xxxx:xxxxxxx@xxx.xxx.x.xx:554/h264Preview_01_sub     
          roles:
            - detect
            - clips
    zones:
      entrada:
        coordinates: 583,1296,0,562,0,431,525,165,1395,486,1618,367,2211,559,1382,1296

    snapshots:
      enabled: True
      timestamp: false
      bounding_box: true
      retain:
        default: 3

#    clips:
#      enabled: True
#      retain:
#        default: 1
#    motion:
#      mask:
#        - 553,137,1669,455,1675,0,0,0,0,201,0,390
#        - 1544,1296,2304,1296,2304,1192,1550,1193
    motion:
      mask:
        - 519,173,1419,518,1661,391,2186,566,1341,1296,2304,1296,2304,0,0,0,0,426
        - 1544,1296,2304,1296,2304,1192,1550,1193

    objects:
       track:
         - person
       filters:
         person:
           threshold: 0.7 
          
      
    record:
      enabled: True
      retain:
        days: 7
        mode: active_objects
      events:
        retain:
          default: 14
          mode: active_objects
          
    detect:
      width: 2304
      height: 1296
```

### Relevant log output

```shell
[2022-08-26 18:50:33] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-08-26 18:50:34] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-08-26 18:50:34] peewee_migrate                 INFO    : There is nothing to migrate
[2022-08-26 18:50:34] detector.coral                 INFO    : Starting detection process: 224
[2022-08-26 18:50:34] frigate.app                    INFO    : Output process started: 226
[2022-08-26 18:50:34] frigate.app                    INFO    : Camera processor started for quintal: 231
[2022-08-26 18:50:34] ws4py                          INFO    : Using epoll
[2022-08-26 18:50:34] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-08-26 18:50:34] frigate.app                    INFO    : Camera processor started for front_door: 233
[2022-08-26 18:50:36] frigate.edgetpu                INFO    : TPU found
[2022-08-26 18:50:34] frigate.app                    INFO    : Capture process started for quintal: 236
[2022-08-26 18:50:34] frigate.app                    INFO    : Capture process started for front_door: 240
[2022-08-26 18:50:34] ws4py                          INFO    : Using epoll
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Exception in thread event_processor:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/events.py", line 67, in run
    Event.replace(
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1898, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1969, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2730, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2466, in _execute
    return self.handle_result(database, cursor)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2739, in handle_result
    return database.last_insert_id(cursor, self._query_type)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3218, in last_insert_id
    return cursor.lastrowid
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 88, in lastrowid
    self._wait()
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3136, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2902, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

**Comment by NickM-27** [comment]
Please read the release notes before updating. 

![Screen Shot 2022-08-26 at 12 02 03 PM](https://user-images.githubusercontent.com/14866235/186964942-05e00dfd-b733-4d96-8801-3112458563c7.png)

As is stated in the breaking changes section: 

> Upgrading to the beta will run migrations on the database file that are not backwards compatible. In order to rollback to 0.10.0, you will either need to restore an old database file or delete the database files so they can be recreated.

If you don't have a backup of the DB then you'll need to delete it and start fresh.

**Comment by vMeph** [comment]
@NickM-27 missed the part of backwards compatible grrr
thanks alot
