### ISSUE TITLE
[Support]: 0.11.0-rc1 working ok but rc2 broke ffmpeg

### ISSUE THREAD

**Issue by jcastro** [blakeblackshear/frigate#3722]
### Describe the problem you are having

Camera output is green

### Version

0.11.0-rc2

### Frigate config file

```yaml
mqtt:
  host: 10.0.1.30
  user: mosquitto
  password: XXXXX

ui:
  use_experimental: true

cameras:
  entrance_cam:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.1.116/11
          roles:
            - detect
    motion:
      threshold: 1
#      mask:
#        - 399,170,450,181,481,0,415,0
    detect:
      width: 640
      height: 360
      fps: 10
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the $
      max_disappeared: 350
      stationary:
        interval: 90
        #threshold: 50
    objects:
      track:
        - person
      mask: 399,170,450,181,481,0,415,0
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
      width: 640
      height: 360
      fps: 10
      # Optional: enables detection for the camera (default: True)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the $
      max_disappeared: 350
      stationary:
        interval: 90
        #threshold: 50
    objects:
      track:
        - person
      mask: 399,170,450,181,481,0,415,0
      filters:
        person:
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 5000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 100000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.77
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive ($
          threshold: 0.70
    record:
      enabled: True
      retain_days: 1
      events:
        retain:
          default: 1

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
          max_area: 100000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.77
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive ($
          threshold: 0.70
    record:
      enabled: True
      retain_days: 1
      events:
        retain:
          default: 1

    # Optional: Configuration for the jpg snapshots written to the clips directory for each event
    snapshots:
      # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
      # This value can be set via MQTT and will be updated in startup based on retained value
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: False
      # Optional: height to resize the snapshot to (default: original size)
      #height: 480
      # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
      required_zones: []
      # Optional: Camera override for retention settings (default: global values)
      retain:
        # Required: Default retention days (default: shown below)
        default: 1
        # Optional: Per object retention days
        objects:
          person: 1

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
[2022-08-28 17:48:58] frigate.app                    INFO    : Starting Frigate (0.11.0-c461c9e)
[2022-08-28 17:48:58] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
Starting migrations
[2022-08-28 17:48:58] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-08-28 17:48:58] peewee_migrate                 INFO    : There is nothing to migrate
[2022-08-28 17:48:58] detector.coral                 INFO    : Starting detection process: 224
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
[2022-08-28 17:48:58] frigate.app                    INFO    : Output process started: 225
Process output_processor:
[2022-08-28 17:48:58] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-08-28 17:48:58] ws4py                          INFO    : Using epoll
[2022-08-28 17:48:58] frigate.app                    INFO    : Camera processor started for entrance_cam: 228
[2022-08-28 17:48:58] frigate.app                    INFO    : Capture process started for entrance_cam: 232
[2022-08-28 17:48:58] ws4py                          INFO    : Using epoll
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/output.py", line 372, in output_frames
    converters[camera] = FFMpegConverter(
  File "/opt/frigate/frigate/output.py", line 36, in __init__
    self.process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
[2022-08-28 17:49:01] frigate.edgetpu                INFO    : TPU found
[2022-08-28 17:50:05] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46050]
[2022-08-28 17:50:43] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46050]
[2022-08-28 17:50:43] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46052]
[2022-08-28 17:50:51] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:46052]```
```

### FFprobe output from your camera

```shell
➜  ~ ffprobe rtsp://10.0.1.116/11
ffprobe version 5.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/5.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-neon
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, rtsp, from 'rtsp://10.0.1.116/11':
  Metadata:
    title           : ww live test
  Duration: N/A, start: 0.050000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, progressive), 1280x720, 20 fps, 20 tbr, 90k tbn
➜  ~
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Aqara G2H

**Comment by blakeblackshear** [comment]
You must be overriding your PATH variable somewhere

**Comment by jcastro** [comment]
I've tried to set PATH variable to
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jellyfin-ffmpegin-ffmpeg`
I've also tried to remove the variable con Portainer but I'm getting same results.

Am I supposed to set a variable or just remove the variable?

**Comment by NickM-27** [comment]
We aren't using jellyfin ffmpeg anymore so that won't work. Ideally the path isn't overridden and it is accepted as is. https://github.com/blakeblackshear/frigate/issues/3223 mentions how this was done.

**Comment by jcastro** [comment]
Thanks!
