### ISSUE TITLE
[Support]: Uploading images to Frigate+ no longer works

### ISSUE THREAD

**Issue by ehn** [blakeblackshear/frigate#3749]
### Describe the problem you are having

I can no longer upload images from the Frigate UI to Frigate+. When clicking the _SEND TO FRIGATE+_ button, it changes to _UPLOADING..._ and stays that way, seemingly forever. The image is never uploaded.

### Version

0.11.0-C461C9E

### Frigate config file

```yaml
mqtt:
  host: redacted
  user: mosquitto
  password: redacted

detectors:
  coral0:
    type: edgetpu
    device: "pci:0"
  coral1:
    type: edgetpu
    device: "pci:1"
  coral2:
    type: edgetpu
    device: "pci:2"
  coral3:
    type: edgetpu
    device: "pci:3"
  coral4:
    type: edgetpu
    device: "pci:4"
  coral5:
    type: edgetpu
    device: "pci:5"
  coral6:
    type: edgetpu
    device: "pci:6"
  coral7:
    type: edgetpu
    device: "pci:7"

birdseye:
  mode: continuous

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bus
    - boat
    - bird
    - cat
    - dog
    - frisbee
    - sports ball
    - kite
    - skateboard
    - bottle
    - cell phone

cameras:
  redacted:
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@redacted:554/profile2/media.smp
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 2592
      height: 1944
      fps: 25
  further 12 cameras with similar config redacted
record:
  enabled: True
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 365

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True

timestamp_style:
  format: "%Y-%m-%d %H:%M:%S"

ffmpeg:
  hwaccel_args: -c:v h264_cuvid
```

### Relevant log output

```shell
[2022-09-01 04:27:32] frigate.http                   ERROR   : [Errno Expecting value] Exceeded image limit.: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 179, in send_to_plus
    plus_id = current_app.plus_api.upload_image(image, event.camera)
  File "/opt/frigate/frigate/plus.py", line 87, in upload_image
    presigned_urls = r.json()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] Exceeded image limit.: 0
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Network connection

Wired

### Camera make and model

Various Hanwha models

**Comment by NickM-27** [comment]
The error is in the log. `Exceeded image limit.`

You'll need to email blake@frigate.video for support in getting that increased. Frigate proper is still working with the API as intended.

**Comment by ehn** [comment]
Ah, thanks for explaining! I have uploaded 101 images, so I suppose that's the limit. If that is indeed the limit, perhaps it would be good to add it to the documentation?
