### ISSUE TITLE
[Support]: Ubunti on NUC - USB Coral not working

### ISSUE THREAD

**Issue by Jonnehs** [blakeblackshear/frigate#3758]
### Describe the problem you are having

Hi, and thanks to Nickm_27 for encouraging me to log a ticket - I am struggling. I'm a windows admin by trade so my linux skills are limited to what I find on google.

So, I'm running an Intel NUC with USB coral. It shows up under LSUSB as `Bus 004 Device 002: ID 1a6e:089a Global Unichip Corp.
`
I'm not sure how to get it to load its driver, in any case this is preventing it being passed to portainer/docker compose

configs for each below

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.25.1.15
  user: MQTTUser
  password: <mqqttpass>

cameras:
  Front:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:<pass>@10.25.101.102:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:<pass>@10.25.101.102:554//h264Preview_01_main
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
  Garage:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:<pass>@10.25.101.103:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:<pass>@10.25.101.103:554//h264Preview_01_main
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
  Driveway:
    rtmp:
      enabled: false
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - qsv
        - -qsv_device
        - /dev/dri/renderD128
      inputs:
        - path: rtsp://admin:<pass>@10.25.101.101:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://admin:<pass>@10.25.101.101:554//h264Preview_01_main
          roles:
            - rtmp
            - record
    detect:
      width: 640
      height: 480
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
[2022-09-02 19:02:59] frigate.video                  ERROR   : Garage: Unable to read frames from ffmpeg process.,
[2022-09-02 19:02:59] frigate.video                  ERROR   : Garage: ffmpeg process is not running. exiting capture thread...,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2022-09-02 19:03:03] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af),
Starting migrations,
[2022-09-02 19:03:03] peewee_migrate                 INFO    : Starting migrations,
There is nothing to migrate,
[2022-09-02 19:03:03] peewee_migrate                 INFO    : There is nothing to migrate,
[2022-09-02 19:03:03] detector.coral                 INFO    : Starting detection process: 225,
[2022-09-02 19:03:03] frigate.app                    INFO    : Output process started: 226,
[2022-09-02 19:03:03] ws4py                          INFO    : Using epoll,
[2022-09-02 19:03:03] frigate.app                    INFO    : Camera processor started for Front: 232,
[2022-09-02 19:03:03] frigate.app                    INFO    : Camera processor started for Garage: 235,
[2022-09-02 19:03:03] frigate.app                    INFO    : Camera processor started for Driveway: 238,
[2022-09-02 19:03:03] frigate.app                    INFO    : Capture process started for Front: 239,
[2022-09-02 19:03:03] frigate.app                    INFO    : Capture process started for Garage: 241,
[2022-09-02 19:03:03] frigate.app                    INFO    : Capture process started for Driveway: 246,
[2022-09-02 19:03:03] frigate.video                  ERROR   : Driveway: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:03] frigate.video                  ERROR   : Driveway: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:03] ws4py                          INFO    : Using epoll,
[2022-09-02 19:03:03] frigate.video                  ERROR   : Front: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:03] frigate.video                  ERROR   : Front: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:06] frigate.video                  ERROR   : Garage: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:06] frigate.video                  ERROR   : Garage: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:23] watchdog.Driveway              ERROR   : Ffmpeg process crashed unexpectedly for Driveway.,
[2022-09-02 19:03:23] watchdog.Driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2022-09-02 19:03:23] ffmpeg.Driveway.detect         ERROR   : [tcp @ 0x564a30884180] Connection to tcp://10.25.101.101:554?timeout=5000000 failed: Network is unreachable,
[2022-09-02 19:03:23] ffmpeg.Driveway.detect         ERROR   : rtsp://admin:CamerazP4ssw0rd!@10.25.101.101:554/h264Preview_01_sub: Network is unreachable,
[2022-09-02 19:03:23] watchdog.Front                 ERROR   : Ffmpeg process crashed unexpectedly for Front.,
[2022-09-02 19:03:23] watchdog.Front                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2022-09-02 19:03:23] ffmpeg.Front.detect            ERROR   : [tcp @ 0x55ac57d98180] Connection to tcp://10.25.101.102:554?timeout=5000000 failed: Network is unreachable,
[2022-09-02 19:03:23] ffmpeg.Front.detect            ERROR   : rtsp://admin:CamerazP4ssw0rd!@10.25.101.102:554/h264Preview_01_sub: Network is unreachable,
[2022-09-02 19:03:23] frigate.video                  ERROR   : Driveway: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:23] frigate.video                  ERROR   : Driveway: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:23] frigate.video                  ERROR   : Front: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:23] frigate.video                  ERROR   : Front: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:23] watchdog.Garage                ERROR   : Ffmpeg process crashed unexpectedly for Garage.,
[2022-09-02 19:03:23] watchdog.Garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2022-09-02 19:03:23] ffmpeg.Garage.detect           ERROR   : [tcp @ 0x563265ac1180] Connection to tcp://10.25.101.103:554?timeout=5000000 failed: Network is unreachable,
[2022-09-02 19:03:23] ffmpeg.Garage.detect           ERROR   : rtsp://admin:CamerazP4ssw0rd!@10.25.101.103:554/h264Preview_01_sub: Network is unreachable,
[2022-09-02 19:03:26] frigate.video                  ERROR   : Garage: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:26] frigate.video                  ERROR   : Garage: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:03] frigate.edgetpu                INFO    : Attempting to load TPU as usb,
Process detector:coral:,
[2022-09-02 19:03:29] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.,
Traceback (most recent call last):,
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate,
    delegate = Delegate(library, options),
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__,
    raise ValueError(capture.message),
ValueError,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap,
    self.run(),
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run,
    self._target(*self._args, **self._kwargs),
  File "/opt/frigate/frigate/edgetpu.py", line 136, in run_detector,
    object_detector = LocalObjectDetector(,
  File "/opt/frigate/frigate/edgetpu.py", line 44, in __init__,
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config),
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate,
    raise ValueError('Failed to load delegate from {}\n{}'.format(,
ValueError: Failed to load delegate from libedgetpu.so.1.0,
,
[2022-09-02 19:03:33] watchdog.Driveway              ERROR   : Ffmpeg process crashed unexpectedly for Driveway.,
[2022-09-02 19:03:33] watchdog.Driveway              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2022-09-02 19:03:33] ffmpeg.Driveway.detect         ERROR   : [tcp @ 0x56453109a180] Connection to tcp://10.25.101.101:554?timeout=5000000 failed: Network is unreachable,
[2022-09-02 19:03:33] ffmpeg.Driveway.detect         ERROR   : rtsp://admin:CamerazP4ssw0rd!@10.25.101.101:554/h264Preview_01_sub: Network is unreachable,
[2022-09-02 19:03:33] watchdog.Front                 ERROR   : Ffmpeg process crashed unexpectedly for Front.,
[2022-09-02 19:03:33] watchdog.Front                 ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2022-09-02 19:03:33] ffmpeg.Front.detect            ERROR   : [tcp @ 0x55fb55207180] Connection to tcp://10.25.101.102:554?timeout=5000000 failed: Network is unreachable,
[2022-09-02 19:03:33] ffmpeg.Front.detect            ERROR   : rtsp://admin:<pass>@10.25.101.102:554/h264Preview_01_sub: Network is unreachable,
[2022-09-02 19:03:33] frigate.video                  ERROR   : Driveway: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:33] frigate.video                  ERROR   : Driveway: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:33] frigate.video                  ERROR   : Front: Unable to read frames from ffmpeg process.,
[2022-09-02 19:03:33] frigate.video                  ERROR   : Front: ffmpeg process is not running. exiting capture thread...,
[2022-09-02 19:03:33] watchdog.Garage                ERROR   : Ffmpeg process crashed unexpectedly for Garage.,
[2022-09-02 19:03:33] watchdog.Garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.,
[2022-09-02 19:03:33] ffmpeg.Garage.detect           ERROR   : [tcp @ 0x56316e0c8180] Connection to tcp://10.25.101.103:554?timeout=5000000 failed: Network is unreachable,
[2022-09-02 19:03:33] ffmpeg.Garage.detect           ERROR   : rtsp://admin:<pass>@10.25.101.103:554/h264Preview_01_sub: Network is unreachable,
[2022-09-02 19:03:33] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
```

### FFprobe output from your camera

```shell
cant seem to run this from ssh
```

### Frigate stats

```json
{"Driveway":{"camera_fps":0.0,"capture_pid":245,"detection_fps":0.0,"pid":237,"process_fps":0.0,"skipped_fps":0.0},"Front":{"camera_fps":0.0,"capture_pid":239,"detection_fps":0.0,"pid":232,"process_fps":0.0,"skipped_fps":0.0},"Garage":{"camera_fps":0.0,"capture_pid":241,"detection_fps":0.0,"pid":236,"process_fps":0.0,"skipped_fps":0.0},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":225}},"service":{"storage":{"/dev/shm":{"free":1073.2,"mount_type":"tmpfs","total":1073.7,"used":0.5},"/media/frigate/clips":{"free":84823.0,"mount_type":"overlay","total":105089.3,"used":14880.8},"/media/frigate/recordings":{"free":84823.0,"mount_type":"overlay","total":105089.3,"used":14880.8},"/tmp/cache":{"free":84823.0,"mount_type":"overlay","total":105089.3,"used":14880.8}},"temperatures":{},"uptime":3,"version":"0.10.1-83481af"}}
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink 520A

**Comment by NickM-27** [comment]
What does your docker compose file look like?

There are a number of reasons why it wouldn't be initializing:
1. In many cases I have seen that the USB coral needs to be interfaced with before it tries to load its internal driver. This means that on first try frigate fails to start but on second try it succeeds
2. The coral uses a decent amount of power, you need to make sure that its USB port and cable are USB 3. I personally found that the included cable was not up to par and a USB C to USB C cable worked much better.

**Comment by Jonnehs** [comment]
frigate:
    container_name: frigate
    image: blakeblackshear/frigate:stable-amd64
    restart: unless-stopped
    shm_size: "1g"
    devices:
      - /dev/bus/usb/:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/jonneh/frigate/config.yml:/config/config.yml:ro
      - /media/CCTV:/media/CCTV
      - /home/jonneh/frigate/:/db
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "<password>"

**Comment by Jonnehs** [comment]
I've restarted a few times so its been loaded a couple of times. I am using the included cable, will try a usb-c/usb-c

**Comment by NickM-27** [comment]
A few things, for one I would change the USB device mapping to just be 

```yaml
    devices:
      - /dev/bus/usb:/dev/bus/usb
```

The other thing is, have you done anything to pass the USB from the host to portainer?

**Comment by Jonnehs** [comment]
`Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp.
`
Still global chip corp on usb c port

What should I be doing to pass usb to portainer?

**Comment by NickM-27** [comment]
Just curious, is there a reason you are running in portainer vs just using docker compose natively on the host?

> What should I be doing to pass usb to portainer?

How do you start portainer?

**Comment by Jonnehs** [comment]
I'm a windows admin and I like GUIs

I'm not sure I recall to be honest. It starts on boot now, I followed a guide I found which I'm struggling to find again

**Comment by NickM-27** [comment]
Fair enough, odds are portainer is not being given access to the USB devices. If you find that guide I can probably direct you, based on their docs seems it might be a docker run command that runs on boot in which case there would need to be `-d /dev/bus/usb` added to it

**Comment by Jonnehs** [comment]
honestly I think it was a youtube where they already had portainer and I just got portainer working off my own back

https://docs.fuga.cloud/how-to-install-portainer-docker-ui-manager-on-ubuntu-20.04-18.04-16.04

**Comment by NickM-27** [comment]
Unfortunately, I don't see anything in there about getting it to run at boot. You don't remember how that part was done?

Do you have anything relevant if you run `crontab -e` ?
Is there anything in `/etc/rc.local` ?

If none of those work out then you may just need to run a `grep` so it can find what file has it

**Comment by Jonnehs** [comment]
`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer **--restart=always** -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer`

**Comment by Jonnehs** [comment]
nothing in crontab or /etc/rc.local - think its the always restart in the docker command to run it I guess?

**Comment by NickM-27** [comment]
Cool looks like you found it, you'll need to add `--device='/dev/bus/usb' to that command and then restart the OS. Should hopefully work then

**Comment by NickM-27** [comment]
The always restart is when portainer stops, not when the OS stops.

**Comment by Jonnehs** [comment]
ah ok, well I can't run that command again because it says the container/name is in use 

`docker: Error response from daemon: Conflict. The container name "/portainer" is already in use by container "30d0743143032cff9f8f39f0564aee879d3da6a0d78643996d5ddc28ad121367". You have to remove (or rename) that container to be able to reuse that name.
`

**Comment by NickM-27** [comment]
Oh I thought you pasted it because you found where it was to be run on start

**Comment by Jonnehs** [comment]
no its from the guide, thats what I did to run it so I presumed that was what did it ^^

**Comment by NickM-27** [comment]
If you run `grep -rnw '/' -e 'portainer/portainer'` from the commandline I think it should tell you what file it is in

**Comment by NickM-27** [comment]
> no its from the guide, thats what I did to run it so I presumed that was what did it ^^

To be 100% clear, it doesn't work like that, there is going to be somewhere where docker is set to run that command on startup

**Comment by Jonnehs** [comment]
ok, I got it almost there, says the device flag is invalid to start it with though

**Comment by Jonnehs** [comment]
`portainer: error: unknown long flag '--device', try --help
`

**Comment by NickM-27** [comment]
Can you paste the full command you are trying to run?

**Comment by Jonnehs** [comment]
`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer -d /dev/bus/usb`

Think its working now, was trying `--device /dev/bus/usb` and it didnt like that

**Comment by NickM-27** [comment]
Okay, usually the image name has to be the last thing, so you might want to rearrange that just in case

`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data -d /dev/bus/usb portainer/portainer`

**Comment by NickM-27** [comment]
Either way, this should have solved it for frigate or at least gotten us closer as there is no chance portainer had access to USB devices before

**Comment by Jonnehs** [comment]
`jonneh@cctv01:~$ docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data -d /dev/bus/usb portainer/portainer
docker: invalid reference format.k:/var/run/docker.sock -v portainer_data:/data      `

Still not liking the syntax on that run command

**Comment by NickM-27** [comment]
according to the docs I think it has to be --device so try 
`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data --device=/dev/bus/usb portainer/portainer`

**Comment by Jonnehs** [comment]
Ok, `docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always --device /dev/bus/usb -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer` worked

Its showing as "google" in `lsusb` now

**Comment by NickM-27** [comment]
Great! If it is showing as Google then frigate should pick it up as expected

**Comment by Jonnehs** [comment]
Thanks a lot for your help. Now I have to read all the strange specific instructions for Reolink cameras ^^

**Comment by NickM-27** [comment]
> Thanks a lot for your help. Now I have to read all the strange specific instructions for Reolink cameras ^^

It's not that bad, just be sure to use the http:// endpoint as explained in the docs: https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others
