### ISSUE TITLE
[Support]:  FFMPEG not found in RC2   RC1 working no problems

### ISSUE THREAD

**Issue by scooper1** [blakeblackshear/frigate#3769]
### Describe the problem you are having

error at startup 
running in docker container 
have removed hw accel  settings in config file

working ok in   11 rc1 following errors in rc2
ffmpeg installed on host system
host is a I5 pc

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

### Version

11.0   rc2

### Frigate config file

```yaml
prefer not to post as has passwords
```

### Relevant log output

```shell
Traceback (most recent call last):


  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner


    self.run()


  File "/opt/frigate/frigate/video.py", line 215, in run


    self.start_ffmpeg_detect()


  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect


    self.ffmpeg_detect_process = start_or_restart_ffmpeg(


  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg


    process = sp.Popen(


  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__


    self._execute_child(args, executable, preexec_fn, close_fds,


  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child


    raise child_exception_type(errno_num, err_msg, err_filename)


FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

### FFprobe output from your camera

```shell
all cameras affected
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

hikvision

**Comment by scooper1** [comment]
do i need to add new items to path
PATH  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jellyfin-ffmpeg

**Comment by NickM-27** [comment]
The release notes cover this change, you need to clear the existing path as currently the containers path is being overwritten.

**Comment by scooper1** [comment]
Thanks   
that works for me
