### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by Lockdown1501** [blakeblackshear/frigate#3794]
### Describe the problem you are having

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-08 10:09:38] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1022, in pydantic.main.validate_model
  File "pydantic/fields.py", line 856, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 991, in pydantic.fields.ModelField._validate_mapping_like
  File "pydantic/fields.py", line 1064, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 854, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1071, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1118, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic/main.py", line 676, in pydantic.main.BaseModel.validate
  File "/opt/frigate/frigate/config.py", line 548, in __init__
    if len(config["ffmpeg"]["inputs"]) == 1:
KeyError: 'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

### Version

????

### Frigate config file

```yaml
mqtt:
  host: 192.168.178.138
  user: mqtt
  password: mqtt1501

cameras:
  Schlafzimmer:
    ffmpeg:
      inputs:
        - path: rtsp://viewer:192.168.178.25:8080/h264_pcm.sdp
          roles: 
            - detect
            - clips
    Detect:
      width: 1280
      height: 720
    fps: 5
  objects:
    track:
      - dog
      - person
  snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
detectors: 
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-08 10:09:38] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
'ffmpeg'
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1022, in pydantic.main.validate_model
  File "pydantic/fields.py", line 856, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 991, in pydantic.fields.ModelField._validate_mapping_like
  File "pydantic/fields.py", line 1064, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 854, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1071, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1118, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic/main.py", line 676, in pydantic.main.BaseModel.validate
  File "/opt/frigate/frigate/config.py", line 548, in __init__
    if len(config["ffmpeg"]["inputs"]) == 1:
KeyError: 'ffmpeg'
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
- path: rtsp://viewer:192.168.178.25:8080/h264_pcm.sdp
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

ip webcam

**Comment by NickM-27** [comment]
https://docs.frigate.video/guides/getting_started#step-3-add-a-minimal-camera-configuration

YAML is a space dependent language based on increments of indentions by 2 spaces, without proper spacing it can not read the file. Your file is inconsistently formatted, also it should be `detect` not `Detect`. 

Also notice how `width` and `fps` are both properties of detect and yet they are not aligned. 

Please go back into the docs and see how it is formatted and reformat your config file.

**Comment by Lockdown1501** [comment]
the fu..... "D"

thanks
