### ISSUE TITLE
[Camera Support]: 

### ISSUE THREAD

**Issue by larrym** [blakeblackshear/frigate#3805]
### Describe the problem you are having

Reolink RLC-811A green screen

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 192.168.10.21
  user: homeassistant
  password: pwd

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:

  reolink: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtmp://admin:pwd2@192.168.10.204:554/h265Preview_01_Main
          roles:
            - detect
    rtmp:
      enabled: false # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
      fps: 10
logger:
  default: info
  logs:
    frigate.event: debug
```

### Relevant log output

```shell
[2022-09-07 19:02:15] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
Starting migrations
[2022-09-07 19:02:15] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-07 19:02:15] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-07 19:02:15] detector.coral                 INFO    : Starting detection process: 217
[2022-09-07 19:02:15] frigate.app                    INFO    : Output process started: 219
[2022-09-07 19:02:15] ws4py                          INFO    : Using epoll
[2022-09-07 19:02:15] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
[2022-09-07 19:02:15] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
[2022-09-07 19:02:15] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-07 19:02:17] frigate.edgetpu                INFO    : TPU found
[2022-09-07 19:02:15] frigate.app                    INFO    : Camera processor started for reolink: 223
[2022-09-07 19:02:15] frigate.app                    INFO    : Capture process started for reolink: 229
[2022-09-07 19:02:15] ws4py                          INFO    : Using epoll
[2022-09-07 19:02:35] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
[2022-09-07 19:02:35] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-07 19:02:35] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x55d9a37df780] method DESCRIBE failed: 404 Stream Not Found
[2022-09-07 19:02:35] ffmpeg.reolink.detect          ERROR   : rtsp://admin:pwd2@192.168.10.204:554/h265Preview_01_Main: Server returned 404 Not Found
[2022-09-07 19:02:35] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
[2022-09-07 19:02:35] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
[2022-09-07 19:02:45] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
[2022-09-07 19:02:45] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-07 19:02:45] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x5588e7173780] method DESCRIBE failed: 404 Stream Not Found
[2022-09-07 19:02:45] ffmpeg.reolink.detect          ERROR   : rtsp://admin:pwd2@192.168.10.204:554/h265Preview_01_Main: Server returned 404 Not Found
[2022-09-07 19:02:45] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
[2022-09-07 19:02:45] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
[2022-09-07 19:02:55] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
[2022-09-07 19:02:55] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-07 19:02:55] ffmpeg.reolink.detect          ERROR   : [rtsp @ 0x556232d71780] method DESCRIBE failed: 404 Stream Not Found
[2022-09-07 19:02:55] ffmpeg.reolink.detect          ERROR   : rtsp://admin:pwd2@192.168.10.204:554/h265Preview_01_Main: Server returned 404 Not Found
[2022-09-07 19:02:55] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
[2022-09-07 19:02:55] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
$ ffprobe rtsp://admin:qiqltoq@192.168.10.204:554
ffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, rtsp, from 'rtsp://admin:qiqltoq@192.168.10.204:554':
  Metadata:
    title           : Session streamed by "preview"
    comment         : 
  Duration: N/A, start: 0.000250, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 3840x2160, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
?
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink RLC-811A

### Any other information that may be helpful

I tried different resolutions, but output was still green screen

**Comment by NickM-27** [comment]
Please read the docs, reolink cams have specific args / stream: https://docs.frigate.video/configuration/camera_specific#reolink-410520-possibly-others

**Comment by larrym** [comment]
When I copy the config from that link, changing only the ip, user and pwd, I get the following error. So yml doens't like the empty object hwaccel_args.

```[2022-09-09 10:19:28] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> reolink -> ffmpeg -> hwaccel_args
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 312, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 77, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 904, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> reolink -> ffmpeg -> hwaccel_args
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by NickM-27** [comment]
The hwaccel args there is just a placeholder to remind you to add them. Just remove that if you have global hwaccel or haven't set it up yet.

**Comment by larrym** [comment]
Thank you Nick!!! I have not set and acceleration properties, so I commented that line and it works.

**Comment by NickM-27** [comment]
Great! In that case I'll go ahead and close this. Feel free to create a new issue if something else comes up.
