### ISSUE TITLE
[Support]: KeyError: 'ffmpeg'

### ISSUE THREAD

**Issue by johnross2007** [blakeblackshear/frigate#3812]
### Describe the problem you are having

When running docker compose up, I get the following error:

```
 *************************************************************
frigate  | *************************************************************
frigate  | ***    Your config file is not valid!                     ***
frigate  | ***    Please check the docs at                           ***
frigate  | ***    https://docs.frigate.video/configuration/index     ***
frigate  | *************************************************************
frigate  | *************************************************************
frigate  | ***    Config Validation Errors                           ***
frigate  | *************************************************************
frigate  | 'ffmpeg'
frigate  | Traceback (most recent call last):
frigate  |   File "/opt/frigate/frigate/app.py", line 312, in start
frigate  |     self.init_config()
frigate  |   File "/opt/frigate/frigate/app.py", line 77, in init_config
frigate  |     user_config = FrigateConfig.parse_file(config_file)
frigate  |   File "/opt/frigate/frigate/config.py", line 904, in parse_file
frigate  |     return cls.parse_obj(config)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 511, in parse_obj
frigate  |     return cls(**obj)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 329, in __init__
frigate  |     values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 1022, in validate_model
frigate  |     v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 856, in validate
frigate  |     v, errors = self._validate_mapping_like(v, values, loc, cls)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 991, in _validate_mapping_like
frigate  |     value_result, value_errors = self._validate_singleton(v_, values, v_loc, cls)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1064, in _validate_singleton
frigate  |     value, error = field.validate(v, values, loc=loc, cls=cls)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 854, in validate
frigate  |     v, errors = self._validate_singleton(v, values, loc, cls)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1071, in _validate_singleton
frigate  |     return self._apply_validators(v, values, loc, cls, self.validators)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/fields.py", line 1118, in _apply_validators
frigate  |     v = validator(cls, v, values, self, self.model_config)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/class_validators.py", line 313, in <lambda>
frigate  |     return lambda cls, v, values, field, config: validator(v)
frigate  |   File "/usr/local/lib/python3.8/dist-packages/pydantic/main.py", line 676, in validate
frigate  |     return cls(**value)
frigate  |   File "/opt/frigate/frigate/config.py", line 548, in __init__
frigate  |     if len(config["ffmpeg"]["inputs"]) == 1:
frigate  | KeyError: 'ffmpeg'
frigate  | 
frigate  | *************************************************************
frigate  | ***    End Config Validation Errors                       ***
frigate  | *************************************************************
```

Issues I think are related, but haven't worked for me yet:
https://github.com/blakeblackshear/frigate/issues/2680
https://github.com/blakeblackshear/frigate/issues/3599

### Version

web ui not accessible. Most recent docker version (9/10/22) arm64.

### Frigate config file

```yaml
---
cameras:
  detect:
    height: 480
    width: 704
  driveway:
    ffmpeg:
      inputs:
        - path: "rtsp://redacted:redacted@172.16.0.30:554/cam/realmonitor?channel=1&subtype=1"
          roles:
            - detect
detectors:
  coral:
    device: usb
    type: edgetpu
mqtt:
  host: homeassistant.local
  password: redacted
  user: redacted
```

### Relevant log output

```shell
N/A I think?
```

### FFprobe output from your camera

```shell
I can't figure out how to make this work
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP8M-t2499EQ-28MM

### Any other information that may be helpful

Raspberry Pi 400
RaspianOS (most recent version)
Home Assistant on a separate device, running MQTT as an add-on

**Comment by NickM-27** [comment]
Please go through the docs: https://docs.frigate.video/guides/getting_started

yaml is a space / indentation dependent language and your config is not following what the docs have outlined.

**Comment by johnross2007** [comment]
I've tried to. I ran it through an online yaml validator and it worked. It also moved some things around, like putting mqtt at the bottom. Is that ok?

**Comment by NickM-27** [comment]
The yaml validator will only validate that it can be interpreted, not that it's a valid frigate config. 

If you compare it to the docs I sent you'll see, for example, detect is indented more than yours is and it's also below the camera name (since it's a property of the camera). 

Where your MQTT is fine

**Comment by johnross2007** [comment]
It worked! HA's MQTT server isn't working now, so I'll troubleshoot that. Thank you so much Nick!
