### ISSUE TITLE
[Config Support]: CPU Running at 100% with Coral TPU

### ISSUE THREAD

**Issue by christopherdenny** [blakeblackshear/frigate#3836]
### Describe the problem you are having

I had my 8 camera setup running OK under CPU detection, and I recently added the Coral TPU. Everything seemed to be running OK with the CPU running around 35-40% or lower most of the time, but lately it has been pegged near 100% nearly all the time. 

### Version

0.11.0-c461c9e

### Frigate config file

```yaml
mqtt:
  host: 192.168.5.72
  user: user
  password: password

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  coral:
    type: edgetpu
    device: usb

database:
  # The path to store the SQLite DB (default: shown below)
  path: /frigate/db/frigate.db
    
logger:
  default: info
#  logs: frigate.event: debug

# Optional: birdseye configuration
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  width: 1280
  height: 720
  quality: 8
  mode: objects

# Optional: ffmpeg configuration
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: 
    -hwaccel qsv
    -hwaccel_device /dev/dri/renderD128
    -hwaccel_output_format yuv420p
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -an
  # Optional: global output args
  output_args:
#    detect: -f rawvideo -pix_fmt yuv420p -filter:v fps=fps=5
#    record: -vf transpose=1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 
    rtmp: 
      -c copy 
      -f flv
      -c:a aac

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  # Optional: width of the frame for the input with the detect role (default: shown below)
  width: 1280
  # Optional: height of the frame for the input with the detect role (default: shown below)
  height: 720
  # Optional: desired fps for your camera for the input with the detect role (default: shown below)
  # NOTE: Recommended value of 5. Ideally, try and reduce your FPS on the camera.
  fps: 5
  # Optional: enables detection for the camera (default: True)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: Number of frames without a detection before frigate considers an object to be gone. (default: 5x the frame rate)
  max_disappeared: 25
  # Optional: Configuration for stationary object tracking
  stationary:
    # Optional: Frequency for running detection on stationary objects (default: shown below)
    # When set to 0, object detection will never be run on stationary objects. If set to 10, it will be run on every 10th frame.
    interval: 10
    # Optional: Number of frames without a position change for an object to be considered stationary (default: 10x the frame rate or 10s)
    threshold: 50
 
# Optional: Object configuration
# NOTE: Can be overridden at the camera level
objects:
  track:
    - person
    - dog
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 500
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.70
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.75
    
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: motion mask
  # NOTE: see docs for more detailed info on creating masks
  # mask: 0,900,1080,900,1080,1920,0,1920
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: False

# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: True
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 7
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 30
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - dog
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 30
      mode: motion
      # Optional: Per object retention days
      objects:
        person: 30
        dog: 30

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  retain:
    default: 30

# Optional: RTMP configuration
# NOTE: Can be overridden at the camera level
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: True

live:
  height: 720
  quality: 8

cameras:
  driveway: 
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format  
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.5.25:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.25:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    objects:
      track:
        - person
        - dog
        - car
    motion:
      mask:
        - 168,325,179,216,297,149,488,83,649,42,862,28,1015,25,1280,37,1280,0,0,0,0,532
  frontyard: 
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format  
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.5.20:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.20:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 1280,0,1280,720,1207,434,1095,319,974,218,889,161,691,118,594,184,430,211,335,185,242,124,212,54,180,35,0,84,0,0
    objects:
      track:
        - person
        - dog
        - car  
  sideyard: 
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format  
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.5.21:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.21:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 106,191,187,145,293,113,418,103,697,95,761,134,820,93,899,103,1280,174,1280,0,0,0,0,299
  backyard: 
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format  
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.5.23:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.23:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:    
        - 354,488,329,231,362,120,674,56,1003,45,1101,57,1145,69,1177,165,1280,257,1280,0,0,0,0,720,334,720
  patio: 
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format  
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.5.22:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.22:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:    
        - 255,375,317,181,320,0,0,0,0,371
  garage: 
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format  
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.5.24:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.24:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  basement: 
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.5.26:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.26:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
  dogsroom: 
    ffmpeg:
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format  
        - yuv420p
      inputs:
        - path: rtsp://admin:password@192.168.5.27:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
        - path: rtsp://admin:password@192.168.5.27:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    motion:
      mask:
        - 77,530,195,673,386,573,937,232,933,102,806,24,47,269
#  frontdoor:
#    ffmpeg:
#      inputs:
#        - path: rtsp://a042fcfd2769-ring-mqtt:8554/3ce1a1f99bde_live
#          roles:
#            - detect
#            - rtmp
#            - record
#  forrest: 
#    ffmpeg:
#      input_args:
#        - -fflags
#        - nobuffer+genpts+discardcorrupt
#      inputs:
#        - path: rtsp://forrest:password@192.168.5.14/live
#          roles:
#            - detect
#            - rtmp
#        - path: rtsp://forrest:password@192.168.5.14/live
#          roles:
#            - record
#    objects:
#      track:
#        - dog
#    motion:
#      mask:    
#        - 1280,0,862,0,984,720,1280,720
#        - 398,0,0,0,0,720,314,720
#    detect:
#      width: 640
#      height: 480
#      fps: 8
```

### Relevant log output

```shell
Process detector:coral:
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for driveway: 228
[2022-09-13 23:53:49] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for frontyard: 232
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for sideyard: 235
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for backyard: 236
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for patio: 239
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for garage: 241
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for basement: 242
[2022-09-13 23:53:18] frigate.app                    INFO    : Camera processor started for dogsroom: 244
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for driveway: 246
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for frontyard: 247
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for sideyard: 251
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for backyard: 256
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for patio: 262
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for garage: 268
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for basement: 273
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
[2022-09-13 23:53:18] frigate.app                    INFO    : Capture process started for dogsroom: 278
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0

[2022-09-13 23:53:18] ws4py                          INFO    : Using epoll
[2022-09-13 23:53:38] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48848]
[2022-09-13 23:53:58] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-09-13 23:53:58] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:48848]
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[2022-09-13 23:53:58] frigate.video                  ERROR   : backyard: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : backyard: ffmpeg process is not running. exiting capture thread...
[2022-09-13 23:53:58] frigate.video                  ERROR   : driveway: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : driveway: ffmpeg process is not running. exiting capture thread...
[2022-09-13 23:53:58] frigate.video                  ERROR   : dogsroom: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : dogsroom: ffmpeg process is not running. exiting capture thread...
[2022-09-13 23:53:58] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
[2022-09-13 23:53:58] frigate.video                  ERROR   : basement: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : basement: ffmpeg process is not running. exiting capture thread...
[2022-09-13 23:53:58] frigate.video                  ERROR   : frontyard: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : frontyard: ffmpeg process is not running. exiting capture thread...
[2022-09-13 23:53:58] frigate.video                  ERROR   : sideyard: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : sideyard: ffmpeg process is not running. exiting capture thread...
[2022-09-13 23:53:58] frigate.video                  ERROR   : patio: Unable to read frames from ffmpeg process.
[2022-09-13 23:53:58] frigate.video                  ERROR   : patio: ffmpeg process is not running. exiting capture thread...
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-13 23:54:05] frigate.app                    INFO    : Starting Frigate (0.11.0-c461c9e)
Starting migrations
[2022-09-13 23:54:05] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-13 23:54:05] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-13 23:54:05] detector.coral                 INFO    : Starting detection process: 224
[2022-09-13 23:54:05] frigate.app                    INFO    : Output process started: 226
[2022-09-13 23:54:05] ws4py                          INFO    : Using epoll
[2022-09-13 23:54:05] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-13 23:54:08] frigate.edgetpu                INFO    : TPU found
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for driveway: 231
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for frontyard: 234
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for sideyard: 236
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for backyard: 238
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for patio: 240
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for garage: 241
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for basement: 243
[2022-09-13 23:54:05] frigate.app                    INFO    : Camera processor started for dogsroom: 245
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for driveway: 246
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for frontyard: 250
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for sideyard: 255
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for backyard: 262
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for patio: 274
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for garage: 286
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for basement: 292
[2022-09-13 23:54:05] frigate.app                    INFO    : Capture process started for dogsroom: 296
[2022-09-13 23:54:06] ws4py                          INFO    : Using epoll
```

### Frigate stats

```json
{"backyard":{"camera_fps":6.6,"capture_pid":262,"detection_fps":0.0,"pid":238,"process_fps":5.7,"skipped_fps":0.0},"basement":{"camera_fps":6.4,"capture_pid":292,"detection_fps":0.0,"pid":243,"process_fps":5.4,"skipped_fps":0.0},"detection_fps":0.6,"detectors":{"coral":{"detection_start":0.0,"inference_speed":161.03,"pid":224}},"dogsroom":{"camera_fps":4.8,"capture_pid":296,"detection_fps":0.0,"pid":245,"process_fps":4.0,"skipped_fps":0.0},"driveway":{"camera_fps":6.3,"capture_pid":246,"detection_fps":0.6,"pid":231,"process_fps":5.5,"skipped_fps":0.0},"frontyard":{"camera_fps":4.3,"capture_pid":250,"detection_fps":0.0,"pid":234,"process_fps":3.5,"skipped_fps":0.0},"garage":{"camera_fps":9.0,"capture_pid":286,"detection_fps":0.0,"pid":241,"process_fps":7.3,"skipped_fps":0.0},"patio":{"camera_fps":7.2,"capture_pid":274,"detection_fps":0.0,"pid":240,"process_fps":6.3,"skipped_fps":0.0},"service":{"latest_version":"0.10.1","storage":{"/dev/shm":{"free":331.8,"mount_type":"tmpfs","total":377.5,"used":45.7},"/media/frigate/clips":{"free":13865900.9,"mount_type":"nfs","total":23030224.0,"used":9164323.1},"/media/frigate/recordings":{"free":13865900.9,"mount_type":"nfs","total":23030224.0,"used":9164323.1},"/tmp/cache":{"free":1034.5,"mount_type":"tmpfs","total":2000.0,"used":965.5}},"temperatures":{},"uptime":557,"version":"0.11.0-c461c9e"},"sideyard":{"camera_fps":5.7,"capture_pid":255,"detection_fps":0.0,"pid":236,"process_fps":4.9,"skipped_fps":0.0}}
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

I just noticed in the logs there is something wring with the Coral installation, but I do not know how to fix it.

**Comment by NickM-27** [comment]
So at the global level you're using incorrect as hardware acceleration then in the camera level you're using vaapi.

What CPU do you have? Should remove one or the other as that's just confusing.

Can you please also provide an `htop`of what processes are using what CPU?

**Comment by christopherdenny** [comment]
CPU: Intel Core i5-8279U

Here is the HTOP
![image](https://user-images.githubusercontent.com/43104561/190170608-502a30ee-6e37-43aa-87db-4eb0a52a6f38.png)

Don't the cameras still use the CPU to record the video? I thought that's why you still needed hardware acceleration for them.

**Comment by NickM-27** [comment]
You need hardware acceleration to decode the video frames so detection can be run. What I was saying above is you're mixing two different hwaccel APIs which is confusing at best and most likely problematic. 

Have you used `intel_gpu_top` to verify if it's actually working well?

Looks like you're specifying vaapi for hwaccel at the camera level so you should delete the hwaccel arg at the top of the config file.

**Comment by NickM-27** [comment]
Hwaccel is not used for recording

**Comment by NickM-27** [comment]
Looks like the frigate process for your basement is using a LOT of CPU resources. Do you have lots of motion or false positives on that camera? Use the debug view of the camera in frigate to see what's going on (enable motion and bounding boxes)

**Comment by christopherdenny** [comment]
I did not see anything out of the ordinary for the basement. No motion boxes at all. The only thing out of sync on the basement camera is the time, it is four hours out of sync. It's showing 6:15, when it's really 10:15.

Should I remove ALL hardware accelleration from the config file since I am using the TPU?

**Comment by NickM-27** [comment]
> Should I remove ALL hardware accelleration from the config file since I am using the TPU?

No, as I said it is needed and the docs also explain why it is still needed even with the TPU. 

Just remove 

```yaml

ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args: 
    -hwaccel qsv
    -hwaccel_device /dev/dri/renderD128
    -hwaccel_output_format yuv420p
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -an
  # Optional: global output args
  output_args:
#    detect: -f rawvideo -pix_fmt yuv420p -filter:v fps=fps=5
#    record: -vf transpose=1 -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 
    rtmp: 
      -c copy 
      -f flv
      -c:a aac
```

from the top

then use `intel_gpu_top` to verify it is using the GPU

**Comment by NickM-27** [comment]
I also noticed you set a global width / height of the detect streams as 720x1080

Is that the true resolution of ALL the detect streams for your cameras? Otherwise frigate will be spending CPU resources resizing the streams to that size

**Comment by christopherdenny** [comment]
That has been a looming question that I have not been able to find. Do I have the detection at each camera's native resolution to avoid using resources to resize? Your comment seems to say "yes".

**Comment by NickM-27** [comment]
Depends on your needs but the general recommendation is to use a sub stream. Your config is quite inefficient currently since your stream is 640x480 but you have frigate setup to have the detect stream at 1080x720 which means frigate is resizing every stream which of course will use considerable CPU, you should update that. 

This is why we don't recommend copying the reference configuration.

**Comment by christopherdenny** [comment]
Here is the Intel_GPU_Top
![image](https://user-images.githubusercontent.com/43104561/190190647-ffc07848-ef29-46d0-8fc0-b0dcab766808.png)

It is using some of the GPU, but it doesn't seem like much. I will switch everything back to 640x480 detection and change my masks, too, and see what that does.

**Comment by NickM-27** [comment]
yes that is not much for all the cameras you have, you might want to try using the i965 driver instead of the default iHD one and see if that makes a difference.

Also might be worth trying qsv with the new driver and see if the CPU usage goes down.

**Comment by christopherdenny** [comment]
Moving detection back down to 640x480 and removing the global FFMPEG statements has brought the CPU usage down quite a bit. I do have the i965 driver already. I will check the latest qsv driver, as well.

I think the major issue is that I do not have the TPU setup properly in Ubuntu 22.04 because of Python 3.9. I will be tracking that down tonight or tomorrow morning.

**Comment by NickM-27** [comment]
> I think the major issue is that I do not have the TPU setup properly in Ubuntu 22.04 because of Python 3.9. I will be tracking that down tonight or tomorrow morning.

Frigate would not start if the TPU was not working, so that is working fine

**Comment by christopherdenny** [comment]
I thought my hardware acceleration was using qsv. (I thought that was the whole point of acceleration, honestly.)

The reason I didn't think the TPU was configured properly is because of the Python errors in the log:

Exception in thread event_processor:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/events.py", line 67, in run
    Event.replace(
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1898, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 1969, in execute
    return self._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2730, in _execute
    return super(Insert, self)._execute(database)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2466, in _execute
    return self.handle_result(database, cursor)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2739, in handle_result
    return database.last_insert_id(cursor, self._query_type)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3218, in last_insert_id
    return cursor.lastrowid
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 88, in lastrowid
    self._wait()
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/usr/local/lib/python3.8/dist-packages/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3136, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 2902, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely

**Comment by NickM-27** [comment]
> I thought my hardware acceleration was using qsv. (I thought that was the whole point of acceleration, honestly.)

There are two different hw acceleration APIs for Intel. VAAPI and QSV. You had QSV in the global config but it is of course overwritten by you having the VAAPI args at the camera level. 

```
Exception in thread event_processor:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 3129, in execute_sql
cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: event.retain_indefinitely
```

This is a database error because you updated to 0.11 RC2 and then downgraded to 0.10 without deleting your database which is now incompatible with 0.10

**Comment by christopherdenny** [comment]
Finally! I found the proper QSV settings and applied those globally.

I also deleted the old database, and the Python errors are gone.

I am now seeing about 35% CPU usage and some GPU usage. 

Thank you very much for all your help and support.

**Comment by instantdreams** [comment]
> Finally! I found the proper QSV settings and applied those globally.

What are they?

**Comment by xversial** [comment]
> Finally! I found the proper QSV settings and applied those globally.
> 
> I also deleted the old database, and the Python errors are gone.
> 
> I am now seeing about 35% CPU usage and some GPU usage.
> 
> Thank you very much for all your help and support.

Typical response closing the issue and leaving the rest of us to go re-solve the same problem that's probably been solved hundreds of times already. I'll update my response when I solve it once and for all.

**Comment by NickM-27** [comment]
> > Finally! I found the proper QSV settings and applied those globally.
> > 
> > I also deleted the old database, and the Python errors are gone.
> > 
> > I am now seeing about 35% CPU usage and some GPU usage.
> > 
> > Thank you very much for all your help and support.
> 
> Typical response closing the issue and leaving the rest of us to go re-solve the same problem that's probably been solved hundreds of times already. I'll update my response when I solve it once and for all.

This is all covered in the docs

**Comment by iT3E** [comment]
> > Finally! I found the proper QSV settings and applied those globally.
> > I also deleted the old database, and the Python errors are gone.
> > I am now seeing about 35% CPU usage and some GPU usage.
> > Thank you very much for all your help and support.
> 
> Typical response closing the issue and leaving the rest of us to go re-solve the same problem that's probably been solved hundreds of times already. I'll update my response when I solve it once and for all.

....

doesn't respond 😂
