### ISSUE TITLE
[Camera Support]: reolink RLC-520 

### ISSUE THREAD

**Issue by Davxci** [blakeblackshear/frigate#3844]
### Describe the problem you are having

Hello,
I am French and I use google translate for my message, sorry in advance for the English errors.

Since upgrading from 11 beta 7 to RC2 I have a green screen on the camera, something I didn't have before.
I haven't changed anything in the configuration.

Frigate is installed with docker under a synology DS220+

### Version

0.11.0 Release Candidate 2

### Frigate config file

```yaml
mqtt:
  host: xxx.xxx.xxx.xxx
  port: 1883
  user: mqtt
  password: xxxxxxxx
  client_id: frigate
  topic_prefix: frigate

detectors:
  cpu1:
    type: cpu

birdseye:
  enabled: true
  width: 896
  height: 672
  quality: 8
  mode: continuous
  
ffmpeg:
  hwaccel_args:
    - -hwaccel_output_format
    - yuv420p



detect:
  width: 896
  height: 672
  fps: 7
  enabled: True
  max_disappeared: 25

ui:
  use_experimental: False

objects:
  track:
    - person
    - bicycle
    - bird
    - cat
    - car
    - motorcycle
    
detect:
  stationary:
    interval: 0
    threshold: 50
    
record:
  enabled: True
  events:
    pre_capture: 30
    post_capture: 30
    retain:
      default: 30
      
motion:
  mask:    
    - 481,0,480,94,420,90,421,0    
    - 398,78,397,0,239,0,239,64
  
snapshots:
  enabled: True
  timestamp: True
  retain:
    default: 2

rtmp:
  enabled: False 

cameras:
  reolink:
    rtmp:
      enabled: False
    ffmpeg:
      inputs:
        - path: rtmp://xxx.xxx.xxx.xxx:1935/bcs/channel0_ext.bcs?channel=0&stream=2&user=xxxxxx&password=xxxxxxx
          roles:
            - detect
            - record
      input_args:
        - -avoid_negative_ts
        - make_zero
    detect:
      width: 896
      height: 672
    record:
      enabled: True
```

### Relevant log output

```shell
[2022-09-15 16:01:09] frigate.app                    INFO    : Output process started: 216

[2022-09-15 16:01:09] ws4py                          INFO    : Using epoll

[2022-09-15 16:01:09] frigate.app                    INFO    : Camera processor started for reolink: 221

[2022-09-15 16:01:09] frigate.app                    INFO    : Capture process started for reolink: 222

Process output_processor:

Exception in thread Thread-5:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

[2022-09-15 16:01:09] detector.cpu1                  INFO    : Starting detection process: 215

[2022-09-15 16:01:09] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.

    self.run()

  File "/opt/frigate/frigate/video.py", line 215, in run

    self.start_ffmpeg_detect()

  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect

    self.ffmpeg_detect_process = start_or_restart_ffmpeg(

  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg

    process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

Traceback (most recent call last):

  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap

    self.run()

  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/frigate/frigate/output.py", line 372, in output_frames

    converters[camera] = FFMpegConverter(

  File "/opt/frigate/frigate/output.py", line 36, in __init__

    self.process = sp.Popen(

  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

[2022-09-15 16:01:09] ws4py                          INFO    : Using epoll

[2022-09-15 16:01:15] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56782]

[2022-09-15 16:02:15] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:56782]

ffprob

ffprobe

^C[2022-09-15 16:02:48] frigate.app                    INFO    : Stopping...

[2022-09-15 16:02:48] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'

[2022-09-15 16:02:48] frigate.record                 INFO    : Exiting recording maintenance...

[2022-09-15 16:02:48] frigate.events                 INFO    : Exiting event cleanup...

[2022-09-15 16:02:48] frigate.watchdog               INFO    : Exiting watchdog...

[2022-09-15 16:02:48] frigate.record                 INFO    : Exiting recording cleanup...

[2022-09-15 16:02:48] frigate.stats                  INFO    : Exiting watchdog...

[2022-09-15 16:02:49] frigate.object_processing      INFO    : Exiting object processor...

[2022-09-15 16:02:49] frigate.video                  INFO    : reolink: exiting subprocess

[2022-09-15 16:02:50] frigate.events                 INFO    : Exiting event processor...

[2022-09-15 16:02:50] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.

[2022-09-15 16:02:50] root                           INFO    : Waiting for detection process to exit gracefully...
```

### FFprobe output from your camera

```shell
sorry i don't know how to do it
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

reolink RLC-520 

### Any other information that may be helpful

ModelRLC-520
UID95270001WLOFVCCL
Build No.build 20121112
Hardware No.IPC_515B16M5M
Config Versionv3.0.0.0
Firmware Versionv3.0.0.136_20121112
DetailsIPC_515B16M5MS10E1W01100000001

**Comment by NickM-27** [comment]
Hi, please read the release notes. This error is covered there

> Some deployment approaches are overwriting the PATH environment value to an old value. If you see errors like No such file or directory: 'ffmpeg', then you need to stop overriding your PATH. This happens with both Proxmox LXC and Portainer (https://github.com/blakeblackshear/frigate/issues/3223)

**Comment by Davxci** [comment]
thank you for your feedback, it actually solved my problem.

sorry for the inconvenience it's not easy for me to read in english

**Comment by NickM-27** [comment]
Sure no problem, glad it worked 👍

I will close this issue, feel free to open another one if something else comes up.
