### ISSUE TITLE
Detection stops working with ZeroDivisionError exception

### ISSUE THREAD

**Issue by fl42** [blakeblackshear/frigate#3878]
### Describe the problem you are having

Hello,

Thanks for Frigate!

I have a weird issue on latest beta: some cameras (between 1 and 3 in general over 6) stop working after some time (few hours) with ZeroDivisionError exception.
No relevant logs prior to this exception.

I through it was related to HW acceleration (as I enabled it recently) but the problem still happen with HW acceleration disabled.

Any hints?

### Version

0.11.0-be7b858

### Frigate config file

```yaml
[...]
ffmpeg:
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p

cameras:
  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://XXX:XXX@IP:554/11
          roles:
            - detect
            - record
      output_args:
        # Enable audio
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 4
      events:
        pre_capture: 2
        post_capture: 2
        retain:
          default: 2
          objects:
            person: 7
            car: 7
    objects:
      track:
        - person
[...]
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-20 12:57:12] frigate.app                    INFO    : Starting Frigate (0.11.0-be7b858)
Starting migrations
[2022-09-20 12:57:13] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-20 12:57:13] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-20 12:57:13] detector.coral                 INFO    : Starting detection process: 215
[2022-09-20 12:57:13] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2022-09-20 12:57:13] ws4py                          INFO    : Using epoll
[2022-09-20 12:57:13] frigate.app                    INFO    : Output process started: 217
[2022-09-20 12:57:13] frigate.app                    INFO    : Camera processor started for Camera1: 223
[2022-09-20 12:57:13] frigate.app                    INFO    : Camera processor started for Camera2: 225
[2022-09-20 12:57:13] frigate.app                    INFO    : Camera processor started for Camera3: 237
[2022-09-20 12:57:13] frigate.edgetpu                INFO    : TPU found
[2022-09-20 12:57:13] frigate.app                    INFO    : Camera processor started for Camera4: 239
[2022-09-20 12:57:13] frigate.app                    INFO    : Camera processor started for Camera5: 240
[2022-09-20 12:57:13] frigate.app                    INFO    : Camera processor started for Camera6: 242
[2022-09-20 12:57:13] frigate.app                    INFO    : Camera processor started for Camera7: 243
[2022-09-20 12:57:13] frigate.app                    INFO    : Capture process started for Camera1: 245
[2022-09-20 12:57:13] frigate.app                    INFO    : Capture process started for Camera2: 249
[2022-09-20 12:57:13] frigate.app                    INFO    : Capture process started for Camera3: 252
[2022-09-20 12:57:13] frigate.app                    INFO    : Capture process started for Camera4: 255
[2022-09-20 12:57:13] frigate.app                    INFO    : Capture process started for Camera5: 261
[2022-09-20 12:57:13] frigate.app                    INFO    : Capture process started for Camera6: 266
[2022-09-20 12:57:13] frigate.app                    INFO    : Capture process started for Camera7: 273
[2022-09-20 12:57:13] ws4py                          INFO    : Using epoll
Process camera_processor:Camera1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/video.py", line 388, in track_camera
    process_frames(
  File "/opt/frigate/frigate/video.py", line 628, in process_frames
    detect(
  File "/opt/frigate/frigate/video.py", line 465, in detect
    ratio = width / height
ZeroDivisionError: division by zero
Process camera_processor:Camera2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/video.py", line 388, in track_camera
    process_frames(
  File "/opt/frigate/frigate/video.py", line 628, in process_frames
    detect(
  File "/opt/frigate/frigate/video.py", line 465, in detect
    ratio = width / height
ZeroDivisionError: division by zero
Process camera_processor:Camera5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/video.py", line 388, in track_camera
    process_frames(
  File "/opt/frigate/frigate/video.py", line 628, in process_frames
    detect(
  File "/opt/frigate/frigate/video.py", line 465, in detect
    ratio = width / height
ZeroDivisionError: division by zero
[2022-09-20 18:09:58] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:36320]
[2022-09-20 18:11:49] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44386]
[2022-09-20 18:11:54] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:44386]
[2022-09-20 18:11:57] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:55774]
[2022-09-20 18:15:30] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:8082 | Remote => 127.0.0.1:55774]
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

Various

### Any other information that may be helpful

- On Cameras page, image is freezed
- Live stream is not working
- Detection is not working
- Recording *is* working
- In stats, frozen cameras fps are still at 5fps
- LIBVA_DRIVER_NAME set to i965
- Frigate running in k3s v1.24.4+k3s1
- CPU is a J4125

Furthermore, is there any way to detect when the problem occurs to restart the pod? (with a liveness probe)
~~Log pattern: no log~~, /api/stats: fps still > 0, any other ideas?
EDIT: There is trivial log pattern (match ZeroDivisionError) but it's not easily accessible using a liveness probe...

Thanks

**Comment by NickM-27** [comment]
Please include your entire config

**Comment by NickM-27** [comment]
Also, how often does this happen? Does it happen the first time an object is detected or only sometimes?

**Comment by fl42** [comment]
Hello,

Config for other cameras is very similar to the first camera, this is why I removed them.
But if you think it's relevant here, I posted the whole config [here](https://privatebin.net/?bbf21eb3f21bbc40#CWqLgcEKAdzaoLenbBXRWLwi3EdKg7w5sUvREShmBadc).

There is no clear pattern when this occurs.
For instance it occurred 2h03m after the startup of frigate, and to the best of my knowledge there was no object of interest in front of the camera (but still frigate may have detected something later classified as false positive, or not tracked).
It generally happens few hours after startup, for one or more cameras, not always the same cameras. Restarting the pod solves the issue.

I tried to rollback to 0.11.0-rc2, I'll let you know.

**Comment by NickM-27** [comment]
@fl42 I have created a one-off build that will have some extra logging: `crzynik/frigate:zero-division`

Please replace `blakeblackshear/frigate:0.11.0-rc3` with `crzynik/frigate:zero-division` in your docker CLI command and report back here with the logs after one of these errors occurs.

**Comment by fl42** [comment]
@NickM-27 Thanks!
Running on crzynik/frigate:zero-division now.

BTW the problem seems to *not* be present in blakeblackshear/frigate:0.11.0-rc2.

I'll let you know

**Comment by NickM-27** [comment]
yes it is due to https://github.com/blakeblackshear/frigate/pull/3830 which was brought in during RC3

**Comment by NickM-27** [comment]
@fl42 Thanks, I have uploaded `crzynik/frigate:zero-division-fix` so please try that and let me know if you no longer see the problem. I did leave a small error log in there so it is clear when the error would have occurred, but the behavior will be handled the same as my fix (which just ignores that particular detection).

**Comment by fl42** [comment]
@NickM-27 
```
│ [2022-09-21 16:47:39] frigate.video                  ERROR   : Ignoring a zero division error: y_min 722.9750053882599 || y_max 961.030467748642                                                                 │
│ [2022-09-21 16:49:02] frigate.video                  ERROR   : Ignoring a zero division error: y_min 720.2449617385864 || y_max 951.388810634613                                                                 │
│ [2022-09-21 16:50:18] frigate.video                  ERROR   : Ignoring a zero division error: y_min 739.6458892822266 || y_max 1140.1957397460938                                                               │
│ [2022-09-21 16:50:41] frigate.video                  ERROR   : Ignoring a zero division error: y_min 1093.9056313037872 || y_max 1995.6351163387299                                                              │
│ [2022-09-21 16:52:23] frigate.video                  ERROR   : Ignoring a zero division error: y_min 728.4528932571411 || y_max 1098.3791198730469                                                               │
│ [2022-09-21 16:52:41] frigate.video                  ERROR   : Ignoring a zero division error: y_min 1089.4557747840881 || y_max 2010.0693731307983                                                              │
│ [2022-09-21 16:55:37] frigate.video                  ERROR   : Ignoring a zero division error: y_min 724.2746925354004 || y_max 1060.486930847168                                                                │
│ [2022-09-21 17:02:16] frigate.video                  ERROR   : Ignoring a zero division error: y_min 725.7078919410706 || y_max 1101.1241211891174
```
Exceptions are caught as expected and detection is working, many thanks for the fast fix!

**Comment by NickM-27** [comment]
@fl42 Can you please try once more? We are still not 100% sure where this issue originated, can you please try `crzynik/frigate:zero-division-check` for some time and let me know if you see any of those error logs?

**Comment by NickM-27** [comment]
@fl42 actually I missed something and the log won't show on that build. Can you please try `crzynik/frigate:zero-division-check-t` and again post if you see any of those errors. Appreciate your help with tihs.

**Comment by fl42** [comment]
@NickM-27 
```
│ [2022-09-22 08:47:30] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.64459604, -0.0030890107, 0.9872109, 0.980319) calc_box: (156, 721, 1257, 719)                             │
│ [2022-09-22 08:47:46] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.7613177, 0.011195868, 0.99413186, 0.9698367) calc_box: (15, 1081, 1377, 1079)                             │
│ [2022-09-22 08:48:11] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.6420537, 0.0123722255, 0.98975325, 0.98139906) calc_box: (56, 739, 1172, 719)                             │
│ [2022-09-22 08:48:21] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.6392968, 0.0123722255, 0.98699635, 0.98139906) calc_box: (15, 739, 1135, 719)                             │
│ [2022-09-22 08:48:43] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.74386376, 0.011835992, 0.9944741, 0.9564579) calc_box: (122, 1080, 1493, 1079)                            │
│ [2022-09-22 08:49:00] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.5500726, 0.009829849, 0.98810536, 0.9840435) calc_box: (12, 719, 1279, 719)                               │
│ [2022-09-22 08:49:01] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.75355893, 0.011195868, 0.9933347, 0.9698367) calc_box: (131, 1079, 1503, 1079)                            │
│ [2022-09-22 08:50:05] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.75355893, 0.004826516, 0.9933347, 0.96346736) calc_box: (117, 1085, 1498, 1079)                           │
│ [2022-09-22 08:50:20] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.54041874, -0.0022869706, 0.9988916, 0.9705809) calc_box: (0, 1080, 1919, 1079)                            │
│ [2022-09-22 08:51:02] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.52648675, 0.013752878, 0.98431253, 0.9596815) calc_box: (18, 720, 1279, 719)                              │
│ [2022-09-22 08:52:10] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.54255766, -0.0022869706, 1.0010306, 0.9705809) calc_box: (0, 1085, 1919, 1079)                            │
│ [2022-09-22 08:52:30] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.5092983, 0.003533423, 0.9878117, 0.94946206) calc_box: (5, 737, 1279, 719)                                │
│ [2022-09-22 08:52:43] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.7398651, 0.004826516, 0.9941948, 0.96346736) calc_box: (86, 1080, 1485, 1079)                             │
│ [2022-09-22 08:52:45] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.6339599, 0.0051816404, 0.9868196, 0.98858964) calc_box: (129, 732, 1266, 719)                             │
│ [2022-09-22 08:53:08] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.75355893, 0.011835992, 0.9933347, 0.9564579) calc_box: (99, 1079, 1452, 1079)                             │
│ [2022-09-22 08:53:44] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.6367167, 0.0123722255, 0.98957646, 0.98139906) calc_box: (128, 733, 1244, 719)                            │
│ [2022-09-22 08:53:49] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.7235907, 0.010451734, 0.9933576, 0.9833196) calc_box: (246, 720, 1215, 719)                               │
│ [2022-09-22 08:55:13] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.74928105, 0.024574697, 0.9890568, 0.9691966) calc_box: (23, 719, 930, 719)                                │
│ [2022-09-22 08:55:59] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.5728727, 0.020049304, 0.9858393, 0.99426293) calc_box: (45, 721, 1272, 719)                               │
│ [2022-09-22 08:56:33] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.73156106, 0.011195868, 0.98966515, 0.9698367) calc_box: (217, 719, 1160, 719)                             │
│ [2022-09-22 08:56:43] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.6367167, 0.0123722255, 0.98957646, 0.98139906) calc_box: (138, 736, 1258, 719)                            │
│ [2022-09-22 08:57:15] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.73370004, 0.01756522, 0.9918041, 0.97620606) calc_box: (290, 719, 1229, 719)                              │
│ [2022-09-22 09:01:36] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.5092983, 0.013752878, 0.9878117, 0.9596815) calc_box: (19, 733, 1279, 719)                                │
│ [2022-09-22 09:01:53] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.53325665, 0.0067337155, 0.9843874, 0.9667007) calc_box: (9, 731, 1279, 719)                               │
│ [2022-09-22 09:01:54] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.72556317, 0.011195868, 0.9913851, 0.9698367) calc_box: (256, 719, 1207, 719)                              │
│ [2022-09-22 09:03:25] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.5092983, 0.0067337155, 0.9878117, 0.9667007) calc_box: (9, 741, 1279, 719)                                │
│ [2022-09-22 09:05:49] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.52990913, 0.0169532, 0.9877349, 0.9769201) calc_box: (23, 724, 1279, 719)                                 │
│ [2022-09-22 09:05:51] frigate.video                  ERROR   : Division by 0 error was ignored box: (0.5092983, 0.0067337155, 0.9878117, 0.9667007) calc_box: (9, 733, 1279, 719)
```

**Comment by NickM-27** [comment]
Thank you, does it happen all the time or does it happen in clumps? These are all pretty close together.

**Comment by fl42** [comment]
See a longer example [here](https://privatebin.net/?6c7949d2dc408682#95XyPS37i3Q8ghdFE8g1hGDUKfMEmLzkAQ3ZvioWD8X1)
I would say it happens all the time.

**Comment by NickM-27** [comment]
Thanks for your help, should be good now 👍

**Comment by fl42** [comment]
Thank you!
Closing as PR is merged.
