### ISSUE TITLE
[Support]: ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by newcbomb** [blakeblackshear/frigate#3883]
### Describe the problem you are having

Frigate was working fine yesterday, woke up today to the Add-on not running with the following log output:

### Version

0.10.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: frigate
  password: x
rtmp:
  enabled: False
objects:
  track:
    - person
    - car
    - motorcycle
    - dog
    - cat
cameras:
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://admin:x@10.0.3.6:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 5
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:x@10.0.3.7:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 5
  back_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:x@10.0.3.8:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 640
      height: 480
      fps: 5
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://admin:x@10.0.50.119:8554/unicast
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
        - motorcycle
        - dog
        - cat
snapshots:
  enabled: True
detectors:
  coral:
    type: edgetpu
    device: usb
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/frigate/frigate/__main__.py", line 9, in <module>
    from frigate.app import FrigateApp
  File "/opt/frigate/frigate/app.py", line 13, in <module>
    from peewee_migrate import Router
  File "/usr/local/lib/python3.8/dist-packages/peewee_migrate/__init__.py", line 6, in <module>
    import peewee as pw
  File "/usr/local/lib/python3.8/dist-packages/peewee.py", line 7, in <module>
    import calendar
  File "/usr/lib/python3.8/calendar.py", line 10, in <module>
    import locale as _locale
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 640, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink/Wyze

**Comment by NickM-27** [comment]
Has this happened more than once, how long has frigate been running?

According to https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data it is something with the particular python install so a reboot should have fixed it. We've not had this reported before.

**Comment by newcbomb** [comment]
This is the first I've noticed it and I get the error every time I start the addon. I've been using it for about a month and restarted it last a few days ago to add a new camera.

**Comment by NickM-27** [comment]
> I get the error every time I start the addon

Ah interesting, definitely sounds like something is messed up. Are you running an RPi / SD card?

Recommendations:
- Restart the host and see if it continues
- If it still continues then try going into the frigate addon menu and rebuild the container

**Comment by NickM-27** [comment]
Glad that worked. Going to close and if something else comes up feel free to create a new issue.
