### ISSUE TITLE
[Support]: Frigate no longer running since update

### ISSUE THREAD

**Issue by chatz86** [blakeblackshear/frigate#3893]
### Describe the problem you are having

Hi guys. Frigate won't run and I don't know what to do. Please help
![Screenshot_20220923-160414_Home Assistant](https://user-images.githubusercontent.com/82794294/191917318-91998f69-10d4-433f-935a-6ab966440332.jpg)

### Version

0.11.0-rc2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.189
  port: 1883
  topic_prefix: frigate
  client_id: core-mosquitto
  user: mqtt_user
  password: mqtt_pass
  stats_interval: 60
birdseye:
  enabled: False
  width: 1920
  height: 1080
  quality: 8
  mode: objects 
rtmp:
  enabled: True
live:
  height: 720
  quality: 8
detectors:
  coral:
    type: edgetpu
    device: usb
detect:
  enabled: True
  width: 1280
  height: 720
  fps: 5
  max_disappeared: 25
objects:
  track: 
    - person
    - dog
    - car
record:
  # Optional: Enable recording (default: shown below)
  # WARNING: If recording is disabled in the config, turning it on via 
  #          the UI or MQTT later will have no effect.
  # WARNING: Frigate does not currently support limiting recordings based
  #          on available disk space automatically. If using recordings,
  #          you must specify retention settings for a number of days that
  #          will fit within the available disk space of your drive or Frigate
  #          will crash.
  enabled: True
  # Optional: Number of minutes to wait between cleanup runs (default: shown below)
  # This can be used to reduce the frequency of deleting recording segments from disk if you want to minimize i/o
  expire_interval: 60
  # Optional: Retention settings for recording
  retain:
    # Optional: Number of days to retain recordings regardless of events (default: shown below)
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
    # Optional: Mode for retention. Available options are: all, motion, and active_objects
    #   all - save all recording segments regardless of activity
    #   motion - save all recordings segments with any detected motion
    #   active_objects - save all recording segments with active/moving objects
    # NOTE: this mode only applies when the days setting above is greater than 0
    mode: motion
  # Optional: Event recording settings
  events:
    # Optional: Maximum length of time to retain video during long events. (default: shown below)
    # NOTE: If an object is being tracked for longer than this amount of time, the retained recordings
    #       will be the last x seconds of the event unless retain->days under record is > 0.
    # Optional: Number of seconds before the event to include (default: shown below)
    pre_capture: 25
    # Optional: Number of seconds after the event to include (default: shown below)
    post_capture: 10
    # Optional: Objects to save recordings for. (default: all tracked objects)
    objects:
      - person
      - car
    # Optional: Restrict recordings to objects that entered any of the listed zones (default: no required zones)
    required_zones: []
    # Optional: Retention settings for recordings of events
    retain:
      # Required: Default retention days (default: shown below)
      default: 30
      # Optional: Mode for retention. (default: shown below)
      #   all - save all recording segments for events regardless of activity
      #   motion - save all recordings segments for events with any detected motion
      #   active_objects - save all recording segments for event with active/moving objects
      #
      # NOTE: If the retain mode for the camera is more restrictive than the mode configured
      #       here, the segments will already be gone by the time this mode is applied.
      #       For example, if the camera retain mode is "motion", the segments without motion are
      #       never stored, so setting the mode to "all" here won't bring them back.
      mode: all
      # Optional: Per object retention days
      objects:
        person: 60
cameras:
  Garage:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://garage:tiger1986@192.168.1.174:554/stream2
          roles:
            - detect
            - rtmp
        - path: rtsp://garage:tiger1986@192.168.1.174:554/stream1
          roles:
            - record
    objects:
      track:
        - person
        - car
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
  Entrance:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://entrance:tiger1986@192.168.1.74:554/stream2
          roles:
            - detect
            - rtmp
        - path: rtsp://entrance:tiger1986@192.168.1.74:554/stream1
          roles:
            - record
    objects:
      track:
        - person
        - dog
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
  Workshop_Inside:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://workshop_inside:tiger1986@192.168.1.246:554/stream2
          roles:
            - detect
            - rtmp
        - path: rtsp://workshop_inside:tiger1986@192.168.1.246:554/stream1
          roles:  
            - record
    objects:
      track:
        - person
        - dog
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
  Workshop_Outside:
    ffmpeg:
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1
      hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      inputs:
        - path: rtsp://workshop_outside:tiger1986@192.168.1.88:554/stream2
          roles:
            - detect
            - rtmp
        - path: rtsp://workshop_outside:tiger1986@192.168.1.88:554/stream1
          roles:  
            - record
    objects:
      track:
        - person
        - dog
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    snapshots: 
      enabled: True
      timestamp: False
      bounding_box: True
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      quality: 70
```

### Relevant log output

```shell
[2022-09-23 16:03:56] watchdog.Workshop_Inside       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-23 16:03:56] ffmpeg.Workshop_Inside.detect  ERROR   : [AVHWDeviceContext @ 0x55dd56838640] No VA display found for device /dev/dri/renderD128.
[2022-09-23 16:03:56] ffmpeg.Workshop_Inside.detect  ERROR   : Device creation failed: -22.
[2022-09-23 16:03:56] ffmpeg.Workshop_Inside.detect  ERROR   : [h264 @ 0x55dd5671fc40] No device available for decoder: device type vaapi needed for codec h264.
[2022-09-23 16:03:56] ffmpeg.Workshop_Inside.detect  ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-09-23 16:03:56] watchdog.Entrance              ERROR   : Ffmpeg process crashed unexpectedly for Entrance.
[2022-09-23 16:03:56] watchdog.Entrance              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-23 16:03:56] ffmpeg.Entrance.detect         ERROR   : [AVHWDeviceContext @ 0x561de29c1440] No VA display found for device /dev/dri/renderD128.
[2022-09-23 16:03:56] ffmpeg.Entrance.detect         ERROR   : Device creation failed: -22.
[2022-09-23 16:03:56] ffmpeg.Entrance.detect         ERROR   : [h264 @ 0x561de28a7b40] No device available for decoder: device type vaapi needed for codec h264.
[2022-09-23 16:03:56] ffmpeg.Entrance.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-09-23 16:03:56] watchdog.Workshop_Outside      ERROR   : Ffmpeg process crashed unexpectedly for Workshop_Outside.
[2022-09-23 16:03:56] watchdog.Workshop_Outside      ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-23 16:03:56] ffmpeg.Workshop_Outside.detect ERROR   : [AVHWDeviceContext @ 0x55845eca5e40] No VA display found for device /dev/dri/renderD128.
[2022-09-23 16:03:56] ffmpeg.Workshop_Outside.detect ERROR   : Device creation failed: -22.
[2022-09-23 16:03:56] ffmpeg.Workshop_Outside.detect ERROR   : [h264 @ 0x55845eb88100] No device available for decoder: device type vaapi needed for codec h264.
[2022-09-23 16:03:56] ffmpeg.Workshop_Outside.detect ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-09-23 16:03:58] frigate.video                  ERROR   : Garage: Unable to read frames from ffmpeg process.
[2022-09-23 16:03:58] frigate.video                  ERROR   : Garage: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:03:58] frigate.video                  ERROR   : Entrance: Unable to read frames from ffmpeg process.
[2022-09-23 16:03:58] frigate.video                  ERROR   : Entrance: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:03:59] frigate.video                  ERROR   : Workshop_Inside: Unable to read frames from ffmpeg process.
[2022-09-23 16:03:59] frigate.video                  ERROR   : Workshop_Inside: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:04:00] frigate.video                  ERROR   : Workshop_Outside: Unable to read frames from ffmpeg process.
[2022-09-23 16:04:00] frigate.video                  ERROR   : Workshop_Outside: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:03:36] detector.coral                 INFO    : Starting detection process: 216
Process detector:coral:
[2022-09-23 16:03:36] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-23 16:04:01] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-09-23 16:04:06] watchdog.Garage                ERROR   : Ffmpeg process crashed unexpectedly for Garage.
[2022-09-23 16:04:06] watchdog.Garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-23 16:04:06] ffmpeg.Garage.detect           ERROR   : [AVHWDeviceContext @ 0x55fd78a03280] No VA display found for device /dev/dri/renderD128.
[2022-09-23 16:04:06] ffmpeg.Garage.detect           ERROR   : Device creation failed: -22.
[2022-09-23 16:04:06] ffmpeg.Garage.detect           ERROR   : [h264 @ 0x55fd789fc080] No device available for decoder: device type vaapi needed for codec h264.
[2022-09-23 16:04:06] ffmpeg.Garage.detect           ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-09-23 16:04:06] watchdog.Workshop_Inside       ERROR   : Ffmpeg process crashed unexpectedly for Workshop_Inside.
[2022-09-23 16:04:06] watchdog.Workshop_Inside       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-23 16:04:06] ffmpeg.Workshop_Inside.detect  ERROR   : [AVHWDeviceContext @ 0x5625503c6640] No VA display found for device /dev/dri/renderD128.
[2022-09-23 16:04:06] ffmpeg.Workshop_Inside.detect  ERROR   : Device creation failed: -22.
[2022-09-23 16:04:06] ffmpeg.Workshop_Inside.detect  ERROR   : [h264 @ 0x5625503dda40] No device available for decoder: device type vaapi needed for codec h264.
[2022-09-23 16:04:06] ffmpeg.Workshop_Inside.detect  ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-09-23 16:04:06] watchdog.Entrance              ERROR   : Ffmpeg process crashed unexpectedly for Entrance.
[2022-09-23 16:04:06] watchdog.Entrance              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-23 16:04:06] ffmpeg.Entrance.detect         ERROR   : [AVHWDeviceContext @ 0x55e4f74fb780] No VA display found for device /dev/dri/renderD128.
[2022-09-23 16:04:06] ffmpeg.Entrance.detect         ERROR   : Device creation failed: -22.
[2022-09-23 16:04:06] ffmpeg.Entrance.detect         ERROR   : [h264 @ 0x55e4f74fbd80] No device available for decoder: device type vaapi needed for codec h264.
[2022-09-23 16:04:06] ffmpeg.Entrance.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-09-23 16:04:06] watchdog.Workshop_Outside      ERROR   : Ffmpeg process crashed unexpectedly for Workshop_Outside.
[2022-09-23 16:04:06] watchdog.Workshop_Outside      ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
[2022-09-23 16:04:06] ffmpeg.Workshop_Outside.detect ERROR   : [AVHWDeviceContext @ 0x5585fde1e700] No VA display found for device /dev/dri/renderD128.
[2022-09-23 16:04:06] ffmpeg.Workshop_Outside.detect ERROR   : Device creation failed: -22.
[2022-09-23 16:04:06] ffmpeg.Workshop_Outside.detect ERROR   : [h264 @ 0x5585fde1da40] No device available for decoder: device type vaapi needed for codec h264.
[2022-09-23 16:04:06] ffmpeg.Workshop_Outside.detect ERROR   : Device setup failed for decoder on input stream #0:0 : Invalid argument
[2022-09-23 16:04:07] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-09-23 16:04:07] frigate.app                    INFO    : Stopping...
[2022-09-23 16:04:07] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-09-23 16:04:07] frigate.stats                  INFO    : Exiting watchdog...
[2022-09-23 16:04:07] frigate.events                 INFO    : Exiting event cleanup...
[2022-09-23 16:04:07] frigate.record                 INFO    : Exiting recording cleanup...
[2022-09-23 16:04:07] frigate.watchdog               INFO    : Exiting watchdog...
[2022-09-23 16:04:07] frigate.events                 INFO    : Exiting event processor...
[2022-09-23 16:04:07] frigate.record                 INFO    : Exiting recording maintenance...
[2022-09-23 16:04:08] frigate.video                  ERROR   : Entrance: Unable to read frames from ffmpeg process.
[2022-09-23 16:04:08] frigate.video                  ERROR   : Entrance: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:04:08] frigate.video                  ERROR   : Garage: Unable to read frames from ffmpeg process.
[2022-09-23 16:04:08] frigate.video                  ERROR   : Garage: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:04:09] frigate.video                  ERROR   : Workshop_Inside: Unable to read frames from ffmpeg process.
[2022-09-23 16:04:09] frigate.video                  ERROR   : Workshop_Inside: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:04:09] frigate.video                  ERROR   : Workshop_Outside: Unable to read frames from ffmpeg process.
[2022-09-23 16:04:09] frigate.video                  ERROR   : Workshop_Outside: ffmpeg process is not running. exiting capture thread...
[2022-09-23 16:04:16] frigate.object_processing      INFO    : Exiting object processor...
[2022-09-23 16:04:16] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-09-23 16:04:16] root                           INFO    : Waiting for detection process to exit gracefully...
[cmd] python3 exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
How do I do this?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tplink Tapo C200, C210 and C320WS

### Any other information that may be helpful

Was working fine until update. I can still see a stream with RTSP.

**Comment by blakeblackshear** [comment]
I see two different things going on here. The Coral issue and your hwaccel args. Did you try doing a full restart of HassOS? Sometimes this happens with the Coral when something else is hanging onto a connection.

If you still get ffmpeg errors about renderD128, try looking at the updated docs on hwaccel and or setting the i915 driver as described in the breaking changes.

**Comment by chatz86** [comment]
Hi Blake,

I've done numerous HassOS restarts. Even powered the thing off and back on. No good though.

**Comment by NickM-27** [comment]
In the other issue they needed to disable protected mode to get the coral to work. Also I'd recommend updating to 0.11 stable instead of RC2 (use the full access container instead of beta full access)

**Comment by chatz86** [comment]
> In the other issue they needed to disable protected mode to get the coral to work. Also I'd recommend updating to 0.11 stable instead of RC2 (use the full access container instead of beta full access)

Thanks so much Nick. Disabling protection mode fixed it all!!!

**Comment by NickM-27** [comment]
Great! I'll close this and feel free to open a new issue if something else comes up

**Comment by chatz86** [comment]
> Great! I'll close this and feel free to open a new issue if something else comes up

Thanks so much!
