### ISSUE TITLE
[Support]: 0.11.0 Crashes

### ISSUE THREAD

**Issue by alfwro13** [blakeblackshear/frigate#3947]
### Describe the problem you are having

I have upgraded HomeAssistant's Frigate addon to the latest version 0.11.0 (I had to uninstall the previous version to install it).
After the upgrade unfortunately Frigate fails to start - if I read the log files correctly it fails to find my USB Coral device.
Before the upgrade I have created snapshot in my ProxmoxVE of the whole HomeAssistant VM so as a Test I have rolled back the snapshot and with the old version (0.10.1-83481AF) it works fine - TPU found

### Version

unable to access that - app is crashing

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-26 10:26:07] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
[2022-09-26 10:26:08] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-09-26 10:26:08] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-26 10:26:08] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-26 10:26:08] frigate.app                    INFO    : Output process started: 217
[2022-09-26 10:26:08] detector.coral                 INFO    : Starting detection process: 216
[2022-09-26 10:26:08] ws4py                          INFO    : Using epoll
Process detector:coral:
[2022-09-26 10:26:08] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-26 10:26:08] frigate.app                    INFO    : Camera processor started for szopa_26: 226
[2022-09-26 10:26:08] frigate.app                    INFO    : Camera processor started for front_door_27: 228
[2022-09-26 10:26:08] frigate.app                    INFO    : Camera processor started for deck_cam_23: 229
[2022-09-26 10:26:08] frigate.app                    INFO    : Camera processor started for workshop_22: 230
[2022-09-26 10:26:08] frigate.app                    INFO    : Camera processor started for drive_24: 231
Traceback (most recent call last):
[2022-09-26 10:26:08] frigate.app                    INFO    : Camera processor started for dom_25: 233
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-09-26 10:26:08] frigate.app                    INFO    : Capture process started for szopa_26: 235
[2022-09-26 10:26:33] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
[2022-09-26 10:26:08] frigate.app                    INFO    : Capture process started for front_door_27: 236
[2022-09-26 10:26:08] frigate.app                    INFO    : Capture process started for deck_cam_23: 238
[2022-09-26 10:26:08] frigate.app                    INFO    : Capture process started for workshop_22: 239
[2022-09-26 10:26:08] frigate.app                    INFO    : Capture process started for drive_24: 243
[2022-09-26 10:26:08] frigate.app                    INFO    : Capture process started for dom_25: 246
[2022-09-26 10:26:08] ws4py                          INFO    : Using epoll
[2022-09-26 10:26:38] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-09-26 10:26:38] frigate.app                    INFO    : Stopping...
[2022-09-26 10:26:38] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-09-26 10:26:38] frigate.events                 INFO    : Exiting event cleanup...
[2022-09-26 10:26:38] frigate.stats                  INFO    : Exiting watchdog...
[2022-09-26 10:26:38] frigate.watchdog               INFO    : Exiting watchdog...
[2022-09-26 10:26:38] frigate.record                 INFO    : Exiting recording cleanup...
[2022-09-26 10:26:38] frigate.record                 INFO    : Exiting recording maintenance...
[2022-09-26 10:26:38] frigate.events                 INFO    : Exiting event processor...
[2022-09-26 10:26:38] frigate.object_processing      INFO    : Exiting object processor...
[2022-09-26 10:26:38] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-09-26 10:26:38] root                           INFO    : Waiting for detection process to exit gracefully...
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 24 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cmd] python3 exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by alfwro13** [comment]
disabling protection mode has fixed it

**Comment by NickM-27** [comment]
Will go ahead and close then, feel free to open a new issue if something else comes up
