### ISSUE TITLE
[EdgeTPU Support]: 

### ISSUE THREAD

**Issue by driesvj** [blakeblackshear/frigate#3949]
### Describe the problem you are having

upgraded to 3.1.1 and HA 0.11 Add-on and TPU is not working 
No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.

### Version

HA  0.11.0

### Frigate config file

```yaml
mqtt:
  host: x
  user: x
  password: x
  topic_prefix: frigate
  client_id: frigate
  stats_interval: 60
  
detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  # Name of your camera
  Kamers:
    ffmpeg:
      inputs:
        - path: rtsp://x:554/Streaming/Channels/103/
          roles:
            - detect
    detect:
      width: 1024 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 8
      enabled: True
```

### docker-compose file or Docker CLI command

```yaml
na
```

### Relevant log output

```shell
[2022-09-26 14:12:19] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-26 14:12:19] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/3890

**Comment by driesvj** [comment]
thanks, what worked for me was to plug the coral usb into a new usb port and restarted the server.

**Comment by NickM-27** [comment]
Glad it's working. Will close and feel free to open a new issue if something comes up
