### ISSUE TITLE
Frigate not working after update to v0.11.00

### ISSUE THREAD

**Issue by JL500** [blakeblackshear/frigate#3955]
### Describe the problem you are having

I have update Frigate NVR addon this morning. Everything has been working fine for a few minutes. Then, Frigate stopped and I am unable to restart it properly and make it work again.

I am using Home Assistant OS in a Raspberry Pi 4.

I am am quite newby with all of this so I have no clue what to do.

Could any of you give me a hand?

Thanks in advance

### Version

0.11.00

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.120
  port: 1883
  user: addons
  password: PW
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  Salon: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://adminha:PW@192.168.0.129:554/stream2
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      enabled: true
    objects:
      track:
        - person
        - cat
  Cocina: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://adminha:PW.168.0.123:554/stream2
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      enabled: true
    objects:
      track:
        - person
        - cat
  Despacho: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://adminha:PW@192.168.0.126:554/stream2
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      enabled: true
    objects:
      track:
        - person
        - cat
  Buhardilla: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://adminha:PW@192.168.0.135:554/stream2
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      enabled: false
    objects:
      track:
        - person
        - cat
  Garaje: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://adminha:PW@192.168.0.124:554/stream2
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: true # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
      fps: 5
      enabled: false
    objects:
      track:
        - person
        - cat
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-27 13:00:01] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
[2022-09-27 13:00:01] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-09-27 13:00:01] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-27 13:00:01] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-27 13:00:01] frigate.app                    INFO    : Output process started: 217
[2022-09-27 13:00:01] detector.coral                 INFO    : Starting detection process: 216
[2022-09-27 13:00:01] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-09-27 13:00:01] frigate.app                    INFO    : Camera processor started for Salon: 221
[2022-09-27 13:00:01] frigate.app                    INFO    : Camera processor started for Cocina: 222
[2022-09-27 13:00:01] ws4py                          INFO    : Using epoll
[2022-09-27 13:00:01] frigate.app                    INFO    : Camera processor started for Despacho: 225
[2022-09-27 13:00:01] frigate.app                    INFO    : Camera processor started for Buhardilla: 229
[2022-09-27 13:00:01] frigate.app                    INFO    : Camera processor started for Garaje: 231
[2022-09-27 13:00:01] frigate.app                    INFO    : Capture process started for Salon: 232
[2022-09-27 13:00:01] frigate.app                    INFO    : Capture process started for Cocina: 234
[2022-09-27 13:00:01] frigate.app                    INFO    : Capture process started for Despacho: 237
[2022-09-27 13:00:01] frigate.app                    INFO    : Capture process started for Buhardilla: 240
[2022-09-27 13:00:01] frigate.app                    INFO    : Capture process started for Garaje: 244
[2022-09-27 13:00:02] ws4py                          INFO    : Using epoll
[2022-09-27 13:00:27] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-09-27 13:00:32] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-09-27 13:00:32] frigate.app                    INFO    : Stopping...
[2022-09-27 13:00:32] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-09-27 13:00:32] frigate.stats                  INFO    : Exiting watchdog...
[2022-09-27 13:00:32] frigate.events                 INFO    : Exiting event cleanup...
[2022-09-27 13:00:32] frigate.record                 INFO    : Exiting recording cleanup...
[2022-09-27 13:00:32] frigate.watchdog               INFO    : Exiting watchdog...
[2022-09-27 13:00:32] frigate.events                 INFO    : Exiting event processor...
[2022-09-27 13:00:32] frigate.object_processing      INFO    : Exiting object processor...
[2022-09-27 13:00:32] frigate.record                 INFO    : Exiting recording maintenance...
[2022-09-27 13:00:32] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-09-27 13:00:32] root                           INFO    : Waiting for detection process to exit gracefully...
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 17 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cmd] python3 exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### FFprobe output from your camera

```shell
.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo100

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/3890

**Comment by JL500** [comment]
Yes! Switching off Protection mode did the job!
Thanks a lot, NickM-27
