### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by Jonnehs** [blakeblackshear/frigate#3956]
### Describe the problem you are having

Trying to move my hardware accelleration arguments from duplicates on every camera to the single ffmpeg global argument, but I'm getting an invalid ffmpeg error on start now...

### Version

0.10.1-83481AF

### Frigate config file

```yaml
mqtt:
  host: 10.25.1.15
  user: MQTT
  password: mqttpassword
birdseye:
  enabled: true
  width: 1280
  height: 720
  quality: 8
  mode: continuous
ffmpeg:
  hwaccel_args: -hwaccel qsv -qsv_device /dev/dri/renderD128
  output_args:
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
cameras:
  Front:
    rtmp:
      enabled: false
      inputs:
        - path: rtsp://frigate:frigatepassword@10.25.101.102:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:frigatepassword@10.25.101.102:554/h264Preview_01_main
          roles:
            - record
            - rtmp
    zones:
      frontgarden:
        coordinates: 0,205,154,204,356,178,535,159,607,116,640,138,640,480,0,480
    detect:
      width: 640
      height: 480
      fps: 7
      stationary:
        interval: 0
  Garage:
    rtmp:
      enabled: false
      inputs:
        - path: rtsp://frigate:frigatepassword@10.25.101.103:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:frigatepassword@10.25.101.103:554/h264Preview_01_main
          roles:
            - record
            - rtmp

    detect:
      width: 640
      height: 480
      fps: 7
      stationary:
        interval: 0
  Driveway:
    rtmp:
      enabled: false
      inputs:
        - path: rtsp://frigate:frigatepassword@10.25.101.101:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://frigate:frigatepassword@10.25.101.101:554/h264Preview_01_main
          roles:
            - record
            - rtmp
    zones:
      driveway:
        coordinates: 436,30,513,21,593,29,614,146,403,143
    detect:
      width: 640
      height: 480
      fps: 7
      stationary:
        interval: 0
motion:
  threshold: 40
  contour_area: 40
snapshots:
  enabled: true
  bounding_box: true
  retain:
    default: 60
record:
  enabled: True
  retain:
    days: 21
    mode: motion
  events:
    pre_capture: 20
    retain:
      default: 21
      mode: active_objects
      objects:
        person: 60
        car: 60
        motorcycle: 60
        dog: 10
        cat: 10
live:
  height: 720
  quality: 5
objects:
  track:
    - person
    - car
    - motorcycle
    - cat
    - dog
    - bird
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
[2022-09-27 14:19:49] frigate.app                    INFO    : Starting Frigate (0.10.1-83481af),
***    Your config file is not valid!                     ***,
***    Please check the docs at                           ***,
***    https://docs.frigate.video/configuration/index     ***,
***    Config Validation Errors                           ***,
Traceback (most recent call last):,
'ffmpeg',
  File "/opt/frigate/frigate/app.py", line 312, in start,
    self.init_config(),
    user_config = FrigateConfig.parse_file(config_file),
  File "/opt/frigate/frigate/app.py", line 77, in init_config,
  File "/opt/frigate/frigate/config.py", line 904, in parse_file,
    return cls.parse_obj(config),
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj,
  File "pydantic/main.py", line 329, in pydantic.main.BaseModel.__init__,
  File "pydantic/fields.py", line 856, in pydantic.fields.ModelField.validate,
  File "pydantic/main.py", line 1022, in pydantic.main.validate_model,
  File "pydantic/fields.py", line 991, in pydantic.fields.ModelField._validate_mapping_like,
  File "pydantic/fields.py", line 1064, in pydantic.fields.ModelField._validate_singleton,
  File "pydantic/fields.py", line 854, in pydantic.fields.ModelField.validate,
  File "pydantic/fields.py", line 1071, in pydantic.fields.ModelField._validate_singleton,
  File "pydantic/fields.py", line 1118, in pydantic.fields.ModelField._apply_validators,
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12,
  File "pydantic/main.py", line 676, in pydantic.main.BaseModel.validate,
  File "/opt/frigate/frigate/config.py", line 548, in __init__,
    if len(config["ffmpeg"]["inputs"]) == 1:,
KeyError: 'ffmpeg',
*************************************************************,
***    End Config Validation Errors                       ***
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
Your config is invalid. You have rtmp in the middle of your path declaration for the cameras. You still need the `ffmpeg` tag on each camera to define the cameras inputs. 

Here's an example from the docs

```yaml 

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp
          roles:
            - detect
            - rtmp

```

**Comment by Jonnehs** [comment]
ok thanks, i get what you mean, fixed
