### ISSUE TITLE
[Support]: once it decides a stationary object is a person, it just keeps alerting on it. forever.

### ISSUE THREAD

**Issue by stoneobscurity** [blakeblackshear/frigate#3965]
### Describe the problem you are having

once it decides a stationary object is a person, it just keeps alerting on it. forever.

this is already thinking my truck is person @ 75%.
i barely get 71% when i go in the yard,
so its not like i can adjust it.

restarting my frig stopped it. until the next time it thinks its a person.
like when a car headlight sweeps past again.

### Version

0.11.0

### Frigate config file

```yaml
cameras:
### amcrest 5mp starlight
  1_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://@:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://@:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
#      events:
#        required_zones:
#          - zone_street
#    zones:
#      zone_parking:
#        coordinates: 204,480,544,480,640,352,640,239,362,94,66,147
#        objects:
#          - person
#          - car
#      zone_street:
#        coordinates: 0,0,539,0,591,38,0,125
#        objects:
#          - car
#          - person
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 10
#      stationary:
#        interval: 0
#        threshold: 50
#        max_frames:
#          objects:
#            car: 500
    objects:
      track:
        - person
        - car
        - dog
    motion:
      mask:
        # tree
        - 506,110,529,32,498,25,487,118
        # timestamop
        #- 400,43,400,20,610,20,610,43
        # neighbors driveway
        - 640,0,338,0,357,39,640,105
#        # car
#        - 202,409,505,213,391,137,129,239
#      filters:
#        person:
#          mask:
#            - 0,0,438,0,435,22,0,117
#  ### reolink 820A
#  1_driveway:
#    ffmpeg:
#      inputs:
#        - path: rtsp://@:554/h265Preview_01_main
#          roles:
#            - record
#        - path: rtsp://@:554/h264Preview_01_sub
#          roles:
#            - detect
#            - rtmp
#    width: 640
#    height: 360
#    fps: 10
#    record:
#      enabled: True
#    detect:
#      enabled: True
#    objects:
#      track:
#        - person
#        - dog
#        - car
#  ### reolink 520
#  1_driveway:
#    ffmpeg:
#      inputs:
#        - path: rtmp:///bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=
#          roles:
#            - record
#        - path: rtmp:///bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password=
#          roles:
#            - detect
#            - rtmp
#      input_args:
#        - -avoid_negative_ts
#        - make_zero
#        - -fflags
#        - nobuffer
#        - -flags
#        - low_delay
#        - -strict
#        - experimental
#        - -fflags
#        - +genpts+discardcorrupt
#        - -rw_timeout
#        - '5000000'
#        - -use_wallclock_as_timestamps
#        - '1'
#    record:
#      enabled: True
#    detect:
#      enabled: True
#      width: 640
#      height: 480
#      fps: 10
#    objects:
#      track:
#        - person
#        - car
#        - dog
### amcrest 5mp starlight
  2_front_yard:
    ffmpeg:
      inputs:
        - path: rtsp://@:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://@:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 10
 #     stationary:
 #       interval: 0
 #       threshold: 50
 #       max_frames:
 #         objects:
 #           car: 500
    objects:
      track:
        - person
        - car
        - dog
      filters:
        person:
          min_score: 0.7
          threshold: 0.7
    motion:
      mask:
        # trees
        - 514,0,510,162,486,184,464,163,483,0
        - 357,0,354,86,325,87,322,0
        # neighbors driveway
        - 0,0,0,125,180,0
        # timestamop
        - 400,43,400,20,610,20,610,43
#      filters:
#        person:
#          mask:
#            - 186,27,99,26,95,0,640,0,640,32,572,31,493,30,420,29,355,30,284,30
### amcrest ad110 doorbell
  3_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://@:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://@:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      # record sound
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 10
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        #timestamp
        - 328,32,640,32,640,0,328,0
### reolink 520
  4_entry:
    ffmpeg:
      inputs:
#        - path: rtsp://@:554/h264Preview_01_main
#        - path: rtmp:///bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=
        - path: http:///flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
#        - path: rtsp://@:554/h264Preview_01_sub
#        - path: rtmp:///bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password=
        - path: http:///flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
            - rtmp
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      #width: 896
      #height: 672
      fps: 7
    objects:
      track:
        - person
        - dog
        - cat
        - bird
    motion:
      mask:
        #timestamp
        - 160,35,462,35,462,10,160,10
### reolink 520
  5_back_porch:
    ffmpeg:
      inputs:
#        - path: rtsp://@:554/h264Preview_01_main
#        - path: rtmp:///bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=
        - path: http:///flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
#        - path: rtsp://@:554/h264Preview_01_sub
#        - path: rtmp:///bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password=
        - path: http:///flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
            - rtmp
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      #width: 896
      #height: 672
      fps: 7
    objects:
      track:
        - person
        - dog
    motion:
      mask:
        #timestamp
        - 160,35,462,35,462,10,160,10
        #grill
        - 367,480,476,480,548,399,525,345,447,247,365,256,320,389
### reolink 520
  6_garage:
    ffmpeg:
      inputs:
#        - path: rtsp://@:554/h264Preview_01_main
#        - path: rtmp:///bcs/channel0_main.bcs?channel=0&stream=0&user=admin&password=
        - path: http:///flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
          roles:
            - record
#        - path: rtsp://@:554/h264Preview_01_sub
#        - path: rtmp:///bcs/channel0_sub.bcs?channel=0&stream=1&user=admin&password=
        - path: http:///flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
          roles:
            - detect
            - rtmp
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer+genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      #width: 896
      #height: 672
      fps: 7
    objects:
      track:
        - person
        - car
#        - dog
    motion:
      mask:
        #timestamp
        - 160,35,462,35,462,10,160,10
### d-link 920L ### old
#  6_garage:
#    ffmpeg:
#      inputs:
#        - path: http://@/video.cgi
##        - path: rtsp://:5001/live_stream
#          roles:
#            - record
#            - detect
#            - rtmp
#      input_args:
#        - -avoid_negative_ts
#        - make_zero
#        - -fflags
#        - nobuffer
#        - -flags
#        - low_delay
#        - -strict
#        - experimental
#        - -fflags
#        - +genpts+discardcorrupt
#        - -r
#        - '10'
#        - -use_wallclock_as_timestamps
#        - '1'
#      output_args:
#        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
#        clips: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v libx264 -an
#        rtmp: -c:v libx264 -an -f flv
#    width: 640
#    height: 480
#    fps: 10
#    record:
#      enabled: True
#    detect:
#      enabled: False
#    objects:
#      track:
#        - person
#        - car
### reolink e1 pro
  7_office:
    ffmpeg:
      inputs:
        - path: rtsp://@:554/h264Preview_01_main
          roles:
            - record
        - path: rtsp://@:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: False
      width: 640
      height: 352
      fps: 5
### reolink e1 pro
  8_kitchen:
    ffmpeg:
      inputs:
        - path: rtsp://@:554/h264Preview_01_main
          roles:
            - record
        - path: rtsp://@:554/h264Preview_01_sub
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: False
      width: 640
      height: 352
      fps: 5
#  ### reolink 520
#  8_test:
#    ffmpeg:
#      inputs:
#        - path: http:///flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=
#          roles:
#            - record
#        - path: http:///flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=
#          roles:
#            - detect
#            - rtmp
#      input_args:
#        - -avoid_negative_ts
#        - make_zero
#        - -fflags
#        - nobuffer+genpts+discardcorrupt
#        - -flags
#        - low_delay
#        - -strict
#        - experimental
#        - -analyzeduration
#        - 1000M
#        - -probesize
#        - 1000M
#        - -rw_timeout
#        - "5000000"
#    record:
#      enabled: True
#    detect:
#      enabled: True
#      width: 640
#      height: 480
#      fps: 10
#    objects:
#      track:
#        - person
detectors:
#  cpu1:
#    type: cpu
#  cpu2:
#    type: cpu
#  cpu3:
#    type: cpu
#  cpu4:
#    type: cpu
  coral_pci:
    type: edgetpu
    device: pci
logger:
  default: info
  logs:
    frigate.mqtt: error
record:
  retain_days: 9
  events:
    post_capture: 10
    pre_capture: 5
    retain:
      default: 9
      objects:
        person: 20
snapshots:
  enabled: True
  bounding_box: True
  crop: True
  height: 200
  retain:
    default: 3
motion:
  threshold: 20
birdseye:
  enabled: False
  quality: 1
  mode: continuous
### tessa
#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
### 1u server
#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p
rtmp:
  enabled: True
mqtt:
  host:
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: hass
  password:
```

### Relevant log output

```shell
INFO    : Starting Frigate (0.11.0-3846a13)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
cameras -> 2_front_yard -> filters
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 942, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
cameras -> 2_front_yard -> filters
  extra fields not permitted (type=value_error.extra)

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-27 22:49:07] frigate.app                    INFO    : Starting Frigate (0.11.0-3846a13)
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-09-27 22:49:07] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
Starting migrations
[2022-09-27 22:49:07] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-09-27 22:49:07] peewee_migrate                 INFO    : There is nothing to migrate
[2022-09-27 22:49:08] detector.coral_pci             INFO    : Starting detection process: 223
[2022-09-27 22:49:08] frigate.app                    INFO    : Output process started: 225
[2022-09-27 22:49:08] ws4py                          INFO    : Using epoll
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 1_driveway: 227
[2022-09-27 22:49:08] frigate.edgetpu                INFO    : Attempting to load TPU as pci
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 2_front_yard: 232
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 3_doorbell: 233
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 4_entry: 235
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 5_back_porch: 240
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 6_garage: 249
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 7_office: 251
[2022-09-27 22:49:08] frigate.app                    INFO    : Camera processor started for 8_kitchen: 252
[2022-09-27 22:49:08] frigate.edgetpu                INFO    : TPU found
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 1_driveway: 253
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 2_front_yard: 255
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 3_doorbell: 258
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 4_entry: 263
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 5_back_porch: 269
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 6_garage: 277
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 7_office: 285
[2022-09-27 22:49:08] frigate.app                    INFO    : Capture process started for 8_kitchen: 292
[2022-09-27 22:49:09] ws4py                          INFO    : Using epoll
[2022-09-27 22:49:29] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:44046]
[2022-09-27 22:51:21] ws4py                          INFO    : Terminating websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:44046]
[2022-09-27 22:51:25] ws4py                          INFO    : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:40840]
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

n/a

**Comment by blakeblackshear** [comment]
This is expected behavior. As long as Frigate continues to track an object, it will send "update" events to mqtt. You can use object filters to reduce false positives. You can also set max frames for person to turn off stationary object tracking, but lighting changes or other movement is likely to cause a redetection.

**Comment by blakeblackshear** [comment]
It thinks you have filters defined directly under the camera, so you have some kind of indentation issue.
