### ISSUE TITLE
[Camera Support]: green live feed when using custom.png

### ISSUE THREAD

**Issue by Tuurkevg** [blakeblackshear/frigate#3978]
### Describe the problem you are having

When I drop my own custom.png in my media/frigate folder all the camera's changes to a green feed after restarting.

### Version

0.11.0-3846a13

### Frigate config file

```yaml
no problems in my config
```

### Relevant log output

```shell
No errors or warnings in my logs
```

### FFprobe output from your camera

```shell
running correctly when not using my own custom.png for birdseye
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink

### Any other information that may be helpful

N/A

**Comment by Tuurkevg** [comment]
```shell
    [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-09-29 16:05:20] frigate.app INFO : Starting Frigate (0.11.0-3846a13)
[2022-09-29 16:05:20] frigate.app INFO : Creating directory: /tmp/cache
Starting migrations
[2022-09-29 16:05:20] peewee_migrate INFO : Starting migrations
There is nothing to migrate
[2022-09-29 16:05:20] peewee_migrate INFO : There is nothing to migrate
[2022-09-29 16:05:20] frigate.app INFO : Output process started: 216
[2022-09-29 16:05:20] ws4py INFO : Using epoll
[2022-09-29 16:05:20] detector.coral INFO : Starting detection process: 215
[2022-09-29 16:05:20] frigate.app INFO : Camera processor started for cam0: 225
[2022-09-29 16:05:20] frigate.app INFO : Camera processor started for cam1: 226
[2022-09-29 16:05:20] frigate.app INFO : Camera processor started for cam2: 230
[2022-09-29 16:05:20] frigate.app INFO : Camera processor started for cam3: 232
[2022-09-29 16:05:20] frigate.app INFO : Camera processor started for cam360: 233
[2022-09-29 16:05:20] frigate.app INFO : Capture process started for cam0: 235
[2022-09-29 16:05:20] frigate.app INFO : Capture process started for cam1: 237
[2022-09-29 16:05:20] frigate.app INFO : Capture process started for cam2: 243
[2022-09-29 16:05:20] frigate.app INFO : Capture process started for cam3: 249
[2022-09-29 16:05:20] frigate.app INFO : Capture process started for cam360: 254
Process output_processor:
Traceback (most recent call last):
File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/frigate/frigate/output.py", line 400, in output_frames
birdseye_manager = BirdsEyeFrameManager(config, frame_manager)
File "/opt/frigate/frigate/output.py", line 125, in __init__
self.blank_frame[
ValueError: could not broadcast input array from shape (1978,2708) into shape (629,698)
[2022-09-29 16:05:21] ws4py INFO : Using epoll
[2022-09-29 16:05:20] frigate.edgetpu INFO : Attempting to load TPU as usb
[2022-09-29 16:05:23] frigate.edgetpu INFO : TPU found
[2022-09-29 16:05:57] ws4py INFO : Managing websocket [Local => 127.0.0.1:5002 | Remote => 127.0.0.1:49238] 
```

**Comment by Tuurkevg** [comment]
> The png image is too large

Can you give me the max size?

**Comment by NickM-27** [comment]
Most likely depends on the birdseye resolution set

Based on the error in your logs:
> ValueError: could not broadcast input array from shape (1978,2708) into shape (629,698)

it needs to be smaller than 629x698

**Comment by Tuurkevg** [comment]
@NickM-27 I changed the size to the correct format but I get this error after it.
I set it to an lower resolution and also the resolution you gived me. Here the error
```shell
ValueError: could not broadcast input array from shape (459,629) into shape (629,459) 
```

**Comment by Tuurkevg** [comment]
> The default image is 180x180 so I would say start with that. It seems there may be some size requirements using the current logic that I was not aware of when adding this feature.

Alright thx, now it is working!
