### ISSUE TITLE
[EdgeTPU Support]: Coral USB not found

### ISSUE THREAD

**Issue by Frankenberrypi** [blakeblackshear/frigate#3984]
### Describe the problem you are having

I have a USB coral that doesn't seem to be working on a Home Assistant Supervised install.  I tried running the getting started example on coral.ai to make sure the hardware is functional and got the expected output.  Disabling the Coral and enabling a CPU detector in my frigate.yml file gets it running.  How do I get Frigate to recognize the Coral?

### Version

0.11.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.xxx
  user: xxxx
  password: xxxx

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu:
#    type: cpu
#    num_threads: 2
    
#Global Object Settings
objects:
  track:
    - person
    - dog
  filters:
    person:
      min_area: 5000
      max_area: 100000
    dog:
      min_area: 1000
      max_area: 50000

cameras:
  Test_cam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://192.168.3.61:8554/unicast
          roles:
            - record
            - rtmp
            - detect
    # hwaccel_args: -c:v h264_v412m2
    detect:
      width: 1280
      height: 720
    snapshots:
      enabled: True
    record:
      enabled: True
  Amcrest_01:
    ffmpeg:
      inputs:
        # Low resolution stream
        - path: rtsp://user:password@192.168.3.41:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - rtmp
            - detect
        # High Resolution Stream
        - path: rtsp://user:password@192.168.3.41:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 704
      height: 480
    snapshots:
      enabled: True
    record:
      enabled: True
```

### docker-compose file or Docker CLI command

```yaml
N/A, using the addon
```

### Relevant log output

```shell
[2022-09-29 22:16:10] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-09-29 22:16:15] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
See https://github.com/blakeblackshear/frigate/issues/3890

**Comment by Frankenberrypi** [comment]
Toggling protection mode off got it working.
