### ISSUE TITLE
[EdgeTPU Support]:  Frigate Crashing Due to Coral Accelerator

### ISSUE THREAD

**Issue by barans99** [blakeblackshear/frigate#4056]
### Describe the problem you are having

Frigate keeps crashing due to the Coral Accelerator and I cannot figure out why. At first it runs for a few mins but eventually crashes.

Tried different USB slots (3.0), rebooting host, rebooting server.

Running HAOS Bare metal.

Also noticed the LED on the coral itself flashes constantly once Frigate crashes, couldn't find any info on this.

### Version

Current version: 0.11.1 FA

### Frigate config file

```yaml
mqtt:
 host: 192.168.1.69
 port: 1883
 user: user
 password: pw
cameras:
  floorone:
    ffmpeg:
      inputs:
        - path: rtsp://admin:pw@192.168.1.87
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 10
objects:
  track:
     - person
     - dog
  filters:
    dog:
       threshold: 0.7
       min_area: 20000
       max_area: 100000
    person:
       threshold: 0.7
       min_area: 150000
       max_area: 600000
snapshots:
  enabled: True
  timestamp: false
  bounding_box: true
  retain:
    default: 3
record:
  enabled: true
  retain_days: 3
  events:
    retain:
      default: 3
detectors:
  coral:
    type: edgetpu
    device: usb
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
F driver/usb/usb_driver.cc:857] transfer on tag 0 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]
Fatal Python error: Aborted
Thread 0x00007f66a4ef1700 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
Thread 0x00007f66b2fa3740 (most recent call first):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke
  File "/opt/frigate/frigate/edgetpu.py", line 83 in detect_raw
  File "/opt/frigate/frigate/edgetpu.py", line 159 in run_detector
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/edgetpu.py", line 220 in start_or_restart
  File "/opt/frigate/frigate/edgetpu.py", line 189 in __init__
  File "/opt/frigate/frigate/app.py", line 217 in start_detectors
  File "/opt/frigate/frigate/app.py", line 360 in start
  File "/opt/frigate/frigate/__main__.py", line 16 in <module>
  File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
[2022-10-09 18:04:45] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-10-09 18:04:45] frigate.app                    INFO    : Stopping...
[2022-10-09 18:04:45] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-10-09 18:04:45] frigate.events                 INFO    : Exiting event cleanup...
[2022-10-09 18:04:45] frigate.watchdog               INFO    : Exiting watchdog...
[2022-10-09 18:04:45] frigate.stats                  INFO    : Exiting watchdog...
[2022-10-09 18:04:45] frigate.record                 INFO    : Exiting recording cleanup...
[2022-10-09 18:04:45] frigate.record                 INFO    : Exiting recording maintenance...
[2022-10-09 18:04:48] frigate.events                 INFO    : Exiting event processor...
[2022-10-09 18:04:48] frigate.object_processing      INFO    : Exiting object processor...
[2022-10-09 18:04:48] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-10-09 18:04:48] root                           INFO    : Waiting for detection process to exit gracefully...
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cmd] python3 exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
> Also noticed the LED on the coral itself flashes constantly once Frigate crashes, couldn't find any info on this.

This is normal, once the coral is engaged the light will blink when it is used.

What kind of device is your host?

**Comment by barans99** [comment]
> > Also noticed the LED on the coral itself flashes constantly once Frigate crashes, couldn't find any info on this.
> 
> This is normal, once the coral is engaged the light will blink when it is used.
> 
> What kind of device is your host?

It is a mini Dell Optiplex, i5 6500T 4c/4t CPU, 8GB RAM, 1tb Samsung Evo 860 SSD.

**Comment by NickM-27** [comment]
Hm, seems like it is a power delivery issue most likely. As explained in https://github.com/google-coral/edgetpu/issues/11#issuecomment-541850331 the coral will draw more power as it gets hotter (to a certain point, up to 900 mA) which is likely why it fails after some time.

**Comment by barans99** [comment]
> Hm, seems like it is a power delivery issue most likely. As explained in [google-coral/edgetpu#11 (comment)](https://github.com/google-coral/edgetpu/issues/11#issuecomment-541850331) the coral will draw more power as it gets hotter (to a certain point, up to 900 mA) which is likely why it fails after some time.

Makes sense, would it likely be a limitation of the power supply itself or the adapter (it's 90w).

Alternatively, would a powered usb hub work?

**Comment by NickM-27** [comment]
It would be a limitation of either the USB port or the motherboard / power supply. And yes a powered USB hub is the recommendation to try, just be sure it can support the noted 900 mA draw at 5V

**Comment by barans99** [comment]
I got a powered USB hub, however, Frigate doesn't seem to detect coral accelerator when it's plugged into the USB hub.

Is there a configuration I need to configure for this to work?

**Comment by NickM-27** [comment]
Which version of the addon are you running? (Normal or full access?)

**Comment by barans99** [comment]
> Which version of the addon are you running? (Normal or full access?)

Frigate Full Access, protection mode off as suggested in a similar thread.

**Comment by barans99** [comment]
> Have you tried different cables?

Yes, both USB 3.0 to USB C.

**Comment by NickM-27** [comment]
Are you on haos 9?

**Comment by NickM-27** [comment]
That's core versioning, ha os has a different version scheme

**Comment by barans99** [comment]
> 

Sorry, 9.0 HAOS.

**Comment by barans99** [comment]
I managed to get it to run again but crashed after 5 mins, LED on the accelerator is flashing.

F driver/usb/usb_driver.cc:857] transfer on tag 0 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]
Fatal Python error: Aborted
Thread 0x00007fef3ed2d700 (most recent call first):
  File "/usr/lib/python3.9/threading.py", line 312 in wait
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
  File "/usr/lib/python3.9/threading.py", line 892 in run
  File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
  File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
Thread 0x00007fef4cddf740 (most recent call first):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke
  File "/opt/frigate/frigate/edgetpu.py", line 83 in detect_raw
  File "/opt/frigate/frigate/edgetpu.py", line 159 in run_detector
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
  File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
  File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
  File "/opt/frigate/frigate/edgetpu.py", line 220 in start_or_restart
  File "/opt/frigate/frigate/edgetpu.py", line 189 in __init__
  File "/opt/frigate/frigate/app.py", line 217 in start_detectors
  File "/opt/frigate/frigate/app.py", line 360 in start
  File "/opt/frigate/frigate/__main__.py", line 16 in <module>
  File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
[2022-10-10 20:25:45] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
[2022-10-10 20:25:45] detector.coral                 INFO    : Starting detection process: 530
[2022-10-10 20:25:45] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2022-10-10 20:25:51] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-10-10 20:25:55] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2022-10-10 20:25:55] frigate.app                    INFO    : Stopping...
[2022-10-10 20:25:55] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2022-10-10 20:25:55] frigate.events                 INFO    : Exiting event cleanup...
[2022-10-10 20:25:55] frigate.stats                  INFO    : Exiting watchdog...
[2022-10-10 20:25:55] frigate.record                 INFO    : Exiting recording maintenance...
[2022-10-10 20:25:55] frigate.watchdog               INFO    : Exiting watchdog...
[2022-10-10 20:25:55] frigate.record                 INFO    : Exiting recording cleanup...
[2022-10-10 20:25:55] frigate.object_processing      INFO    : Exiting object processor...
[2022-10-10 20:25:56] frigate.events                 INFO    : Exiting event processor...
[2022-10-10 20:25:56] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2022-10-10 20:25:56] root                           INFO    : Waiting for detection process to exit gracefully...
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cmd] python3 exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by Cardy165** [comment]
Just a thought but it mentions deadline exceeded could something else plugged into USB be locking up the controller on the host causing the deadline exceeded ?

**Comment by barans99** [comment]
> Just a thought but it mentions deadline exceeded could something else plugged into USB be locking up the controller on the host causing the deadline exceeded ?

Thanks Cardy, no other USB is plugged in :(

**Comment by Cardy165** [comment]
Only other things I can suggest would be 

- Check the motherboard firmware is up-to-date in case there was a firmware patch for motherboard issues to do with the controller
- trying a dedicated USB card in a PCI/PCIe slot
