### ISSUE TITLE
[Support]: TypeError: Cannot read properties of undefined (reading 'day') when there are no recordings

### ISSUE THREAD

**Issue by madmac2501** [blakeblackshear/frigate#4059]
### Describe the problem you are having

Hi,

I'm getting this error in the browser console when I click on the recordings of a camera with no recordings.

Recording.2e01e5c8.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'day')
    at Recording.2e01e5c8.js:1:33835
    at En (vendor.153a2319.js:1:12519)
    at T.kr [as constructor] (Recording.2e01e5c8.js:1:33770)
    at T._i [as render] (vendor.153a2319.js:1:8095)
    at Bt (vendor.153a2319.js:1:5822)
    at vendor.153a2319.js:1:1528
    at Array.some (<anonymous>)
    at Je (vendor.153a2319.js:1:1426)

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
Recording.2e01e5c8.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'day')
    at Recording.2e01e5c8.js:1:33835
    at En (vendor.153a2319.js:1:12519)
    at T.kr [as constructor] (Recording.2e01e5c8.js:1:33770)
    at T._i [as render] (vendor.153a2319.js:1:8095)
    at Bt (vendor.153a2319.js:1:5822)
    at vendor.153a2319.js:1:1528
    at Array.some (<anonymous>)
    at Je (vendor.153a2319.js:1:1426)
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
Fixed in https://github.com/blakeblackshear/frigate/pull/4069
