### ISSUE TITLE
[Support]: python errors after upgrading to 0.11.1

### ISSUE THREAD

**Issue by lazyjai** [blakeblackshear/frigate#4075]
### Describe the problem you are having

Getting ffmpeg/python errors after upgrading docker image to 0.11.1. Going back to previous major relese restores most functionality. pulling the newest frigate:stable image from docker. Looks like ffmpeg isn't found inside the container? Tested by pulling both :stable and :0.11.1 tagged images.

[PATH] in config below has replaced my actual rtsp path.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 10.8.10.23
  port: 1883
  user: mqtt-ha
  password: mqtt-ha

detectors:
  coral:
    type: edgetpu
    device: usb
#  cpu1:
#    type: cpu
#    num_threads: 4

birdseye:
  enabled: True

ffmpeg:
  global_args: -an
  hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
    rtmp: -c:v copy -f flv -ar 44100 -c:a aac

detect:
  enabled: True

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default: 180

snapshots:
  enabled: True
  retain:
    default: 180

timestamp_style:
  position: "bl"
  thickness: 1
  effect: "shadow"

cameras:
  front_door_ai:
    ffmpeg:
      inputs:
        - path: [PATH]
          roles:
          - detect
          - record
    detect:
      width: 1600
      height: 1200
    rtmp:
      enabled: False
    zones:
      front_steps_ai:
        coordinates: 797,0,1600,0,1600,1200,747,1200,684,1066,667,911,759,696
        objects:
          - person
        filters:
          person:
            min_area: 10000
            threshold: 0.7
  patio_door_ai:
    ffmpeg:
      inputs:
        - path: [PATH]
          roles:
          - detect
          - record
    detect:
      width: 1600
      height: 1200
    rtmp:
      enabled: False
  dining_room_ai:
    ffmpeg:
      inputs:
        - path: [PATH]
          roles:
          - detect
          - record
    detect:
      width: 1920
      height: 1080
    rtmp:
      enabled: False
  living_room_ai:
    ffmpeg:
      inputs:
        - path: [PATH]
          roles:
          - detect
          - record
    detect:
      width: 1920
      height: 1080
    rtmp:
      enabled: False
  office_ai:
    ffmpeg:
      inputs:
        - path: [PATH]
          roles:
          - detect
    detect:
      width: 1920
      height: 1080
    rtmp:
      enabled: False
  office_ai:
    ffmpeg:
      inputs:
        - path: [PATH]
          roles:
          - detect
          - record
    detect:
      width: 1920
      height: 1080
    rtmp:
      enabled: False
  garage_ai:
    ffmpeg:
      inputs:
        - path: [PATH]
          roles:
          - detect
          - record
    detect:
      width: 1920
      height: 1080
    rtmp:
      enabled: False
```

### Relevant log output

```shell
[2022-10-13 03:11:35] frigate.app                    INFO    : Capture process started for patio_door_ai: 238
[2022-10-13 03:11:35] frigate.app                    INFO    : Capture process started for dining_room_ai: 241
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
[2022-10-13 03:11:35] frigate.app                    INFO    : Capture process started for living_room_ai: 245
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
[2022-10-13 03:11:35] frigate.app                    INFO    : Capture process started for office_ai: 249
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
[2022-10-13 03:11:35] frigate.app                    INFO    : Capture process started for garage_ai: 253
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/frigate/frigate/video.py", line 215, in run
    self.start_ffmpeg_detect()
  File "/opt/frigate/frigate/video.py", line 276, in start_ffmpeg_detect
    self.ffmpeg_detect_process = start_or_restart_ffmpeg(
  File "/opt/frigate/frigate/video.py", line 133, in start_or_restart_ffmpeg
    process = sp.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

### FFprobe output from your camera

```shell
bash: ffprobe: command not found
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi flex 3 and g4 doorbell

**Comment by blakeblackshear** [comment]
Check the release notes. My guess is that you are using Portainer which stores and then overrides the PATH environment variable for some crazy reason.

**Comment by NickM-27** [comment]
Please read the release notes, this is explained in the breaking changes section

> Some deployment approaches are overwriting the PATH environment value to an old value. If you see errors like No such file or directory: 'ffmpeg', then you need to stop overriding your PATH. This happens with both Proxmox LXC and Portainer (#3223)

**Comment by lazyjai** [comment]
Got it thanks. Didn't see any changelog documentation on the docs.frigate.video site so unsure where to find the the release notes for future reference.

Cheers.
