### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by newness0** [blakeblackshear/frigate#4143]
### Describe the problem you are having

Couldn't get frigate to start. ffmpeg config error

### Version

NA

### Frigate config file

```yaml
mqtt:
  host: localhost
  port: 1883

cameras:
  camera_1: living 
    ffmpeg:
      inputs:
        - path: rtsp://192.168.30.170:8554/unicast 
          roles:
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camer
```

### Relevant log output

```shell
sudo docker logs frigate
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-10-21 14:19:00] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
mapping values are not allowed here
  in "<unicode string>", line 7, column 11:
        ffmpeg:
              ^
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 938, in parse_file
    config = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 7, column 11:
        ffmpeg:
              ^

*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
[cmd] python3 exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

`version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
#    devices:
    #  - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
#      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/xxxx/Pictures/frigate/config.yml:/config/config.yml:ro
      - /home/xxxx/Pictures/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
`

**Comment by NickM-27** [comment]
Please read the docs for setup: https://docs.frigate.video/guides/getting_started

```yaml
mqtt:
  host: localhost
  port: 1883

cameras:
  camera_1: living  # <--- is not valid, you must just name the camera as living
    ffmpeg:
```

**Comment by newness0** [comment]
> 

Did that already. If you see my config file, it simply says living

**Comment by newness0** [comment]
> Please read the docs for setup: https://docs.frigate.video/guides/getting_started
> 
> ```yaml
> mqtt:
>   host: localhost
>   port: 1883
> 
> cameras:
>   camera_1: living  # <--- is not valid, you must just name the camera as living
>     ffmpeg:
> ```

Did that already. If you see my config file, it simply says living

**Comment by NickM-27** [comment]
You did it incorrectly, iyou want the camera to be called living then it would be:

```yaml
mqtt:
  host: localhost
  port: 1883

cameras:
  living:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.30.170:8554/unicast 
          roles:
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camer
```

**Comment by newness0** [comment]
> You did it incorrectly, if you want the camera to be called living then it would be:
> 
> ```yaml
> mqtt:
>   host: localhost
>   port: 1883
> 
> cameras:
>   living:
>     ffmpeg:
>       inputs:
>         - path: rtsp://192.168.30.170:8554/unicast 
>           roles:
>             - rtmp
>     rtmp:
>       enabled: False # <-- RTMP should be disabled if your stream is not H264
>     detect:
>       width: 1280 # <---- update for your camera's resolution
>       height: 720 # <---- update for your camer
> ```

Yes, just realized and it seems to be good now

**Comment by NickM-27** [comment]
Great, if that fixed it then I'll go ahead and close this. Feel free to create a new issue if something else comes up 👍
