### ISSUE TITLE
[Config Support]: M.2 Coral recognized inside HASS addon

### ISSUE THREAD

**Issue by agrieco** [blakeblackshear/frigate#4358]
### Describe the problem you are having

Summary:
Frigate Addon for a supervised install of Home Assistant isn't recognizing my M.2 Coral.

Background:
I've got a working Frigate install running via docker-compose that uses my M.2 Coral.  Works great and has for a while.  It is running on the same host as a supervised install of Home Assistant (ie Debian host in the HASS quasi-supported mode).  With the recent changes to Home Assistant, even in this mode, the fact that there is another container running on the same system that isn't managed by HA is a problem.  

So- I figured- easy enough- take my working config and run it via the official Addon.  

Unfortunately, the addon isn't recognizing the Coral.  Mind you, the drivers are there on the underlying host and it works great in its own independent container.

I was able to log into the addon_ccab4aaf_frigate-fa-beta container (version 0.11.1) and quickly install lspci prior to it stopping and can see that even from within the addon, the Coral is seen:

```
docker exec -it addon_ccab4aaf_frigate-fa-beta /bin/bash
....
root@ccab4aaf-frigate-fa-beta:/opt/frigate# lspci
<other stuff>
01:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU
<other stuff>

The Addon is running with "protection" OFF. 

Any help woudl be appreciated. 


### Version

0.11.1

### Frigate config file

```yaml
detectors:
  coral1:
    type: edgetpu
    device: pci:0
```

### Relevant log output

```shell
[services.d] starting services
[services.d] done.
[2022-11-09 11:37:53] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2022-11-09 11:37:53] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-11-09 11:37:53] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-11-09 11:37:53] peewee_migrate                 INFO    : There is nothing to migrate
[2022-11-09 11:37:54] frigate.app                    INFO    : Output process started: 218
[2022-11-09 11:37:54] frigate.app                    INFO    : Camera processor started for Driveway: 222
[2022-11-09 11:37:54] ws4py                          INFO    : Using epoll
[2022-11-09 11:37:54] frigate.app                    INFO    : Camera processor started for BackDeck: 226
[2022-11-09 11:37:54] frigate.app                    INFO    : Camera processor started for DadGarage: 229
Process detector:coral1:
[2022-11-09 11:37:54] detector.coral1                INFO    : Starting detection process: 216
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-11-09 11:37:54] frigate.edgetpu                INFO    : Attempting to load TPU as pci:0
[2022-11-09 11:37:54] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

M.2

**Comment by NickM-27** [comment]
Have you disabled protected mode for the addon?

**Comment by agrieco** [comment]
> Have you disabled protected mode for the addon?

Yes.

**Comment by NickM-27** [comment]
If the other frigate is running that it is likely causing issues by having access as only one device can access it at a time.

**Comment by agrieco** [comment]
> If the other frigate is running that it is likely causing issues by having access as only one device can access it at a time.

Bingo.  Machine rebooted and the container restarted.  Now that I've stopped it, addon starts perfectly.  Ugh.  Thanks for pointing this out...should have checked it!

**Comment by NickM-27** [comment]
Glad that worked, feel free to create a new issue if something else comes up.
