### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by mikey6283** [blakeblackshear/frigate#4478]
### Describe the problem you are having

 Recently  my area had a broadband outage and  caused my switches to malfunction , after replacing the  units  i am now unable to load my config.

 Any guidance would be appreciated.

### Version

unable to load but was  latest 

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.15
  user: mikey
  password: mqtt6283

detectors:
  coral1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db

birdseye:
  enabled: True
  mode: objects

objects:
  track:
    - person

record:
  enabled: True
  retain:
    days: 0
  events:
    retain:
      default:  10

cameras:
  Back_garden:
    ffmpeg:
      hwaccel_args: -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: http://192.168.0.17/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=BGarden1
          roles:
            - record
            - rtmp
        - path: http://192.168.0.17/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=BGarden1
          roles:
            - detect

    detect:
      width: 896
      height: 672
      fps: 5

  front:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: http://192.168.0.48/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Front1
          roles:
            - record
            - rtmp
        - path: http://192.168.0.48/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Front1
          roles:
            - detect

    detect:
      width: 896
      height: 672
      fps: 5

  garage:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: http://192.168.0.14/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Garage1
          roles:
            - record
            - rtmp
        - path: http://192.168.0.14/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Garage1
          roles:
            - detect

    detect:
      width: 896
      height: 672
      fps: 5
  koipond:
    ffmpeg:
      hwaccel_args: -c:v h264_qsv -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format yuv420p
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
        - -rw_timeout
        - "5000000"
      output_args:
        record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: http://192.168.0.16/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Koipond1
          roles:
            - record
            - rtmp
        - path: http://192.168.0.16/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Koipond1
          roles:
            - detect
    detect:
      width: 896
      height: 672
      fps: 5
```

### Relevant log output

```shell
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
while parsing a block mapping
  in "<unicode string>", line 141, column 5:
        ffmpeg:
        ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 158, column 6:
         output_args:
         ^
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 332, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 82, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 938, in parse_file
    config = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 141, column 5:
        ffmpeg:
        ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 158, column 6:
         output_args:
         ^
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

M.2

**Comment by NickM-27** [comment]
What version of frigate are you pulling via unraid?

**Comment by mikey6283** [comment]
> 
blakeblackshear/frigate:stable

**Comment by mikey6283** [comment]
> > 
> 
> blakeblackshear/frigate:stable

Latest version installed  2 weeks ago

**Comment by NickM-27** [comment]
You might want to try retyping or otherwise creating a new file, from what I can tell everything looks fine but there may be some corrupt character or something.

**Comment by mikey6283** [comment]
I am at work now so i'll have ago tonight/ tomorrow. 
Thanks
