### ISSUE TITLE
[EdgeTPU Support]: No EdgeTPU was detected

### ISSUE THREAD

**Issue by Rowleys** [blakeblackshear/frigate#4569]
### Describe the problem you are having

Hi, Frigate now says No EdgeTPU was detected. I have a PCI / M.2 The Boards LED are on showing they are working, 

Everything was working fine. Maybe there is an update :( .

I have the the pci slot as well & changed 

pci:0 to pci:1

I have disabled Protection mode .. 

Hope someone can help. 

Thanks 

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.172
  user: mqtt
  password: ....
  
objects:
  track:
    - person
  
  
cameras: 
  Livingroomcam: 
    ffmpeg: 
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs: 
        - path: rtsp://192.168.1.93:8554/unicast
          roles: 
            - detect
    detect:
      width: 1280
      height: 720
      fps: 4
    objects:
      track:
        - person
        - dog
  
 
  front: 
    rtmp:
      enabled: False
    ffmpeg: 
      input_args: -avoid_negative_ts make_zero -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs: 
        - path: rtsp://admin:....@192.168.1.231:554/Streaming/Channels/101/
          roles: 
            - detect
    detect:
      width: 2688
      height: 1520
      fps: 4
    objects:
      track:
        - person
        - car
      filters:
        person:
          min_area: 5000
          max_area: 100000
          threshold: 0.65
    zones:
      vans:
        coordinates: 1638,1520,1555,1194,1543,1015,1540,836,1530,701,1521,586,1513,481,1501,370,1496,297,1479,243,1454,164,1398,120,1324,132,1212,135,1096,208,952,476,856,611,748,807,677,993,464,1520
      frontdoor:
        coordinates: 449,1520,476,1202,468,1177,397,1145,351,1167,314,1221,299,1256,258,1337,228,1383,201,1445,162,1520
      Djvan:
        coordinates: 1422,522,1555,544,1597,743,1692,1520,1427,596,1430,643,1550,706,1592,819,1616,979,1616,1077,1714,1520,1628,1520,1459,1520,1359,1520,1194,1520,1096,1520,1028,1520,942,1520,851,1520,733,1520,743,1327,802,1275
      grovedrive:
        coordinates: 1126,42,625,189,537,326,726,329,1229,353,1457,388,1692,388,2048,341,2308,319,2183,184


birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 15
  mode: motion
  
ffmpeg:
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 30 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    rtmp: -c copy -f flv
            
            
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25

  
live:
  height: 720
  quality: 8
  
timestamp_style:
  position: "tl"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    # All Required when color is specified (default: shown below)
    red: 255
    green: 255
    blue: 255
  thickness: 2
  effect: solid
  
detectors:
  coral1:
    type: edgetpu
    device: pci:1
       
record:
  enabled: True
  retain_days: 10
  events:
    retain:
      default: 10
      
environment_vars:
  PLUS_API_KEY: ...
```

### docker-compose file or Docker CLI command

```yaml
No Idea what this is ..
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-12-01 09:27:30] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2022-12-01 09:27:30] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-12-01 09:27:30] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
[2022-12-01 09:27:30] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2022-12-01 09:27:30] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2022-12-01 09:27:30] peewee_migrate                 INFO    : There is nothing to migrate
[2022-12-01 09:27:30] frigate.app                    INFO    : Output process started: 217
[2022-12-01 09:27:30] ws4py                          INFO    : Using epoll
[2022-12-01 09:27:30] frigate.app                    INFO    : Camera processor started for Livingroomcam: 222
[2022-12-01 09:27:30] frigate.app                    INFO    : Camera processor started for front: 223
[2022-12-01 09:27:30] frigate.app                    INFO    : Capture process started for Livingroomcam: 224
[2022-12-01 09:27:30] detector.coral1                INFO    : Starting detection process: 216
[2022-12-01 09:27:30] frigate.app                    INFO    : Capture process started for front: 228
[2022-12-01 09:27:30] frigate.edgetpu                INFO    : Attempting to load TPU as pci:1
Process detector:coral1:
[2022-12-01 09:27:30] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2022-12-01 09:27:30] frigate.video                  ERROR   : front: Unable to read frames from ffmpeg process.
[2022-12-01 09:27:30] frigate.video                  ERROR   : front: ffmpeg process is not running. exiting capture thread...
[2022-12-01 09:27:30] frigate.video                  ERROR   : Livingroomcam: Unable to read frames from ffmpeg process.
[2022-12-01 09:27:30] frigate.video                  ERROR   : Livingroomcam: ffmpeg process is not running. exiting capture thread...
[2022-12-01 09:27:30] ws4py                          INFO    : Using epoll
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

**Comment by NickM-27** [comment]
pci:1 is only if you have multiple. Disabling protection mode is all it should take, unless HA OS messed the driver up in the latest update. 

What do you see in the hardware devices section of HA OS? Should see it there

**Comment by Rowleys** [comment]
> pci:1 is only if you have multiple. Disabling protection mode is all it should take, unless HA OS messed the driver up in the latest update.
> 
> What do you see in the hardware devices section of HA OS? Should see it there

Hi, I have not got it working. No idea how but it's not detected. 

I now have this error 

[2022-12-01 09:48:41] frigate.edgetpu                INFO    : TPU found
[2022-12-01 09:48:42] frigate.video                  ERROR   : Livingroomcam: Unable to read frames from ffmpeg process.
[2022-12-01 09:48:42] frigate.video                  ERROR   : Livingroomcam: ffmpeg process is not running. exiting capture thread...
[2022-12-01 09:48:42] frigate.video                  ERROR   : front: Unable to read frames from ffmpeg process.
[2022-12-01 09:48:42] frigate.video                  ERROR   : front: ffmpeg process is not running. exiting capture thread...

**Comment by NickM-27** [comment]
Need more log than that to understand the error. Let frigate run for a minute then paste the logs

**Comment by blakeblackshear** [comment]
As stated in the release notes, you need to change stimeout to timeout in your input args.
