### ISSUE TITLE
[Config Support]: Birdseye with empty - full transparent - custom.png image failing

### ISSUE THREAD

**Issue by dough29** [blakeblackshear/frigate#4633]
### Describe the problem you are having

I made a PNG full transparency and no pixel in color : I want the Birdseye screen full black when there is nothing to show.

### Version

0.11.1

### Frigate config file

```yaml
Base64 encoded file : iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAQAAACXxM65AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QAAKqNIzIAAAAJcEhZcwAAAEgAAABIAEbJaz4AAAAHdElNRQfmDAcTNgdd9p54AAAAbElEQVR42u3OAREAEBQFsNdFCRXUFU2BL4XjzpZgSaWyMsJhlZl2O/GDfjsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPCYDZRXBUa+lR+QAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTEyLTA3VDE5OjUyOjM5KzAwOjAwusm/YQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0xMi0wN1QxOTo1MjozOSswMDowMMuUB90AAAAASUVORK5CYII=
```

### Relevant log output

```shell
Process output_processor:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/output.py", line 400, in output_frames
    birdseye_manager = BirdsEyeFrameManager(config, frame_manager)
  File "/opt/frigate/frigate/output.py", line 122, in __init__
    transparent_layer = birdseye_logo[:, :, 3]
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Maybe try an all black image and see how that works

**Comment by dough29** [comment]
@NickM-27 you mean PNG with transparency and fill with black ?

When filling with black I have the same error, have to leave at least one pixel in transparent... and every non transparent pixel become white on Frigate

**Comment by dough29** [comment]
Hello, I'm still facing this issue with latest 0.14.0 release.

As I'm displaying the birdseye view 24/7 on a tablet screen, I'm in the need that the image is 100% black pixels when there is no motion to show.

A full transparent PNG file would make Frigate crash for now.

Or is it possible to add a "no_logo" option for the birdseye view ?
