### ISSUE TITLE
Unhandled expection when camera doesn't have a detect role

### ISSUE THREAD

**Issue by natm** [blakeblackshear/frigate#482]
**Describe the bug**
One camera at home is in a wooded area, I don't need object detection enabled, but would like to proxy it via Frigate for RTMP access via the common URL. Exception in logs is thrown when starting up.

**Version of frigate**
0.8.0-444fa45

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
cameras:
  polewoods:
    ffmpeg:
      inputs:
        - path: rtsp://10.76.31.2:554/Streaming/Channels/1/
          roles:
            - rtmp
    width: 704
    height: 576
    fps: 6

```

**Logs**
```
2021-01-06T18:13:27.372287806Z frigate.app                    INFO    : Capture process started for logsnorth: 115
2021-01-06T18:13:27.376754572Z frigate.app                    INFO    : Capture process started for utility: 120
2021-01-06T18:13:27.380969072Z frigate.app                    INFO    : Capture process started for rear: 124
2021-01-06T18:13:27.385810466Z frigate.app                    INFO    : Capture process started for polewoods: 131
2021-01-06T18:13:27.393832431Z Exception in thread Thread-3:
2021-01-06T18:13:27.393936355Z Traceback (most recent call last):
2021-01-06T18:13:27.393970437Z   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-01-06T18:13:27.395054653Z     self.run()
2021-01-06T18:13:27.395301611Z   File "/opt/frigate/frigate/video.py", line 157, in run
2021-01-06T18:13:27.395583491Z     self.start_ffmpeg_detect()
2021-01-06T18:13:27.395618691Z   File "/opt/frigate/frigate/video.py", line 204, in start_ffmpeg_detect
2021-01-06T18:13:27.395894424Z     ffmpeg_cmd = [c['cmd'] for c in self.config.ffmpeg_cmds if 'detect' in c['roles']][0]
2021-01-06T18:13:27.395948062Z IndexError: list index out of range
2021-01-06T18:13:27.396286373Z frigate.app                    INFO    : Capture process started for officetest: 136
2021-01-06T18:13:30.713694772Z frigate.edgetpu                INFO    : Attempting to load TPU as usb
2021-01-06T18:13:30.719201894Z frigate.edgetpu                INFO    : TPU found
2021-01-06T18:14:27.382895730Z frigate.app                    INFO    : Stopping...
2021-01-06T18:14:27.388255068Z frigate.object_processing      INFO    : Exiting object processor...
2021-01-06T18:14:30.613788617Z  * Starting nginx nginx
2021-01-06T18:14:30.621267778Z    ...done.
2021-01-06T18:14:31.909864880Z frigate.mqtt                   INFO    : MQTT connected
2021-01-06T18:14:31.928600214Z detector.coral1                INFO    : Starting detection process: 48
```

**Frigate debug stats**
```
{"barnleft":{"camera_fps":6.1,"capture_pid":72,"detection_fps":2.4,"pid":55,"process_fps":2.2,"skipped_fps":0.0},"barnright":{"camera_fps":6.0,"capture_pid":77,"detection_fps":0.0,"pid":57,"process_fps":6.1,"skipped_fps":0.0},"bridge":{"camera_fps":6.1,"capture_pid":69,"detection_fps":0.0,"pid":53,"process_fps":6.1,"skipped_fps":0.0},"detection_fps":7.1,"detectors":{"coral1":{"detection_start":1609957010.522863,"inference_speed":131.77,"pid":48}},"driveeast":{"camera_fps":6.1,"capture_pid":103,"detection_fps":0.0,"pid":61,"process_fps":6.1,"skipped_fps":0.0},"drivenorth":{"camera_fps":6.0,"capture_pid":68,"detection_fps":0.0,"pid":51,"process_fps":6.0,"skipped_fps":0.0},"drivewest":{"camera_fps":6.1,"capture_pid":96,"detection_fps":0.0,"pid":60,"process_fps":6.1,"skipped_fps":0.0},"logsnorth":{"camera_fps":6.1,"capture_pid":119,"detection_fps":0.0,"pid":63,"process_fps":6.1,"skipped_fps":0.0},"logssouth":{"camera_fps":6.1,"capture_pid":112,"detection_fps":0.0,"pid":62,"process_fps":6.1,"skipped_fps":0.0},"officetest":{"camera_fps":6.0,"capture_pid":134,"detection_fps":2.3,"pid":66,"process_fps":2.3,"skipped_fps":0.0},"polewoods":{"camera_fps":0.0,"capture_pid":139,"detection_fps":0.0,"pid":67,"process_fps":0.0,"skipped_fps":0.0},"rear":{"camera_fps":6.1,"capture_pid":130,"detection_fps":2.4,"pid":65,"process_fps":1.5,"skipped_fps":0.0},"service":{"uptime":100,"version":"0.8.0-444fa45"},"shed":{"camera_fps":6.0,"capture_pid":91,"detection_fps":0.0,"pid":59,"process_fps":6.0,"skipped_fps":0.0},"utility":{"camera_fps":6.1,"capture_pid":124,"detection_fps":0.0,"pid":64,"process_fps":6.1,"skipped_fps":0.0},"workshop":{"camera_fps":6.0,"capture_pid":82,"detection_fps":0.0,"pid":58,"process_fps":6.0,"skipped_fps":0.0}}
```

**Comment by blakeblackshear** [comment]
I hadn't considered that use case. I will look into how I can handle it.

**Comment by blakeblackshear** [comment]
This should be resolved in RC1. You must use the detect role, but you can disable detection.
