### ISSUE TITLE
[Support]: 0.12.0 Beta 1 camera x "has restream enabled, but restream is not assigned to an input."

### ISSUE THREAD

**Issue by LaurenceGough** [blakeblackshear/frigate#4862]
### Describe the problem you are having

Hello,

I upgraded to 0.12.0 Beta 1 just now from the last Frigate 0.11 release.

Unfortunately my Frigate now won't boot due to the following error:

Camera x "has restream enabled, but restream is not assigned to an input."

Which is weird as I don't have restream enabled as I don't use it. I have tried removing the camera from the config then it just moves onto the next camera.

I have tried adding the rtmp role as an input option but no difference. 
I have tried commenting out any ffmpeg options in the config.

I have also tried adding the following to my config with no luck:
rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False

Running on a Raspberry Pi 4 container via Portainer (the path variable that is set by Portainer has been removed)

Thank you

### Version

0.12.0 Beta 1

### Frigate config file

```yaml
cam1:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxxxx
          roles:
            - detect
        - path: rtsp://xxxxxxxxxxxxxxxxx
          roles:
            - record
```

### Relevant log output

```shell
2023-01-02 21:32:09.228447160  [2023-01-02 21:32:09] frigate.app                    INFO    : Starting Frigate (0.12.0-53d39a1)
2023-01-02 21:32:09.338680956  *************************************************************
2023-01-02 21:32:09.338693771  *************************************************************
2023-01-02 21:32:09.338706178  ***    Your config file is not valid!                     ***
2023-01-02 21:32:09.338711271  ***    Please check the docs at                           ***
2023-01-02 21:32:09.338714308  ***    https://docs.frigate.video/configuration/index     ***
2023-01-02 21:32:09.340725474  *************************************************************
2023-01-02 21:32:09.340737808  *************************************************************
2023-01-02 21:32:09.340740530  ***    Config Validation Errors                           ***
2023-01-02 21:32:09.340743048  *************************************************************
2023-01-02 21:32:09.340746030  Camera cam1 has restream enabled, but restream is not assigned to an input.
2023-01-02 21:32:09.342366456  Traceback (most recent call last):
2023-01-02 21:32:09.342378011    File "/opt/frigate/frigate/app.py", line 335, in start
2023-01-02 21:32:09.342379974      self.init_config()
2023-01-02 21:32:09.342382456    File "/opt/frigate/frigate/app.py", line 81, in init_config
2023-01-02 21:32:09.342384678      self.config = user_config.runtime_config
2023-01-02 21:32:09.342387141    File "/opt/frigate/frigate/config.py", line 941, in runtime_config
2023-01-02 21:32:09.342389104      verify_config_roles(camera_config)
2023-01-02 21:32:09.342393289    File "/opt/frigate/frigate/config.py", line 733, in verify_config_roles
2023-01-02 21:32:09.342403011      raise ValueError(
2023-01-02 21:32:09.342406011  ValueError: Camera cam1 has restream enabled, but restream is not assigned to an input.
2023-01-02 21:32:09.342407641  
2023-01-02 21:32:09.342410123  *************************************************************
2023-01-02 21:32:09.342504030  ***    End Config Validation Errors                       ***
2023-01-02 21:32:09.342508123  *************************************************************
s6-rc: info: service legacy-services: stopping
2023-01-02 21:32:10.022713937  exit OK
s6-svwait: fatal: supervisor died
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvisions

**Comment by NickM-27** [comment]
Please read the release notes, they are clear that restream is enabled by default. Rtmp is deprecated and there is a new restream config / role

**Comment by NickM-27** [comment]
Also highly suggest keeping restream enabled as it allows the new live view options.

**Comment by LaurenceGough** [comment]
Sorry I somehow missed that section. As you say it looks like restream is now enabled by default.

All is fine now after reconfiguring my cameras to the new style and using the new restreaming method. 

My Raspberry Pi 4 hwaccel fix has stopped working but that's a totally different issue :).

Thanks again :)

**Comment by ljmerza** [comment]
whats the new config I need to change to get this working?

**Comment by NickM-27** [comment]
@ljmerza make your own issue and answer all the questions.
