### ISSUE TITLE
[Config Support]: MQTT requires host even if disabled

### ISSUE THREAD

**Issue by Chris18284** [blakeblackshear/frigate#4879]
### Describe the problem you are having

MQTT requires host even if disabled

### Version

0.12.0-53D39A1

### Frigate config file

```yaml
mqtt:
  enabled: False
```

### Relevant log output

```shell
*************************************************************
*************************************************************
***    Your config file is not valid!                     ***
***    Please check the docs at                           ***
***    https://docs.frigate.video/configuration/index     ***
*************************************************************
*************************************************************
***    Config Validation Errors                           ***
*************************************************************
1 validation error for FrigateConfig
mqtt -> host
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/opt/frigate/frigate/app.py", line 335, in start
    self.init_config()
  File "/opt/frigate/frigate/app.py", line 80, in init_config
    user_config = FrigateConfig.parse_file(config_file)
  File "/opt/frigate/frigate/config.py", line 1002, in parse_file
    return cls.parse_obj(config)
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
mqtt -> host
  none is not an allowed value (type=type_error.none.not_allowed)
  
*************************************************************
***    End Config Validation Errors                       ***
*************************************************************
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
Just want to make sure, if you provide `host` it runs successfully?

**Comment by Chris18284** [comment]
Yes.
