### ISSUE TITLE
[EdgeTPU Support]: USB TPU working for a few days now refusing to

### ISSUE THREAD

**Issue by rmfm** [blakeblackshear/frigate#4952]
### Describe the problem you are having

I set up a bit of a test system within HA, which was working great low inference speed and coral was working. (Attached screenshots).

A few days later post HA core update (but can't prove it was that) the coral refuses to pick up.

The error I always recieve is : INFO    : Attempting to load TPU as usb
[2023-01-07 18:20:54] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.

If I switch back to CPU detectors all works fine, but inference speed is much lower.

I have:
Moved around on the USB ports.
Restarted
Installed the Full access version and disabled protection mode.

Same error.
Coral lights up and looks fine.

Please excuse me if I'm being thick, it's early days, but spent a bit of time looking online, so I'm sure I'm missing something obvious. Any help/pointers appreciated.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: 192.XXX.X.XXX
  user: XXX
  password: XXX

cameras:
  PI_1:
    ffmpeg:
      inputs:
        - path: rtsp://192.XXX.X.XXX:X/h264
          roles:
            - detect
            - rtmp
        - path: rtsp://192.XXX.XX.XXX:X/h264
          roles:
            - record
    detect:
      width: 1280
      height: 1024
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
detectors:
  coral:
    type: edgetpu
    device: usb

#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 3
#  cpu2:
#    type: cpu
#    num_threads: 3

record:
  enabled: True
  events:
    retain:
      default: 10q
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-01-07 18:20:54] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2023-01-07 18:20:54] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2023-01-07 18:20:54] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-01-07 18:20:54] peewee_migrate                 INFO    : There is nothing to migrate
[2023-01-07 18:20:54] frigate.app                    INFO    : Output process started: 217
[2023-01-07 18:20:54] frigate.mqtt                   INFO    : Turning on snapshots for PI_1 via mqtt
[2023-01-07 18:20:54] ws4py                          INFO    : Using epoll
[2023-01-07 18:20:54] frigate.app                    INFO    : Camera processor started for PI_1: 221
[2023-01-07 18:20:54] frigate.app                    INFO    : Capture process started for PI_1: 222
[2023-01-07 18:20:54] detector.coral                 INFO    : Starting detection process: 216
Process detector:coral:
[2023-01-07 18:20:54] frigate.edgetpu                INFO    : Attempting to load TPU as usb
[2023-01-07 18:20:54] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
[2023-01-07 18:20:54] ws4py                          INFO    : Using epoll
[2023-01-07 18:21:14] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
[2023-01-07 18:21:14] frigate.app                    INFO    : Stopping...
[2023-01-07 18:21:14] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
[2023-01-07 18:21:14] frigate.record                 INFO    : Exiting recording cleanup...
[2023-01-07 18:21:14] frigate.events                 INFO    : Exiting event cleanup...
[2023-01-07 18:21:14] frigate.stats                  INFO    : Exiting watchdog...
[2023-01-07 18:21:14] frigate.watchdog               INFO    : Exiting watchdog...
[2023-01-07 18:21:14] frigate.record                 INFO    : Exiting recording maintenance...
[2023-01-07 18:21:16] frigate.object_processing      INFO    : Exiting object processor...
[2023-01-07 18:21:24] frigate.events                 INFO    : Exiting event processor...
[2023-01-07 18:21:24] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
[2023-01-07 18:21:24] root                           INFO    : Waiting for detection process to exit gracefully...
[cmd] python3 exited 0
/usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Was working, hope these are the right screen grabs to show that.

![Screenshot_20230101-121744](https://user-images.githubusercontent.com/85053638/211165580-bd37de74-7f65-4354-bcc0-e09e7d1c946c.png)
![Screenshot_20230101-122422](https://user-images.githubusercontent.com/85053638/211165582-33b86436-304f-4ea0-8c41-30d9ecc92d2b.png)

**Comment by NickM-27** [comment]
When you plug the USB in what does it show as in the HA OS hardware section? If you leave it plugged in and try to run with coral detector and frigate crashes, what does it show as in the HA OS section after that?

**Comment by rmfm** [comment]
Thanks, what hardware code am I looking for?
![Uploading Screenshot_20230107-184903.png…]()

Within HA, is there a log I need to get? I've attached the output log from the integration, is there another one? I basically get red dot and the integration is stopped, if I switch to CPU detectors runs and is stable.

> When you plug the USB in what does it show as in the HA OS hardware section? If you leave it plugged in and try to run with coral detector and frigate crashes, what does it show as in the HA OS section after that?

**Comment by NickM-27** [comment]
Go to HA OS system settings and there is a hardware section in there. It is in the GUI, not logs

**Comment by rmfm** [comment]
> Go to HA OS system settings and there is a hardware section in there. It is in the GUI, not logs

Thanks done that, what is the hardware code I'm looking for. Hopefully the attached screen grab of USB over it. Or should I be seeing TPU or eTPU or something like that?

**Comment by NickM-27** [comment]
You're looking for Google Inc but you'll probably see Global Unicorp Chip at first. Take screenshots of either of them following the steps I outlined above.

**Comment by rmfm** [comment]
And it is not there... I'm out at the moment, but will try a different port/cable/double check it's plugged in.

Or is there something driver/config side I need to do?

**Comment by NickM-27** [comment]
The USB includes its own driver so there's no config

**Comment by rmfm** [comment]
Thanks, in that case I will try a new cable/different port and get back to you.
Thanks.

**Comment by pabloantonelli** [comment]
I had the same problem. Did you try use on this way?

`
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  `

This way works for me.

**Comment by rmfm** [comment]
> I had the same problem. Did you try use on this way?
> 
> ```
> detectors:
>   coral1:
>     type: edgetpu
>     device: usb:0
>   
> ```
> 
> That works for me.

I'll give this a go thanks. Specifying the port was on my list to try.

**Comment by rmfm** [comment]
> > I had the same problem. Did you try use on this way?
> > ```
> > detectors:
> >   coral1:
> >     type: edgetpu
> >     device: usb:0
> >   
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That works for me.
> 
> I'll give this a go thanks. Specifying the port was on my list to try.

Unfortunately no luck cycled through the ports no pick up.

**Comment by rmfm** [comment]
> The USB includes its own driver so there's no config

New cable tried. No results in hardware or frigate.

Moved around USB ports also..no result.

Attempted specifying the port (although if hardware not detected, not sure if this is valid). No result.

**Comment by NickM-27** [comment]
If it doesn't show in the hardware section in HA OS then the OS is not seeing the USB. Can always get a shell and run `ls /dev/` to make sure

**Comment by rmfm** [comment]
Doesn't look good. I guess I should plug the coral into another PC and do some form of check.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/85053638/211218388-cb69a773-eaed-4ac3-bc1f-68ac458c735f.png">

**Comment by NickM-27** [comment]
Sorry it should be /dev/usb

**Comment by rmfm** [comment]
Well I'm not doing that on quite right. Assuming still want a listing. e.g. ls /dev/usb

<img width="756" alt="image" src="https://user-images.githubusercontent.com/85053638/211218603-e93a9759-ed2f-4127-afd9-5947647cb208.png">

**Comment by NickM-27** [comment]
sorry working a little slow today on this front, it is `/dev/bus/usb`

**Comment by NickM-27** [comment]
you may also be able to run lsusb to get a better idea

**Comment by rmfm** [comment]
> /dev/bus/usb

No worries, all been there, appreciate the help.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/85053638/211277195-65cd4ade-fd6c-491b-a616-8eedf8b31357.png">

**Comment by NickM-27** [comment]
what about `lsusb` ?

**Comment by rmfm** [comment]
> what about `lsusb` ?

Hi Nick, see attached:
<img width="172" alt="image" src="https://user-images.githubusercontent.com/85053638/211409441-84970925-b89e-4f56-8863-49b765601820.png">

**Comment by rmfm** [comment]
Hi Nick, any views? Still stuck from my end. @NickM-27

**Comment by NickM-27** [comment]
I don't see the coral device there, not sure what happened but maybe a hardware issue? Would be good to find another device and see if it shows up

**Comment by rmfm** [comment]
Hi all, I've found a working solution. Apparently insufficient power to the coral 😖

Using a powered USB hub had to wait a few days for delivery, now up and working.

I don't feel this really explains it, but I do have a working coral now...

**Comment by rmfm** [comment]
Just like to say thanks for the help much appreciated
