### ISSUE TITLE
[Support]: Beta 12.0 won't start - log says config file problem.

### ISSUE THREAD

**Issue by FS1961** [blakeblackshear/frigate#4999]
### Describe the problem you are having

I restored (back to last saved config) and tried installing Beta 12.0 and can't get it to start.

The frigate config file is the same as 0.11.1

### Version

Frigate (Full Access) Beta (0.12.0)

### Frigate config file

```yaml
cameras:
  Dining: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password@192.168.178.59:554/play2.sdp # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://frigate:password@192.168.178.59:554/play1.sdp # <----- Update for your camera
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 10
    motion:
      mask:
        - 85,207,134,279,174,352,106,352,0,352,0,104,0,0,86,0
        - 394,36,389,229,313,188,315,42

  Garage: # <------ Name the camera
    motion:
      mask:
        - 110,352,91,220,173,227,351,352
        - 578,352,402,352,473,158,563,167
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password@192.168.178.36:554/play1.sdp          # <----- Update for your camera
          roles:
            - record
            - rtmp
        - path: rtsp://frigate:password@192.168.178.36:554/play3.sdp         # <----- Update for your camera
          roles:
            - detect
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 10
      
  Front-door: # <------ Name the camera
    motion:
      mask:
        - 0,127,0,352,226,352,242,327,206,83
        - 640,352,640,218,506,318,356,352,240,331,227,352
    zones:
      entry_doors:
        coordinates: 293,318,513,302,574,63,285,27
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password@192.168.178.28:554/play3.sdp # <----- Update for your camera
          roles:
            - detect
        - path: rtsp://frigate:password@192.168.178.28:554/play1.sdp # <----- Update for your camera
          roles:
            - record
            - rtmp
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
      fps: 10
      
  Garten-house: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password@192.168.178.46:554/play1.sdp # <----- Update for your camera
          roles:
            - record
            - rtmp
        - path: rtsp://frigate:password@192.168.178.46:554/play2.sdp # <----- Update for your camera
          roles:
            - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 480 # <---- update for your camera's resolution
      fps: 5
    motion:
      mask:
        - 0,480,241,480,171,403,0,100
        - 640,480,572,480,511,399,560,252,640,168
        
  Drive-way: # <------ Name the camera
    motion:
      mask:
        - 206,0,123,176,195,360,0,360,0,0
        - 640,180,640,0,530,0,451,0
    zones:
      driveway_area:
        coordinates: 469,117,596,360,226,360,224,115
      front_entrance:
        coordinates: 224,112,463,105,442,0,211,0
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password22!@192.168.178.55:554/h264  # <----- Update for your camera
          roles:
            - record
            - rtmp
        - path: rtsp://frigate:password22!@192.168.178.55:554/h264cif  # <----- Update for your camera
          roles:
            - detect
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
      
  Patio: # <------ Name the camera.
    motion:
      mask:
        - 640,0,436,0,397,120,640,129
        - 575,126,521,221,488,196,525,129
        - 0,283,0,0,273,0,198,54,151,65,179,220,125,273
    ffmpeg:
      inputs:
        - path: rtsp://frigate:password22!@192.168.178.74:554/h264  # <----- Update for your camera
          roles:
            - record
            - rtmp
        - path: rtsp://frigate:password22!@192.168.178.74:554/h264cif  # <----- Update for your camera
          roles:
            - detect
    rtmp:
      enabled: True # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
      fps: 5
      
detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/prepare-logs.sh
cont-init: info: /etc/cont-init.d/prepare-logs.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun frigate (no readiness notification)
services-up: info: copying legacy longrun go2rtc (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
2023-01-10 15:13:36.783797963  15:13:36.783 INF go2rtc version 0.1-rc.6 linux/amd64
2023-01-10 15:13:36.784966836  15:13:36.784 INF [api] listen addr=:1984
2023-01-10 15:13:36.785643537  15:13:36.785 INF [rtsp] listen addr=:8554
2023-01-10 15:13:36.786503360  15:13:36.786 INF [webrtc] listen addr=:8555
2023-01-10 15:13:36.790408326  15:13:36.790 INF [srtp] listen addr=:8443
2023-01-10 15:13:37.406697689  2023/01/10 16:13:37 [error] 112#112: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "ccab4aaf-frigate-fa-beta:5000"
2023-01-10 15:13:37.406813834  172.30.32.1 - - [10/Jan/2023:16:13:37 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.1.0 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:13:39.202871365  [2023-01-10 16:13:39] frigate.app                    INFO    : Starting Frigate (0.12.0-0dbf909)
2023-01-10 15:13:39.256801505  *************************************************************
2023-01-10 15:13:39.257137138  *************************************************************
2023-01-10 15:13:39.257218545  ***    Your config file is not valid!                     ***
2023-01-10 15:13:39.257282824  ***    Please check the docs at                           ***
2023-01-10 15:13:39.257345181  ***    https://docs.frigate.video/configuration/index     ***
2023-01-10 15:13:39.257406960  *************************************************************
2023-01-10 15:13:39.257468535  *************************************************************
2023-01-10 15:13:39.257558607  ***    Config Validation Errors                           ***
2023-01-10 15:13:39.258184374  *************************************************************
2023-01-10 15:13:39.258371423  Camera Dining has restream enabled, but restream is not assigned to an input.
2023-01-10 15:13:39.259798243  Traceback (most recent call last):
2023-01-10 15:13:39.259801677    File "/opt/frigate/frigate/app.py", line 335, in start
2023-01-10 15:13:39.259808485      self.init_config()
2023-01-10 15:13:39.259811930    File "/opt/frigate/frigate/app.py", line 81, in init_config
2023-01-10 15:13:39.259814179      self.config = user_config.runtime_config
2023-01-10 15:13:39.259816240    File "/opt/frigate/frigate/config.py", line 950, in runtime_config
2023-01-10 15:13:39.259833653      verify_config_roles(camera_config)
2023-01-10 15:13:39.259835944    File "/opt/frigate/frigate/config.py", line 742, in verify_config_roles
2023-01-10 15:13:39.259838259      raise ValueError(
2023-01-10 15:13:39.259840279  ValueError: Camera Dining has restream enabled, but restream is not assigned to an input.
2023-01-10 15:13:39.259940763  
2023-01-10 15:13:39.260107126  *************************************************************
2023-01-10 15:13:39.260215695  ***    End Config Validation Errors                       ***
2023-01-10 15:13:39.260280692  *************************************************************
s6-rc: info: service legacy-services: stopping
2023-01-10 15:13:39.567376258  exit OK
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
none
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

D-link and others

### Any other information that may be helpful

The config file is unchanged between the Frigate Beta versions. Works with 11.1 not with 12.0

**Comment by NickM-27** [comment]
Please read the release notes, this is covered in the breaking changes https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0-beta2

You should disable rtmp and remove that role, replacing it with the `restream` role

**Comment by FS1961** [comment]
Okay, I disabled RTMP. still getting errors
2023-01-10 15:36:03.385043916  15:36:03.384 INF [webrtc] listen addr=:8555
2023-01-10 15:36:03.390602051  15:36:03.385 INF [srtp] listen addr=:8443
2023-01-10 15:36:05.643726282  [2023-01-10 16:36:05] frigate.app                    INFO    : Starting Frigate (0.12.0-0dbf909)
2023-01-10 15:36:05.748534630  [2023-01-10 16:36:05] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-01-10 15:36:05.749366562  [2023-01-10 16:36:05] peewee_migrate                 INFO    : Starting migrations
2023-01-10 15:36:05.785808651  [2023-01-10 16:36:05] peewee_migrate                 INFO    : Migrate "012_add_segment_size"
2023-01-10 15:36:05.787063880  [2023-01-10 16:36:05] peewee_migrate                 INFO    : add_column ('recordings', 'segment_size', <FloatField: Recordings.segment_size>)
2023-01-10 15:36:05.792270616  [2023-01-10 16:36:05] peewee_migrate                 INFO    : Done 012_add_segment_size
2023-01-10 15:36:05.844329061  [2023-01-10 16:36:05] ws4py                          INFO    : Using epoll
2023-01-10 15:36:05.993495101  [2023-01-10 16:36:05] frigate.comms.dispatcher       INFO    : Turning off detection for Dining
2023-01-10 15:36:06.024748188  [2023-01-10 16:36:06] frigate.comms.dispatcher       INFO    : Turning on snapshots for Garten-house
2023-01-10 15:36:06.060724610  [2023-01-10 16:36:06] frigate.app                    INFO    : Output process started: 202
2023-01-10 15:36:06.094440685  [2023-01-10 16:36:06] ws4py                          INFO    : Using epoll
2023-01-10 15:36:08.312919322  [2023-01-10 16:36:06] detector.coral                 INFO    : Starting detection process: 201
2023-01-10 15:36:08.314019505  [2023-01-10 16:36:06] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-01-10 15:36:08.314683907  [2023-01-10 16:36:06] frigate.app                    INFO    : Camera processor started for Dining: 208
2023-01-10 15:36:08.315292531  [2023-01-10 16:36:06] frigate.app                    INFO    : Camera processor started for Garage: 209
2023-01-10 15:36:08.315799826  [2023-01-10 16:36:06] frigate.app                    INFO    : Camera processor started for Front-door: 213
2023-01-10 15:36:08.316484975  [2023-01-10 16:36:06] frigate.comms.dispatcher       INFO    : Turning on recordings for Drive-way
2023-01-10 15:36:08.317288317  [2023-01-10 16:36:06] frigate.app                    INFO    : Camera processor started for Garten-house: 215
2023-01-10 15:36:08.318099401  [2023-01-10 16:36:06] frigate.app                    INFO    : Camera processor started for Drive-way: 218
2023-01-10 15:36:08.318444529  [2023-01-10 16:36:06] frigate.app                    INFO    : Camera processor started for Patio: 220
2023-01-10 15:36:08.319372878  [2023-01-10 16:36:06] frigate.comms.dispatcher       INFO    : Turning on snapshots for Drive-way
2023-01-10 15:36:08.319935237  [2023-01-10 16:36:06] frigate.comms.dispatcher       INFO    : Turning on recordings for Patio
2023-01-10 15:36:08.320591825  [2023-01-10 16:36:06] frigate.comms.dispatcher       INFO    : Turning on snapshots for Patio
2023-01-10 15:36:08.321259889  [2023-01-10 16:36:06] frigate.app                    INFO    : Capture process started for Dining: 223
2023-01-10 15:36:08.322282287  [2023-01-10 16:36:06] frigate.app                    INFO    : Capture process started for Garage: 224
2023-01-10 15:36:08.323340567  [2023-01-10 16:36:06] frigate.app                    INFO    : Capture process started for Front-door: 230
2023-01-10 15:36:08.324409627  [2023-01-10 16:36:06] frigate.app                    INFO    : Capture process started for Garten-house: 232
2023-01-10 15:36:08.325007096  [2023-01-10 16:36:06] frigate.app                    INFO    : Capture process started for Drive-way: 241
2023-01-10 15:36:08.325662750  [2023-01-10 16:36:06] frigate.app                    INFO    : Capture process started for Patio: 250
2023-01-10 15:36:08.326252649  [2023-01-10 16:36:08] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-01-10 15:36:14.970006357  F driver/usb/usb_driver.cc:857] transfer on tag 2 failed. Abort. Deadline exceeded: USB transfer error 2 [LibUsbDataOutCallback]
2023-01-10 15:36:14.970012828  Fatal Python error: Aborted
2023-01-10 15:36:14.970020412  
2023-01-10 15:36:14.970022257  Thread 0x00007f25137fe6c0 (most recent call first):
2023-01-10 15:36:14.970024998    File "/usr/lib/python3.9/threading.py", line 312 in wait
2023-01-10 15:36:14.970027428    File "/usr/lib/python3.9/multiprocessing/queues.py", line 233 in _feed
2023-01-10 15:36:14.970045102    File "/usr/lib/python3.9/threading.py", line 892 in run
2023-01-10 15:36:14.970048249    File "/usr/lib/python3.9/threading.py", line 954 in _bootstrap_inner
2023-01-10 15:36:14.970050354    File "/usr/lib/python3.9/threading.py", line 912 in _bootstrap
2023-01-10 15:36:14.970051810  
2023-01-10 15:36:14.970053631  Thread 0x00007f2536651740 (most recent call first):
2023-01-10 15:36:14.970055626    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 833 in invoke
2023-01-10 15:36:14.970076730    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 53 in detect_raw
2023-01-10 15:36:14.970079068    File "/opt/frigate/frigate/object_detection.py", line 71 in detect_raw
2023-01-10 15:36:14.970094114    File "/opt/frigate/frigate/object_detection.py", line 120 in run_detector
2023-01-10 15:36:14.970096379    File "/usr/lib/python3.9/multiprocessing/process.py", line 108 in run
2023-01-10 15:36:14.970098575    File "/usr/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
2023-01-10 15:36:14.970100556    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
2023-01-10 15:36:14.970102551    File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
2023-01-10 15:36:14.970104490    File "/usr/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
2023-01-10 15:36:14.970106400    File "/usr/lib/python3.9/multiprocessing/context.py", line 224 in _Popen
2023-01-10 15:36:14.970123368    File "/usr/lib/python3.9/multiprocessing/process.py", line 121 in start
2023-01-10 15:36:14.970125669    File "/opt/frigate/frigate/object_detection.py", line 172 in start_or_restart
2023-01-10 15:36:14.970127572    File "/opt/frigate/frigate/object_detection.py", line 144 in __init__
2023-01-10 15:36:14.970130364    File "/opt/frigate/frigate/app.py", line 214 in start_detectors
2023-01-10 15:36:14.970132152    File "/opt/frigate/frigate/app.py", line 364 in start
2023-01-10 15:36:14.970133958    File "/opt/frigate/frigate/__main__.py", line 16 in <module>
2023-01-10 15:36:14.970135724    File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
2023-01-10 15:36:14.970738553    File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
2023-01-10 15:36:16.568292778  172.30.32.1 - - [10/Jan/2023:16:36:16 +0100] "GET /api/stats HTTP/1.1" 200 3130 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:16.575021004  172.30.32.1 - - [10/Jan/2023:16:36:16 +0100] "GET /api/version HTTP/1.1" 200 14 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:16.596195620  172.30.32.1 - - [10/Jan/2023:16:36:16 +0100] "GET /api/config HTTP/1.1" 200 16902 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:24.360212918  172.30.32.1 - - [10/Jan/2023:16:36:24 +0100] "GET /api/stats HTTP/1.1" 200 3150 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:26.607631134  [2023-01-10 16:36:26] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2023-01-10 15:36:26.626960090  [2023-01-10 16:36:26] detector.coral                 INFO    : Starting detection process: 350
2023-01-10 15:36:32.370877267  172.30.32.1 - - [10/Jan/2023:16:36:32 +0100] "GET /api/stats HTTP/1.1" 200 3132 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:40.357413121  172.30.32.1 - - [10/Jan/2023:16:36:40 +0100] "GET /api/stats HTTP/1.1" 200 3117 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:48.368805434  172.30.32.1 - - [10/Jan/2023:16:36:48 +0100] "GET /api/stats HTTP/1.1" 200 3117 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:56.353836570  172.30.32.1 - - [10/Jan/2023:16:36:56 +0100] "GET /api/stats HTTP/1.1" 200 3117 "-" "HomeAssistant/2023.1.2 aiohttp/3.8.1 Python/3.10" "-"
2023-01-10 15:36:59.143480549  [2023-01-10 16:36:26] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-01-10 15:36:59.144206851  [2023-01-10 16:36:59] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-01-10 15:36:59.144729510  Process detector:coral:
2023-01-10 15:36:59.148530206  Traceback (most recent call last):
2023-01-10 15:36:59.149000685    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-01-10 15:36:59.149004078      delegate = Delegate(library, options)
2023-01-10 15:36:59.149579305    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-01-10 15:36:59.149582618      raise ValueError(capture.message)
2023-01-10 15:36:59.150073319  ValueError
2023-01-10 15:36:59.151623773  
2023-01-10 15:36:59.151627456  During handling of the above exception, another exception occurred:
2023-01-10 15:36:59.151629156  
2023-01-10 15:36:59.152034228  Traceback (most recent call last):
2023-01-10 15:36:59.152217190    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-10 15:36:59.152220087      self.run()
2023-01-10 15:36:59.152285688    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-10 15:36:59.152288401      self._target(*self._args, **self._kwargs)
2023-01-10 15:36:59.152343847    File "/opt/frigate/frigate/object_detection.py", line 97, in run_detector
2023-01-10 15:36:59.152346577      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-01-10 15:36:59.152488285    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-01-10 15:36:59.152491368      self.detect_api = create_detector(detector_config)
2023-01-10 15:36:59.152664834    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-01-10 15:36:59.152667714      return api(detector_config)
2023-01-10 15:36:59.152789763    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 34, in __init__
2023-01-10 15:36:59.152792817      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-01-10 15:36:59.153321448    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-01-10 15:36:59.153324740      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-01-10 15:36:59.153544854  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-01-10 15:36:59.153547604

**Comment by NickM-27** [comment]
Make sure you're running the full access beta and make sure that protected mode is disabled.

**Comment by FS1961** [comment]
I think this is going to take some time. Not a smooth transition.

**Comment by FS1961** [comment]
Okay, I'm learning the new system.
