### ISSUE TITLE
[Config Support]: Configure the model in the detector.

### ISSUE THREAD

**Issue by hallenmaia** [blakeblackshear/frigate#5019]
### Describe the problem you are having

According to the detector_config.py source code, it is possible to configure the model in detector: https://github.com/blakeblackshear/frigate/blob/acd1fb9e3e0f4596ed794aec6552df01c66f1bef/frigate/detectors/detector_config.py#L71-L76.

If I set it up like this:

```
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
      labelmap_path: /openvino-model/coco_91cl_bkgr.txt
      width: 300
      height: 300
      input_pixel_format: bgr
      input_tensor: nhwc

```

The following error appears in the logs:

```
2023-01-11 10:25:18.485111493  [2023-01-11 10:25:18] frigate.app                    INFO    : Camera processor started for rua-desce: 276
2023-01-11 10:25:18.488542244  Process camera_processor:rua-desce:
2023-01-11 10:25:18.489992057  Traceback (most recent call last):
2023-01-11 10:25:18.490277870    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-11 10:25:18.490281383      self.run()
2023-01-11 10:25:18.490362977    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-11 10:25:18.490365838      self._target(*self._args, **self._kwargs)
2023-01-11 10:25:18.490468821    File "/opt/frigate/frigate/video.py", line 447, in track_camera
2023-01-11 10:25:18.490471460      object_detector = RemoteObjectDetector(
2023-01-11 10:25:18.490548377    File "/opt/frigate/frigate/object_detection.py", line 183, in __init__
2023-01-11 10:25:18.490550865      self.np_shm = np.ndarray(
2023-01-11 10:25:18.490670591  TypeError: buffer is too small for requested array
```

Live view is normal but motion detection process is not started:

Live:
<img width="1113" alt="Captura de Tela 2023-01-11 às 10 30 41" src="https://user-images.githubusercontent.com/29228176/211819274-f7447adb-16e4-4bf7-ad20-bb27efbfa136.png">

Debug:
<img width="1113" alt="Captura de Tela 2023-01-11 às 10 31 00" src="https://user-images.githubusercontent.com/29228176/211819309-b2d2656f-c804-43d0-b7a8-b0160e674128.png">

If I configure it the way it is in the documentation:

```
detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
  width: 300
  height: 300
  input_pixel_format: bgr
  input_tensor: nhwc
```

It works as expected and the error doesn't appear in the logs.

Live:
<img width="1113" alt="Captura de Tela 2023-01-11 às 10 39 00" src="https://user-images.githubusercontent.com/29228176/211820673-97a2365f-6dbd-4a87-b173-9595a4cb948b.png">

Debug:
<img width="1113" alt="Captura de Tela 2023-01-11 às 10 39 15" src="https://user-images.githubusercontent.com/29228176/211820682-d4bf80ed-e263-419d-bc65-404662e86519.png">

### Version

0.12.0 Beta 2

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.2
  user: frigate
  password: blablabla

detectors:
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
      labelmap_path: /openvino-model/coco_91cl_bkgr.txt
      width: 300
      height: 300
      input_pixel_format: bgr
      input_tensor: nhwc

database:
  path: /db/frigate.db


birdseye:
  mode: objects

ffmpeg:
  hwaccel_args: preset-vaapi

detect:
  width: 704
  height: 480

objects:
  track:
    - person
    - cat

motion:
  mask:
    - 704,0,704,45,455,45,455,0

record:
  enabled: true
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      mode: motion
      objects:
        person: 15

snapshots:
  enabled: true
  retain:
    objects:
      person: 15

restream:
  force_audio: false
  birdseye: false

timestamp_style:
  format: "%d/%m/%Y %H:%M:%S"

cameras:
  rua-desce:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - restream
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      rua:
        coordinates: 360,138,704,293,704,480,275,480,0,480,0,135,0,31
    ui:
      order: 1
      dashboard: true
  rua-sobe:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.12:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - restream
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.12:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    zones:
      rua:
        coordinates: 0,480,704,480,704,0,637,0,528,29,361,97,271,147,0,298
    ui:
      order: 2
      dashboard: true
  garagem:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.13:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - restream
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.13:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    ui:
      order: 3
      dashboard: true
  varanda:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.14:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - restream
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.14:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    ui:
      order: 4
      dashboard: true
  porteiro:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.15:554/Streaming/Channels/101
          roles:
            - record
            - restream
        - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@192.168.1.15:554/Streaming/Channels/102
          roles:
            - detect
      output_args: 
        record: preset-record-generic-audio
    zones:
      rua:
        coordinates: 0,480,558,480,581,357,590,233,452,271,293,303,0,344
    birdseye:
      enabled: False        
    ui:
      order: 5
      dashboard: true
```

### Relevant log output

```shell
[2023-01-11 10:25:18] frigate.app                    INFO    : Starting Frigate (0.12.0-0dbf909)
2023-01-11 10:25:18.405122258  [2023-01-11 10:25:18] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-01-11 10:25:18.417361664  [2023-01-11 10:25:18] peewee_migrate                 INFO    : Starting migrations
2023-01-11 10:25:18.424165185  [2023-01-11 10:25:18] peewee_migrate                 INFO    : There is nothing to migrate
2023-01-11 10:25:18.426972782  [2023-01-11 10:25:18] ws4py                          INFO    : Using epoll
2023-01-11 10:25:18.471131705  [2023-01-11 10:25:18] detector.ov                    INFO    : Starting detection process: 269
2023-01-11 10:25:18.474999038  [2023-01-11 10:25:18] frigate.app                    INFO    : Output process started: 271
2023-01-11 10:25:18.483389964  [2023-01-11 10:25:18] ws4py                          INFO    : Using epoll
2023-01-11 10:25:18.485111493  [2023-01-11 10:25:18] frigate.app                    INFO    : Camera processor started for rua-desce: 276
2023-01-11 10:25:18.488542244  Process camera_processor:rua-desce:
2023-01-11 10:25:18.489992057  Traceback (most recent call last):
2023-01-11 10:25:18.490277870    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-11 10:25:18.490281383      self.run()
2023-01-11 10:25:18.490362977    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-11 10:25:18.490365838      self._target(*self._args, **self._kwargs)
2023-01-11 10:25:18.490468821    File "/opt/frigate/frigate/video.py", line 447, in track_camera
2023-01-11 10:25:18.490471460      object_detector = RemoteObjectDetector(
2023-01-11 10:25:18.490548377    File "/opt/frigate/frigate/object_detection.py", line 183, in __init__
2023-01-11 10:25:18.490550865      self.np_shm = np.ndarray(
2023-01-11 10:25:18.490670591  TypeError: buffer is too small for requested array
2023-01-11 10:25:18.492479796  [2023-01-11 10:25:18] frigate.app                    INFO    : Camera processor started for rua-sobe: 277
2023-01-11 10:25:18.512959303  [2023-01-11 10:25:18] frigate.app                    INFO    : Camera processor started for garagem: 279
2023-01-11 10:25:18.513440109  Process camera_processor:rua-sobe:
2023-01-11 10:25:18.514683845  Traceback (most recent call last):
2023-01-11 10:25:18.514783176    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-11 10:25:18.514785781      self.run()
2023-01-11 10:25:18.514803522    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-11 10:25:18.514810982      self._target(*self._args, **self._kwargs)
2023-01-11 10:25:18.514813769    File "/opt/frigate/frigate/video.py", line 447, in track_camera
2023-01-11 10:25:18.514833099      object_detector = RemoteObjectDetector(
2023-01-11 10:25:18.514835652    File "/opt/frigate/frigate/object_detection.py", line 183, in __init__
2023-01-11 10:25:18.514837897      self.np_shm = np.ndarray(
2023-01-11 10:25:18.514839540  TypeError: buffer is too small for requested array
2023-01-11 10:25:18.519832645  [2023-01-11 10:25:18] frigate.app                    INFO    : Camera processor started for varanda: 280
2023-01-11 10:25:18.520567177  Process camera_processor:garagem:
2023-01-11 10:25:18.521832276  Traceback (most recent call last):
2023-01-11 10:25:18.522028831    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-11 10:25:18.522031915      self.run()
2023-01-11 10:25:18.522117613    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-11 10:25:18.522120222      self._target(*self._args, **self._kwargs)
2023-01-11 10:25:18.522201474    File "/opt/frigate/frigate/video.py", line 447, in track_camera
2023-01-11 10:25:18.522204023      object_detector = RemoteObjectDetector(
2023-01-11 10:25:18.522234312    File "/opt/frigate/frigate/object_detection.py", line 183, in __init__
2023-01-11 10:25:18.522236644      self.np_shm = np.ndarray(
2023-01-11 10:25:18.526746025  [2023-01-11 10:25:18] frigate.app                    INFO    : Camera processor started for porteiro: 281
2023-01-11 10:25:18.530020226  TypeError: buffer is too small for requested array
2023-01-11 10:25:18.534864121  [2023-01-11 10:25:18] frigate.app                    INFO    : Capture process started for rua-desce: 283
2023-01-11 10:25:18.542677002  [2023-01-11 10:25:18] frigate.app                    INFO    : Capture process started for rua-sobe: 284
2023-01-11 10:25:18.543400120  Process camera_processor:porteiro:
2023-01-11 10:25:18.544628989  Traceback (most recent call last):
2023-01-11 10:25:18.544722408    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-11 10:25:18.544724953      self.run()
2023-01-11 10:25:18.544726907    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-11 10:25:18.544728581      self._target(*self._args, **self._kwargs)
2023-01-11 10:25:18.544730346    File "/opt/frigate/frigate/video.py", line 447, in track_camera
2023-01-11 10:25:18.544731971      object_detector = RemoteObjectDetector(
2023-01-11 10:25:18.544733859    File "/opt/frigate/frigate/object_detection.py", line 183, in __init__
2023-01-11 10:25:18.544735348      self.np_shm = np.ndarray(
2023-01-11 10:25:18.544736946  TypeError: buffer is too small for requested array
2023-01-11 10:25:18.546681408  Process camera_processor:varanda:
2023-01-11 10:25:18.547981787  Traceback (most recent call last):
2023-01-11 10:25:18.548090745    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-11 10:25:18.548093455      self.run()
2023-01-11 10:25:18.548095289    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-11 10:25:18.548096951      self._target(*self._args, **self._kwargs)
2023-01-11 10:25:18.548098713    File "/opt/frigate/frigate/video.py", line 447, in track_camera
2023-01-11 10:25:18.548100274      object_detector = RemoteObjectDetector(
2023-01-11 10:25:18.548102074    File "/opt/frigate/frigate/object_detection.py", line 183, in __init__
2023-01-11 10:25:18.548103547      self.np_shm = np.ndarray(
2023-01-11 10:25:18.548105169  TypeError: buffer is too small for requested array
2023-01-11 10:25:18.567669744  [2023-01-11 10:25:18] frigate.app                    INFO    : Capture process started for garagem: 288
2023-01-11 10:25:18.584673622  [2023-01-11 10:25:18] frigate.app                    INFO    : Capture process started for varanda: 297
2023-01-11 10:25:18.591260808  [2023-01-11 10:25:18] frigate.app                    INFO    : Capture process started for porteiro: 300
2023-01-11 10:25:18.969753131  [2023-01-11 10:25:18] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-01-11 10:25:18.970017703  [2023-01-11 10:25:18] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-01-11 10:25:18.970164584  [2023-01-11 10:25:18] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
```

### Frigate stats

```json
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.3"},"1":{"cpu":"0.0","mem":"0.0"},"1039":{"cpu":"0.0","mem":"0.0"},"112":{"cpu":"0.0","mem":"0.1"},"113":{"cpu":"0.0","mem":"0.1"},"114":{"cpu":"0.0","mem":"0.1"},"115":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"17":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"262":{"cpu":"0.0","mem":"1.0"},"268":{"cpu":"0.7","mem":"0.1"},"269":{"cpu":"0.0","mem":"5.8"},"271":{"cpu":"2.0","mem":"1.2"},"275":{"cpu":"0.0","mem":"0.2"},"276":{"cpu":"1.0","mem":"1.2"},"277":{"cpu":"1.0","mem":"1.2"},"278":{"cpu":"0.0","mem":"0.3"},"279":{"cpu":"1.3","mem":"1.2"},"280":{"cpu":"1.0","mem":"1.2"},"281":{"cpu":"0.0","mem":"0.3"},"282":{"cpu":"1.3","mem":"1.2"},"283":{"cpu":"1.7","mem":"1.1"},"284":{"cpu":"1.3","mem":"1.1"},"287":{"cpu":"0.0","mem":"0.3"},"288":{"cpu":"2.0","mem":"1.1"},"289":{"cpu":"1.7","mem":"0.6"},"295":{"cpu":"1.7","mem":"1.1"},"298":{"cpu":"1.7","mem":"1.1"},"299":{"cpu":"1.7","mem":"0.3"},"300":{"cpu":"0.0","mem":"0.2"},"304":{"cpu":"2.0","mem":"0.6"},"305":{"cpu":"2.0","mem":"0.6"},"306":{"cpu":"2.3","mem":"0.6"},"309":{"cpu":"0.0","mem":"0.3"},"313":{"cpu":"4.0","mem":"0.5"},"314":{"cpu":"2.0","mem":"0.3"},"319":{"cpu":"1.7","mem":"0.3"},"323":{"cpu":"1.7","mem":"0.3"},"326":{"cpu":"6.3","mem":"0.4"},"33":{"cpu":"0.0","mem":"0.0"},"72":{"cpu":"0.0","mem":"0.0"},"74":{"cpu":"0.0","mem":"0.0"},"75":{"cpu":"0.0","mem":"0.0"},"76":{"cpu":"0.0","mem":"0.0"},"77":{"cpu":"0.0","mem":"0.0"},"78":{"cpu":"0.0","mem":"0.0"},"79":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.2"},"82":{"cpu":"0.0","mem":"0.0"},"83":{"cpu":"0.0","mem":"0.4"},"84":{"cpu":"7.0","mem":"2.1"},"85":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"6419.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"average:","mem":"1.58,"}},"detection_fps":3.4,"detectors":{"ov":{"detection_start":0.0,"inference_speed":28.01,"pid":269}},"garagem":{"camera_fps":5.0,"capture_pid":288,"detection_fps":3.4,"ffmpeg_pid":305,"pid":279,"process_fps":5.1,"skipped_fps":0.0},"gpu_usages":{"intel-vaapi":{"gpu":"2.8 %","mem":"- %"}},"porteiro":{"camera_fps":5.1,"capture_pid":298,"detection_fps":0.0,"ffmpeg_pid":313,"pid":282,"process_fps":5.1,"skipped_fps":0.0},"rua-desce":{"camera_fps":5.0,"capture_pid":283,"detection_fps":0.0,"ffmpeg_pid":289,"pid":276,"process_fps":5.0,"skipped_fps":0.0},"rua-sobe":{"camera_fps":5.0,"capture_pid":284,"detection_fps":0.0,"ffmpeg_pid":304,"pid":277,"process_fps":5.0,"skipped_fps":0.0},"service":{"latest_version":"0.11.1","storage":{"/dev/shm":{"free":62.3,"mount_type":"tmpfs","total":67.1,"used":4.8},"/media/frigate/clips":{"free":73032.5,"mount_type":"ext4","total":84884.6,"used":7493.1},"/media/frigate/recordings":{"free":73032.5,"mount_type":"ext4","total":84884.6,"used":7493.1},"/tmp/cache":{"free":929.4,"mount_type":"tmpfs","total":1000.0,"used":70.6}},"temperatures":{},"uptime":307,"version":"0.12.0-0dbf909"},"varanda":{"camera_fps":5.0,"capture_pid":295,"detection_fps":0.0,"ffmpeg_pid":306,"pid":280,"process_fps":5.0,"skipped_fps":0.0}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

**Comment by NickM-27** [comment]
Only the model path is configurable as part of the detector model field, all other fields are inherited from the global model config, this is working as expected.

**Comment by hallenmaia** [comment]
Ok, but as the model configuration is specific for each type of detector, it doesn't make sense to configure the model globally.

Or am I mistaken?

**Comment by NickM-27** [comment]
> Ok, but as the model configuration is specific for each type of detector, it doesn't make sense to configure the model globally.
> 
> Or am I mistaken?

Currently mixing two different detector types (google coral & openvino) is not supported
