### ISSUE TITLE
[Config Support]: config error when updating to use go2rtc

### ISSUE THREAD

**Issue by jsbowling42** [blakeblackshear/frigate#5142]
### Describe the problem you are having

getting an error when trying to update to Beta4

### Version

0.12Beta4

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.65
  user: xxxx
  password: xxxx
 
ffmpeg:
  hwaccel_args: -c:v h264_cuvid

go2rtc:
  streams:
    driveway_cam: ffmpeg:rtsp://admin:xxxx!@192.168.1.195:554/cam/realmonitor?channel=1&subtype=0
    front_Door_cam: ffmpeg:rtsp://admin:xxxx@192.168.1.208:554/cam/realmonitor?channel=1&subtype=0
    
cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.40:8554/driveway_cam?video=copy&audio=aac # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - car
        - dog
        - cat
      filters:
        dog:
          mask: 0,87,1070,109,1753,226,1899,102,1920,0,1623,0,52,0,0,0,0,0
          threshold: 0.7
        cat:
          mask: 0,87,1070,109,1753,226,1899,102,1920,0,1623,0,52,0,0,0,0,0
          threshold: 0.7
        car:
          mask:
            - 1920,602,1920,338,1817,273,1769,454
            - 421,97,397,125,472,122,516,121,555,124,769,103,773,52,556,62
          min_score: 0.5
          threshold: 0.6
        person:
          min_area: 2500
          mask:  0,87,1070,109,1753,226,1899,102,1920,0,1623,0,52,0,0,0,0,0
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.5
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 7
      required_zones:
        # - driveway_entrance
        - side_yard
        - front_yard
        - driveway
    motion:
      improve_contrast: True
      threshold: 25
      contour_area: 30
      # 1080
      mask: 21,1053,510,1051,510,1006,21,1005

    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
          # - driveway_entrance
          - side_yard
          - front_yard
          - driveway
        retain:
          default: 14
          mode: active_objects
    zones:
      # driveway_entrance:
      #   # 1920x1080
      #   coordinates: 1104,213,1354,245,1324,206,1132,182
      #   objects:
      #     - person
      #     - dog
      #     - cat
      #     - car
      driveway:
        coordinates: 0,1080,1920,1080,1920,753,1920,689,1880,650,1859,615,1834,583,1801,543,1779,516,1756,497,1738,473,1708,458,1693,441,1673,424,1687,401,1681,383,1645,373,1605,363,1563,352,1529,345,1495,333,1455,324,1424,314,1396,300,1373,283,1345,248,1109,215,1073,243,1031,257,952,259,877,266,810,280,769,297,711,331,656,359,541,429,451,485,360,545,232,640,147,706,0,831
        objects:
          - car
          - person
          - dog
          - cat
      side_yard:
        coordinates:  0,784,52,753,102,719,141,680,174,657,259,596,316,551,367,514,422,483,472,452,524,425,564,400,605,380,637,355,672,336,713,318,737,298,776,281,828,264,884,253,920,247,968,249,997,246,1044,239,1077,233,1105,218,1116,202,1088,196,1051,194,1021,192,983,188,920,179,886,189,802,216,722,239,574,291,446,343,321,390,178,469,95,517,0,499
        objects: 
          - person
          - dog
          - cat
      front_yard:
        coordinates: 1574,267,1630,280,1669,291,1695,300,1724,305,1721,325,1704,365,1683,372,1654,366,1616,357,1584,349,1553,342,1520,333,1483,321,1452,312,1423,302,1396,292,1376,275,1362,261,1349,247,1345,225
        objects: 
          - person
          - dog
          - cat
  front_Door_cam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.40:8554/front_Door_cam?video=copy&audio=aac  # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1440
      height: 1080
      fps: 10
    objects:
      # Optional: list of objects to track from labelmap.txt (default: shown below
      track:
        - person
        - car
        - dog
        - cat
      filters:
        dog:
          threshold: 0.7
        cat:
          threshold: 0.7
        person:
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.45
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.6
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 7
      required_zones:
        - front_yard
    motion:
      improve_contrast: True
      mask: 1418,0,1419,38,1017,35,1015,0


    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        required_zones:
          - front_yard
        retain:
          default: 14
          mode: active_objects
    zones:
      front_yard:
        coordinates: 404,1080,1440,1080,1440,671,1360,655,1276,640,1084,613,958,600,919,599,831,590,745,596,662,600,573,605,435,611,437,695
        objects: 
          - person
          - dog
          - cat
          
detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### Relevant log output

```shell
2023-01-17 10:31:16.145725111  [2023-01-17 10:31:16] detector.tensorrt              INFO    : Starting detection process: 270
2023-01-17 10:31:16.170010389  [2023-01-17 10:31:16] frigate.app                    INFO    : Capture process started for front_Door_cam: 285
2023-01-17 10:31:16.252186552  Process detector:tensorrt:
2023-01-17 10:31:16.252341014  [2023-01-17 10:31:16] frigate.detectors.plugins.tensorrt ERROR   : ERROR: failed to load libraries. /trt-models/libyolo_layer.so: cannot open shared object file: No such file or directory
2023-01-17 10:31:16.253000992  Traceback (most recent call last):
2023-01-17 10:31:16.253003655    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-17 10:31:16.253004878      self.run()
2023-01-17 10:31:16.253006156    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-17 10:31:16.253008730      self._target(*self._args, **self._kwargs)
2023-01-17 10:31:16.253010147    File "/opt/frigate/frigate/object_detection.py", line 97, in run_detector
2023-01-17 10:31:16.253026253      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-01-17 10:31:16.253028280    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-01-17 10:31:16.253029484      self.detect_api = create_detector(detector_config)
2023-01-17 10:31:16.253030744    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-01-17 10:31:16.253047299      return api(detector_config)
2023-01-17 10:31:16.253048954    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 219, in __init__
2023-01-17 10:31:16.253050273      self.engine = self._load_engine(detector_config.model.path)
2023-01-17 10:31:16.253051541    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 87, in _load_engine
2023-01-17 10:31:16.253062440      with open(model_path, "rb") as f, trt.Runtime(self.trt_logger) as runtime:
2023-01-17 10:31:16.253081252  FileNotFoundError: [Errno 2] No such file or directory: '/trt-models/yolov7-tiny-416.trt'
2023-01-17 10:31:16.253082645  Exception ignored in: <function TensorRtDetector.__del__ at 0x7fa4e7072c10>
2023-01-17 10:31:16.253083720  Traceback (most recent call last):
2023-01-17 10:31:16.253085001    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-01-17 10:31:16.253183882      if self.outputs is not None:
2023-01-17 10:31:16.253197582  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2023-01-17 10:31:16.283417002  2023/01/17 10:31:16 [error] 110#110: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.65, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.1.40:5000"
2023-01-17 10:31:16.283507804  192.168.1.65 - - [17/Jan/2023:10:31:16 -0600] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.1.4 aiohttp/3.8.1 Python/3.10" "-"
2023-01-17 10:31:24.511603278  192.168.1.65 - - [17/Jan/2023:10:31:24 -0600] "GET /api/stats HTTP/1.1" 200 2273 "-" "HomeAssistant/2023.1.4 aiohttp/3.8.1 Python/3.10" "-"
s6-rc: info: service legacy-services: stopping
2023-01-17 10:31:27.633923767  exit OK
2023-01-17 10:31:27.635077125  [2023-01-17 10:31:27] frigate.app                    INFO    : Stopping...
2023-01-17 10:31:27.641335165  [2023-01-17 10:31:27] ws4py                          INFO    : Closing all websockets with [1001] 'Server is shutting down'
2023-01-17 10:31:27.641340312  [2023-01-17 10:31:27] frigate.events                 INFO    : Exiting event cleanup...
s6-svwait: fatal: supervisor died
2023-01-17 10:31:27.641767458  [2023-01-17 10:31:27] frigate.record                 INFO    : Exiting recording maintenance...
2023-01-17 10:31:27.641976992  [2023-01-17 10:31:27] frigate.watchdog               INFO    : Exiting watchdog...
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
2023-01-17 10:31:27.642581659  [2023-01-17 10:31:27] frigate.stats                  INFO    : Exiting watchdog...
2023-01-17 10:31:27.642723061  [2023-01-17 10:31:27] frigate.record                 INFO    : Exiting recording cleanup...
2023-01-17 10:31:27.642863424  [2023-01-17 10:31:27] frigate.storage                INFO    : Exiting storage maintainer...
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/prepare-logs.sh
cont-init: info: /etc/cont-init.d/prepare-logs.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun frigate (no readiness notification)
services-up: info: copying legacy longrun go2rtc (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
2023-01-17 13:27:25.880060927  19:27:25.879 INF go2rtc version 0.1-rc.9 linux/amd64
2023-01-17 13:27:25.880356323  19:27:25.880 INF [api] listen addr=:1984
2023-01-17 13:27:25.880471542  19:27:25.880 INF [rtsp] listen addr=:8554
2023-01-17 13:27:25.880834039  19:27:25.880 INF [webrtc] listen addr=:8555
2023-01-17 13:27:25.880971606  19:27:25.880 INF [srtp] listen addr=:8443
2023-01-17 13:27:26.805266457  [2023-01-17 13:27:26] frigate.app                    INFO    : Starting Frigate (0.12.0-19afb03)
2023-01-17 13:27:26.848357301  [2023-01-17 13:27:26] peewee_migrate                 INFO    : Starting migrations
2023-01-17 13:27:26.853056056  [2023-01-17 13:27:26] peewee_migrate                 INFO    : There is nothing to migrate
2023-01-17 13:27:26.855600976  [2023-01-17 13:27:26] ws4py                          INFO    : Using epoll
2023-01-17 13:27:26.872962706  [2023-01-17 13:27:26] frigate.app                    INFO    : Output process started: 272
2023-01-17 13:27:26.874600117  [2023-01-17 13:27:26] ws4py                          INFO    : Using epoll
2023-01-17 13:27:26.884417930  [2023-01-17 13:27:26] frigate.app                    INFO    : Camera processor started for driveway_cam: 277
2023-01-17 13:27:26.891681338  [2023-01-17 13:27:26] frigate.app                    INFO    : Camera processor started for front_Door_cam: 279
2023-01-17 13:27:26.896913957  [2023-01-17 13:27:26] frigate.app                    INFO    : Capture process started for driveway_cam: 280
2023-01-17 13:27:26.904544102  [2023-01-17 13:27:26] detector.tensorrt              INFO    : Starting detection process: 270
2023-01-17 13:27:26.905323218  [2023-01-17 13:27:26] frigate.app                    INFO    : Capture process started for front_Door_cam: 282
2023-01-17 13:27:27.026710346  [2023-01-17 13:27:27] frigate.detectors.plugins.tensorrt ERROR   : ERROR: failed to load libraries. /trt-models/libyolo_layer.so: cannot open shared object file: No such file or directory
2023-01-17 13:27:27.026716583  Process detector:tensorrt:
2023-01-17 13:27:27.027611626  Traceback (most recent call last):
2023-01-17 13:27:27.027614330    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-01-17 13:27:27.027615510      self.run()
2023-01-17 13:27:27.027616801    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-01-17 13:27:27.027618355      self._target(*self._args, **self._kwargs)
2023-01-17 13:27:27.027619580    File "/opt/frigate/frigate/object_detection.py", line 97, in run_detector
2023-01-17 13:27:27.027638287      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-01-17 13:27:27.027640417    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-01-17 13:27:27.027641599      self.detect_api = create_detector(detector_config)
2023-01-17 13:27:27.027642822    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-01-17 13:27:27.027660353      return api(detector_config)
2023-01-17 13:27:27.027662018    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 219, in __init__
2023-01-17 13:27:27.027663346      self.engine = self._load_engine(detector_config.model.path)
2023-01-17 13:27:27.027664595    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 87, in _load_engine
2023-01-17 13:27:27.027675399      with open(model_path, "rb") as f, trt.Runtime(self.trt_logger) as runtime:
2023-01-17 13:27:27.027695401  FileNotFoundError: [Errno 2] No such file or directory: '/trt-models/yolov7-tiny-416.trt'
2023-01-17 13:27:27.027696828  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f0c451b4c10>
2023-01-17 13:27:27.027697874  Traceback (most recent call last):
2023-01-17 13:27:27.027699134    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-01-17 13:27:27.027775679      if self.outputs is not None:
2023-01-17 13:27:27.027792670  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2023-01-17 13:27:32.517984399  192.168.1.65 - - [17/Jan/2023:13:27:32 -0600] "GET /api/stats HTTP/1.1" 200 2336 "-" "HomeAssistant/2023.1.4 aiohttp/3.8.1 Python/3.10" "-"
2023-01-17 13:27:40.514344655  192.168.1.65 - - [17/Jan/2023:13:27:40 -0600] "GET /api/stats HTTP/1.1" 200 2336 "-" "HomeAssistant/2023.1.4 aiohttp/3.8.1 Python/3.10" "-"
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

**Comment by NickM-27** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: '/trt-models/yolov7-tiny-416.trt'`

looks like you haven't mapped the model to the correct directory

**Comment by jsbowling42** [comment]
dang, i missed that in my compose file. thanks!
