### ISSUE TITLE
0.8.0-beta3 - Exception in thread recording_maint

### ISSUE THREAD

**Issue by TheSleepySlee** [blakeblackshear/frigate#522]
Same config as here: https://github.com/blakeblackshear/frigate/issues/521

See logs below:
```
2021-01-13T20:45:42.397151098Z  * Starting nginx nginx
2021-01-13T20:45:42.412610590Z    ...done.
2021-01-13T20:45:43.384723478Z frigate.app                    WARNING : Camera portailcam has clips assigned to an input, but save_clips is not enabled.
2021-01-13T20:45:43.474688223Z detector.coral                 INFO    : Starting detection process: 33
2021-01-13T20:45:46.132981958Z frigate.app                    INFO    : Camera processor started for garageptz: 36
2021-01-13T20:45:46.133076412Z frigate.edgetpu                INFO    : Attempting to load TPU as usb
2021-01-13T20:45:46.133168770Z frigate.app                    INFO    : Camera processor started for japonais: 38
2021-01-13T20:45:46.133254477Z frigate.app                    INFO    : Camera processor started for z5: 40
2021-01-13T20:45:46.133339640Z frigate.app                    INFO    : Camera processor started for garage: 41
2021-01-13T20:45:46.133418304Z frigate.app                    INFO    : Camera processor started for portailcam: 43
2021-01-13T20:45:46.133571494Z frigate.app                    INFO    : Capture process started for garageptz: 44
2021-01-13T20:45:46.133661476Z frigate.app                    INFO    : Capture process started for japonais: 47
2021-01-13T20:45:46.133783666Z frigate.app                    INFO    : Capture process started for z5: 49
2021-01-13T20:45:46.133841012Z frigate.app                    INFO    : Capture process started for garage: 51
2021-01-13T20:45:46.133933026Z frigate.app                    INFO    : Capture process started for portailcam: 56
2021-01-13T20:45:46.137213772Z frigate.edgetpu                INFO    : TPU found
2021-01-13T20:45:53.840275167Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55821dda3140] moov atom not found
2021-01-13T20:45:53.840293693Z /tmp/cache/garage-20210113214536.mp4: Invalid data found when processing input
2021-01-13T20:45:53.841786490Z frigate.events                 INFO    : bad file: garage-20210113214536.mp4
2021-01-13T20:45:54.788585224Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55ef9988d140] moov atom not found
2021-01-13T20:45:54.788691183Z /tmp/cache/garageptz-20210113214536.mp4: Invalid data found when processing input
2021-01-13T20:45:54.790174106Z frigate.events                 INFO    : bad file: garageptz-20210113214536.mp4
2021-01-13T20:45:54.802736082Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x5569f8143140] moov atom not found
2021-01-13T20:45:54.802751869Z /tmp/cache/z5-20210113214535.mp4: Invalid data found when processing input
2021-01-13T20:45:54.804288414Z frigate.events                 INFO    : bad file: z5-20210113214535.mp4
2021-01-13T20:45:55.418824594Z [mov,mp4,m4a,3gp,3g2,mj2 @ 0x55c76dee0140] moov atom not found
2021-01-13T20:45:55.418840475Z /tmp/cache/japonais-20210113214535.mp4: Invalid data found when processing input
2021-01-13T20:45:55.420260447Z frigate.events                 INFO    : bad file: japonais-20210113214535.mp4
2021-01-14T17:29:45.132215013Z Exception in thread recording_maint:
2021-01-14T17:29:45.132347063Z Traceback (most recent call last):
2021-01-14T17:29:45.132441514Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 449, in wrapper
2021-01-14T17:29:45.153053869Z     ret = self._cache[fun]
2021-01-14T17:29:45.153537776Z AttributeError: _cache
2021-01-14T17:29:45.153620470Z 
2021-01-14T17:29:45.153628908Z During handling of the above exception, another exception occurred:
2021-01-14T17:29:45.153634369Z 
2021-01-14T17:29:45.153703765Z Traceback (most recent call last):
2021-01-14T17:29:45.154096866Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1515, in wrapper
2021-01-14T17:29:45.155119542Z     return fun(self, *args, **kwargs)
2021-01-14T17:29:45.155134714Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 452, in wrapper
2021-01-14T17:29:45.155300530Z     return fun(self)
2021-01-14T17:29:45.155309631Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1557, in _parse_stat_file
2021-01-14T17:29:45.155848009Z     with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
2021-01-14T17:29:45.155906187Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 713, in open_binary
2021-01-14T17:29:45.156105952Z     return open(fname, "rb", **kwargs)
2021-01-14T17:29:45.156162609Z FileNotFoundError: [Errno 2] No such file or directory: '/proc/11620/stat'
2021-01-14T17:29:45.156170987Z 
2021-01-14T17:29:45.156174732Z During handling of the above exception, another exception occurred:
2021-01-14T17:29:45.156178507Z 
2021-01-14T17:29:45.156181428Z Traceback (most recent call last):
2021-01-14T17:29:45.156184261Z   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-01-14T17:29:45.156435062Z     self.run()
2021-01-14T17:29:45.156496091Z   File "/opt/frigate/frigate/record.py", line 122, in run
2021-01-14T17:29:45.156995623Z     self.move_files()
2021-01-14T17:29:45.157005179Z   File "/opt/frigate/frigate/record.py", line 48, in move_files
2021-01-14T17:29:45.157155285Z     if process.name() != 'ffmpeg':
2021-01-14T17:29:45.157259791Z   File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 634, in name
2021-01-14T17:29:45.159125919Z     name = self._proc.name()
2021-01-14T17:29:45.159191606Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1515, in wrapper
2021-01-14T17:29:45.159953677Z     return fun(self, *args, **kwargs)
2021-01-14T17:29:45.160009505Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1610, in name
2021-01-14T17:29:45.160425829Z     name = self._parse_stat_file()['name']
2021-01-14T17:29:45.160435601Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1522, in wrapper
2021-01-14T17:29:45.160804532Z     raise NoSuchProcess(self.pid, self._name)
2021-01-14T17:29:45.160857132Z psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=11620)
```

**Comment by TheSleepySlee** [comment]
Faced same issue again. Adding logs in case different issue:
```
2021-01-15T23:52:29.006746694Z Exception in thread recording_maint:
2021-01-15T23:52:29.012216427Z Traceback (most recent call last):
2021-01-15T23:52:29.012237372Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 449, in wrapper
2021-01-15T23:52:29.016435864Z     ret = self._cache[fun]
2021-01-15T23:52:29.016462979Z AttributeError: _cache
2021-01-15T23:52:29.016468716Z 
2021-01-15T23:52:29.016473306Z During handling of the above exception, another exception occurred:
2021-01-15T23:52:29.016477503Z 
2021-01-15T23:52:29.016482039Z Traceback (most recent call last):
2021-01-15T23:52:29.016506456Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1515, in wrapper
2021-01-15T23:52:29.017476225Z     return fun(self, *args, **kwargs)
2021-01-15T23:52:29.017491841Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 452, in wrapper
2021-01-15T23:52:29.017617245Z     return fun(self)
2021-01-15T23:52:29.017625992Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1558, in _parse_stat_file
2021-01-15T23:52:29.017901531Z     data = f.read()
2021-01-15T23:52:29.018014485Z ProcessLookupError: [Errno 3] No such process
2021-01-15T23:52:29.018021401Z 
2021-01-15T23:52:29.018024734Z During handling of the above exception, another exception occurred:
2021-01-15T23:52:29.018028065Z 
2021-01-15T23:52:29.018031047Z Traceback (most recent call last):
2021-01-15T23:52:29.018033948Z   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
2021-01-15T23:52:29.019049809Z     self.run()
2021-01-15T23:52:29.019061689Z   File "/opt/frigate/frigate/record.py", line 122, in run
2021-01-15T23:52:29.019384693Z     self.move_files()
2021-01-15T23:52:29.019393307Z   File "/opt/frigate/frigate/record.py", line 48, in move_files
2021-01-15T23:52:29.019500994Z     if process.name() != 'ffmpeg':
2021-01-15T23:52:29.019509074Z   File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 634, in name
2021-01-15T23:52:29.020230753Z     name = self._proc.name()
2021-01-15T23:52:29.020242122Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1515, in wrapper
2021-01-15T23:52:29.020625080Z     return fun(self, *args, **kwargs)
2021-01-15T23:52:29.020632424Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1610, in name
2021-01-15T23:52:29.021174896Z     name = self._parse_stat_file()['name']
2021-01-15T23:52:29.021182696Z   File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1519, in wrapper
2021-01-15T23:52:29.021563987Z     raise NoSuchProcess(self.pid, self._name)
2021-01-15T23:52:29.021608388Z psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=32412)
```

**Comment by TheSleepySlee** [comment]
Looks like same issue 👍

**Comment by blakeblackshear** [comment]
This should be resolved in RC1

**Comment by TheSleepySlee** [comment]
Great, I have moved to rc1. Will let you know.
This was causing issues in my docker since filling up the disk.
