### ISSUE TITLE
[Config Support]: After 30 minute the camera's crush "no frames have been received"

### ISSUE THREAD

**Issue by antonbek89** [blakeblackshear/frigate#5365]
### Describe the problem you are having

The camera's working good some while (~30 minutes) and after that its look like its crush
When I going into server and doing htop command I got :
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
16897 root       20   0 4095M 3205M  5604 R 98.1 27.0 10:43.70 frigate.capture:LivingRoom
16881 root       20   0 4095M 3205M  5604 S 96.8 27.0 10:50.64 frigate.capture:LivingRoom
16890 root       20   0  531M 84720  1412 S 55.8  0.7 16:51.09 ffmpeg -hide_banner -loglevel warning -user_agent FFmpeg Frigate/0.12.0-66881eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://12716960 root       20   0  531M 84720  1412 S  4.5  0.7  0:31.02 ffmpeg -hide_banner -loglevel warning -user_agent FFmpeg Frigate/0.12.0-66881eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://12716963 root       20   0  531M 84720  1412 S  5.1  0.7  0:30.28 ffmpeg -hide_banner -loglevel warning -user_agent FFmpeg Frigate/0.12.0-66881eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://12716962 root       20   0  531M 84720  1412 S  4.5  0.7  0:30.84 ffmpeg -hide_banner -loglevel warning -user_agent FFmpeg Frigate/0.12.0-66881eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://12716961 root       20   0  531M 84720  1412 S  3.8  0.7  0:29.77 ffmpeg -hide_banner -loglevel warning -user_agent FFmpeg Frigate/0.12.0-66881eb -rtsp_transport tcp -timeout 5000000 -fflags nobuffer -flags low_delay -i rtsp://12723935 a          20   0  9328  5128  3196 R  1.9  0.0  0:16.86 htop
```
Its look like Livingroom camera killing the CPU

FFPROBE log:
`"[\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1080,\n          \"width\": 1920\n        }\n      ]\n    }\n  },\n  {\n    \"return_code\": 0,\n    \"stderr\": {},\n    \"stdout\": {\n      \"programs\": [],\n      \"streams\": [\n        {\n          \"avg_frame_rate\": \"0/0\",\n          \"codec_long_name\": \"H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10\",\n          \"height\": 1080,\n          \"width\": 1920\n        }\n      ]\n    }\n  }\n]"`
### Version

0.12 beta6

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.230
  user: "mqttuser"
  password: "password"


birdseye:
  enabled: True
  width: 1280
  height: 720
  quality: 15
  mode: continuous

detectors:
  coral:
    type: edgetpu
    device: usb   
    
go2rtc:
  streams:
    Hall:
      - rtsp://admin:password@192.168.1.106:8554/Streaming/Channels/101
      - ffmpeg:Hall#audio=opus
    Hall_sub: 
      - rtsp://admin:password@192.168.1.106:8554/Streaming/Channels/102
    LivingRoom:
      - rtsp://admin:password@192.168.1.103:8554/Streaming/Channels/101
      - ffmpeg:LivingRoom#audio=opus
    LivingRoom_sub: 
      - rtsp://admin:password@192.168.1.103:8554/Streaming/Channels/102
cameras:
  Hall:
    ffmpeg:
       inputs:
           - path:  rtsp://127.0.0.1:8554/Hall_sub?video=copy
             input_args: preset-rtsp-restream
             roles:
               - detect
           - path: rtsp://127.0.0.1:8554/Hall?video=copy&audio=aac
             input_args: preset-rtsp-restream
             roles:
               - record

    detect:
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: false
           
    objects:
      track:
        - person
      filters:
        person:
          threshold: 0.70
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 175
      retain:
        default: 14
 
    record:
      enabled: true
      retain_days: 1
      events:
        pre_capture: 5
        post_capture: 10
        objects:
          - person
        retain:
          default: 2

#####################################################LivingRoom################################
  LivingRoom:
    ffmpeg:
       inputs:
           - path:  rtsp://127.0.0.1:8554/LivingRoom?video=copy
             input_args: preset-rtsp-restream
             roles:
               - detect
           - path: rtsp://127.0.0.1:8554/LivingRoom?video=copy&audio=aac
             input_args: preset-rtsp-restream
             roles:
               - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    rtmp:
      enabled: false
           
    objects:
      track:
        - person
        - dog
      filters:
        person:
          threshold: 0.70
        dog:
          threshold: 0.70
        
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: false
      crop: False
      height: 500
      retain:
        default: 14
 
    record:
      enabled: true
      retain:
        days: 1
      events:
        pre_capture: 5
        post_capture: 10
        objects:
          - person
        retain:
          default: 2
    motion:
      mask:
        - 1221,174,1512,327,1591,99,1316,0,1290,0,1260,0
```

### Relevant log output

```shell
2023-02-03 11:16:52.133295184  [2023-02-03 13:16:52] frigate.app                    INFO    : Starting Frigate (0.12.0-66881eb)
2023-02-03 11:16:52.161964566  [2023-02-03 13:16:52] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
2023-02-03 11:16:52.172369543  [2023-02-03 13:16:52] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-02-03 11:16:52.174311511  [2023-02-03 13:16:52] peewee_migrate                 INFO    : Starting migrations
2023-02-03 11:16:52.180744448  [2023-02-03 13:16:52] peewee_migrate                 INFO    : There is nothing to migrate
2023-02-03 11:16:52.199073912  [2023-02-03 13:16:52] frigate.app                    INFO    : Output process started: 292
2023-02-03 11:16:52.206993108  [2023-02-03 13:16:52] frigate.app                    INFO    : Camera processor started for Hall: 297
2023-02-03 11:16:52.210378909  [2023-02-03 13:16:52] detector.coral                 INFO    : Starting detection process: 291
2023-02-03 11:16:52.210385033  [2023-02-03 13:16:52] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-02-03 11:16:52.213491116  [2023-02-03 13:16:52] frigate.app                    INFO    : Camera processor started for LivingRoom: 298
2023-02-03 11:16:52.218930311  [2023-02-03 13:16:52] frigate.app                    INFO    : Capture process started for Hall: 301
2023-02-03 11:16:52.239409793  [2023-02-03 13:16:52] frigate.app                    INFO    : Capture process started for LivingRoom: 302
2023-02-03 11:16:54.904788171  [2023-02-03 13:16:54] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-02-03 11:48:22.414414796  [2023-02-03 13:48:22] watchdog.LivingRoom            INFO    : LivingRoom exceeded fps limit. Exiting ffmpeg...
2023-02-03 11:48:22.415226312  [2023-02-03 13:48:22] watchdog.LivingRoom            INFO    : Waiting for ffmpeg to exit gracefully...
2023-02-03 11:48:22.427031791  [2023-02-03 13:48:22] watchdog.Hall                  INFO    : Hall exceeded fps limit. Exiting ffmpeg...
2023-02-03 11:48:22.432659797  [2023-02-03 13:48:22] watchdog.Hall                  INFO    : Waiting for ffmpeg to exit gracefully...
2023-02-03 11:49:15.003510801  Exception in thread Exception in thread Thread-7Thread-7:
2023-02-03 11:49:15.102833826  :
2023-02-03 11:49:27.152630457  Traceback (most recent call last):
2023-02-03 11:49:29.166721695  Traceback (most recent call last):
2023-02-03 11:49:39.580218120    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-02-03 11:49:39.619269204    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-02-03 11:59:46.664580378      self.run()
2023-02-03 11:59:46.700040473    File "/opt/frigate/frigate/video.py", line 283, in run
2023-02-03 11:59:47.323702548      self.ffmpeg_detect_process.communicate(timeout=30)
2023-02-03 11:59:47.324029648    File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
2023-02-03 11:59:47.811177084      stdout, stderr = self._communicate(input, endtime, timeout)
2023-02-03 11:59:47.811246224    File "/usr/lib/python3.9/subprocess.py", line 1974, in _communicate
2023-02-03 11:59:47.817771468      self._check_timeout(endtime, orig_timeout,
2023-02-03 11:59:47.817937169    File "/usr/lib/python3.9/subprocess.py", line 1180, in _check_timeout
2023-02-03 11:59:47.820004136      output=b''.join(stdout_seq) if stdout_seq else None,
2023-02-03 11:59:47.820368626  MemoryError
2023-02-03 11:59:48.048113595  [2023-02-03 13:59:46] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2023-02-03 11:59:48.048120759  [2023-02-03 13:59:47] root                           INFO    : Waiting for detection process to exit gracefully...
2023-02-03 11:59:48.447783727  [2023-02-03 13:59:48] detector.coral                 INFO    : Starting detection process: 3426
2023-02-03 11:59:49.717969954  [2023-02-03 13:59:48] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-02-03 11:59:52.184030871  [2023-02-03 13:59:52] frigate.record                 WARNING : Failed to probe corrupt segment LivingRoom-20230203135948.mp4: 0 - b'[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55b1609f16c0] moov atom not found\n/tmp/cache/Hall-20230203134853.mp4: Invalid data found when processing input\n'
2023-02-03 11:59:52.184039251  [2023-02-03 13:59:52] frigate.record                 WARNING : Discarding a corrupt recording segment: LivingRoom-20230203135948.mp4
2023-02-03 11:59:52.487168738  [2023-02-03 13:59:52] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
Yes, it's a known case and the reason for the log `LivingRoom exceeded fps limit. Exiting ffmpeg...`

**Comment by antonbek89** [comment]
> Yes, it's a known case and the reason for the log `LivingRoom exceeded fps limit. Exiting ffmpeg...`

What's its mean ?
How I can fix it via configuration ?
I limit the FPS to 5

**Comment by NickM-27** [comment]
> > Yes, it's a known case and the reason for the log `LivingRoom exceeded fps limit. Exiting ffmpeg...`
> 
> What's its mean ? How I can fix it via configuration ? I limit the FPS to 5

yes, and the camera sends bad data which causes the process to get stuck and fps to go too high so we have to exit ffmpeg and reconnect to the stream

**Comment by antonbek89** [comment]
> > > Yes, it's a known case and the reason for the log `LivingRoom exceeded fps limit. Exiting ffmpeg...`
> > 
> > 
> > What's its mean ? How I can fix it via configuration ? I limit the FPS to 5
> 
> yes, and the camera sends bad data which causes the process to get stuck and fps to go too high so we have to exit ffmpeg and reconnect to the stream

Its make the HA totally crush
After HA start again the camera with black screen on Frigate
In previous version 0.11 all working good

**Comment by NickM-27** [comment]
You don't need to use go2rtc as the source for frigate, you can still just connect frigate directly to the camera and that way you have the live views from go2rtc and frigate still connects to the camera the same way

**Comment by NickM-27** [comment]
you could also try just setting the input_args to `-rtsp_transport tcp -timeout 5000000` and see if that works
