### ISSUE TITLE
[Support]: can't get coral working

### ISSUE THREAD

**Issue by Heelderpeel** [blakeblackshear/frigate#5389]
### Describe the problem you are having

Hi, I'm new here and don't have much computer skills.
I had read that the google coral would be plug and play from HAS os 8.5, but I still can't get the coral to work.
First there were problems that the PI could not supply the current. so now i bought a powered hub (whitout backpowering).
But now I get the following error.
I hope someone can help me in simple language.

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
  host: x
  user: x
  password: x
  
detectors:
  coral:
    type: edgetpu
    device: usb

  
cameras:
  Keuken: 
    ffmpeg:
#      output_args:
#        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -ar 44100 -c:a aac
#        rtmp: -c:v copy -f flv -ar 44100 -c:a aac
      inputs:
        - path: rtsps://x unifi cam
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
      fps: 5

    objects:
      track:
        - person
        - dog
```

### Relevant log output

```shell
Process detector:coral:
[2023-02-05 19:40:13] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### FFprobe output from your camera

```shell
?
```

### Frigate stats

```json
?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G3 DOME

**Comment by Heelderpeel** [comment]
Found it, the full acces switch
