### ISSUE TITLE
[Config Support]: Cannot add go2rtc to config (beta)

### ISSUE THREAD

**Issue by reidprichard** [blakeblackshear/frigate#5501]
### Describe the problem you are having

If I add the go2rtc property to my config, the language server warns me that the property is not allowed. If I ignore it and add it anyway, Frigate throws a validation error as shown in log output below.

### Version

0.12.0-0dbf909

### Frigate config file

```yaml
# yaml-language-server: $schema=http://sanitized/api/config/schema.json

mqtt:
  host: sanitized
  user: sanitized
  password: sanitized

database:
  path: /database/frigate.db

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

ffmpeg:
  hwaccel_args: -c:v h264_cuvid

go2rtc:
  streams:
    office: rtsp://sanitized@sanitized/video1_unicast

cameras:
  office_cam:
    ffmpeg:
      inputs:
        - path: rtsp://sanitized@sanitized/video1_unicast
          roles:
            - record
```

### Relevant log output

```shell
2023-02-15 00:23:57.036186882  *************************************************************
2023-02-15 00:23:57.036203632  ***    Config Validation Errors                           ***
2023-02-15 00:23:57.036219512  *************************************************************
2023-02-15 00:23:57.036322352  1 validation error for FrigateConfig
2023-02-15 00:23:57.036337962  go2rtc
2023-02-15 00:23:57.036835702    extra fields not permitted (type=value_error.extra)
2023-02-15 00:23:57.037172912  Traceback (most recent call last):
2023-02-15 00:23:57.037194542    File "/opt/frigate/frigate/app.py", line 335, in start
2023-02-15 00:23:57.037219542      self.init_config()
2023-02-15 00:23:57.037242182    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-02-15 00:23:57.037265632      user_config = FrigateConfig.parse_file(config_file)
2023-02-15 00:23:57.037290572    File "/opt/frigate/frigate/config.py", line 1019, in parse_file
2023-02-15 00:23:57.037309482      return cls.parse_obj(config)
2023-02-15 00:23:57.037333532    File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
2023-02-15 00:23:57.037357532    File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
2023-02-15 00:23:57.037376662  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2023-02-15 00:23:57.037402072  go2rtc
2023-02-15 00:23:57.037422842    extra fields not permitted (type=value_error.extra)
2023-02-15 00:23:57.037621682  
2023-02-15 00:23:57.037817822  *************************************************************
2023-02-15 00:23:57.037993502  ***    End Config Validation Errors                       ***
2023-02-15 00:23:57.038170982  *************************************************************
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

I tried this on `0.12.0-beta2-tensorrt` first. I've also tried with no values under the "go2rtc:" property.

**Comment by blakeblackshear** [comment]
Beta2 is an old beta that didn't have the go2rtc config yet. We are on beta8 now.

**Comment by blakeblackshear** [comment]
Also, your config is missing any detect related roles and settings. If you don't include the detect role, it gets automatically inserted. Also, because you haven't specified a detect resolution, ffmpeg is just going to resize your stream to the default of 720p. I recommend following the guide in the docs: https://deploy-preview-4055--frigate-docs.netlify.app/guides/getting_started

**Comment by NickM-27** [comment]
> Thanks for the help - well that's a dumb mistake to make. I guess I'm just a Docker noob - is the [Docker Hub page](https://hub.docker.com/r/blakeblackshear/frigate/tags) for a project not where images come from? I figured it must be since I didn't see a release tagged "stable" on GitHub.
> 
> Appreciate the advice on detect settings - I pruned out everything but the bare bones for troubleshooting but will definitely add that.

dockerhub has been used in the past but as it says at the top of the dockerhub page it is no longer in use for 0.12

https://github.com/blakeblackshear/frigate/pkgs/container/frigate

![Screen Shot 2023-02-15 at 08 35 26 AM](https://user-images.githubusercontent.com/14866235/219074952-ce4489bb-d22a-4dfb-9193-9395fcf49768.png)
