### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by avico78** [blakeblackshear/frigate#5548]
### Describe the problem you are having

Upgrading from frigate:0.12.0-beta2 -> frigate:0.12.0-beta8
 /database deleted before upgrade

1.No Audio for Dahua Dorbell both webrtc and mse,
Tried opus/aac with no difference

```
go2rtc:
  streams:
       intercom: 
      - rtsp://aaaa:bbbb@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:intercom#audio=opus # also tried with =aac
```

ffprobe:

```
[ { "return_code": 0, "stderr": {}, "stdout": { "programs": [], "streams": [ { "avg_frame_rate": "25/1", "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10", "height": 720, "width": 1280 } ] } } ]
```

2.error in log (log section).

Note sure if it is still required to keep separate config file for go2rtc in docker-compose
```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/frigate.yml:/config/config.yml:ro
      - ./frigate/NAS:/media/frigate
      - ./frigate/database:/db
     - ./frigate/go2rtc.yaml:/config/frigate-go2rtc.yaml:ro   # ???

```
or instead put it in frigate.yaml?
Not , sure if frigate IP is required ?
(previously was listen: ":8555")
```
  webrtc:
    candidates:
      - 192.168.1.3:8555
      - stun:8555
```

### Version

 0.12.0 Beta8

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.113
  port: 1883


database:
  path: /db/frigate.db

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu


go2rtc:
  streams:
    salon_ceiling: # <- for RTSP streams
      - rtsp://aaaaa:bbbbbb@192.168.1.138/cam/realmonitor?channel=1&subtype=0 
      - ffmpeg:salon_ceiling#audio=opus 

  webrtc:
    candidates:
      - 192.168.1.3:8555
      - stun:8555

cameras:

  salon_ceiling:
    
    ffmpeg:
      global_args: -hide_banner -loglevel warning
      hwaccel_args: preset-vaapi
      inputs:
          - path: rtsp://127.0.0.1:8554/salon_ceiling
            input_args: preset-rtsp-restream
            roles:
            - record
            - detect 
            

    objects:
      track:
        - person
        - dog

    birdseye:
      mode: objects

    motion:
      mask:
        - 1920,1080,1747,710,1512,429,1588,0,1920,0
        - 1920,0,1920,183,932,132,681,141,389,174,0,185,0,0

    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100    
      height: 500
      required_zones:
        - ceiling_door
        - ceiling_salon
        - ceiling_hall

    detect:
      height: 1080
      width: 1920
      fps: 5      

    zones:
      ceiling_door:
        coordinates: 163,578,392,628,470,626,472,769,45,757
      ceiling_salon:
        coordinates: 1679,1080,988,1080,918,1080,925,683,762,585,764,330,824,212,1108,218,1526,251,1732,663,1791,766,1813,836,1723,878
      ceiling_hall:
        coordinates: 411,725,698,758,670,424,588,424

    snapshots:
      enabled: True
      timestamp: True
      required_zones:
        - ceiling_door
        - ceiling_salon
        - ceiling_hall
      # height: 175
      retain:
        # Required: Default retention days (default: shown below)
        default: 3
        
        objects:
          person: 5

    record:
      enabled: True
      retain:
        days: 5
        mode: motion
      events:
        pre_capture: 2
        post_capture: 2      
        retain:
          default: 5
          mode: active_objects
    live:
      stream_name: salon_ceiling
```

### Relevant log output

```shell
2023-02-20 10:36:27.915449594  [2023-02-20 10:36:27] frigate.http                   ERROR   : Exception on /salon_ceiling/latest.jpg [GET]
2023-02-20 10:36:27.915454084  Traceback (most recent call last):
2023-02-20 10:36:27.915457204    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2525, in wsgi_app
2023-02-20 10:36:27.915459823      response = self.full_dispatch_request()
2023-02-20 10:36:27.915462459    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1822, in full_dispatch_request
2023-02-20 10:36:27.915467991      rv = self.handle_user_exception(e)
2023-02-20 10:36:27.915470314    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1820, in full_dispatch_request
2023-02-20 10:36:27.915504481      rv = self.dispatch_request()
2023-02-20 10:36:27.915507288    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1796, in dispatch_request
2023-02-20 10:36:27.915531376      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-02-20 10:36:27.915533880    File "/opt/frigate/frigate/http.py", line 864, in latest_frame
2023-02-20 10:36:27.915536633      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-02-20 10:36:27.915539547  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-02-20 10:36:27.915552323  
```
```


### Frigate stats

_No response_

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

Dahua 4Mb set to 1080P + AAC

**Comment by NickM-27** [comment]
1. Where was the ffprobe from? It doesn't have audio which means the camera itself likely isn't returning audio. 

2. No, the separate file does nothing. You should still set the WebRTC candidates in the frigate go2rtc config.

**Comment by blakeblackshear** [comment]
The docs have all been updated. A separate file is no longer required for go2rtc config. https://deploy-preview-4055--frigate-docs.netlify.app/configuration/live/#webrtc-extra-configuration
