### ISSUE TITLE
[Support]: Frigate 0.12 Beta8 container fails to start (modules not found)

### ISSUE THREAD

**Issue by MrPlatnum** [blakeblackshear/frigate#5622]
### Describe the problem you are having

I tried to start the new beta 8 image but it wont start the container. It tells me that there is no module named flasked and yaml.

### Version

Frigate 0.12 beta version 8: ghcr.io/blakeblackshear/frigate:0.12.0-beta8

### Frigate config file

```yaml
/
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
[INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[INFO] Starting Frigate...
[INFO] Starting NGINX...
2023-03-01 19:34:37.142411012  Traceback (most recent call last):
2023-03-01 19:34:37.142523594    File "/usr/lib/btbn-ffmpeg/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-03-01 19:34:37.142614300      return _run_code(code, main_globals, None,
2023-03-01 19:34:37.142618967    File "/usr/lib/btbn-ffmpeg/lib/python3.10/runpy.py", line 86, in _run_code
2023-03-01 19:34:37.142621300      exec(code, run_globals)
2023-03-01 19:34:37.142627425    File "/opt/frigate/frigate/__main__.py", line 2, in <module>
2023-03-01 19:34:37.142631217      from flask import cli
2023-03-01 19:34:37.142634133  ModuleNotFoundError: No module named 'flask'
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
s6-rc: info: service legacy-services successfully started
Service go2rtc exited with code 1 (by signal 0)
Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
/
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

/

### Any other information that may be helpful

I use a custom ffmpeg and mounted it to the container. I also tried it without the mount and it still would not work.

**Comment by NickM-27** [comment]
Please read the release notes, this is covered 

> Some deployment approaches are overwriting the PATH environment value to an old value. If you see errors like ./run: line 7: exec: nginx: not found, then you need to stop overriding your PATH. This happens with both Proxmox LXC and Portainer (#3223 the database will need to be deleted to roll-back successfully.

**Comment by MrPlatnum** [comment]
It does indeed override my PATH variable but i dont use portainer nor proxmox so i dont know where it is comming from.

**Comment by NickM-27** [comment]
What does your compose look like?

**Comment by MrPlatnum** [comment]
The output of eoch $PATH inside the container is:

root@e093559a7eb5:/opt/frigate# echo $PATH
/usr/lib/btbn-ffmpeg/bin:/usr/local/go2rtc/bin:/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

so is it really overwriting it?

**Comment by MrPlatnum** [comment]
My compose looks like:

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-beta8
    shm_size: "4gb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128
      - /dev/dri/card0 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/server/docker/frigate/config.yml:/config/config.yml
      - /mnt/media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "698763"

**Comment by NickM-27** [comment]
Where is your ffmpeg bind mount?

`usr/lib/btbn-ffmpeg/lib/python3.10/runpy.py` is very wrong and seems weird. 

What system arch are you running on?

**Comment by NickM-27** [comment]
> Sorry i removed it for testing. (removed and restarted container without the bind) it looks like this:
> 
> ```
>   - /usr:/usr/lib/btbn-ffmpeg:ro
> ```
> 
> It worked as a charm under 0.11.
> 
> I use a Ubuntu version of Armbian on the Orange Pi 5

This is definitely what is causing the problem. You should only map the bin directly, which is what the docs suggest https://docs.frigate.video/configuration/advanced#custom-ffmpeg-build

Your system python is getting injected into the container causing confusion. I do not know why removing the bind mount isn't fixing it, but the logs are clear it is pointing to a python file inside the `/btbn-ffmpeg/lib` which does not exist under normal running circustances
