### ISSUE TITLE
Send to Frigate+ Hangs

### ISSUE THREAD

**Issue by ccutrer** [blakeblackshear/frigate#5669]
### Describe the problem you are having

Apparently I've run into a limit of how many images I can upload to Frigate+. At https://plus.frigate.video/dashboard/add-image/, it says "New users are limited to 100 images.". However, in my local Frigate installation, when I click "Send to Frigate+", it switches to "Uploading..." and just stays there forever, with no indication of failure. The log indicates an error decoding the (presumably error) response from Frigate+

### Version

0.12.0-27A31E7

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
2023-03-07 14:34:01.502008258  [2023-03-07 14:34:01] frigate.http                   ERROR   : Expecting value: line 1 column 1 (char 0)
2023-03-07 14:34:01.502013423  Traceback (most recent call last):
2023-03-07 14:34:01.502015311    File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 971, in json
2023-03-07 14:34:01.502016750      return complexjson.loads(self.text, **kwargs)
2023-03-07 14:34:01.502018229    File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
2023-03-07 14:34:01.502019457      return _default_decoder.decode(s)
2023-03-07 14:34:01.502020770    File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
2023-03-07 14:34:01.502022163      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-03-07 14:34:01.502023686    File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
2023-03-07 14:34:01.502025061      raise JSONDecodeError("Expecting value", s, err.value) from None
2023-03-07 14:34:01.502026493  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-03-07 14:34:01.502027599  
2023-03-07 14:34:01.502029119  During handling of the above exception, another exception occurred:
2023-03-07 14:34:01.502030166  
2023-03-07 14:34:01.502031477  Traceback (most recent call last):
2023-03-07 14:34:01.502040106    File "/opt/frigate/frigate/http.py", line 206, in send_to_plus
2023-03-07 14:34:01.502042208      plus_id = current_app.plus_api.upload_image(image, event.camera)
2023-03-07 14:34:01.502043952    File "/opt/frigate/frigate/plus.py", line 87, in upload_image
2023-03-07 14:34:01.502045619      presigned_urls = r.json()
2023-03-07 14:34:01.502047597    File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
2023-03-07 14:34:01.502049457      raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2023-03-07 14:34:01.502051462  requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
You'll need to email the support link on the website to get it increased. Not sure what the response is exactly from frigate+

**Comment by ccutrer** [comment]
I've emailed asking for an increase, but this ticket is specifically to handle the error condition better. It took me several days of reviewing events and sending to Frigate+ hanging for me to even realize it was a problem that _could_ be addressed, and not just Frigate+'s upload API being broken or my API key being bad or something.

**Comment by blakeblackshear** [comment]
I'm planning to just remove that limit anyway.
