### ISSUE TITLE
[Detector Support]: Mixing coral and TensorRT - possible?

### ISSUE THREAD

**Issue by szupi-ipuzs** [blakeblackshear/frigate#5670]
### Describe the problem you are having

Hi,
I am using Beta9 and I recently managed to setup TensorRT (GeForce GTX 950) as detector using your instructions. Seems to be working fine!
I also have a Coral (USB), which I previously managed to setup as detector - was working fine as well.
So what's the problem? I cannot seem to enable both of them at the same time. When I do, Frigate crashes at startup saying "No EdgeTPU was detected". But one line earlier it does say it has detected it. This is confusing... 
I suspect that the power needed to run both at the same time is simply too much for my "gaming" PC and the Corall gets disconnected. How can I check this is the case? I'm running ubuntu 22.04.

### Version

0.12.0-e8d8cc4

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.111
detectors:
    coral:
      type: edgetpu
      device: usb
    tensorrt:
      type: tensorrt
      device: 0
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
motion:
  contour_area: 15
cameras:
  gatewatcher:
    motion:
      improve_contrast: True
    rtmp:
      enabled: false
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bird
        - bicycle
        - motorcycle
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - +genpts+discardcorrupt
        - -flags
        - low_delay
        - -strict
        - experimental
        - -analyzeduration
        - 1000M
        - -probesize
        - 1000M
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/gatewatcher?video=all&audio=all
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/gatewatcher_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles: []
    detect:
      width: 2048
      height: 1536
      fps: 6
    record:
      enabled: true
      events:
        pre_capture: 5
        post_capture: 5
        retain:
          default: 7
        objects:
          - person
          - car
          - dog
    snapshots:
      enabled: true
    live:
      height: 1536
  salon:
    motion:
      improve_contrast: True
    rtmp:
      enabled: False
    objects:
      track:
        - person
        - dog
        - cat
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/salon?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
        - path: rtsp://127.0.0.1:8554/salon_sub?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles: []
    detect:
      width: 2560
      height: 1440
      fps: 6
    snapshots:
      enabled: true
    live:
      height: 1440
  # birdfeeder:
  #   motion:
  #     improve_contrast: True
  #   rtmp:
  #     enabled: False
  #   objects:
  #     track:
  #       - person
  #       - dog
  #       - cat
  #       - bird
  #   ffmpeg:
  #     hwaccel_args: preset-nvidia-h264
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/birdfeeder?video=copy&audio=aac
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #           - detect
  #   detect:
  #     width: 640
  #     height: 360
  #     fps: 5
  #   record:
  #     enabled: true
  #     events:
  #       pre_capture: 2
  #       post_capture: 2
  #       retain:
  #         default: 7
  #       objects:
  #         - person
  #         - dog
  #         - cat
  #         - bird
  #   snapshots:
  #     enabled: true
birdseye:
  enabled: False
go2rtc:
  streams:
    gatewatcher:
      - http://192.168.2.216/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_RTSP_USER}&password={FRIGATE_RTSP_PASSWORD}
      - "ffmpeg:gatewatcher#audio=opus"
    gatewatcher_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.216:554/h264Preview_01_sub
      - "ffmpeg:gatewatcher_sub#audio=opus"
    salon:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.230:554/h264Preview_01_main
      - "ffmpeg:salon#audio=opus"
    salon_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.2.230:554/h264Preview_01_sub
      - "ffmpeg:salon_sub#audio=opus"
    # birdfeeder:
    #   - echo:/config/get_ha_stream.sh camera.smart_bird_feeder_camera
    #   - "ffmpeg:birdfeeder#audio=aac"
  webrtc:
    candidates:
      - 192.168.2.5:8555
      - stun:8555
```

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate \
        --privileged \
        --restart=unless-stopped \
        --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
        --device /dev/bus/usb:/dev/bus/usb \
        --device /dev/dri/renderD128 \
        --shm-size=200m \
        -v /home/user/frigate/storage:/media/frigate \
        -v /home/user/frigate/config:/config \
        -v /home/user/frigate/trt-models:/trt-models \
        -v /etc/localtime:/etc/localtime:ro \
        -p 5000:5000 -p 1984:1984 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp \
        -e FRIGATE_RTSP_USER=redacted \
        -e FRIGATE_RTSP_PASSWORD=redacted \
        -e YOLO_MODELS=yolov4-tiny-288,yolov4-tiny-416,yolov7-tiny-416 \
        --gpus=all \
```

### Relevant log output

```shell
2023-03-07 20:49:37.112742811  [INFO] Starting Frigate...
2023-03-07 20:49:38.530059786  [2023-03-07 20:49:38] frigate.app                    INFO    : Starting Frigate (0.12.0-e8d8cc4)
2023-03-07 20:49:38.575588274  [2023-03-07 20:49:38] peewee_migrate                 INFO    : Starting migrations
2023-03-07 20:49:38.580758534  [2023-03-07 20:49:38] peewee_migrate                 INFO    : There is nothing to migrate
2023-03-07 20:49:38.607487119  [2023-03-07 20:49:38] detector.coral                 INFO    : Starting detection process: 432
2023-03-07 20:49:38.619867963  [2023-03-07 20:49:38] frigate.app                    INFO    : Output process started: 437
2023-03-07 20:49:38.632447374  [2023-03-07 20:49:38] frigate.app                    INFO    : Camera processor started for gatewatcher: 442
2023-03-07 20:49:38.653485472  [2023-03-07 20:49:38] frigate.app                    INFO    : Camera processor started for salon: 444
2023-03-07 20:49:38.654973688  [2023-03-07 20:49:38] frigate.app                    INFO    : Capture process started for gatewatcher: 445
2023-03-07 20:49:38.665716091  [2023-03-07 20:49:38] frigate.app                    INFO    : Capture process started for salon: 449
2023-03-07 20:49:38.922060239  [2023-03-07 20:49:38] detector.tensorrt              INFO    : Starting detection process: 434
2023-03-07 20:49:39.411687986  [2023-03-07 20:49:39] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +187, GPU +0, now: CPU 244, GPU 102 (MiB)
2023-03-07 20:49:39.438783013  [2023-03-07 20:49:39] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 35 MiB
2023-03-07 20:49:39.855503186  [2023-03-07 20:49:39] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +181, GPU +70, now: CPU 489, GPU 208 (MiB)
2023-03-07 20:49:40.091431574  [2023-03-07 20:49:40] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +111, GPU +46, now: CPU 600, GPU 254 (MiB)
2023-03-07 20:49:40.112632753  [2023-03-07 20:49:40] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +34, now: CPU 0, GPU 34 (MiB)
2023-03-07 20:49:40.115302018  [2023-03-07 20:49:40] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 564, GPU 246 (MiB)
2023-03-07 20:49:40.115522419  [2023-03-07 20:49:40] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 564, GPU 254 (MiB)
2023-03-07 20:49:40.115755652  [2023-03-07 20:49:40] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +13, now: CPU 0, GPU 47 (MiB)
2023-03-07 20:49:41.894087867  [2023-03-07 20:49:38] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-03-07 20:49:41.895931282  Process detector:coral:
2023-03-07 20:49:41.895933903  [2023-03-07 20:49:41] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-03-07 20:49:41.896181832  [2023-03-07 20:49:41] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-03-07 20:49:41.898429583  Traceback (most recent call last):
2023-03-07 20:49:41.898579004    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-03-07 20:49:41.898587060      self.run()
2023-03-07 20:49:41.898591218    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-03-07 20:49:41.898598890      self._target(*self._args, **self._kwargs)
2023-03-07 20:49:41.898605319    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-03-07 20:49:41.898637026      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-03-07 20:49:41.898668914    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-03-07 20:49:41.898672852      self.detect_api = create_detector(detector_config)
2023-03-07 20:49:41.898676216    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-03-07 20:49:41.898679091      return api(detector_config)
2023-03-07 20:49:41.898682495    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 39, in __init__
2023-03-07 20:49:41.898685515      self.interpreter = Interpreter(
2023-03-07 20:49:41.898689076    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
2023-03-07 20:49:41.898694236      _interpreter_wrapper.CreateWrapperFromFile(
2023-03-07 20:49:41.898697365  ValueError: Model provided has model identifier '
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

**Comment by NickM-27** [comment]
Running different detector types is not supported for 0.12

**Comment by szupi-ipuzs** [comment]
Thanks for quick answer. Is this feature planned for the future? Just wanted to know if I should keep both the Coral and the Nvidia or get rid of one :)

**Comment by NickM-27** [comment]
Yes this is planned for the future.

**Comment by szupi-ipuzs** [comment]
Can't wait! Thanks!

**Comment by NickM-27** [comment]
By the way you should still be using the Nvidia GPU for hwaccel
