### ISSUE TITLE
[Detector Support]: Coral on k8s not detected

### ISSUE THREAD

**Issue by SchoolGuy** [blakeblackshear/frigate#5765]
### Describe the problem you are having

Coral is not detected properly. When running the following pycoral with the container it can detect the USB though (see further information).

### Version

0.11.1

### Frigate config file

```yaml
mqtt:
      host: mosquitto.mqtt.svc.cluster.local
    detectors:
      coral:
        type: edgetpu
        device: usb
    cameras:
      garden_dolly:
        ffmpeg:
          input_args:
            - -avoid_negative_ts
            - make_zero
            - -fflags
            - +genpts+discardcorrupt
            - -flags
            - low_delay
            - -strict
            - experimental
            - -analyzeduration
            - 1000M
            - -probesize
            - 1000M
            - -rw_timeout
            - "5000000"
          inputs:
            - path: http://1.1.1.1/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=viewer&password=mypass
              roles:
                - record
                - rtmp
            - path: http://1.1.1.1/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=viewer&password=mypass
              roles:
                - detect
        detect:
          width: 1280
          height: 720
      garden_igel:
        ffmpeg:
          inputs:
            - path: rtsp://admin:mypass@1.1.1.1:554/h264_stream
              roles:
                - detect
                - rtmp
                - record
        rtmp:
          enabled: False
        detect:
          width: 1280
          height: 720
```

### docker-compose file or Docker CLI command

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: frigate
    component: application
  name: frigate-app
  namespace: frigate
spec:
  selector:
    matchLabels:
      app: frigate
  serviceName: "frigate"
  template:
    metadata:
      labels:
        app: frigate
        component: application
    spec:
      containers:
        - image: docker.io/blakeblackshear/frigate:0.11.1
          imagePullPolicy: IfNotPresent
          name: frigate
          volumeMounts:
          - name: frigate-conf-volume
            mountPath: /config/config.yml
            subPath: config.yml
            readOnly: True
          - name: frigate-storage
            mountPath: /media/frigate
          - name: dshm
            mountPath: /dev/shm
          - mountPath: /dev/bus/usb
            name: usb
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              memory: 1Gi
      volumes:
        - name: frigate-conf-volume
          configMap:
            name: frigate-conf
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 64M
        - name: usb
          hostPath:
            path: /dev/bus/usb/001/001
  volumeClaimTemplates:
    - metadata:
        name: frigate-storage
        annotations:
          k8up.io/backup: "false"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 500Gi
```

### Relevant log output

```shell
[2023-03-17 21:31:47] frigate.edgetpu                ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 135, in run_detector
    object_detector = LocalObjectDetector(
  File "/opt/frigate/frigate/edgetpu.py", line 43, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Operating system

Other Linux

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Shell Output:

```
root@command-demo:/opt/frigate# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycoral.utils.edgetpu import list_edge_tpus
>>> print(list_edge_tpus(), flush=True)
[{'type': 'usb', 'path': '/sys/bus/usb/devices/1-1'}]
```

Pod config:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: docker.io/blakeblackshear/frigate:0.11.1
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
      - mountPath: /dev/bus/usb
        name: usb
  volumes:
    - name: usb
      hostPath:
        path: /dev/bus/usb/001/001
```

**Comment by blakeblackshear** [comment]
They both use the same libraries. Not sure why this would happen. It is generally an issue with permissions, power to the device, or passing the device to the container incorrectly. The helm chart should work for 0.11.1. Are you using the same pod configuration that the chart uses to pass the USB device?

**Comment by SchoolGuy** [comment]
I am not aware of a recommended Helmchart atm (at least Artifacthub doesn't have one listed that looks official). Thus I just wrote my own little YAML file that you see above. Configuration happens via a `ConfigMap`. Since I have decided to use the same image and both Pods run on the same host a configuration issue seems unlikely to me.

Host OS is openSUSE MicroOS and on top of that, I am using k3s. Mounting an arbitrary host path should however not be problematic, shouldn't it?

**Comment by blakeblackshear** [comment]
https://github.com/blakeblackshear/blakeshome-charts

**Comment by SchoolGuy** [comment]
I will switch right over. Is is possible to run Frigate+ via this chart as well? I want to create a custom model later down the road. :)

**Comment by blakeblackshear** [comment]
You can set an env var with it in the values under `env` to integrate with Frigate+. Frigate+ isnt something you "run". It's a service that you can submit examples to for model training.

**Comment by SchoolGuy** [comment]
Using your HelmChart I was able to load the TPU. I suspect that indeed on my `StatefulSet` I was missing permissions. Your deployment has the privileged option enabled which was missing from my YAMLs. Thanks for leading me on the correct track.

**Comment by SchoolGuy** [comment]
I consider this issue closed and completed.

**Comment by b2un0** [comment]
litte not, if you don't want to run frigate with `priviliged: true` use these k8s plugin
https://github.com/h-s-c/edge-device-plugin
