### ISSUE TITLE
Home Assistant Error

### ISSUE THREAD

**Issue by grego1981** [blakeblackshear/frigate#580]
Hi all! I have installed the home assistant plugin and trying to make it work with one RTSP camera in the beggining. I have tried to follow the configuration example but the plugin does not start. Can you help me make it work? In the logs 

I have the following error:

```
Fontconfig error: Cannot load default config file
On connect called
Traceback (most recent call last):
  File "detect_objects.py", line 441, in <module>
    main()
  File "detect_objects.py", line 202, in main
    ffmpeg_output_args = ["-r", str(config.get('fps'))] + ffmpeg_output_args
TypeError: can only concatenate list (not "NoneType") to list
Starting detection process: 20
```

My config:

```
web_port: 5000
detectors:
  coral:
    type: edgetpu
    device: usb
save_clips:
  max_seconds: 300
  clips_dir: /clips
  cache_dir: /cache
mqtt:
  host: 10.10.10.3
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt
  password: password
ffmpeg:
  global_args:
    - '-hide_banner'
    - '-loglevel'
    - panic
  hwaccel_args:
    - '-hwaccel'
    - vaapi
    - '-hwaccel_device'
    - /dev/dri/renderD128
    - '-hwaccel_output_format'
    - yuv420p
  input_args:
    - '-avoid_negative_ts'
    - make_zero
    - '-fflags'
    - nobuffer
    - '-flags'
    - low_delay
    - '-strict'
    - experimental
    - '-fflags'
    - +genpts+discardcorrupt
    - '-rtsp_transport'
    - tcp
    - '-stimeout'
    - '5000000'
    - '-use_wallclock_as_timestamps'
    - '1'
  output_args:
    - '-f'
    - rawvideo
    - '-pix_fmt'
    - yuv420p
cameras:
  lroom:
    ffmpeg:
      input: 'rtsp://10.10.10.47/unicast'
      global_args: null
      hwaccel_args: null
      input_args: null
      output_args: null
    height: 1080
    width: 1920
    fps: 5
    mask: 'poly,0,900,1080,900,1080,1920,0,1920'
    best_image_timeout: 120
    mqtt:
      crop_to_region: true
      snapshot_height: 300
    zones:
      lroom_door:
        coordinates: '545,1077,747,939,788,805'
        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.8
    save_clips:
      enabled: false
      pre_capture: 30
      objects:
        - person
    snapshots:
      show_timestamp: true
      draw_zones: false
      draw_bounding_boxes: true
    objects:
      track:
        - person
      filters:
        person:
          min_area: 5000
          max_area: 100000
          min_score: 0.5
          threshold: 0.85
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_score: 0.5
      threshold: 0.85
```

**Comment by blakeblackshear** [comment]
I would recommend using the beta version at this point. The official release is very close, and you will have to rework a good bit of your config to update.

**Comment by grego1981** [comment]
Just did the transition to beta, with the same config I got the error:
` * Starting nginx nginx
   ...done.
Error parsing config: expected a dictionary for dictionary value @ data['ffmpeg']['output_args']`

Though the addon started I went to the web panel and saw the image below which doesn't  change. 
![image](https://user-images.githubusercontent.com/9021998/105508260-d9b0d900-5cd4-11eb-8a22-65900a01525c.png)

After a while though, it stopped working.... and it doesn't start again

Do I need to change something in the config? Is there a minimal 'safe' config to start with so as to add options as I go?

**Comment by blakeblackshear** [comment]
Lots of required changes. See updated docs: https://blakeblackshear.github.io/frigate/

**Comment by grego1981** [comment]
Thank you ! I'll try my luck there!

**Comment by tubalainen** [comment]
> Thank you ! I'll try my luck there!

A friendly tip - start with the bare minimum in your config, make sure that all indentations are correct and move on from there. :)
Have a nice weekend!
