### ISSUE TITLE
[Detector Support]: TensorRT libraries not found

### ISSUE THREAD

**Issue by weswitt** [blakeblackshear/frigate#5810]
### Describe the problem you are having

i followed the instructions for getting everything setup for nvidia gpu detector (tensor). when i run the frigate docker container i get the error message: "TensorRT libraries not found, tensorrt detector not present". 

### Version

0.12

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### docker-compose file or Docker CLI command

```yaml
docker run --rm --name frigate --privileged --shm-size=512m -v /dev/bus/usb:/dev/bus/usb -v /etc/localtime:/etc/localtime:ro -v /opt/frigate/config/config.yml:/config/config.yml:ro -v /opt/frigate/trt-models:/trt-models:ro -v /opt/frigate/media:/media/frigate:rw -e USE_FP16=False -p 5000:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp -e FRIGATE_RTSP_PASSWORD='password' ghcr.io/blakeblackshear/frigate:0.12.0-beta10
```

### Relevant log output

```shell
2023-03-22 22:09:51.449389085  [2023-03-22 22:09:51] frigate.app                    INFO    : Output process started: 724
2023-03-22 22:09:51.449697586  Traceback (most recent call last):
2023-03-22 22:09:51.449712634    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-03-22 22:09:51.449714050      self.run()
2023-03-22 22:09:51.449715410    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-03-22 22:09:51.449716717      self._target(*self._args, **self._kwargs)
2023-03-22 22:09:51.449718065    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-03-22 22:09:51.449719421      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-03-22 22:09:51.449724093    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-03-22 22:09:51.449733423      self.detect_api = create_detector(detector_config)
2023-03-22 22:09:51.449744153    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-03-22 22:09:51.449745235      return api(detector_config)
2023-03-22 22:09:51.449746409    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 198, in __init__
2023-03-22 22:09:51.449747434      assert (
2023-03-22 22:09:51.449748763  AssertionError: TensorRT libraries not found, tensorrt detector not present
2023-03-22 22:09:51.449755820  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f54694ac5e0>
2023-03-22 22:09:51.449761203  Traceback (most recent call last):
2023-03-22 22:09:51.449762561    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-03-22 22:09:51.449863414      if self.outputs is not None:
2023-03-22 22:09:51.449870823  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
```

### Operating system

HassOS

### Install method

Docker CLI

### Coral version

USB

**Comment by andreipopovici** [comment]
Docs seem to be fine, but I get a similar error using the tensorrt image you just mentioned above:

```
2023-03-23 16:02:37.249503832  [2023-03-23 16:02:37] frigate.detectors.plugins.tensorrt ERROR   : ERROR: failed to load libraries. libcudart.so.12: cannot open shared object file: No such file or directory
2023-03-23 16:02:43.906237724  [2023-03-23 16:02:43] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +188, GPU +0, now: CPU 239, GPU 143 (MiB)
2023-03-23 16:02:43.929025444  [2023-03-23 16:02:43] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 34 MiB
2023-03-23 16:02:43.953339693  [2023-03-23 16:02:43] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::40] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 213, Serialized Engine Version: 232)
2023-03-23 16:02:43.964471529  [2023-03-23 16:02:43] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
2023-03-23 16:02:43.965148602  Process detector:tensorrt:
2023-03-23 16:02:44.001473835  Traceback (most recent call last):
2023-03-23 16:02:44.001511920    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-03-23 16:02:44.001514428      self.run()
2023-03-23 16:02:44.001533773    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-03-23 16:02:44.001536182      self._target(*self._args, **self._kwargs)
2023-03-23 16:02:44.001538267    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-03-23 16:02:44.001540106      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-03-23 16:02:44.001542847    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-03-23 16:02:44.001561138      self.detect_api = create_detector(detector_config)
2023-03-23 16:02:44.001582860    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-03-23 16:02:44.001586512      return api(detector_config)
2023-03-23 16:02:44.001588301    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 220, in __init__
2023-03-23 16:02:44.001590587      self.input_shape = self._get_input_shape()
2023-03-23 16:02:44.001643001    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 92, in _get_input_shape
2023-03-23 16:02:44.001662345      binding = self.engine[0]
2023-03-23 16:02:44.001664969  TypeError: 'NoneType' object is not subscriptable
2023-03-23 16:02:44.001666996  Exception ignored in: <function TensorRtDetector.__del__ at 0x1552abdbd8b0>
2023-03-23 16:02:44.001668456  Traceback (most recent call last):
2023-03-23 16:02:44.001716671    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-03-23 16:02:44.001915122      if self.outputs is not None:
2023-03-23 16:02:44.001938812  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
```

**Comment by NickM-27** [comment]
@andreipopovici This is a different config error usually due to not mapping the models correctly https://github.com/blakeblackshear/frigate/issues/5058

**Comment by andreipopovici** [comment]
@NickM-27 models are mapped fine, it's a different file missing:

```
ERROR: failed to load libraries. libcudart.so.12: cannot open shared object file: No such file or directory
```

**Comment by NickM-27** [comment]
> @NickM-27 models are mapped fine, it's a different file missing:
> 
> ```
> ERROR: failed to load libraries. libcudart.so.12: cannot open shared object file: No such file or directory
> ```

gotcha, then it will probably be similar to https://github.com/blakeblackshear/frigate/issues/5166 where the library is missing on the host

**Comment by weswitt** [comment]
ok i've moved on past that error but now frigate cannot find the cuda drivers: "RuntimeError: Failed to dlopen libcuda.so". i have verified that the nvidia drivers are available and work in docker. what do i need to do to get cuda installed for docker??

2023-03-23 15:50:25.902739293  Traceback (most recent call last):
2023-03-23 15:50:25.902752833    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-03-23 15:50:25.902754277      self.run()
2023-03-23 15:50:25.902755561    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-03-23 15:50:25.902756803      self._target(*self._args, **self._kwargs)
2023-03-23 15:50:25.902758124    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-03-23 15:50:25.902759438      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-03-23 15:50:25.902763726    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-03-23 15:50:25.902772136      self.detect_api = create_detector(detector_config)
2023-03-23 15:50:25.902778721    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-03-23 15:50:25.902779920      return api(detector_config)
2023-03-23 15:50:25.902781262    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 202, in __init__
2023-03-23 15:50:25.902782264      (cuda_err,) = cuda.cuInit(0)
2023-03-23 15:50:25.902783455    File "cuda/cuda.pyx", line 10727, in cuda.cuda.cuInit
2023-03-23 15:50:25.902784580    File "cuda/ccuda.pyx", line 17, in cuda.ccuda.cuInit
2023-03-23 15:50:25.902785751    File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
2023-03-23 15:50:25.902786922    File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
2023-03-23 15:50:25.902788025  RuntimeError: Failed to dlopen libcuda.so
2023-03-23 15:50:25.902792709  Exception ignored in: <function TensorRtDetector.__del__ at 0x7efc02a748b0>
2023-03-23 15:50:25.902796033  Traceback (most recent call last):
2023-03-23 15:50:25.902797216    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-03-23 15:50:25.902886254      if self.outputs is not None:
2023-03-23 15:50:25.902888116  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'

**Comment by NickM-27** [comment]
What GPUs are y'all using? 

CC @NateMeyer

**Comment by weswitt** [comment]
nvidia-smi
Thu Mar 23 15:57:13 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   45C    P5    16W / 120W |      0MiB /  6144MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by weswitt** [comment]
01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)

**Comment by NickM-27** [comment]
Do the yolov4 models work for you?

**Comment by weswitt** [comment]
got it working. needed to add "--runtime=nvidia" to my docker run command.

**Comment by NickM-27** [comment]
Gotcha, that is good to know. I'll go ahead and close, feel free to create a new issue if something else comes up.

**Comment by Luem2** [comment]
> You aren't using the tensorrt image.
> 
> ```
> ghcr.io/blakeblackshear/frigate:0.12.0-beta10-tensorrt
> ```
> 
> Do we have this wrong in the docs somewhere?

I love you bro, my boss was thinking fired me.

**Comment by dukenewcombe** [comment]
> You aren't using the tensorrt image.
> 
> ```
> ghcr.io/blakeblackshear/frigate:0.12.0-beta10-tensorrt
> ```
> 
> Do we have this wrong in the docs somewhere?

I've managed to get mine working using this image... so cheers for that, however, I haven't seen any references to the different disro's/releases available. I went through the latest releases and found 12.1 as the latest with 13.0-Beta's available as well... but nothing about a 12.1-tensorrt:latest or 13.0-Beta-Tensorrt...

**Comment by NickM-27** [comment]
You can see releases in the releases section of the repo, where all the images and documentation are linked https://github.com/blakeblackshear/frigate/releases

**Comment by dukenewcombe** [comment]
> You can see releases in the releases section of the repo, where all the images and documentation are linked https://github.com/blakeblackshear/frigate/releases

I was aware of where the releases were;  it was the specific Tensorrt release I was curious about... Anyway turns that information is in the docs, just with all the other information I missed it.

_

> ["NVidia GPUs may be used for object detection using the TensorRT libraries. Due to the size of the additional libraries, this detector is only provided in images with the -tensorrt tag suffix. This detector is designed to work with Yolo models for object detection"](https://docs.frigate.video/configuration/detectors#nvidia-tensorrt-detector)

_
Which was the key piece that I was missing...
