### ISSUE TITLE
[Support]: Import error with numpy

### ISSUE THREAD

**Issue by camrun91** [blakeblackshear/frigate#5880]
### Describe the problem you are having

Trying to update to the RC1 docker image. I run compose and get an error saying that numpy failed to import

### Version

0.12.0-rc1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.193
  user: USER
  password: PASSWORD
record:
  retain:
    days: 15
    mode: all
cameras:
#  front_yard:
 #   ffmpeg:
  #    inputs:
   #     - path: rtsp://USERNAME:PASSWORD@192.168.1.XXX:554/h264Preview_01_main
    #      roles:
     #       - record
      #      - rtmp
  #  rtmp:
   #   enabled: False
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://USERNAE:PASSWORD@192.168.1.xxx:554/h264Preview_01_main
          roles:
            - record
            - rtmp
    rtmp:
      enabled: False
```

### Relevant log output

```shell
[+] Running 2/2
 ⠿ Network "frigate_default"  Created                                                                                                                        0.7s
 ⠿ frigate                    Created                                                                                                                        1.7s
Attaching to frigate
frigate    | s6-rc: info: service s6rc-fdholder: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2023-03-30 14:09:21.640806100  [INFO] Starting Frigate...
frigate    | 2023-03-30 14:09:21.640806100  [INFO] Preparing go2rtc config...
frigate    | 2023-03-30 14:09:21.640806100  [INFO] Starting NGINX...
frigate    | 2023-03-30 14:09:22.685940200  2023/03/30 14:09:22 [alert] 135#135: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:09:22.685981300  2023/03/30 14:09:22 [alert] 136#136: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:09:22.687376600  2023/03/30 14:09:22 [alert] 137#137: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:09:22.687905700  2023/03/30 14:09:22 [alert] 139#139: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:09:22.689715900  2023/03/30 14:09:22 [alert] 140#140: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:09:22.690296000  2023/03/30 14:09:22 [alert] 138#138: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:09:22.725120600  2023/03/30 14:09:22 [alert] 117#117: worker process 135 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:09:22.725173200  2023/03/30 14:09:22 [alert] 117#117: worker process 136 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:09:22.725199300  2023/03/30 14:09:22 [alert] 117#117: worker process 137 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:09:22.725922500  2023/03/30 14:09:22 [alert] 117#117: worker process 139 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:09:22.727780600  2023/03/30 14:09:22 [alert] 117#117: worker process 140 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:09:22.731863900  2023/03/30 14:09:22 [alert] 117#117: worker process 138 exited with fatal code 2 and cannot be respawned
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | ImportError: numpy.core.multiarray failed to import
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/local/go2rtc/create_config.py", line 10, in <module>
frigate    |     from frigate.ffmpeg_presets import parse_preset_hardware_acceleration_encode
frigate    |   File "/opt/frigate/frigate/ffmpeg_presets.py", line 10, in <module>
frigate    |     from frigate.util import vainfo_hwaccel
frigate    |   File "/opt/frigate/frigate/util.py", line 19, in <module>
frigate    |     import cv2
frigate    |   File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 8, in <module>
frigate    |     from .cv2 import *
frigate    | ImportError: numpy.core.multiarray failed to import
frigate    | 2023-03-30 14:09:24.749815500  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate    | 2023-03-30 14:09:24.886014600  OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 6: Operation not permitted
frigate    | 2023-03-30 14:09:24.886044900  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:09:24.886071100  OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 6: Operation not permitted
frigate    | 2023-03-30 14:09:24.886096900  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:09:24.886122800  OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 6: Operation not permitted
frigate    | 2023-03-30 14:09:24.886148300  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:09:24.886190300  OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 6: Operation not permitted
frigate    | 2023-03-30 14:09:24.886214800  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:09:24.886239000  OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 6: Operation not permitted
frigate    | 2023-03-30 14:09:24.886284600  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:09:24.891027300  Traceback (most recent call last):
frigate    | 2023-03-30 14:09:24.891056000    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
frigate    | 2023-03-30 14:09:24.891219900      return _run_code(code, main_globals, None,
frigate    | 2023-03-30 14:09:24.891243400    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
frigate    | 2023-03-30 14:09:24.891451200      exec(code, run_globals)
frigate    | 2023-03-30 14:09:24.891478300    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
frigate    | 2023-03-30 14:09:24.891980600      from frigate.app import FrigateApp
frigate    | 2023-03-30 14:09:24.892006300    File "/opt/frigate/frigate/app.py", line 17, in <module>
frigate    | 2023-03-30 14:09:24.892030300      from frigate.comms.dispatcher import Communicator, Dispatcher
frigate    | 2023-03-30 14:09:24.892054000    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
frigate    | 2023-03-30 14:09:24.892081200      from frigate.config import FrigateConfig
frigate    | 2023-03-30 14:09:24.892111800    File "/opt/frigate/frigate/config.py", line 9, in <module>
frigate    | 2023-03-30 14:09:24.892796000      import matplotlib.pyplot as plt
frigate    | 2023-03-30 14:09:24.892848300    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 108, in <module>
frigate    | 2023-03-30 14:09:24.892943000      import numpy
frigate    | 2023-03-30 14:09:24.892969800    File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 144, in <module>
frigate    | 2023-03-30 14:09:24.892994500      from . import core
frigate    | 2023-03-30 14:09:24.893272100    File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 23, in <module>
frigate    | 2023-03-30 14:09:24.893297400      from . import multiarray
frigate    | 2023-03-30 14:09:24.893324400    File "/usr/local/lib/python3.9/dist-packages/numpy/core/multiarray.py", line 10, in <module>
frigate    | 2023-03-30 14:09:24.893351000      from . import overrides
frigate    | 2023-03-30 14:09:24.893378600    File "/usr/local/lib/python3.9/dist-packages/numpy/core/overrides.py", line 6, in <module>
frigate    | 2023-03-30 14:09:24.893686400      from numpy.core._multiarray_umath import (
frigate    | 2023-03-30 14:09:24.893941000  KeyboardInterrupt
frigate    | 2023-03-30 14:09:24.959317300  [INFO] Service Frigate exited with code 256 (by signal 2)
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | s6-rc: info: service legacy-services successfully stopped
frigate    | s6-rc: info: service nginx: stopping
frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate    | 2023-03-30 14:09:24.985178200  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate    | 2023-03-30 14:09:24.991629900  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate    | s6-rc: info: service nginx successfully stopped
frigate    | s6-rc: info: service nginx-log: stopping
frigate    | s6-rc: info: service frigate: stopping
frigate    | s6-rc: info: service frigate successfully stopped
frigate    | s6-rc: info: service go2rtc: stopping
frigate    | s6-rc: info: service frigate-log: stopping
frigate    | s6-rc: info: service nginx-log successfully stopped
frigate    | s6-rc: info: service go2rtc successfully stopped
frigate    | s6-rc: info: service go2rtc-log: stopping
frigate    | s6-rc: info: service go2rtc-log successfully stopped
frigate    | s6-rc: info: service frigate-log successfully stopped
frigate    | s6-rc: info: service log-prepare: stopping
frigate    | s6-rc: info: service s6rc-fdholder: stopping
frigate    | s6-rc: info: service log-prepare successfully stopped
frigate    | s6-rc: info: service legacy-cont-init: stopping
frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate    | s6-rc: info: service legacy-cont-init successfully stopped
frigate    | s6-rc: info: service fix-attrs: stopping
frigate    | s6-rc: info: service fix-attrs successfully stopped
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
ffprobe version 4.4.2 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-libzimg --enable-libzvbi --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --enable-zlib --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --disable-securetransport --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-libdav1d --enable-libaom --enable-librav1e --enable-libsvtav1 --arch=x86_64 --enable-x86asm --enable-gpl --enable-postproc --enable-libx264 --enable-libx265 --enable-libxvid --enable-libvidstab
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x7fface813e00] max delay reached. need to consume packet
[rtsp @ 0x7fface813e00] RTP: missed 20 packets
[rtsp @ 0x7fface813e00] max delay reached. need to consume packet
[rtsp @ 0x7fface813e00] RTP: missed 60 packets
[h264 @ 0x7fface817a00] cabac decode of qscale diff failed at 29 80
[h264 @ 0x7fface817a00] error while decoding MB 29 80, bytestream 11712
[h264 @ 0x7fface817a00] concealing 164 DC, 164 AC, 164 MV errors in I frame
Input #0, rtsp, from 'rtsp://user:password@192.168.1.xxx:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000313, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 2304x1296, 24.92 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Frigate stats

```json
N/A
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink  810A

### Any other information that may be helpful

I had it running and camera working but no recordings on the stable docker container from docker hub. Wanted to try the beta to see if it would fix the recording problem and try out the UI.

I am running in docker on an old mac mini it does have the intel i7 with intel graphics and is 64 bit.

**Comment by NickM-27** [comment]
What is your docker compose file?

**Comment by camrun91** [comment]
@NickM-27 this is the compose file. 

`version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0-rc1
    shm_size: "128mb"
    #devices:
      #- /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/madalyn/frigate/config.yml:/config/config.yml:ro
      - /Volumes/tlhome_disk2/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

`

**Comment by NickM-27** [comment]
What command are you using to run frigate?

**Comment by camrun91** [comment]
I am just running it with `docker compose up`

**Comment by NickM-27** [comment]
What if you do `sudo docker compose up`?

**Comment by camrun91** [comment]
Just tried that and the output looks the same. errors out and then closes.

**Comment by NickM-27** [comment]
Can you include the logs? This doesn't really make sense why it would fail on mac as it's working for every other user including users on older intel.

**Comment by camrun91** [comment]
The same logs that I included earlier? or logs from somewhere else?

**Comment by camrun91** [comment]
```
frigate    | s6-rc: info: service s6rc-oneshot-runner: starting
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate    | s6-rc: info: service fix-attrs: starting
frigate    | s6-rc: info: service s6rc-fdholder successfully started
frigate    | s6-rc: info: service fix-attrs successfully started
frigate    | s6-rc: info: service legacy-cont-init: starting
frigate    | s6-rc: info: service legacy-cont-init successfully started
frigate    | s6-rc: info: service log-prepare: starting
frigate    | s6-rc: info: service log-prepare successfully started
frigate    | s6-rc: info: service nginx-log: starting
frigate    | s6-rc: info: service go2rtc-log: starting
frigate    | s6-rc: info: service frigate-log: starting
frigate    | s6-rc: info: service go2rtc-log successfully started
frigate    | s6-rc: info: service go2rtc: starting
frigate    | s6-rc: info: service nginx-log successfully started
frigate    | s6-rc: info: service frigate-log successfully started
frigate    | s6-rc: info: service go2rtc successfully started
frigate    | s6-rc: info: service go2rtc-healthcheck: starting
frigate    | s6-rc: info: service frigate: starting
frigate    | s6-rc: info: service go2rtc-healthcheck successfully started
frigate    | 2023-03-30 14:53:49.689642000  [INFO] Preparing go2rtc config...
frigate    | s6-rc: info: service frigate successfully started
frigate    | s6-rc: info: service nginx: starting
frigate    | 2023-03-30 14:53:49.716004000  [INFO] Starting Frigate...
frigate    | s6-rc: info: service nginx successfully started
frigate    | s6-rc: info: service legacy-services: starting
frigate    | 2023-03-30 14:53:49.740158600  [INFO] Starting NGINX...
frigate    | s6-rc: info: service legacy-services successfully started
frigate    | 2023-03-30 14:53:49.824828400  2023/03/30 14:53:49 [alert] 135#135: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:53:49.825359700  2023/03/30 14:53:49 [alert] 136#136: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:53:49.828186500  2023/03/30 14:53:49 [alert] 137#137: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:53:49.828212500  2023/03/30 14:53:49 [alert] 139#139: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:53:49.828914900  2023/03/30 14:53:49 [alert] 140#140: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:53:49.831346800  2023/03/30 14:53:49 [alert] 138#138: pthread_create() failed (1: Operation not permitted)
frigate    | 2023-03-30 14:53:49.838922300  2023/03/30 14:53:49 [alert] 120#120: worker process 135 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:53:49.842580600  2023/03/30 14:53:49 [alert] 120#120: worker process 137 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:53:49.842609200  2023/03/30 14:53:49 [alert] 120#120: worker process 136 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:53:49.846794400  2023/03/30 14:53:49 [alert] 120#120: worker process 139 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:53:49.846912600  2023/03/30 14:53:49 [alert] 120#120: worker process 140 exited with fatal code 2 and cannot be respawned
frigate    | 2023-03-30 14:53:49.848184100  2023/03/30 14:53:49 [alert] 120#120: worker process 138 exited with fatal code 2 and cannot be respawned
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 6: Operation not permitted
frigate    | OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | ImportError: numpy.core.multiarray failed to import
frigate    | Traceback (most recent call last):
frigate    |   File "/usr/local/go2rtc/create_config.py", line 10, in <module>
frigate    |     from frigate.ffmpeg_presets import parse_preset_hardware_acceleration_encode
frigate    |   File "/opt/frigate/frigate/ffmpeg_presets.py", line 10, in <module>
frigate    |     from frigate.util import vainfo_hwaccel
frigate    |   File "/opt/frigate/frigate/util.py", line 19, in <module>
frigate    |     import cv2
frigate    |   File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 8, in <module>
frigate    |     from .cv2 import *
frigate    | ImportError: numpy.core.multiarray failed to import
frigate    | 2023-03-30 14:53:49.989477000  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate    | 2023-03-30 14:53:50.182737200  OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 6: Operation not permitted
frigate    | 2023-03-30 14:53:50.182768900  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:53:50.182796100  OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 6: Operation not permitted
frigate    | 2023-03-30 14:53:50.182822800  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:53:50.182849800  OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 6: Operation not permitted
frigate    | 2023-03-30 14:53:50.182876200  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:53:50.182920800  OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 6: Operation not permitted
frigate    | 2023-03-30 14:53:50.182946400  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:53:50.182971700  OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 6: Operation not permitted
frigate    | 2023-03-30 14:53:50.183020400  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
frigate    | 2023-03-30 14:53:50.189364100  Traceback (most recent call last):
frigate    | 2023-03-30 14:53:50.189398600    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
frigate    | 2023-03-30 14:53:50.189889300      return _run_code(code, main_globals, None,
frigate    | 2023-03-30 14:53:50.189915200    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
frigate    | 2023-03-30 14:53:50.190070700      exec(code, run_globals)
frigate    | 2023-03-30 14:53:50.190102900    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
frigate    | 2023-03-30 14:53:50.190588500      from frigate.app import FrigateApp
frigate    | 2023-03-30 14:53:50.190761500    File "/opt/frigate/frigate/app.py", line 17, in <module>
frigate    | 2023-03-30 14:53:50.190792700      from frigate.comms.dispatcher import Communicator, Dispatcher
frigate    | 2023-03-30 14:53:50.190821600    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
frigate    | 2023-03-30 14:53:50.190847700      from frigate.config import FrigateConfig
frigate    | 2023-03-30 14:53:50.191592000    File "/opt/frigate/frigate/config.py", line 9, in <module>
frigate    | 2023-03-30 14:53:50.192516200      import matplotlib.pyplot as plt
frigate    | 2023-03-30 14:53:50.192549300    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 108, in <module>
frigate    | 2023-03-30 14:53:50.192577500      import numpy
frigate    | 2023-03-30 14:53:50.192600200    File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 144, in <module>
frigate    | 2023-03-30 14:53:50.192633600      from . import core
frigate    | 2023-03-30 14:53:50.192662400    File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 23, in <module>
frigate    | 2023-03-30 14:53:50.192691400      from . import multiarray
frigate    | 2023-03-30 14:53:50.192720300    File "/usr/local/lib/python3.9/dist-packages/numpy/core/multiarray.py", line 10, in <module>
frigate    | 2023-03-30 14:53:50.192745100      from . import overrides
frigate    | 2023-03-30 14:53:50.192879700    File "/usr/local/lib/python3.9/dist-packages/numpy/core/overrides.py", line 6, in <module>
frigate    | 2023-03-30 14:53:50.192911900      from numpy.core._multiarray_umath import (
frigate    | 2023-03-30 14:53:50.192940800  KeyboardInterrupt
frigate    | 2023-03-30 14:53:50.285316100  [INFO] Service Frigate exited with code 256 (by signal 2)
frigate    | s6-rc: info: service legacy-services: stopping
frigate    | s6-rc: info: service legacy-services successfully stopped
frigate    | s6-rc: info: service nginx: stopping
frigate    | s6-rc: info: service go2rtc-healthcheck: stopping
frigate    | 2023-03-30 14:53:50.323203100  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate    | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate    | 2023-03-30 14:53:50.330526500  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate    | s6-rc: info: service nginx successfully stopped
frigate    | s6-rc: info: service nginx-log: stopping
frigate    | s6-rc: info: service frigate: stopping
frigate    | s6-rc: info: service frigate successfully stopped
frigate    | s6-rc: info: service go2rtc: stopping
frigate    | s6-rc: info: service frigate-log: stopping
frigate    | s6-rc: info: service nginx-log successfully stopped
frigate    | s6-rc: info: service go2rtc successfully stopped
frigate    | s6-rc: info: service go2rtc-log: stopping
frigate    | s6-rc: info: service frigate-log successfully stopped
frigate    | s6-rc: info: service go2rtc-log successfully stopped
frigate    | s6-rc: info: service log-prepare: stopping
frigate    | s6-rc: info: service s6rc-fdholder: stopping
frigate    | s6-rc: info: service log-prepare successfully stopped
frigate    | s6-rc: info: service legacy-cont-init: stopping
frigate    | s6-rc: info: service s6rc-fdholder successfully stopped
frigate    | s6-rc: info: service legacy-cont-init successfully stopped
frigate    | s6-rc: info: service fix-attrs: stopping
frigate    | s6-rc: info: service fix-attrs successfully stopped
frigate    | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by NickM-27** [comment]
the only time we saw this issue was when a user was running 32 bit https://github.com/blakeblackshear/frigate/issues/5236

**Comment by camrun91** [comment]
Yeah I saw that and I just verified that the mac is 64bit and that docker is running as 64bit as well.

**Comment by NickM-27** [comment]
Unfortunately, I don't have any suggestions, out of the ~ 3000 users running these betas / RC no one else has experienced this issue except on 32 bit. I also don't see the issue on my mac, though it is running M1 so it is arm64. 

@blakeblackshear do you have any thoughts?

**Comment by camrun91** [comment]
It's odd because it is a 2011 Mac mini so it isn't M1 it is intel i7

**Comment by blakeblackshear** [comment]
I assume you are running this on MacOS? I don't have suggestions to offer either unfortunately. It's probably an incompatiblity with numpy and your kernel or something obscure. I would guess that it would work if you installed debian on the machine.

**Comment by camrun91** [comment]
Yeah I am running it on Mac OS. There are a few things I may try. 

Is numpy a new requirement with the beta? It was running fine on the stable version in docker hub.

**Comment by NickM-27** [comment]
Frigate has always used numpy, the dependency version for numpy has also not changed since 0.11 was released https://github.com/blakeblackshear/frigate/commit/afe88d6e3a30945903239d1fcb4db7eada4c40ea

**Comment by camrun91** [comment]
Hmmm that is even more odd. I will take a closer look it has to be something with how my system is set up.

**Comment by camrun91** [comment]
@NickM-27 @blakeblackshear I evidently had a really old version of docker. I updated and I am no longer getting the errors.

**Comment by Whytey** [comment]
Just confirming I saw the same error - initially I could only find tickets to the 32bit OS issues, which wasn't me.  An update to the docker engine did resolve my issue though.

Cheers!

**Comment by joekrill** [comment]
FYI -- in case this is useful for anyone else -- I encountered  this as well. I did not have `privileged: true` in my `docker-compose.yml` and also had:

```
    security_opt:
      - no-new-privileges:true
```

removing that and adding: `privileged: true` to the service gave me more specific information about what was failing. For me it was a config file issue. So perhaps the issue is that the config file can't be read? Maybe something wrong with the mount point or permissions?

It's not clear to my why the container needs to be privileged just to read the config file? Or really at all. I'd prefer to remove this if possible. 

In my case I had named my configuration file `frigate.yml` instead of `config.yml`. The [Installation page](https://docs.frigate.video/frigate/installation) of the docs just says `frigate.yml` with some recommendations. I read that before the "Configuration File" section, which comes way later, and glossed over the filenames at that point.  Oddly, when _neither_ file existed I got a different error 🤷

**Comment by jshep321** [comment]
In my (rpi4 CM) case I think I have a root cause for this.  I have a chimera of an install.  
dpkg --print-architecture yields
armhf (indicates 32 bit)
uname -m 
aarch64 (indicates 64 bit)

If I recall, when I installed frigate previously there was an issue with rpi 64 bit and my upgrades have created this situation.  I think a full reinstall is required.  I will wait for my new rpi5 for this.
