### ISSUE TITLE
[Config Support]: Frigate+ API Key not detected

### ISSUE THREAD

**Issue by amosyuen** [blakeblackshear/frigate#5925]
### Describe the problem you are having

Using HA frigate add-on, I set the PLUS_API_KEY but the "SEND TO FRIGATE+" button on events is greyed out and clicking it prompts me to setup a frigate+ account.

### Version

0.11.1-2EADA21

### Frigate config file

```yaml
environment_vars:
  PLUS_API_KEY: <api_key>

...
```

### Relevant log output

Nothing looks relevant, searched for "PLUS_API_KEY" and "env" and "frigate+" without finding anything.

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2023-04-06 23:15:26] frigate.app                    INFO    : Starting Frigate (0.11.1-2eada21)
[2023-04-06 23:15:26] frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
[2023-04-06 23:15:26] peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
[2023-04-06 23:15:26] peewee_migrate                 INFO    : There is nothing to migrate
[2023-04-06 23:15:26] frigate.app                    INFO    : Output process started: 219
[2023-04-06 23:15:26] detector.cpu1                  INFO    : Starting detection process: 216
[2023-04-06 23:15:26] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2023-04-06 23:15:26] frigate.app                    INFO    : Camera processor started for baby: 222
[2023-04-06 23:15:26] detector.cpu2                  INFO    : Starting detection process: 218
[2023-04-06 23:15:26] frigate.edgetpu                WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
[2023-04-06 23:15:26] frigate.app                    INFO    : Camera processor started for kitchen: 224
[2023-04-06 23:15:26] ws4py                          INFO    : Using epoll
[2023-04-06 23:15:26] frigate.app                    INFO    : Camera processor started for garage: 227
[2023-04-06 23:15:26] frigate.app                    INFO    : Capture process started for baby: 228
[2023-04-06 23:15:27] frigate.app                    INFO    : Capture process started for kitchen: 230
[2023-04-06 23:15:27] frigate.app                    INFO    : Capture process started for garage: 235
[2023-04-06 23:15:27] ws4py                          INFO    : Using epoll
[2023-04-06 23:16:07] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
[2023-04-06 23:16:07] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
[2023-04-06 23:16:07] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by blakeblackshear** [comment]
Setting the api key in the frigate config file is not supported. There is a special place for it in the addon configuration. 

https://deploy-preview-4055--frigate-docs.netlify.app/integrations/plus

**Comment by amosyuen** [comment]
Thanks for clarifying that. The instructions in Frigate+ where you generate
the API key needs to be updated or clarified since it says:

Set your API key as an environment variable named PLUS_API_KEY to enable
Frigate+ features inside of Frigate.

**Comment by NickM-27** [comment]
It'a already explained in that way in the beta docs https://deploy-preview-4055--frigate-docs.netlify.app/integrations/plus#set-your-api-key which will soon be stable

**Comment by bob454522** [comment]
Shoot-  i take it back,  Setting it in the environmental variable section of Docker-compose does not seem to be working (via Portainer, Which I assume is passing the environmental variable to Frigate) ,
I didn't get an error but when I click send to frigate plus it still tells me I need to sign up  :(

**Comment by NickM-27** [comment]
There's no way to show a screenshot because every user has a different env variable location based on how they run their docker containers. 

and there's no way for frigate to have a place to enter it in the webUI. It is set via docker environment variable and frigate can not change those since it runs in a container 

If it didn't work setting there then that may be a portainer issue.

**Comment by aisbergde** [comment]
it would be fine to add this portainer example to the documentation. Or at least a general example / description, how to include into a docker compose file. Some users may not be docker nerds.

**Comment by MaBeniu** [comment]
indeed. it took time until I was able to get api key into docker compose file. without finding this issue I am not sure if I would have been able to tackle it.
but now I get different error :(
```
2024-01-29 16:00:41.047741520    File "/opt/frigate/frigate/plus.py", line 215, in get_model_info
2024-01-29 16:00:41.047775148      raise Exception(r.text)
2024-01-29 16:00:41.047776516  Exception: {"errors":"incorrect_id"}
2024-01-29 16:00:41.047777422  
2024-01-29 16:00:41.047778336  *************************************************************
2024-01-29 16:00:41.047779273  ***    End Config Validation Errors                       ***
2024-01-29 16:00:41.047791595  *************************************************************
2024-01-29 16:00:41.883669160  [INFO] Service Frigate exited with code 1 (by signal 0)
```

**Comment by NickM-27** [comment]
did you enter the correct model ID that you got from the dashboard?

**Comment by Midoxx22** [comment]
I also face a smiliar issue. 
I´m passing the api key on docker compose via env.

```
    environment:
      FRIGATE_RTSP_PASSWORD: "<pass>"
      PLUS_API_KEY: "<apiKey>"
```

if I log the variable in the container with `echo $PLUS_API_KEY` I get the correct key which means passing through is working fine.
But I do not see the "send to frigate+" button on my events.

Is there additional config required?

Using 0.13.0-rc1

Thanks!

**Comment by NickM-27** [comment]
you must have snapshots enabled to be able to submit to frigate+

**Comment by Midoxx22** [comment]
> you must have snapshots enabled to be able to submit to frigate+

thanks! that was the missing part!

**Comment by hagak** [comment]
> you must have snapshots enabled to be able to submit to frigate+

Can we add this to the docs?  I was confused why it was not showing up until i searched and found this.

**Comment by NickM-27** [comment]
It is in the docs https://docs.frigate.video/integrations/plus#submit-examples

**Comment by jacktux** [comment]
I'm having trouble getting the Frigate PLUS key to work, I am running Frigate standalone as a Promox Container (No Docker) and Using the HA Frigate Proxy, so I have no where to add the key.

Can some suggest on where to put the key for my setup?

**Comment by jacktux** [comment]
Ok got it working, had to add it to the frigate.service of the Container

`nano /etc/systemd/system/frigate.service`

> [Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStartPre=+rm /dev/shm/logs/frigate/current
ExecStart=bash /opt/frigate/docker/main/rootfs/etc/s6-overlay/s6-rc.d/frigate/run
StandardOutput=file:/dev/shm/logs/frigate/current
StandardError=file:/dev/shm/logs/frigate/current
Environment="PLUS_API_KEY=your key here"

Restarted the container and all working now

**Comment by mercuryin** [comment]
Ok but I still don´t get it. On home assistant addon is easy where to write the api key within the addon options and the model  key within the yaml file .conf. But where goes the model key when using a lxc container ? Right now the API key I have in frigate.service and the model patch key inside the yaml config file but I get this error:

root@frigate:~# tail -f /dev/shm/logs/frigate/current
    f"{self.host}/v1/{path}", headers=self._get_authorization_header()
  File "/opt/frigate/frigate/plus.py", line 75, in _get_authorization_header
    self._refresh_token_if_needed()
  File "/opt/frigate/frigate/plus.py", line 67, in _refresh_token_if_needed
    raise Exception("Plus API not activated")
Exception: Plus API not activated

If I remove the path to the model from the yaml file it works but with the base models I guess, not with my own.

**Comment by blakeblackshear** [comment]
There isn't a separate key for the model. That should be all you need to do. Are you able to submit images to Frigate+ within Frigate?

The error message you are seeing indicates that Frigate still doesn't see the API key. Did you reload systemd after modifying the unit file?

**Comment by mercuryin** [comment]
> There isn't a separate key for the model. That should be all you need to do. Are you able to submit images to Frigate+ within Frigate?
> 
> The error message you are seeing indicates that Frigate still doesn't see the API key. Did you reload systemd after modifying the unit file?

With the api key within frigate.service yes, I got everything working. But reading on your site about this needed to be done I thought reading that about I need to add a new line to config with = model:
  path: plus://xxxxxxxxxxxxxxxxxxxxxxx 

So if you say is not needed is ok then. Thanks anyway

**Comment by blakeblackshear** [comment]
When you have your own model id, then you will need to set that so your Frigate+ model is used. If you don't, then it will still use the default model. 

See here: https://docs.frigate.video/plus/first_model

**Comment by cchewanik** [comment]
Hi I'm also struggling with this also, running docker on a rasp pi with latest 0.15.0 beta 2

Through docker inspect I can see the variable is set ?
<img width="179" alt="desktop" src="https://github.com/user-attachments/assets/be7a9ea0-f0e9-4018-bf48-eb26fe5b77aa">

Snapshots is enabled, I simplified my config to rule out some other issues, can't get Frigate+ to show up anywhere. Any ideas? Thank you

`mqtt:
  #host: x
  topic_prefix: frigate_pi5
  client_id: frigate_pi5
  host: 192.168.1.2


detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True

go2rtc:
  streams:
    #front_cam:
    #  - rtsp://192.168.1.2:45043/21a633a68bb69f10 #- http://192.168.1.80/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=Honda101#video=copy#audio=copy#audio=opus
    front_cam_sub:
      - rtsp://192.168.1.2:45043/e821ff7c0ffa7ef7 #rtsp sub stream
    backyard_cam_sub:
      - rtsp://192.168.1.2:41047/6e6ec5ad3a0004aa

  webrtc:
    candidates:
      - 127.0.0.1:8555

cameras:
  front:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 10
    objects:
      mask: 0.44,0.23,1,0.206,0.998,0.002,0,0,0,0.378
      track:
        - dog
        - person
        - cat
        - car
      filters:
        dog:
          min_score: 0.1
          threshold: 0.1
          min_area: 0
          max_area: 24000000
          min_ratio: 0.1
          max_ratio: 5
        cat:
          min_score: 0.3
          threshold: 0.3
          min_area: 0
          max_area: 24000000
          min_ratio: 0.1
          max_ratio: 5
        person:
          min_score: 0.5
          threshold: 0.8
          min_area: 1000
          max_area: 60000
          min_ratio: 0.1
          max_ratio: 5
    # snapshots:
    #   enabled: true # <-- retains snapshots for 10 days on default
    #   bounding_box: true
    #   required_zones:
    #     - front_1
    record:
      enabled: True
      alerts:
        retain:
          days: 10
      detections:
        retain:
          days: 10
    zones:
      front_1:
        coordinates: 0,0.38,0.441,0.236,1,0.212,1,1,0,1
        loitering_time: 0
        inertia: 3
    review:
      alerts:
        required_zones: front_1
      detections:
        required_zones: front_1
    motion:
      mask: 0.001,0.371,0.26,0.288,0.433,0.236,0.618,0.225,0.999,0.208,1,0,0,0`

**Comment by patradley** [comment]
I am also tearing my hair out a bit with this one.  I went from running Frigate as an add-on to having it run in its own LXC container.  I've been successfully using frigate+ for over a year now.
As soon as I add the model ID to my config.yml, my config crashes and goes into a reboot loop.
How I am adding it:
model:
  path: plus://xxxxxxxxxxxxxxxxxxxxxxxxx


I have:
Added 
`lxc.environment: PLUS_API_KEY=my_actual_api_key`
 to 
`/etc/pve/lxc/<container_id>.conf`
Yes I know the model id is different from the API key

Verified this by: 
from the proxmox console:
```
pct enter <container_id>
echo $PLUS_API_KEY
```

from the frigate LXC console:
`tr '\0' '\n' < /proc/1/environ | grep PLUS_API_KEY`

Both show my API key

I can ping plus.frigate.video from the LXC console

I regenerated a new API key to use and have been using that

I am using an edgetpu model ID (not CPU) and according to the logs, my TPUs are just fine

For all I can tell, frigate is not seeing the env var, but I'm trying to determine other troubleshooting steps to verify this.  

Here is the error.  Which only presents itself when I add the model section to config.yml
```
2025-07-02 12:50:11.994024  *************************************************************
2025-07-02 12:50:11.994052  *************************************************************
2025-07-02 12:50:11.994064  ***    Your config file is not valid!                     ***
2025-07-02 12:50:11.994075  ***    Please check the docs at                           ***
2025-07-02 12:50:11.994091  ***    https://docs.frigate.video/configuration/index     ***
2025-07-02 12:50:11.994102  *************************************************************
2025-07-02 12:50:11.994138  *************************************************************
2025-07-02 12:50:11.994161  ***    Config Validation Errors                           ***
2025-07-02 12:50:11.994171  *************************************************************
2025-07-02 12:50:11.994181  Plus API not activated
2025-07-02 12:50:11.994397  Traceback (most recent call last):
2025-07-02 12:50:11.994420    File "/opt/frigate/frigate/app.py", line 645, in start
2025-07-02 12:50:11.994433      self.init_config()
2025-07-02 12:50:11.994443    File "/opt/frigate/frigate/app.py", line 140, in init_config
2025-07-02 12:50:11.994453      self.config = user_config.runtime_config(self.plus_api)
2025-07-02 12:50:11.994464    File "/opt/frigate/frigate/config.py", line 1599, in runtime_config
2025-07-02 12:50:11.994474      config.model.check_and_load_plus_model(plus_api)
2025-07-02 12:50:11.994484    File "/opt/frigate/frigate/detectors/detector_config.py", line 91, in check_and_load_plus_model
2025-07-02 12:50:11.994493      download_url = plus_api.get_model_download_url(model_id)
2025-07-02 12:50:11.994503    File "/opt/frigate/frigate/plus.py", line 228, in get_model_download_url
2025-07-02 12:50:11.994513      r = self._get(f"model/{model_id}/signed_url")
2025-07-02 12:50:11.994523    File "/opt/frigate/frigate/plus.py", line 84, in _get
2025-07-02 12:50:11.994533      f"{self.host}/v1/{path}", headers=self._get_authorization_header()
2025-07-02 12:50:11.994543    File "/opt/frigate/frigate/plus.py", line 79, in _get_authorization_header
2025-07-02 12:50:11.994553      self._refresh_token_if_needed()
2025-07-02 12:50:11.994563    File "/opt/frigate/frigate/plus.py", line 71, in _refresh_token_if_needed
2025-07-02 12:50:11.994573      raise Exception("Plus API not activated")
2025-07-02 12:50:11.994583  Exception: Plus API not activated
```

**Comment by NickM-27** [comment]
If you're running in an addon via home assistant then that's where you'd set the key

**Comment by mrdarrengriffin** [comment]
If you're using docker-compose, use my example below. My issue was that I was using quotes to wrap the string, removing them fixed it:

```
    environment:
      - FRIGATE_RTSP_PASSWORD=xyz
      - PLUS_API_KEY=243de....
```
