### ISSUE TITLE
[Support]: Not able to start the latest 0.12.0 addon

### ISSUE THREAD

**Issue by sheminasalam** [blakeblackshear/frigate#5940]
### Describe the problem you are having

Getting folowing error in log

```
2023-04-08 16:12:57.415765231  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-04-08 16:12:57.416107764  Traceback (most recent call last):
2023-04-08 16:12:57.416122523    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-04-08 16:12:57.416727145      return _run_code(code, main_globals, None,
2023-04-08 16:12:57.416741237    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-04-08 16:12:57.417341748      exec(code, run_globals)
2023-04-08 16:12:57.417359507    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-04-08 16:12:57.417415007      from frigate.app import FrigateApp
2023-04-08 16:12:57.417424525    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-04-08 16:12:57.417896075      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-04-08 16:12:57.417912649    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-04-08 16:12:57.417929149      from frigate.config import FrigateConfig
2023-04-08 16:12:57.417938741    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-04-08 16:12:57.418809989      import matplotlib.pyplot as plt
2023-04-08 16:12:57.418828230    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-04-08 16:12:57.418882637      from . import _api, _version, cbook, _docstring, rcsetup
2023-04-08 16:12:57.418892266    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-04-08 16:12:57.419936309      from matplotlib.colors import Colormap, is_color_like
2023-04-08 16:12:57.419956753    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-04-08 16:12:57.419964253      from matplotlib import _api, _cm, cbook, scale
2023-04-08 16:12:57.419971993    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-04-08 16:12:57.420456617      from matplotlib.ticker import (
2023-04-08 16:12:57.420481542    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-04-08 16:12:57.420894815      from matplotlib import transforms as mtransforms
2023-04-08 16:12:57.420910296    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-04-08 16:12:57.421234459      from matplotlib._path import (
2023-04-08 16:12:57.421249903  ImportError: numpy.core.multiarray failed to import

```

### Version

0.12.0

### Frigate config file

```yaml
ff
```

### Relevant log output

```shell
ff
```

### FFprobe output from your camera

```shell
ff
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wireless

### Camera make and model

cpplus

**Comment by northwarks** [comment]
Exact same issue here for me.

**Comment by NickM-27** [comment]
What's the system arch y'all are running on?

**Comment by MavenCH** [comment]
me3
HassOS in a VM x64 AMD Ryzen 7

**Comment by NickM-27** [comment]
we saw a report of this issue happening when the user was running an old version of docker, I'd suggest updating docker

**Comment by NickM-27** [comment]
maybe try uninstalling / reinstalling the addon

**Comment by northwarks** [comment]
Pi4 so Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.8GHz

**Comment by NickM-27** [comment]
@northwarks what OS and is the OS 64 bit or 32 bit?

**Comment by MavenCH** [comment]
If anyone needs a Home Assistant backup from Frigate. Here Frigate in version 11.1.
First uninstall your current Frigate version and then upload the backup in Home Assistant under Backup.
Worked for me :)

https://drive.google.com/file/d/1-oSNpJfbAtIS1TwPqWlN6S8Sy23evkqd/view?usp=sharing

**Comment by northwarks** [comment]
> @northwarks what OS and is the OS 64 bit or 32 bit?

HAS OS 9.5

**Comment by NickM-27** [comment]
> > @northwarks what OS and is the OS 64 bit or 32 bit?
> 
> HAS OS 9.5
> 
> tried an uninstall and reinstall and get the same error as op

32 bit or 64 bit?

**Comment by northwarks** [comment]
So did a uname -m and got armv7l so it’s 32bit not 64

**Comment by NickM-27** [comment]
In that case, we've seen some 32 bit users have this issue while others did not. The recommendation is to upgrade to 64 bit

**Comment by novag** [comment]
Updating numpy to version 1.23.0 will fix this. 1.24.0 won't work as frigate uses some deprecated features that have been removed in 1.24.0.

**Comment by sheminasalam** [comment]
In my case downgrading numpy also didnt work. i get the following error. PS: I had to change the ports from 8555 to 8556 since for some reason it was reported that 8555 was occupied.
```
2023-04-09 07:24:29.986644540  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-04-09 07:24:29.986880725  Traceback (most recent call last):
2023-04-09 07:24:29.986891966    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-04-09 07:24:29.988849961      return _run_code(code, main_globals, None,
2023-04-09 07:24:29.988866850    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-04-09 07:24:29.989137257      exec(code, run_globals)
2023-04-09 07:24:29.989180386    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-04-09 07:24:29.989299571      from frigate.app import FrigateApp
2023-04-09 07:24:29.989336905    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-04-09 07:24:29.991005697      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-04-09 07:24:29.991057938    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-04-09 07:24:29.991275141      from frigate.config import FrigateConfig
2023-04-09 07:24:29.991285474    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-04-09 07:24:29.991446752      import matplotlib.pyplot as plt
2023-04-09 07:24:29.991456844    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-04-09 07:24:29.993307970      from . import _api, _version, cbook, _docstring, rcsetup
2023-04-09 07:24:29.993362155    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-04-09 07:24:29.993555636      from matplotlib.colors import Colormap, is_color_like
2023-04-09 07:24:29.993565599    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-04-09 07:24:29.993780654      from matplotlib import _api, _cm, cbook, scale
2023-04-09 07:24:29.993791061    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-04-09 07:24:29.995526409      from matplotlib.ticker import (
2023-04-09 07:24:29.995542187    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-04-09 07:24:29.995966241      from matplotlib import transforms as mtransforms
2023-04-09 07:24:29.996013464    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-04-09 07:24:29.998207847      from matplotlib._path import (
2023-04-09 07:24:29.998261866  ImportError: numpy.core.multiarray failed to import
2023-04-09 07:24:30.127746979  [INFO] Starting go2rtc...
2023-04-09 07:24:30.191158890  [INFO] Service Frigate exited with code 1 (by signal 0)

```

**Comment by NickM-27** [comment]
Numpy has been pinned at 1.22 since frigate 0.11 so it doesn't explain why it would be an issue. Also, this issue only came up with one user because their docker was out of date on macOS and another user running on a 32 bit only board. If you're running 32 bit you'll want to update to 64 bit. 

@sheminasalam frigate runs in a container so whatever version of numpy is on your host won't affect what is in the container.

**Comment by sheminasalam** [comment]
I am running 64bit but I got a similar issue with latest version of esphome also. it seemed others also had that. can anybody check it to see if there are any connections. also its still not working

**Comment by northwarks** [comment]
I dug out an old 64bit Pi4, started from a fresh build and it now works - Need to figure out how to migrate/restore my whole HA system from 32bit -> 64bit without breaking it.

**Comment by harambe88** [comment]
Shifted my system too to 64bit, but problem persists...

How can numpy be upgraded? Anybody knows this, because I'm still getting this errors in frigate log (RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf)?

**Comment by NickM-27** [comment]
> How can numpy be upgraded? Anybody knows this, because I'm still getting this errors in frigate log (RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf)?

this is not something the user can do. 

I would make sure you have cleared the addon and redownload, if you are running arm64 this issue should not be there. what OS are you running?

**Comment by harambe88** [comment]
Linux Raspi4 5.15.32-v8+ #1537 SMP PREEMPT Wed Mar 30 17:17:41 BST 2022 aarch64 GNU/Linux

 

I have deinstalled & reinstalled frigate after going to 64 bit. Didn't change anything.

 

__________________________________________________________

 
 

Gesendet: Dienstag, 11. April 2023 um 15:16 Uhr
Von: "Nicolas Mowen" ***@***.***>
An: "blakeblackshear/frigate" ***@***.***>
Cc: "harambe88" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [blakeblackshear/frigate] [Support]: Not able to start the latest 0.12.0 addon (Issue #5940)


 


How can numpy be upgraded? Anybody knows this, because I'm still getting this errors in frigate log (RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf)?


this is not something the user can do.

I would make sure you have cleared the addon and redownload, if you are running arm64 this issue should not be there. what OS are you running?

**Comment by harambe88** [comment]
OK, can you tell me how to do that or where to look for it?


 

__________________________________________________________

 
 

Gesendet: Dienstag, 11. April 2023 um 15:28 Uhr
Von: "Nicolas Mowen" ***@***.***>
An: "blakeblackshear/frigate" ***@***.***>
Cc: "harambe88" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [blakeblackshear/frigate] [Support]: Not able to start the latest 0.12.0 addon (Issue #5940)


 

In that case I would make sure docker is fully up to date, some users found older versions of docker caused this to happen

**Comment by NickM-27** [comment]
https://askubuntu.com/questions/472412/how-do-i-upgrade-docker

**Comment by harambe88** [comment]
Thanks!

 

I'm getting "docker-ce ist schon die neueste Version (5:23.0.3-1~raspbian.10~buster)"

 


 

__________________________________________________________

 
 

Gesendet: Dienstag, 11. April 2023 um 15:41 Uhr
Von: "Nicolas Mowen" ***@***.***>
An: "blakeblackshear/frigate" ***@***.***>
Cc: "harambe88" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [blakeblackshear/frigate] [Support]: Not able to start the latest 0.12.0 addon (Issue #5940)


 

https://askubuntu.com/questions/472412/how-do-i-upgrade-docker

**Comment by NickM-27** [comment]
Maybe it is different, but on both my devices I have a docker version of 20.10.23. What happens if you run `docker --version` on your host?

**Comment by harambe88** [comment]
Docker version 20.10.22, build 3a2c30b
 

__________________________________________________________

 
 

Gesendet: Dienstag, 11. April 2023 um 16:08 Uhr
Von: "Nicolas Mowen" ***@***.***>
An: "blakeblackshear/frigate" ***@***.***>
Cc: "harambe88" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [blakeblackshear/frigate] [Support]: Not able to start the latest 0.12.0 addon (Issue #5940)


 

Maybe it is different, but on both my devices I have a docker version of 20.10.23. What happens if you run docker --version on your host?

**Comment by NickM-27** [comment]
So it most likely should be fine, no idea why that would be a problem then

**Comment by harambe88** [comment]
Thank you for your time anyway. I'll keep googleing then...
 

__________________________________________________________

 
 

Gesendet: Dienstag, 11. April 2023 um 16:14 Uhr
Von: "Nicolas Mowen" ***@***.***>
An: "blakeblackshear/frigate" ***@***.***>
Cc: "harambe88" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [blakeblackshear/frigate] [Support]: Not able to start the latest 0.12.0 addon (Issue #5940)


 

So it most likely should be fine, no idea why that would be a problem then

**Comment by NickM-27** [comment]
@antonio-fiol you are running 32 bit OS

**Comment by antonio-fiol** [comment]
Oh, you're right... it's Raspberry Pi OS... and even though the HW is 64-bit, both the Kernel and OS are 32-bit. Are you saying I should reinstall everything from scratch in order to be able to use frigate 0.12.0 addon? (I have plans to upgrade anyway, but was hoping to do that during summer vacation... I guess I may need to skip frigate updates for now.)

**Comment by harambe88** [comment]
Oh, you are right:

 

getconf LONG_BIT
32
 

__________________________________________________________

 
 

Gesendet: Dienstag, 11. April 2023 um 16:35 Uhr
Von: "Nicolas Mowen" ***@***.***>
An: "blakeblackshear/frigate" ***@***.***>
Cc: "harambe88" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [blakeblackshear/frigate] [Support]: Not able to start the latest 0.12.0 addon (Issue #5940)


 

@antonio-fiol you are running 32 bit OS

**Comment by NickM-27** [comment]
> Oh, you're right... it's Raspberry Pi OS... and even though the HW is 64-bit, both the Kernel and OS are 32-bit. Are you saying I should reinstall everything from scratch in order to be able to use frigate 0.12.0 addon? (I have plans to upgrade anyway, but was hoping to do that during summer vacation... I guess I may need to skip frigate updates for now.)

@antonio-fiol if you make a full backup and then install HA OS 64bit you can restore you backup and it will pull the correct versions of things

**Comment by harambe88** [comment]
'I'm confused. I'm having

 

uname -a
Linux Raspi4 5.15.32-v8+ #1537 SMP PREEMPT Wed Mar 30 17:17:41 BST 2022 aarch64 GNU/Linux
 

and 

 

getconf LONG_BIT

32

 

What is it now 32bit or 64bit?

 

And I understand from your last post that HA itsself must be a 64 bit version as well. OK?

 

 

 

 

 

__________________________________________________________

 
 

Gesendet: Dienstag, 11. April 2023 um 16:47 Uhr
Von: "Nicolas Mowen" ***@***.***>
An: "blakeblackshear/frigate" ***@***.***>
Cc: "harambe88" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [blakeblackshear/frigate] [Support]: Not able to start the latest 0.12.0 addon (Issue #5940)


 


Oh, you're right... it's Raspberry Pi OS... and even though the HW is 64-bit, both the Kernel and OS are 32-bit. Are you saying I should reinstall everything from scratch in order to be able to use frigate 0.12.0 addon? (I have plans to upgrade anyway, but was hoping to do that during summer vacation... I guess I may need to skip frigate updates for now.)


@antonio-fiol if you make a full backup and then install HA OS 64bit you can restore you backup and it will pull the correct versions of things

**Comment by arigit** [comment]
For people having this problem on RPi4, with a 64-bit kernel, most likely your userland is still 32 bits, you can confirm this with

> getconf LONG_BIT
32

That was my case. All is not lost: you can install docker 64bits manually, see here for hints: https://discourse.osmc.tv/t/support-for-64bit-docker-containers/94286/20

after that, your next docker pull will bring arm64 images and frigate 0.12.0 works.

**Comment by harambe88** [comment]
I tried the arm64 version of the upgrade but my raspi says "package architecture doesn't match with system architecture". 
Before I try the armhf version: is armhf  64 bit anyway?

**Comment by harambe88** [comment]
OK. I installed the armhf version which worked without any errors only after having stopped docker service. After that I rebooted and started docker again. Hello World is working.

But now my home-assistant doesn't work anymore. Must I install that also and if so which version? I have tried aarch64 and arm 64 which gave both me errors and ha still didn't work anymore.
