### ISSUE TITLE
[Detector Support]: frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected.

### ISSUE THREAD

**Issue by johanandersson88** [blakeblackshear/frigate#5955]
### Describe the problem you are having

Hello!

I have not yet been able to get it to work. These are the three problems that I found in the log:
1. Coral can't be detected. I can't find it in the HA hardware list either. Connected with USB and external power source. I have tried to use Frigate full access and disabled protection mode as well.
2. When I open frigate, in the video window, it says "no frames have been received, check error logs". The stream works fine in VLC. (Hikvision camera)
3. I get the error message "peewee_migrate                 INFO    : There is nothing to migrate".

I would really appreciate some pointers on how to solve this! When I searched the forums problem #3 seams to be related to the MQTT in some way, but I can't see what the problem is. I have tried both with the port spelled out below host and without it, as it is the standard port.

Best regards,
Johan

### Version

9.5

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.206
  user: mqttuser
  password: password
  
detectors:
  coral:
    type: edgetpu
    device: usb


cameras:
  frontcam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.1.64:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    detect:
      width:  640
      height:  480
      fps:  5
```

### docker-compose file or Docker CLI command

```yaml
I don't use docker. I installed the HA add-on on a Raspberry pi4.
```

### Relevant log output

```shell
2023-04-09 17:17:48.839854004  [INFO] Got IP address from supervisor: 192.168.1.163
2023-04-09 17:17:48.985136044  [INFO] Got WebRTC port from supervisor: 8555
2023-04-09 17:17:49.740226647  [INFO] Starting go2rtc...
2023-04-09 17:17:49.937067310  19:17:49.936 INF go2rtc version 1.2.0 linux/arm64
2023-04-09 17:17:49.938539527  19:17:49.938 INF [api] listen addr=:1984
2023-04-09 17:17:49.939711286  19:17:49.939 INF [rtsp] listen addr=:8554
2023-04-09 17:17:49.941388388  19:17:49.941 INF [srtp] listen addr=:8443
2023-04-09 17:17:49.942478926  19:17:49.942 INF [webrtc] listen addr=:8555
2023-04-09 17:17:52.836477491  [2023-04-09 19:17:52] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-09 17:17:52.882895624  [2023-04-09 19:17:52] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-04-09 17:17:52.901803168  [2023-04-09 19:17:52] peewee_migrate                 INFO    : Starting migrations
2023-04-09 17:17:52.911814319  [2023-04-09 19:17:52] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-09 17:17:52.977718671  [2023-04-09 19:17:52] frigate.app                    INFO    : Output process started: 300
2023-04-09 17:17:52.988938266  [2023-04-09 19:17:52] detector.coral                 INFO    : Starting detection process: 299
2023-04-09 17:17:52.989619978  [2023-04-09 19:17:52] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-04-09 17:17:52.999205099  [2023-04-09 19:17:52] frigate.app                    INFO    : Camera processor started for frontcam: 304
2023-04-09 17:17:53.024327616  [2023-04-09 19:17:53] frigate.app                    INFO    : Capture process started for frontcam: 307
2023-04-09 17:17:53.029484606  [2023-04-09 19:17:53] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-04-09 17:17:53.029783471  Process detector:coral:
2023-04-09 17:17:53.036236403  Traceback (most recent call last):
2023-04-09 17:17:53.036254181    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-04-09 17:17:53.036256255      delegate = Delegate(library, options)
2023-04-09 17:17:53.036270477    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-04-09 17:17:53.036273236      raise ValueError(capture.message)
2023-04-09 17:17:53.036378512  ValueError
2023-04-09 17:17:53.036380975  
2023-04-09 17:17:53.036383086  During handling of the above exception, another exception occurred:
2023-04-09 17:17:53.036384160  
2023-04-09 17:17:53.036385678  Traceback (most recent call last):
2023-04-09 17:17:53.046896174    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-04-09 17:17:53.046906655      self.run()
2023-04-09 17:17:53.046908896    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-04-09 17:17:53.046910655      self._target(*self._args, **self._kwargs)
2023-04-09 17:17:53.046912748    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-04-09 17:17:53.046914785      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-04-09 17:17:53.046919655    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-04-09 17:17:53.046929914      self.detect_api = create_detector(detector_config)
2023-04-09 17:17:53.046932155    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-04-09 17:17:53.046933877      return api(detector_config)
2023-04-09 17:17:53.046988617    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-04-09 17:17:53.046991691      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-04-09 17:17:53.046994080    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-04-09 17:17:53.046996006      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-04-09 17:17:53.046997802  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-04-09 17:17:53.046998820  
2023-04-09 17:17:54.512807399  172.30.32.2 - - [09/Apr/2023:19:17:54 +0200] "GET // HTTP/1.1" 200 6701 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15" "fe80::105b:9002:a41f:225, 172.30.32.1"
2023-04-09 17:17:54.615000919  172.30.32.2 - - [09/Apr/2023:19:17:54 +0200] "GET /api/config HTTP/1.1" 200 4463 "http://homeassistant.local:8123/api/hassio_ingress/CFWo-gBVJ5-GilUiPbF-ve2apJyPqfz_k6S-CvQWeoM//" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15" "fe80::105b:9002:a41f:225, 172.30.32.1"
2023-04-09 17:17:54.798965254  172.30.32.2 - - [09/Apr/2023:19:17:54 +0200] "GET //api/frontcam/latest.jpg?h=292 HTTP/1.1" 200 7406 "http://homeassistant.local:8123/api/hassio_ingress/CFWo-gBVJ5-GilUiPbF-ve2apJyPqfz_k6S-CvQWeoM//" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15" "fe80::105b:9002:a41f:225, 172.30.32.1"
2023-04-09 17:17:57.775446069  172.30.32.2 - - [09/Apr/2023:19:17:57 +0200] "GET /api/config HTTP/1.1" 200 4463 "http://homeassistant.local:8123/api/hassio_ingress/CFWo-gBVJ5-GilUiPbF-ve2apJyPqfz_k6S-CvQWeoM//" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15" "fe80::105b:9002:a41f:225, 172.30.32.1"
2023-04-09 17:17:58.676952102  [INFO] Starting go2rtc healthcheck service...
2023-04-09 17:18:12.257518150  172.30.32.2 - - [09/Apr/2023:19:18:12 +0200] "GET /api/config HTTP/1.1" 200 4463 "http://homeassistant.local:8123/api/hassio_ingress/CFWo-gBVJ5-GilUiPbF-ve2apJyPqfz_k6S-CvQWeoM//" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15" "fe80::105b:9002:a41f:225, 172.30.32.1"
2023-04-09 17:18:12.587592346  172.30.32.2 - - [09/Apr/2023:19:18:12 +0200] "GET / HTTP/1.1" 200 6641 "-" "HomeAssistantSupervisor/2023.04.0 aiohttp/3.8.4 Python/3.10" "-"
2023-04-09 17:18:13.471608627  [2023-04-09 19:18:13] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-04-09 17:18:13.524801297  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-04-09 17:18:13.610694916  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-04-09 17:18:13.619942636  [2023-04-09 19:18:13] frigate.app                    INFO    : Stopping...
2023-04-09 17:18:13.622133582  [2023-04-09 19:18:13] frigate.watchdog               INFO    : Exiting watchdog...
s6-rc: info: service nginx-log successfully stopped
2023-04-09 17:18:13.626342180  [2023-04-09 19:18:13] frigate.record                 INFO    : Exiting recording maintenance...
2023-04-09 17:18:13.632314990  [2023-04-09 19:18:13] frigate.storage                INFO    : Exiting storage maintainer...
2023-04-09 17:18:13.632827630  [2023-04-09 19:18:13] frigate.stats                  INFO    : Exiting stats emitter...
2023-04-09 17:18:13.633487508  [2023-04-09 19:18:13] frigate.record                 INFO    : Exiting recording cleanup...
2023-04-09 17:18:13.634676359  [2023-04-09 19:18:13] frigate.events                 INFO    : Exiting event cleanup...
2023-04-09 17:18:13.635489605  [2023-04-09 19:18:13] frigate.object_processing      INFO    : Exiting object processor...
2023-04-09 17:18:13.721510888  [2023-04-09 19:18:13] frigate.comms.ws               INFO    : Exiting websocket client...
2023-04-09 17:18:14.472702204  [2023-04-09 19:18:14] frigate.events                 INFO    : Exiting event processor...
2023-04-09 17:18:14.475495659  [2023-04-09 19:18:14] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-04-09 17:18:14.484467586  [2023-04-09 19:18:14] watchdog.frontcam              INFO    : Terminating the existing ffmpeg process...
2023-04-09 17:18:14.486208169  [2023-04-09 19:18:14] watchdog.frontcam              INFO    : Waiting for ffmpeg to exit gracefully...
2023-04-09 17:18:15.099145941  [2023-04-09 19:18:15] frigate.output                 INFO    : exiting output process...
2023-04-09 17:18:19.222680012  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked shared_memory objects to clean up at shutdown
2023-04-09 17:18:19.222691548    warnings.warn('resource_tracker: There appear to be %d '
2023-04-09 17:18:19.237488141  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-04-09 17:18:19.250838108  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-04-09 17:18:19.266868884  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

USB with external power source connected to Raspberry Pi4 via USB3. I also have an SSD connected via USB.

**Comment by NickM-27** [comment]
1. If it's not in the hardware list there's not much Frigate can do. Either the host isn't seeing it or it's not working. Have you tried it on a different host to see if it appears?
2. There's no logs related to this, most likely frigate isn't staying up long enough and that's the only issue
3. This isn't an error?
