### ISSUE TITLE
[Config Support]: arm32 numpy error

### ISSUE THREAD

**Issue by dth97410** [blakeblackshear/frigate#5973]
### Describe the problem you are having

I can't get the frigate to work after the last update

### Version

 0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.31.143
  port: 1883
  topic_prefix: frigate
  user: mqtt
  password: XXXXXXX

detectors:
  coral:
    type: edgetpu
    device: usb
    
go2rtc:
  streams:
    imoucam:
      - rtsp://XXXX:XXXX@192.168.31.96:80/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

cameras:
  imoucam:
    ffmpeg:
      inputs:
        - path: rtsp://XXXX:XXXX@192.168.31.96:80/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
        - bird
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-04-10 15:07:09.658831569  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-04-10 15:07:09.677356566  [INFO] Starting Frigate...
2023-04-10 15:07:09.685731157  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-04-10 15:07:09.813798579  [INFO] Got IP address from supervisor: 192.168.31.143
2023-04-10 15:07:09.999402413  [WARN] Failed to get WebRTC port from supervisor
2023-04-10 15:07:10.869181497  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-04-10 15:07:10.869584011  Traceback (most recent call last):
2023-04-10 15:07:10.869608381    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-04-10 15:07:10.870506056      return _run_code(code, main_globals, None,
2023-04-10 15:07:10.870537315    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-04-10 15:07:10.871048124      exec(code, run_globals)
2023-04-10 15:07:10.871069290    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-04-10 15:07:10.871493267      from frigate.app import FrigateApp
2023-04-10 15:07:10.871585525    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-04-10 15:07:10.872019261      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-04-10 15:07:10.872135853    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-04-10 15:07:10.872389424      from frigate.config import FrigateConfig
2023-04-10 15:07:10.872477349    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-04-10 15:07:10.872765883      import matplotlib.pyplot as plt
2023-04-10 15:07:10.872886159    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-04-10 15:07:10.873400857      from . import _api, _version, cbook, _docstring, rcsetup
2023-04-10 15:07:10.873423375    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-04-10 15:07:10.873905388      from matplotlib.colors import Colormap, is_color_like
2023-04-10 15:07:10.874090757    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-04-10 15:07:10.874571085      from matplotlib import _api, _cm, cbook, scale
2023-04-10 15:07:10.874629121    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-04-10 15:07:10.875267077      from matplotlib.ticker import (
2023-04-10 15:07:10.875536352    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-04-10 15:07:10.876141919      from matplotlib import transforms as mtransforms
2023-04-10 15:07:10.876338824    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-04-10 15:07:10.876636413      from matplotlib._path import (
2023-04-10 15:07:10.876713542  ImportError: numpy.core.multiarray failed to import
2023-04-10 15:07:10.923213653  [INFO] Starting go2rtc...
2023-04-10 15:07:11.074637017  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-04-10 15:07:11.123630692  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-04-10 15:07:11.185654574  19:07:11.185 INF go2rtc version 1.2.0 linux/arm
2023-04-10 15:07:11.186721043  19:07:11.186 INF [api] listen addr=:1984
2023-04-10 15:07:11.187653366  19:07:11.187 INF [rtsp] listen addr=:8554
2023-04-10 15:07:11.188840020  19:07:11.188 INF [srtp] listen addr=:8443
2023-04-10 15:07:11.189759306  19:07:11.189 INF [webrtc] listen addr=:8555
2023-04-10 15:07:11.293307075  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-04-10 15:07:11.306535039  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-04-10 15:07:11.329045435  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by dth97410** [comment]
Raspberry HA 32bit

**Comment by NickM-27** [comment]
some 32bit users have had issues, the recommendation is to update to 64 bit OS

**Comment by dth97410** [comment]
Is it safe to upgrade my entire installation from 32bit to 64bit knowing that my raspberry is a 2GB?

**Comment by NickM-27** [comment]
yes, all users are recommended to do so

**Comment by dth97410** [comment]
Ok I will try to make it as soon as possible thanks.

**Comment by neophitus** [comment]
Check if you have the WebRTC Camera integration or another application using the ports used by go2rtc. That's its your issue!

**Comment by dth97410** [comment]
Ok I will try to see that .
