### ISSUE TITLE
[Support]: 32 bit arm error

### ISSUE THREAD

**Issue by evasilisin1984** [blakeblackshear/frigate#6030]
### Describe the problem you are having

Frigate (the add-on for Home Assistant) suddenly stopped running.  Won’t restart.  

### Version

0.12 Home Assistant 

### Frigate config file

```yaml
Not currently available to upload
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-04-13 02:01:24.319014080  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-04-13 02:01:24.331832284  [INFO] Starting Frigate...
2023-04-13 02:01:24.347148274  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-04-13 02:01:24.475936014  [INFO] Got IP address from supervisor: 192.168.50.3
2023-04-13 02:01:24.629593116  [WARN] Failed to get WebRTC port from supervisor
2023-04-13 02:01:25.439005243  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-04-13 02:01:25.440475263  Traceback (most recent call last):
2023-04-13 02:01:25.440616651    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-04-13 02:01:25.441887988      return _run_code(code, main_globals, None,
2023-04-13 02:01:25.442015690    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-04-13 02:01:25.443375712      exec(code, run_globals)
2023-04-13 02:01:25.443507914    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-04-13 02:01:25.444654493      from frigate.app import FrigateApp
2023-04-13 02:01:25.444783973    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-04-13 02:01:25.445921164      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-04-13 02:01:25.446055792    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-04-13 02:01:25.447175149      from frigate.config import FrigateConfig
2023-04-13 02:01:25.447303555    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-04-13 02:01:25.448659725      import matplotlib.pyplot as plt
2023-04-13 02:01:25.448799334    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-04-13 02:01:25.450071672      from . import _api, _version, cbook, _docstring, rcsetup
2023-04-13 02:01:25.450204207    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-04-13 02:01:25.451383027      from matplotlib.colors import Colormap, is_color_like
2023-04-13 02:01:25.451514951    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-04-13 02:01:25.452678901      from matplotlib import _api, _cm, cbook, scale
2023-04-13 02:01:25.452978120    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-04-13 02:01:25.454118977      from matplotlib.ticker import (
2023-04-13 02:01:25.454253494    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-04-13 02:01:25.455563719      from matplotlib import transforms as mtransforms
2023-04-13 02:01:25.455697236    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-04-13 02:01:25.456846279      from matplotlib._path import (
2023-04-13 02:01:25.457482049  ImportError: numpy.core.multiarray failed to import
2023-04-13 02:01:25.647912839  [INFO] Service Frigate exited with code 1 (by signal 0)
2023-04-13 02:01:25.654741297  [INFO] Starting go2rtc...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-04-13 02:01:25.700443401  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-04-13 02:01:25.813191177  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2023-04-13 02:01:25.846552163  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
Command will not run.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

HikVision and Lorex 

### Any other information that may be helpful

Previously worked without any issues.  Not sure if update caused failure or not.  Auto Update was turned on.

**Comment by NickM-27** [comment]
are you running on 32bit OS? recommendation is to run 64bit

**Comment by evasilisin1984** [comment]
It’s running on raspberry Pi running HA.   It’s been that way for awhile.  It just now started to fail.

**Comment by NickM-27** [comment]
There are users running 32 bit without issues, in the next release it will be removed. 

And yes, that is one of the image tags available as shown in the release notes

**Comment by blakeblackshear** [comment]
I went ahead and added a note to breaking changes about the new location for images.

**Comment by homeassistant7** [comment]
I have the same issue running on Raspberry Pi 3, 32-bit. 
`ImportError: numpy.core.multiarray failed to import`

Rolled back to 0.10.1 as I had other issues with 0.11 that I never got around to resolving (I think that was camera related).

**Comment by groenmarsmannetje** [comment]
Same issue here...
