### ISSUE TITLE
[Support]: go2rtc crashes

### ISSUE THREAD

**Issue by hkapanen** [blakeblackshear/frigate#6037]
### Describe the problem you are having

go2rtc crashes at Frigate add-on startup and keeps on crashing repeatedly thereafter.

### Version

0.12.0

### Frigate config file

```yaml
logger:
  default: info

go2rtc:
  streams:
    etuovi: 
      - path: rtsp://****:****@192.168.***.***:554/s0
  log:
    format: text
    exec: trace
    
mqtt:
  host: 192.168.***.***
  user: ****
  password: ****

ffmpeg:
  hwaccel_args: preset-vaapi
  input_args: preset-rtsp-generic

environment_vars:
  LIBVA_DRIVER_NAME: i965

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous

detect:
  width: 1920 
  height: 1080
  fps: 10

cameras:
  etuovi:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/etuovi
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - cat
        - bird
        - bicycle
    record:
      enabled: True
      events:
        pre_capture: 3
        post_capture: 3
    snapshots:
      enabled: True
    motion:
      mask:
        - 0,513,1225,0,0,0
        - 1658,0,1652,138,1452,138,1445,0
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-04-13 08:31:42.279351766  [INFO] Preparing go2rtc config...
s6-rc: info: service go2rtc-healthcheck successfully started
2023-04-13 08:31:42.296549781  [INFO] Starting Frigate...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-04-13 08:31:42.305558146  [INFO] Starting NGINX...
2023-04-13 08:31:42.360347039  [INFO] Got IP address from supervisor: 192.168.0.186
s6-rc: info: service legacy-services successfully started
2023-04-13 08:31:42.433354501  [INFO] Got WebRTC port from supervisor: 8555
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 90, in <module>
    go2rtc_config["streams"][name][i] = stream.format(**FRIGATE_ENV_VARS)
AttributeError: 'dict' object has no attribute 'format'
2023-04-13 08:31:42.875105518  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-04-13 08:31:43.881410460  [INFO] Preparing go2rtc config...
2023-04-13 08:31:43.941592605  [INFO] Got IP address from supervisor: 192.168.0.186
2023-04-13 08:31:44.008265343  [INFO] Got WebRTC port from supervisor: 8555
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 90, in <module>
    go2rtc_config["streams"][name][i] = stream.format(**FRIGATE_ENV_VARS)
AttributeError: 'dict' object has no attribute 'format'
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 0

Audio:

Codec: AAC (Advanced Audio Coding)

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 1920x1080
FPS: 15/1
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Unifi G3

**Comment by blakeblackshear** [comment]
Does your password have curly braces or something? It's failing when trying to substitute the password in the go2rtc config.

**Comment by hkapanen** [comment]
No special characters on user:pass, just plain alphabet characters.

**Comment by blakeblackshear** [comment]
I see. You added a `path:` in the go2rtc config section. Check the docs again: https://docs.frigate.video/guides/configuring_go2rtc/

```yaml
go2rtc:
  streams:
    etuovi: 
      - path: rtsp://****:****@192.168.***.***:554/s0
  log:
    format: text
    exec: trace
```

It should be:
```yaml
go2rtc:
  streams:
    etuovi: 
      - rtsp://****:****@192.168.***.***:554/s0
  log:
    format: text
    exec: trace
```
