### ISSUE TITLE
[HW Accel Support]: Google Coral Not Found in Docker

### ISSUE THREAD

**Issue by soloam** [blakeblackshear/frigate#6052]
### Describe the problem you are having

I have proxmox and I have a debian 11 VM running docker, I tried to add a USB Google Coral. I have passed the TPU to the vm, 

In the VM I do lsusb and I get:

```
Bus 003 Device 002: ID 18d1:9302 Google Inc.
```

Can't get it to work

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  host: xx.xx.xx.xx
  #user: PASSWORD
  #password: PASSWORD

detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/custom_model.tflite"

detect:
  stationary:
    interval: 10
  fps: 5

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.7

cameras:
  livingroom:
    mqtt: 
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500
    detect:
      width: 1152
      height: 864
      fps: 5
    ffmpeg:
      inputs:
        - path: rtsp://xxxx.xxx.xxx.xxx
          roles:
            - rtmp
            - detect
  varanda:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 500   
    ffmpeg:
      inputs:
        - path: rtsp://xxxx.xxx.xxx.xxx
          roles:
            - rtmp
            - detect
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb
    #  - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-li>
    #  - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate.yml:/config/config.yml
      - /mnt/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
2023-04-13 18:14:47.185552163  [2023-04-13 18:14:44] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-04-13 18:14:47.186496167  Process detector:coral:
2023-04-13 18:14:47.186499212  [2023-04-13 18:14:47] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-04-13 18:14:47.186574690  [2023-04-13 18:14:47] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-04-13 18:14:47.187670204  Traceback (most recent call last):
2023-04-13 18:14:47.187673199    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-04-13 18:14:47.187674669      self.run()
2023-04-13 18:14:47.187676272    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-04-13 18:14:47.187679164      self._target(*self._args, **self._kwargs)
2023-04-13 18:14:47.187697559    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-04-13 18:14:47.187699181      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-04-13 18:14:47.187700667    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-04-13 18:14:47.187702077      self.detect_api = create_detector(detector_config)
2023-04-13 18:14:47.187703619    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-04-13 18:14:47.187705792      return api(detector_config)
2023-04-13 18:14:47.187707394    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 39, in __init__
2023-04-13 18:14:47.187725103      self.interpreter = Interpreter(
2023-04-13 18:14:47.187726823    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
2023-04-13 18:14:47.187728591      _interpreter_wrapper.CreateWrapperFromFile(
2023-04-13 18:14:47.187730008  ValueError: Could not open '/custom_model.tflite'.
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Proxmox

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

not relevant

### Any other information that may be helpful

In the VM I do lsusb and I get:

```
Bus 003 Device 002: ID 18d1:9302 Google Inc.
```

**Comment by soloam** [comment]
I found the problem... I had to remove:

```yaml
    model:
      path: "/custom_model.tflite"
```

Now just a question, i'm getting Inference Speed of 20 with 2 cameras, is this normal, I was expecting lower with the TPU!

**Comment by NickM-27** [comment]
for proxmox that seems normal, running on bare metal linux usually is 10 ms but users have reported proxmox adds some delays. Seeing as the original issue is fixed, going to close this. Feel free to create a new issue if something else comes up
