### ISSUE TITLE
[Detector Support]: Running custom model TensorRT/GPU

### ISSUE THREAD

**Issue by christian-sapconet** [blakeblackshear/frigate#6156]
### Describe the problem you are having

Hi, 

I would like to run my own custom yolo model (TensorRT) on the frigate for inference and would just like to know what does frigate expect in the output layer of the model?

The normal tiny yolo model runs 100% fine, but I would like to be able to keep improving the model. 

Thnx in advance!

### Version

0.12.0-da3e197

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 10.0.10.46
  user: frigate
  password: something



database:
  path: /db/frigate.db

cameras:
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.15/live
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    record:
      enabled: True
    snapshots:  
      timestamp: True
      bounding_box: False
      retain:
        default: 1
  driveway2:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.16:554/live
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - dog
        - car
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: False
      retain:
        default: 1

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  # path: /trt-models/yolov7-tiny-416.trt
  path: /trt-models/model.trt
  # input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

record:
  enabled: true
  retain:
    days: 0
  events:
    retain:
      default: 3

# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: objects
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "64mb" # update for your cameras based on calculation above
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/frigate/config.yml:/config/config.yml
      - /mnt/frigate-footage/frigate_footage/nvidia/:/media/frigate
      - /home/ubuntu/frigate/media/:/db
      - /home/ubuntu/trt-models/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
2023-04-19 10:06:31.400981185  [INFO] Starting Frigate...
2023-04-19 10:06:31.957687054  [2023-04-19 10:06:31] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-19 10:06:31.971182882  [2023-04-19 10:06:31] peewee_migrate                 INFO    : Starting migrations
2023-04-19 10:06:31.973618071  [2023-04-19 10:06:31] peewee_migrate                 INFO    : There is nothing to migrate
2023-04-19 10:06:31.986253439  [2023-04-19 10:06:31] frigate.app                    INFO    : Output process started: 434
2023-04-19 10:06:31.989779120  [2023-04-19 10:06:31] frigate.app                    INFO    : Camera processor started for driveway: 437
2023-04-19 10:06:31.994562306  [2023-04-19 10:06:31] detector.tensorrt              INFO    : Starting detection process: 432
2023-04-19 10:06:32.075260991  [2023-04-19 10:06:31] frigate.app                    INFO    : Camera processor started for cam2: 439
2023-04-19 10:06:32.075341642  [2023-04-19 10:06:31] frigate.app                    INFO    : Capture process started for driveway: 442
2023-04-19 10:06:32.075394583  [2023-04-19 10:06:32] frigate.app                    INFO    : Capture process started for cam2: 446
2023-04-19 10:06:32.223112163  [2023-04-19 10:06:32] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +188, GPU +0, now: CPU 244, GPU 890 (MiB)
2023-04-19 10:06:32.236601201  [2023-04-19 10:06:32] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 40 MiB
2023-04-19 10:06:32.248081855  [2023-04-19 10:06:32] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::30] Error Code 1: Serialization (Serialization assertion magicTagRead == kMAGIC_TAG failed.Magic tag does not match)
2023-04-19 10:06:32.254390409  Process detector:tensorrt:
2023-04-19 10:06:32.254392289  [2023-04-19 10:06:32] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
2023-04-19 10:06:32.254897745  Traceback (most recent call last):
2023-04-19 10:06:32.254906395    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-04-19 10:06:32.254907075      self.run()
2023-04-19 10:06:32.254907745    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-04-19 10:06:32.254908345      self._target(*self._args, **self._kwargs)
2023-04-19 10:06:32.254910075    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-04-19 10:06:32.254911425      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-04-19 10:06:32.254912205    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-04-19 10:06:32.254923615      self.detect_api = create_detector(detector_config)
2023-04-19 10:06:32.254924305    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-04-19 10:06:32.254924875      return api(detector_config)
2023-04-19 10:06:32.254932155    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 220, in __init__
2023-04-19 10:06:32.254932795      self.input_shape = self._get_input_shape()
2023-04-19 10:06:32.254933475    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 92, in _get_input_shape
2023-04-19 10:06:32.254933965      binding = self.engine[0]
2023-04-19 10:06:32.254934495  TypeError: 'NoneType' object is not subscriptable
2023-04-19 10:06:32.254937345  Exception ignored in: <function TensorRtDetector.__del__ at 0x7fe6f4b78700>
2023-04-19 10:06:32.254937895  Traceback (most recent call last):
2023-04-19 10:06:32.254938595    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-04-19 10:06:32.255010046      if self.outputs is not None:
2023-04-19 10:06:32.255010836  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

**Comment by ilya-merkushin** [comment]
Hi.
Same problem with the custom model.
I have a custom yolo model, but it is based on the WongKinYiu repository, not on darknet. The model works successfully on Triton.

I got the same error as [christian-sapconet](https://github.com/christian-sapconet) when generating a trt-model using tensorrt with a version less than 22.07.

When using 22.07, a new error occurred (Frigate v0.12.0): 
```
frigate.detectors.plugins.tensorrt ERROR   : can't convert negative value to size_t
Traceback (most recent call last):
 File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 228, in __init__
  ) = self._allocate_buffers()
 File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 130, in _allocate_buffers
  err, host_mem = cuda.cuMemHostAlloc(
 File "cuda/cuda.pyx", line 14069, in cuda.cuda.cuMemHostAlloc
 OverflowError: can't convert negative value to size_t
```


Is it possible to fix it?

P.S.
I create a trt-model based on WongKinYiu recommendations to export yolov7 to TensorRT:
to onnx `python export.py --weights yolo7-custom.pt --grid --end2end --dynamic-batch --simplify --topk-all 100 --iou-thres 0.65 --conf-thres 0.25 --img-size 640 640`
to trt `./tensorrt/bin/trtexec --onnx=yolov7-custom.onnx --minShapes=images:1x3x640x640 --optShapes=images:8x3x640x640 --maxShapes=images:8x3x640x640 --fp16 --workspace=4096 --saveEngine=yolov7-custom.engine --timingCacheFile=timing.cache`

Frigate v0.12.0:
```yaml
model:  
 path: /trt-models/yolov7-custom.rt  
 input_tensor: nchw  
 input_pixel_format: bgr  
 width: 640  
 height: 640  
 labelmap:  
  1: n1  
  2: n2  
```

**Comment by NateMeyer** [comment]
Using the 22.07 version is a good place to start.

The tensorrt models included in the frigate documentation come from https://github.com/yeahme49/tensorrt_demos, which includes an extra library `libyolo_layer.so` that gets loaded as a plugin to do extra processing on the model.  Each detection result then has a format of `[x, y, w, h, box_confidence, class_id, class_prob]`.

I'm not sure if this plugin layer is used or needed when converting the model? Otherwise you could copy the `tensorrt.py` detector and modify the output processing to handle your model's outputs.  Then you could map this file back in to the detectors/plugins folder to use it.

**Comment by klutzzykitty** [comment]
Hi @christian-sapconet and @ilya-merkushin 
stumbled upon this recently when reading through frigate+ custom models. 

I see the issue was closed, if so, please do share the working procedure on  
how the WongKinYiu yolov7 trained model was converted to a working TRT model for frigate? 

Thanks!
