### ISSUE TITLE
[Detector Support]:  Coral Ai M2 on PC windows 10 with Docker

### ISSUE THREAD

**Issue by Gazz-yniere** [blakeblackshear/frigate#6170]
### Describe the problem you are having

Hello,

I"m trying to figure out how to use the Coral AI pci (on M2) with my PC. The Frigate docker is not able to find my device but it's working correctly with the tutorial.

So my configuration is:
Intel CPU 11th Gen Intel Core i5-11400
M2 Coral AI 
Windows 10
Docker 

I installed all drivers and did the tutorial [coral.ai](https://coral.ai/docs/accelerator/get-started/#3-run-a-model-on-the-edge-tpu)
everything running like a charm.

I run this command to run frigate on docker windows:

`docker run -d --name frigate0.12 --restart=unless-stopped --shm-size=64m -v c:/frigate_012/storage:/media/frigate -v c:/frigate_012/config.yml:/config/config.yml:ro -e FRIGATE_RTSP_PASSWORD='xxxx' -p 5000:5000 -p 1935:1935 ghcr.io/blakeblackshear/frigate:0.12.0`

in my config file I add 
```
detectors:
  # Required: name of the detector
  coral:
    type: edgetpu
    device: pci:1
```
and got the error:

```
[2023-04-20 07:03:29] detector.coral                 INFO    : Starting detection process: 254
[2023-04-20 07:03:29] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:1
[2023-04-20 07:03:29] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
    object_detector = LocalObjectDetector(detector_config=detector_config)
  File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
    self.detect_api = create_detector(detector_config)
  File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
    return api(detector_config)
  File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

And the coral ai is not recognized so I had this argument --device="class/e8c7bb5b-6bd1-44c5-b852-2e5038239871" to link the device to the docker but not able to run the docker and got the error : 

`docker: class/e8c7bb5b-6bd1-44c5-b852-2e5038239871 is not an absolute path.`

I do not understand how I can use the coral Ai through docker on windows!

Anyone have an idea?
 

### Version

0.12

### Frigate config file

```yaml
detectors:
  # Required: name of the detector
  coral:
    type: edgetpu
    device: pci:1
```

### docker-compose file or Docker CLI command

```yaml
docker run -d --name frigate0.12 --restart=unless-stopped --shm-size=64m -v c:/frigate_012/storage:/media/frigate -v c:/frigate_012/config.yml:/config/config.yml:ro -e FRIGATE_RTSP_PASSWORD='xxxx' -p 5000:5000 -p 1935:1935 ghcr.io/blakeblackshear/frigate:0.12.0
```

### Relevant log output

```shell
[2023-04-20 07:03:29] detector.coral                 INFO    : Starting detection process: 254
[2023-04-20 07:03:29] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:1
[2023-04-20 07:03:29] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
    raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
    object_detector = LocalObjectDetector(detector_config=detector_config)
  File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
    self.detect_api = create_detector(detector_config)
  File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
    return api(detector_config)
  File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
    edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Operating system

Windows

### Install method

Docker CLI

### Coral version

M.2

**Comment by my-umd** [comment]
Need to run docker in privileged mode.

**Comment by Gazz-yniere** [comment]
so I tried to add --privileged mode on my docker run command but nothing change, still avec same issue with or without --device

**Comment by my-umd** [comment]
If you only have one Coral, maybe remove ':1' from 'pci:1'?

**Comment by NickM-27** [comment]
Windows is not a supported install method. Some users have anecdotally gotten it working but frigate does not support the install. I would suggest commenting on https://github.com/blakeblackshear/frigate/discussions/4375
