### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by alexvdbergh** [blakeblackshear/frigate#6195]
### Describe the problem you are having

Iam following the guide of Everthing Smart Home https://www.youtube.com/watch?v=pqDCEZSVeRk but i get stuck at the config file. Looked at different config ways simple to complex but i keep the same logging errors 

### Version

 0.12.0

### Frigate config file

```yaml
mqtt:
    host: 192.168.50.13
    user: 
    password: 

Cameras:
  Voordeurbel:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.50.98:554/h264Preview_01_main
          roles:
            - detect
    width: 2560
    height: 1920
    fps: 5

detectors: 
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-04-21 20:35:18.358086440  [INFO] Preparing go2rtc config...
2023-04-21 20:35:18.358454188  [INFO] Starting Frigate...
2023-04-21 20:35:18.358744958  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-04-21 20:35:18.383816526  [INFO] Got IP address from supervisor: 192.168.50.13
2023-04-21 20:35:18.409333283  [INFO] Got WebRTC port from supervisor: 8555
2023-04-21 20:35:18.597701454  [INFO] Starting go2rtc...
2023-04-21 20:35:18.640778053  22:35:18.640 INF go2rtc version 1.2.0 linux/amd64
2023-04-21 20:35:18.641110852  22:35:18.641 INF [api] listen addr=:1984
2023-04-21 20:35:18.641252508  22:35:18.641 INF [rtsp] listen addr=:8554
2023-04-21 20:35:18.641382548  22:35:18.641 INF [srtp] listen addr=:8443
2023-04-21 20:35:18.641482858  22:35:18.641 INF [webrtc] listen addr=:8555
2023-04-21 20:35:19.105462596  [2023-04-21 22:35:19] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-04-21 20:35:19.108280112  *************************************************************
2023-04-21 20:35:19.108282444  *************************************************************
2023-04-21 20:35:19.108284567  ***    Your config file is not valid!                     ***
2023-04-21 20:35:19.108286116  ***    Please check the docs at                           ***
2023-04-21 20:35:19.108287194  ***    https://docs.frigate.video/configuration/index     ***
2023-04-21 20:35:19.108296575  *************************************************************
2023-04-21 20:35:19.108297584  *************************************************************
2023-04-21 20:35:19.108298804  ***    Config Validation Errors                           ***
2023-04-21 20:35:19.108299774  *************************************************************
2023-04-21 20:35:19.108305659  2 validation errors for FrigateConfig
2023-04-21 20:35:19.108306392  cameras
2023-04-21 20:35:19.108307260    field required (type=value_error.missing)
2023-04-21 20:35:19.108307995  Cameras
2023-04-21 20:35:19.108308861    extra fields not permitted (type=value_error.extra)
2023-04-21 20:35:19.108717196  Traceback (most recent call last):
2023-04-21 20:35:19.108719025    File "/opt/frigate/frigate/app.py", line 351, in start
2023-04-21 20:35:19.108720264      self.init_config()
2023-04-21 20:35:19.108721622    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-04-21 20:35:19.108722851      user_config = FrigateConfig.parse_file(config_file)
2023-04-21 20:35:19.108724194    File "/opt/frigate/frigate/config.py", line 1072, in parse_file
2023-04-21 20:35:19.108725298      return cls.parse_obj(config)
2023-04-21 20:35:19.108726561    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2023-04-21 20:35:19.108727642    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-04-21 20:35:19.108728564  pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
2023-04-21 20:35:19.108729860  cameras
2023-04-21 20:35:19.108730723    field required (type=value_error.missing)
2023-04-21 20:35:19.108731437  Cameras
2023-04-21 20:35:19.108750651    extra fields not permitted (type=value_error.extra)
2023-04-21 20:35:19.108751836  
2023-04-21 20:35:19.108752995  *************************************************************
2023-04-21 20:35:19.108764882  ***    End Config Validation Errors                       ***
2023-04-21 20:35:19.108766307  *************************************************************
2023-04-21 20:35:20.201647444  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-04-21 20:35:20.206889124  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-04-21 20:35:20.251753033  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-04-21 20:35:20.258281704  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-04-21 20:35:20.269465567  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

Im running HassOS dedicated on a old work intel I5 desktop

**Comment by NickM-27** [comment]
`Cameras` != `cameras` you, capitalization matters

**Comment by alexvdbergh** [comment]
Great that helpt a whole bit! 

But now it keeps hanging on the width, height, fps 

2023-04-21 20:57:00.369225203  3 validation errors for FrigateConfig
2023-04-21 20:57:00.369226019  cameras -> voordeurbel -> fps
2023-04-21 20:57:00.369226852    extra fields not permitted (type=value_error.extra)
2023-04-21 20:57:00.369227641  cameras -> voordeurbel -> height
2023-04-21 20:57:00.369228681    extra fields not permitted (type=value_error.extra)
2023-04-21 20:57:00.369229676  cameras -> voordeurbel -> width
2023-04-21 20:57:00.369230934    extra fields not permitted (type=value_error.extra)
2023-04-21 20:57:00.369608155  Traceback (most recent call last):
2023-04-21 20:57:00.369609358    File "/opt/frigate/frigate/app.py", line 351, in start
2023-04-21 20:57:00.369610156      self.init_config()
2023-04-21 20:57:00.369611036    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-04-21 20:57:00.369611867      user_config = FrigateConfig.parse_file(config_file)
2023-04-21 20:57:00.369612739    File "/opt/frigate/frigate/config.py", line 1072, in parse_file
2023-04-21 20:57:00.369613537      return cls.parse_obj(config)
2023-04-21 20:57:00.369614444    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2023-04-21 20:57:00.369615318    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-04-21 20:57:00.369616243  pydantic.error_wrappers.ValidationError: 3 validation errors for FrigateConfig
2023-04-21 20:57:00.369617354  cameras -> voordeurbel -> fps
2023-04-21 20:57:00.369618225    extra fields not permitted (type=value_error.extra)
2023-04-21 20:57:00.369649877  cameras -> voordeurbel -> height
2023-04-21 20:57:00.369650846    extra fields not permitted (type=value_error.extra)
2023-04-21 20:57:00.369651975  cameras -> voordeurbel -> width
2023-04-21 20:57:00.369652889    extra fields not permitted (type=value_error.extra)

**Comment by NickM-27** [comment]
I'd highly suggest reading our docs. all of those are properties of `detect` which you seem to be missing

**Comment by alexvdbergh** [comment]
Reading a lot but still a noob : )) 

I thought this was right in my file

            - detect
    width: 2560
    height: 1920
    fps: 5

**Comment by alexvdbergh** [comment]
Thanks for the help will read on

**Comment by NickM-27** [comment]
compare what you have put to https://docs.frigate.video/guides/getting_started#step-1-add-a-detect-stream

```
mqtt:
  enabled: False

cameras:
  name_of_your_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

**Comment by alexvdbergh** [comment]
whoohoo thanx for the great help! 

What a little word makes a differente .... detect:
