### ISSUE TITLE
[Detector Support]: ValueError: Failed to load delegate from libedgetpu.so.1.0

### ISSUE THREAD

**Issue by DushanthaS** [blakeblackshear/frigate#6254]
### Describe the problem you are having

Not sure this is anything to do with the frigate itself, but raising the issue here in order to get input from the community and for documentation purposes. 

I am getting "ValueError: Failed to load delegate from libedgetpu.so.1.0" repeatedly on frigate on docker inside LXC container on Proxmox host. I also Tried on a VM (with PCI bypass, and got the same error).

AFAIK TPU is detected on the system (both proxmox and LXC) I get the following output on LXC 

```
root@pve:# ls /dev/apex_0
/dev/apex_0
root@pve:# lspci -nn | grep 089a
01:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
```

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 10.0.18.4
  port: 1883
  user: mqttuser
  password: XXXXXXX
timestamp_style:
  position: "tl"
  format: "%d-%m-%Y %H:%M:%S"
  color:
    red: 255
    green: 0
    blue: 0
  thickness: 2

birdseye:
  enabled: True
  width: 1918
  height: 1080
  quality: 8
  mode: motion

objects:
  track:
    - person
    - car
    - dog
  filters:
    person:
      min_score: 0.5
      threshold: 0.7
      mask:
        - 0,0,640,0,640,99,0,127,0,110
    car:
      min_score: 0.5
      threshold: 0.7
      mask:
        - 0,108,640,74,640,0,0,0


# Global rtmp configuration
rtmp:
  enabled: true

# Global snapshots configuration
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 7



# Global record configuration
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 7
      mode: active_objects



cameras:
  reolink:
    ffmpeg:
     # hwaccel_args: -c:v h264_cuvid
      input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: rtmp://10.0.10.254/bcs/channel0_sub.bcs?channel=0&stream=1&user=Frigate&password=XXXXXX
          roles:
            - rtmp
        - path: rtmp://10.0.10.254/bcs/channel0_main.bcs?channel=0&stream=1&user=Frigate&password=XXXXXX
          roles:
            - detect
            - record

    # Camera-specific detection and recording configuration
    detect:
      width: 1280
      height: 718
      fps: 5
    record:
      enabled: True
      retain_days: 30
      events:
        retain:
          default: 10

  C180:
    ffmpeg:
     # hwaccel_args: -c:v h264_cuvid
     # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
      #output_args:
       # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
      inputs:
        - path: rtsp://Frigate:XXXXXX@10.0.10.247:554/stream2
          roles:
            - rtmp
        - path: rtsp://Frigate:XXXXXX@10.0.10.247:554/stream1
          roles:
            - detect
            - record

    # Camera-specific detection and recording configuration
    detect:
      width: 1280
      height: 718
      fps: 5
    record:
      enabled: True
      retain_days: 10
      events:
        retain:
          default: 7
    objects:
      track:
        - person






  C100:
      ffmpeg:
      # hwaccel_args: -c:v h264_cuvid
      # input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -flags low_delay -strict experimental -analyzeduration 1000M -probesize 1000M -rw_timeout 5000000
        #output_args:
        # record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
        inputs:
          - path: rtsp://Frigate:XXXXXX@10.0.10.244:554/stream2
            roles:
              - rtmp
          - path: rtsp://Frigate:XXXXXX@10.0.10.244:554/stream1
            roles:
              - detect
              - record

      # Camera-specific detection and recording configuration
      detect:
        width: 1280
        height: 718
        fps: 5
      record:
        enabled: True
        retain_days: 10
        events:
          retain:
            default: 7
      objects:
        track:
          - person
detectors:
  coral:
    type: edgetpu
    device: pci:0


# Available log levels are: debug, info, warning, error, critical
logger:
  default: info
  logs:
    frigate.record: info
    frigate.event: debug
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.0
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config.yml:/config/config.yml:ro
      - /mnt/hdd/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "XXXXXX"
```

### Relevant log output

```shell
2023-04-23 14:13:35.377352906 [2023-04-23 14:13:22] frigate.detectors.plugins.edgetpu_tfl INFO : Attempting to load TPU as pci:0
2023-04-23 14:13:35.377590706 Process detector:coral:
2023-04-23 14:13:35.377719405 [2023-04-23 14:13:35] frigate.detectors.plugins.edgetpu_tfl ERROR : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-04-23 14:13:35.403316706 Traceback (most recent call last):
2023-04-23 14:13:35.403321637 File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-04-23 14:13:35.403322841 delegate = Delegate(library, options)
2023-04-23 14:13:35.403349218 File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in init
2023-04-23 14:13:35.403350884 raise ValueError(capture.message)
2023-04-23 14:13:35.403351895 ValueError
2023-04-23 14:13:35.403352820
2023-04-23 14:13:35.403354000 During handling of the above exception, another exception occurred:
2023-04-23 14:13:35.403357991
2023-04-23 14:13:35.403359072 Traceback (most recent call last):
2023-04-23 14:13:35.403506237 File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-04-23 14:13:35.403507799 self.run()
2023-04-23 14:13:35.403509095 File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-04-23 14:13:35.403510225 self._target(*self._args, **self._kwargs)
2023-04-23 14:13:35.403511389 File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-04-23 14:13:35.403512632 object_detector = LocalObjectDetector(detector_config=detector_config)
2023-04-23 14:13:35.403514374 File "/opt/frigate/frigate/object_detection.py", line 52, in init
2023-04-23 14:13:35.403516471 self.detect_api = create_detector(detector_config)
2023-04-23 14:13:35.403517682 File "/opt/frigate/frigate/detectors/init.py", line 24, in create_detector
2023-04-23 14:13:35.403519189 return api(detector_config)
2023-04-23 14:13:35.403520434 File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in init
2023-04-23 14:13:35.403539562 edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-04-23 14:13:35.403541011 File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-04-23 14:13:35.403559932 raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-04-23 14:13:35.403561265 ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-04-23 14:13:35.403562309
2023-04-23 14:13:42.497007034 [2023-04-23 14:13:42] frigate.watchdog INFO : Detection appears to have stopped. Exiting Frigate...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

LXC config

arch: amd64
cores: 4
features: nesting=1
hostname: frigate2
memory: 1024
mp0: STORE:vm-109-disk-0,mp=/mnt/STORE/,size=8G
net0: name=eth0,bridge=vmbr0,firewall=1,gw=10.0.18.1,hwaddr=AE:7F:40:F1:51:CA,ip=10.0.18.225/24,type=veth
ostype: debian
rootfs: VM:vm-109-disk-0,size=8G
swap: 512
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.apparmor.profile: unconfined
lxc.cgroup2.devices.allow: a
lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file 0, 0
lxc.mount.entry: /dev/apex_0 dev/apex_0 none bind,optional,create=file 0, 0
lxc.cap.drop:
lxc.mount.auto: cgroup:rw

**Comment by NickM-27** [comment]
This is most likely a proxmox config issue. I'd suggest getting a shell in frigate itself and see if it sees /dev/apex_0 correctly

**Comment by DushanthaS** [comment]
Thanks again, its still erroring out. I followed multiple guides and it seems to be not working for some reason. 

2023-04-25 16:51:11.094012773  [2023-04-25 16:51:09] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-04-25 16:51:11.101294420  Process detector:coral:
2023-04-25 16:51:11.101297490  [2023-04-25 16:51:11] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.

**Comment by NickM-27** [comment]
I don't know much about this type of setup other than many users have this similar problem and it's often some issue or another with passing info through the various configs. You may want to look at posting in one of the proxmox specific discussions in this repo

**Comment by stefan2030** [comment]
> Maybe try
> 
> ```
> detectors:
>   coral:
>     type: edgetpu
>     device: pci
> ```
> 
> and see. It does not like something that it is seeing.

this was it! In the documentation it says " decice: /dev/apex_0

it should be device: pci instead, now it works (unraid docker PCI M.2 Coral TPU

**Comment by jasonhwest** [comment]
I see this reference in "Step 4: Configure detectors" on this page: https://docs.frigate.video/guides/getting_started

**Comment by hawkeye217** [comment]
Ah, I see. You're confusing the `docker-compose.yml` file (which is displayed there in step 4) and the `config.yml` file, which is Frigate's configuration file. The documentation is indeed correct as it's showing you `docker-compose.yml`.
