### ISSUE TITLE
[Support]: frigate docker keeps restarting 

### ISSUE THREAD

**Issue by SrFatCat** [blakeblackshear/frigate#6292]
### Describe the problem you are having

Frigate cannot start after installation via docker compose.

### Version

:stable

### Frigate config file

```yaml
mqtt:
  host: 192.168.0.60
  user: bogdan
  password: **password**

cameras:
  driveway_cam:
    ffmpeg:
      inputs:
        - path: rtsp://admin:marus14kaSC9@192.168.0.137:554/user=admin_password=HT7HKwnL_channel=0_stream=1
          roles:
            - detect
    width: 704
    height: 576
    fps: 5

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service fix-attrs successfully started
 s6-rc: info: service legacy-cont-init: starting
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service nginx-log successfully started
 s6-rc: info: service go2rtc-log successfully started
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 s6-rc: info: service frigate successfully started
 s6-rc: info: service nginx: starting
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 s6-rc: info: service legacy-services successfully started
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
 s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 s6-rc: info: service nginx-log successfully stopped
 s6-rc: info: service frigate-log successfully stopped
 s6-rc: info: service go2rtc successfully stopped
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
 s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 s6-rc: info: service fix-attrs successfully started
 s6-rc: info: service legacy-cont-init: starting
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service nginx-log successfully started
 s6-rc: info: service go2rtc-log successfully started
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 s6-rc: info: service frigate successfully started
 s6-rc: info: service nginx: starting
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 s6-rc: info: service legacy-services successfully started
 2023-04-27 18:39:14.928431702  [INFO] Preparing go2rtc config...
 2023-04-27 18:39:14.937792029  [INFO] Starting Frigate...
 2023-04-27 18:39:14.951706067  [INFO] Starting NGINX...
 2023-04-27 18:39:15.669112125  [INFO] Starting go2rtc...
 2023-04-27 18:39:15.879270242  18:39:15.879 INF go2rtc version 1.2.0 linux/arm
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
 s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 s6-rc: info: service nginx-log successfully stopped
 2023-04-27 18:39:15.880808158  18:39:15.880 INF [api] listen addr=:1984
 s6-rc: info: service frigate-log successfully stopped
 2023-04-27 18:39:15.881916132  18:39:15.881 INF [rtsp] listen addr=:8554
 2023-04-27 18:39:15.883352826  18:39:15.883 INF [srtp] listen addr=:8443
 s6-rc: info: service go2rtc successfully stopped
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
 s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 s6-rc: info: service fix-attrs successfully started
 s6-rc: info: service legacy-cont-init: starting
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service nginx-log successfully started
 s6-rc: info: service go2rtc-log successfully started
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service frigate successfully started
 s6-rc: info: service nginx: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 s6-rc: info: service legacy-services successfully started
 2023-04-27 18:39:15.884567207  18:39:15.884 INF [webrtc] listen addr=:8555
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
 s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 s6-rc: info: service nginx-log successfully stopped
 s6-rc: info: service frigate-log successfully stopped
 s6-rc: info: service go2rtc successfully stopped
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 2023-04-27 18:39:15.898093211  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
 s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service fix-attrs successfully started
 s6-rc: info: service legacy-cont-init: starting
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service go2rtc-log successfully started
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service nginx-log successfully started
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 s6-rc: info: service frigate successfully started
 s6-rc: info: service nginx: starting
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 s6-rc: info: service legacy-services successfully started
 2023-04-27 18:39:15.898596393  Traceback (most recent call last):
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
 s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 s6-rc: info: service nginx-log successfully stopped
 s6-rc: info: service frigate-log successfully stopped
 2023-04-27 18:39:15.898611893    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
 2023-04-27 18:39:15.899073297      return _run_code(code, main_globals, None,
 s6-rc: info: service go2rtc successfully stopped
 2023-04-27 18:39:15.899087260    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
 s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 s6-rc: info: service fix-attrs successfully started
 2023-04-27 18:39:15.899437406      exec(code, run_globals)
 s6-rc: info: service legacy-cont-init: starting
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service go2rtc-log successfully started
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service nginx-log successfully started
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 s6-rc: info: service frigate successfully started
 s6-rc: info: service nginx: starting
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 s6-rc: info: service legacy-services successfully started
 2023-04-27 18:39:15.899450535    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
 2023-04-27 18:39:15.899814385      from frigate.app import FrigateApp
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 2023-04-27 18:39:15.899827866    File "/opt/frigate/frigate/app.py", line 17, in <module>
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
 s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 s6-rc: info: service nginx-log successfully stopped
 2023-04-27 18:39:15.899837348      from frigate.comms.dispatcher import Communicator, Dispatcher
 s6-rc: info: service frigate-log successfully stopped
 s6-rc: info: service go2rtc successfully stopped
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 2023-04-27 18:39:15.899852440    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 2023-04-27 18:39:15.900065735      from frigate.config import FrigateConfig
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
 s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service fix-attrs successfully started
 2023-04-27 18:39:15.900360844    File "/opt/frigate/frigate/config.py", line 9, in <module>
 s6-rc: info: service legacy-cont-init: starting
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 2023-04-27 18:39:15.900656305      import matplotlib.pyplot as plt
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service go2rtc-log successfully started
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service nginx-log successfully started
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service frigate successfully started
 2023-04-27 18:39:15.900699916    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
 s6-rc: info: service nginx: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 s6-rc: info: service legacy-services successfully started
 2023-04-27 18:39:15.901058932      from . import _api, _version, cbook, _docstring, rcsetup
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 2023-04-27 18:39:15.901399337    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
 s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 2023-04-27 18:39:15.901412689      from matplotlib.colors import Colormap, is_color_like
 s6-rc: info: service nginx-log successfully stopped
 s6-rc: info: service frigate-log successfully stopped
 s6-rc: info: service go2rtc successfully stopped
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 2023-04-27 18:39:15.901422263    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
 s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 2023-04-27 18:39:15.901732743      from matplotlib import _api, _cm, cbook, scale
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service fix-attrs successfully started
 s6-rc: info: service legacy-cont-init: starting
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service nginx-log successfully started
 s6-rc: info: service go2rtc-log successfully started
 2023-04-27 18:39:15.901745650    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service frigate successfully started
 s6-rc: info: service nginx: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 2023-04-27 18:39:15.902102351      from matplotlib.ticker import (
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 s6-rc: info: service legacy-services successfully started
 2023-04-27 18:39:15.902115314    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
 2023-04-27 18:39:15.902517163      from matplotlib import transforms as mtransforms
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 2023-04-27 18:39:15.902821495    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
 2023-04-27 18:39:15.902865106      from matplotlib._path import (
 s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 s6-rc: info: service nginx-log successfully stopped
 s6-rc: info: service frigate-log successfully stopped
 s6-rc: info: service go2rtc successfully stopped
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 2023-04-27 18:39:15.902874402  ImportError: numpy.core.multiarray failed to import
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 2023-04-27 18:39:16.038918470  [INFO] Service Frigate exited with code 1 (by signal 0)
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
 s6-rc: info: service s6rc-fdholder: starting
 s6-rc: info: service s6rc-oneshot-runner: starting
 s6-rc: info: service s6rc-oneshot-runner successfully started
 s6-rc: info: service fix-attrs: starting
 s6-rc: info: service s6rc-fdholder successfully started
 s6-rc: info: service fix-attrs successfully started
 s6-rc: info: service legacy-cont-init: starting
 2023-04-27 18:39:16.068718514  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
 s6-rc: info: service legacy-cont-init successfully started
 s6-rc: info: service log-prepare: starting
 s6-rc: info: service log-prepare successfully started
 s6-rc: info: service nginx-log: starting
 s6-rc: info: service go2rtc-log: starting
 s6-rc: info: service frigate-log: starting
 s6-rc: info: service nginx-log successfully started
 2023-04-27 18:39:16.130547274  [INFO] Service NGINX exited with code 0 (by signal 0)
 s6-rc: info: service go2rtc-log successfully started
 s6-rc: info: service go2rtc: starting
 s6-rc: info: service frigate-log successfully started
 s6-rc: info: service go2rtc successfully started
 2023-04-27 18:39:16.139926138  exit OK
 s6-rc: info: service go2rtc-healthcheck: starting
 s6-rc: info: service frigate: starting
 s6-rc: info: service go2rtc-healthcheck successfully started
 s6-rc: info: service frigate successfully started
 s6-rc: info: service nginx: starting
 s6-rc: info: service nginx successfully started
 s6-rc: info: service legacy-services: starting
 2023-04-27 18:39:16.153397679  [INFO] The go2rtc service exited with code 0 (by signal 0)
 s6-rc: info: service legacy-services successfully started
 2023-04-27 18:39:22.574967508  [INFO] Preparing go2rtc config...
 2023-04-27 18:39:22.589651412  [INFO] Starting Frigate...
 2023-04-27 18:39:22.617316063  [INFO] Starting NGINX...
 2023-04-27 18:39:23.281281251  [INFO] Starting go2rtc...
 2023-04-27 18:39:23.443313889  18:39:23.443 INF go2rtc version 1.2.0 linux/arm
 2023-04-27 18:39:23.444586677  18:39:23.444 INF [api] listen addr=:1984
 2023-04-27 18:39:23.445482430  18:39:23.445 INF [rtsp] listen addr=:8554
 s6-rc: info: service legacy-services: stopping
 s6-rc: info: service legacy-services successfully stopped
 s6-rc: info: service nginx: stopping
 2023-04-27 18:39:23.446432942  18:39:23.446 INF [srtp] listen addr=:8443
 2023-04-27 18:39:23.447164789  18:39:23.446 INF [webrtc] listen addr=:8555
 s6-rc: info: service go2rtc-healthcheck: stopping
 s6-rc: info: service go2rtc-healthcheck successfully stopped
 s6-rc: info: service nginx successfully stopped
 s6-rc: info: service nginx-log: stopping
 s6-rc: info: service frigate: stopping
 s6-rc: info: service frigate successfully stopped
--More-- s6-rc: info: service go2rtc: stopping
 s6-rc: info: service frigate-log: stopping
 s6-rc: info: service nginx-log successfully stopped
 s6-rc: info: service frigate-log successfully stopped
 s6-rc: info: service go2rtc successfully stopped
 s6-rc: info: service go2rtc-log: stopping
 s6-rc: info: service go2rtc-log successfully stopped
 s6-rc: info: service log-prepare: stopping
 s6-rc: info: service s6rc-fdholder: stopping
 s6-rc: info: service log-prepare successfully stopped
 s6-rc: info: service legacy-cont-init: stopping
 s6-rc: info: service s6rc-fdholder successfully stopped
 s6-rc: info: service legacy-cont-init successfully stopped
 s6-rc: info: service fix-attrs: stopping
 s6-rc: info: service fix-attrs successfully stopped
 s6-rc: info: service s6rc-oneshot-runner: stopping
 s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, rtsp, from 'rtsp://admin:marus14kaSC9@192.168.0.137:554/user=admin_password=HT7HKwnL_channel=0_stream=1':
  Metadata:
    title           : RTSP Session
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 800x448, 12 fps, 12 tbr, 90k tbn, 12 tbc
    Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hiseeu WHD812

### Any other information that may be helpful

It's Raspberry PI 4B with 4Mb RAM
Linux hass 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
docker-compose version 1.29.2, build unknown
Docker version 23.0.4, build f480fb1

docker compose yaml file:
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    # devices:
      # - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      # - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/homeassistant/frigate/config.yml:/config/config.yml
      - /media/frigate:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "*password*"
```

**Comment by NickM-27** [comment]
you should be running with a 64bit OS, some 32bit OS seem to have issues running 0.12
