### ISSUE TITLE
[Support]: Frigate docker container continuously restarting

### ISSUE THREAD

**Issue by gradation0746** [blakeblackshear/frigate#6313]
### Describe the problem you are having

I have set up Frigate as a docker container. I was able to launch it once. I stopped the container and edited the config file to rename the camera. I restarted the container and the container keeps restarting and the webui will not load.

### Version

I can't get the Web UI to load. Latest docker image (stable)

### Frigate config file

```yaml
GNU nano 6.2                                                                                                     config.yml
mqtt:
  enabled: False

cameras:
  name_of_your_camera: frontcam # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://w9lVV8:wJVQsCdGq3WM@192.168.1.25:554/live/ch0 # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 2048 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
```

### Relevant log output

```shell
[+] Running 2/1
 ✔ Network frigate_default  Created                                                                                                                                                                                                   0.1s 
 ✔ Container frigate        Created                                                                                                                                                                                                   0.0s 
Attaching to frigate
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-04-28 16:16:55.597960919  [INFO] Starting NGINX...
frigate  | 2023-04-28 16:16:55.597962657  [INFO] Starting Frigate...
frigate  | 2023-04-28 16:16:55.597974378  [INFO] Preparing go2rtc config...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/go2rtc/create_config.py", line 27, in <module>
frigate  |     config: dict[str, any] = yaml.safe_load(raw_config)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
frigate  |     return load(stream, SafeLoader)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
frigate  |     return loader.get_single_data()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
frigate  |     node = self.get_single_node()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
frigate  |     document = self.compose_document()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
frigate  |     node = self.compose_node(None, None)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  |     item_value = self.compose_node(node, item_key)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
frigate  |     while not self.check_event(MappingEndEvent):
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
frigate  |     self.current_event = self.state()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
frigate  |     raise ParserError("while parsing a block mapping", self.marks[-1],
frigate  | yaml.parser.ParserError: while parsing a block mapping
frigate  |   in "<unicode string>", line 5, column 3:
frigate  |       name_of_your_camera: frontcam #  ...
frigate  |       ^
frigate  | expected <block end>, but found '<block mapping start>'
frigate  |   in "<unicode string>", line 6, column 5:
frigate  |         ffmpeg:
frigate  |         ^
frigate  | 2023-04-28 16:16:57.550488816  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate  | 2023-04-28 16:16:58.027409751  [2023-04-28 16:16:58] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
frigate  | 2023-04-28 16:16:58.028269706  *************************************************************
frigate  | 2023-04-28 16:16:58.028274196  *************************************************************
frigate  | 2023-04-28 16:16:58.028293506  ***    Your config file is not valid!                     ***
frigate  | 2023-04-28 16:16:58.028295338  ***    Please check the docs at                           ***
frigate  | 2023-04-28 16:16:58.028297191  ***    https://docs.frigate.video/configuration/index     ***
frigate  | 2023-04-28 16:16:58.028300667  *************************************************************
frigate  | 2023-04-28 16:16:58.028303234  *************************************************************
frigate  | 2023-04-28 16:16:58.028317405  ***    Config Validation Errors                           ***
frigate  | 2023-04-28 16:16:58.028331382  *************************************************************
frigate  | 2023-04-28 16:16:58.028393348  while parsing a block mapping
frigate  | 2023-04-28 16:16:58.028396775    in "<unicode string>", line 5, column 3:
frigate  | 2023-04-28 16:16:58.028398977        name_of_your_camera: frontcam #  ...
frigate  | 2023-04-28 16:16:58.028400663        ^
frigate  | 2023-04-28 16:16:58.028402795  expected <block end>, but found '<block mapping start>'
frigate  | 2023-04-28 16:16:58.028404724    in "<unicode string>", line 6, column 5:
frigate  | 2023-04-28 16:16:58.028406278          ffmpeg:
frigate  | 2023-04-28 16:16:58.028407912          ^
frigate  | 2023-04-28 16:16:58.030120141  Traceback (most recent call last):
frigate  | 2023-04-28 16:16:58.030124103    File "/opt/frigate/frigate/app.py", line 351, in start
frigate  | 2023-04-28 16:16:58.030126056      self.init_config()
frigate  | 2023-04-28 16:16:58.030128453    File "/opt/frigate/frigate/app.py", line 80, in init_config
frigate  | 2023-04-28 16:16:58.030130590      user_config = FrigateConfig.parse_file(config_file)
frigate  | 2023-04-28 16:16:58.030132313    File "/opt/frigate/frigate/config.py", line 1068, in parse_file
frigate  | 2023-04-28 16:16:58.030134040      config = load_config_with_no_duplicates(raw_config)
frigate  | 2023-04-28 16:16:58.030135957    File "/opt/frigate/frigate/util.py", line 78, in load_config_with_no_duplicates
frigate  | 2023-04-28 16:16:58.030140427      return yaml.load(raw_config, PreserveDuplicatesLoader)
frigate  | 2023-04-28 16:16:58.030143063    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
frigate  | 2023-04-28 16:16:58.030167896      return loader.get_single_data()
frigate  | 2023-04-28 16:16:58.030170429    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
frigate  | 2023-04-28 16:16:58.030172206      node = self.get_single_node()
frigate  | 2023-04-28 16:16:58.030174172    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
frigate  | 2023-04-28 16:16:58.030188149      document = self.compose_document()
frigate  | 2023-04-28 16:16:58.030190915    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
frigate  | 2023-04-28 16:16:58.030193156      node = self.compose_node(None, None)
frigate  | 2023-04-28 16:16:58.030195635    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  | 2023-04-28 16:16:58.030197681      node = self.compose_mapping_node(anchor)
frigate  | 2023-04-28 16:16:58.030200335    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  | 2023-04-28 16:16:58.030202468      item_value = self.compose_node(node, item_key)
frigate  | 2023-04-28 16:16:58.030216449    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  | 2023-04-28 16:16:58.030218197      node = self.compose_mapping_node(anchor)
frigate  | 2023-04-28 16:16:58.030220251    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
frigate  | 2023-04-28 16:16:58.030222118      while not self.check_event(MappingEndEvent):
frigate  | 2023-04-28 16:16:58.030223991    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
frigate  | 2023-04-28 16:16:58.030225509      self.current_event = self.state()
frigate  | 2023-04-28 16:16:58.030227408    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
frigate  | 2023-04-28 16:16:58.030245611      raise ParserError("while parsing a block mapping", self.marks[-1],
frigate  | 2023-04-28 16:16:58.030247924  yaml.parser.ParserError: while parsing a block mapping
frigate  | 2023-04-28 16:16:58.030250017    in "<unicode string>", line 5, column 3:
frigate  | 2023-04-28 16:16:58.030251873        name_of_your_camera: frontcam #  ...
frigate  | 2023-04-28 16:16:58.030253590        ^
frigate  | 2023-04-28 16:16:58.030256169  expected <block end>, but found '<block mapping start>'
frigate  | 2023-04-28 16:16:58.030257605    in "<unicode string>", line 6, column 5:
frigate  | 2023-04-28 16:16:58.030258928          ffmpeg:
frigate  | 2023-04-28 16:16:58.030260494          ^
frigate  | 2023-04-28 16:16:58.030261971
frigate  | 2023-04-28 16:16:58.030264142  *************************************************************
frigate  | 2023-04-28 16:16:58.030266151  ***    End Config Validation Errors                       ***
frigate  | 2023-04-28 16:16:58.030296876  *************************************************************
frigate  | 2023-04-28 16:16:58.554248934  [INFO] Preparing go2rtc config...
frigate  | Traceback (most recent call last):
frigate  |   File "/usr/local/go2rtc/create_config.py", line 27, in <module>
frigate  |     config: dict[str, any] = yaml.safe_load(raw_config)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
frigate  |     return load(stream, SafeLoader)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
frigate  |     return loader.get_single_data()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
frigate  |     node = self.get_single_node()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
frigate  |     document = self.compose_document()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
frigate  |     node = self.compose_node(None, None)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
frigate  |     item_value = self.compose_node(node, item_key)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
frigate  |     node = self.compose_mapping_node(anchor)
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
frigate  |     while not self.check_event(MappingEndEvent):
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
frigate  |     self.current_event = self.state()
frigate  |   File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
frigate  |     raise ParserError("while parsing a block mapping", self.marks[-1],
frigate  | yaml.parser.ParserError: while parsing a block mapping
frigate  |   in "<unicode string>", line 5, column 3:
frigate  |       name_of_your_camera: frontcam #  ...
frigate  |       ^
frigate  | expected <block end>, but found '<block mapping start>'
frigate  |   in "<unicode string>", line 6, column 5:
frigate  |         ffmpeg:
frigate  |         ^
frigate  | 2023-04-28 16:16:58.857912878  [INFO] The go2rtc service exited with code 1 (by signal 0)
frigate  | 2023-04-28 16:16:59.140676100  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-04-28 16:16:59.150143542  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2023-04-28 16:16:59.299306099  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
frigate exited with code 0
```

### FFprobe output from your camera

```shell
yeah I haven't set this up yet. Not really sure what it is.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Galayou G6

**Comment by NickM-27** [comment]
to name a camera you replace `name_of_your_camera` with the name, you don't add it to the end

**Comment by gradation0746** [comment]
> to name a camera you replace `name_of_your_camera` with the name, you don't add it to the end

lol thanks.
