### ISSUE TITLE
[Detector Support]: Coral not found 

### ISSUE THREAD

**Issue by serot23** [blakeblackshear/frigate#6317]
### Describe the problem you are having

Tpu not detected, i have the coral dual edge tpu and the B + M key version. I want to use them in my thinclient HP t620 quad core version. I have a m.2 slot and an mini pcie slot. But the mini pcie i can't find any specs of. So i later bought the bm key version and put that in the m.2 slot, and my ssd in an usb adapter on the motherboard. I am really a noob and tried it but i can't figure it out. I appreciate your hard work and would be happy if you can help me. I have a HA OS x86-64 generic installed and docker is something for later if i understand things better.

### Version

Current version: 0.12.0

### Frigate config file

```yaml
mqtt:
  host: xxxxxxxx
  user: xxxxxxx
  password: xxxxxxxxx

birdseye:
  enabled: False

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - info
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - +genpts+discardcorrupt
    - -rtsp_transport
    - tcp
    - -timeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
    
cameras:
  Voordeur:
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxx/live/ch00_1
          roles: 
            - detect
        - path: rtsp://xxxxxxxxx/live/ch00_0
          roles: 
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
        track:
            - person
    snapshots:
      enabled: True
      bounding_box: True
      retain:
        default: 5
    record:
      enabled: True
      retain:
        days: 7
    rtmp:
      enabled: False
      
detectors:
 coral1:
  type: edgetpu
  device: pci:0
```

### docker-compose file or Docker CLI command

```yaml
X
```

### Relevant log output

```shell
2023-04-29 07:16:07.786929375 [INFO] Got IP address from supervisor: xxxxxx 2023-04-29 07:16:07.905023133 [INFO] Got WebRTC port from supervisor: 8555 2023-04-29 07:16:08.701647433 [INFO] Starting go2rtc... 2023-04-29 07:16:08.921180245 09:16:08.921 INF go2rtc version 1.2.0 linux/amd64 2023-04-29 07:16:08.922664398 09:16:08.922 INF [api] listen addr=:1984 2023-04-29 07:16:08.924133040 09:16:08.923 INF [rtsp] listen addr=:8554 2023-04-29 07:16:08.925422120 09:16:08.925 INF [srtp] listen addr=:8443 2023-04-29 07:16:08.926620933 09:16:08.926 INF [webrtc] listen addr=:8555 2023-04-29 07:16:10.356768531 2023/04/29 09:16:10 [error] 138#138: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "ccab4aaf-frigate:5000" 2023-04-29 07:16:10.356921007 172.30.32.1 - - [29/Apr/2023:09:16:10 +0200] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.4.6 aiohttp/3.8.4 Python/3.10" "-" 2023-04-29 07:16:12.642785062 [2023-04-29 09:16:12] frigate.app INFO : Starting Frigate (0.12.0-da3e197) 2023-04-29 07:16:12.709207953 [2023-04-29 09:16:12] frigate.app INFO : Creating directory: /tmp/cache 2023-04-29 07:16:12.716940548 [2023-04-29 09:16:12] peewee_migrate INFO : Starting migrations 2023-04-29 07:16:12.733340359 [2023-04-29 09:16:12] peewee_migrate INFO : There is nothing to migrate 2023-04-29 07:16:12.778863146 [2023-04-29 09:16:12] detector.coral1 INFO : Starting detection process: 300 2023-04-29 07:16:12.788411221 [2023-04-29 09:16:12] frigate.detectors.plugins.edgetpu_tfl INFO : Attempting to load TPU as pci:0 2023-04-29 07:16:12.799072760 [2023-04-29 09:16:12] frigate.app INFO : Output process started: 302 2023-04-29 07:16:12.800486541 [2023-04-29 09:16:12] frigate.detectors.plugins.edgetpu_tfl ERROR : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors. 2023-04-29 07:16:12.800501286 Process detector:coral1: 2023-04-29 07:16:12.804082656 Traceback (most recent call last): 2023-04-29 07:16:12.804263520 File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate 2023-04-29 07:16:12.804268799 delegate = Delegate(library, options) 2023-04-29 07:16:12.804340953 File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__ 2023-04-29 07:16:12.804345743 raise ValueError(capture.message) 2023-04-29 07:16:12.804498354 ValueError 2023-04-29 07:16:12.804644100 2023-04-29 07:16:12.804649539 During handling of the above exception, another exception occurred: 2023-04-29 07:16:12.804651919 2023-04-29 07:16:12.804760925 Traceback (most recent call last): 2023-04-29 07:16:12.804950855 File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap 2023-04-29 07:16:12.804954968 self.run() 2023-04-29 07:16:12.805060253 File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run 2023-04-29 07:16:12.805065101 self._target(*self._args, **self._kwargs) 2023-04-29 07:16:12.805167599 File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector 2023-04-29 07:16:12.805172599 object_detector = LocalObjectDetector(detector_config=detector_config) 2023-04-29 07:16:12.805276526 File "/opt/frigate/frigate/object_detection.py", line 52, in __init__ 2023-04-29 07:16:12.805281354 self.detect_api = create_detector(detector_config) 2023-04-29 07:16:12.805389627 File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector 2023-04-29 07:16:12.805393968 return api(detector_config) 2023-04-29 07:16:12.805498761 File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__ 2023-04-29 07:16:12.805504122 edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config) 2023-04-29 07:16:12.805631973 File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate 2023-04-29 07:16:12.805637082 raise ValueError('Failed to load delegate from {}\n{}'.format( 2023-04-29 07:16:12.805786010 ValueError: Failed to load delegate from libedgetpu.so.1.0 2023-04-29 07:16:12.805789853 2023-04-29 07:16:12.819170713 [2023-04-29 09:16:12] frigate.app INFO : Camera processor started for Voordeur: 307 2023-04-29 07:16:12.834329739 [2023-04-29 09:16:12] frigate.app INFO : Capture process started for Voordeur: 309 2023-04-29 07:16:17.684443325 [INFO] Starting go2rtc healthcheck service... 2023-04-29 07:16:18.655067375 172.30.32.1 - - [29/Apr/2023:09:16:18 +0200] "GET /api/stats HTTP/1.1" 200 2094 "-" "HomeAssistant/2023.4.6 aiohttp/3.8.4 Python/3.10" "-" 2023-04-29 07:16:26.655198999 172.30.32.1 - - [29/Apr/2023:09:16:26 +0200] "GET /api/stats HTTP/1.1" 200 2069 "-" "HomeAssistant/2023.4.6 aiohttp/3.8.4 Python/3.10" "-" 2023-04-29 07:16:33.121255203 [2023-04-29 09:16:33] frigate.watchdog INFO : Detection appears to have stopped. Exiting Frigate... s6-rc: info: service legacy-services: stopping s6-rc: info: service legacy-services successfully stopped s6-rc: info: service nginx: stopping s6-rc: info: service go2rtc-healthcheck: stopping 2023-04-29 07:16:33.154379836 [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15) s6-rc: info: service go2rtc-healthcheck successfully stopped 2023-04-29 07:16:33.183494904 [INFO] Service NGINX exited with code 0 (by signal 0) s6-rc: info: service nginx successfully stopped s6-rc: info: service nginx-log: stopping s6-rc: info: service frigate: stopping 2023-04-29 07:16:33.189852995 [2023-04-29 09:16:33] frigate.app INFO : Stopping... s6-rc: info: service nginx-log successfully stopped 2023-04-29 07:16:33.194309734 [2023-04-29 09:16:33] frigate.record INFO : Exiting recording maintenance... 2023-04-29 07:16:33.194879553 [2023-04-29 09:16:33] frigate.events INFO : Exiting event cleanup... 2023-04-29 07:16:33.196933110 [2023-04-29 09:16:33] frigate.watchdog INFO : Exiting watchdog... 2023-04-29 07:16:33.199391159 [2023-04-29 09:16:33] frigate.stats INFO : Exiting stats emitter... 2023-04-29 07:16:33.199783618 [2023-04-29 09:16:33] frigate.storage INFO : Exiting storage maintainer... 2023-04-29 07:16:33.200390310 [2023-04-29 09:16:33] frigate.record INFO : Exiting recording cleanup... 2023-04-29 07:16:33.200812683 [2023-04-29 09:16:33] frigate.object_processing INFO : Exiting object processor... 2023-04-29 07:16:33.271195665 [2023-04-29 09:16:33] frigate.comms.ws INFO : Exiting websocket client... 2023-04-29 07:16:34.149780688 [2023-04-29 09:16:34] frigate.events INFO : Exiting event processor... 2023-04-29 07:16:34.150162348 [2023-04-29 09:16:34] peewee.sqliteq INFO : writer received shutdown request, exiting. 2023-04-29 07:16:34.155182827 [2023-04-29 09:16:34] watchdog.Voordeur INFO : Terminating the existing ffmpeg process... 2023-04-29 07:16:34.155429054 [2023-04-29 09:16:34] watchdog.Voordeur INFO : Waiting for ffmpeg to exit gracefully... 2023-04-29 07:16:34.268762070 [2023-04-29 09:16:34] watchdog.Voordeur INFO : Terminating the existing ffmpeg process... 2023-04-29 07:16:34.269194598 [2023-04-29 09:16:34] watchdog.Voordeur INFO : Waiting for ffmpeg to exit gracefully... 2023-04-29 07:16:34.383259915 [2023-04-29 09:16:34] frigate.output INFO : exiting output process... 2023-04-29 07:16:38.813145630 /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked shared_memory objects to clean up at shutdown 2023-04-29 07:16:38.813157775 warnings.warn('resource_tracker: There appear to be %d ' 2023-04-29 07:16:38.823241224 [INFO] Service Frigate exited with code 0 (by signal 0) s6-rc: info: service frigate successfully stopped s6-rc: info: service go2rtc: stopping s6-rc: info: service frigate-log: stopping 2023-04-29 07:16:38.831229303 exit OK s6-rc: info: service frigate-log successfully stopped 2023-04-29 07:16:38.848768221 [INFO] The go2rtc service exited with code 0 (by signal 0) s6-rc: info: service go2rtc successfully stopped s6-rc: info: service go2rtc-log: stopping s6-rc: info: service go2rtc-log successfully stopped s6-rc: info: service log-prepare: stopping s6-rc: info: service s6rc-fdholder: stopping s6-rc: info: service log-prepare successfully stopped s6-rc: info: service legacy-cont-init: stopping s6-rc: info: service s6rc-fdholder successfully stopped s6-rc: info: service legacy-cont-init successfully stopped s6-rc: info: service fix-attrs: stopping s6-rc: info: service fix-attrs successfully stopped s6-rc: info: service s6rc-oneshot-runner: stopping s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

**Comment by NickM-27** [comment]
please repaste your logs as they are shown, right now they are a single line and unreadable.

Which addon are you running? if not already, you should try running the full access addon with protection mode disabled

**Comment by blakeblackshear** [comment]
Not all m.2 slots support PCIe devices. Some are sata only.
