### ISSUE TITLE
[Config Support]: can't adjust segment_time greater than 60 (version 0.12.0)

### ISSUE THREAD

**Issue by doctorttt** [blakeblackshear/frigate#6335]
### Describe the problem you are having

Hi, I'm relatively new to Frigate but I have spent a lot of time researching on this. In some older posts, I thought Frigate is now capable of setting `segment_time` greater than 60. However, when I tried to set it to, for example, 600 (10 mins), the log is telling me that the value must be 60 or less. Am I missing something? I'm using 0.12.0-da3e197. My sample config file is pasted below. 

I understand the project's rationale of `segment_time` between 10 and 60, but I need to have the ability to merge, for example, 10-min, 20-min, or 30-min recordings into a single file. I did some research on this and came across something like using api or ffmpeg to merge files? I have no idea what it means. Please help.

I'm running frigate on TrueNAS Scale, which is a k3s platform. I manually installed the docker image and Frigate works. I'm a the point of fine tuning, just some additional information - that's all. 

### Version

0.12.0-da3e197

### Frigate config file

```yaml
ui:
  use_experimental: false
  live_mode: mse

mqtt:
  enabled: false
  host: 192.168.1.100
  topic_prefix: frigate
  client_id: frigate
  port: 1883
  user: user
  password: password
  stats_interval: 30

detectors:
  cpu1:
    type: cpu
    number_threads: 4

ffmpeg:
  global_args: -hide_banner
  hwaccel_args: preset-intel-qsv-h264
  input_args: preset-rtsp-restream
  output_args: 
    record: -f segment -segment_time 600 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    detect: -f rawvideo -pix_fmt yuv420p -an

objects:
 track:
   - person
   - car

birdseye:
  enabled: false

rtmp:
  enabled: false

detect:
  enabled: false
  width: 1280
  height: 720
  fps: 15

record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 5
      mode: motion
    pre_capture: 5
    post_capture: 15  


go2rtc:
  streams:
    3rdfloor: 
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.104:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:3rdfloor#video=h264"
    3rdfloor_sub: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.104:554/cam/realmonitor?channel=1&subtype=1
    2ndfloor: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.105:554/cam/realmonitor?channel=1&subtype=0
    2ndfloor_sub: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.1.105:554/cam/realmonitor?channel=1&subtype=1

cameras:
    3rdfloor:
      ffmpeg:
        inputs:
          # High resolution stream
          - path: rtsp://127.0.0.1:8554/3rdfloor
            roles:
              - record    
          # Low resolution stream
          - path: rtsp://127.0.0.1:8554/3rdfloor_sub
            roles:
              - detect

      record:
        enabled: true

    2ndfloor:
      ffmpeg:
        inputs:
          # High resolution stream
          - path: rtsp://127.0.0.1:8554/2ndfloor
            roles:
              - record
          # Low resolution stream
          - path: rtsp://127.0.0.1:8554/2ndfloor_sub
            roles:
              - detect

      record:
        enabled: false
```

### Relevant log output

```shell
2023-05-01 02:57:15.479596+00:00s6-rc: info: service s6rc-fdholder: starting
2023-05-01 02:57:15.479675+00:00s6-rc: info: service s6rc-oneshot-runner: starting
2023-05-01 02:57:15.480440+00:00s6-rc: info: service s6rc-oneshot-runner successfully started
2023-05-01 02:57:15.480465+00:00s6-rc: info: service fix-attrs: starting
2023-05-01 02:57:15.480630+00:00s6-rc: info: service s6rc-fdholder successfully started
2023-05-01 02:57:15.481649+00:00s6-rc: info: service fix-attrs successfully started
2023-05-01 02:57:15.481670+00:00s6-rc: info: service legacy-cont-init: starting
2023-05-01 02:57:15.482797+00:00s6-rc: info: service legacy-cont-init successfully started
2023-05-01 02:57:15.482820+00:00s6-rc: info: service log-prepare: starting
2023-05-01 02:57:15.484991+00:00s6-rc: info: service log-prepare successfully started
2023-05-01 02:57:15.485021+00:00s6-rc: info: service nginx-log: starting
2023-05-01 02:57:15.485053+00:00s6-rc: info: service go2rtc-log: starting
2023-05-01 02:57:15.485088+00:00s6-rc: info: service frigate-log: starting
2023-05-01 02:57:15.485509+00:00s6-rc: info: service nginx-log successfully started
2023-05-01 02:57:15.485564+00:00s6-rc: info: service go2rtc-log successfully started
2023-05-01 02:57:15.485631+00:00s6-rc: info: service go2rtc: starting
2023-05-01 02:57:15.485696+00:00s6-rc: info: service frigate-log successfully started
2023-05-01 02:57:15.486057+00:00s6-rc: info: service go2rtc successfully started
2023-05-01 02:57:15.486096+00:00s6-rc: info: service go2rtc-healthcheck: starting
2023-05-01 02:57:15.486120+00:00s6-rc: info: service frigate: starting
2023-05-01 02:57:15.486649+00:00s6-rc: info: service frigate successfully started
2023-05-01 02:57:15.486669+00:00s6-rc: info: service nginx: starting
2023-05-01 02:57:15.486723+00:00s6-rc: info: service go2rtc-healthcheck successfully started
2023-05-01 02:57:15.487366+00:00s6-rc: info: service nginx successfully started
2023-05-01 02:57:15.487402+00:00s6-rc: info: service legacy-services: starting
2023-05-01 02:57:15.487503+00:002023-05-01 02:57:15.487447842  [INFO] Preparing go2rtc config...
2023-05-01 02:57:15.488087+00:002023-05-01 02:57:15.488057160  [INFO] Starting Frigate...
2023-05-01 02:57:15.488394+00:002023-05-01 02:57:15.488366919  [INFO] Starting NGINX...
2023-05-01 02:57:15.489350+00:00s6-rc: info: service legacy-services successfully started
2023-05-01 02:57:15.588242+00:002023-05-01 02:57:15.588069761  [INFO] Starting go2rtc...
2023-05-01 02:57:15.646906+00:002023-05-01 02:57:15.646818861  02:57:15.646 INF go2rtc version 1.2.0 linux/amd64
2023-05-01 02:57:15.646936+00:002023-05-01 02:57:15.646822668  02:57:15.646 INF [api] listen addr=:1984
2023-05-01 02:57:15.646939+00:002023-05-01 02:57:15.646824501  02:57:15.646 INF [rtsp] listen addr=:8554
2023-05-01 02:57:15.646945+00:002023-05-01 02:57:15.646825852  02:57:15.646 INF [srtp] listen addr=:8443
2023-05-01 02:57:15.646955+00:002023-05-01 02:57:15.646827376  02:57:15.646 INF [webrtc] listen addr=:8555
2023-05-01 02:57:16.041711+00:002023-05-01 02:57:16.041612003  [2023-05-01 02:57:16] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-01 02:57:16.048771+00:002023-05-01 02:57:16.048676286  *************************************************************
2023-05-01 02:57:16.048794+00:002023-05-01 02:57:16.048678495  *************************************************************
2023-05-01 02:57:16.048797+00:002023-05-01 02:57:16.048680694  ***    Your config file is not valid!                     ***
2023-05-01 02:57:16.048800+00:002023-05-01 02:57:16.048681802  ***    Please check the docs at                           ***
2023-05-01 02:57:16.048805+00:002023-05-01 02:57:16.048682371  ***    https://docs.frigate.video/configuration/index     ***
2023-05-01 02:57:16.048807+00:002023-05-01 02:57:16.048688369  *************************************************************
2023-05-01 02:57:16.048809+00:002023-05-01 02:57:16.048688899  *************************************************************
2023-05-01 02:57:16.048812+00:002023-05-01 02:57:16.048689677  ***    Config Validation Errors                           ***
2023-05-01 02:57:16.048814+00:002023-05-01 02:57:16.048694289  *************************************************************
2023-05-01 02:57:16.048816+00:002023-05-01 02:57:16.048694811  Camera 3rdfloor has invalid segment_time output arg, segment_time must be 60 or less.
2023-05-01 02:57:16.049092+00:002023-05-01 02:57:16.048932602  Traceback (most recent call last):
2023-05-01 02:57:16.049107+00:002023-05-01 02:57:16.048933166    File "/opt/frigate/frigate/app.py", line 351, in start
2023-05-01 02:57:16.049111+00:002023-05-01 02:57:16.048933664      self.init_config()
2023-05-01 02:57:16.049113+00:002023-05-01 02:57:16.048934178    File "/opt/frigate/frigate/app.py", line 81, in init_config
2023-05-01 02:57:16.049121+00:002023-05-01 02:57:16.048934629      self.config = user_config.runtime_config
2023-05-01 02:57:16.049123+00:002023-05-01 02:57:16.048935123    File "/opt/frigate/frigate/config.py", line 1006, in runtime_config
2023-05-01 02:57:16.049125+00:002023-05-01 02:57:16.048935597      verify_recording_segments_setup_with_reasonable_time(camera_config)
2023-05-01 02:57:16.049130+00:002023-05-01 02:57:16.048936143    File "/opt/frigate/frigate/config.py", line 835, in verify_recording_segments_setup_with_reasonable_time
2023-05-01 02:57:16.049133+00:002023-05-01 02:57:16.048936627      raise ValueError(
2023-05-01 02:57:16.049135+00:002023-05-01 02:57:16.048937160  ValueError: Camera 3rdfloor has invalid segment_time output arg, segment_time must be 60 or less.
2023-05-01 02:57:16.049139+00:002023-05-01 02:57:16.048943422  
2023-05-01 02:57:16.049142+00:002023-05-01 02:57:16.048945604  *************************************************************
2023-05-01 02:57:16.049144+00:002023-05-01 02:57:16.048946106  ***    End Config Validation Errors                       ***
2023-05-01 02:57:16.049149+00:002023-05-01 02:57:16.048946615  *************************************************************
2023-05-01 02:57:17.120551+00:002023-05-01 02:57:17.120459283  [INFO] Service Frigate exited with code 1 (by signal 0)
2023-05-01 02:57:17.121542+00:00s6-rc: info: service legacy-services: stopping
2023-05-01 02:57:17.122590+00:00s6-rc: info: service legacy-services successfully stopped
2023-05-01 02:57:17.122725+00:00s6-rc: info: service nginx: stopping
2023-05-01 02:57:17.122829+00:00s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-01 02:57:17.125837+00:002023-05-01 02:57:17.125762891  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2023-05-01 02:57:17.126074+00:00s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-01 02:57:17.225071+00:002023-05-01 02:57:17.224892362  [INFO] Service NGINX exited with code 0 (by signal 0)
2023-05-01 02:57:17.226629+00:00s6-rc: info: service nginx successfully stopped
2023-05-01 02:57:17.226921+00:00s6-rc: info: service nginx-log: stopping
2023-05-01 02:57:17.227223+00:00s6-rc: info: service frigate: stopping
2023-05-01 02:57:17.229107+00:00s6-rc: info: service frigate successfully stopped
2023-05-01 02:57:17.229284+00:00s6-rc: info: service go2rtc: stopping
2023-05-01 02:57:17.229477+00:00s6-rc: info: service frigate-log: stopping
2023-05-01 02:57:17.230503+00:00s6-rc: info: service nginx-log successfully stopped
2023-05-01 02:57:17.231024+00:002023-05-01 02:57:17.230945826  exit OK
2023-05-01 02:57:17.232727+00:00s6-rc: info: service frigate-log successfully stopped
2023-05-01 02:57:17.238430+00:002023-05-01 02:57:17.238353553  [INFO] The go2rtc service exited with code 0 (by signal 0)
2023-05-01 02:57:17.239331+00:00s6-rc: info: service go2rtc successfully stopped
2023-05-01 02:57:17.239578+00:00s6-rc: info: service go2rtc-log: stopping
2023-05-01 02:57:17.242648+00:00s6-rc: info: service go2rtc-log successfully stopped
2023-05-01 02:57:17.242788+00:00s6-rc: info: service log-prepare: stopping
2023-05-01 02:57:17.242939+00:00s6-rc: info: service s6rc-fdholder: stopping
2023-05-01 02:57:17.244906+00:00s6-rc: info: service log-prepare successfully stopped
2023-05-01 02:57:17.245031+00:00s6-rc: info: service legacy-cont-init: stopping
2023-05-01 02:57:17.246025+00:00s6-rc: info: service s6rc-fdholder successfully stopped
2023-05-01 02:57:17.253962+00:00s6-rc: info: service legacy-cont-init successfully stopped
2023-05-01 02:57:17.254154+00:00s6-rc: info: service fix-attrs: stopping
2023-05-01 02:57:17.256015+00:00s6-rc: info: service fix-attrs successfully stopped
2023-05-01 02:57:17.256178+00:00s6-rc: info: service s6rc-oneshot-runner: stopping
2023-05-01 02:57:17.259065+00:00s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by blakeblackshear** [comment]
Frigate's recording files are a part of it's internal database and cannot be longer than 60s.

Perhaps if you describe your use case for why you need to combine files we can help.

**Comment by doctorttt** [comment]
Thanks Blake. Here is the background. I'm coming from Synology's surveillance station and I'm moving away from using Synology's off-the-shelf hardware and building an open source custom hardware NAS. This is why I'm looking for a replacement of surveillance station. 

Over the past couple years, there were a few incidents in my neighborhood where law enforcement requested my assistance because I had several cameras pointing towards the street and recording footages. Police officers asked whether my cameras captured the incident and they did, so I copied the recording to a USB thumb drive to help them out. The footage was like 10 mins and it was a single mp4 file and the officers only had to work with one file. 

So, this is they reason why I'm trying to see if Frigate has the capability to merge several 1-min footages for this kind of event to help out the neighborhood when needed. I was on Home Assistant discord today and Nick told me some options. One of which is using ffmpeg in shell and merge the files. I'm going to look into it.

**Comment by frankrbrts622** [comment]
Have same issue. Was forced(?) to upgrade to Version 0.12. Configuration was set at segment_time at 600 with Version 0.11 and it worked fine for my purposes. I was using recording 24/7 and was able to easily find and download what I needed to monitor. Limit of segment_time to 60 will now have to look through 30 files for 30 minutes instead of 3. Is there anyway around this to make larger segment_time. If not - is there way to rollback to Ver 0.11 which worked great? Otherwise, is there a simple guide to putting segments together (combine) - I saw something about using api(?)

**Comment by NickM-27** [comment]
There are many solutions discussed in https://github.com/blakeblackshear/frigate/issues/2369 and it's as simple as `ffmpeg -i http://frigate_ip:5000/vod/${YMDH1}/${camarray[$i]}/master.m3u8 -c copy ${OUTDIR}/${camarray[$i]}-${YMDH2}.mp4 `

**Comment by frankrbrts622** [comment]
Thanks NickM-27 very much for quick reply. I have installed Frigate 0.12 in Home Assistant via the Add-On and also have the integration installed. I have no issue accessing via HA - Frigate, see all events, etc. I also can see the clips (1 min) via Samba through the HA IP Address\media\frigate. What I can't seem to do is access Frigate from outside of HA interface with any combination of URLs. From HA the URL to interface is: http://192.168.1.xx:8123/ccab4aaf_frigate/dashboard

**Comment by NickM-27** [comment]
you must enable the port 5000 in addon config settings

**Comment by frankrbrts622** [comment]
Eternal Gratitude NickM-27! Enabled the port 5000 in settings, and now I'm able to use KennyStier bash script with my config. Just tested and works great.
