### ISSUE TITLE
[Support]: Frigate crashes when tensor is enabled

### ISSUE THREAD

**Issue by tiny-e** [blakeblackshear/frigate#6357]
### Describe the problem you are having

Seems to crash every 20 seconds or so when I have tensorrt GPU detection enabled-  If I comment out the tensor stuff and just let the edgeTPU do its thing, no issues (other than higher CPU usage).  But when running tensor I get crashes every N seconds.  Video stops (see link) and any terminal windows (like SSH connections, dropping into a console in the container, etc.) also close. 

GPU is an NVIDIA Quadro M2000

https://www.dropbox.com/s/dnbgmn1ghwhlxvt/Flashback%20-%20May%202%2C%202023%2017%2030%2031%20Copy%281%29.m4v?dl=0

`detectors: 
  coral:
    type: edgetpu
    device: usb
  #tensorrt:
    #type: tensorrt
    #device: 0
    
#model: 
    #path: /trt-models/yolov7-tiny-416.trt
    #input_tensor: nchw
    #input_pixel_format: rgb
    #width: 416
    #height: 416`

### Version

Frigate (0.12.0-da3e197)

### Frigate config file

```yaml
mqtt:
  host: 192.168.11.5
  port: 1883
  user: homeassistant
  password: xxxxxxxxxxxxxxxxx
cameras:

  1_backyard_west:
    ffmpeg:
        inputs:
          - path: rtsp://admin:XXXXX@192.168.11.141:554/h264Preview_01_main
            roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    objects:
      track:
        - person
        - car 
        - dog
        - cat        
  2_backyard_east:
    ffmpeg:
        inputs:
          - path: rtsp://admin:XXXXXX@192.168.11.141:554/h264Preview_02_main
            roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    objects:
      track:
        - person
        - car 
        - dog
        - cat        
  3_driveway_cam:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://dave:XXXXXX@192.168.11.140:554/stream0
          roles: 
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    objects:
      track:
        - person
        - car 
        - dog
        - cat


detectors: 
  coral:
    type: edgetpu
    device: usb
  tensorrt:
    type: tensorrt
    device: 0
    
model: 
    path: /trt-models/yolov7-tiny-416.trt
    input_tensor: nchw
    input_pixel_format: rgb
    width: 416
    height: 416
```

### Relevant log output

```shell
text  error  warn  system  array  login  

s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-05-02 17:48:45.568589149  [INFO] Preparing go2rtc config...
2023-05-02 17:48:45.572267969  [INFO] Starting Frigate...
2023-05-02 17:48:45.573241807  [INFO] Starting NGINX...
2023-05-02 17:48:45.770036131  [INFO] Starting go2rtc...
2023-05-02 17:48:45.887181182  17:48:45.887 INF go2rtc version 1.2.0 linux/amd64
2023-05-02 17:48:45.887489658  17:48:45.887 INF [api] listen addr=:1984
2023-05-02 17:48:45.887617064  17:48:45.887 INF [rtsp] listen addr=:8554
2023-05-02 17:48:45.887809503  17:48:45.887 INF [srtp] listen addr=:8443
2023-05-02 17:48:45.888048782  17:48:45.888 INF [webrtc] listen addr=:8555
2023-05-02 17:48:46.075157649  2023/05/02 17:48:46 [error] 134#134: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.11.5, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.11.10:5000"
2023-05-02 17:48:46.075162200  192.168.11.5 - - [02/May/2023:17:48:46 -0500] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.4.6 aiohttp/3.8.4 Python/3.10" "-"
2023-05-02 17:48:46.621117271  [2023-05-02 17:48:46] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-02 17:48:46.652498291  [2023-05-02 17:48:46] peewee_migrate                 INFO    : Starting migrations
2023-05-02 17:48:46.657184357  [2023-05-02 17:48:46] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-02 17:48:46.698486218  [2023-05-02 17:48:46] frigate.app                    INFO    : Output process started: 293
2023-05-02 17:48:46.717732976  [2023-05-02 17:48:46] frigate.app                    INFO    : Camera processor started for 1_backyard_west: 299
2023-05-02 17:48:46.725807782  [2023-05-02 17:48:46] frigate.app                    INFO    : Camera processor started for 2_backyard_east: 303
2023-05-02 17:48:46.734029264  [2023-05-02 17:48:46] frigate.app                    INFO    : Camera processor started for 3_driveway_cam: 304
2023-05-02 17:48:46.748230174  [2023-05-02 17:48:46] frigate.app                    INFO    : Capture process started for 1_backyard_west: 306
2023-05-02 17:48:46.758042387  [2023-05-02 17:48:46] frigate.app                    INFO    : Capture process started for 2_backyard_east: 307
2023-05-02 17:48:46.766708382  [2023-05-02 17:48:46] frigate.app                    INFO    : Capture process started for 3_driveway_cam: 309
2023-05-02 17:48:46.802299167  [2023-05-02 17:48:46] detector.tensorrt              INFO    : Starting detection process: 291
2023-05-02 17:48:47.185380998  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +187, GPU +0, now: CPU 239, GPU 102 (MiB)
2023-05-02 17:48:47.209606579  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 35 MiB
2023-05-02 17:48:47.561093098  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +181, GPU +70, now: CPU 483, GPU 208 (MiB)
2023-05-02 17:48:47.739826078  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +110, GPU +46, now: CPU 593, GPU 254 (MiB)
2023-05-02 17:48:47.743685605  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +34, now: CPU 0, GPU 34 (MiB)
2023-05-02 17:48:47.757176081  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 558, GPU 246 (MiB)
2023-05-02 17:48:47.760533361  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 558, GPU 254 (MiB)
2023-05-02 17:48:47.760700888  [2023-05-02 17:48:47] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +13, now: CPU 0, GPU 47 (MiB)
2023-05-02 17:48:49.861971304  [2023-05-02 17:48:46] detector.coral                 INFO    : Starting detection process: 289
2023-05-02 17:48:49.874550362  [2023-05-02 17:48:46] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-02 17:48:49.874553987  [2023-05-02 17:48:49] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-02 17:48:49.877830435  [2023-05-02 17:48:49] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-05-02 17:48:49.881303548  Process detector:coral:
2023-05-02 17:48:49.882472051  Traceback (most recent call last):
2023-05-02 17:48:49.882533559    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-05-02 17:48:49.882535303      self.run()
2023-05-02 17:48:49.882556287    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-05-02 17:48:49.882557705      self._target(*self._args, **self._kwargs)
2023-05-02 17:48:49.882574977    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-05-02 17:48:49.882576336      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-05-02 17:48:49.882600159    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-05-02 17:48:49.882601528      self.detect_api = create_detector(detector_config)
2023-05-02 17:48:49.882620815    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-05-02 17:48:49.882622006      return api(detector_config)
2023-05-02 17:48:49.882638441    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 39, in __init__
2023-05-02 17:48:49.882639608      self.interpreter = Interpreter(
2023-05-02 17:48:49.882656648    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
2023-05-02 17:48:49.882657857      _interpreter_wrapper.CreateWrapperFromFile(
2023-05-02 17:48:49.882686034  ValueError: Model provided has model identifier '
2023-05-02 17:48:54.542197203  192.168.11.5 - - [02/May/2023:17:48:54 -0500] "GET /api/stats HTTP/1.1" 200 2812 "-" "HomeAssistant/2023.4.6 aiohttp/3.8.4 Python/3.10" "-"
2023-05-02 17:48:55.571669327  [INFO] Starting go2rtc healthcheck service...
2023-05-02 17:49:02.571225643  192.168.11.5 - - [02/May/2023:17:49:02 -0500] "GET /api/stats HTTP/1.1" 200 2835 "-" "HomeAssistant/2023.4.6 aiohttp/3.8.4 Python/3.10" "-"
2023-05-02 17:49:07.147873063  [2023-05-02 17:49:07] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-02 17:49:07.162873652  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-02 17:49:07.189483738  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-05-02 17:49:07.192177621  [2023-05-02 17:49:07] frigate.app                    INFO    : Stopping...
2023-05-02 17:49:07.192785324  [2023-05-02 17:49:07] detector.tensorrt              INFO    : Signal to exit detection process...
2023-05-02 17:49:07.193020125  [2023-05-02 17:49:07] root                           INFO    : Waiting for detection process to exit gracefully...
2023-05-02 17:49:07.193114290  [2023-05-02 17:49:07] frigate.record                 INFO    : Exiting recording cleanup...
2023-05-02 17:49:07.193760963  [2023-05-02 17:49:07] frigate.storage                INFO    : Exiting storage maintainer...
s6-rc: info: service nginx-log successfully stopped
2023-05-02 17:49:07.194040076  [2023-05-02 17:49:07] frigate.events                 INFO    : Exiting event cleanup...
2023-05-02 17:49:07.194042265  [2023-05-02 17:49:07] frigate.stats                  INFO    : Exiting stats emitter...
2023-05-02 17:49:07.194043627  [2023-05-02 17:49:07] frigate.watchdog               INFO    : Exiting watchdog...
2023-05-02 17:49:07.194047193  [2023-05-02 17:49:07] frigate.record                 INFO    : Exiting recording maintenance...
2023-05-02 17:49:07.224758827  [2023-05-02 17:49:07] frigate.events                 INFO    : Exiting event processor...
2023-05-02 17:49:07.282759097  [2023-05-02 17:49:07] frigate.object_processing      INFO    : Exiting object processor...
2023-05-02 17:49:07.301827052  [2023-05-02 17:49:07] detector.tensorrt              INFO    : Exited detection process...
2023-05-02 17:49:07.437566806  [2023-05-02 17:49:07] root                           INFO    : Detection process has exited...
2023-05-02 17:49:07.681807311  [2023-05-02 17:49:07] frigate.comms.ws               INFO    : Exiting websocket client...
2023-05-02 17:49:07.681955868  [2023-05-02 17:49:07] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-05-02 17:49:07.684442989  [2023-05-02 17:49:07] watchdog.1_backyard_west       INFO    : Terminating the existing ffmpeg process...
2023-05-02 17:49:07.684646908  [2023-05-02 17:49:07] watchdog.1_backyard_west       INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-02 17:49:07.684830784  [2023-05-02 17:49:07] watchdog.3_driveway_cam        INFO    : Terminating the existing ffmpeg process...
2023-05-02 17:49:07.685170436  [2023-05-02 17:49:07] watchdog.2_backyard_east       INFO    : Terminating the existing ffmpeg process...
2023-05-02 17:49:07.685172734  [2023-05-02 17:49:07] watchdog.2_backyard_east       INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-02 17:49:07.685323754  [2023-05-02 17:49:07] watchdog.3_driveway_cam        INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-02 17:49:08.514866688  [2023-05-02 17:49:08] frigate.video                  INFO    : 2_backyard_east: exiting subprocess
2023-05-02 17:49:08.590811354  [2023-05-02 17:49:08] frigate.video                  INFO    : 1_backyard_west: exiting subprocess
2023-05-02 17:49:08.839645091  [2023-05-02 17:49:08] frigate.output                 INFO    : exiting output process...
2023-05-02 17:49:12.722028242  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 12 leaked shared_memory objects to clean up at shutdown
2023-05-02 17:49:12.722031590    warnings.warn('resource_tracker: There appear to be %d '
2023-05-02 17:49:12.728601222  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-05-02 17:49:12.732351966  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-05-02 17:49:12.737566717  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
###Backyard West###
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]

###Backyard East###
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1440,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]

###Driveway Cam###
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"25/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1296,"width":2304},{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"}]}}]
```

### Frigate stats

```json
{"1_backyard_west":{"camera_fps":3.58,"capture_pid":304,"detection_enabled":1,"detection_fps":10.98,"ffmpeg_pid":310,"pid":300,"process_fps":3.53,"skipped_fps":0.0},"2_backyard_east":{"camera_fps":4.19,"capture_pid":308,"detection_enabled":1,"detection_fps":5.91,"ffmpeg_pid":316,"pid":302,"process_fps":4.12,"skipped_fps":0.0},"3_driveway_cam":{"camera_fps":4.13,"capture_pid":311,"detection_enabled":1,"detection_fps":5.55,"ffmpeg_pid":321,"pid":303,"process_fps":4.05,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.1"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"8.3","mem":"0.8"},"118":{"cpu":"0.0","mem":"0.0"},"119":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.0"},"135":{"cpu":"0.0","mem":"0.0"},"136":{"cpu":"0.0","mem":"0.0"},"137":{"cpu":"0.0","mem":"0.0"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"0.4"},"287":{"cpu":"0.0","mem":"0.0"},"288":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.0","mem":"2.1"},"294":{"cpu":"1.0","mem":"0.4"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.3","mem":"0.4"},"301":{"cpu":"0.0","mem":"0.0"},"302":{"cpu":"0.7","mem":"0.4"},"303":{"cpu":"0.3","mem":"0.4"},"304":{"cpu":"1.3","mem":"0.4"},"308":{"cpu":"1.7","mem":"0.4"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"21.9","mem":"0.1"},"311":{"cpu":"1.7","mem":"0.4"},"314":{"cpu":"0.0","mem":"0.0"},"316":{"cpu":"24.3","mem":"0.1"},"319":{"cpu":"0.0","mem":"0.0"},"32":{"cpu":"0.0","mem":"0.0"},"321":{"cpu":"3.0","mem":"0.3"},"323":{"cpu":"0.0","mem":"0.0"},"338":{"cpu":"0.0","mem":"0.0"},"389":{"cpu":"0.0","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"88":{"cpu":"0.0","mem":"0.0"},"98":{"cpu":"0.0","mem":"0.0"},"MiB":{"cpu":"29136.1","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"1"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":22.45,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":288},"tensorrt":{"detection_start":0.0,"inference_speed":14.0,"pid":290}},"gpu_usages":{"Quadro M2000":{"gpu":"1 %","mem":"11.4 %"}},"service":{"last_updated":1683068133,"latest_version":"0.12.0","storage":{"/dev/shm":{"free":260.7,"mount_type":"tmpfs","total":268.4,"used":7.7},"/media/frigate/clips":{"free":3919600.0,"mount_type":"xfs","total":3998833.5,"used":79233.5},"/media/frigate/recordings":{"free":3919600.0,"mount_type":"xfs","total":3998833.5,"used":79233.5},"/tmp/cache":{"free":89.2,"mount_type":"tmpfs","total":100.0,"used":10.8}},"temperatures":{},"uptime":6,"version":"0.12.0-da3e197"}}
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Backyard = Reolink Duo POE, Driveway = SV3C B01POE-1080P-HX

### Any other information that may be helpful

Installed into Unraid via unraid 'app store' section.  Happy to share anything from there (container config, etc) if needed.

**Comment by NickM-27** [comment]
You can't run a coral and tensorrt at the same time, only one detector type at a time is currently supported

**Comment by tiny-e** [comment]
Thanks --

I must of missed that somewhere... I thought it actually was encouraged (but I've been pouring over a lot of docs the last day or so trying to get set up).

**Comment by NickM-27** [comment]
It's encouraged to use a hardware detector AND a hardware accelerated decoder. There are a lot of limitations to running multiple types of detectors that need to be worked through.
