### ISSUE TITLE
[Support]: Frigate install in HAssOS

### ISSUE THREAD

**Issue by ellacer3** [blakeblackshear/frigate#6374]
### Describe the problem you are having

Hi there. I'm having an issue with the instalation of Frigate in HA. I'm pretty new to this so I don't know if I followed the docs correctly. All help is apreciated in advance.

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  enabled: True
  user: user
  passwd: passwd

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.88.108:554 
          roles:
            - detect
    detect:
      enabled: True 
      width: 1280 
      height: 720
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-05-04 11:30:39.949249522  [INFO] Starting Frigate...
2023-05-04 11:30:39.949232003  [INFO] Starting NGINX...
2023-05-04 11:30:39.949233337  [INFO] Preparing go2rtc config...
2023-05-04 11:30:40.421224888  [INFO] Got IP address from supervisor: 192.168.88.246
2023-05-04 11:30:40.566100684  [INFO] Got WebRTC port from supervisor: 8555
2023-05-04 11:30:43.505409606  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-05-04 11:30:43.505899408  Traceback (most recent call last):
2023-05-04 11:30:43.505916926    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-05-04 11:30:43.507654241      return _run_code(code, main_globals, None,
2023-05-04 11:30:43.507721593    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-05-04 11:30:43.508152801      exec(code, run_globals)
2023-05-04 11:30:43.508199709    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-05-04 11:30:43.508575046      from frigate.app import FrigateApp
2023-05-04 11:30:43.508627751    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-05-04 11:30:43.508982514      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-05-04 11:30:43.509031181    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-05-04 11:30:43.509449278      from frigate.config import FrigateConfig
2023-05-04 11:30:43.509488648    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-05-04 11:30:43.509730058      import matplotlib.pyplot as plt
2023-05-04 11:30:43.509775855    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-05-04 11:30:43.511771154      from . import _api, _version, cbook, _docstring, rcsetup
2023-05-04 11:30:43.511787987    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-05-04 11:30:43.514325902      from matplotlib.colors import Colormap, is_color_like
2023-05-04 11:30:43.514343495    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-05-04 11:30:43.516403442      from matplotlib import _api, _cm, cbook, scale
2023-05-04 11:30:43.516422442    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-05-04 11:30:43.518295240      from matplotlib.ticker import (
2023-05-04 11:30:43.518358777    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-05-04 11:30:43.520253093      from matplotlib import transforms as mtransforms
2023-05-04 11:30:43.520268149    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-05-04 11:30:43.522053445      from matplotlib._path import (
2023-05-04 11:30:43.522111612  ImportError: numpy.core.multiarray failed to import
2023-05-04 11:30:43.704151089  [INFO] Starting go2rtc...
2023-05-04 11:30:44.027036913  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-04 11:30:44.096053312  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-04 11:30:44.222396509  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2023-05-04 11:30:44.270960567  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
I don't know where i should run this.
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hyundai    HYU-649

**Comment by NickM-27** [comment]
Looks like you're running HA OS as 32bit OS, this issue happens for some users and the recommendation is to update to a 64bit version of HA OS
