### ISSUE TITLE
[Support]: Broken Pipe Error

### ISSUE THREAD

**Issue by gcortes** [blakeblackshear/frigate#6409]
### Describe the problem you are having

I upgraded to the latest release. I was getting a lot off errors using go2rtc. I've created an issue regarding them on that github site. I then decided to fall back to not using it. After rebooting, I got the error shown below. Frigate appears to be running normally.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 10.0.0.185
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: curt
  password: redacted
#  password: {FRIGATE_MQTT_PASSWORD}
  stats_interval: 60

birdseye:
  enabled: False
  #mode: continuous

detectors:
  # cpu1:
  #   type: cpu
  #   num_threads: 3
  coral:
    # Required: type of the detector
    # Valid values are 'edgetpu' (requires device property below) and 'cpu'.
    type: edgetpu
    # Optional: device name as defined here: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api
    device: usb
    # Optional: num_threads value passed to the tflite.Interpreter (default: shown below)
    # This value is only used for CPU types
    num_threads: 3

#go2rtc:
#  streams:
#    drive_way:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
#    drive_way_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
#    north_yard:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/102
#    north_yard_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/101
#    back_door:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/102
#    back_door_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/101
#    south_yard:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/102
#    south_yard_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/101
#    front_porch:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/102
#    front_porch_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/101
#    back_yard:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/102
#    back_yard_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/101
#    garage:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/102
#    garage_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/101
#    living_room:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/102
#    living_room_sub:
#      - rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/101

cameras:
  drive_way:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/drive_way_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.114:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/drive_way
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
        - car
      filters:
        person:
          mask:
            - 201,242,306,239,418,241,548,241,640,239,640,133,640,0,230,0,0,0,0,62,0,172,69,171,120,183
            - 0,327,0,283,69,278,112,270,143,279,158,311,150,354,106,374,32,425
        car:
          mask:
            - 488,237,547,227,560,262,640,315,640,480,503,480
            - 0,118,0,218,40,415,155,347,296,259,341,212,324,121,497,141,640,135,640,0,0,0            
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - near_driveway
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,365,51,346,21,224,32,184,151,131,228,123,353,114,442,114,545,121,640,121,640,0,0,0
    zones:
      near_driveway:
        coordinates: 138,358,163,327,144,271,206,263,287,292,367,311,496,343,604,480,213,480,50,480,36,406
        objects:
          - person
          - car
    record:
      enabled: True
      retain: 
        days: 0
      events:
        required_zones:
          - near_driveway
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  north_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/north_yard_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.106:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/north_yard
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - north_yard_walk
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 144,0,205,480,0,480,0,0
        - 422,480,338,299,340,258,241,139,215,80,220,0,640,0,640,480
    zones:
      north_yard_walk:
        coordinates: 420,480,338,299,338,253,304,206,270,164,243,127,224,79,213,0,149,0,154,169,210,480
        objects:
          - person
    record:
      enabled: True
      retain: 
        days: 0
      events:
        required_zones:
          - north_yard_walk
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  back_door:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/back_door_sub
#          input_args: preset-rtsp-restream

          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.108:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/back_door
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - back_door_isolation
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,0,402,0,640,0,640,117,515,142,31,235,229,187,67,229,101,480,0,480
    zones:
      back_door_isolation:
        coordinates: 73,456,31,235,345,169,523,150,560,225,559,332,560,436
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  south_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/south_yard_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.111:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/south_yard
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 523,0,640,0,640,117,640,480,532,480,400,480,407,191,525,88
        - 0,0,0,480,113,313,68,169,221,102,386,55,378,0
    zones:
      south_yard_isolation:
        coordinates: 63,480,128,278,111,210,304,139,410,149,406,233,370,332,408,480
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  front_porch:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/front_porch_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.112:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/front_porch
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
      filters:
        person:
          mask:
            - 0,0,188,0,640,0,640,31,524,79,449,97,346,202,188,326,0,457    
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      required_zones:
        - front_porch_walk
      enabled: true
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
         - 0,0,402,0,640,0,640,24,549,10,384,77,408,187,305,225,278,122,116,220,0,299
    zones:
      front_porch_walk:
        coordinates: 414,480,472,376,554,166,619,159,619,322,607,480
        objects:
          - person        
    record:
      enabled: True
      retain: 
        days: 0
      events:
        required_zones:
          - front_porch_walk
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  back_yard:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/back_yard_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.113:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/back_yard
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 77,0,402,0,640,0,640,117,640,274,640,454,640,480,360,480,246,325,182,223,99,96
        - 98,403,56,140,48,0,0,0,0,327,0,480,122,480
    zones:
      back_yard_isolation:
        coordinates: 183,480,74,205,51,114,103,96,195,244,261,338,353,480
    record:
      enabled: True
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/garage_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.103:554/Streaming/Channels/101
 #       - path: rtsp://127.0.0.1:8554/garage
 #         input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: False
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,239,94,188,247,137,538,118,539,0,0,0
    zones:
      garage_isolation:
        coordinates: 198,149,0,233,0,480,542,480,565,345,578,245,589,59
    record:
      enabled: False
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15  
########################################
  living_room:
    ffmpeg:
      inputs:
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/102
#        - path: rtsp://127.0.0.1:8554/living_room_sub
#          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://home_assistant:{FRIGATE_RTSP_PASSWORD}@10.0.0.115:554/Streaming/Channels/101
#        - path: rtsp://127.0.0.1:8554/living_room
#          input_args: preset-rtsp-restream
          roles:
            - record
    detect:
      enabled: False
      width: 640
      height: 480
      fps: 6
    objects:
      track:
        - person
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 175
      quality: 100
    snapshots:
      enabled: false
      timestamp: false
      bounding_box: true
      retain:
        default: 5
    motion:
      mask:
        - 0,144,228,145,220,24,0,22
        - 552,0,552,61,413,63,414,0
    zones:
      living_room_isolation:
        coordinates: 147,480,0,301,228,145,500,97,589,103,559,332,562,480
    record:
      enabled: False
      retain: 
        days: 0
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 5
        post_capture: 15
```

### Relevant log output

```shell
2023-05-06 09:01:03.518157830  [2023-05-06 09:01:03] ws4py                          ERROR   : Error when terminating the connection: [Errno 32] Broken pipe
2023-05-06 09:01:06.851772940  Traceback (most recent call last):
2023-05-06 09:01:06.851829923    File "/usr/lib/python3.9/wsgiref/handlers.py", line 138, in run
2023-05-06 09:01:06.851834740      self.finish_response()
2023-05-06 09:01:06.851839520    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 87, in finish_response
2023-05-06 09:01:06.851848298      self.request_handler.server.link_websocket_to_server(ws)
2023-05-06 09:01:06.851853517    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 129, in link_websocket_to_server
2023-05-06 09:01:06.851858784      self.manager.add(ws)
2023-05-06 09:01:06.851863188    File "/usr/local/lib/python3.9/dist-packages/ws4py/manager.py", line 253, in add
2023-05-06 09:01:06.851895096      logger.info("Managing websocket %s" % format_addresses(websocket))
2023-05-06 09:01:06.851900843    File "/usr/local/lib/python3.9/dist-packages/ws4py/__init__.py", line 61, in format_addresses
2023-05-06 09:01:06.851936016      peer = ws.peer_address
2023-05-06 09:01:06.851975307    File "/usr/local/lib/python3.9/dist-packages/ws4py/websocket.py", line 164, in peer_address
2023-05-06 09:01:06.851979947      self._peer_address = self.sock.getpeername()
2023-05-06 09:01:06.851983986  OSError: [Errno 107] Transport endpoint is not connected
2023-05-06 09:01:06.852145916  ----------------------------------------
2023-05-06 09:01:06.852179782  Exception occurred during processing of request from ('127.0.0.1', 43304)
2023-05-06 09:01:06.853644953  Traceback (most recent call last):
2023-05-06 09:01:06.853652666    File "/usr/lib/python3.9/wsgiref/handlers.py", line 138, in run
2023-05-06 09:01:06.853656113      self.finish_response()
2023-05-06 09:01:06.853660560    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 87, in finish_response
2023-05-06 09:01:06.853665010      self.request_handler.server.link_websocket_to_server(ws)
2023-05-06 09:01:06.853700796    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 129, in link_websocket_to_server
2023-05-06 09:01:06.853705545      self.manager.add(ws)
2023-05-06 09:01:06.853709556    File "/usr/local/lib/python3.9/dist-packages/ws4py/manager.py", line 253, in add
2023-05-06 09:01:06.853713763      logger.info("Managing websocket %s" % format_addresses(websocket))
2023-05-06 09:01:06.853718250    File "/usr/local/lib/python3.9/dist-packages/ws4py/__init__.py", line 61, in format_addresses
2023-05-06 09:01:06.853721756      peer = ws.peer_address
2023-05-06 09:01:06.853726214    File "/usr/local/lib/python3.9/dist-packages/ws4py/websocket.py", line 164, in peer_address
2023-05-06 09:01:06.853730501      self._peer_address = self.sock.getpeername()
2023-05-06 09:01:06.853734781  OSError: [Errno 107] Transport endpoint is not connected
2023-05-06 09:01:06.853737734  
2023-05-06 09:01:06.853741711  During handling of the above exception, another exception occurred:
2023-05-06 09:01:06.853744826  
2023-05-06 09:01:06.853841271  Traceback (most recent call last):
2023-05-06 09:01:06.853846587    File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
2023-05-06 09:01:06.853850243      self.process_request(request, client_address)
2023-05-06 09:01:06.853854152    File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
2023-05-06 09:01:06.853857878      self.finish_request(request, client_address)
2023-05-06 09:01:06.853862160    File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
2023-05-06 09:01:06.853865741      self.RequestHandlerClass(request, client_address, self)
2023-05-06 09:01:06.853870261    File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
2023-05-06 09:01:06.853873450      self.handle()
2023-05-06 09:01:06.853916287    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 105, in handle
2023-05-06 09:01:06.853921155      handler.run(self.server.get_app())
2023-05-06 09:01:06.853925212    File "/usr/lib/python3.9/wsgiref/handlers.py", line 145, in run
2023-05-06 09:01:06.853928322      self.handle_error()
2023-05-06 09:01:06.853933004    File "/usr/lib/python3.9/wsgiref/handlers.py", line 382, in handle_error
2023-05-06 09:01:06.853975829      self.finish_response()
2023-05-06 09:01:06.854010936    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 80, in finish_response
2023-05-06 09:01:06.854015260      SimpleHandler.finish_response(self)
2023-05-06 09:01:06.854019740    File "/usr/lib/python3.9/wsgiref/handlers.py", line 184, in finish_response
2023-05-06 09:01:06.854023251      self.write(data)
2023-05-06 09:01:06.854027275    File "/usr/lib/python3.9/wsgiref/handlers.py", line 288, in write
2023-05-06 09:01:06.854030700      self.send_headers()
2023-05-06 09:01:06.854034691    File "/usr/lib/python3.9/wsgiref/handlers.py", line 345, in send_headers
2023-05-06 09:01:06.854038643      if not self.origin_server or self.client_is_modern():
2023-05-06 09:01:06.854042812    File "/usr/lib/python3.9/wsgiref/handlers.py", line 358, in client_is_modern
2023-05-06 09:01:06.854046859      return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
2023-05-06 09:01:06.854050535  TypeError: 'NoneType' object is not subscriptable
2023-05-06 09:01:06.854053915  ----------------------------------------
```

### FFprobe output from your camera

```shell
I see no mention of a camera in the log so don't know if the problem is camera related. I ran ffprobe on all my cameras. The output was the same for all of them: 

FFPROBE OUTPUT
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 640x480
FPS: 6/1

Stream 1:
Return Code: 0

Video:
```
```


### Frigate stats

```json
Don't know what this is. Is /api/stats to be added to the url?
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision DS-2CD2043G0-I

### Any other information that may be helpful

I have eight cameras, all the same make and model. I'm running on Ubuntu on an Intel Mac Mini. It's a direct boot of Ubuntu, not a VM.

**Comment by NickM-27** [comment]
Does this continue to happen? Seems like a weird webserver error

**Comment by gcortes** [comment]
I haven't seen it or any other error since. I just did a reboot to see if it's a startup issue. It's been about ten minutes and it hasn't reoccured.

**Comment by gcortes** [comment]
I checked the log again this morning. There are no errors so it was just a one off.
