### ISSUE TITLE
0.80: Frigate stops when it doesn't detect a TPU, and does not try to restart

### ISSUE THREAD

**Issue by Ysbrand** [blakeblackshear/frigate#642]
This is a follow up of Issue 381

Environment:
Frigate 0.80
Installed as a HA Add-on.

Frigate now indeed stops when its not able to detect a TPU. This condition still exists in 0.80.

The problem is that it now stops but never starts again. ie I have to start it manually.

```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
frigate.app                    INFO    : Creating tmpfs of size 256m
frigate.app                    WARNING : Camera Voordeur has rtmp enabled, but rtmp is not assigned to an input.
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.app                    INFO    : Camera processor started for Voordeur: 40
frigate.app                    INFO    : Capture process started for Voordeur: 42
detector.coral                 INFO    : Starting detection process: 38
frigate.edgetpu                INFO    : Attempting to load TPU as usb
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55a472ec10] moov atom not found
/media/frigate/recordings/Voordeur-20210128042429.mp4: Invalid data found when processing input
frigate.record                 INFO    : bad file: Voordeur-20210128042429.mp4
Process detector:coral:
frigate.edgetpu                INFO    : No EdgeTPU detected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
frigate.watchdog               INFO    : Detection appears to have stopped. Restarting frigate
frigate.app                    INFO    : Stopping...
frigate.events                 INFO    : Exiting event processor...
frigate.record                 INFO    : Exiting recording maintenance...
frigate.object_processing      INFO    : Exiting object processor...
frigate.events                 INFO    : Exiting event cleanup...
frigate.watchdog               INFO    : Exiting watchdog...
frigate.stats                  INFO    : Exiting watchdog...
root                           INFO    : Waiting for detection process to exit gracefully...
```

**Comment by robsonke** [comment]
See breaking changes, this is by design.

**Comment by Ysbrand** [comment]
Well, it was my understanding that the container was restarted. At least that was what was discussed previously.

**Comment by blakeblackshear** [comment]
How are you running the container?

**Comment by Ysbrand** [comment]
Hi,

I'm running it as a HA add-on. Or do I misunderstand the question?

**Comment by blakeblackshear** [comment]
Enable the watchdog for the addon and homeassistant will restart it.
![image](https://user-images.githubusercontent.com/569905/106140086-e77eb800-6133-11eb-8365-c309bc5bfd61.png)

**Comment by Ysbrand** [comment]
Thanks, will give that a try.

**Comment by hagak** [comment]
If we are not running Frigate as a HA addon what is the best way to handle this condition?

**Comment by blakeblackshear** [comment]
How are you running it? Docker has commands built in for automatic restarts.

**Comment by hagak** [comment]
I am running it via compose and have "restart: always" set.  However when I see the error the OP posted the container is still running so docker does not know to restart since it is still online.  Should I add a health check to the container?  If so what is a good health check, since when this occurs the web server still responds.

**Comment by blakeblackshear** [comment]
Maybe something at `/api/stats`. There must be some process blocking the container from exiting. If you can find out what it is, I can try to reproduce it.

**Comment by hagak** [comment]
I just noticed i was on v0.8.0 so updated my container to v0.8.1 if the behaviour for this was modified.

**Comment by AlbinoDrought** [comment]
Similar here, all `/api` calls seems to return 502 when this happens:

```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

UI still loads but goes into endless `fetch /api/config` loop and does about 1000 requests/second:

![image](https://user-images.githubusercontent.com/852873/109595064-a843de00-7ac8-11eb-99d4-2586fd4d448d.png)


Docker container continues running for at least five minutes (but probably forever). These processes are still running

```
# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.5  1.4 1575100 114800 ?      Ssl  03:52   0:01 python3 -u -m frigate
root        18  0.0  0.0  16408  3240 ?        Ss   03:52   0:00 nginx: master process /usr/sbin/nginx
nobody      19  0.0  0.0  17484  7640 ?        S    03:52   0:00 nginx: worker process
root        30  0.0  0.0      0     0 ?        Z    03:52   0:00 [frigate.logger] <defunct>
root        34  0.0  0.1  14520 11036 ?        S    03:52   0:00 /usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(27)
root        38  0.0  0.8 934808 72424 ?        Sl   03:52   0:00 frigate.process:test
root        40  1.9  0.0      0     0 ?        Z    03:52   0:04 [python3] <defunct>
root        69  1.0  0.0   2612   608 pts/0    Ss   03:56   0:00 sh
root        74  0.0  0.0   5900  2888 pts/0    R+   03:56   0:00 ps aux
```

Logs:

```
frigate    | frigate.app                    INFO    : Stopping...
frigate    | frigate.object_processing      INFO    : Exiting object processor...
frigate    | frigate.events                 INFO    : Exiting event processor...
frigate    | frigate.record                 INFO    : Exiting recording maintenance...
frigate    | frigate.events                 INFO    : Exiting event cleanup...
frigate    | frigate.watchdog               INFO    : Exiting watchdog...
frigate    | frigate.stats                  INFO    : Exiting watchdog...
frigate    | peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
frigate    | root                           INFO    : Waiting for detection process to exit gracefully...
```

**Comment by progman32** [comment]
I also see this issue. It's a bit of a pain because it never detects the USB EdgeTPU the first try after a reboot, but it always works the second time.
```
root@3fa27d72af1d:/opt/frigate# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.7  1.3 1348916 106600 ?      Ssl  20:51   0:02 python3 -u -m frigate
root        19  0.0  0.0  16408  3240 ?        Ss   20:51   0:00 nginx: master process /usr/sbin/nginx
nobody      20  0.0  0.0  17072  6860 ?        S    20:51   0:00 nginx: worker process
root        29  0.0  0.0      0     0 ?        Z    20:51   0:00 [frigate.logger] <defunct>
root        33  0.0  0.1  14504 10940 ?        S    20:51   0:00 /usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(33)
root        38  0.0  0.8 931804 72312 ?        Sl   20:51   0:00 frigate.process:cave
root        39  0.0  0.0      0     0 ?        Z    20:51   0:00 [frigate.process] <defunct>
root        40  0.0  0.0      0     0 ?        Z    20:51   0:00 [frigate.process] <defunct>
root        41  0.0  0.0      0     0 ?        Z    20:51   0:00 [python3] <defunct>
root        42  0.0  0.0      0     0 ?        Z    20:51   0:00 [python3] <defunct>
root        45  0.0  0.0      0     0 ?        Z    20:51   0:00 [python3] <defunct>
root        47  0.1  0.0      0     0 ?        Z    20:51   0:00 [python3] <defunct>
root       232  0.0  0.0   4244  3556 pts/0    Ss   20:56   0:00 /bin/bash
root       241  0.0  0.0   5900  2916 pts/0    R+   20:57   0:00 ps aux
```
```
frigate.watchdog               INFO    : Detection appears to have stopped. Exiting frigate...
frigate.app                    INFO    : Stopping...
frigate.object_processing      INFO    : Exiting object processor...
frigate.events                 INFO    : Exiting event processor...
frigate.record                 INFO    : Exiting recording maintenance...
frigate.watchdog               INFO    : Exiting watchdog...
frigate.events                 INFO    : Exiting event cleanup...
frigate.stats                  INFO    : Exiting watchdog...
peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
root                           INFO    : Waiting for detection process to exit gracefully...
frigate.video                  INFO    : driveway: exiting subprocess
```

If I manually send a TERM to process 38 in my example, nothing happens. I have to KILL the process for frigate to actually stop. Then docker restarts the container.
