### ISSUE TITLE
[Support]: 0.12 Container stops before loading completely

### ISSUE THREAD

**Issue by poulti** [blakeblackshear/frigate#6433]
### Describe the problem you are having

I'm trying to migrate to the latest version of Frigate (container from ghcr.io) but I can't get it to start - my ultimate goal of the migration will be to turn on hwaccel on raspberry pi 4.
My config works well in 0.11.1-2EADA21 (from docker hub registry). I'm trying to start the image from GitHub Registry ``ghcr.io/blakeblackshear/frigate:stable``.

In the log below, you'll see all starting (normally?) up to
```
2023-05-08 08:28:59.107213696  [INFO] Starting go2rtc healthcheck service...
```
Then nothing else in the log for a few minutes, and the rest of the log files (all the "stopping").
During the "few minutes" the webrtc is not available.

Reverting to 0.11.1 (by changing the image in compose file) restores everything normally.
I'm wondering if some existing data / db or somehting leftover from 0.11.1 would be conflicting with 0.12? Any lead?
Thanks

### Version

0.11.1-2EADA21 to 0.12.0-da3e197 (I guess)

### Frigate config file

```yaml
# yaml-language-server: $schema=http://localhost:5555/api/config/schema
mqtt:
  host: mosquitto

## Hardware acceleration for raspberry 4 (64bit OS)
# ffmpeg:
#   hwaccel_args: preset-rpi-64-h264
# ffmpeg:
#   hwaccel_args:
#     - -c:v
#     - h264_v4l2m2m

cameras:

  camera_tapo2: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@xxx:554/stream2 # Low 640x360 stream
          # roles:
          #   - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: False # No detection in kids room
      width: 640 # <---- update for your camera's resolution
      height: 360 # <---- update for your camera's resolution
    mqtt:
      enabled: false # Deactivated to save CPU time
      quality: 100
      timestamp: false
      bounding_box: false
      crop: True
      height: 360

  camera_g41: # <------ Name the camera
    ffmpeg:
      inputs:
          # From the RTSPS link in Unifi protect, remove the s, change port to 7447
          # and remove the final enableSTPS
        - path: rtsp://xxx:7447/xxx # Medium 1280x720 stream
          roles:
            - detect
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    mqtt:
      enabled: true
      quality: 100
      timestamp: false
      bounding_box: false
      crop: True
      height: 720

  camera_g42: # <------ Name the camera
    ffmpeg:
      inputs:
          # From the RTSPS link in Unifi protect, remove the s, change port to 7447
          # and remove the final enableSTPS
        - path: rtsp://xxx:7447/xxx # Medium 1280x720 stream
          # roles:
          #   - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: False # No detection for FFA
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
    mqtt:
      enabled: false # Deactivated to save CPU time
      quality: 100
      timestamp: false
      bounding_box: false
      crop: True
      height: 720

  camera_iegeek1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxx:554/2 # Low 640x352 stream
          roles:
            - detect
    motion:
      mask:
        #- 0,0,0,981,523,142,1212,105,1920,326,1920,0 # Mask for High quality stream
        - 0,0,0,352,139,32,344,31,640,260,640,0 # Mask for Low quality stream
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: True
      width: 640 # <---- update for your camera's resolution
      height: 352 # <---- update for your camera's resolution
    objects:
      filters:
        person:
          min_score: 0.7
          threshold: 0.8
    record:
      enabled: true
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 2
          mode: active_objects
        pre_capture: 5
        post_capture: 5
        objects:
          - person
    mqtt:
      enabled: false # Deactivated to save CPU time
      quality: 100
      timestamp: false
      bounding_box: false
      crop: True
      height: 352

snapshots:
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True


detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-05-08 08:28:49.080894388  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service go2rtc-healthcheck successfully started
2023-05-08 08:28:49.100402166  [INFO] Starting Frigate...
s6-rc: info: service legacy-services: starting
2023-05-08 08:28:49.126341198  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-05-08 08:28:50.027142275  [INFO] Starting go2rtc...
2023-05-08 08:28:50.249782906  08:28:50.249 INF go2rtc version 1.2.0 linux/arm64
2023-05-08 08:28:50.251094690  08:28:50.250 INF [api] listen addr=:1984
2023-05-08 08:28:50.252249994  08:28:50.252 INF [rtsp] listen addr=:8554
2023-05-08 08:28:50.253567167  08:28:50.253 INF [srtp] listen addr=:8443
2023-05-08 08:28:50.254594342  08:28:50.254 INF [webrtc] listen addr=:8555
2023-05-08 08:28:53.604425902  [2023-05-08 08:28:53] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-08 08:28:53.743851248  [2023-05-08 08:28:53] peewee_migrate                 INFO    : Starting migrations
2023-05-08 08:28:53.844261667  [2023-05-08 08:28:53] peewee_migrate                 INFO    : There is nothing to migrate
2023-05-08 08:28:53.937510672  [2023-05-08 08:28:53] detector.coral                 INFO    : Starting detection process: 293
2023-05-08 08:28:53.948325811  [2023-05-08 08:28:53] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-08 08:28:56.687884264  [2023-05-08 08:28:53] frigate.app                    INFO    : Output process started: 295
2023-05-08 08:28:56.687897930  [2023-05-08 08:28:53] frigate.app                    INFO    : Camera processor started for camera_tapo2: 299
2023-05-08 08:28:56.687913245  [2023-05-08 08:28:53] frigate.app                    INFO    : Camera processor started for camera_g41: 302
2023-05-08 08:28:56.687918189  [2023-05-08 08:28:54] frigate.app                    INFO    : Camera processor started for camera_g42: 303
2023-05-08 08:28:56.688005689  [2023-05-08 08:28:54] frigate.app                    INFO    : Camera processor started for camera_iegeek1: 304
2023-05-08 08:28:56.688234131  [2023-05-08 08:28:54] frigate.app                    INFO    : Capture process started for camera_tapo2: 306
2023-05-08 08:28:56.688242816  [2023-05-08 08:28:54] frigate.app                    INFO    : Capture process started for camera_g41: 308
2023-05-08 08:28:56.688704571  [2023-05-08 08:28:54] frigate.app                    INFO    : Capture process started for camera_g42: 312
2023-05-08 08:28:56.689279269  [2023-05-08 08:28:54] frigate.app                    INFO    : Capture process started for camera_iegeek1: 314
2023-05-08 08:28:56.707357190  [2023-05-08 08:28:56] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-08 08:28:59.107213696  [INFO] Starting go2rtc healthcheck service...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-08 08:33:52.052052324  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-08 08:33:52.152720168  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-05-08 08:33:52.164507613  [2023-05-08 08:33:52] frigate.app                    INFO    : Stopping...
2023-05-08 08:33:52.167616176  [2023-05-08 08:33:52] frigate.events                 INFO    : Exiting event cleanup...
2023-05-08 08:33:52.168545056  [2023-05-08 08:33:52] root                           INFO    : Waiting for detection process to exit gracefully...
2023-05-08 08:33:52.169386455  [2023-05-08 08:33:52] detector.coral                 INFO    : Signal to exit detection process...
s6-rc: info: service nginx-log successfully stopped
2023-05-08 08:33:52.173212030  [2023-05-08 08:33:52] frigate.record                 INFO    : Exiting recording maintenance...
2023-05-08 08:33:52.176184021  [2023-05-08 08:33:52] frigate.watchdog               INFO    : Exiting watchdog...
2023-05-08 08:33:52.182387703  [2023-05-08 08:33:52] frigate.stats                  INFO    : Exiting stats emitter...
2023-05-08 08:33:52.184622811  [2023-05-08 08:33:52] frigate.storage                INFO    : Exiting storage maintainer...
2023-05-08 08:33:52.185323064  [2023-05-08 08:33:52] frigate.record                 INFO    : Exiting recording cleanup...
2023-05-08 08:33:52.261098903  [2023-05-08 08:33:52] frigate.object_processing      INFO    : Exiting object processor...
2023-05-08 08:33:52.279315786  [2023-05-08 08:33:52] detector.coral                 INFO    : Exited detection process...
2023-05-08 08:33:52.323441721  [2023-05-08 08:33:52] root                           INFO    : Detection process has exited...
2023-05-08 08:33:52.850308535  [2023-05-08 08:33:52] frigate.comms.ws               INFO    : Exiting websocket client...
2023-05-08 08:33:53.076685783  [2023-05-08 08:33:53] frigate.events                 INFO    : Exiting event processor...
2023-05-08 08:33:53.092685002  [2023-05-08 08:33:53] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-05-08 08:33:53.112594147  [2023-05-08 08:33:53] watchdog.camera_g42            INFO    : Terminating the existing ffmpeg process...
2023-05-08 08:33:53.114560517  [2023-05-08 08:33:53] watchdog.camera_g41            INFO    : Terminating the existing ffmpeg process...
2023-05-08 08:33:53.115493657  [2023-05-08 08:33:53] watchdog.camera_g42            INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-08 08:33:53.128560274  [2023-05-08 08:33:53] watchdog.camera_iegeek1        INFO    : Terminating the existing ffmpeg process...
2023-05-08 08:33:53.129263675  [2023-05-08 08:33:53] watchdog.camera_iegeek1        INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-08 08:33:53.130017945  [2023-05-08 08:33:53] watchdog.camera_tapo2          INFO    : Terminating the existing ffmpeg process...
2023-05-08 08:33:53.130713179  [2023-05-08 08:33:53] watchdog.camera_tapo2          INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-08 08:33:53.131347673  [2023-05-08 08:33:53] watchdog.camera_g41            INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-08 08:33:53.131939983  [2023-05-08 08:33:53] frigate.video                  INFO    : camera_tapo2: exiting subprocess
2023-05-08 08:33:53.842897037  [2023-05-08 08:33:53] frigate.output                 INFO    : exiting output process...
2023-05-08 08:33:53.973118509  [2023-05-08 08:33:53] frigate.video                  INFO    : camera_iegeek1: exiting subprocess
2023-05-08 08:33:54.027165684  [2023-05-08 08:33:54] frigate.video                  INFO    : camera_g42: exiting subprocess
2023-05-08 08:33:58.050713246  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 20 leaked shared_memory objects to clean up at shutdown
2023-05-08 08:33:58.050731857    warnings.warn('resource_tracker: There appear to be %d '
2023-05-08 08:33:58.072710613  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-05-08 08:33:58.094504129  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-05-08 08:33:58.129888535  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

1x Tapo c200, 2x Unifi G4, 1x ieGeek

### Any other information that may be helpful

Running on Raspbian OS. Kernel 6.1.21-v8+.

Relevant part of the compose file (I'm in Swarm Mode, hence the USB passed in volume):
```yaml
  frigate:
    container_name: frigate
    hostname: frigate
    image: ghcr.io/blakeblackshear/frigate:stable # Moved to ghcr registry from Docker Hub
    restart: unless-stopped
    ports:
      - "5555:5000"
      - "1935:1935" # RTMP feeds
    environment:
     - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate-config:/config:ro
      - frigate-media:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    # shm_size: "190mb" # update for your cameras based on calculation below (each Tapo is ~27mb and G4 is ~53mb)
    # (width * height * 1.5 * 9 + 270480)/1048576 = <shm size in mb> for each camera
    # The below volume replaces shm_size for swarm mode
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: 190000000 # (this means 190mb)
      - /dev/bus/usb:/dev/bus/usb # passes the whole USB bus to access the USB Coral (because it changes name)
      - /dev/video10:/dev/video10 # passing the Raspberry Pi 4 GPU
    networks:
      - homelab-net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5000 || exit 1
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s
```

**Comment by poulti** [comment]
Good call! It now loads and I can access the WebUI

Got a couple of resize error, but looks like one off and the interface seems to work fine.
I'll try to add the hwaccel now, thanks
```
2023-05-08 17:26:32.095380731  [2023-05-08 17:26:32] frigate.http                   ERROR   : Exception on /camera_tapo2/latest.jpg [GET]
2023-05-08 17:26:32.095393601  Traceback (most recent call last):
2023-05-08 17:26:32.095396564    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
2023-05-08 17:26:32.095398712      response = self.full_dispatch_request()
2023-05-08 17:26:32.095401749    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-05-08 17:26:32.095403730      rv = self.handle_user_exception(e)
2023-05-08 17:26:32.095406675    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-05-08 17:26:32.095408508      rv = self.dispatch_request()
2023-05-08 17:26:32.095411471    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-05-08 17:26:32.095414045      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-05-08 17:26:32.095416415    File "/opt/frigate/frigate/http.py", line 896, in latest_frame
2023-05-08 17:26:32.095419064      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-05-08 17:26:32.095422712  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
```
