### ISSUE TITLE
[Config Support]: Creating a basic config.yml to get started with go2rtc

### ISSUE THREAD

**Issue by mikey6283** [blakeblackshear/frigate#6500]
### Describe the problem you are having

  I am unable to create a basic config based on the documentation for Reolink cameras.

### Version

latest stable version

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.55.51:5000/api/config/schema


mqtt:
  host: 192.168.55.51
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db

record:
  expire_interval: 20

go2rtc:
  streams
    garage:
      - http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Garage1
      - "ffmpeg:reolink#audio=opus"
    garage_sub:
      - http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1


cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 2
#        mode: active_objects
#      events:
#        retain:
#          default: 5
#          mode: motion
#        pre_capture: 3
#        post_capture: 10
```

### Relevant log output

```shell
023-05-15 17:39:55.137858336      return loader.get_single_data()
2023-05-15 17:39:55.137859892    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
2023-05-15 17:39:55.137861172      node = self.get_single_node()
2023-05-15 17:39:55.137862545    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
2023-05-15 17:39:55.137875383      document = self.compose_document()
2023-05-15 17:39:55.137876872    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
2023-05-15 17:39:55.137878172      node = self.compose_node(None, None)
2023-05-15 17:39:55.137879564    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-05-15 17:39:55.137880812      node = self.compose_mapping_node(anchor)
2023-05-15 17:39:55.137882252    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
2023-05-15 17:39:55.137883452      while not self.check_event(MappingEndEvent):
2023-05-15 17:39:55.137894955    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
2023-05-15 17:39:55.137896158      self.current_event = self.state()
2023-05-15 17:39:55.137897558    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
2023-05-15 17:39:55.137898820      if self.check_token(KeyToken):
2023-05-15 17:39:55.137900130    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
2023-05-15 17:39:55.137901262      self.fetch_more_tokens()
2023-05-15 17:39:55.137902625    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
2023-05-15 17:39:55.137918079      return self.fetch_value()
2023-05-15 17:39:55.137919434    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
2023-05-15 17:39:55.137920536      raise ScannerError(None, None,
2023-05-15 17:39:55.137921765  yaml.scanner.ScannerError: mapping values are not allowed here
2023-05-15 17:39:55.137923056    in "<unicode string>", line 22, column 11:
2023-05-15 17:39:55.137924113          garage:
2023-05-15 17:39:55.137925155                ^
2023-05-15 17:39:55.137978611  
2023-05-15 17:39:55.138009329  *************************************************************
2023-05-15 17:39:55.138084635  ***    End Config Validation Errors                       ***
2023-05-15 17:39:55.138142506  *************************************************************
2023-05-15 17:39:55.483302249  2023/05/15 17:39:55 [error] 136#136: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.55.15, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.55.51:5000"
2023-05-15 17:39:55.483329279  192.168.55.15 - - [15/May/2023:17:39:55 +0100] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.5.2 aiohttp/3.8.4 Python/3.10" "-"
2023-05-15 17:39:55.503841595  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 27, in <module>
    config: dict[str, any] = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 22, column 11:
        garage:
              ^
2023-05-15 17:39:55.674120806  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-05-15 17:39:56.294494758  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-15 17:39:56.305950158  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-15 17:39:56.333504884  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Frigate stats

```json
not available.
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

PCIe

### Any other information that may be helpful

 I have tried many combination  Using the  rstp:// instead of http:// url as suggested in the docs. When using rstp URL i  was able to see the info  from go2rtc. ie config , logs etc, however when i revert back to the doc infor using http;// url i cannot  get  this information

**Comment by NickM-27** [comment]
the problem is that you are missing the `:` at the end of `streams` in the config

**Comment by mikey6283** [comment]
> the problem is that you are missing the `:` at the end of `streams` in the config

I  amended this` :` error but still no joy

This the error messages in th logs `y...
2023-05-15 18:53:52.138032987  [2023-05-15 18:53:52] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2023-05-15 18:53:52.138520792  [2023-05-15 18:53:52] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2023-05-15 18:53:57.674262921  192.168.55.15 - - [15/May/2023:18:53:57 +0100] "GET /api/stats HTTP/1.1" 200 2107 "-" "HomeAssistant/2023.5.2 aiohttp/3.8.4 Python/3.10" "-"
2023-05-15 18:54:02.142072180  [2023-05-15 18:54:02] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
2023-05-15 18:54:02.142181279  [2023-05-15 18:54:02] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-15 18:54:02.142209936  [2023-05-15 18:54:02] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x558ed60d7c40] method DESCRIBE failed: 404 Not Found
2023-05-15 18:54:02.142282407  [2023-05-15 18:54:02] ffmpeg.garage.detect           ERROR   : rtsp://127.0.0.1:8554/reolink_sub?video=copy: Server returned 404 Not Found
2023-05-15 18:54:02.152908744  [2023-05-15 18:54:02] ffmpeg.garage.record           ERROR   : [rtsp @ 0x55922b6bdd80] method DESCRIBE failed: 404 Not Found
2023-05-15 18:54:02.153002654  [2023-05-15 18:54:02] ffmpeg.garage.record           ERROR   : rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac: Server returned 404 Not Found
2023-05-15 18:54:02.153076555  [2023-05-15 18:54:02] watchdog.garage                INFO    : Terminating the existing ffmpeg process...
2023-05-15 18:54:02.153139760  [2023-05-15 18:54:02] watchdog.garage                INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-15 18:54:02.160064728  [2023-05-15 18:54:02] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2023-05-15 18:54:02.160656867  [2023-05-15 18:54:02] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2023-05-15 18:54:05.775619384  192.168.55.15 - - [15/May/2023:18:54:05 +0100] "GET /api/stats HTTP/1.1" 200 2075 "-" "HomeAssistant/2023.5.2 aiohttp/3.8.4 Python/3.10" "-"
2023-05-15 18:54:12.163758417  [2023-05-15 18:54:12] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
2023-05-15 18:54:12.163819431  [2023-05-15 18:54:12] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-15 18:54:12.163944143  [2023-05-15 18:54:12] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x5612a9169c40] method DESCRIBE failed: 404 Not Found
2023-05-15 18:54:12.163946672  [2023-05-15 18:54:12] ffmpeg.garage.detect           ERROR   : rtsp://127.0.0.1:8554/reolink_sub?video=copy: Server returned 404 Not Found
2023-05-15 18:54:12.174691751  [2023-05-15 18:54:12] ffmpeg.garage.record           ERROR   : [rtsp @ 0x55da13d65d80] method DESCRIBE failed: 404 Not Found
2023-05-15 18:54:12.179202545  [2023-05-15 18:54:12] ffmpeg.garage.record           ERROR   : rtsp://127.0.0.1:8554/reolink?video=copy&audio=aac: Server returned 404 Not Found
2023-05-15 18:54:12.179756279  [2023-05-15 18:54:12] watchdog.garage                INFO    : Terminating the existing ffmpeg process...
2023-05-15 18:54:12.179759186  [2023-05-15 18:54:12] watchdog.garage                INFO    : Waiting for ffmpeg to exit gracefully...
2023-05-15 18:54:12.180550355  [2023-05-15 18:54:12] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2023-05-15 18:54:12.181044123  [2023-05-15 18:54:12] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2023-05-15 18:54:13.670349254  192.168.55.15 - - [15/May/2023:18:54:13 +0100] "GET /api/stats HTTP

 This the type of error i have been receiving all day

**Comment by mikey6283** [comment]
> because reolink_sub does not exist. You called it garage_sub so of course you need to refer to it as garage_sub in the cameras config

I  changed back to reolink & reolink_sub where required and still get the `023-05-15 19:41:53.781081893  [2023-05-15 19:41:53] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x55ea30b50c40] method DESCRIBE failed: 404 Not Found
2023-05-15 19:41:53.781144794  [2023-05-15 19:41:53] ffmpeg.garage.detect           ERROR   : rtsp://127.0.0.1:8554/reolink_sub?video=copy: Server returned 404 Not Found
2023-05-15 19:41:53.913001566  19:41:53.912 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" url=http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1
2023-05-15 19:41:53.913005211  19:41:53.912 WRN [rtsp] error="source 0 error: Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" stream=reolink_sub
2023-05-15 19:41:53.915436536  [2023-05-15 19:41:53] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2023-05-15 19:41:53.915576472  [2023-05-15 19:41:53] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2023-05-15 19:42:00.673911823  192.168.55.15 - - [15/May/2023:19:42:00 +0100] "GET /api/stats HTTP/1.1" 200 2073 "-" "HomeAssistant/2023.5.2 aiohttp/3.8.4 Python/3.10" "-"
2023-05-15 19:42:03.792109898  [2023-05-15 19:42:03] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
2023-05-15 19:42:03.792237145  [2023-05-15 19:42:03] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-15 19:42:03.792263308  [2023-05-15 19:42:03] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x55e41fe3fc40] method DESCRIBE failed: 404 Not Found
2023-05-15 19:42:03.792346927  [2023-05-15 19:42:03] ffmpeg.garage.detect           ERROR   : rtsp://127.0.0.1:8554/reolink_sub?video=copy: Server returned 404 Not Found
2023-05-15 19:42:03.984771359  19:42:03.984 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" url=http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1
2023-05-15 19:42:03.984809000  19:42:03.984 WRN [rtsp] error="source 0 error: Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" stream=reolink_sub
2023-05-15 19:42:03.987192758  [2023-05-15 19:42:03] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2023-05-15 19:42:03.987445396  [2023-05-15 19:42:03] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...

**Comment by NickM-27** [comment]
What does your config look like now? Also to be clear if you've done it correctly you should not have reolink_sub in your config as that is just an example, you name it what you want.

**Comment by mikey6283** [comment]
The config has all the changes  we hae and i checked the config .yml in th go2rtc and  unraid bothe are the same  , but get theses error in both 

023-05-15 21:15:29.223229395  [2023-05-15 21:15:29] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x5635ddde2c40] method DESCRIBE failed: 404 Not Found
2023-05-15 21:15:29.223232236  [2023-05-15 21:15:29] ffmpeg.garage.detect           ERROR   : rtsp://127.0.0.1:8554/garage_sub?video=copy: Server returned 404 Not Found
2023-05-15 21:15:29.338674932  21:15:29.338 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" url=http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1
2023-05-15 21:15:29.338693681  21:15:29.338 WRN [rtsp] error="source 0 error: Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" stream=garage_sub
2023-05-15 21:15:29.341753391  [2023-05-15 21:15:29] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2023-05-15 21:15:29.341931579  [2023-05-15 21:15:29] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
2023-05-15 21:15:32.680055461  192.168.55.15 - - [15/May/2023:21:15:32 +0100] "GET /api/stats HTTP/1.1" 200 2079 "-" "HomeAssistant/2023.5.2 aiohttp/3.8.4 Python/3.10" "-"
2023-05-15 21:15:39.230024449  [2023-05-15 21:15:39] watchdog.garage                ERROR   : Ffmpeg process crashed unexpectedly for garage.
2023-05-15 21:15:39.230146123  [2023-05-15 21:15:39] watchdog.garage                ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-05-15 21:15:39.230180532  [2023-05-15 21:15:39] ffmpeg.garage.detect           ERROR   : [rtsp @ 0x5618d33e3c40] method DESCRIBE failed: 404 Not Found
2023-05-15 21:15:39.230246223  [2023-05-15 21:15:39] ffmpeg.garage.detect           ERROR   : rtsp://127.0.0.1:8554/garage_sub?video=copy: Server returned 404 Not Found
2023-05-15 21:15:39.346949893  21:15:39.346 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" url=http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1
2023-05-15 21:15:39.346969101  21:15:39.346 WRN [rtsp] error="source 0 error: Get \"http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1\": EOF" stream=garage_sub
2023-05-15 21:15:39.349376048  [2023-05-15 21:15:39] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2023-05-15 21:15:39.349971787  [2023-05-15 21:15:39] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
`
# yaml-language-server: $schema=http://192.168.55.51:5000/api/config/schema


mqtt:
  host: 192.168.55.51
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db

record:
  expire_interval: 20

go2rtc:
  streams:
    garage:
      - http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=Garage1
      - "ffmpeg:reolink#audio=opus"
    garage_sub:
      - http://10.10.75.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=username&password=Garage1


cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 2
#        mode: active_objects
#      events:
#        retain:
#          default: 5
#          mode: motion
#        pre_capture: 3
#        post_capture: 10

**Comment by mikey6283** [comment]
> Your second stream on garage `- "ffmpeg:reolink#audio=opus"` should be `- "ffmpeg:garage#audio=opus"`
 I have been trying various option and  have been able to get images into frigate ui  However, i am still  get  the following error and i am unable to look a recordings in the Frigate ui. any  help would be appreciated.

" url="ffmpeg:rtsp://admin:Front1@10.10.75.27:554/h264Preview_01_main - \"ffmpeg:front#audio=opus\""
2023-05-16 16:14:06.681837122  16:14:06.681 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=front
2023-05-16 16:14:07.147040037  16:14:07.146 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Garage1@10.10.75.24:554/h264Preview_01_main - \"ffmpeg:garage#audio=opus\""
2023-05-16 16:14:07.147043928  16:14:07.147 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=garage
2023-05-16 16:14:14.336808518  16:14:14.336 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Koipond1@10.10.75.25:554/h264Preview_01_main - \"ffmpeg:koipond#audio=opus\""
2023-05-16 16:14:14.660180368  16:14:14.660 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Front1@10.10.75.27:554/h264Preview_01_main - \"ffmpeg:front#audio=opus\""
2023-05-16 16:14:15.127086080  16:14:15.126 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Garage1@10.10.75.24:554/h264Preview_01_main - \"ffmpeg:garage#audio=opus\""
2023-05-16 16:14:16.315113269  16:14:16.315 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Koipond1@10.10.75.25:554/h264Preview_01_main - \"ffmpeg:koipond#audio=opus\""
2023-05-16 16:14:16.315116734  16:14:16.315 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=koipond
2023-05-16 16:14:16.619593861  16:14:16.619 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Front1@10.10.75.27:554/h264Preview_01_main - \"ffmpeg:front#audio=opus\""
2023-05-16 16:14:16.619597409  16:14:16.619 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=front
2023-05-16 16:14:17.124498868  16:14:17.124 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Garage1@10.10.75.24:554/h264Preview_01_main - \"ffmpeg:garage#audio=opus\""
2023-05-16 16:14:17.124521602  16:14:17.124 WRN [rtsp] error="source 0 error: exec: exit status 1" stream=garage
2023-05-16 16:14:24.335899587  16:14:24.335 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Koipond1@10.10.75.25:554/h264Preview_01_main - \"ffmpeg:koipond#audio=opus\""
2023-05-16 16:14:24.608432253  16:14:24.608 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Front1@10.10.75.27:554/h264Preview_01_main - \"ffmpeg:front#audio=opus\""
2023-05-16 16:14:25.150719457  16:14:25.150 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url="ffmpeg:rtsp://admin:Garage1@10.10.75.24:554/h264Preview_01_main - \"ffmpeg:garage#audio=opus

config is ` # yaml-language-server: $schema=http://192.168.55.51:5000/api/config/schema

mqtt:
  host: 192.168.55.51
  user: mqtt6283
  password: mikey

detectors:
  cora1:
    type: edgetpu
    device: pci:0

database:
  path: /media/frigate/frigate.db

record:
  expire_interval: 20

go2rtc:
  streams:
    koipond: ffmpeg:rtsp://admin:Koipond1@10.10.75.25:554/h264Preview_01_main
      - "ffmpeg:koipond#audio=opus"
    koipond_sub: ffmpeg:rtsp://admin:Koipond1@10.10.75.25:554/h264Preview_01_sub
    front: ffmpeg:rtsp://admin:Front1@10.10.75.27:554/h264Preview_01_main
      - "ffmpeg:front#audio=opus"
    front_sub: ffmpeg:rtsp://admin:Front1@10.10.75.27:554/h264Preview_01_sub
    garage: ffmpeg:rtsp://admin:Garage1@10.10.75.24:554/h264Preview_01_main
      - "ffmpeg:garage#audio=opus"
    garage_sub: ffmpeg:rtsp://admin:Garage1@10.10.75.24/h264Preview_01_sub
cameras:
  koipond:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/koipond?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/koipond_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
  front:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    objects:
      track:
        - person
        - cat
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 7
          mode: active_objects
