### ISSUE TITLE
[Support]: Unhandled exception in latest_frame function on 0.12.0

### ISSUE THREAD

**Issue by mweinelt** [blakeblackshear/frigate#6565]
### Describe the problem you are having

I was in the process of setting up my first camera, when I noticed an exception flying around in my logs, likely because the first camera setup didn't work.

The issue is not related to any specific camera, it's just about an exception that probably should be caught.

### Version

0.12.0

### Frigate config file

n/a

### Relevant log output

```shell
python3.10[552576]: [2023-05-22 02:15:11] frigate.http                   ERROR   : Exception on /ball/latest.jpg [GET]
python3.10[552576]: Traceback (most recent call last):
python3.10[552576]:   File "/nix/store/n0syiwyy2bxg30l13sia42y13isgacqg-python3.10-flask-2.2.3/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
python3.10[552576]:     response = self.full_dispatch_request()
python3.10[552576]:   File "/nix/store/n0syiwyy2bxg30l13sia42y13isgacqg-python3.10-flask-2.2.3/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
python3.10[552576]:     rv = self.handle_user_exception(e)
python3.10[552576]:   File "/nix/store/n0syiwyy2bxg30l13sia42y13isgacqg-python3.10-flask-2.2.3/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
python3.10[552576]:     rv = self.dispatch_request()
python3.10[552576]:   File "/nix/store/n0syiwyy2bxg30l13sia42y13isgacqg-python3.10-flask-2.2.3/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
python3.10[552576]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
python3.10[552576]:   File "/nix/store/v63yzly5l7nj70fn8jfl0j9awlzw4a27-frigate-0.12.0/lib/python3.10/site-packages/frigate/http.py", line 893, in latest_frame
python3.10[552576]:     height = int(request.args.get("h", str(frame.shape[0])))
python3.10[552576]: AttributeError: 'NoneType' object has no attribute 'shape'
```

### FFprobe output from your camera

n/a

### Operating system

Other Linux

### Install method

Packaged up for NixOS

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

irrelevant

**Comment by mweinelt** [comment]
Still relevant.

**Comment by zoechi** [comment]
I still see a lot of these errors `AttributeError: 'NoneType' object has no attribute 'shape'` in 0.14.1
