### ISSUE TITLE
[Config Support]: escaping mqtt password

### ISSUE THREAD

**Issue by spad** [blakeblackshear/frigate#6605]
### Describe the problem you are having

When the mqtt password contains a } character, the python format function fails.

Trying to escape the password as suggested by python doc (doubling the }) the authentication fails

### Version

0.13.0-E3B9998

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.200.27
  port: 8883
  user: <myuser>
  password: 'abdcefgh1234}4'
```

### Relevant log output

```shell
2023-05-25 08:34:37.680035501  Traceback (most recent call last):
2023-05-25 08:34:37.680052856    File "/opt/frigate/frigate/app.py", line 401, in start
2023-05-25 08:34:37.680053753      self.init_config()
2023-05-25 08:34:37.680054676    File "/opt/frigate/frigate/app.py", line 94, in init_config
2023-05-25 08:34:37.680055504      self.config = user_config.runtime_config(self.plus_api)
2023-05-25 08:34:37.680056333    File "/opt/frigate/frigate/config.py", line 917, in runtime_config
2023-05-25 08:34:37.680057141      config.mqtt.password = config.mqtt.password.format(**FRIGATE_ENV_VARS)
2023-05-25 08:34:37.680058798  ValueError: Single '}' encountered in format string
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

I'm using _ghcr.io/blakeblackshear/frigate:dev-e3b9998-tensorrt_ image

**Comment by NickM-27** [comment]
The best way would be to probably set an env variable with the password and use the password substitution

**Comment by solstyce9** [comment]
I just ran into this as well.  Annoying.
