### ISSUE TITLE
[Detector Support]: USB Coral Getting Stuck

### ISSUE THREAD

**Issue by korsmann** [blakeblackshear/frigate#6623]
### Describe the problem you are having

I have a USB Coral forwarded to HA running on a VM in Proxmox.
Using USB ID (or Port) forwarding, Frigate sucessfully detects the Coral and detection/recording starts.
However, after a while (non specific) the frigate.watchdog reports "Detection appears to be stuck" and force restarts the process.
TPU is detected as expected and may run for up to an hour, no issues, when it again detection get stuck.

### Version

0.12.0-DA3E197

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.150
  user: FRIGATE_user
  password: FRIGATE_MQTT_password
  
detectors:
  coral:
    type: edgetpu
    device: usb
cameras:
  front_door:
    record:
      enabled: False
      expire_interval: 30
      retain:
        days: 0
        mode: motion
      events:
        retain:
          default: 2
          mode: active_objects
          objects:
            person: 2
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.1.110:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://user:password@192.168.1.110:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 1280
      height: 720
```

### docker-compose file or Docker CLI command

```yaml
Not using docker (ATM)
```

### Relevant log output

```shell
2023-05-26 10:15:31.594521922  [2023-05-26 12:15:31] detector.coral                 INFO    : Starting detection process: 299
2023-05-26 10:15:31.595267261  [2023-05-26 12:15:31] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-26 10:15:31.612783476  [2023-05-26 12:15:31] frigate.app                    INFO    : Camera processor started for front_door: 304
2023-05-26 10:15:31.667442967  [2023-05-26 12:15:31] frigate.app                    INFO    : Capture process started for front_door: 308
2023-05-26 10:15:34.459791929  [2023-05-26 12:15:34] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-26 10:23:12.131379876  [2023-05-26 12:23:12] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2023-05-26 10:23:12.132825466  [2023-05-26 12:23:12] root                           INFO    : Waiting for detection process to exit gracefully...
2023-05-26 10:23:42.159822231  [2023-05-26 12:23:42] root                           INFO    : Detection process didnt exit. Force killing...
2023-05-26 10:23:42.188064273  [2023-05-26 12:23:42] root                           INFO    : Detection process has exited...
2023-05-26 10:23:42.205152063  [2023-05-26 12:23:42] detector.coral                 INFO    : Starting detection process: 647
2023-05-26 10:23:42.212014803  [2023-05-26 12:23:42] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-26 10:23:45.080337060  [2023-05-26 12:23:45] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-05-26 10:26:27.474809245  [2023-05-26 12:26:27] frigate.http                   ERROR   : Exception on /front_door/latest.jpg [GET]
2023-05-26 10:26:27.474817605  Traceback (most recent call last):
2023-05-26 10:26:27.474826586    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
2023-05-26 10:26:27.474829485      response = self.full_dispatch_request()
2023-05-26 10:26:27.474832096    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-05-26 10:26:27.474834712      rv = self.handle_user_exception(e)
2023-05-26 10:26:27.474837088    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-05-26 10:26:27.475680842      rv = self.dispatch_request()
2023-05-26 10:26:27.475689031    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-05-26 10:26:27.476198072      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-05-26 10:26:27.476202733    File "/opt/frigate/frigate/http.py", line 896, in latest_frame
2023-05-26 10:26:27.476205991      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-05-26 10:26:27.476208642  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-05-26 10:26:27.476264471  
2023-05-26 10:26:30.238475044  [2023-05-26 12:26:30] frigate.comms.dispatcher       INFO    : Turning on snapshots for front_door
2023-05-26 10:26:51.503680791  [2023-05-26 12:26:51] frigate.http                   ERROR   : Exception on /front_door/latest.jpg [GET]
2023-05-26 10:26:51.503688896  Traceback (most recent call last):
2023-05-26 10:26:51.503691286    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2528, in wsgi_app
2023-05-26 10:26:51.503693232      response = self.full_dispatch_request()
2023-05-26 10:26:51.503695468    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-05-26 10:26:51.503697240      rv = self.handle_user_exception(e)
2023-05-26 10:26:51.503699528    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-05-26 10:26:51.503701196      rv = self.dispatch_request()
2023-05-26 10:26:51.503703364    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-05-26 10:26:51.503705441      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-05-26 10:26:51.503707420    File "/opt/frigate/frigate/http.py", line 896, in latest_frame
2023-05-26 10:26:51.503709493      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-05-26 10:26:51.503712053  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-05-26 10:26:51.503713531  
2023-05-26 10:29:02.210372412  [2023-05-26 12:29:02] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2023-05-26 10:29:02.210840554  [2023-05-26 12:29:02] root                           INFO    : Waiting for detection process to exit gracefully...
2023-05-26 10:29:32.241918172  [2023-05-26 12:29:32] root                           INFO    : Detection process didnt exit. Force killing...
2023-05-26 10:29:32.257709668  [2023-05-26 12:29:32] root                           INFO    : Detection process has exited...
2023-05-26 10:29:32.294888166  [2023-05-26 12:29:32] detector.coral                 INFO    : Starting detection process: 906
2023-05-26 10:29:32.301481365  [2023-05-26 12:29:32] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-05-26 10:29:35.167096239  [2023-05-26 12:29:35] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

I have 3 different cameras, wifi and wired, error occur if only using 1 (of any) of the cameras.
Config and log is from using a Reolink 410 wired PoE camera.
Running on a NUC, plugged in to USB3.0 port.

**Comment by NickM-27** [comment]
Try different ports and make sure you are not using the included cable, some users have seen problems with the included cable

**Comment by korsmann** [comment]
DIfferent ports (3.0 high power) and new cable (5Gb/s) tested, still get the same error.  
I am considering removing Proxmox and try running HA Core in Docker on Debian/Ubuntu as I struggle to get GPU hardware decoding working as well in the current setup...
