### ISSUE TITLE
[Config Support]: Config File Not Found

### ISSUE THREAD

**Issue by Richfa** [blakeblackshear/frigate#6632]
### Describe the problem you are having

good Morning, i dont have much computer experience, I managed to get frigate working on my pi4 but had to upgrade to get some extra CPU power,
I now have a intel nuc and using the same config i used previously doesn't work and i am getting all sorts of errors showing in portainer and the container always crashes. Would you be able to give me any guidance on what i should do please

### Version

?

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  name_of_your_camera: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:WJQKCN@192.168.5.18/h264_stream # <----- The strea>
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera >
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-05-27 07:59:23.329803801  [INFO] Preparing go2rtc config...
2023-05-27 07:59:23.331389119  [INFO] Starting Frigate...
2023-05-27 07:59:23.332644780  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:23.542985525  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-05-27 07:59:24.089180434  *************************************************************
2023-05-27 07:59:24.089183816  *************************************************************
2023-05-27 07:59:24.089185423  ***    Your config file is not valid!                     ***
2023-05-27 07:59:24.089186881  ***    Please check the docs at                           ***
2023-05-27 07:59:24.089187998  ***    https://docs.frigate.video/configuration/index     ***
2023-05-27 07:59:24.089189369  *************************************************************
2023-05-27 07:59:24.089190349  *************************************************************
2023-05-27 07:59:24.089208200  ***    Config Validation Errors                           ***
2023-05-27 07:59:24.089209196  *************************************************************
2023-05-27 07:59:24.089210020  [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:24.089820617  Traceback (most recent call last):
2023-05-27 07:59:24.089822382    File "/opt/frigate/frigate/app.py", line 351, in start
2023-05-27 07:59:24.089823302      self.init_config()
2023-05-27 07:59:24.089824292    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-05-27 07:59:24.089825198      user_config = FrigateConfig.parse_file(config_file)
2023-05-27 07:59:24.089826130    File "/opt/frigate/frigate/config.py", line 1064, in parse_file
2023-05-27 07:59:24.089826930      with open(config_file) as f:
2023-05-27 07:59:24.089827787  IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:24.089828487  
2023-05-27 07:59:24.089829392  *************************************************************
2023-05-27 07:59:24.089830538  ***    End Config Validation Errors                       ***
2023-05-27 07:59:24.089831418  *************************************************************
2023-05-27 07:59:24.090041378  [2023-05-27 07:59:24] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-27 07:59:24.551877388  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:24.719912546  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-05-27 07:59:25.211206622  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-27 07:59:25.219222600  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-27 07:59:25.344639749  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Frigate stats

```json
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-05-27 07:59:23.329803801  [INFO] Preparing go2rtc config...
2023-05-27 07:59:23.331389119  [INFO] Starting Frigate...
2023-05-27 07:59:23.332644780  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:23.542985525  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-05-27 07:59:24.089180434  *************************************************************
2023-05-27 07:59:24.089183816  *************************************************************
2023-05-27 07:59:24.089185423  ***    Your config file is not valid!                     ***
2023-05-27 07:59:24.089186881  ***    Please check the docs at                           ***
2023-05-27 07:59:24.089187998  ***    https://docs.frigate.video/configuration/index     ***
2023-05-27 07:59:24.089189369  *************************************************************
2023-05-27 07:59:24.089190349  *************************************************************
2023-05-27 07:59:24.089208200  ***    Config Validation Errors                           ***
2023-05-27 07:59:24.089209196  *************************************************************
2023-05-27 07:59:24.089210020  [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:24.089820617  Traceback (most recent call last):
2023-05-27 07:59:24.089822382    File "/opt/frigate/frigate/app.py", line 351, in start
2023-05-27 07:59:24.089823302      self.init_config()
2023-05-27 07:59:24.089824292    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-05-27 07:59:24.089825198      user_config = FrigateConfig.parse_file(config_file)
2023-05-27 07:59:24.089826130    File "/opt/frigate/frigate/config.py", line 1064, in parse_file
2023-05-27 07:59:24.089826930      with open(config_file) as f:
2023-05-27 07:59:24.089827787  IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:24.089828487  
2023-05-27 07:59:24.089829392  *************************************************************
2023-05-27 07:59:24.089830538  ***    End Config Validation Errors                       ***
2023-05-27 07:59:24.089831418  *************************************************************
2023-05-27 07:59:24.090041378  [2023-05-27 07:59:24] frigate.app                    INFO    : Starting Frigate (0.12.0-da3e197)
2023-05-27 07:59:24.551877388  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-05-27 07:59:24.719912546  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-05-27 07:59:25.211206622  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-27 07:59:25.219222600  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-27 07:59:25.344639749  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: True # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified >
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructio>
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your h>
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /cam/frigate/media/config.yml:/config/config.yml
      - /cam/frigate/media/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000

**Comment by NickM-27** [comment]
`/cam/frigate/media/config.yml` doesn't exist or isn't in that location

**Comment by Richfa** [comment]
That should be where my config. Yml is located I created it with mkdir cam, mkdir frigate, mkdir media then touch config.Yml then nano config.yml 
This created the correct file last time I did it, it was a while ago and it took me months of attempts I thought I had learned the basics on how to get it running.

**Comment by NickM-27** [comment]
Perhaps the directory structure is different, but there is no variability for docker finding that file, it does not exist at that location

**Comment by Richfa** [comment]
Do you have any other suggestions in setting up the file in Ubuntu in docker on a nuc? If I mkdir the config.yml then nano docker-compose will that be acceptable I think that creates a directory instead of the file that's needed

**Comment by NickM-27** [comment]
Creating the file there can be done however, you just need to verify the directory path is correct.

**Comment by Richfa** [comment]
i will give this ago with the nano docker-compose in the config.yml after making it with the mkdir just got remove current files. thank you for your help

**Comment by Richfa** [comment]
devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/cofig/config.yml:/config/config.yml
      - /frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

richard@nuc:~$ mkdir frigate
richard@nuc:~$ cd frigate
richard@nuc:~/frigate$ mkdir config
richard@nuc:~/frigate$ cd config
richard@nuc:~/frigate/config$ mkdir config.yml
richard@nuc:~/frigate/config$ cd config.yml
richard@nuc:~/frigate/config/config.yml$ nano docker-compose.yml
richard@nuc:~/frigate/config/config.yml$ nano config.yml
richard@nuc:~/frigate/config/config.yml$ exit

richard@nuc:~$ cd frigate
richard@nuc:~/frigate$ mkdir storage
richard@nuc:~/frigate$ nano docker-compose.yml
richard@nuc:~/frigate$ 

docker-compose up -d

**Comment by Richfa** [comment]
found a new command "locate filename"
locate config.yml
/cam/frigate/media/config.yml
/frigate/config.yml
/frigate/cofig/config.yml
/frigate/config/config.yml
/home/richard/frigate/config/config.yml
/nuc/frigate/cofig/config.yml
/path/to/your/config.yml
turns out I haven't deleted earlier attempts correctly I will reflash and start again next time with this I hope to get it write

**Comment by Richfa** [comment]
2023-05-28 16:28:36.225486416    File "/opt/frigate/frigate/config.py", line 1068, in parse_file
2023-05-28 16:28:36.225487300      config = load_config_with_no_duplicates(raw_config)
2023-05-28 16:28:36.225488229    File "/opt/frigate/frigate/util.py", line 78, in load_config_with_no_duplicates
2023-05-28 16:28:36.225489095      return yaml.load(raw_config, PreserveDuplicatesLoader)
2023-05-28 16:28:36.225490064    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
2023-05-28 16:28:36.225521713      return loader.get_single_data()
2023-05-28 16:28:36.225522884    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
2023-05-28 16:28:36.225523840      node = self.get_single_node()
2023-05-28 16:28:36.225524868    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
2023-05-28 16:28:36.225532438      document = self.compose_document()
2023-05-28 16:28:36.225533573    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
2023-05-28 16:28:36.225534562      node = self.compose_node(None, None)
2023-05-28 16:28:36.225535623    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-05-28 16:28:36.225536577      node = self.compose_mapping_node(anchor)
2023-05-28 16:28:36.225537649    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
2023-05-28 16:28:36.225538545      item_value = self.compose_node(node, item_key)
2023-05-28 16:28:36.225545572    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-05-28 16:28:36.225546480      node = self.compose_mapping_node(anchor)
2023-05-28 16:28:36.225547551    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
2023-05-28 16:28:36.225548522      while not self.check_event(MappingEndEvent):
2023-05-28 16:28:36.225549517    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
2023-05-28 16:28:36.225550364      self.current_event = self.state()
2023-05-28 16:28:36.225551392    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
2023-05-28 16:28:36.225560756      raise ParserError("while parsing a block mapping", self.marks[-1],
2023-05-28 16:28:36.225561699  yaml.parser.ParserError: while parsing a block mapping
2023-05-28 16:28:36.225562577    in "<unicode string>", line 5, column 3:
2023-05-28 16:28:36.225563444        name_of_your_camera: yard_camera ... 
2023-05-28 16:28:36.225564206        ^
2023-05-28 16:28:36.225565233  expected <block end>, but found '<block mapping start>'
2023-05-28 16:28:36.225566088    in "<unicode string>", line 6, column 5:
2023-05-28 16:28:36.225566857          ffmpeg:
2023-05-28 16:28:36.225567643          ^
2023-05-28 16:28:36.225568408  
2023-05-28 16:28:36.225569332  *************************************************************
2023-05-28 16:28:36.225570283  ***    End Config Validation Errors                       ***
2023-05-28 16:28:36.225575663  *************************************************************
2023-05-28 16:28:36.707348604  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 27, in <module>
    config: dict[str, any] = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 5, column 3:
      name_of_your_camera: yard_camera ... 
      ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 6, column 5:
        ffmpeg:

^
2023-05-28 16:28:36.880173243  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-05-28 16:28:37.366741618  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped

**Comment by Richfa** [comment]
worked it out it was just the config happy days

**Comment by NickM-27** [comment]
Thanks for updating, so everything is working as far as this issue is concerned?
