### ISSUE TITLE
[Support]: Unable to start container on Debian

### ISSUE THREAD

**Issue by tedski** [blakeblackshear/frigate#6655]
### Describe the problem you are having

I am attempting to set up Frigate for the first time on Debian.  I am starting as simple as possible, following the [installation documentation](https://docs.frigate.video/frigate/installation/).  If I start an unpriveleged container, it fails with a numpy import error (see Relevant log output section).  If I attempt to run the container as privileged, the container fails to start due to an issue with the `CAP_PERFMON` privilege.  I am running an up to date system (latest docker, latest debian, etc).

My docker command that yields the relevant log output:
```
$ docker run --rm \
> --name frigate \
> --mount type=tmpfs,target=/tmp/cache/tmpfs-size=1000000000 \
> --device /dev/bus/usb:/dev/bus/usb \
> --shm-size=64m \
> -v /srv/docker/frigate/config.yml:/config/config.yml \
> -v /srv/docker/frigate/data:/media/frigate \
> -v /etc/localtime:/etc/localtime:ro \
> -e FRIGATE_RTSP_PASSWORD='password' \
> -p 5000:5000 \
> -p 8554:8554 \
> -p 8555:8555/tcp \
> -p 8555:8555/udp \
> ghcr.io/blakeblackshear/frigate:stable
```

### Version

stable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  main_gate: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://172.16.27.20:554/rtsp # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-05-30 17:20:29.102189656  [INFO] Preparing go2rtc config...
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
2023-05-30 17:20:29.105065042  [INFO] Starting Frigate...
s6-rc: info: service legacy-services: starting
2023-05-30 17:20:29.107894216  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-05-30 17:20:29.121352820  2023/05/30 17:20:29 [alert] 134#134: pthread_create() failed (1: Operation not permitted)
2023-05-30 17:20:29.121359891  2023/05/30 17:20:29 [alert] 137#137: pthread_create() failed (1: Operation not permitted)
2023-05-30 17:20:29.121691239  2023/05/30 17:20:29 [alert] 136#136: pthread_create() failed (1: Operation not permitted)
2023-05-30 17:20:29.122450599  2023/05/30 17:20:29 [alert] 135#135: pthread_create() failed (1: Operation not permitted)
2023-05-30 17:20:29.163454979  2023/05/30 17:20:29 [alert] 116#116: worker process 134 exited with fatal code 2 and cannot be respawned
2023-05-30 17:20:29.163461130  2023/05/30 17:20:29 [alert] 116#116: worker process 136 exited with fatal code 2 and cannot be respawned
2023-05-30 17:20:29.163463380  2023/05/30 17:20:29 [alert] 116#116: worker process 137 exited with fatal code 2 and cannot be respawned
2023-05-30 17:20:29.179294647  2023/05/30 17:20:29 [alert] 116#116: worker process 135 exited with fatal code 2 and cannot be respawned
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 10, in <module>
    from frigate.ffmpeg_presets import parse_preset_hardware_acceleration_encode
  File "/opt/frigate/frigate/ffmpeg_presets.py", line 10, in <module>
    from frigate.util import vainfo_hwaccel
  File "/opt/frigate/frigate/util.py", line 19, in <module>
    import cv2
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
2023-05-30 17:20:29.275087402  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-05-30 17:20:29.423988186  OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
2023-05-30 17:20:29.423993931  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
2023-05-30 17:20:29.423996551  OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
2023-05-30 17:20:29.423998556  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
2023-05-30 17:20:29.424000806  OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
2023-05-30 17:20:29.424002807  OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
2023-05-30 17:20:29.426174812  Traceback (most recent call last):
2023-05-30 17:20:29.426179561    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-05-30 17:20:29.426353300      return _run_code(code, main_globals, None,
2023-05-30 17:20:29.426371077    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-05-30 17:20:29.426465109      exec(code, run_globals)
2023-05-30 17:20:29.426489511    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-05-30 17:20:29.426572757      from frigate.app import FrigateApp
2023-05-30 17:20:29.426576089    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-05-30 17:20:29.426660115      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-05-30 17:20:29.426663332    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-05-30 17:20:29.426766596      from frigate.config import FrigateConfig
2023-05-30 17:20:29.426819750    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-05-30 17:20:29.426887888      import matplotlib.pyplot as plt
2023-05-30 17:20:29.426904105    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 108, in <module>
2023-05-30 17:20:29.427212034      import numpy
2023-05-30 17:20:29.427229196    File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 144, in <module>
2023-05-30 17:20:29.427391777      from . import core
2023-05-30 17:20:29.427395521    File "/usr/local/lib/python3.9/dist-packages/numpy/core/__init__.py", line 23, in <module>
2023-05-30 17:20:29.427485137      from . import multiarray
2023-05-30 17:20:29.427501584    File "/usr/local/lib/python3.9/dist-packages/numpy/core/multiarray.py", line 10, in <module>
2023-05-30 17:20:29.427579051      from . import overrides
2023-05-30 17:20:29.427650108    File "/usr/local/lib/python3.9/dist-packages/numpy/core/overrides.py", line 6, in <module>
2023-05-30 17:20:29.427735351      from numpy.core._multiarray_umath import (
2023-05-30 17:20:29.427738144  KeyboardInterrupt
2023-05-30 17:20:29.470201376  [INFO] Service Frigate exited with code 256 (by signal 2)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-05-30 17:20:29.478579022  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-05-30 17:20:29.480458980  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
n/a
```

### Frigate stats

```json
n/a
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Dahua

### Any other information that may be helpful
```
$ cat /etc/debian_version
11.7
```

```
$ uname -a
Linux nucleus 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
```

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:22:47 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          24.0.1
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       463850e
  Built:            Fri May 19 18:06:34 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
When running with `--privileged`:
```
$ docker run --rm --name frigate --mount type=tmpfs,target=/tmp/cache/tmpfs-size=1000000000 --device /dev/bus/usb:/dev/bus/usb --shm-size=64m -v /srv/docker/frigate/config.yml:/config/config.yml -v /srv/docker/frigate/data:/media/frigate -v /etc/localtime:/etc/localtime:ro -e FRIGATE_RTSP_PASSWORD='password' -p 5000:5000 -p 8554:8554 -p 8555:8555/tcp -p 8555:8555/udp --privileged ghcr.io/blakeblackshear/frigate:stable
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: container_linux.go:349: starting container process caused "unknown capability \"CAP_PERFMON\"": unknown.
```

**Comment by tedski** [comment]
> This is usually due to running on 32 bit or using an outdated version of docker

I saw that in the issues history, but I'm running latest docker on a 64-bit OS (see "Any other information that may be helpful" section in my original comment).  I'm running Debian Bullseye (updated) x86_64 with Docker Engine v24.0.1 (latest).

**Comment by tedski** [comment]
@NickM-27 any other ideas if I've confirmed this is 64-bit and latest Docker?

**Comment by NickM-27** [comment]
I'm really not sure unfortunately, maybe @blakeblackshear has other ideas

**Comment by tedski** [comment]
A bit of a development on this one from my side.  It seems the default Seccomp profile is too restrictive for the container.  I have not been able to figure out why running as privileged doesn't work.  It appears the bug in runc has been solved and shipped in latest docker, but CAP_PERFMON still causes issues.  I will need to whittle away at the default Seccomp profile to figure out which syscalls are being blocked so I can grant them without using `--security-opt seccomp=unconfined` (too permissive).

**Comment by blakeblackshear** [comment]
I don't have any ideas either. I don't understand why others wouldn't be seeing this issue.

**Comment by mnl1121** [comment]
I have this exact same issue when updating to version .12. This does not happen when using .11.1

**Comment by tedski** [comment]
Thanks to @mnl1121's information in #6708, I was able to notice that the version of `runc` in his fully updated Docker install was `1.1.7` while my install was showing `1.0.0`.  This was confusing as `docker-ce` ships with its own `runc` bundled in `containerd.io` and that package was up to date.  However, due to reasons not relevant to this issue, my system had a very old version of `runc` built from archives through system automation from years gone by.  Cleaning this up has resolved this issue.

For future readers, ensure not only Docker, but all of its dependencies are up to date, perhaps by installing Docker on a clean system and comparing the output of `docker version`.
