### ISSUE TITLE
[Detector Support]: ValueError with OpenVINO

### ISSUE THREAD

**Issue by chatziko** [blakeblackshear/frigate#6855]
### Describe the problem you are having

I use the OpenVINO detector, with the default config from the documentation, and occasionally get the ValueError shown in the log below. I can't easily reproduce it, it happens once in a while.

Note that I use a recent version (dev-b668102, in order to try go2rtc 1.5.0). Not sure whether this is relevant.

### Version

dev-b668102

### Frigate config file

```yaml
detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

cameras:
  frigate_livingroom:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://<camera-direct-url>
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy    # enabled audio in recordings
    motion:
      mask:
        - 235,23,233,0,0,0,0,22
    detect:
      width: 640
      height: 360

detect:
  enabled: true
  fps: 5
```

### docker-compose file or Docker CLI command

```yaml
Not used.
```

### Relevant log output

```shell
2023-06-20 08:12:19.897913818  [INFO] Starting Frigate...
2023-06-20 08:12:21.124432433  [2023-06-20 11:12:21] frigate.app                    INFO    : Starting Frigate (0.13.0-b668102)
2023-06-20 08:12:21.125192363  [2023-06-20 11:12:21] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-06-20 08:12:21.151324559  [2023-06-20 11:12:21] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-06-20 08:12:21.157911710  [2023-06-20 11:12:21] peewee_migrate.logs            INFO    : Starting migrations
2023-06-20 08:12:21.162057360  [2023-06-20 11:12:21] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-06-20 08:12:21.166804039  [2023-06-20 11:12:21] frigate.app                    INFO    : Recording process started: 299
2023-06-20 08:12:21.169321137  [2023-06-20 11:12:21] frigate.app                    INFO    : go2rtc process pid: 89
2023-06-20 08:12:21.199378666  [2023-06-20 11:12:21] frigate.app                    INFO    : Output process started: 309
2023-06-20 08:12:21.206707373  [2023-06-20 11:12:21] frigate.app                    INFO    : Camera processor started for frigate_livingroom: 313
2023-06-20 08:12:21.207290081  [2023-06-20 11:12:21] detector.ov                    INFO    : Starting detection process: 308
2023-06-20 08:12:21.213177648  [2023-06-20 11:12:21] frigate.app                    INFO    : Camera processor started for frigate_doorbell: 315
2023-06-20 08:12:21.219554563  [2023-06-20 11:12:21] frigate.app                    INFO    : Capture process started for frigate_livingroom: 317
2023-06-20 08:12:21.226276168  [2023-06-20 11:12:21] frigate.app                    INFO    : Capture process started for frigate_doorbell: 318
2023-06-20 08:12:21.317367016  [2023-06-20 11:12:21] frigate.comms.dispatcher       INFO    : Turning off recordings for frigate_livingroom
2023-06-20 08:12:21.328553261  [2023-06-20 11:12:21] frigate.comms.dispatcher       INFO    : Turning off detection for frigate_livingroom
2023-06-20 08:12:21.338395833  [2023-06-20 11:12:21] frigate.comms.dispatcher       INFO    : Turning on detection for frigate_livingroom
2023-06-20 08:12:25.885334948  [2023-06-20 11:12:25] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-06-20 08:12:25.885495709  [2023-06-20 11:12:25] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-06-20 08:12:25.885589286  [2023-06-20 11:12:25] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2023-06-20 08:26:49.331179467  frame.shape: (540, 640)
2023-06-20 08:26:49.331183353  region: (375, 173, 525, 323)
2023-06-20 08:26:49.332118452  Process camera_processor:frigate_livingroom:
2023-06-20 08:26:49.333028142  Traceback (most recent call last):
2023-06-20 08:26:49.333030792    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-06-20 08:26:49.333032103      self.run()
2023-06-20 08:26:49.333041106    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-06-20 08:26:49.333042513      self._target(*self._args, **self._kwargs)
2023-06-20 08:26:49.333043501    File "/opt/frigate/frigate/video.py", line 483, in track_camera
2023-06-20 08:26:49.333056981      process_frames(
2023-06-20 08:26:49.333057905    File "/opt/frigate/frigate/video.py", line 842, in process_frames
2023-06-20 08:26:49.333058943      detect(
2023-06-20 08:26:49.333059882    File "/opt/frigate/frigate/video.py", line 553, in detect
2023-06-20 08:26:49.333060798      tensor_input = create_tensor_input(frame, model_config, region)
2023-06-20 08:26:49.333061657    File "/opt/frigate/frigate/video.py", line 102, in create_tensor_input
2023-06-20 08:26:49.333077284      cropped_frame = yuv_region_2_bgr(frame, region)
2023-06-20 08:26:49.333078793    File "/opt/frigate/frigate/util.py", line 567, in yuv_region_2_bgr
2023-06-20 08:26:49.333080679      yuv_cropped_frame = yuv_crop_and_resize(frame, region)
2023-06-20 08:26:49.333082594    File "/opt/frigate/frigate/util.py", line 333, in yuv_crop_and_resize
2023-06-20 08:26:49.333098612      yuv_cropped_frame[
2023-06-20 08:26:49.333100228  ValueError: could not broadcast input array from shape (148,150) into shape (148,148)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

Other

**Comment by NickM-27** [comment]
Just wanted to make it clear there is no need to run the dev build to use go2rtc 1.5.0, frigate supports using custom versions of go2rtc in 0.12

Will look at this and see.

**Comment by chatziko** [comment]
> Just wanted to make it clear there is no need to run the dev build to use go2rtc 1.5.0, frigate supports using custom versions of go2rtc in 0.12

Thanks for the quick response. I briefly tried to launch a custom go2rtc and setup its streams in frigate. It worked, but then my understanding is that frigate didn't know that the stream comes from go2rtc so it couldn't use WebRTC in the UI. Same for frigate-hass-card, no WebRTC there either.

Is there maybe a better way to use external go2rtc so that frigate is aware of it?

**Comment by NickM-27** [comment]
It's covered in the docs https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by chatziko** [comment]
Oh, I missed it, thanks a lot!

I'd suggest adding a link to the [go2rtc page](https://docs.frigate.video/guides/configuring_go2rtc), this is where one would expect to find such info.

**Comment by Codel1417** [comment]
I am having a similar issue but with a RuntimeError.
Current version: 0.12.1.
Doorbell is reolink, LivingRoom & Packages is wyze through the docker bridge addon, and mainsail is mjpeg. Before detection crashes all cameras work fine. Same exception stacktrace every time.
```2023-06-22 22:32:59.164573439  [2023-06-22 18:32:59] peewee_migrate                 INFO    : Starting migrations
2023-06-22 22:32:59.170614064  [2023-06-22 18:32:59] peewee_migrate                 INFO    : There is nothing to migrate
2023-06-22 22:32:59.200658479  [2023-06-22 18:32:59] frigate.app                    INFO    : Output process started: 302
2023-06-22 22:32:59.206548011  [2023-06-22 18:32:59] frigate.app                    INFO    : Camera processor started for Packages: 304
2023-06-22 22:32:59.211694739  [2023-06-22 18:32:59] frigate.app                    INFO    : Camera processor started for LivingRoom: 306
2023-06-22 22:32:59.217713354  [2023-06-22 18:32:59] frigate.app                    INFO    : Camera processor started for Doorbell: 307
2023-06-22 22:32:59.222768605  [2023-06-22 18:32:59] frigate.app                    INFO    : Camera processor started for mainsail: 309
2023-06-22 22:32:59.227811706  [2023-06-22 18:32:59] frigate.app                    INFO    : Capture process started for Packages: 310
2023-06-22 22:32:59.235022497  [2023-06-22 18:32:59] frigate.app                    INFO    : Capture process started for LivingRoom: 311
2023-06-22 22:32:59.235659815  [2023-06-22 18:32:59] detector.ov                    INFO    : Starting detection process: 301
2023-06-22 22:32:59.248833758  [2023-06-22 18:32:59] frigate.app                    INFO    : Capture process started for Doorbell: 313
2023-06-22 22:32:59.260524929  [2023-06-22 18:32:59] frigate.app                    INFO    : Capture process started for mainsail: 315
2023-06-22 22:33:00.004636964  172.30.32.1 - - [22/Jun/2023:18:33:00 -0400] "GET /api/Packages/latest.jpg?h=414 HTTP/1.1" 200 12350 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:00.058687705  172.30.32.1 - - [22/Jun/2023:18:33:00 -0400] "GET /api/Doorbell/latest.jpg?h=552 HTTP/1.1" 200 17823 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:06.223377430  172.30.32.1 - - [22/Jun/2023:18:33:06 -0400] "GET /api/stats HTTP/1.1" 200 2998 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:07.050964788  [INFO] Starting go2rtc healthcheck service...
2023-06-22 22:33:08.874240641  172.30.32.2 - - [22/Jun/2023:18:33:08 -0400] "GET /api/config HTTP/1.1" 200 12668 "http://floofassistant.local:8123/api/hassio_ingress/iwmz2qZkxd7XSJ2ZdhlrFCP3ZfY-RWiLhcQqJL1P-0Q//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "192.168.50.189, 172.30.32.1"
2023-06-22 22:33:09.902378637  172.30.32.1 - - [22/Jun/2023:18:33:09 -0400] "GET /api/Packages/latest.jpg?h=414 HTTP/1.1" 200 12350 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:10.038760218  172.30.32.1 - - [22/Jun/2023:18:33:10 -0400] "GET /api/Doorbell/latest.jpg?h=414 HTTP/1.1" 200 12350 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:15.388669601  172.30.32.1 - - [22/Jun/2023:18:33:15 -0400] "GET /api/stats HTTP/1.1" 200 3041 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:19.938430695  172.30.32.1 - - [22/Jun/2023:18:33:19 -0400] "GET /api/Doorbell/latest.jpg?h=414 HTTP/1.1" 200 12350 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:20.058927486  172.30.32.1 - - [22/Jun/2023:18:33:20 -0400] "GET /api/Packages/latest.jpg?h=414 HTTP/1.1" 200 12350 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:21.204501999  [2023-06-22 18:33:21] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-06-22 22:33:21.204526892  [2023-06-22 18:33:21] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-06-22 22:33:21.204533070  [2023-06-22 18:33:21] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2023-06-22 22:33:24.132433984  172.30.32.1 - - [22/Jun/2023:18:33:24 -0400] "GET /api/stats HTTP/1.1" 200 3001 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:30.089385246  172.30.32.1 - - [22/Jun/2023:18:33:30 -0400] "GET /api/Packages/latest.jpg?h=414 HTTP/1.1" 200 77331 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:30.405131833  172.30.32.1 - - [22/Jun/2023:18:33:30 -0400] "GET /api/Doorbell/latest.jpg?h=414 HTTP/1.1" 200 32055 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:33.426789036  172.30.32.1 - - [22/Jun/2023:18:33:33 -0400] "GET /api/stats HTTP/1.1" 200 3015 "-" "HomeAssistant/2023.6.2 aiohttp/3.8.4 Python/3.11" "-"
2023-06-22 22:33:35.323491392  Process detector:ov:
2023-06-22 22:33:35.324761996  Traceback (most recent call last):
2023-06-22 22:33:35.324767086    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-06-22 22:33:35.324768207      self.run()
2023-06-22 22:33:35.324769502    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-06-22 22:33:35.324770661      self._target(*self._args, **self._kwargs)
2023-06-22 22:33:35.324771947    File "/opt/frigate/frigate/object_detection.py", line 121, in run_detector
2023-06-22 22:33:35.324808681      detections = object_detector.detect_raw(input_frame)
2023-06-22 22:33:35.324811228    File "/opt/frigate/frigate/object_detection.py", line 71, in detect_raw
2023-06-22 22:33:35.324812625      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-06-22 22:33:35.324813918    File "/opt/frigate/frigate/detectors/plugins/openvino.py", line 84, in detect_raw
2023-06-22 22:33:35.324846603      infer_request.infer([tensor_input])
2023-06-22 22:33:35.324848231    File "/usr/local/lib/python3.9/dist-packages/openvino/runtime/ie_api.py", line 151, in infer
2023-06-22 22:33:35.324849405      return super().infer(
2023-06-22 22:33:35.324850408  RuntimeError: clWaitForEvents
2023-06-22 22:33:39.632105773  [2023-06-22 18:33:39] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-06-22 22:33:39.654335124  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-06-22 22:33:39.668717761  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-06-22 22:33:39.671303584  [2023-06-22 18:33:39] frigate.app                    INFO    : Stopping...
2023-06-22 22:33:39.671974302  [2023-06-22 18:33:39] frigate.events                 INFO    : Exiting event cleanup...
s6-rc: info: service nginx-log successfully stopped
2023-06-22 22:33:39.679127458  [2023-06-22 18:33:39] frigate.storage                INFO    : Exiting storage maintainer...
2023-06-22 22:33:39.679131744  [2023-06-22 18:33:39] frigate.record                 INFO    : Exiting recording cleanup...
2023-06-22 22:33:39.679133309  [2023-06-22 18:33:39] frigate.record                 INFO    : Exiting recording maintenance...
2023-06-22 22:33:39.681447493  [2023-06-22 18:33:39] frigate.stats                  INFO    : Exiting stats emitter...
2023-06-22 22:33:39.686920801  [2023-06-22 18:33:39] frigate.watchdog               INFO    : Exiting watchdog...
2023-06-22 22:33:39.686925440  [2023-06-22 18:33:39] frigate.object_processing      INFO    : Exiting object processor...
2023-06-22 22:33:40.007499246  [2023-06-22 18:33:40] frigate.comms.ws               INFO    : Exiting websocket client...
2023-06-22 22:33:40.173715366  [2023-06-22 18:33:40] frigate.events                 INFO    : Exiting event processor...
2023-06-22 22:33:40.174482161  [2023-06-22 18:33:40] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-06-22 22:33:40.178345182  [2023-06-22 18:33:40] watchdog.LivingRoom            INFO    : Terminating the existing ffmpeg process...
2023-06-22 22:33:40.178667542  [2023-06-22 18:33:40] watchdog.LivingRoom            INFO    : Waiting for ffmpeg to exit gracefully...
2023-06-22 22:33:40.180135225  [2023-06-22 18:33:40] watchdog.Doorbell              INFO    : Terminating the existing ffmpeg process...
2023-06-22 22:33:40.180139991  [2023-06-22 18:33:40] watchdog.Doorbell              INFO    : Waiting for ffmpeg to exit gracefully...
2023-06-22 22:33:40.180532177  [2023-06-22 18:33:40] watchdog.Packages              INFO    : Terminating the existing ffmpeg process...
2023-06-22 22:33:40.180824350  [2023-06-22 18:33:40] watchdog.Packages              INFO    : Waiting for ffmpeg to exit gracefully...
2023-06-22 22:33:40.181313081  [2023-06-22 18:33:40] watchdog.mainsail              INFO    : Terminating the existing ffmpeg process...
2023-06-22 22:33:40.181687808  [2023-06-22 18:33:40] watchdog.mainsail              INFO    : Waiting for ffmpeg to exit gracefully...
2023-06-22 22:33:40.612234111  [2023-06-22 18:33:40] frigate.video                  INFO    : Packages: exiting subprocess
2023-06-22 22:33:40.988553285  [2023-06-22 18:33:40] frigate.output                 INFO    : exiting output process...
2023-06-22 22:33:41.066111405  [2023-06-22 18:33:41] frigate.video                  INFO    : Doorbell: exiting subprocess
2023-06-22 22:33:44.924676303  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 24 leaked shared_memory objects to clean up at shutdown
2023-06-22 22:33:44.924680576    warnings.warn('resource_tracker: There appear to be %d '
2023-06-22 22:33:44.927102280  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-06-22 22:33:44.929636554  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-06-22 22:33:44.936917209  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

```#yaml-language-server: $schema=http://ccab4aaf-frigate:5000/api/config/schema.json
mqtt:
  host: 192.168.50.10
  user: frigate
  password: frigate

go2rtc:
  streams:
    mainsail: "ffmpeg:http://192.168.50.100/webcam/?action=stream#video=h264#hardware" # <- use hardware acceleration to create an h264 stream usable for other components.
cameras:
  Packages:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.50.10:8554/packages
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 10
  LivingRoom:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.50.10:8554/living-room-cam
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 10
  Doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@192.168.50.215:554
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
      fps: 10
  mainsail:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mainsail
          roles:
            - record
      
detectors:
  ov:
    type: openvino
    device: GPU
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt
ffmpeg:
  hwaccel_args: preset-vaapi

birdseye:
  enabled: True
  mode: continuous
  restream: True
record:
  enabled: True
  events:
    retain:
      default: 10```

**Comment by yeahme49** [comment]
Having the same issue on 0.13.0-EF14A43 using OpenVINO.
```
2023-06-28 19:38:35.029452366  [INFO] Preparing Frigate...
2023-06-28 19:38:35.034479533  [INFO] Starting Frigate...
2023-06-28 19:38:36.520665717  [2023-06-28 19:38:36] frigate.app                    INFO    : Starting Frigate (0.13.0-ef14a43)
2023-06-28 19:38:36.542315916  [2023-06-28 19:38:36] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-06-28 19:38:36.549125590  [2023-06-28 19:38:36] peewee_migrate.logs            INFO    : Starting migrations
2023-06-28 19:38:36.554079741  [2023-06-28 19:38:36] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-06-28 19:38:36.586885023  [2023-06-28 19:38:36] frigate.app                    INFO    : Recording process started: 285
2023-06-28 19:38:36.589131040  [2023-06-28 19:38:36] frigate.app                    INFO    : go2rtc process pid: 99
2023-06-28 19:38:36.622249285  [2023-06-28 19:38:36] frigate.app                    INFO    : Output process started: 295
2023-06-28 19:38:36.642538635  [2023-06-28 19:38:36] detector.vino                  INFO    : Starting detection process: 294
2023-06-28 19:38:36.643026968  [2023-06-28 19:38:36] frigate.app                    INFO    : Camera processor started for front_porch: 299
2023-06-28 19:38:36.653188276  [2023-06-28 19:38:36] frigate.app                    INFO    : Camera processor started for driveway: 301
2023-06-28 19:38:36.662683886  [2023-06-28 19:38:36] frigate.app                    INFO    : Capture process started for front_porch: 303
2023-06-28 19:38:36.686064816  [2023-06-28 19:38:36] frigate.app                    INFO    : Capture process started for driveway: 305
2023-06-28 19:38:46.317532036  [2023-06-28 19:38:46] frigate.detectors.plugins.openvino INFO    : Model Input Shape: {1, 300, 300, 3}
2023-06-28 19:38:46.317535130  [2023-06-28 19:38:46] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: {1, 1, 100, 7}
2023-06-28 19:38:46.317538486  [2023-06-28 19:38:46] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2023-06-28 19:38:46.472372244  frame.shape: (1620, 1920)
2023-06-28 19:38:46.472389009  region: (1024, 47, 1174, 197)
2023-06-28 19:38:46.472957690  Process camera_processor:driveway:
2023-06-28 19:38:46.473662499  Traceback (most recent call last):
2023-06-28 19:38:46.473771403    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-06-28 19:38:46.473773185      self.run()
2023-06-28 19:38:46.473907568    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-06-28 19:38:46.473909718      self._target(*self._args, **self._kwargs)
2023-06-28 19:38:46.474015070    File "/opt/frigate/frigate/video.py", line 493, in track_camera
2023-06-28 19:38:46.474016726      process_frames(
2023-06-28 19:38:46.474018011    File "/opt/frigate/frigate/video.py", line 853, in process_frames
2023-06-28 19:38:46.474019071      detect(
2023-06-28 19:38:46.474020271    File "/opt/frigate/frigate/video.py", line 563, in detect
2023-06-28 19:38:46.474021501      tensor_input = create_tensor_input(frame, model_config, region)
2023-06-28 19:38:46.474033966    File "/opt/frigate/frigate/video.py", line 102, in create_tensor_input
2023-06-28 19:38:46.474035581      cropped_frame = yuv_region_2_bgr(frame, region)
2023-06-28 19:38:46.474037203    File "/opt/frigate/frigate/util.py", line 567, in yuv_region_2_bgr
2023-06-28 19:38:46.474038498      yuv_cropped_frame = yuv_crop_and_resize(frame, region)
2023-06-28 19:38:46.474039607    File "/opt/frigate/frigate/util.py", line 333, in yuv_crop_and_resize
2023-06-28 19:38:46.474049148      yuv_cropped_frame[
2023-06-28 19:38:46.474072416  ValueError: could not broadcast input array from shape (148,150) into shape (148,148)
2023-06-28 19:38:48.593099040  frame.shape: (1620, 1920)
2023-06-28 19:38:48.593101900  region: (1770, 930, 1920, 1080)
2023-06-28 19:38:48.593896086  Process camera_processor:front_porch:
2023-06-28 19:38:48.594432555  Traceback (most recent call last):
2023-06-28 19:38:48.594563336    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-06-28 19:38:48.594565181      self.run()
2023-06-28 19:38:48.594566556    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-06-28 19:38:48.594567835      self._target(*self._args, **self._kwargs)
2023-06-28 19:38:48.594569051    File "/opt/frigate/frigate/video.py", line 493, in track_camera
2023-06-28 19:38:48.594570139      process_frames(
2023-06-28 19:38:48.594571413    File "/opt/frigate/frigate/video.py", line 853, in process_frames
2023-06-28 19:38:48.594572481      detect(
2023-06-28 19:38:48.594573684    File "/opt/frigate/frigate/video.py", line 563, in detect
2023-06-28 19:38:48.594574920      tensor_input = create_tensor_input(frame, model_config, region)
2023-06-28 19:38:48.594576059    File "/opt/frigate/frigate/video.py", line 102, in create_tensor_input
2023-06-28 19:38:48.594577224      cropped_frame = yuv_region_2_bgr(frame, region)
2023-06-28 19:38:48.594578392    File "/opt/frigate/frigate/util.py", line 567, in yuv_region_2_bgr
2023-06-28 19:38:48.594580058      yuv_cropped_frame = yuv_crop_and_resize(frame, region)
2023-06-28 19:38:48.594581264    File "/opt/frigate/frigate/util.py", line 333, in yuv_crop_and_resize
2023-06-28 19:38:48.594595259      yuv_cropped_frame[
2023-06-28 19:38:48.594596720  ValueError: could not broadcast input array from shape (148,150) into shape (148,148)
```

**Comment by Steve-Tech** [comment]
I mentioned it in #6867 but I'll put it here too, commit d81dd60 seems to break OpenVINO, build `dev-0f1cf67` is the last working build.

**Comment by chatziko** [comment]
> I mentioned it in #6867 but I'll put it here too, commit [d81dd60](https://github.com/blakeblackshear/frigate/commit/d81dd60fefda1c05a968047b8296e62df65df9dc) seems to break OpenVINO, build `dev-0f1cf67` is the last working build.


This sounds consistent with my observations, I reported the issue using dev-b668102, but later went back to 0.12.1 and I don't think I've had the issue since.

**Comment by RaylightGames** [comment]
> I mentioned it in #6867 but I'll put it here too, commit [d81dd60](https://github.com/blakeblackshear/frigate/commit/d81dd60fefda1c05a968047b8296e62df65df9dc) seems to break OpenVINO, build `dev-0f1cf67` is the last working build.

the same behaviour for me. I'm keeping old build until is fixed, thanks

**Comment by xfaustus** [comment]
> I mentioned it in #6867 but I'll put it here too, commit [d81dd60](https://github.com/blakeblackshear/frigate/commit/d81dd60fefda1c05a968047b8296e62df65df9dc) seems to break OpenVINO, build `dev-0f1cf67` is the last working build.

For me latest working build is `dev-3256984`. Using  `dev-0f1cf67` i already see the "Valuerrors"

**Comment by NickM-27** [comment]
Those value errors are unrelated to the ones being discussed in this issue

**Comment by NickM-27** [comment]
I am mainly laying this out to reference / for other contributors. This is happening because in [d81dd60](https://github.com/blakeblackshear/frigate/commit/d81dd60fefda1c05a968047b8296e62df65df9dc) the regions can now be half the size of the model input (300x300 in openvino case)

However, the yuv crops must be a multiple of 4 in resolution:

https://github.com/blakeblackshear/frigate/blob/12d4a47e3d97248f961858bbf5d83a5fdf8386a8/frigate/util.py#L323-L326

150 is naturally not divisible by 4, so it fails.

Should be a simple fix to ensure that the min_region_size is divisible by 4

**Comment by xfaustus** [comment]
> I am mainly laying this out to reference / for other contributors. This is happening because in [d81dd60](https://github.com/blakeblackshear/frigate/commit/d81dd60fefda1c05a968047b8296e62df65df9dc) the regions can now be half the size of the model input (300x300 in openvino case)
> 
> However, the yuv crops must be a multiple of 4 in resolution:
> 
> https://github.com/blakeblackshear/frigate/blob/12d4a47e3d97248f961858bbf5d83a5fdf8386a8/frigate/util.py#L323-L326
> 
> 150 is naturally not divisible by 4, so it fails.
> 
> Should be a simple fix to ensure that the min_region_size is divisible by 4

Hello Nick thanks for the fix.
I saw your code and would kindly suggest 3 faster  way of round up 4.

half  = int((half+3)/4)*4

half = ((half+3)>>2)<<2

half = (half+3)& ~3

Thanks again for all your great work on the project
