### ISSUE TITLE
[Support]: Database issue for Frigate in HASS on RPI

### ISSUE THREAD

**Issue by sebastian-tischer** [blakeblackshear/frigate#6976]
### Describe the problem you are having

Hi everyone,

until the last update of Frigate (0.12.1) everything ran smooth but since the installation, I constantly get the error in the logs below.

The following is not working:
- Record of events
- Show old records for Camera "Garten"

Further more, the timestamp in the log is 2h off - it shows 12:40 actually it is 14:40 - not sure if this is related.

The camera "Garage" is not connected, the issue there can be ignored.

Thanks a lot and warm regards
Sebastian

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
      host: 192.168.2.109
      port: 1883
      user: hass-mqtt
      password: mqtt
    detectors:
      coral:
        type: edgetpu
        device: usb
    birdseye:
      enabled: True
      width: 1920
      height: 1080
      quality: 15
      mode: continuous
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: True
      max_disappeared: 25
    objects:
      track:
        - person
      filters:
        person:
          min_score: 0.65
          threshold: 0.5
    record:
      enabled: True
      expire_interval: 60
      events:
        pre_capture: 5
        post_capture: 5
        objects:
          - person
        retain:
          default: 5
          mode: motion
          objects:
            person: 15
    
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 5
        objects:
          person: 15
    
    rtmp:
      enabled: True
    cameras:
      IN-9408-Eingang:
        ffmpeg:
          inputs:
            - path: rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.127/livestream/12
              roles:
                - detect
                - record
                - rtmp
    
      IN-9408-Garten:
        ffmpeg:
          inputs:
            - path: rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.128/livestream/12
              roles:
                - detect
                - record
                - rtmp
  
      IN-9408-Garage:
        ffmpeg:
          inputs:
            - path: rtsp://operator-kamera:qyw8xU8mkr.zh4R7znL3@192.168.2.141/livestream/12
              roles:
                - detect
                - record
                - rtmp
```

### Relevant log output

```shell
2023-07-01 12:40:51.803131081  Exception in thread event_processor:
2023-07-01 12:40:51.803143154  Traceback (most recent call last):
2023-07-01 12:40:51.803146728    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3237, in execute_sql
2023-07-01 12:40:51.803161821      cursor.execute(sql, params or ())
2023-07-01 12:40:51.803165543  sqlite3.DatabaseError: database disk image is malformed
2023-07-01 12:40:51.803167450  
2023-07-01 12:40:51.803170117  During handling of the above exception, another exception occurred:
2023-07-01 12:40:51.803264225  
2023-07-01 12:40:51.803267984  Traceback (most recent call last):
2023-07-01 12:40:51.803272169    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-07-01 12:40:51.803273928      self.run()
2023-07-01 12:40:51.803276206    File "/opt/frigate/frigate/events.py", line 64, in run
2023-07-01 12:40:51.803278984      Event.update(end_time=Event.start_time + 30).where(
2023-07-01 12:40:51.803281539    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 1962, in inner
2023-07-01 12:40:51.803503903      return method(self, database, *args, **kwargs)
2023-07-01 12:40:51.803513125    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2033, in execute
2023-07-01 12:40:51.804524631      return self._execute(database)
2023-07-01 12:40:51.804660794    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2552, in _execute
2023-07-01 12:40:51.806969297      return self.handle_result(database, cursor)
2023-07-01 12:40:51.807095108    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2563, in handle_result
2023-07-01 12:40:51.808666024      return database.rows_affected(cursor)
2023-07-01 12:40:51.808824278    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3753, in rows_affected
2023-07-01 12:40:51.818227807      return cursor.rowcount
2023-07-01 12:40:51.818853269    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 94, in rowcount
2023-07-01 12:40:51.820152286      self._wait()
2023-07-01 12:40:51.820465517    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 63, in _wait
2023-07-01 12:40:51.821276159      raise self._exc
2023-07-01 12:40:51.821397859    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 178, in execute
2023-07-01 12:40:51.822030654      cursor = self.database._execute(obj.sql, obj.params, obj.commit)
2023-07-01 12:40:51.822142781    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3244, in execute_sql
2023-07-01 12:40:51.826491630      self.commit()
2023-07-01 12:40:51.826628811    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3010, in __exit__
2023-07-01 12:40:51.833104207      reraise(new_type, new_type(exc_value, *exc_args), traceback)
2023-07-01 12:40:51.833254369    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
2023-07-01 12:40:51.833973680      raise value.with_traceback(tb)
2023-07-01 12:40:51.834086399    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3237, in execute_sql
2023-07-01 12:40:51.835711405      cursor.execute(sql, params or ())
2023-07-01 12:40:51.836060543  peewee.DatabaseError: database disk image is malformed
2023-07-01 12:40:53.240100275  [2023-07-01 14:40:53] frigate.video                  ERROR   : IN-9408-Garten: Unable to read frames from ffmpeg process.
2023-07-01 12:40:53.243189459  [2023-07-01 14:40:53] frigate.video                  ERROR   : IN-9408-Garten: ffmpeg process is not running. exiting capture thread...
2023-07-01 12:40:53.989023276  [2023-07-01 14:40:53] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-07-01 12:40:55.261927908  [2023-07-01 14:40:55] frigate.video                  ERROR   : IN-9408-Garage: Unable to read frames from ffmpeg process.
2023-07-01 12:40:55.263107224  [2023-07-01 14:40:55] frigate.video                  ERROR   : IN-9408-Garage: ffmpeg process is not running. exiting capture thread...
2023-07-01 12:40:55.498340676  [INFO] Starting go2rtc healthcheck service...
2023-07-01 12:40:57.262486865  [2023-07-01 14:40:57] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/IN-9408-Garten-20230701144053.mp4
2023-07-01 12:40:58.711357793  172.30.32.1 - - [01/Jul/2023:14:40:58 +0200] "GET /api/stats HTTP/1.1" 200 2596 "-" "HomeAssistant/2023.6.3 aiohttp/3.8.4 Python/3.11" "-"
2023-07-01 12:40:59.596180565  172.30.32.2 - - [01/Jul/2023:14:40:59 +0200] "GET / HTTP/1.1" 200 6641 "-" "HomeAssistantSupervisor/2023.06.4 aiohttp/3.8.4 Python/3.11" "-"
2023-07-01 12:41:06.690404049  172.30.32.1 - - [01/Jul/2023:14:41:06 +0200] "GET /api/stats HTTP/1.1" 200 2583 "-" "HomeAssistant/2023.6.3 aiohttp/3.8.4 Python/3.11" "-"
2023-07-01 12:41:11.122201809  [2023-07-01 14:41:11] watchdog.IN-9408-Garten        ERROR   : Ffmpeg process crashed unexpectedly for IN-9408-Garten.
2023-07-01 12:41:11.122839679  [2023-07-01 14:41:11] watchdog.IN-9408-Garten        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-07-01 12:41:11.123340294  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [h264 @ 0x55908e3510] error while decoding MB 77 54, bytestream -5
2023-07-01 12:41:11.123872908  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [segment @ 0x559090c9c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-07-01 12:41:11.124844249  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [mp4 @ 0x5590c3f810] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-07-01 12:41:11.125858626  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [mp4 @ 0x5590c3f810] pts has no value
2023-07-01 12:41:11.126069046  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x5590998040] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-07-01 12:41:11.126709879  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x5590998040] Packet is missing PTS
2023-07-01 12:41:11.127576908  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : av_interleaved_write_frame(): Invalid argument
2023-07-01 12:41:11.128065375  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [h264 @ 0x5590908460] error while decoding MB 77 54, bytestream -5
2023-07-01 12:41:11.128420587  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : Finishing stream 2:0 without any data written to it.
2023-07-01 12:41:11.128991181  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x5590998040] Failed to update header with correct duration.
2023-07-01 12:41:11.129410761  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x5590998040] Failed to update header with correct filesize.
2023-07-01 12:41:11.229985468  [2023-07-01 14:41:11] watchdog.IN-9408-Garage        ERROR   : Ffmpeg process crashed unexpectedly for IN-9408-Garage.
2023-07-01 12:41:11.230570951  [2023-07-01 14:41:11] watchdog.IN-9408-Garage        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-07-01 12:41:11.230954051  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garage.detect   ERROR   : [tcp @ 0x556b624e60] Connection to tcp://192.168.2.141:554?timeout=5000000 failed: No route to host
2023-07-01 12:41:11.231461943  [2023-07-01 14:41:11] ffmpeg.IN-9408-Garage.detect   ERROR   : rtsp://*:*@192.168.2.141/livestream/12: No route to host
2023-07-01 12:41:13.096127144  [2023-07-01 14:41:13] frigate.video                  ERROR   : IN-9408-Garten: Unable to read frames from ffmpeg process.
2023-07-01 12:41:13.099051909  [2023-07-01 14:41:13] frigate.video                  ERROR   : IN-9408-Garten: Unable to read frames from ffmpeg process.
2023-07-01 12:41:13.100608325  [2023-07-01 14:41:13] frigate.video                  ERROR   : IN-9408-Garten: Unable to read frames from ffmpeg process.
2023-07-01 12:41:13.102431086  [2023-07-01 14:41:13] frigate.video                  ERROR   : IN-9408-Garten: ffmpeg process is not running. exiting capture thread...
2023-07-01 12:41:14.737101630  172.30.32.1 - - [01/Jul/2023:14:41:14 +0200] "GET /api/stats HTTP/1.1" 200 2646 "-" "HomeAssistant/2023.6.3 aiohttp/3.8.4 Python/3.11" "-"
2023-07-01 12:41:14.882858134  [2023-07-01 14:41:14] frigate.video                  ERROR   : IN-9408-Garage: Unable to read frames from ffmpeg process.
2023-07-01 12:41:14.884131244  [2023-07-01 14:41:14] frigate.video                  ERROR   : IN-9408-Garage: ffmpeg process is not running. exiting capture thread...
2023-07-01 12:41:17.943895654  [2023-07-01 14:41:17] frigate.record                 WARNING : Discarding a corrupt recording segment: /tmp/cache/IN-9408-Garten-20230701144112.mp4
2023-07-01 12:41:21.205604158  [2023-07-01 14:41:21] watchdog.IN-9408-Garten        ERROR   : Ffmpeg process crashed unexpectedly for IN-9408-Garten.
2023-07-01 12:41:21.205618695  [2023-07-01 14:41:21] watchdog.IN-9408-Garten        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-07-01 12:41:21.205624713  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : [segment @ 0x559ba239c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-07-01 12:41:21.208996410  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : [mp4 @ 0x559bb98f20] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-07-01 12:41:21.209805090  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : [mp4 @ 0x559bb98f20] pts has no value
2023-07-01 12:41:21.210739247  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x559baa1970] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
2023-07-01 12:41:21.212026654  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x559baa1970] Packet is missing PTS
2023-07-01 12:41:21.213098326  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : av_interleaved_write_frame(): Invalid argument
2023-07-01 12:41:21.214560227  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : Finishing stream 2:0 without any data written to it.
2023-07-01 12:41:21.215748099  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x559baa1970] Failed to update header with correct duration.
2023-07-01 12:41:21.216942342  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garten.detect   ERROR   : [flv @ 0x559baa1970] Failed to update header with correct filesize.
2023-07-01 12:41:21.269839874  [2023-07-01 14:41:21] watchdog.IN-9408-Garage        ERROR   : Ffmpeg process crashed unexpectedly for IN-9408-Garage.
2023-07-01 12:41:21.271055912  [2023-07-01 14:41:21] watchdog.IN-9408-Garage        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-07-01 12:41:21.271988292  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garage.detect   ERROR   : [tcp @ 0x55af619e60] Connection to tcp://192.168.2.141:554?timeout=5000000 failed: No route to host
2023-07-01 12:41:21.273642318  [2023-07-01 14:41:21] ffmpeg.IN-9408-Garage.detect   ERROR   : rtsp://*:*@192.168.2.141/livestream/12: No route to host
2023-07-01 12:41:22.728560141  172.30.32.1 - - [01/Jul/2023:14:41:22 +0200] "GET /api/stats HTTP/1.1" 200 2647 "-" "HomeAssistant/2023.6.3 aiohttp/3.8.4 Python/3.11" "-"
2023-07-01 12:41:23.140477857  [2023-07-01 14:41:23] frigate.video                  ERROR   : IN-9408-Garten: Unable to read frames from ffmpeg process.
2023-07-01 12:41:23.141182299  [2023-07-01 14:41:23] frigate.video                  ERROR   : IN-9408-Garten: ffmpeg process is not running. exiting capture thread...
2023-07-01 12:41:24.864682655  [2023-07-01 14:41:24] frigate.video                  ERROR   : IN-9408-Garage: Unable to read frames from ffmpeg process.
2023-07-01 12:41:24.865838695  [2023-07-01 14:41:24] frigate.video                  ERROR   : IN-9408-Garage: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
-
```

### Frigate stats

```json
-
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

instar 9408 (PoE)

**Comment by blakeblackshear** [comment]
Are you running off an sd card?

**Comment by sebastian-tischer** [comment]
Holy moly that was fast :D No it is running via SSD

**Comment by blakeblackshear** [comment]
Unfortunately it sounds like your sqlite database has been corrupted. It is stored at `/media/frigate/frigate.db` if you want to shutdown the addon and attempt to repair it. Or you can delete the files after shutting down and a new one will be created on startup.

**Comment by sebastian-tischer** [comment]
Stupid question - I just use the RPI with HASS and never needed to access files except via HASS File Explorer or VSCode. Can I access the file anyway via the File Explorer?

**Comment by sebastian-tischer** [comment]
Forget my last message - I deleted the db file via samba-share and now it works again :)

I just need to delete all the old recordings and have no idea how to do that...

**Comment by NickM-27** [comment]
> I just need to delete all the old recordings and have no idea how to do that...

similar idea the recordings are in `/media/frigate/recordings`

**Comment by sebastian-tischer** [comment]
That folder is ok and accessible via Samba. The problem is there are tons of recordings in the folder "My Media". It seems, they get saved there as well and I have no idea how to clean that up

**Comment by NickM-27** [comment]
if you don't care about what is there currently then you can simply turn off frigate, delete the entire /mediate/frigate directory, and then start frigate again

**Comment by cagivacode** [comment]
A related question, is the recording retention based on the database or on the files. 

I used ZM for years and it did depend on the DB for deletions but had a maintenance script that vacuumed the database and deleted any recordings not listed in the database.

**Comment by sebastian-tischer** [comment]
I just delete the frigate folder in the media folder via Samba integration - lets see if that works 🤣

**Comment by NickM-27** [comment]
> A related question, is the recording retention based on the database or on the files.
> 
> I used ZM for years and it did depend on the DB for deletions but had a maintenance script that vacuumed the database and deleted any recordings not listed in the database.

In the current version of frigate, it is based on the DB and if the recording file is not in the DB then frigate leaves it alone.

In the upcoming Frigate 0.13 the recordings files that are not in the db but are in the recordings directory will be deleted / managed as well as the files that are in the DB as it is now. There are also other DB related optimizations like a vacuum policy.

**Comment by sebastian-tischer** [comment]
Thats great news @NickM-27 👍  Is the way to delete frigate folder in media folder via Samba for now the correct way to get rid of all old records?

**Comment by NickM-27** [comment]
you can do it however you like, there are plenty of different options in HA OS and even more when just running frigate in docker.

**Comment by sebastian-tischer** [comment]
Really? The media ui browser seems to be crap 🤣  I only see the delete via Samba option...

**Comment by NickM-27** [comment]
you could use SSH, and I think there are other addons as well

**Comment by sebastian-tischer** [comment]
Got it - thanks a lot for the help 👍

**Comment by cagivacode** [comment]
Thank you, I will have to go check. New to frigate and have renamed / run test cameras so I must have many orphaned recordings.

**Comment by NickM-27** [comment]
frigate does have logic to remove recordings of cameras that are still in the DB but have been renamed
