### ISSUE TITLE
[Config Support]: Frigate startup in a loop 

### ISSUE THREAD

**Issue by haideramn** [blakeblackshear/frigate#7025]
### Describe the problem you are having

I am seeing Frigate stuck in loop when I start up the service. I have a basic config running, but every time I start the service, it loops with the error below. The WebUI never loads and just shows a circle spinning.

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.131
  user: mqtt
  password: mypassword

cameras:
  BabyCam
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.102:8544/baby-cam
          roles:
            - detect
    detect:
      enabled: False 
      width: 1280 
      height: 720
```

### Relevant log output

```shell
4 01:50:38.238983288  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-04 01:50:39.252324966  [INFO] Preparing go2rtc config...
2023-07-04 01:50:39.381000955  [INFO] Got IP address from supervisor: 192.168.1.102
2023-07-04 01:50:39.509962070  [INFO] Got WebRTC port from supervisor: 8555
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 27, in <module>
    config: dict[str, any] = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 8, column 11:
        ffmpeg:
              ^
2023-07-04 01:50:40.108602365  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-04 01:50:41.121427447  [INFO] Preparing go2rtc config...
2023-07-04 01:50:41.249589510  [INFO] Got IP address from supervisor: 192.168.1.102
2023-07-04 01:50:41.378539499  [INFO] Got WebRTC port from supervisor: 8555
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Any other information that may be helpful

Using RTSP feed from Wyze Docker Bridge which is getting video from a Wyze V3 Camera.

**Comment by NickM-27** [comment]
Like it shows in the error message your config is not valid, you are missing a `:` after `BabyCam`

**Comment by haideramn** [comment]
> Like it shows in the error message your config is not valid, you are missing a `:` after `BabyCam`

Thank you! That got the loop issue resolved and WebGUI works, but now getting this:

2023-07-04 03:50:56.772854321  [2023-07-03 23:50:56] watchdog.BabyCam               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-07-04 03:50:56.772908629  [2023-07-03 23:50:56] ffmpeg.BabyCam.detect          ERROR   : [tcp @ 0x5607639a0140] Connection to tcp://192.168.1.102:8544?timeout=5000000 failed: Connection refused
2023-07-04 03:50:56.781365399  [2023-07-03 23:50:56] ffmpeg.BabyCam.detect          ERROR   : rtsp://192.168.1.102:8544/baby-cam: Connection refused
2023-07-04 03:50:56.806720831  [2023-07-03 23:50:56] frigate.video                  ERROR   : BabyCam: Unable to read frames from ffmpeg process.
2023-07-04 03:50:56.807128659  [2023-07-03 23:50:56] frigate.video                  ERROR   : BabyCam: ffmpeg process is not running. exiting capture 

Any insight? Looks like the camera is refusing the connection?

**Comment by NickM-27** [comment]
yes it is refusing the connection

**Comment by haideramn** [comment]
any way to check why/what’s causing the refuse. The camera through Wyze Bridge has no username or password - how to check further?

**Comment by NickM-27** [comment]
Check the wyze bridge logs

**Comment by haideramn** [comment]
Wyze Bridge logs doesn't indicate anything....odd

**Comment by haideramn** [comment]
It was a port issue.....tired eyes missed that.

**Comment by NickM-27** [comment]
Feel free to create a new issue if something else comes up
