### ISSUE TITLE
[Bug]: Race condition in object detection queue

### ISSUE THREAD

**Issue by no2chem** [blakeblackshear/frigate#7081]
### Describe the problem you are having

If the `detected_objects_queue` is full but the check in video.py:1029 for `detected_objects_queue().full()` happens before it is full, then `detected_objects_queue.put(...)` will result in `queue.Full` being raised.

For example:

```
ha-frigate-1  | 2023-07-07 08:13:11.155047066  Process camera_processor:back-view:
ha-frigate-1  | 2023-07-07 08:13:11.161434476  Traceback (most recent call last):
ha-frigate-1  | 2023-07-07 08:13:11.161441196    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
ha-frigate-1  | 2023-07-07 08:13:11.161441996      self.run()
ha-frigate-1  | 2023-07-07 08:13:11.161442988    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
ha-frigate-1  | 2023-07-07 08:13:11.161443692      self._target(*self._args, **self._kwargs)
ha-frigate-1  | 2023-07-07 08:13:11.161444492    File "/opt/frigate/frigate/video.py", line 504, in track_camera
ha-frigate-1  | 2023-07-07 08:13:11.161445132      process_frames(
ha-frigate-1  | 2023-07-07 08:13:11.161448556    File "/opt/frigate/frigate/video.py", line 1035, in process_frames
ha-frigate-1  | 2023-07-07 08:13:11.161478925      detected_objects_queue.put(
ha-frigate-1  | 2023-07-07 08:13:11.161479821    File "/opt/frigate/frigate/util/builtin.py", line 91, in put
ha-frigate-1  | 2023-07-07 08:13:11.161480557      raise Full
ha-frigate-1  | 2023-07-07 08:13:11.161481165  queue.Full
```

This might be related to improved multiprocessing introduced in #6986, which may have allowed for much more concurrency. I'll try to push a PR for this soon.

### Version

0.13.0-CB35DB2

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
ha-frigate-1  | 2023-07-07 08:13:11.155047066  Process camera_processor:back-view:
ha-frigate-1  | 2023-07-07 08:13:11.161434476  Traceback (most recent call last):
ha-frigate-1  | 2023-07-07 08:13:11.161441196    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
ha-frigate-1  | 2023-07-07 08:13:11.161441996      self.run()
ha-frigate-1  | 2023-07-07 08:13:11.161442988    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
ha-frigate-1  | 2023-07-07 08:13:11.161443692      self._target(*self._args, **self._kwargs)
ha-frigate-1  | 2023-07-07 08:13:11.161444492    File "/opt/frigate/frigate/video.py", line 504, in track_camera
ha-frigate-1  | 2023-07-07 08:13:11.161445132      process_frames(
ha-frigate-1  | 2023-07-07 08:13:11.161448556    File "/opt/frigate/frigate/video.py", line 1035, in process_frames
ha-frigate-1  | 2023-07-07 08:13:11.161478925      detected_objects_queue.put(
ha-frigate-1  | 2023-07-07 08:13:11.161479821    File "/opt/frigate/frigate/util/builtin.py", line 91, in put
ha-frigate-1  | 2023-07-07 08:13:11.161480557      raise Full
ha-frigate-1  | 2023-07-07 08:13:11.161481165  queue.Full
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

N/A

**Comment by NickM-27** [comment]
Is this still an issue on the latest build?

**Comment by no2chem** [comment]
This appears to be fixed now in dev... thanks!
