### ISSUE TITLE
[Config Support]: devbranch: detect -> stationary -> interval cannot be 0

### ISSUE THREAD

**Issue by csreynolds** [blakeblackshear/frigate#7106]
### Describe the problem you are having

Loaded up the latest dev-tensorrt image to see whats up and my config didnt load because the detect stationary interval was 0

Loads up fine and runs as expected with any non0 value in that one place.

```Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 995, in config_save
    FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1186, in parse_raw
    return cls.parse_obj(config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
detect -> stationary -> interval
  ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)```

### Version

0.13.0-7C0D25F

### Frigate config file

```yaml
mqtt:
  host: mqtt
database:
  path: /db/frigate.db

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt 
  input_tensor: nchw
  input_pixel_format: rgb
  width: 640
  height: 640
birdseye:
  enabled: True
  restream: False
  mode: continuous
  quality: 5
detect:
  width: 1280
  height: 720
  fps: 15
  stationary:
    interval: 0
    threshold: 10
objects:
  track:
    - person
    - bicycle
    - car
    - cat
    - dog
    - bird
    - mouse
record:
  enabled: True
  retain:
    days: 1
  events:
    pre_capture: 10
    post_capture: 10
    retain:
      mode: active_objects
      default: 15
      objects:
        dog: 2
        car: 5
        person: 14
snapshots:
  enabled: True
  retain:
    default: 10
    objects:
      person: 14
      car: 5
go2rtc:
  streams:
    Garage:
      - rtsp://viewonly:viewonly12@192.168.7.181:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Garage#video=h264"
    Garage_sub:
      - rtsp://viewonly:viewonly12@192.168.7.181:554/cam/realmonitor?channel=1&subtype=1
    Driveway:
      - rtsp://viewonly:viewonly12@192.168.7.184:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Driveway#video=h264"
    Driveway_sub:
      - rtsp://viewonly:viewonly12@192.168.7.184:554/cam/realmonitor?channel=1&subtype=1
  webrtc:
    candidates:
      - 192.168.7.201:8555
      - stun:8555
ffmpeg:
  hwaccel_args: preset-nvidia-h264
  input_args: preset-rtsp-restream
  output_args:
    record: preset-record-generic-audio-aac
cameras:
  Garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Garage_sub
          roles:
            - detect
  Driveway:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/Driveway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/Driveway_sub
          roles:
            - detect
```

### Relevant log output

```shell
N/A
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

**Comment by NickM-27** [comment]
This is expected, the docs in the dev branch say that the value can't be 0
