### ISSUE TITLE
New Random Crashes

### ISSUE THREAD

**Issue by StarMonkey1** [blakeblackshear/frigate#7213]
### Describe the problem you are having

System has been stable for a number of weeks, suddenly having major crashes. System will lose camera feeds and a Frigate reboot will result in the errors below. Frigate then crashes and no web interface can be access at all.
Underlying Ubuntu Server host seems fine.

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: 192.168.1.10
  port: 1883
  user: frigate_mqtt
  password: password

detectors:
  coral:
    type: edgetpu
    device: usb

snapshots:
  enabled: true
  timestamp: true

ui:
  live_mode: webrtc

cameras:
  Front_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Door
          roles:
            - record
        - path: rtsp://user:password@192.168.1.108:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Front_Door
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 0

  Front_Garden:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Front_Garden
          roles:
            - record
        - path: rtsp://user:password@192.168.1.107:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Front_Garden
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 1

  Utility_External:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Utility_External
          roles:
            - record
        - path: rtsp://user:password@192.168.1.105:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Utility_External
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
        car:
          min_area: 25000
    ui:
      order: 2

  Office_External:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Office_External
          roles:
            - record
        - path: rtsp://user:password@192.168.1.106:554/Streaming/channels/101
          roles:
            - detect
    live:
      stream_name: Office_External
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - horse
      filters:
        person:
          min_area: 1000
    motion:
      mask:
        - 643,305,645,720,1080,720,1080,0,621,0
    ui:
      order: 3

  Garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Garage
          roles:
            - record
        - path: rtsp://user:password@192.168.1.102/av_stream/ch0
          roles:
            - detect
    live:
      stream_name: Garage
    record:
      enabled: true
      events:
        pre_capture: 15
        post_capture: 15
    detect:
      width: 1080
      height: 720
      fps: 5
    objects:
      track:
        - person
        - dog
        - bird
        - cat
        - bicycle
        - car
        - motorcycle
        - horse
      filters:
        person:
          min_area: 1000
    ui:
      order: 4

  Back_Door:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/Back_Door_Rotated
          roles:
            - record
            - detect
    live:
      stream_name: Back_Door_Rotated
    objects:
      track:
        - person
        - bicycle
      filters:
        person:
          min_area: 25000
    record:
      enabled: true
      retain:
        days: 14
        mode: motion
      events:
        retain: 
          default: 14
          mode: active_objects
        pre_capture: 15
        post_capture: 15
    detect:
      width: 720
      height: 1080
      fps: 5
    ui:
      order: 5

go2rtc:
  streams:
    Front_Door:
      - rtsp://user:password@192.168.1.108:554/Streaming/channels/101
    Front_Garden:
      - rtsp://user:password@192.168.1.107:554/Streaming/channels/101
    Utility_External:
      - rtsp://user:password@192.168.1.105:554/Streaming/channels/101
    Office_External:
      - rtsp://user:password@192.168.1.106:554/Streaming/channels/101
    Garage:
      - rtsp://user:password@192.168.1.102/av_stream/ch0
    Back_Door:
      - rtsp://user:password@192.168.1.103/av_stream/ch0
    Back_Door_Rotated:
      - "ffmpeg:Back_Door#video=h264#rotate=90"

  webrtc:
    candidates:
      - 192.168.1.4:8555
      - stun:8555
```

### Relevant log output

```shell
2023-07-18 22:12:59.345318484  [INFO] Starting Frigate...
2023-07-18 22:13:01.006790269  [2023-07-18 22:13:01] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-07-18 22:13:01.107618981  [2023-07-18 22:13:01] peewee_migrate                 INFO    : Starting migrations
2023-07-18 22:13:01.116038280  [2023-07-18 22:13:01] peewee_migrate                 INFO    : There is nothing to migrate
2023-07-18 22:13:01.152814567  [2023-07-18 22:13:01] detector.coral                 INFO    : Starting detection process: 288
2023-07-18 22:13:01.162740326  [2023-07-18 22:13:01] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-07-18 22:13:01.163902149  [2023-07-18 22:13:01] frigate.app                    INFO    : Output process started: 290
2023-07-18 22:13:01.182313732  [2023-07-18 22:13:01] frigate.app                    INFO    : Camera processor started for Front_Door: 298
2023-07-18 22:13:01.195366722  [2023-07-18 22:13:01] frigate.app                    INFO    : Camera processor started for Front_Garden: 299
2023-07-18 22:13:01.204150701  [2023-07-18 22:13:01] frigate.app                    INFO    : Camera processor started for Utility_External: 301
2023-07-18 22:13:01.213524518  [2023-07-18 22:13:01] frigate.app                    INFO    : Camera processor started for Office_External: 303
2023-07-18 22:13:01.222397413  [2023-07-18 22:13:01] frigate.app                    INFO    : Camera processor started for Garage: 304
2023-07-18 22:13:01.231280909  [2023-07-18 22:13:01] frigate.app                    INFO    : Camera processor started for Back_Door: 305
2023-07-18 22:13:01.239108214  [2023-07-18 22:13:01] frigate.app                    INFO    : Capture process started for Front_Door: 307
2023-07-18 22:13:01.248040389  [2023-07-18 22:13:01] frigate.app                    INFO    : Capture process started for Front_Garden: 310
2023-07-18 22:13:01.256803389  [2023-07-18 22:13:01] frigate.app                    INFO    : Capture process started for Utility_External: 313
2023-07-18 22:13:01.266539496  [2023-07-18 22:13:01] frigate.app                    INFO    : Capture process started for Office_External: 318
2023-07-18 22:13:01.275584970  [2023-07-18 22:13:01] frigate.app                    INFO    : Capture process started for Garage: 322
2023-07-18 22:13:01.284625426  [2023-07-18 22:13:01] frigate.app                    INFO    : Capture process started for Back_Door: 327
2023-07-18 22:13:07.177184228  Process detector:coral:
2023-07-18 22:13:07.177718641  [2023-07-18 22:13:07] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-07-18 22:13:07.179796687  Traceback (most recent call last):
2023-07-18 22:13:07.179827471    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-07-18 22:13:07.179830233      delegate = Delegate(library, options)
2023-07-18 22:13:07.179847529    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-07-18 22:13:07.179850218      raise ValueError(capture.message)
2023-07-18 22:13:07.180058471  ValueError
2023-07-18 22:13:07.180061268  
2023-07-18 22:13:07.180063426  During handling of the above exception, another exception occurred:
2023-07-18 22:13:07.180064880  
2023-07-18 22:13:07.180084403  Traceback (most recent call last):
2023-07-18 22:13:07.180125028    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-07-18 22:13:07.180127671      self.run()
2023-07-18 22:13:07.180168255    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-07-18 22:13:07.180171003      self._target(*self._args, **self._kwargs)
2023-07-18 22:13:07.180172967    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-07-18 22:13:07.180179482      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-07-18 22:13:07.180181743    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-07-18 22:13:07.180184551      self.detect_api = create_detector(detector_config)
2023-07-18 22:13:07.180212815    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-07-18 22:13:07.180215330      return api(detector_config)
2023-07-18 22:13:07.180241416    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-07-18 22:13:07.180244289      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-07-18 22:13:07.180246496    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-07-18 22:13:07.180248403      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-07-18 22:13:07.180309556  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-07-18 22:13:07.180311883
```

### FFprobe output from your camera

```shell
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2688x1520
FPS: 25/1

Stream 1:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2688x1520
FPS: 25/1
```

### Frigate stats

```json
{"Back_Door":{"camera_fps":0.0,"capture_pid":313,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":629,"pid":304,"process_fps":0.0,"skipped_fps":0.0},"Front_Door":{"camera_fps":5.0,"capture_pid":305,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":334,"pid":292,"process_fps":5.0,"skipped_fps":0.0},"Front_Garden":{"camera_fps":5.1,"capture_pid":307,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":336,"pid":293,"process_fps":5.1,"skipped_fps":0.0},"Garage":{"camera_fps":5.1,"capture_pid":312,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":347,"pid":302,"process_fps":5.1,"skipped_fps":0.0},"Office_External":{"camera_fps":5.1,"capture_pid":310,"detection_enabled":1,"detection_fps":3.9,"ffmpeg_pid":330,"pid":298,"process_fps":5.1,"skipped_fps":0.0},"Utility_External":{"camera_fps":5.1,"capture_pid":308,"detection_enabled":1,"detection_fps":5.0,"ffmpeg_pid":333,"pid":295,"process_fps":5.1,"skipped_fps":0.0},"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"1.0"},"1":{"cpu":"0.0","mem":"0.0"},"110":{"cpu":"7.3","mem":"2.1"},"111":{"cpu":"0.0","mem":"0.0"},"119":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"18":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"1.0"},"287":{"cpu":"0.3","mem":"0.1"},"288":{"cpu":"9.0","mem":"1.4"},"289":{"cpu":"1.7","mem":"1.2"},"29":{"cpu":"0.0","mem":"0.0"},"292":{"cpu":"0.7","mem":"1.2"},"293":{"cpu":"0.7","mem":"1.2"},"295":{"cpu":"7.3","mem":"1.2"},"296":{"cpu":"0.0","mem":"0.2"},"298":{"cpu":"7.3","mem":"1.2"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.2"},"302":{"cpu":"0.7","mem":"1.2"},"303":{"cpu":"0.0","mem":"0.2"},"304":{"cpu":"0.0","mem":"1.1"},"305":{"cpu":"2.3","mem":"1.1"},"306":{"cpu":"0.0","mem":"0.2"},"307":{"cpu":"2.3","mem":"1.1"},"308":{"cpu":"2.0","mem":"1.1"},"309":{"cpu":"0.0","mem":"0.2"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"2.3","mem":"1.1"},"311":{"cpu":"0.0","mem":"0.2"},"312":{"cpu":"2.0","mem":"1.1"},"313":{"cpu":"0.0","mem":"1.1"},"314":{"cpu":"0.0","mem":"0.2"},"32":{"cpu":"0.0","mem":"0.0"},"330":{"cpu":"7.3","mem":"0.6"},"333":{"cpu":"7.7","mem":"0.7"},"334":{"cpu":"7.7","mem":"0.6"},"336":{"cpu":"7.7","mem":"0.7"},"345":{"cpu":"4.7","mem":"0.3"},"347":{"cpu":"2.0","mem":"0.5"},"349":{"cpu":"5.0","mem":"0.3"},"351":{"cpu":"4.3","mem":"0.3"},"352":{"cpu":"4.3","mem":"0.3"},"357":{"cpu":"0.0","mem":"0.3"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"543":{"cpu":"0.0","mem":"0.0"},"629":{"cpu":"0.0","mem":"0.2"},"631":{"cpu":"0.0","mem":"0.4"},"638":{"cpu":"0.0","mem":"0.0"},"648":{"cpu":"0.7","mem":"0.0"},"662":{"cpu":"2.7","mem":"0.4"},"77":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"83":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"38.3","mem":"0.3"},"MiB":{"cpu":"6022.9","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"load","mem":"average:"}},"detection_fps":8.9,"detectors":{"coral":{"detection_start":0.0,"inference_speed":12.59,"pid":288}},"gpu_usages":{"intel-vaapi":{"gpu":"23.07 %","mem":"- %"}},"service":{"last_updated":1689715608,"latest_version":"unknown","storage":{"/dev/shm":{"free":260.1,"mount_type":"tmpfs","total":268.4,"used":8.4},"/media/frigate/clips":{"free":48370.5,"mount_type":"ext4","total":105089.3,"used":51333.3},"/media/frigate/recordings":{"free":48370.5,"mount_type":"ext4","total":105089.3,"used":51333.3},"/tmp/cache":{"free":1816.4,"mount_type":"tmpfs","total":2000.0,"used":183.6}},"temperatures":{},"uptime":66,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Hikvision and Sonoff

**Comment by NickM-27** [comment]
The coral is being lost, this is usually due to a power issue where the USB ports are unable to supply enough power

**Comment by StarMonkey1** [comment]
Ok, I'll look into this. It's a built in USB3 port and it's been stable for
a few weeks until now. This isn't a Pi build, it's on a small Dell pc.

**Comment by NickM-27** [comment]
Right, it is usually the problem on a Pi though I have seen it on PCs before.

**Comment by StarMonkey1** [comment]
Same issue again today. Frigate web front end struggles to load. Coral is
lit up and flashing away. As I said, it's been stable for a while before
this. I've made no changes recently. Dell PC is running from a 65W PSU, its
only running Frigate in a container. Power seems unlikely, also difficult
for me to test.

**Comment by NickM-27** [comment]
What is your docker compose?

**Comment by StarMonkey1** [comment]
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/sm/frigate/config.yml:/config/config.yml
      - /path/to/your/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
```

**Comment by NickM-27** [comment]
what type of mount is `- /path/to/your/storage:/media/frigate`

**Comment by StarMonkey1** [comment]
It's an iSCSI share mounted to the Ubuntu box. Ubuntu can see the share,
it's not full. Frigate seems to report on it ok when it works.

On my phone at the moment and use portainer so that's a saved copy of the
compose, should be correct though.

**Comment by NickM-27** [comment]
That will likely be the problem for the slowdowns, the default location for the db is /media/frigate/frigate.db which is not meant to be stored on a network share. I'd highly suggest moving the db (and related files) to /config and updating your config accordingly https://docs.frigate.video/configuration/advanced#database

another thing you can do is run `VACUUM` on the database.

Both of these things will be done / required in 0.13

**Comment by StarMonkey1** [comment]
Ah, that's not how I have it configured then. The .dB is on the local disk
(nvme), its just the media that's on the iscsi share

**Comment by NickM-27** [comment]
> Ah, that's not how I have it configured then. The .dB is on the local disk (nvme), its just the media that's on the iscsi share

No , that is not how you have it configured, I can see in your config above you are not setting the db file location anywhere which means it is still in the default location

**Comment by StarMonkey1** [comment]
Just double checked, I have an iSCSI share mapped to /mnt but I'm not yet using it (its been a while since I set this up). So the frigate.db and media are all on a local nvme drive. Which means that's not causing the crashes.

If I reboot the physical host everything starts working again for a while.

**Comment by StarMonkey1** [comment]
I also have these errors in go2rtc logs:
```
2023-07-20 09:54:07.299940233  [INFO] Preparing go2rtc config...
2023-07-20 09:54:07.837390947  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-07-20 09:54:07.970593323  [INFO] Starting go2rtc...
2023-07-20 09:54:08.112701931  09:54:08.112 INF go2rtc version 1.2.0 linux/amd64
2023-07-20 09:54:08.113206498  09:54:08.113 INF [api] listen addr=:1984
2023-07-20 09:54:08.113785789  09:54:08.113 INF [rtsp] listen addr=:8554
2023-07-20 09:54:08.114379146  09:54:08.114 INF [srtp] listen addr=:8443
2023-07-20 09:54:08.114786547  09:54:08.114 INF [webrtc] listen addr=:8555
2023-07-20 09:54:15.763055987  09:54:15.762 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:54:17.314642913  [INFO] Starting go2rtc healthcheck service...
2023-07-20 09:54:35.734502888  09:54:35.734 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:54:45.734930429  09:54:45.734 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:54:55.802555292  09:54:55.802 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:55:05.740080573  09:55:05.739 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:55:15.716757739  09:55:15.715 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:55:25.792139889  09:55:25.791 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:55:35.858711078  09:55:35.858 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:55:45.779322638  09:55:45.779 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:55:55.786516107  09:55:55.786 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:56:05.814519485  09:56:05.814 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:56:15.818954407  09:56:15.818 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:56:25.835348131  09:56:25.835 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:56:35.807259967  09:56:35.807 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:56:45.818615858  09:56:45.818 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:56:55.834814243  09:56:55.834 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:57:05.778452281  09:57:05.778 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:57:15.778822715  09:57:15.778 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:57:25.818930682  09:57:25.818 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:57:35.870452019  09:57:35.870 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:57:45.875117826  09:57:45.874 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:57:55.814468277  09:57:55.814 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:58:05.802681492  09:58:05.802 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:58:15.830447022  09:58:15.830 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:58:25.834625007  09:58:25.834 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:58:35.834740624  09:58:35.834 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:58:45.898535711  09:58:45.898 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:58:55.916311701  09:58:55.915 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:59:05.846762806  09:59:05.846 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:59:15.858751372  09:59:15.858 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:59:25.866630584  09:59:25.866 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-07-20 09:59:35.917338700  09:59:35.916 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
```

**Comment by NickM-27** [comment]
It definitely could be related if the stream is crashing often enough and causing a memory leak or something. I'd suggest updating go2rtc https://docs.frigate.video/configuration/advanced#custom-go2rtc-version and running `VACUUM` on the DB

**Comment by StarMonkey1** [comment]
How do I do this for a machine in docker? The changes won't persist over an
update will they? This will be a manual thing I need to do each time?

I do wish the documentation wouldn't assume expertise in the underlying
tools Frigate runs on top of.
