### ISSUE TITLE
Error with frigate

### ISSUE THREAD

**Issue by bend94** [blakeblackshear/frigate#7276]
### Describe the problem you are having

hi have that kind of errors 

```
Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
```

and these also

```
Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
```

need help
thx

### Version

0.12.1-367D724

### Frigate config file

```yaml
logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.components.stream: debug
#ui:
#  use_experimental: false
 # live_mode: mse

mqtt:
  host: 192.168.1.32
  port : 1883
  topic_prefix : frigate
  user: mqtt
  password: pass4MQTT


detectors:
  coral:
    type: edgetpu
    device: usb
  #cpu1:
  #  type: cpu
  #cpu2:
  #  type: cpu


ffmpeg:
  hwaccel_args: preset-rpi-64-h264

birdseye:
  enabled: true
  width: 896
  height: 672
  quality: 1
  mode: continuous


cameras:
  terrasse:
    ffmpeg:
      inputs:
        - path: rtsp://test:Carrefour04C@192.168.1.202:554/Streaming/Channels/102/
          #input_args: preset-rpi-64-h264
          roles:
            - detect
            - rtmp
        - path: rtsp://test:Carrefour04C@192.168.1.202:554/Streaming/Channels/101/
          #input_args: preset-rtsp-restream
          roles:
            - record
   # rtmp:
  #    enabled: true
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
      - 253,240,148,0,0,0,0,112,0,240,47,240,88,240
    zones:
      Jardin:
        coordinates: 140,65,221,240,253,240,274,201,299,138,195,52
    record:
      enabled: True
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: False
      timestamp: True
      bounding_box: True
      retain:
        default: 5
        mode: motion
  cuisine:
    ffmpeg:
      inputs:
        - path: rtsp://test:Carrefour04C@192.168.1.203:554/Streaming/Channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://test:Carrefour04C@192.168.1.203:554/Streaming/Channels/101/
          roles:
            - record
    rtmp:
      enabled: true
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask:
        - 162,159,163,25,0,0,0,240,83,240,161,240
    record:
      enabled: False
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: False
      timestamp: True
      bounding_box: True
      retain:
        default: 5
        mode: motion
  salon:
    ffmpeg:
      inputs:
        - path: rtsp://test:Carrefour04C@192.168.1.201:554/Streaming/Channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://test:Carrefour04C@192.168.1.201:554/Streaming/Channels/102/
          roles:
            - record
    rtmp:
      enabled: true
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
        - dog
        - cat
    motion:
      mask:
       - 0,32,104,32,111,136,0,193
       - 320,240,320,30,275,32,248,240
    zones:
      ZSalon:
        coordinates: 0,240,0,200,110,129,107,30,272,36,248,240
    record:
      enabled: False
      retain:
        days: 2
        mode: motion
    snapshots:
      enabled: False
      timestamp: True
      bounding_box: True
      retain:
        default: 5
        mode: motion
  bureau:
    ffmpeg:
      inputs:
        - path: rtsp://test:Carrefour04C@192.168.1.205:554/Streaming/Channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://test:Carrefour04C@192.168.1.205:554/Streaming/Channels/102/
          roles:
            - record
    rtmp:
      enabled: true
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    record:
      enabled: False
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: False
      timestamp: True
      bounding_box: True
      retain:
        default: 5
        mode: motion
  couloir:
    ffmpeg:
      inputs:   
        - path: rtsp://test:Carrefour04C@192.168.1.204:554/Streaming/Channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://test:Carrefour04C@192.168.1.204:554/Streaming/Channels/102/
          roles:
            - record
    rtmp:
      enabled: true
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    record:
      enabled: False
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: False
      timestamp: True
      bounding_box: True
      retain:
        default: 5
        mode: motion
  interphone:
    ffmpeg:
      inputs:
        - path: rtsp://ghnfij0002:Tc7KMmWxXG@192.168.1.173:554/mpeg/media.amp
          #input_args: preset-rpi-64-h264
          roles:
            - detect
            - rtmp
        - path: rtsp://ghnfij0002:Tc7KMmWxXG@192.168.1.173:554/mpeg/media.amp
          #input_args: preset-rpi-64-h264
          roles:
            - record
    rtmp:
      enabled: true
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      filters:
        car:
          mask:
            - 0,0,320,0,320,107,0,109
        person:
          mask:
            - 0,0,320,0,320,107,0,109
        dog:
          mask:
            - 0,0,320,0,320,107,0,109
        cat:
          mask:
            - 0,0,320,0,320,107,0,109
    motion:
      mask:    
        - 0,0,320,0,320,92,0,95
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
    snapshots:
      enabled: false
      timestamp: True
      bounding_box: True
      retain:
        default: 5
        mode: motion
  devant:
    ffmpeg:
      inputs:
        - path: rtsp://test:Carrefour04C@192.168.1.200:554/Streaming/Channels/102/
          roles:
            - detect
            - rtmp
        - path: rtsp://test:Carrefour04C@192.168.1.200:554/Streaming/Channels/101/
          roles:
            - record
    rtmp:
      enabled: true
    detect:
      width: 320
      height: 240
      fps: 4
    objects:
      track:
        - person
    motion:
      mask:
      - 320,123,320,0,159,0,0,0,0,112,0,182,76,126
    zones:
      Front:
        coordinates: 35,173,0,240,320,240,320,163,275,128,102,126
    record:
      enabled: true
      retain:
        days: 5
        mode: motion
    snapshots:
      enabled: False
      timestamp: True
      bounding_box: True
      retain:
        default: 5
        mode: motion
```

### Relevant log output

```shell
2023-07-24 17:02:43.049 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-24 17:02:43.051 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-24 17:02:43.053 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration rpi_gpio which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-24 17:02:43.055 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-24 17:03:04.965 DEBUG (SyncWorker_0) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:03:04.970 DEBUG (SyncWorker_5) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:03:06.722 ERROR (MainThread) [homeassistant.components.automation] Failed to generate automation from blueprint: Failed to load blueprint: Unable to find hunterjm/frigate_notification.yaml
2023-07-24 17:03:09.380 ERROR (MainThread) [homeassistant.components.esphome.dashboard] Error requesting ESPHome Dashboard data: Cannot connect to host 127.0.0.1:63398 ssl:default [Connect call failed ('127.0.0.1', 63398)]
2023-07-24 17:03:09.384 ERROR (MainThread) [homeassistant.components.esphome.dashboard] Dashboard unavailable; skipping reauth: Cannot connect to host 127.0.0.1:63398 ssl:default [Connect call failed ('127.0.0.1', 63398)]
2023-07-24 17:03:09.890 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform scrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 167, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 421, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 425, in async_added_to_hass
    self.hass.bus.async_listen_once(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1193, in async_listen_once
    HassJob(_onetime_listener, f"onetime listen {event_type} {listener}"),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 686, in __repr__
    return super().__repr__()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1184, in __repr__
    return f"<entity {self.entity_id}={self._stringify_state(self.available)}>"
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 487, in state
    raise ValueError(
ValueError: Sensor sensor.web_scrape has a unit of measurement and thus indicating it has a numeric value; however, it has the non-numeric device class: date
2023-07-24 17:03:09.916 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up scrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 167, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 421, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/template_entity.py", line 425, in async_added_to_hass
    self.hass.bus.async_listen_once(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1193, in async_listen_once
    HassJob(_onetime_listener, f"onetime listen {event_type} {listener}"),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 686, in __repr__
    return super().__repr__()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1184, in __repr__
    return f"<entity {self.entity_id}={self._stringify_state(self.available)}>"
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 487, in state
    raise ValueError(
ValueError: Sensor sensor.web_scrape has a unit of measurement and thus indicating it has a numeric value; however, it has the non-numeric device class: date
2023-07-24 17:03:12.117 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name has no usable address]
2023-07-24 17:03:12.345 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Name has no usable address]
2023-07-24 17:03:25.185 ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: 502, message='Bad Gateway', url=URL('http://ccab4aaf-frigate:5000/api/stats')
2023-07-24 17:04:05.313 DEBUG (SyncWorker_0) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:04:05.315 DEBUG (SyncWorker_7) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:05:05.315 DEBUG (SyncWorker_10) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:05:05.316 DEBUG (SyncWorker_5) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:05:39.257 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:06:05.316 DEBUG (SyncWorker_4) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:06:05.318 DEBUG (SyncWorker_10) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:06:19.361 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:06:35.667 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:07:05.318 DEBUG (SyncWorker_9) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:07:05.319 DEBUG (SyncWorker_3) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:07:05.670 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:07:09.454 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:07:15.692 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:07:15.711 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:07:35.719 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:08:05.320 DEBUG (SyncWorker_2) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:08:05.321 DEBUG (SyncWorker_1) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:08:05.749 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:08:05.807 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:08:09.515 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:08:45.773 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:09:05.320 DEBUG (SyncWorker_9) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:09:05.322 DEBUG (SyncWorker_7) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:09:05.891 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:09:19.566 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:09:35.797 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:10:05.323 DEBUG (SyncWorker_2) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:10:05.326 DEBUG (SyncWorker_7) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:10:15.946 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:10:35.824 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:10:39.656 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:11:05.323 DEBUG (SyncWorker_6) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:11:05.324 DEBUG (SyncWorker_4) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:11:36.032 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:11:45.849 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:12:05.324 DEBUG (SyncWorker_4) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:12:05.324 DEBUG (SyncWorker_7) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:12:09.740 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:13:05.324 DEBUG (SyncWorker_9) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:13:05.324 DEBUG (SyncWorker_4) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:13:05.880 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:13:06.127 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:13:49.788 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:14:05.325 DEBUG (SyncWorker_0) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:14:05.325 DEBUG (SyncWorker_6) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:14:35.905 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:14:46.219 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
2023-07-24 17:15:05.326 DEBUG (SyncWorker_3) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:15:05.326 DEBUG (SyncWorker_10) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:15:39.873 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/interphone
2023-07-24 17:16:05.326 DEBUG (SyncWorker_6) [homeassistant.components.command_line] Running command: date>> /tmp/date.txt
2023-07-24 17:16:05.327 DEBUG (SyncWorker_8) [homeassistant.components.command_line] Running command: cat /sys/class/thermal/thermal_zone0/temp
2023-07-24 17:16:15.931 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.interphone_live] Error from stream worker: Error opening stream (HTTP_OTHER_4XX, Server returned 4XX Client Error, but not one of 40{0,1,3,4}) rtsp://****:****@192.168.1.173:554/mpeg/media.amp
2023-07-24 17:16:36.320 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.couloir] Error from stream worker: Error opening stream (ERRORTYPE_5, I/O error) rtmp://ccab4aaf-frigate/live/couloir
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
This should be reportd [on the integration repo](https://github.com/blakeblackshear/frigate-hass-integration) not the main frigate repo as these error logs are from home assistant
