### ISSUE TITLE
[Config Support]: mapping values are not allowed here roles

### ISSUE THREAD

**Issue by EuPhobos** [blakeblackshear/frigate#7337]
### Describe the problem you are having

Frigate wont start

### Version

ghcr.io/blakeblackshear/frigate:stable

### Frigate config file

```yaml
mqtt:
  host: 172.17.0.7
  user: mqtt
  password: ###
database:
  path: /media/frigate/db/frigate.db
cameras:
  mycam:
    ffmpeg:
      inputs:
        - http://172.17.0.7:20880/api/camera/stream/640018196634/54624969
          roles:
            - detect
            - rtmp
rtmp:
  enabled: False
detect:
  width: 1280
  height: 720
```

### Relevant log output

```shell
2023-07-31 11:26:20.045741840  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-07-31 11:26:20.058137555  [2023-07-31 11:26:20] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-07-31 11:26:20.060361770  *************************************************************
2023-07-31 11:26:20.060367270  *************************************************************
2023-07-31 11:26:20.060394365  ***    Your config file is not valid!                     ***
2023-07-31 11:26:20.060396013  ***    Please check the docs at                           ***
2023-07-31 11:26:20.060397377  ***    https://docs.frigate.video/configuration/index     ***
2023-07-31 11:26:20.060400409  *************************************************************
2023-07-31 11:26:20.060402763  *************************************************************
2023-07-31 11:26:20.060431326  ***    Config Validation Errors                           ***
2023-07-31 11:26:20.060432997  *************************************************************
2023-07-31 11:26:20.060444390  mapping values are not allowed here
2023-07-31 11:26:20.060445789    in "<unicode string>", line 12, column 16:
2023-07-31 11:26:20.060446849                roles:
2023-07-31 11:26:20.060447819                     ^
2023-07-31 11:26:20.062739192  Traceback (most recent call last):
2023-07-31 11:26:20.062742576    File "/opt/frigate/frigate/app.py", line 351, in start
2023-07-31 11:26:20.062744154      self.init_config()
2023-07-31 11:26:20.062745709    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-07-31 11:26:20.062747179      user_config = FrigateConfig.parse_file(config_file)
2023-07-31 11:26:20.062748761    File "/opt/frigate/frigate/config.py", line 1074, in parse_file
2023-07-31 11:26:20.062750197      config = load_config_with_no_duplicates(raw_config)
2023-07-31 11:26:20.062751546    File "/opt/frigate/frigate/util.py", line 78, in load_config_with_no_duplicates
2023-07-31 11:26:20.062752985      return yaml.load(raw_config, PreserveDuplicatesLoader)
2023-07-31 11:26:20.062755091    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
2023-07-31 11:26:20.062779352      return loader.get_single_data()
2023-07-31 11:26:20.062781291    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
2023-07-31 11:26:20.062782689      node = self.get_single_node()
2023-07-31 11:26:20.062784221    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
2023-07-31 11:26:20.062795319      document = self.compose_document()
2023-07-31 11:26:20.062797004    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
2023-07-31 11:26:20.062798284      node = self.compose_node(None, None)
2023-07-31 11:26:20.062799660    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-07-31 11:26:20.062800878      node = self.compose_mapping_node(anchor)
2023-07-31 11:26:20.062802354    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
2023-07-31 11:26:20.062803604      item_value = self.compose_node(node, item_key)
2023-07-31 11:26:20.062816518    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-07-31 11:26:20.062817944      node = self.compose_mapping_node(anchor)
2023-07-31 11:26:20.062819460    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
2023-07-31 11:26:20.062820817      item_value = self.compose_node(node, item_key)
2023-07-31 11:26:20.062822108    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-07-31 11:26:20.062823170      node = self.compose_mapping_node(anchor)
2023-07-31 11:26:20.062824552    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
2023-07-31 11:26:20.062836600      item_value = self.compose_node(node, item_key)
2023-07-31 11:26:20.062838153    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-07-31 11:26:20.062839374      node = self.compose_mapping_node(anchor)
2023-07-31 11:26:20.062840884    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
2023-07-31 11:26:20.062842301      item_value = self.compose_node(node, item_key)
2023-07-31 11:26:20.062843743    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 82, in compose_node
2023-07-31 11:26:20.062844924      node = self.compose_sequence_node(anchor)
2023-07-31 11:26:20.062846486    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
2023-07-31 11:26:20.062847785      while not self.check_event(SequenceEndEvent):
2023-07-31 11:26:20.062849183    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
2023-07-31 11:26:20.062850313      self.current_event = self.state()
2023-07-31 11:26:20.062851696    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
2023-07-31 11:26:20.062852859      if self.check_token(BlockEntryToken):
2023-07-31 11:26:20.062870549    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
2023-07-31 11:26:20.062871822      self.fetch_more_tokens()
2023-07-31 11:26:20.062873215    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
2023-07-31 11:26:20.062874333      return self.fetch_value()
2023-07-31 11:26:20.062875693    File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
2023-07-31 11:26:20.062876768      raise ScannerError(None, None,
2023-07-31 11:26:20.062878129  yaml.scanner.ScannerError: mapping values are not allowed here
2023-07-31 11:26:20.062879177    in "<unicode string>", line 12, column 16:
2023-07-31 11:26:20.062880142                roles:
2023-07-31 11:26:20.062881062                     ^
2023-07-31 11:26:20.062881878  
2023-07-31 11:26:20.062883004  *************************************************************
2023-07-31 11:26:20.062884129  ***    End Config Validation Errors                       ***
2023-07-31 11:26:20.062907820  *************************************************************
```

### Frigate stats

```json
nope
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Please follow the docs https://docs.frigate.video/guides/getting_started

You are missing `- path:` at the beginning of the stream url

**Comment by EuPhobos** [comment]
Oh my .. inattention
I ran through the documentation several times, and did not notice the banal.
@NickM-27 thank you, now it works.
