### ISSUE TITLE
[Config Support]:  Config.yml not found - UnRaidOS - 

### ISSUE THREAD

**Issue by TheCrey** [blakeblackshear/frigate#7352]
### Describe the problem you are having

Hi there, i hope you are fine. 
I am trying to install frigate on one of my unraid servers, but i do have the issue in all. 
I got it running sucessfully on my HA instance (running on a PI) but i would like to get in runn on the unraid server 

The issue is right at the startup, as the config.yml file is not found, and i really do not know why, i am sure i am overseeing something very simple.

But the facts first: 
Unraid Version 6.12.3
Installed the docker over the CA - from "yayitazale" to be precise, repository "ghcr.io/blakeblackshear/frigate:stable
"

I do have the config file from my HA version with changes to it should be running, but if not that would be ok i could then work on that, but first i need it running itself. 

The settings are kind of normale, nothign special in my eyes, i am sure its something with the folder mounting but i am not able to find out what. 

Could someone give me a hint in the correct direction ? 
Thanks a lot 

<img width="1161" alt="1" src="https://github.com/blakeblackshear/frigate/assets/4265066/069320f4-0d0c-487f-b6b6-acc5a8c43609">

<img width="1622" alt="2" src="https://github.com/blakeblackshear/frigate/assets/4265066/80f0f8b3-c3b4-4f73-bd92-c92273b9549b">

<img width="1656" alt="3" src="https://github.com/blakeblackshear/frigate/assets/4265066/298cf93f-ba89-4185-8fd3-3690cc0d1722">

### Version

- not able to get to that page 

### Frigate config file

```yaml
mqtt:
  host: 192.168.x.x
  user: xxxx
  password: xxx


cameras:
  holz_frigate:
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.xxx.xxx:554/stream1 
            - detect
    detect:
      enabled: False 
      width: 2304 
      height: 1296 
      fps: 5
```

### Relevant log output

```shell
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
2023-08-01 17:25:52.272100524  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2023-08-01 17:25:52.319455382  [INFO] Service NGINX exited with code 0 (by signal 0)
2023-08-01 17:25:52.332775382  [INFO] The go2rtc service exited with code 256 (by signal 15)
2023-08-01 17:25:57.621878394  [INFO] Preparing go2rtc config...
2023-08-01 17:25:57.623802512  [INFO] Starting Frigate...
2023-08-01 17:25:57.627490009  [INFO] Starting NGINX...
2023-08-01 17:25:58.060105354  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-08-01 17:25:59.070263489  [INFO] Preparing go2rtc config...
2023-08-01 17:25:59.513129646  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-08-01 17:26:00.159248571  *************************************************************
2023-08-01 17:26:00.159259704  *************************************************************
2023-08-01 17:26:00.159266103  ***    Your config file is not valid!                     ***
2023-08-01 17:26:00.159271970  ***    Please check the docs at                           ***
2023-08-01 17:26:00.159276428  ***    https://docs.frigate.video/configuration/index     ***
2023-08-01 17:26:00.159317575  *************************************************************
2023-08-01 17:26:00.159322600  *************************************************************
2023-08-01 17:26:00.159326330  ***    Config Validation Errors                           ***
2023-08-01 17:26:00.159330398  *************************************************************
2023-08-01 17:26:00.159333902  [Errno 2] No such file or directory: '/config/config.yml'
2023-08-01 17:26:00.159578391  [2023-08-01 17:26:00] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-01 17:26:00.161085936  Traceback (most recent call last):
2023-08-01 17:26:00.161091768    File "/opt/frigate/frigate/app.py", line 351, in start
2023-08-01 17:26:00.161095465      self.init_config()
2023-08-01 17:26:00.161099551    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-08-01 17:26:00.161103091      user_config = FrigateConfig.parse_file(config_file)
2023-08-01 17:26:00.161107358    File "/opt/frigate/frigate/config.py", line 1070, in parse_file
2023-08-01 17:26:00.161110836      with open(config_file) as f:
2023-08-01 17:26:00.161115816  FileNotFoundError: [Errno 2] No such file or directory: '/config/config.yml'
2023-08-01 17:26:00.161156983  
2023-08-01 17:26:00.161162395  *************************************************************
2023-08-01 17:26:00.161166969  ***    End Config Validation Errors                       ***
2023-08-01 17:26:00.161210279  *************************************************************
2023-08-01 17:26:00.521508988  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
FileNotFoundErr
```

### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
First off, you called the file `frigate.yml` but that is wrong. Secondly your path shows `/mnt/user/appdata/frigate_docker/frigate/config` but the path in the file explorer is actually `/mnt/user/appdata/frigate_docker/frigate/config/config`

I would highly suggest cleaning that up to just be `/mnt/user/appdata/frigate` and moving the frigate.yml file to be called config.yml inside of that folder
