### ISSUE TITLE
[Detector Support]: Custom Models with EdgeTPU

### ISSUE THREAD

**Issue by Gie92** [blakeblackshear/frigate#7370]
### Describe the problem you are having

Hello!

I am currently trying to create a .tflite model from Teachable Machine, Everytime I try to add the files and point the path in Frigate get:

IndexError: list index out of range

I've been testing out the models from the coral ai website and I've had luck getting SSD MobileNet V2 / TF. 1 to work with Frigate, and I've noticed a huge difference when it came to detection accuracy.

I've noticed that on the coral ai website anything with TF. 2 will not work with it.

Here's the site for reference:

https://coral.ai/models/object-detection/

I was hoping someone can point me in the right direction on how to create a custom model for EdgeTPU that will work with Frigate?

Thanks!

### Version

0.12.1

### Frigate config file

```yaml
cameras:
  fg_food_bowl:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.98:8554/dogfoodcamera
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    zones:
      benny:
        coordinates: 687,998,200,908,611,685,753,698
      shylo:
        coordinates: 1252,1009,1803,922,1413,673,1240,647,1123,685
    motion:
      mask:
        - 0,85,693,74,695,0,0,0
  fg_rccam:
    ffmpeg:
      inputs:
        - path: rtsp://10.0.0.98:8554/rccamera
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
    zones:
      hallway:
        coordinates: 850,1080,1235,1080,1175,40,1077,40,1067,187,971,183
      livingroom:
        coordinates: 844,1080,0,1080,0,407,113,303,569,279,646,438,915,441
      doorway:
        coordinates: 1648,713,1920,707,1920,502,1815,399,1512,366
      kitchen:
        coordinates: 1920,1080,1253,1080,1201,349,1512,384,1649,724,1920,717
      bedroomentrance:
        coordinates: 1005,96,1076,100,1081,32,1023,31
      officeentrance:
        coordinates: 974,176,1065,177,1067,107,999,99
    motion:
      mask:    
        - 467,0,0,0,0,51,469,54
    
        
detectors: 
  #cpu1:
    #type: cpu
    #num_threads: 3
  #cpu2:
    #type: cpu
    #num_threads: 3
  coral_pci:
    type: edgetpu
    device: pci

model:
 # path: /edgetpu_model.tflite
  path: /media/frigate/model/dogs.tflite
  labelmap_path: /media/frigate/model/dogs.txt
  width: 224
  height: 224

detect:
  fps: 5
    
objects:
  track:
  #  - dog
  #  - person
    - shylo
    - benny
  filters:
    person:
      threshold: 0.8  

record:
  enabled: True
  retain:
    days: 1
    mode: motion
  events:
    pre_capture: 2
    post_capture: 2
    retain:
      default: 1
      mode: motion
      objects:
        dog: 1

ffmpeg:
  hwaccel_args: preset-vaapi
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant log output

```shell
2023-08-03 00:00:35.133550678  18:00:35.133 INF [srtp] listen addr=:8443
2023-08-03 00:00:35.133785011  18:00:35.133 INF [webrtc] listen addr=:8555
2023-08-03 00:00:35.455103940  2023/08/02 18:00:35 [error] 137#137: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "ccab4aaf-frigate:5000"
2023-08-03 00:00:35.455161243  172.30.32.1 - - [02/Aug/2023:18:00:35 -0600] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.8.0 aiohttp/3.8.5 Python/3.11" "-"
2023-08-03 00:00:35.834705141  [2023-08-02 18:00:35] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-03 00:00:35.857745196  [2023-08-02 18:00:35] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-08-03 00:00:35.859487859  [2023-08-02 18:00:35] peewee_migrate                 INFO    : Starting migrations
2023-08-03 00:00:35.862814953  [2023-08-02 18:00:35] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-03 00:00:35.887693049  [2023-08-02 18:00:35] frigate.app                    INFO    : Output process started: 300
2023-08-03 00:00:35.899617422  [2023-08-02 18:00:35] frigate.app                    INFO    : Camera processor started for fg_food_bowl: 304
2023-08-03 00:00:35.906820621  [2023-08-02 18:00:35] frigate.app                    INFO    : Camera processor started for fg_rccam: 306
2023-08-03 00:00:35.909736417  [2023-08-02 18:00:35] frigate.app                    INFO    : Capture process started for fg_food_bowl: 308
2023-08-03 00:00:35.919638386  [2023-08-02 18:00:35] detector.coral_pci             INFO    : Starting detection process: 299
2023-08-03 00:00:35.919816112  [2023-08-02 18:00:35] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-08-03 00:00:35.922223642  [2023-08-02 18:00:35] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-08-03 00:00:35.923240055  [2023-08-02 18:00:35] frigate.app                    INFO    : Capture process started for fg_rccam: 312
2023-08-03 00:00:37.485944352  Process detector:coral_pci:
2023-08-03 00:00:37.487485867  Traceback (most recent call last):
2023-08-03 00:00:37.487491620    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-03 00:00:37.487497013      self.run()
2023-08-03 00:00:37.487500696    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-03 00:00:37.487503049      self._target(*self._args, **self._kwargs)
2023-08-03 00:00:37.487505350    File "/opt/frigate/frigate/object_detection.py", line 121, in run_detector
2023-08-03 00:00:37.487529600      detections = object_detector.detect_raw(input_frame)
2023-08-03 00:00:37.487532812    File "/opt/frigate/frigate/object_detection.py", line 71, in detect_raw
2023-08-03 00:00:37.487534721      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-08-03 00:00:37.487536467    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 59, in detect_raw
2023-08-03 00:00:37.487567511      class_ids = self.interpreter.tensor(self.tensor_output_details[1]["index"])()[0]
2023-08-03 00:00:37.487569427  IndexError: list index out of range
2023-08-03 00:00:44.111274981  172.30.32.1 - - [02/Aug/2023:18:00:44 -0600] "GET /api/stats HTTP/1.1" 200 2439 "-" "HomeAssistant/2023.8.0 aiohttp/3.8.5 Python/3.11" "-"
2023-08-03 00:00:44.684572853  [INFO] Starting go2rtc healthcheck service...
2023-08-03 00:00:53.137514049  172.30.32.1 - - [02/Aug/2023:18:00:53 -0600] "GET /api/stats HTTP/1.1" 200 2440 "-" "HomeAssistant/2023.8.0 aiohttp/3.8.5 Python/3.11" "-"
2023-08-03 00:00:56.194934379  [2023-08-02 18:00:56] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2023-08-03 00:00:56.208535163  [2023-08-02 18:00:56] detector.coral_pci             INFO    : Starting detection process: 382
2023-08-03 00:00:56.212513005  [2023-08-02 18:00:56] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-08-03 00:00:56.213813937  [2023-08-02 18:00:56] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-08-03 00:00:56.217925922  Process detector:coral_pci:
2023-08-03 00:00:56.218781540  Traceback (most recent call last):
2023-08-03 00:00:56.218792321    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-03 00:00:56.218793626      self.run()
2023-08-03 00:00:56.218794787    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-03 00:00:56.218795968      self._target(*self._args, **self._kwargs)
2023-08-03 00:00:56.218802652    File "/opt/frigate/frigate/object_detection.py", line 121, in run_detector
2023-08-03 00:00:56.218804470      detections = object_detector.detect_raw(input_frame)
2023-08-03 00:00:56.218806250    File "/opt/frigate/frigate/object_detection.py", line 71, in detect_raw
2023-08-03 00:00:56.218807838      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-08-03 00:00:56.218809573    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 59, in detect_raw
2023-08-03 00:00:56.218811381      class_ids = self.interpreter.tensor(self.tensor_output_details[1]["index"])()[0]
2023-08-03 00:00:56.218824001  IndexError: list index out of range
2023-08-03 00:01:02.140731855  172.30.32.1 - - [02/Aug/2023:18:01:02 -0600] "GET /api/stats HTTP/1.1" 200 2440 "-" "HomeAssistant/2023.8.0 aiohttp/3.8.5 Python/3.11" "-"
2023-08-03 00:01:06.206479493  [2023-08-02 18:01:06] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-03 00:01:06.215701909  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-03 00:01:06.239958559  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-08-03 00:01:06.241886469  [2023-08-02 18:01:06] frigate.app                    INFO    : Stopping...
s6-rc: info: service nginx-log successfully stopped
2023-08-03 00:01:06.242617207  [2023-08-02 18:01:06] frigate.storage                INFO    : Exiting storage maintainer...
2023-08-03 00:01:06.243019473  [2023-08-02 18:01:06] frigate.record                 INFO    : Exiting recording maintenance...
2023-08-03 00:01:06.243023243  [2023-08-02 18:01:06] frigate.events                 INFO    : Exiting event cleanup...
2023-08-03 00:01:06.244639444  [2023-08-02 18:01:06] frigate.stats                  INFO    : Exiting stats emitter...
2023-08-03 00:01:06.247069272  [2023-08-02 18:01:06] frigate.watchdog               INFO    : Exiting watchdog...
2023-08-03 00:01:06.247073322  [2023-08-02 18:01:06] frigate.record                 INFO    : Exiting recording cleanup...
2023-08-03 00:01:06.247075643  [2023-08-02 18:01:06] frigate.object_processing      INFO    : Exiting object processor...
2023-08-03 00:01:06.399442361  [2023-08-02 18:01:06] frigate.comms.ws               INFO    : Exiting websocket client...
2023-08-03 00:01:07.221423837  [2023-08-02 18:01:07] frigate.events                 INFO    : Exiting event processor...
2023-08-03 00:01:07.223181332  [2023-08-02 18:01:07] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-08-03 00:01:07.227661416  [2023-08-02 18:01:07] watchdog.fg_food_bowl          INFO    : Terminating the existing ffmpeg process...
2023-08-03 00:01:07.227833683  [2023-08-02 18:01:07] watchdog.fg_rccam              INFO    : Terminating the existing ffmpeg process...
2023-08-03 00:01:07.227938439  [2023-08-02 18:01:07] watchdog.fg_food_bowl          INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-03 00:01:07.228048224  [2023-08-02 18:01:07] watchdog.fg_rccam              INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-03 00:01:07.473016602  [2023-08-02 18:01:07] frigate.output                 INFO    : exiting output process...
2023-08-03 00:01:11.426030210  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked shared_memory objects to clean up at shutdown
2023-08-03 00:01:11.426035600    warnings.warn('resource_tracker: There appear to be %d '
2023-08-03 00:01:11.428136220  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-08-03 00:01:11.429998736  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-08-03 00:01:11.434751887  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

PCIe

**Comment by NickM-27** [comment]
CC @blakeblackshear

**Comment by blakeblackshear** [comment]
Frigate uses the mobiledet model from there as the bundled model.

I have tested all the mobilenet models there extensively. They output higher scores, but the false positive scores are also higher. The mobiledet model outperforms all the mobilenet models in all my testing against thousands of examples.

I haven't used teachable machine, so I'm not sure what is different about the model it generates.

**Comment by Gie92** [comment]
Ahh sounds good! Thanks for the quick reply!
I think it's TF2 cause I would get the same error message.

Hopefully I didn't waste your time haha, super new with learning ML and tflite.
Just trying to create a tflite model to detect my dogs, and have their name in HASS so I can track their food habits.

**Comment by blakeblackshear** [comment]
I know others use the EfficientDet models listed there, so I believe they are mostly plug and play still.

**Comment by Heisenberg2980** [comment]
Same issue here with teachable machine, @Gie92 did you manage to train and use a different custom model?

**Comment by Gie92** [comment]
Nope, unfortunately, there's too many variables for me to try to understand haha, trying different converters and code to convert or to compile a certain way does not work...
