### ISSUE TITLE
[Config Support]: Camera Not Connecting

### ISSUE THREAD

**Issue by awilliams84** [blakeblackshear/frigate#7375]
### Describe the problem you are having

Frigate add-on keeps crashing. I think it's something with go2rtc within the add-on that's crashing based on the logs (but I am no expert... a novice at best). That and I have never been able to get frigate to capture/detect any video or still images. The best I get is to pull up the live video from the camera. The initial frigate load shows "No frames have been received, check error logs."
![Screenshot 2023-08-03 130133](https://github.com/blakeblackshear/frigate/assets/17094825/fd6739b1-285d-4f95-a9c6-8308533c2605)

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb
    model:
      path: "/custom_model.tflite"

go2rtc:
  streams:
    front_gate: rtsp://***:*******@192.168.***.***:554/h264Preview_01_main
    indoor_storage: rtsp://***:*******@192.168.***.***5:554/h264Preview_01_main
  webrtc:
    candidates:
      - 192.168.***.***:85555
      - stun:8555


# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous


cameras: 
  front_gate:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_gate
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    detect:
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: true
      retain: 
        days: 10

  indoor_storage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor_storage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    detect:
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: true
      retain: 
        days: 10
```

### Relevant log output

```shell
2023-08-03 05:59:38.329382138  [INFO] Got WebRTC port from supervisor: 8555
2023-08-03 05:59:39.143623639  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-08-03 05:59:39.292064983  [INFO] Starting go2rtc...
2023-08-03 05:59:39.542664285  07:59:39.542 INF go2rtc version 1.2.0 linux/arm64
2023-08-03 05:59:39.544371523  07:59:39.544 INF [api] listen addr=:1984
2023-08-03 05:59:39.545754354  07:59:39.545 INF [rtsp] listen addr=:8554
2023-08-03 05:59:39.547370037  07:59:39.547 INF [srtp] listen addr=:8443
2023-08-03 05:59:39.548568498  07:59:39.548 INF [webrtc] listen addr=:8555
2023-08-03 05:59:43.143737078  [2023-08-03 07:59:43] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-03 05:59:43.232048516  [2023-08-03 07:59:43] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-08-03 05:59:43.247682970  [2023-08-03 07:59:43] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-08-03 05:59:43.257077639  [2023-08-03 07:59:43] peewee_migrate                 INFO    : Starting migrations
2023-08-03 05:59:43.275038367  [2023-08-03 07:59:43] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-03 05:59:43.341181751  [2023-08-03 07:59:43] detector.coral                 INFO    : Starting detection process: 300
2023-08-03 05:59:43.352293232  [2023-08-03 07:59:43] frigate.app                    INFO    : Output process started: 302
2023-08-03 05:59:43.353788044  [2023-08-03 07:59:43] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-08-03 05:59:43.391347590  [2023-08-03 07:59:43] frigate.app                    INFO    : Camera processor started for front_gate: 309
2023-08-03 05:59:43.414506827  [2023-08-03 07:59:43] frigate.app                    INFO    : Camera processor started for indoor_storage: 310
2023-08-03 05:59:43.449121581  [2023-08-03 07:59:43] frigate.app                    INFO    : Capture process started for front_gate: 312
2023-08-03 05:59:43.481270562  [2023-08-03 07:59:43] frigate.app                    INFO    : Capture process started for indoor_storage: 313
2023-08-03 05:59:47.943018675  [INFO] Starting go2rtc healthcheck service...
2023-08-03 05:59:59.436256173  172.30.32.2 - - [03/Aug/2023:07:59:59 +0200] "GET / HTTP/1.1" 200 6641 "-" "HomeAssistantSupervisor/2023.07.1 aiohttp/3.8.4 Python/3.11" "-"
2023-08-03 06:00:08.715746197  [2023-08-03 08:00:08] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-08-03 06:00:08.716192604  Process detector:coral:
2023-08-03 06:00:08.727617838  Traceback (most recent call last):
2023-08-03 06:00:08.727700912    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-08-03 06:00:08.727704319      delegate = Delegate(library, options)
2023-08-03 06:00:08.727707486    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-08-03 06:00:08.727718579      raise ValueError(capture.message)
2023-08-03 06:00:08.727720412  ValueError
2023-08-03 06:00:08.739656682  
2023-08-03 06:00:08.739686700  During handling of the above exception, another exception occurred:
2023-08-03 06:00:08.739688275  
2023-08-03 06:00:08.739690275  Traceback (most recent call last):
2023-08-03 06:00:08.740308051    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-03 06:00:08.740319162      self.run()
2023-08-03 06:00:08.740321810    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-03 06:00:08.740323884      self._target(*self._args, **self._kwargs)
2023-08-03 06:00:08.740326421    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-08-03 06:00:08.740328958      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-08-03 06:00:08.740389162    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-08-03 06:00:08.740490513      self.detect_api = create_detector(detector_config)
2023-08-03 06:00:08.740494606    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-08-03 06:00:08.740496773      return api(detector_config)
2023-08-03 06:00:08.740499551    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-08-03 06:00:08.740603384      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-08-03 06:00:08.740608235    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-08-03 06:00:08.740686420      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-08-03 06:00:08.740689995  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-08-03 06:00:08.740691735  
2023-08-03 06:00:14.202831806  [2023-08-03 08:00:14] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-03 06:00:14.328743202  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-03 06:00:14.449297017  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-08-03 06:00:14.527998150  [2023-08-03 08:00:14] frigate.app                    INFO    : Stopping...
2023-08-03 06:00:14.532914102  [2023-08-03 08:00:14] frigate.storage                INFO    : Exiting storage maintainer...
s6-rc: info: service nginx-log successfully stopped
2023-08-03 06:00:14.536247668  [2023-08-03 08:00:14] frigate.events                 INFO    : Exiting event cleanup...
2023-08-03 06:00:14.540119826  [2023-08-03 08:00:14] frigate.record                 INFO    : Exiting recording cleanup...
2023-08-03 06:00:14.548277807  [2023-08-03 08:00:14] frigate.stats                  INFO    : Exiting stats emitter...
2023-08-03 06:00:14.549622415  [2023-08-03 08:00:14] frigate.record                 INFO    : Exiting recording maintenance...
2023-08-03 06:00:14.549634286  [2023-08-03 08:00:14] frigate.watchdog               INFO    : Exiting watchdog...
2023-08-03 06:00:14.553856887  [2023-08-03 08:00:14] frigate.object_processing      INFO    : Exiting object processor...
2023-08-03 06:00:14.847095509  [2023-08-03 08:00:14] frigate.comms.ws               INFO    : Exiting websocket client...
2023-08-03 06:00:15.200137267  [2023-08-03 08:00:15] frigate.events                 INFO    : Exiting event processor...
2023-08-03 06:00:15.201403875  [2023-08-03 08:00:15] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-08-03 06:00:15.230364475  [2023-08-03 08:00:15] watchdog.indoor_storage        INFO    : Terminating the existing ffmpeg process...
2023-08-03 06:00:15.232109230  [2023-08-03 08:00:15] watchdog.indoor_storage        INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-03 06:00:15.234978279  [2023-08-03 08:00:15] watchdog.front_gate            INFO    : Terminating the existing ffmpeg process...
2023-08-03 06:00:15.237231496  [2023-08-03 08:00:15] watchdog.front_gate            INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-03 06:00:16.066290350  [2023-08-03 08:00:16] frigate.output                 INFO    : exiting output process...
2023-08-03 06:00:20.222441951  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked shared_memory objects to clean up at shutdown
2023-08-03 06:00:20.222454581    warnings.warn('resource_tracker: There appear to be %d '
2023-08-03 06:00:20.238918597  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-08-03 06:00:20.253798468  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-08-03 06:00:20.281202365  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Frigate stats

```json
Stream 0:
Return Code: 1

Error:
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Loaded on Home Assistant Yellow

**Comment by NickM-27** [comment]
You have

```
    model:
      path: "/custom_model.tflite"
```

but it looks like that does not exist, if you are not using a custom model then you should not have that in your config

**Comment by NickM-27** [comment]
Not, it was just explaining how to use another model. This is right above that:

> A TensorFlow Lite model is provided in the container at /cpu_model.tflite and is used by this detector type by default. To provide your own model, bind mount the file into the container and provide the path with model.path.

**Comment by awilliams84** [comment]
> Let's see new logs then

Yessir 👍 

`s6-rc: info: service legacy-services successfully started
2023-08-03 13:39:52.481012706  [INFO] Got IP address from supervisor: 192.168.4.250
2023-08-03 13:39:52.656378882  [INFO] Got WebRTC port from supervisor: 8555
2023-08-03 13:39:53.395234413  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-08-03 13:39:53.526125830  [INFO] Starting go2rtc...
2023-08-03 13:39:53.773346880  15:39:53.773 INF go2rtc version 1.2.0 linux/arm64
2023-08-03 13:39:53.775084286  15:39:53.774 INF [api] listen addr=:1984
2023-08-03 13:39:53.776512914  15:39:53.776 INF [rtsp] listen addr=:8554
2023-08-03 13:39:53.778243764  15:39:53.778 INF [srtp] listen addr=:8443
2023-08-03 13:39:53.779483856  15:39:53.779 INF [webrtc] listen addr=:8555
2023-08-03 13:39:57.254591161  [2023-08-03 15:39:57] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-03 13:39:57.347485420  [2023-08-03 15:39:57] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-08-03 13:39:57.356202933  [2023-08-03 15:39:57] peewee_migrate                 INFO    : Starting migrations
2023-08-03 13:39:57.371577406  [2023-08-03 15:39:57] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-03 13:39:57.443029529  [2023-08-03 15:39:57] detector.coral                 INFO    : Starting detection process: 298
2023-08-03 13:39:57.448875192  [2023-08-03 15:39:57] frigate.app                    INFO    : Output process started: 300
2023-08-03 13:39:57.453007671  [2023-08-03 15:39:57] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-08-03 13:39:57.478105971  [2023-08-03 15:39:57] frigate.app                    INFO    : Camera processor started for front_gate: 304
2023-08-03 13:39:57.512565895  [2023-08-03 15:39:57] frigate.app                    INFO    : Camera processor started for indoor_storage: 308
2023-08-03 13:39:57.531415513  [2023-08-03 15:39:57] frigate.app                    INFO    : Capture process started for front_gate: 309
2023-08-03 13:39:57.564282642  [2023-08-03 15:39:57] frigate.app                    INFO    : Capture process started for indoor_storage: 311
2023-08-03 13:40:02.289700190  [INFO] Starting go2rtc healthcheck service...
2023-08-03 13:40:22.820181419  Process detector:coral:
2023-08-03 13:40:22.820206956  [2023-08-03 15:40:22] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-08-03 13:40:22.826155130  Traceback (most recent call last):
2023-08-03 13:40:22.826407000    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-08-03 13:40:22.826414723      delegate = Delegate(library, options)
2023-08-03 13:40:22.826513889    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-08-03 13:40:22.826517889      raise ValueError(capture.message)
2023-08-03 13:40:22.826708482  ValueError
2023-08-03 13:40:22.826847464  
2023-08-03 13:40:22.826853649  During handling of the above exception, another exception occurred:
2023-08-03 13:40:22.826855131  
2023-08-03 13:40:22.826942834  Traceback (most recent call last):
2023-08-03 13:40:22.827131094    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-03 13:40:22.827136872      self.run()
2023-08-03 13:40:22.827266594    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-03 13:40:22.827272557      self._target(*self._args, **self._kwargs)
2023-08-03 13:40:22.827366742    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-08-03 13:40:22.827370724      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-08-03 13:40:22.827452261    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-08-03 13:40:22.827456168      self.detect_api = create_detector(detector_config)
2023-08-03 13:40:22.827533576    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-08-03 13:40:22.827538094      return api(detector_config)
2023-08-03 13:40:22.827611261    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-08-03 13:40:22.827615613      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-08-03 13:40:22.827693724    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-08-03 13:40:22.827697891      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-08-03 13:40:22.827837576  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-08-03 13:40:22.827843669  
2023-08-03 13:40:28.318795050  [2023-08-03 15:40:28] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-03 13:40:28.484189347  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-03 13:40:28.556102571  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-08-03 13:40:28.578745180  [2023-08-03 15:40:28] frigate.app                    INFO    : Stopping...
2023-08-03 13:40:28.582393315  [2023-08-03 15:40:28] frigate.events                 INFO    : Exiting event cleanup...
2023-08-03 13:40:28.584040170  [2023-08-03 15:40:28] frigate.record                 INFO    : Exiting recording cleanup...
2023-08-03 13:40:28.584054448  [2023-08-03 15:40:28] frigate.storage                INFO    : Exiting storage maintainer...
2023-08-03 13:40:28.586309525  [2023-08-03 15:40:28] frigate.stats                  INFO    : Exiting stats emitter...
2023-08-03 13:40:28.587069767  [2023-08-03 15:40:28] frigate.watchdog               INFO    : Exiting watchdog...
2023-08-03 13:40:28.608647486  [2023-08-03 15:40:28] frigate.object_processing      INFO    : Exiting object processor...
s6-rc: info: service nginx-log successfully stopped
2023-08-03 13:40:28.945008106  [2023-08-03 15:40:28] frigate.comms.ws               INFO    : Exiting websocket client...
2023-08-03 13:40:29.306277469  [2023-08-03 15:40:29] frigate.events                 INFO    : Exiting event processor...
2023-08-03 13:40:29.718913364  [2023-08-03 15:40:29] frigate.record                 INFO    : Exiting recording maintenance...
2023-08-03 13:40:29.729395326  [2023-08-03 15:40:29] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-08-03 13:40:29.743100829  [2023-08-03 15:40:29] watchdog.indoor_storage        INFO    : Terminating the existing ffmpeg process...
2023-08-03 13:40:29.744538110  [2023-08-03 15:40:29] watchdog.indoor_storage        INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-03 13:40:29.746472650  [2023-08-03 15:40:29] watchdog.front_gate            INFO    : Terminating the existing ffmpeg process...
2023-08-03 13:40:29.747687170  [2023-08-03 15:40:29] watchdog.front_gate            INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-03 13:40:32.221541128  15:40:32.220 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 172.30.33.2:59882->192.168.4.205:554: i/o timeout" url=rtsp://admin:greenGA00!@192.168.4.205:554/h264Preview_01_main
2023-08-03 13:40:35.656547739  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 9 leaked shared_memory objects to clean up at shutdown
2023-08-03 13:40:35.656560239    warnings.warn('resource_tracker: There appear to be %d '
2023-08-03 13:40:35.679747970  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-08-03 13:40:35.695250001  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-08-03 13:40:35.719701161  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by NickM-27** [comment]
it can't find your coral

**Comment by awilliams84** [comment]
> try "Frigate NVR **(Full Access)**" version of add-on with disabled protection mode

I am running Full Access already. I downgraded from the Beta version thinking maybe that was the problem initially. But full access both installs

**Comment by awilliams84** [comment]
Still struggling to keep Frigate running

```
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
2023-08-04 19:52:01.671770254  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-08-04 19:52:01.704564829  [INFO] Starting Frigate...
2023-08-04 19:52:01.708168862  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-08-04 19:52:01.870721489  [INFO] Got IP address from supervisor: 192.168.4.250
2023-08-04 19:52:02.031086310  [INFO] Got WebRTC port from supervisor: 8555
2023-08-04 19:52:02.869218299  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-08-04 19:52:03.010725415  [INFO] Starting go2rtc...
2023-08-04 19:52:03.260478068  21:52:03.260 INF go2rtc version 1.2.0 linux/arm64
2023-08-04 19:52:03.262129310  21:52:03.261 INF [api] listen addr=:1984
2023-08-04 19:52:03.263689018  21:52:03.263 INF [rtsp] listen addr=:8554
2023-08-04 19:52:03.265475776  21:52:03.265 INF [srtp] listen addr=:8443
2023-08-04 19:52:03.266917337  21:52:03.266 INF [webrtc] listen addr=:8555
2023-08-04 19:52:06.659745484  [2023-08-04 21:52:06] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-04 19:52:06.745698703  [2023-08-04 21:52:06] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-08-04 19:52:06.755158611  [2023-08-04 21:52:06] peewee_migrate                 INFO    : Starting migrations
2023-08-04 19:52:06.770728779  [2023-08-04 21:52:06] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-04 19:52:06.844424519  [2023-08-04 21:52:06] frigate.app                    INFO    : Output process started: 299
2023-08-04 19:52:06.849007939  [2023-08-04 21:52:06] detector.coral                 INFO    : Starting detection process: 298
2023-08-04 19:52:06.849022680  [2023-08-04 21:52:06] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-08-04 19:52:06.882400355  [2023-08-04 21:52:06] frigate.app                    INFO    : Camera processor started for front_gate: 305
2023-08-04 19:52:06.902846085  [2023-08-04 21:52:06] frigate.app                    INFO    : Camera processor started for indoor_storage: 308
2023-08-04 19:52:06.923389961  [2023-08-04 21:52:06] frigate.app                    INFO    : Capture process started for front_gate: 309
2023-08-04 19:52:06.944901001  [2023-08-04 21:52:06] frigate.app                    INFO    : Capture process started for indoor_storage: 310
2023-08-04 19:52:11.692582629  [INFO] Starting go2rtc healthcheck service...
2023-08-04 19:52:32.155839567  Process detector:coral:
2023-08-04 19:52:32.156202189  [2023-08-04 21:52:32] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-08-04 19:52:32.164736528  Traceback (most recent call last):
2023-08-04 19:52:32.165012689    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-08-04 19:52:32.165020892      delegate = Delegate(library, options)
2023-08-04 19:52:32.165024336    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-08-04 19:52:32.165041614      raise ValueError(capture.message)
2023-08-04 19:52:32.165043577  ValueError
2023-08-04 19:52:32.168195103  
2023-08-04 19:52:32.168210603  During handling of the above exception, another exception occurred:
2023-08-04 19:52:32.168211992  
2023-08-04 19:52:32.168213899  Traceback (most recent call last):
2023-08-04 19:52:32.168470579    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-04 19:52:32.168477264      self.run()
2023-08-04 19:52:32.168479893    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-04 19:52:32.168481875      self._target(*self._args, **self._kwargs)
2023-08-04 19:52:32.177490204    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-08-04 19:52:32.177521851      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-08-04 19:52:32.177524351    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-08-04 19:52:32.177526499      self.detect_api = create_detector(detector_config)
2023-08-04 19:52:32.177529073    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-08-04 19:52:32.177654312      return api(detector_config)
2023-08-04 19:52:32.177658941    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-08-04 19:52:32.177663497      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-08-04 19:52:32.177666867    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-08-04 19:52:32.177774161      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-08-04 19:52:32.177779142  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-08-04 19:52:32.177780735  
2023-08-04 19:52:37.671486449  [2023-08-04 21:52:37] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-04 19:52:37.760493601  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-04 19:52:37.847852066  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-08-04 19:52:37.882567467  [2023-08-04 21:52:37] frigate.app                    INFO    : Stopping...
2023-08-04 19:52:37.902334405  [2023-08-04 21:52:37] frigate.record                 INFO    : Exiting recording cleanup...
2023-08-04 19:52:37.905262325  [2023-08-04 21:52:37] frigate.record                 INFO    : Exiting recording maintenance...
2023-08-04 19:52:37.911927926  [2023-08-04 21:52:37] frigate.stats                  INFO    : Exiting stats emitter...
2023-08-04 19:52:37.911942370  [2023-08-04 21:52:37] frigate.events                 INFO    : Exiting event cleanup...
2023-08-04 19:52:37.911945870  [2023-08-04 21:52:37] frigate.storage                INFO    : Exiting storage maintainer...
2023-08-04 19:52:37.915759623  [2023-08-04 21:52:37] frigate.watchdog               INFO    : Exiting watchdog...
2023-08-04 19:52:37.915776419  [2023-08-04 21:52:37] frigate.object_processing      INFO    : Exiting object processor...
s6-rc: info: service nginx-log successfully stopped
2023-08-04 19:52:38.335794858  [2023-08-04 21:52:38] frigate.comms.ws               INFO    : Exiting websocket client...
2023-08-04 19:52:38.644569259  [2023-08-04 21:52:38] frigate.events                 INFO    : Exiting event processor...
2023-08-04 19:52:38.648639044  [2023-08-04 21:52:38] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-08-04 19:52:38.688912441  [2023-08-04 21:52:38] watchdog.indoor_storage        INFO    : Terminating the existing ffmpeg process...
2023-08-04 19:52:38.690713903  [2023-08-04 21:52:38] watchdog.indoor_storage        INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-04 19:52:38.695737353  [2023-08-04 21:52:38] watchdog.front_gate            INFO    : Terminating the existing ffmpeg process...
2023-08-04 19:52:38.696911662  [2023-08-04 21:52:38] watchdog.front_gate            INFO    : Waiting for ffmpeg to exit gracefully...
```

**Comment by JohnyBeGood** [comment]
> try "Frigate NVR **(Full Access)**" version of add-on with disabled protection mode

Thank you, Sir! 
I was getting the same error "No EdgeTPU was detected" and after I turned off protection mode it detected it right away and add-on never crashed. This is the full Home Assitant version on Dell OptiPlex 9020 bare metal.

![image](https://github.com/blakeblackshear/frigate/assets/1755800/3b6c6389-e948-4c9c-877b-70f6378a7442)
