### ISSUE TITLE
[Support]:   dev-00b9a49 all streams go black 

### ISSUE THREAD

**Issue by johnvprcam24573455623** [blakeblackshear/frigate#7395]
### Describe the problem you are having

Frigate dev-00b9a49 stops working and all streams go black , I also see a memory leak that grows, and the container reaches the max. I also tried to restart with a health check in the docker compose but its not working.

### Version

dev-00b9a49

### Frigate config file

```yaml
ffmpeg:
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: usb

birdseye:
  enabled: True
  mode: continuous    

go2rtc:
  streams:
 
    wcam1:
      - "rtsp://10.10.40.211:8554/1080p?mp4"
    wcam1_sub:  
      - "rtsp://10.10.40.211:8554/360p?mp4"


cameras:

  wcam2:
    ffmpeg:
#      input_args: preset-rtsp-udp
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/wcam2
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/wcam2_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

------------------------------------------

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    mem_limit: "2g"   
 #   image: ghcr.io/blakeblackshear/frigate:stable
    image: ghcr.io/blakeblackshear/frigate:dev-00b9a49

    shm_size: "256mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      #- /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/config.yml:/config/config.yml 
      - /home/frigate/config:/config 
      - /media/frigate:/media/frigate
      - /home/media:/media/frigate
      
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
          
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
      - "8554:8554" # Birdseye In v 0.12
      
    # https://github.com/blakeblackshear/frigate/pull/62    # https://github.com/blakeblackshear/frigate/issues/2299
#    restart: unless-stopped
    restart: on-failure
    healthcheck:
#      test: ["CMD", "curl", "-sI", "http://127.0.0.1:5000/"]
#      test: ["CMD", "curl", "-sI", "/api/version"]
      test: ["CMD", "curl", "-sI", "/api/stats"]
      interval: 30s
      timeout: 1s
      retries: 10
```

### Relevant log output

```shell
2023-08-04 18:28:17.947936023  Exception in thread detected_frames_processor:
2023-08-04 18:28:17.948012350  Traceback (most recent call last):
2023-08-04 18:28:17.948018695    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-08-04 18:28:17.949960841      self.run()
2023-08-04 18:28:17.949971135    File "/opt/frigate/frigate/object_processing.py", line 1028, in run
2023-08-04 18:28:17.950621641      self.video_output_queue.put(
2023-08-04 18:28:17.950631499    File "/opt/frigate/frigate/util/builtin.py", line 91, in put
2023-08-04 18:28:17.950951430      raise Full
2023-08-04 18:28:17.950957499  queue.Full
2023-08-04 18:28:34.593501039  Exception in thread Thread-15:
2023-08-04 18:28:34.593557240  Traceback (most recent call last):
2023-08-04 18:28:34.593563990    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-08-04 18:28:34.594446909      self.run()
2023-08-04 18:28:34.594456447    File "/opt/frigate/frigate/output.py", line 210, in run
2023-08-04 18:28:34.594740461      ws.send(buf, binary=True)
2023-08-04 18:28:34.594747612    File "/usr/local/lib/python3.9/dist-packages/ws4py/websocket.py", line 303, in send
2023-08-04 18:28:34.595873880      self._write(m)
2023-08-04 18:28:34.595883910    File "/usr/local/lib/python3.9/dist-packages/ws4py/websocket.py", line 285, in _write
2023-08-04 18:28:34.596159087      self.sock.sendall(b)
2023-08-04 18:28:34.596236084  ConnectionResetError: [Errno 104] Connection reset by peer
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Mixed

### Camera make and model

wyze reolink

**Comment by LckySndays** [comment]
@blakeblackshear @NickM-27 @hawkeye217 
I think the error is similar enough with my encountered problem #7257

**Comment by blakeblackshear** [comment]
There have been many commits since this build. Please try the current dev build.

**Comment by blakeblackshear** [comment]
These "Connection reset by peer" messages happen during normal usage of the frontend when the websocket is disconnected. It is not the source of any problems and can be ignored.
