### ISSUE TITLE
[Support]: Frigate addon won't stay online (keeps crashing)

### ISSUE THREAD

**Issue by awilliams84** [blakeblackshear/frigate#7397]
### Describe the problem you are having

I cannot get Frigate to stay connected. I can start it, but if I leave it for a few minutes and I click on "Frigate" in the side bar, it tells me "The add-on is not running. Do you want to start it now?"

Running on a Home Assistant Yellow with USB Coral

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.4.250
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: ***
  stats_interval: 60

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    front_gate: 
      - rtsp://admin:***@192.168.4.206:554/h264Preview_01_main
      - "ffmpeg:front_gate#audio=aac"
    indoor_storage: 
      - rtsp://admin:***@192.168.4.205:554/h264Preview_01_main
      - "ffmpeg:indoor_storage#audio=aac"
  webrtc:
    candidates:
      - 192.168.4.250:85555
      - stun:8555


# Include all cameras by default in Birdseye view
birdseye:
  enabled: True
  mode: continuous


cameras: 
  front_gate:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_gate
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    detect:
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: true
      retain: 
        days: 10

  indoor_storage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/indoor_storage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    detect:
      fps: 5
    objects:
      track:
        - person
        - cat
        - dog
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain: 
        default: 2
    record:
      enabled: true
      retain: 
        days: 10
```

### Relevant log output

```shell
2023-08-05 07:36:13.808101678  09:36:13.807 INF [rtsp] listen addr=:8554
2023-08-05 07:36:13.810974910  09:36:13.810 INF [srtp] listen addr=:8443
2023-08-05 07:36:13.812990267  09:36:13.812 INF [webrtc] listen addr=:8555
2023-08-05 07:36:17.329423771  [2023-08-05 09:36:17] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-05 07:36:17.421097915  [2023-08-05 09:36:17] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-08-05 07:36:17.429825333  [2023-08-05 09:36:17] peewee_migrate                 INFO    : Starting migrations
2023-08-05 07:36:17.445345347  [2023-08-05 09:36:17] peewee_migrate                 INFO    : There is nothing to migrate
2023-08-05 07:36:17.519588953  [2023-08-05 09:36:17] frigate.app                    INFO    : Output process started: 303
2023-08-05 07:36:17.559564247  [2023-08-05 09:36:17] frigate.app                    INFO    : Camera processor started for front_gate: 307
2023-08-05 07:36:17.570727719  [2023-08-05 09:36:17] frigate.app                    INFO    : Camera processor started for indoor_storage: 310
2023-08-05 07:36:17.598703333  [2023-08-05 09:36:17] frigate.app                    INFO    : Capture process started for front_gate: 312
2023-08-05 07:36:17.618633870  [2023-08-05 09:36:17] frigate.app                    INFO    : Capture process started for indoor_storage: 313
2023-08-05 07:36:22.329700433  [INFO] Starting go2rtc healthcheck service...
2023-08-05 07:36:23.666719808  [2023-08-05 09:36:23] frigate.video                  ERROR   : indoor_storage: Unable to read frames from ffmpeg process.
2023-08-05 07:36:23.668161063  [2023-08-05 09:36:23] frigate.video                  ERROR   : indoor_storage: ffmpeg process is not running. exiting capture thread...
2023-08-05 07:36:26.186865696  [2023-08-05 09:36:26] frigate.comms.mqtt             ERROR   : Unable to publish to front_gate/all: client is not connected
2023-08-05 07:36:31.656129790  09:36:31.655 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error=EOF
2023-08-05 07:36:37.719105623  [2023-08-05 09:36:37] watchdog.indoor_storage        ERROR   : Ffmpeg process crashed unexpectedly for indoor_storage.
2023-08-05 07:36:37.719119104  [2023-08-05 09:36:37] watchdog.indoor_storage        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-08-05 07:36:37.719133067  [2023-08-05 09:36:37] ffmpeg.indoor_storage.detect   ERROR   : rtsp://127.0.0.1:8554/indoor_storage: Invalid data found when processing input
2023-08-05 07:36:42.827179269  [2023-08-05 09:36:17] detector.coral                 INFO    : Starting detection process: 302
2023-08-05 07:36:42.827192195  [2023-08-05 09:36:17] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-08-05 07:36:42.830792583  [2023-08-05 09:36:42] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-08-05 07:36:42.831370611  Process detector:coral:
2023-08-05 07:36:42.839455040  Traceback (most recent call last):
2023-08-05 07:36:42.839905736    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-08-05 07:36:42.839915384      delegate = Delegate(library, options)
2023-08-05 07:36:42.840166640    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-08-05 07:36:42.840174158      raise ValueError(capture.message)
2023-08-05 07:36:42.840489098  ValueError
2023-08-05 07:36:42.841269289  
2023-08-05 07:36:42.841281363  During handling of the above exception, another exception occurred:
2023-08-05 07:36:42.841282826  
2023-08-05 07:36:42.841614080  Traceback (most recent call last):
2023-08-05 07:36:42.842139961    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-05 07:36:42.842151386      self.run()
2023-08-05 07:36:42.842506899    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-05 07:36:42.842515344      self._target(*self._args, **self._kwargs)
2023-08-05 07:36:42.842792858    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-08-05 07:36:42.842801191      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-08-05 07:36:42.843022595    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-08-05 07:36:42.843028391      self.detect_api = create_detector(detector_config)
2023-08-05 07:36:42.843286461    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-08-05 07:36:42.843292276      return api(detector_config)
2023-08-05 07:36:42.843519680    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-08-05 07:36:42.843525106      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-08-05 07:36:42.843743880    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-08-05 07:36:42.843748991      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-08-05 07:36:42.844024950  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-08-05 07:36:42.844031153  
2023-08-05 07:36:48.307973170  [2023-08-05 09:36:48] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-05 07:36:48.419526799  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-05 07:36:48.530957189  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-08-05 07:36:48.547600503  [2023-08-05 09:36:48] frigate.app                    INFO    : Stopping...
s6-rc: info: service nginx-log successfully stopped
2023-08-05 07:36:48.567422824  [2023-08-05 09:36:48] frigate.record                 INFO    : Exiting recording maintenance...
2023-08-05 07:36:48.568714507  [2023-08-05 09:36:48] frigate.record                 INFO    : Exiting recording cleanup...
2023-08-05 07:36:48.570972879  [2023-08-05 09:36:48] frigate.watchdog               INFO    : Exiting watchdog...
2023-08-05 07:36:48.570984583  [2023-08-05 09:36:48] frigate.storage                INFO    : Exiting storage maintainer...
2023-08-05 07:36:48.575576344  [2023-08-05 09:36:48] frigate.stats                  INFO    : Exiting stats emitter...
2023-08-05 07:36:48.578531076  [2023-08-05 09:36:48] frigate.events                 INFO    : Exiting event cleanup...
2023-08-05 07:36:48.579949646  [2023-08-05 09:36:48] frigate.object_processing      INFO    : Exiting object processor...
2023-08-05 07:36:49.005463281  [2023-08-05 09:36:49] frigate.comms.ws               INFO    : Exiting websocket client...
2023-08-05 07:36:49.321598700  [2023-08-05 09:36:49] frigate.events                 INFO    : Exiting event processor...
2023-08-05 07:36:49.321611755  [2023-08-05 09:36:49] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-08-05 07:36:49.341569314  [2023-08-05 09:36:49] watchdog.indoor_storage        INFO    : Terminating the existing ffmpeg process...
2023-08-05 07:36:49.341587425  [2023-08-05 09:36:49] watchdog.indoor_storage        INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-05 07:36:49.347856605  [2023-08-05 09:36:49] watchdog.front_gate            INFO    : Terminating the existing ffmpeg process...
2023-08-05 07:36:49.349811148  [2023-08-05 09:36:49] watchdog.front_gate            INFO    : Waiting for ffmpeg to exit gracefully...
2023-08-05 07:36:49.864292138  [2023-08-05 09:36:49] frigate.output                 INFO    : exiting output process...
2023-08-05 07:36:54.254559669  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked shared_memory objects to clean up at shutdown
2023-08-05 07:36:54.254572354    warnings.warn('resource_tracker: There appear to be %d '
2023-08-05 07:36:54.277999822  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-08-05 07:36:54.290715939  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-08-05 07:36:54.315345944  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
Where do I run this? I tried to click "FFPROBE" in "System" for one of the cameras, but it keeps spinning with no result
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink E1 Outdoor and E1 Zoom

**Comment by NickM-27** [comment]
Your coral is not online, most likely because it is not getting enough power from the yellow. More info on this is here: https://github.com/blakeblackshear/frigate/discussions/5951

**Comment by awilliams84** [comment]
> Your coral is not online, most likely because it is not getting enough power from the yellow. More info on this is here: #5951

I read that before, but then I read that it should work on USB... My Yellow does run from POE. I wonder if that makes a difference. It might be time to scrap Frigate as an add on and figure out another way. I could try to run it from my QNAP NAS, but I just migrated HA from the NAS to the Yellow because it was unreliable.

**Comment by NickM-27** [comment]
You can try a USB powered hub but the USB ports on the yellow and other sbcs generally don't apply enough power.
