### ISSUE TITLE
[Detector Support]: USB CORAL Devices not detected

### ISSUE THREAD

**Issue by arrikhan** [blakeblackshear/frigate#7434]
### Describe the problem you are having

Moved my frigate docker container install from a raspberry pi 4 to macmini (ubuntu install) by relocating 2x USB corals and docker-compose files to rebuild/reload frigate.

Removed ffmpeg entries (cannot find appropriate driver for macmini 2012) and rebuilt/reloaded docker image/container.

USB corals devices fail to be detected. Devices show in lsusb and LED bright/solid on devices.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: x.x.x.x 
  user: 'user'
  password: 'password'

cameras: 
  driveway:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://x.x.x.x:8554/driveway
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - clips
            - rtmp
    record:
      events:
        required_zones:
          - front-driveway
          - front-porch
    motion:
      mask: 0,0,897,0,1280,0,1280,352,0,381
    zones:
      front-drive:
        coordinates: 671,653,1259,660,1215,345,920,353
        objects:
          - car
          - license_plate
      front-driveway:
        coordinates: 1159,337,1149,271,947,277,951,341
        objects:
          - person
          - cat
          - dog
      front-porch:
        coordinates: 0,720,447,720,349,327,0,351
        objects:
          - person
          - cat
          - dog
  side-entrance:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://x.x.x.x:8554/side-entrance
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - clips
            - rtmp
  kamado-cam:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://x.x.x.x:8554/kamado-cam
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - clips
            - rtmp
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1

#ffmpeg:
  #hwaccel_args: preset-rpi-64-h264

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - dog
    - cat
    - car
    - bicycle
    - license_plate
    - package
    - amazon
    - bird

snapshots:
  enabled: True
  timestamp: True
  bounding_box: True
  retain:
    default: 7
```

### docker-compose file or Docker CLI command

```yaml
version: '3'
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true
    restart: unless-stopped
    tmpfs:
      - /tmp/cache:rw,size=1000000000
    devices:
      - /dev/bus/usb:/dev/bus/usb
    shm_size: 64m
    volumes:
      - ./storage:/media/frigate
      - ./config/config.yml:/config/config.yml
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FRIGATE_RTSP_PASSWORD=xxx
      - PLUS_API_KEY=xxx
    ports:
      - '5000:5000'
      - '8554:8554'
      - '8555:8555/tcp'
      - '8555:8555/udp'
```

### Relevant log output

```shell
2023-08-10 02:59:33.431363931  [2023-08-10 02:59:08] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb:0
2023-08-10 02:59:33.431571113  Process detector:coral1:
2023-08-10 02:59:33.431575918  [2023-08-10 02:59:33] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-08-10 02:59:33.432929160  Traceback (most recent call last):
2023-08-10 02:59:33.432945836    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-08-10 02:59:33.432948241      delegate = Delegate(library, options)
2023-08-10 02:59:33.432957753    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-08-10 02:59:33.432959816      raise ValueError(capture.message)
2023-08-10 02:59:33.432968211  ValueError
2023-08-10 02:59:33.433001130  
2023-08-10 02:59:33.433004766  During handling of the above exception, another exception occurred:
2023-08-10 02:59:33.433006489  
2023-08-10 02:59:33.433008454  Traceback (most recent call last):
2023-08-10 02:59:33.433078710    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-10 02:59:33.433081150      self.run()
2023-08-10 02:59:33.433083350    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-10 02:59:33.433085280      self._target(*self._args, **self._kwargs)
2023-08-10 02:59:33.433089693    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-08-10 02:59:33.433104436      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-08-10 02:59:33.433112369    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-08-10 02:59:33.433115226      self.detect_api = create_detector(detector_config)
2023-08-10 02:59:33.433117422    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-08-10 02:59:33.433119401      return api(detector_config)
2023-08-10 02:59:33.433121641    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-08-10 02:59:33.433139169      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-08-10 02:59:33.433141999    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-08-10 02:59:33.433154003      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-08-10 02:59:33.433156317  ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

~/docker-frigate$ lsusb
Bus 002 Device 005: ID 05ac:8242 Apple, Inc. Built-in IR Receiver
Bus 002 Device 008: ID 05ac:828a Apple, Inc. Bluetooth USB Host Controller
Bus 002 Device 004: ID 0a5c:4500 Broadcom Corp. BCM2046B1 USB 2.0 Hub (part of BCM2046 Bluetooth)
Bus 002 Device 003: ID 0424:2512 Microchip Technology, Inc. (formerly SMSC) USB 2.0 Hub
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
**Bus 004 Device 003: ID 1a6e:089a Global Unichip Corp. 
Bus 004 Device 002: ID 1a6e:089a Global Unichip Corp.** 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by NickM-27** [comment]
> Bus 004 Device 003: ID 1a6e:089a Global Unichip Corp.

This means the coral is not initialized. Once it is initialized it will have the name `Google Inc.`

If this doesn't change after trying to run frigate then it's likely a power issue and the corals aren't getting enough power.
