### ISSUE TITLE
[Config Support]: TensorRT Detector not working

### ISSUE THREAD

**Issue by futuredj** [blakeblackshear/frigate#7457]
### Describe the problem you are having

I've been trying to enable tensor as a detector to my setup but I am getting this error in logs no matter what ive tried in this forum. I'm probably just being stupid but help me out please :) 

Ubuntu 22.04
Docker 24.0.5
CUDA 12.2
QUADRO M2000 535.86.10

Hardware decoding and restream is working ok providing I disable tensor. 

I have bind libnvrtc.so.12.2.128 > libnvrtc.so and trt-models using protainer and confirmed the generated models are accessable by navigating to them in the docker console.  

![portainer](https://github.com/blakeblackshear/frigate/assets/9522017/bb9ac3d8-a5c5-4907-87f6-a5fcc4b2b288)

![nvidiasmi](https://github.com/blakeblackshear/frigate/assets/9522017/3a135554-2e3a-4cdf-830a-84175e2512f1)

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com

go2rtc:
  streams:
    portable:
      - rtsp://@192.168.40.104:554/stream1
      - "ffmpeg:portable#audio=aac"
    boys:
      - rtsp://@192.168.40.246:554/stream1
      - "ffmpeg:boys#audio=aac"
    garden:
      - rtsp://@192.168.40.40:554/stream1
      - "ffmpeg:garden#audio=aac"
    driveway:
      - rtsp://@192.168.40.39:554/stream1
      - "ffmpeg:driveway#audio=aac"
    frontdoor:
      - rtsp://@192.168.40.101:554/h264Preview_01_main
      - "ffmpeg:frontdoor#audio=opus"

cameras:
  Portable:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/portable
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
  Boys:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/boys
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 25
  Garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 25
  Driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 25
  Frontdoor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - detect
            - record
    detect:
      width: 2560
      height: 1920
      fps: 29

record:
  enabled: True
  retain:
    days: 14
    mode: active_objects
  events:
    retain:
      default: 14
      mode: active_objects

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect: -f rawvideo -pix_fmt yuv420p
    rtmp: -c:v copy -c:a aac -f flv
  
birdseye:
  enabled: True
  restream: True
  width: 1920
  height: 1080
  quality: 1
  mode: motion

#detectors:
#  cpu:
#    type: cpu
#    num_threads: 10

detectors:
  tensorrt:
    type: tensorrt

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### Relevant log output

```shell
2023-08-12 15:16:16.271270262  Traceback (most recent call last):
2023-08-12 15:16:16.271273236    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-08-12 15:16:16.271274603      self.run()
2023-08-12 15:16:16.271278118    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-08-12 15:16:16.271279922      self._target(*self._args, **self._kwargs)
2023-08-12 15:16:16.271281492    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-08-12 15:16:16.271295603      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-08-12 15:16:16.271319200    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-08-12 15:16:16.271321638      self.detect_api = create_detector(detector_config)
2023-08-12 15:16:16.271323531    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-08-12 15:16:16.271325202      return api(detector_config)
2023-08-12 15:16:16.271326991    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 198, in __init__
2023-08-12 15:16:16.271328446      assert (
2023-08-12 15:16:16.271330328  AssertionError: TensorRT libraries not found, tensorrt detector not present
2023-08-12 15:16:16.271358863  Exception ignored in: <function TensorRtDetector.__del__ at 0x7fa737b6d550>
2023-08-12 15:16:16.271361278  Traceback (most recent call last):
2023-08-12 15:16:16.271370159    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-08-12 15:16:16.271554895      if self.outputs is not None:
2023-08-12 15:16:16.271557378  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
```

### Operating system

Debian

### Install method

Docker CLI

### Coral version

Other

**Comment by NickM-27** [comment]
What is your docker run command?

**Comment by futuredj** [comment]
I have no idea how to get the run command from portainer sorry. Bit of a noob with docker lol

![port](https://github.com/blakeblackshear/frigate/assets/9522017/eb73ed71-fea9-4aa8-aa2f-925b5418c3cc)

**Comment by futuredj** [comment]
What should my docker run file include?

**Comment by NickM-27** [comment]
that single .so file is not enough to fix this, and it's likely that portainer is going to cause confusion here. You need portainer to deploy frigate with the nvidia driver. I have no idea if that is even possible because running in native docker without portainer is recommended way in the docs.

**Comment by NickM-27** [comment]
relevant docs: https://docs.frigate.video/configuration/hardware_acceleration#docker-compose---nvidia-gpu

**Comment by NickM-27** [comment]
also, what image are you using?

**Comment by futuredj** [comment]
So I used that doc you referenced to set up hardware decoding and that is working fine. 

I'm using the ghcr.io/blakeblackshear/frigate:stable image.

Can you show me what a typical docker run file would look like that is using tensor and deploying the nvidia driver?

Thanks

**Comment by futuredj** [comment]
Also I have installed the nvidia container kit and that is working with hardware decoding

**Comment by NickM-27** [comment]
Well there's the problem, you're not using the tensorrt image like it says to in the detector docs.

**Comment by futuredj** [comment]
https://hub.docker.com/r/yeahme49/frigatetensor this?

It says use frigate 0.12 instead of this. Should I try it anyway?

**Comment by NickM-27** [comment]
https://docs.frigate.video/configuration/detectors#nvidia-tensorrt-detector

> NVidia GPUs may be used for object detection using the TensorRT libraries. Due to the size of the additional libraries, this detector is only provided in images with the -tensorrt tag suffix. This detector is designed to work with Yolo models for object detection.

So it would be ghcr.io/blakeblackshear/frigate:stable-tensorrt

**Comment by futuredj** [comment]
Thanks sorry im a noob :D

**Comment by futuredj** [comment]
Many thanks, all working :)
