### ISSUE TITLE
[Support]: devcontainer fails to start

### ISSUE THREAD

**Issue by AskAlice** [blakeblackshear/frigate#7502]
### Describe the problem you are having

with an unchanged dev branch, whether I start from WSL or windows, my devcontainer for some reason can't seem to find the initialize script.
[11213 ms] Start: Run: /bin/sh -c .devcontainer/initialize.sh
/bin/sh: 1: .devcontainer/initialize.sh: not found

### Version

dev

### Frigate config file

```yaml
n/a
```

### Relevant log output

```shell
[43 ms] Dev Containers 0.304.0 in VS Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97).
[41 ms] Start: Resolving Remote
[64 ms] Start: Run: wsl -l -v
[171 ms] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u c:\Users\alice\frigate
[375 ms] Start: Run: wsl -d Ubuntu-22.04 -e /bin/sh -c cd '/c/Users/alice/frigate' && /bin/sh
[396 ms] Start: Run in host: id -un
[491 ms] alice
[492 ms] 
[492 ms] Start: Run in host: getent passwd alice
[494 ms] Start: Run in host: echo ~
[495 ms] /home/alice
[495 ms] 
[495 ms] Start: Run in host: test -x '/home/alice/.vscode-remote-containers/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/node'
[496 ms] 
[496 ms] 
[496 ms] Exit code 1
[497 ms] Start: Run in host: test -x '/home/alice/.vscode-server/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/node'
[498 ms] 
[498 ms] 
[498 ms] Start: Run in host: test -f '/home/alice/.vscode-server/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/node_modules/node-pty/package.json'
[499 ms] 
[499 ms] 
[499 ms] Start: Run in host: test -f '/home/alice/.vscode-remote-containers/dist/vscode-remote-containers-server-0.304.0.js'
[500 ms] 
[500 ms] 
[502 ms] userEnvProbe: loginInteractiveShell (default)
[503 ms] userEnvProbe: not found in cache
[503 ms] userEnvProbe shell: /usr/bin/zsh
[2513 ms] Start: Run in Host: /bin/sh 
[2516 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[2813 ms] userEnvProbe is taking longer than 2 seconds. Process tree:
  111959: /usr/bin/zsh -lic echo -n 0c92f669-d3ef-406f-807f-425a3654147f; cat /proc/self/environ; echo -n 0c92f669-d3ef-406f-807f-425a3654147f 
    112304: /usr/bin/zsh -lic echo -n 0c92f669-d3ef-406f-807f-425a3654147f; cat /proc/self/environ; echo -n 0c92f669-d3ef-406f-807f-425a3654147f 
      112308: manpath 
[5142 ms] userEnvProbe PATHs:
Probe:     '/home/alice/anaconda3/bin:/home/alice/anaconda3/condabin:/home/alice/.bun/bin:/run/user/1000/fnm_multishells/113364_1692291487604/bin:/home/alice/.fnm:/home/alice/.npm-packages/bin:/home/alice/.nvm/versions/node/v16.17.0/bin:/home/alice/.pyenv/bin:/home/alice/go/bin:/c/Windows/System32:/home/alice/minikube:/home/alice/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin:/c/Program Files/Common Files/Oracle/Java/javapath:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/libnvvp:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.0/libnvvp:/c/PROGRA~1/NVIDIA~2/CUDA/v11.3/bin:/c/PROGRA~1/NVIDIA~2/CUDA/v11.3/libnvvp:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/PROGRA~1/GITHUB~1:/c/PROGRA~1/dotnet:/c/PROGRA~1/Amazon/AWSCLIV2:/c/PROGRA~1/MICROS~1/bin:/c/PROGRA~1/Git/cmd:/c/PROGRA~1/OJDKBU~1/JAVA-1~1.14-/bin:/c/PROGRA~2/GnuPG/bin:/c/PROGRA~1/Go/bin:/c/PROGRA~1/PuTTY:/c/PROGRA~2/NVIDIA~1/PhysX/Common:/c/laragon/bin/php/PHP-80~1.10-:/c/PROGRA~3/COMPOS~1/bin:/c/PROGRA~3/CHOCOL~2/bin:/c/k/KUBERN~1/node/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/PROGRA~1/CMake/bin:/c/PROGRA~1/Docker/Docker/RESOUR~1/bin:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Users/alice/AppData/Roaming/nvm:/c/Program Files/nodejs:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Git/cmd:/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.5.0:/c/Program Files/dotnet:/c/Program Files/Nordic Semiconductor/nrf-command-line-tools/bin:/c/Program Files/MATLAB/MATLAB Runtime/v910/runtime/win64:/c/HashiCorp/Vagrant/bin:/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin:/c/Program Files (x86)/cloudflared:/c/Program Files/Graphviz/bin:/c/Program Files/Calibre2:/Docker/host/bin:/c/Program Files/usbipd-win:/c/Program Files/Mullvad VPN/resources:/c/Program Files/Cloudflare/Cloudflare WARP:/c/Program Files/FileBot:/c/Program Files/WireGuard:/c/Program Files/Go/bin:/c/Users/alice/scoop/shims:/c/PROGRA~1/nodejs:/c/PROGRA~1/Microsoft VS Code/bin:/c/Users/alice/.cargo/bin:/c/Users/alice/AppData/Roaming/npm:/c/Users/alice/.pyenv/pyenv-win/bin:/c/Users/alice/.pyenv/pyenv-win/shims:/c/Users/alice/AppData/Local/Microsoft/WindowsApps:/c/Program Files (x86)/Nmap:/c/platform-tools:/c/Users/alice/bin/SysinternalsSuite:/c/Users/alice/go/bin:/c/Users/alice/bin:/c/Program Files/heroku/bin:/c/ProgramData/chocolatey/bin:/c/Users/alice/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/alice/AppData/Local/Fig/latest:/c/Users/alice/jadx/bin:/c/Users/alice/.krew/bin:/c/Users/alice/go/bin:/c/Users/alice/AppData/Local/Microsoft/WinGet/Links:/c/Users/alice/AppData/Local/spicetify:/c/Program Files/RedHat/Podman:/c/depot_tools:/c/Users/alice/go/bin:/home/alice/.krew/bin:/home/linuxbrew/.linuxbrew/bin:/home/alice/bin:/home/alice/.kube/plugins/jordanwilson230:/home/alice/.krew/bin:/home/alice/depot_tools'
Container: None
[5143 ms] Setting up container for folder or workspace: /c/Users/alice/frigate
[5158 ms] Start: Check Docker is running
[5158 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[5207 ms] Server API version: 1.42
[5208 ms] Start: Run in Host: docker volume ls -q
[5249 ms] Start: Run in Host: tar --no-same-owner -x -f -
[5481 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=c:\Users\alice\frigate --filter label=vsch.quality=stable
[5529 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\alice\frigate --filter label=devcontainer.config_file=file:///c%3A/Users/alice/frigate/.devcontainer/devcontainer.json
[5572 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\alice\frigate
[5620 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\alice\frigate
[5668 ms] Start: Run in Host: /home/alice/.vscode-server/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/node /home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /c/Users/alice/frigate --id-label devcontainer.local_folder=c:\Users\alice\frigate --id-label devcontainer.config_file=file:///c%3A/Users/alice/frigate/.devcontainer/devcontainer.json --log-level debug --log-format json --config /tmp/devcontainer-config-af8b7413-bb7d-40f7-9605-a1ab47142682/.devcontainer/devcontainer.json --mount-workspace-git-root true
[5815 ms] @devcontainers/cli 0.50.0. Node.js v16.17.1. linux 5.15.90.1-microsoft-standard-WSL2+ x64.
[5815 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\alice\frigate --filter label=devcontainer.config_file=file:///c%3A/Users/alice/frigate/.devcontainer/devcontainer.json
[5865 ms] Start: Run in Host: /home/alice/.vscode-server/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/node /home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-d87b4d0d-9d12-4579-9874-e3f5f41b07b51692291483657 --workspace-folder /c/Users/alice/frigate --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\alice\frigate --id-label devcontainer.config_file=file:///c%3A/Users/alice/frigate/.devcontainer/devcontainer.json --log-level debug --log-format json --config /tmp/devcontainer-config-af8b7413-bb7d-40f7-9605-a1ab47142682/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-e095127f-f3fc-4f4e-a6ee-2161c7e031fe.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[6011 ms] @devcontainers/cli 0.50.0. Node.js v16.17.1. linux 5.15.90.1-microsoft-standard-WSL2+ x64.
[6011 ms] Start: Run: docker buildx version
[6087 ms] github.com/docker/buildx v0.10.4 c513d34049e499c53468deac6c4267ee72948f02
[6087 ms] 
[6087 ms] Start: Resolving Remote
Running the initializeCommand from devcontainer.json...

[11213 ms] Start: Run: /bin/sh -c .devcontainer/initialize.sh
/bin/sh: 1: .devcontainer/initialize.sh: not found
[11219 ms] Error: Command failed: /bin/sh -c .devcontainer/initialize.sh
[11219 ms]     at NK (/home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:15)
[11219 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11219 ms]     at async mAA (/home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:3522)
[11219 ms]     at async LC (/home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[11219 ms]     at async jeA (/home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:12219)
[11219 ms]     at async _eA (/home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:11960)
[11222 ms] Exit code 1
[11225 ms] Command failed: /home/alice/.vscode-server/bin/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/node /home/alice/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-d87b4d0d-9d12-4579-9874-e3f5f41b07b51692291483657 --workspace-folder /c/Users/alice/frigate --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\alice\frigate --id-label devcontainer.config_file=file:///c%3A/Users/alice/frigate/.devcontainer/devcontainer.json --log-level debug --log-format json --config /tmp/devcontainer-config-af8b7413-bb7d-40f7-9605-a1ab47142682/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-e095127f-f3fc-4f4e-a6ee-2161c7e031fe.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[11225 ms] Exit code 1

```
```


### FFprobe output from your camera

```shell
n/a
```

### Operating system

Windows

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

n/a

**Comment by NickM-27** [comment]
another user was using windows to contribute and outlined briefly some steps: https://github.com/blakeblackshear/frigate/discussions/5007

Not sure why this error would be happening, except for some reason the vscode config is not storing the files at the root level

**Comment by AskAlice** [comment]
hmm actually what I had to do was add
```
text eol=lf
``` 
to the gitattributes / git config,
then I had to use the absolute wslpath of the initialize script to start it(i could `ls ./.devcontainer/`  but running `./.devcontainer/initialize.sh` acted like it wasn't found)

**Comment by AskAlice** [comment]
example of this strange behavior
```
[12105 ms] Start: Run: /bin/sh -c echo $PWD; ls -al; ls ./.devcontainer/ -al; ./.devcontainer/initialize.sh
/c/Users/alice/frigate
total 68
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 .
drwxr-xr-x 1 alice alice  4096 Aug 17 17:11 ..
-rwxr--r-- 1 alice alice  5486 Aug 17 10:29 audio-labelmap.txt
-rwxr--r-- 1 alice alice  3959 Aug 17 10:29 benchmark_motion.py
-rwxr--r-- 1 alice alice  3241 Aug 17 10:29 benchmark.py
-rwxr--r-- 1 alice alice   161 Aug 17 10:29 CODEOWNERS
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 config
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 .devcontainer
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 docker
-rwxr--r-- 1 alice alice  1157 Aug 17 10:29 docker-compose.yml
-rwxr--r-- 1 alice alice   133 Aug 17 10:29 .dockerignore
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 docs
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 frigate
drwxr-xr-x 1 alice alice  4096 Aug 18 13:08 .git
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 .github
-rwxr--r-- 1 alice alice   219 Aug 17 10:29 .gitignore
-rwxr--r-- 1 alice alice  1144 Aug 17 10:29 labelmap.txt
-rwxr--r-- 1 alice alice  1096 Aug 17 10:29 LICENSE
-rwxr--r-- 1 alice alice  1636 Aug 17 10:29 Makefile
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 migrations
-rwxr--r-- 1 alice alice 10555 Aug 17 10:29 process_clip.py
-rwxr--r-- 1 alice alice 18656 Aug 17 10:29 .pylintrc
-rwxr--r-- 1 alice alice    79 Aug 17 10:29 pyproject.toml
-rwxr--r-- 1 alice alice  2149 Aug 17 10:29 README.md
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 .vscode
drwxr-xr-x 1 alice alice  4096 Aug 17 10:29 web
total 8
drwxr-xr-x 1 alice alice 4096 Aug 17 10:29 .
drwxr-xr-x 1 alice alice 4096 Aug 17 10:29 ..
-rwxr--r-- 1 alice alice 3225 Aug 18 13:19 devcontainer.json
-rwxr--r-- 1 alice alice  347 Aug 17 10:29 initialize.sh
-rwxr--r-- 1 alice alice 1292 Aug 17 10:29 post_create.sh
/bin/sh: 1: ./.devcontainer/initialize.sh: not found
[12187 ms] Error: Command failed: /bin/sh -c echo $PWD; ls -al; ls ./.devcontainer/ -al; ./.devcontainer/initialize.sh
```

**Comment by AskAlice** [comment]
it seems i also had to use bash instead of /bin/sh, /bin/sh can't seem to stat /c/Users/alice/frigate/.devcontainer/initialize.sh due to a permission error

**Comment by AskAlice** [comment]
I also had to update the dockerfile to modify the permissions on install_deps and build_nginx as WSL optionally sets a umask on paths that are in windows filesystems, and rebuild with emptied cache

**Comment by NickM-27** [comment]
To be clear I was suggesting a PR to the docs for changes necessary for windows users. Seems more maybe needed but yeah it should be double checked to ensure it doesn't cause issues with dev container on Linux / macos.
