### ISSUE TITLE
[Support]: RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

### ISSUE THREAD

**Issue by ensmings** [blakeblackshear/frigate#7570]
### Describe the problem you are having

While starting Frigate, an error about Numpy version is raised and Frigate stopps.

### Version

core-2023.8.3

### Frigate config file

```yaml
[core-ssh ~]$ ha info
arch: armv7
channel: stable
docker: 23.0.6
features:

    reboot
    shutdown
    services
    network
    hostname
    timedate
    os_agent
    haos
    resolved
    journal
    disk
    mount
    hassos: "10.5"
    homeassistant: 2023.8.3
    hostname: homeassistant
    logging: info
    machine: raspberrypi3
    operating_system: Home Assistant OS 10.5
    state: running
    supervisor: 2023.08.1
    supported: true
    supported_arch:
    armv7
    armhf
    timezone: Europe/Paris
```

### Relevant log output

```shell
2023-08-22 21:32:08.817052261 RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-08-22 21:32:08.818549024 Traceback (most recent call last):
2023-08-22 21:32:08.819377510 File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-08-22 21:32:08.821802705 return _run_code(code, main_globals, None,
2023-08-22 21:32:08.822697440 File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-08-22 21:32:08.824073787 exec(code, run_globals)
2023-08-22 21:32:08.824936543 File "/opt/frigate/frigate/main.py", line 9, in
2023-08-22 21:32:08.826865075 from frigate.app import FrigateApp
2023-08-22 21:32:08.827680748 File "/opt/frigate/frigate/app.py", line 17, in
2023-08-22 21:32:08.829946882 from frigate.comms.dispatcher import Communicator, Dispatcher
2023-08-22 21:32:08.830667451 File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in
2023-08-22 21:32:08.832542233 from frigate.config import FrigateConfig
2023-08-22 21:32:08.833284209 File "/opt/frigate/frigate/config.py", line 9, in
2023-08-22 21:32:08.835354875 import matplotlib.pyplot as plt
2023-08-22 21:32:08.836267058 File "/usr/local/lib/python3.9/dist-packages/matplotlib/init.py", line 113, in
2023-08-22 21:32:08.839086210 from . import _api, _version, cbook, _docstring, rcsetup
2023-08-22 21:32:08.839840008 File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in
2023-08-22 21:32:08.842278121 from matplotlib.colors import Colormap, is_color_like
2023-08-22 21:32:08.843046138 File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in
2023-08-22 21:32:08.845511281 from matplotlib import _api, _cm, cbook, scale
2023-08-22 21:32:08.846301225 File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in
2023-08-22 21:32:08.848602724 from matplotlib.ticker import (
2023-08-22 21:32:08.849404907 File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in
2023-08-22 21:32:08.852030102 from matplotlib import transforms as mtransforms
2023-08-22 21:32:08.852953274 File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in
2023-08-22 21:32:08.855266752 from matplotlib._path import (
2023-08-22 21:32:08.856093623 ImportError: numpy.core.multiarray failed to import
```

### FFprobe output from your camera

```shell
Frigate is not starting !!
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

...

**Comment by NickM-27** [comment]
Looks like you're running on a 32bit OS, this is a known problem with 32 bit. Recommendation is to run on 64bit OS

**Comment by ensmings** [comment]
> Looks like you're running on a 32bit OS, this is a known problem with 32 bit. Recommendation is to run on 64bit OS

However I' have no other possibility than running the 32 bit OS. Wouldn't it be possible to find a fix anyway ?

**Comment by ensmings** [comment]
Is it possible to have more details about that bug ? According to the message, Frigate was compiled with an older Numpy version as the one in Home Assistant. Why isn't it possible to upgrade the Numpy version in Frigate ? What would be the impact ?

**Comment by NickM-27** [comment]
Frigate does not support 32 bit OS anymore, it was found that 32 bit OS represented less than 1% of users and it takes way more time to continue supporting it.

**Comment by ensmings** [comment]
Ok. As actually I have no other way than keeping on using the 32 bit OS, I will try to do the modification on my side. If you could share your point of view on that modification it would help me to start. According to you, is it a small modification (i.e. just recompile with the new version) or are there a lot of code impacts ?

**Comment by ensmings** [comment]
Surprisingly, if I check the numpy version directly in Home Assistant through pyscript, the version is 1.26:
`2023-11-05 12:59:37.649 INFO (MainThread) [custom_components.pyscript.file.check_numpy_version.check_numpy_version] NUMPY version: 1.26.0`
which should be compatible with frigate requirements.

**Comment by ensmings** [comment]
> You can certainly give it a go though, just need to update numpy in the requirements-wheels.txt file

I tried to update the numpy version in the requirements-wheels.txt file from 1.22 to 1.23 and it works now with my 32b Home Assistant !
I did it in [this fork](https://github.com/ensmings/frigate) in case someone is interested.
