### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by kasjet99** [blakeblackshear/frigate#7590]
### Describe the problem you are having

I cannot access my web inteface after frigate installed. 192.168.88.244

### Version

I dont know

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  name_of_your_camera: Vigic540
    ffmpeg:
      inputs:
        - path:  rtsp://admin:wagwoord@192.168.88.100:554/stream1/rtsp

          roles:
            - detect
    detect:
      enabled: False # <---- disable detection until you have a working camera feed
      width: 1280 # <---- update for your camera's resolution
      height: 720 # <---- update for your camera's resolution
```

### Relevant log output

```shell
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-08-27 21:57:46.109379064  [INFO] Starting Frigate...
2023-08-27 21:57:46.111639602  [INFO] Preparing go2rtc config...
2023-08-27 21:57:46.120627799  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:46.742876490  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-08-27 21:57:47.204120728  *************************************************************
2023-08-27 21:57:47.204126446  *************************************************************
2023-08-27 21:57:47.204129644  ***    Your config file is not valid!                     ***
2023-08-27 21:57:47.204132564  ***    Please check the docs at                           ***
2023-08-27 21:57:47.204134604  ***    https://docs.frigate.video/configuration/index     ***
2023-08-27 21:57:47.204137595  *************************************************************
2023-08-27 21:57:47.204139430  *************************************************************
2023-08-27 21:57:47.204152441  ***    Config Validation Errors                           ***
2023-08-27 21:57:47.204154956  *************************************************************
2023-08-27 21:57:47.204173553  [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:47.204771003  Traceback (most recent call last):
2023-08-27 21:57:47.204774484    File "/opt/frigate/frigate/app.py", line 351, in start
2023-08-27 21:57:47.204776535      self.init_config()
2023-08-27 21:57:47.204778841    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-08-27 21:57:47.204780574      user_config = FrigateConfig.parse_file(config_file)
2023-08-27 21:57:47.204782528    File "/opt/frigate/frigate/config.py", line 1070, in parse_file
2023-08-27 21:57:47.204784138      with open(config_file) as f:
2023-08-27 21:57:47.204786022  IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:47.204787386  
2023-08-27 21:57:47.204789432  *************************************************************
2023-08-27 21:57:47.204791238  ***    End Config Validation Errors                       ***
2023-08-27 21:57:47.204794420  *************************************************************
2023-08-27 21:57:47.205278298  [2023-08-27 21:57:47] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-27 21:57:47.748110670  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:48.011006105  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-08-27 21:57:48.361266170  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-27 21:57:48.369559006  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-27 21:57:48.451738594  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
I dont have a clue
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Vigi C540 2.0

### Any other information that may be helpful

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml
      - /opt/frigate/config/storage:/media/frigate

    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "wagwoord"

**Comment by NickM-27** [comment]
Your config isn't located at `/opt/frigate/config/config.yml`

**Comment by kasjet99** [comment]
I tried to move the config file from the config.yml created by frigate to config dir now getting error 404 failed to start

**Comment by kasjet99** [comment]
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-08-27 21:57:46.109379064  [INFO] Starting Frigate...
2023-08-27 21:57:46.111639602  [INFO] Preparing go2rtc config...
2023-08-27 21:57:46.120627799  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:46.742876490  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-08-27 21:57:47.204120728  *************************************************************
2023-08-27 21:57:47.204126446  *************************************************************
2023-08-27 21:57:47.204129644  ***    Your config file is not valid!                     ***
2023-08-27 21:57:47.204132564  ***    Please check the docs at                           ***
2023-08-27 21:57:47.204134604  ***    https://docs.frigate.video/configuration/index     ***
2023-08-27 21:57:47.204137595  *************************************************************
2023-08-27 21:57:47.204139430  *************************************************************
2023-08-27 21:57:47.204152441  ***    Config Validation Errors                           ***
2023-08-27 21:57:47.204154956  *************************************************************
2023-08-27 21:57:47.204173553  [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:47.204771003  Traceback (most recent call last):
2023-08-27 21:57:47.204774484    File "/opt/frigate/frigate/app.py", line 351, in start
2023-08-27 21:57:47.204776535      self.init_config()
2023-08-27 21:57:47.204778841    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-08-27 21:57:47.204780574      user_config = FrigateConfig.parse_file(config_file)
2023-08-27 21:57:47.204782528    File "/opt/frigate/frigate/config.py", line 1070, in parse_file
2023-08-27 21:57:47.204784138      with open(config_file) as f:
2023-08-27 21:57:47.204786022  IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:47.204787386  
2023-08-27 21:57:47.204789432  *************************************************************
2023-08-27 21:57:47.204791238  ***    End Config Validation Errors                       ***
2023-08-27 21:57:47.204794420  *************************************************************
2023-08-27 21:57:47.205278298  [2023-08-27 21:57:47] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-27 21:57:47.748110670  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-08-27 21:57:48.011006105  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-08-27 21:57:48.361266170  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-27 21:57:48.369559006  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-27 21:57:48.451738594  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by kasjet99** [comment]
rudi@ubuntu:/opt/frigate/config$ ls
config.yml  storage

**Comment by kasjet99** [comment]
Thanks for the feedback so far

**Comment by myllo** [comment]
Your camera name line is wrong. Check from the documentation (https://docs.frigate.video/configuration/) how to correctly give a name to your camera.

**Comment by kasjet99** [comment]
thank you I am currently reinstalling the whole system I am quite new to all this so much aprieciate your feedback. Wil check setup and get back to you
