### ISSUE TITLE
[Config Support]: Config Validation Error: Replacement index 0 out of range

### ISSUE THREAD

**Issue by AP-Sig** [blakeblackshear/frigate#7628]
### Describe the problem you are having

This is my first time installing frigate, and I've been working through a number of configuration file errors which I've been able to resolve. However, I'm encountering an error in my configuration file which I can't find a solution for: IndexError: Replacement index 0 out of range for positional args tuple. The relevant log output and my config are below.

### Version

3.9

### Frigate config file

```yaml
mqtt:
  enabled: False
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://user:password@192.168.0.100:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
detectors:
  coral1:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
2023-08-30 08:37:16.272581115  [INFO] Preparing go2rtc config...
2023-08-30 08:37:16.272911682  [INFO] Starting Frigate...
2023-08-30 08:37:16.273359364  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-08-30 08:37:16.400886543  [INFO] Starting go2rtc...
2023-08-30 08:37:16.442754949  08:37:16.442 INF go2rtc version 1.2.0 linux/amd64
2023-08-30 08:37:16.442875972  08:37:16.442 INF [api] listen addr=:1984
2023-08-30 08:37:16.442954884  08:37:16.442 INF [rtsp] listen addr=:8554
2023-08-30 08:37:16.443042373  08:37:16.443 INF [srtp] listen addr=:8443
2023-08-30 08:37:16.443112047  08:37:16.443 INF [webrtc] listen addr=:8555
2023-08-30 08:37:16.736797306  [2023-08-30 08:37:16] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-08-30 08:37:16.739303431  *************************************************************
2023-08-30 08:37:16.739305385  *************************************************************
2023-08-30 08:37:16.739307449  ***    Your config file is not valid!                     ***
2023-08-30 08:37:16.739309543  ***    Please check the docs at                           ***
2023-08-30 08:37:16.739310725  ***    https://docs.frigate.video/configuration/index     ***
2023-08-30 08:37:16.739328830  *************************************************************
2023-08-30 08:37:16.739330003  *************************************************************
2023-08-30 08:37:16.739331696  ***    Config Validation Errors                           ***
2023-08-30 08:37:16.739332778  *************************************************************
2023-08-30 08:37:16.739333790  Replacement index 0 out of range for positional args tuple
2023-08-30 08:37:16.739557751  Traceback (most recent call last):
2023-08-30 08:37:16.739559054    File "/opt/frigate/frigate/app.py", line 351, in start
2023-08-30 08:37:16.739560015      self.init_config()
2023-08-30 08:37:16.739561088    File "/opt/frigate/frigate/app.py", line 81, in init_config
2023-08-30 08:37:16.739562059      self.config = user_config.runtime_config
2023-08-30 08:37:16.739563071    File "/opt/frigate/frigate/config.py", line 956, in runtime_config
2023-08-30 08:37:16.739564003      input.path = input.path.format(**FRIGATE_ENV_VARS)
2023-08-30 08:37:16.739565025  IndexError: Replacement index 0 out of range for positional args tuple
2023-08-30 08:37:16.739565777  
2023-08-30 08:37:16.739566789  *************************************************************
2023-08-30 08:37:16.739567790  ***    End Config Validation Errors                       ***
2023-08-30 08:37:16.739568722  *************************************************************
2023-08-30 08:37:17.844933927  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-08-30 08:37:17.852304259  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-08-30 08:37:17.990490872  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-08-30 08:37:17.996634694  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-08-30 08:37:17.999115981  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

M.2

**Comment by NickM-27** [comment]
It seems you most likely have `{` or `}` in the password which is causing issues

**Comment by AP-Sig** [comment]
@NickM-27 That was the issue. Thanks for your help. Was there a section in the documentation that mentions this? I was pretty sure I read through everything but I may have missed that.

**Comment by NickM-27** [comment]
https://docs.frigate.video/configuration/ covers what the `{}` characters are actually used for, there is no specific section about the password in a camera password because the issue does not happen very often

Feel free to create a new issue if something else comes up
