### ISSUE TITLE
[Camera Support]: FFMPEG 

### ISSUE THREAD

**Issue by Mr-CostlessClaw** [blakeblackshear/frigate#7651]
### Describe the problem you are having

FFMPEg is not streaming. Frigate registers the proses of Capture(CPU 3%, MEM .5%) and detect(CPU 0%, MEM .5%).
Have tried a few configs and URLs and none seem to do any good.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.14
  port: 1883
  user: ****
  password: ****

go2rtc:
  streams:
    Frontyard_Right:
      - rtsp://User:password@192.168.**.***:554/cam/realmonitor?channe1=1&subtype=0
    Frontyard_Right_sub:
      - rtsp://User:Password@192.168.**.***5:554/cam/realmonitor?channe1=1&subtype=1

cameras:
  Frontyard_Right:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.**.***:8554/Frontyard_Right_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://192.168.**.***:8554/Frontyard_Right
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-acc
    detect:
      width: 720
      height: 480
      fps: 5
    objects:
      track:
        - person
        - car
        - dog
        - cat
        - bus
    snapshots:
      enabled: True
      timestamp: false
      bounding_box: false
      retain:
        default: 30
    record:
      enabled: True
      retain_days: 30
      events:
        retain:
          default: 30

[ffmpeg:
  hwaccel_args: preset-nvidia-h264] -Was added but did not change the current stats.

detectors:
  coral:
    type: edgetpu
    device: pci
```

### Relevant log output

```shell
With FFMPEG Nvidia
2023-09-01 18:50:29.154796103  [INFO] Starting Frigate...
2023-09-01 18:50:30.097566755  [2023-09-01 18:50:30] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-01 18:50:30.120850026  [2023-09-01 18:50:30] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
2023-09-01 18:50:30.129644880  [2023-09-01 18:50:30] peewee_migrate                 INFO    : Starting migrations
2023-09-01 18:50:30.137391781  [2023-09-01 18:50:30] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-01 18:50:30.143164345  [2023-09-01 18:50:30] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 18:50:30.155415359  [2023-09-01 18:50:30] frigate.app                    INFO    : Output process started: 290
2023-09-01 18:50:30.160307972  [2023-09-01 18:50:30] frigate.app                    INFO    : Camera processor started for Frontyard_Right: 292
2023-09-01 18:50:30.165081596  [2023-09-01 18:50:30] frigate.app                    INFO    : Capture process started for Frontyard_Right: 293
2023-09-01 18:50:30.174576487  [2023-09-01 18:50:30] detector.coral                 INFO    : Starting detection process: 289
2023-09-01 18:50:30.189234008  [2023-09-01 18:50:30] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-09-01 18:50:30.189473734  [2023-09-01 18:50:30] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-09-01 18:50:30.189536438  Process detector:coral:
2023-09-01 18:50:30.190989453  Traceback (most recent call last):
2023-09-01 18:50:30.190992820    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-09-01 18:50:30.190994122      delegate = Delegate(library, options)
2023-09-01 18:50:30.190995502    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-09-01 18:50:30.190999556      raise ValueError(capture.message)
2023-09-01 18:50:30.191011802  ValueError
2023-09-01 18:50:30.191012885  
2023-09-01 18:50:30.191014310  During handling of the above exception, another exception occurred:
2023-09-01 18:50:30.191015726  
2023-09-01 18:50:30.191016809  Traceback (most recent call last):
2023-09-01 18:50:30.191018126    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-09-01 18:50:30.191019163      self.run()
2023-09-01 18:50:30.191020380    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-09-01 18:50:30.191039472      self._target(*self._args, **self._kwargs)
2023-09-01 18:50:30.191040937    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-09-01 18:50:30.191042608      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-09-01 18:50:30.191043826    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-09-01 18:50:30.191060340      self.detect_api = create_detector(detector_config)
2023-09-01 18:50:30.191061738    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-09-01 18:50:30.191062902      return api(detector_config)
2023-09-01 18:50:30.191064158    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-09-01 18:50:30.191065394      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-09-01 18:50:30.191078858    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-09-01 18:50:30.191080167      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-09-01 18:50:30.191081288  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-09-01 18:50:30.191082311  
2023-09-01 18:50:30.202315032  [2023-09-01 18:50:30] frigate.video                  ERROR   : Frontyard_Right: Unable to read frames from ffmpeg process.
2023-09-01 18:50:30.202723488  [2023-09-01 18:50:30] frigate.video                  ERROR   : Frontyard_Right: ffmpeg process is not running. exiting capture thread...
2023-09-01 18:50:31.145431003  [2023-09-01 18:50:31] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 18:50:33.148475776  [2023-09-01 18:50:33] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 18:50:37.151233684  [2023-09-01 18:50:37] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized

Before FFMPEG Nvidia 

2023-09-01 17:44:42.166763087  [INFO] Starting Frigate...
2023-09-01 17:44:43.185946178  [2023-09-01 17:44:43] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-01 17:44:43.194880376  [2023-09-01 17:44:43] frigate.config                 WARNING : The 'retain_days' config option has been DEPRECATED and will be removed in a future version. Please use the 'days' setting under 'retain'
2023-09-01 17:44:43.197089908  [2023-09-01 17:44:43] peewee_migrate                 INFO    : Starting migrations
2023-09-01 17:44:43.202117735  [2023-09-01 17:44:43] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-01 17:44:43.205934350  [2023-09-01 17:44:43] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 17:44:43.218957640  [2023-09-01 17:44:43] frigate.app                    INFO    : Output process started: 291
2023-09-01 17:44:43.226979542  [2023-09-01 17:44:43] frigate.app                    INFO    : Camera processor started for Frontyard_Right: 294
2023-09-01 17:44:43.231553154  [2023-09-01 17:44:43] frigate.app                    INFO    : Capture process started for Frontyard_Right: 295
2023-09-01 17:44:43.243985426  [2023-09-01 17:44:43] detector.coral                 INFO    : Starting detection process: 290
2023-09-01 17:44:43.253151555  [2023-09-01 17:44:43] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-09-01 17:44:43.259892323  [2023-09-01 17:44:43] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-09-01 17:44:43.274251204  [2023-09-01 17:44:43] frigate.video                  ERROR   : Frontyard_Right: Unable to read frames from ffmpeg process.
2023-09-01 17:44:43.274467059  [2023-09-01 17:44:43] frigate.video                  ERROR   : Frontyard_Right: ffmpeg process is not running. exiting capture thread...
2023-09-01 17:44:44.208170388  [2023-09-01 17:44:44] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 17:44:46.211704742  [2023-09-01 17:44:46] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 17:44:50.214549952  [2023-09-01 17:44:50] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 17:44:58.218327397  [2023-09-01 17:44:58] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 17:45:03.284922266  [2023-09-01 17:45:03] watchdog.Frontyard_Right       ERROR   : Ffmpeg process crashed unexpectedly for Frontyard_Right.
2023-09-01 17:45:03.285473358  [2023-09-01 17:45:03] watchdog.Frontyard_Right       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-09-01 17:45:03.285482237  [2023-09-01 17:45:03] ffmpeg.Frontyard_Right.detect  ERROR   : [tcp @ 0x5624a8f3ae40] Connection to tcp://192.168.1.145:8554?timeout=5000000 failed: Connection refused
2023-09-01 17:45:03.285548116  [2023-09-01 17:45:03] ffmpeg.Frontyard_Right.detect  ERROR   : rtsp://192.168.1.145:8554/Frontyard_Right_sub: Connection refused
2023-09-01 17:45:03.297674637  [2023-09-01 17:45:03] ffmpeg.Frontyard_Right.record  ERROR   : [tcp @ 0x557aa91e0cc0] Connection to tcp://192.168.1.145:8554?timeout=5000000 failed: Connection refused
2023-09-01 17:45:03.297678743  [2023-09-01 17:45:03] ffmpeg.Frontyard_Right.record  ERROR   : rtsp://192.168.1.145:8554/Frontyard_Right: Connection refused
2023-09-01 17:45:03.297775481  [2023-09-01 17:45:03] watchdog.Frontyard_Right       INFO    : Terminating the existing ffmpeg process...
2023-09-01 17:45:03.297840688  [2023-09-01 17:45:03] watchdog.Frontyard_Right       INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-01 17:45:03.298466009  [2023-09-01 17:45:03] frigate.video                  ERROR   : Frontyard_Right: Unable to read frames from ffmpeg process.
2023-09-01 17:45:03.298640493  [2023-09-01 17:45:03] frigate.video                  ERROR   : Frontyard_Right: ffmpeg process is not running. exiting capture thread...
2023-09-01 17:45:13.302859733  [2023-09-01 17:45:13] watchdog.Frontyard_Right       ERROR   : Ffmpeg process crashed unexpectedly for Frontyard_Right.
2023-09-01 17:45:13.303107703  [2023-09-01 17:45:13] watchdog.Frontyard_Right       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-09-01 17:45:13.303266838  [2023-09-01 17:45:13] ffmpeg.Frontyard_Right.detect  ERROR   : [tcp @ 0x5646e11a0e40] Connection to tcp://192.168.1.145:8554?timeout=5000000 failed: Connection refused
2023-09-01 17:45:13.303447646  [2023-09-01 17:45:13] ffmpeg.Frontyard_Right.detect  ERROR   : rtsp://192.168.1.145:8554/Frontyard_Right_sub: Connection refused
2023-09-01 17:45:13.313219088  [2023-09-01 17:45:13] ffmpeg.Frontyard_Right.record  ERROR   : [tcp @ 0x55e033a48cc0] Connection to tcp://192.168.1.145:8554?timeout=5000000 failed: Connection refused
2023-09-01 17:45:13.313223541  [2023-09-01 17:45:13] ffmpeg.Frontyard_Right.record  ERROR   : rtsp://192.168.1.145:8554/Frontyard_Right: Connection refused
2023-09-01 17:45:13.313225194  [2023-09-01 17:45:13] watchdog.Frontyard_Right       INFO    : Terminating the existing ffmpeg process...
2023-09-01 17:45:13.313246562  [2023-09-01 17:45:13] watchdog.Frontyard_Right       INFO    : Waiting for ffmpeg to exit gracefully...
2023-09-01 17:45:13.317388912  [2023-09-01 17:45:13] frigate.video                  ERROR   : Frontyard_Right: Unable to read frames from ffmpeg process.
2023-09-01 17:45:13.317831253  [2023-09-01 17:45:13] frigate.video                  ERROR   : Frontyard_Right: ffmpeg process is not running. exiting capture thread...
2023-09-01 17:45:14.221915297  [2023-09-01 17:45:14] frigate.comms.mqtt             ERROR   : Unable to connect to MQTT server: MQTT Not authorized
2023-09-01 17:45:23.321427533  [2023-09-01 17:45:23] watchdog.Frontyard_Right       ERROR   : Ffmpeg process crashed unexpectedly for Frontyard_Right.
2023-09-01 17:45:23.321650129  [2023-09-01 17:45:23] watchdog.Frontyard_Right       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-09-01 17:45:23.321654938  [2023-09-01 17:45:23] ffmpeg.Frontyard_Right.detect  ERROR   : [tcp @ 0x55c103f53e40] Connection to tcp://192.168.1.145:8554?timeout=5000000 failed: Connection refused
2023-09-01 17:45:23.321768751  [2023-09-01 17:45:23] ffmpeg.Frontyard_Right.detect  ERROR   : rtsp://192.168.1.145:8554/Frontyard_Right_sub: Connection refused
2023-09-01 17:45:23.334387141  [2023-09-01 17:45:23] ffmpeg.Frontyard_Right.record  ERROR   : [tcp @ 0x5589c9818cc0] Connection to tcp://192.168.1.145:8554?timeout=5000000 failed: Connection refused
```

### FFprobe output from your camera

```shell
None is provided.
```

### Frigate stats

```json
WebUI is running. No Frames have been received.
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Marquis IPC-YT624

### Any other information that may be helpful

I have a few configs. Some have the stream pop up, but everything usually is not stable. This is a cleaner version of my config. Which I am moving too, but it still did not help with the ffmpeg stream. The cam has worked previously and I do not know what has changed. I have found the stream on more than one server to be very finicky.
Any tips and knowledge would be helpful.
VLC Picks up the stream, Using Edge browser for the WebUI so I have no problem to view any type of stream.

I had less MQTT errors using port 9001 but still some MQTT errors.
Soory if the config and logs are a lot. I have been doing everything that I know and think of to get this running.

**Comment by NickM-27** [comment]
The first set of logs shows that your coral is not found

`Connection to tcp://192.168.1.145:8554?timeout=5000000 failed: Connection refused`

second set of logs shows that the camera is refusing the connection, usually due to incorrect credentials
