### ISSUE TITLE
[Support]: Docker services starts and stops with gui just spinning as busy. 

### ISSUE THREAD

**Issue by rkbest13** [blakeblackshear/frigate#7773]
### Describe the problem you are having

I am trying to implement frigate in a docker with coral pci. I have the pci device detecting correctly but when I start the docker CT, frigate just keep showing hte landing page with busy ring. The logs are also not very intuitive to me to understand if its config or compose file error. 

### Version

0.12

### Frigate config file

```yaml
mqtt:
  host: 10.13.58.34
  user: mqttuser
  password: 'some-password'

 detectors: 
  coral:
    type: edgetpu
    device: pci

cameras:
  ### amcrest 5mp starlight
  1_driveway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@20.13.80.10:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:fETRa4wa3Rm@20.13.80.10:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 10

  ### amcrest 5mp starlight
  1_entryway:
    ffmpeg:
      inputs:
        - path: rtsp://admin:fETRa4wa3Rm@20.13.80.11:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://admin:fETRa4wa3Rm@20.13.80.11:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 10
  ### Annke  5mp starlight
  1_front_lawn:
    ffmpeg:
      inputs:
        - path: rtsp://admin:fETRa4wa3Rm@20.13.80.12:554/Streaming/Channels/101
          roles:
            - record
        - path: rtsp://admin:fETRa4wa3Rm@20.13.80.12:554/Streaming/Channels/102
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
    detect:
      enabled: True
      width: 640
      height: 480
      fps: 10
```

### Relevant log output

```shell
2023-09-11 17:55:08.083311345       detectors:
2023-09-11 17:55:08.083312222       ^
2023-09-11 17:55:08.084237487  Traceback (most recent call last):
2023-09-11 17:55:08.084240034    File "/opt/frigate/frigate/app.py", line 351, in start
2023-09-11 17:55:08.084241548      self.init_config()
2023-09-11 17:55:08.084243450    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-09-11 17:55:08.084244588      user_config = FrigateConfig.parse_file(config_file)
2023-09-11 17:55:08.084245826    File "/opt/frigate/frigate/config.py", line 1074, in parse_file
2023-09-11 17:55:08.084247094      config = load_config_with_no_duplicates(raw_config)
2023-09-11 17:55:08.084249621    File "/opt/frigate/frigate/util.py", line 78, in load_config_with_no_duplicates
2023-09-11 17:55:08.084251207      return yaml.load(raw_config, PreserveDuplicatesLoader)
2023-09-11 17:55:08.084253352    File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
2023-09-11 17:55:08.084254430      return loader.get_single_data()
2023-09-11 17:55:08.084256348    File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
2023-09-11 17:55:08.084258048      node = self.get_single_node()
2023-09-11 17:55:08.084259409    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
2023-09-11 17:55:08.084260480      document = self.compose_document()
2023-09-11 17:55:08.084261733    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
2023-09-11 17:55:08.084262952      node = self.compose_node(None, None)
2023-09-11 17:55:08.084264255    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
2023-09-11 17:55:08.084265306      node = self.compose_mapping_node(anchor)
2023-09-11 17:55:08.084266501    File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
2023-09-11 17:55:08.084267555      while not self.check_event(MappingEndEvent):
2023-09-11 17:55:08.084291231    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
2023-09-11 17:55:08.084292485      self.current_event = self.state()
2023-09-11 17:55:08.084294367    File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
2023-09-11 17:55:08.084295752      raise ParserError("while parsing a block mapping", self.marks[-1],
2023-09-11 17:55:08.084296849  yaml.parser.ParserError: while parsing a block mapping
2023-09-11 17:55:08.084298038    in "<unicode string>", line 1, column 1:
2023-09-11 17:55:08.084299055      mqtt:
2023-09-11 17:55:08.084319897      ^
2023-09-11 17:55:08.084321364  expected <block end>, but found '<block mapping start>'
2023-09-11 17:55:08.084322485    in "<unicode string>", line 6, column 2:
2023-09-11 17:55:08.084323461       detectors:
2023-09-11 17:55:08.084324408       ^
2023-09-11 17:55:08.084325310  
2023-09-11 17:55:08.084326562  *************************************************************
2023-09-11 17:55:08.084327937  ***    End Config Validation Errors                       ***
2023-09-11 17:55:08.084329144  *************************************************************
2023-09-11 17:55:08.086192746  [2023-09-11 17:55:08] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-11 17:55:08.463097324  [INFO] Preparing go2rtc config...
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 27, in <module>
    config: dict[str, any] = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:

```

### FFprobe output from your camera

```shell
----Not sure how to run this ----
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

PCIe

### Network connection

Wired

### Camera make and model

Amcrest, IP5M-T1179EW-28MM

**Comment by NickM-27** [comment]
frigate has started and given an error, so it is an error in the config. 

in this case looks like `detectors` in indented incorrectly

**Comment by rkbest13** [comment]
Following the guide, will this work 
 detectors: 
  coral:
    type: edgetpu
        device: pci

**Comment by rkbest13** [comment]
I am new to yml and thus not aware of the syntax rules. So I put this in yaml syntax checker and got this as good. Hopefully this works. 

detectors: 
 coral:
   type: edgetpu
   device: pci

**Comment by rkbest13** [comment]
I don't know why the syntax above trips the spaces on the above comment. But I have the Coral with one space and type and device with two at same indentation.

**Comment by NickM-27** [comment]
each level needs to be done in increments of 2 spaces

**Comment by rkbest13** [comment]
After fixing the the indentation I get another error in the logs that don't make sense to me. I have a old bare-metal with an IP  '20.13.60.39' but not in the current setup. How is that being called in. Followed by warning the database is locked and that RTPM restream is deprecated.

 
2023-09-12 16:56:43.426373567  [INFO] Starting go2rtc...
s6-rc: info: service legacy-services successfully started
2023-09-12 16:56:43.517828102  16:56:43.517 INF go2rtc version 1.2.0 linux/amd64
2023-09-12 16:56:43.518273401  16:56:43.518 INF [api] listen addr=:1984
2023-09-12 16:56:43.518534704  16:56:43.518 INF [rtsp] listen addr=:8554
2023-09-12 16:56:43.518788899  16:56:43.518 INF [srtp] listen addr=:8443
2023-09-12 16:56:43.519046306  16:56:43.519 INF [webrtc] listen addr=:8555
2023-09-12 16:56:43.873247345  2023/09/12 16:56:43 [error] 125#125: *1 connect() failed (111: Connection refused) while connecting to upstream, client: **20.13.60.39**, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "10.13.58.120:5000", referrer: "http://10.13.58.120:5000/"
2023-09-12 16:56:43.873251147  20.13.60.39 - - [12/Sep/2023:16:56:43 -0500] "GET /api/config HTTP/1.1" 502 157 "http://10.13.58.120:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" "-"
2023-09-12 16:56:43.940953105  [2023-09-12 16:56:43] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-12 16:56:43.944949157  [2023-09-12 16:56:43] frigate.config                 WARNING : RTMP restream is deprecated in favor of the restream role, recommend disabling RTMP.
2023-09-12 16:56:43.946361615  [2023-09-12 16:56:43] frigate.config                 WARNING : RTMP restream is deprecated in favor of the restream role, recommend disabling RTMP.
2023-09-12 16:56:43.948978775  [2023-09-12 16:56:43] frigate.config                 WARNING : RTMP restream is deprecated in favor of the restream role, recommend disabling RTMP.
2023-09-12 16:56:43.957453433  [2023-09-12 16:56:43] peewee_migrate                 INFO    : Starting migrations
2023-09-12 16:56:44.842214914  20.13.60.39 - - [12/Sep/2023:16:56:44 -0500] "GET / HTTP/1.1" 200 6641 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" "-"
2023-09-12 16:56:44.968448558  2023/09/12 16:56:44 [error] 125#125: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 20.13.60.39, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "10.13.58.120:5000", referrer: "http://10.13.58.120:5000/"
2023-09-12 16:56:44.968634384  20.13.60.39 - - [12/Sep/2023:16:56:44 -0500] "GET /api/config HTTP/1.1" 502 157 "http://10.13.58.120:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" "-"
2023-09-12 16:56:48.982613253  **database is locked**
2023-09-12 16:56:49.845435609  20.13.60.39 - - [12/Sep/2023:16:56:49 -0500] "GET / HTTP/1.1" 200 6641 "http://10.13.58.120:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" "-"
2023-09-12 16:56:49.947427896  2023/09/12 16:56:49 [error] 125#125: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 20.13.60.39, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "10.13.58.120:5000", referrer: "http://10.13.58.120:5000/"
2023-09-12 16:56:49.947431207  20.13.60.39 - - [12/Sep/2023:16:56:49 -0500] "GET /api/config HTTP/1.1" 502 157 "http://10.13.58.120:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" "-"
2023-09-12 16:56:50.088259478  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping

**Comment by NickM-27** [comment]
database locked usually happens when the database file is hosted on a network share

**Comment by rkbest13** [comment]
The only folder on NAS is 'clips' in my case. 
```
# Adapted from Mostlychris and thehomeautomationguy
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
#      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
#      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
         - /etc/localtime:/etc/localtime:ro
         - /opt/frigate/frigate.yml:/config/config.yml:ro
#         - /opt/frigate/frigate2.yml:/config/config.yml:ro
         - /mnt/cam-dvr/clips:/media/frigate
         - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
           target: /tmp/cache
           tmpfs:
             size: 1000000000
    environment:
         - FRIGATE_RTSP_PASSWORD="password"
    ports:
         - 5000:5000
         - 1935:1935 # RTMP feeds
         - 8554:8554 #Birdseye In v 0.12
#         - 8554:8554/tcp #WebRTC over tcp        
#         - 8554:8554/udp #WebRTC over udp  
```

**Comment by NickM-27** [comment]
currently the default location for the db is /media/frigate/frigate.db so that would be the case

you're going to want to change the name of the config file to config.yml, update the compose to pass the entire directory into the container, and then add

```yaml
database:
  path: /config/frigate.db
```

**Comment by rkbest13** [comment]
Thanks NickM  - So Frigate is working now. yay

Added the database path to the config.yml file and 
updated the compose file with the full directory path to volumes

```
    volumes:
         - /etc/localtime:/etc/localtime:ro
#         - /opt/frigate/frigate.yml:/config/config.yml:ro
         - /opt/frigate/config.yml:/config/config.yml:ro
         - /opt/frigate/config:/config
         - /mnt/cam-dvr/clips:/media/frigate
```

I am getting to complex yml that I will start with a new thread as its a different error.
