### ISSUE TITLE
[Support]: all events broken when upgrading to 13 beta1

### ISSUE THREAD

**Issue by ljmerza** [blakeblackshear/frigate#7808]
### Describe the problem you are having

All my previous events refuse to load

### Version

0.13 beta1

### Frigate config file

```yaml
logger:
  default: info

database:
  path: /config/frigate.db

detectors:
  coral_pci:
    type: edgetpu
    device: pci

mqtt:
  host: 192.168.1.76

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: True
  bounding_box: False
  retain:
    default: 7

objects:
  track:
    - person
    - dog
    - cat
    - bird
  filters:
    person:
      min_area: 1100

birdseye:
  enabled: True
  mode: continuous

rtmp:
  enabled: False

cameras:
  3d_printer_camera:
    ffmpeg:
      inputs:
        - path: rtsp://wyzebridge:8554/3d-printer-cam
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 1080
      fps: 5
```
```


### Relevant log output

```shell
2023-09-14T17:09:36.660254330Z 2023-09-14 13:09:36.660029210      return method(self, database, *args, **kwargs)
2023-09-14T17:09:36.660257659Z 2023-09-14 13:09:36.660030196    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2042, in execute
2023-09-14T17:09:36.660260290Z 2023-09-14 13:09:36.660031063      return self._execute(database)
2023-09-14T17:09:36.660262695Z 2023-09-14 13:09:36.660032059    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2215, in _execute
2023-09-14T17:09:36.660265268Z 2023-09-14 13:09:36.660032936      cursor = database.execute(self)
2023-09-14T17:09:36.660267626Z 2023-09-14 13:09:36.660033941    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3259, in execute
2023-09-14T17:09:36.660270043Z 2023-09-14 13:09:36.660034815      return self.execute_sql(sql, params)
2023-09-14T17:09:36.660272391Z 2023-09-14 13:09:36.660035825    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 247, in execute_sql
2023-09-14T17:09:36.660274860Z 2023-09-14 13:09:36.660036671      return self._execute(sql, params)
2023-09-14T17:09:36.660277237Z 2023-09-14 13:09:36.660037677    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-09-14T17:09:36.660279721Z 2023-09-14 13:09:36.660038547      cursor.execute(sql, params or ())
2023-09-14T17:09:36.660282155Z 2023-09-14 13:09:36.660039572    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3019, in __exit__
2023-09-14T17:09:36.660284608Z 2023-09-14 13:09:36.660040511      reraise(new_type, new_type(exc_value, *exc_args), traceback)
2023-09-14T17:09:36.660286996Z 2023-09-14 13:09:36.660041505    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
2023-09-14T17:09:36.660291095Z 2023-09-14 13:09:36.660042374      raise value.with_traceback(tb)
2023-09-14T17:09:36.660293463Z 2023-09-14 13:09:36.660043360    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-09-14T17:09:36.660298446Z 2023-09-14 13:09:36.660044202      cursor.execute(sql, params or ())
2023-09-14T17:09:36.660301048Z 2023-09-14 13:09:36.660045093  peewee.OperationalError: no such column: t1.data
```
```


### FFprobe output from your camera

```shell
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

wyze

**Comment by NickM-27** [comment]
what is your docker compose?

**Comment by ljmerza** [comment]
```
frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta1
    container_name: frigate
    privileged: true
    restart: unless-stopped
    shm_size: 512mb
    env_file: ./env/frigate.env
    volumes:
      - ./volumes/frigate/config:/config
      - /media/user/nvr/frigate:/media/frigate
      - /dev/bus/usb:/dev/bus/usb
      - /dev/apex_0:/dev/apex_0
      - /dev/dri/renderD128
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000 # 1GB
    ports:
      - 5000:5000
     ```

**Comment by NickM-27** [comment]
something is wrong with the database, it seems like the database has not gone through the migrations, but you have not included the full set of logs so it is impossible to know what happened

**Comment by ljmerza** [comment]
```
2023-09-14T17:18:12.222550492Z 2023-09-14 13:18:12.222449639  192.168.1.61 - - [14/Sep/2023:13:18:12 -0400] "GET /api/events?cameras=back_yard_camera&labels=bird&zones=all&sub_labels=all&favorites=0&include_thumbnails=0&limit=25 HTTP/1.1" 500 265 "http://192.168.1.76:5001/events?cameras=back_yard_camera&labels=bird" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" "-"
2023-09-14T17:18:12.223043230Z 2023-09-14 13:18:12.222674036  [2023-09-14 13:18:12] frigate.http                   ERROR   : Exception on /events [GET]
2023-09-14T17:18:12.223052392Z 2023-09-14 13:18:12.222676359  Traceback (most recent call last):
2023-09-14T17:18:12.223055193Z 2023-09-14 13:18:12.222677589    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-09-14T17:18:12.223057960Z 2023-09-14 13:18:12.222678634      cursor.execute(sql, params or ())
2023-09-14T17:18:12.223060569Z 2023-09-14 13:18:12.222679668  sqlite3.OperationalError: no such column: t1.data
2023-09-14T17:18:12.223082973Z 2023-09-14 13:18:12.222680565  
2023-09-14T17:18:12.223086129Z 2023-09-14 13:18:12.222681623  During handling of the above exception, another exception occurred:
2023-09-14T17:18:12.223088568Z 2023-09-14 13:18:12.222682477  
2023-09-14T17:18:12.223090989Z 2023-09-14 13:18:12.222683389  Traceback (most recent call last):
2023-09-14T17:18:12.223093339Z 2023-09-14 13:18:12.222684444    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2023-09-14T17:18:12.223095813Z 2023-09-14 13:18:12.222685433      response = self.full_dispatch_request()
2023-09-14T17:18:12.223098162Z 2023-09-14 13:18:12.222686485    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2023-09-14T17:18:12.223100641Z 2023-09-14 13:18:12.222687400      rv = self.handle_user_exception(e)
2023-09-14T17:18:12.223102977Z 2023-09-14 13:18:12.222688502    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2023-09-14T17:18:12.223105442Z 2023-09-14 13:18:12.222689358      rv = self.dispatch_request()
2023-09-14T17:18:12.223107798Z 2023-09-14 13:18:12.222690475    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2023-09-14T17:18:12.223110361Z 2023-09-14 13:18:12.222691493      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-09-14T17:18:12.223112865Z 2023-09-14 13:18:12.222692429    File "/opt/frigate/frigate/http.py", line 879, in events
2023-09-14T17:18:12.223115270Z 2023-09-14 13:18:12.222693288      return jsonify([e for e in events])
2023-09-14T17:18:12.223132334Z 2023-09-14 13:18:12.222694314    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 7126, in __iter__
2023-09-14T17:18:12.223135430Z 2023-09-14 13:18:12.222695158      self.execute()
2023-09-14T17:18:12.223137863Z 2023-09-14 13:18:12.222696167    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 1971, in inner
2023-09-14T17:18:12.223140326Z 2023-09-14 13:18:12.222697087      return method(self, database, *args, **kwargs)
2023-09-14T17:18:12.223143196Z 2023-09-14 13:18:12.222698073    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2042, in execute
2023-09-14T17:18:12.223145737Z 2023-09-14 13:18:12.222698952      return self._execute(database)
2023-09-14T17:18:12.223148087Z 2023-09-14 13:18:12.222699962    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2215, in _execute
2023-09-14T17:18:12.223150581Z 2023-09-14 13:18:12.222700888      cursor = database.execute(self)
2023-09-14T17:18:12.223152907Z 2023-09-14 13:18:12.222701911    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3259, in execute
2023-09-14T17:18:12.223155396Z 2023-09-14 13:18:12.222702803      return self.execute_sql(sql, params)
2023-09-14T17:18:12.223157725Z 2023-09-14 13:18:12.222703838    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 247, in execute_sql
2023-09-14T17:18:12.223160186Z 2023-09-14 13:18:12.222704707      return self._execute(sql, params)
2023-09-14T17:18:12.223165952Z 2023-09-14 13:18:12.222705719    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-09-14T17:18:12.223168560Z 2023-09-14 13:18:12.222706623      cursor.execute(sql, params or ())
2023-09-14T17:18:12.223170938Z 2023-09-14 13:18:12.222707633    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3019, in __exit__
2023-09-14T17:18:12.223173366Z 2023-09-14 13:18:12.222708572      reraise(new_type, new_type(exc_value, *exc_args), traceback)
2023-09-14T17:18:12.223175743Z 2023-09-14 13:18:12.222709580    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
2023-09-14T17:18:12.223178268Z 2023-09-14 13:18:12.222710451      raise value.with_traceback(tb)
2023-09-14T17:18:12.223180586Z 2023-09-14 13:18:12.222711454    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-09-14T17:18:12.223183145Z 2023-09-14 13:18:12.222712315      cursor.execute(sql, params or ())
2023-09-14T17:18:12.223185596Z 2023-09-14 13:18:12.222713225  peewee.OperationalError: no such column: t1.data
```

**Comment by ljmerza** [comment]
```
2023-09-14T17:17:47.466589340Z 2023-09-14 13:17:47.466481912  [2023-09-14 13:17:47] frigate.app                    INFO    : Starting Frigate (0.13.0-9185753)
2023-09-14T17:17:47.567158764Z 2023-09-14 13:17:47.567033033  [2023-09-14 13:17:47] peewee_migrate.logs            INFO    : Starting migrations
2023-09-14T17:17:47.570435212Z 2023-09-14 13:17:47.570358827  [2023-09-14 13:17:47] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-09-14T17:17:48.484537075Z 2023-09-14 13:17:48.484436836  [2023-09-14 13:17:48] frigate.app                    INFO    : Recording process started: 370
2023-09-14T17:17:48.486692435Z 2023-09-14 13:17:48.486594024  [2023-09-14 13:17:48] frigate.app                    INFO    : go2rtc process pid: 96
2023-09-14T17:17:48.538215264Z 2023-09-14 13:17:48.538132364  [2023-09-14 13:17:48] detector.coral_pci             INFO    : Starting detection process: 380
2023-09-14T17:17:48.538234840Z 2023-09-14 13:17:48.538136182  [2023-09-14 13:17:48] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-09-14T17:17:48.538238249Z 2023-09-14 13:17:48.538140072  [2023-09-14 13:17:48] frigate.app                    INFO    : Output process started: 381
2023-09-14T17:17:48.546312073Z 2023-09-14 13:17:48.546238477  [2023-09-14 13:17:48] frigate.app                    INFO    : Camera processor started for 3d_printer_camera: 400
```

**Comment by NickM-27** [comment]
for some reason the database seems like it did not migrate properly or something else is wrong. That being said, no one else who has upgraded / run the dev images has had this issue so I am thinking this may not be a frigate issue or at the very least will be difficult to reproduce. We will have to see if anyone else sees the same issue.

**Comment by ljmerza** [comment]
deleting the last few entries of the migrations table and trying again fixed it
