### ISSUE TITLE
[Detector Support]: 

### ISSUE THREAD

**Issue by martinjung7109** [blakeblackshear/frigate#7821]
### Describe the problem you are having

I am setting up Frigate in a Debian VM on Proxmox and I am gettting an error that Frigate doesn't detect the Coral TPU. I am using the M.2 B+M key TPU which is passed through to my Debian VM where it is recognised as Global Unichip Corp. Coral Edge TPU (drivers and runtime are installed).
![Screenshot (35)](https://github.com/blakeblackshear/frigate/assets/64349124/9c5110a4-0072-40d2-af04-02594ecbed13)
Altough I am getting this error, the Inference Speed goes down to 10 ms when I add the Coral to the configuration file.
![Screenshot (31)](https://github.com/blakeblackshear/frigate/assets/64349124/b539fd1d-1695-4658-b162-3a0a4f860c12)
![Screenshot (32)](https://github.com/blakeblackshear/frigate/assets/64349124/041132a2-d323-478f-9779-5afbdc1cf4c0)
Intel hardware acceleration (iGPU passed through to VM) works without problems.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com
ffmpeg:
  hwaccel_args: preset-vaapi
detectors:
  coral:
    type: edgetpu
    device: pcie
cameras:
  back:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.170.20:554
          roles:
            - detect
    detect:
      width: 1280
      height: 720
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/frigate/config.yml:/config/config.yml
      - /root/frigate/media/:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
```

### Relevant log output

```shell
2023-09-15 15:26:56.163819815  [2023-09-15 15:26:56] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pcie
2023-09-15 15:26:56.163877712  [2023-09-15 15:26:56] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-09-15 15:26:56.163937554  Process detector:coral:
2023-09-15 15:26:56.164430713  Traceback (most recent call last):
2023-09-15 15:26:56.164459007    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-09-15 15:26:56.164459891      delegate = Delegate(library, options)
2023-09-15 15:26:56.164460674    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-09-15 15:26:56.164462156      raise ValueError(capture.message)
2023-09-15 15:26:56.164562931  ValueError
2023-09-15 15:26:56.164563536  
2023-09-15 15:26:56.164564316  During handling of the above exception, another exception occurred:
2023-09-15 15:26:56.164564858  
2023-09-15 15:26:56.164565432  Traceback (most recent call last):
2023-09-15 15:26:56.164566027    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-09-15 15:26:56.164566591      self.run()
2023-09-15 15:26:56.164567226    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-09-15 15:26:56.164568596      self._target(*self._args, **self._kwargs)
2023-09-15 15:26:56.164576067    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-09-15 15:26:56.164576723      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-09-15 15:26:56.164577347    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-09-15 15:26:56.164577955      self.detect_api = create_detector(detector_config)
2023-09-15 15:26:56.164589140    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-09-15 15:26:56.164589785      return api(detector_config)
2023-09-15 15:26:56.164598079    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-09-15 15:26:56.164598719      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-09-15 15:26:56.164599428    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-09-15 15:26:56.164600034      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-09-15 15:26:56.164600605  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-09-15 15:26:56.164601228  
2023-09-15 15:27:14.113699570  [2023-09-15 15:27:14] frigate.comms.mqtt             ERROR   : Unable to publish to back/all: client is not connected
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

M.2

**Comment by NickM-27** [comment]
> Altough I am getting this error, the Inference Speed goes down to 10 ms when I add the Coral to the configuration file.

that doesn't mean anything, 10 is the default starting value before it gets real values to average with.

I would suggest running frigate with CPU detector and getting a shell in frigate, see if /dev/apex_0 is visible to the container

**Comment by NickM-27** [comment]
actually I just realized, you are doing

```
detectors:
  coral:
    type: edgetpu
    device: pcie
```

but that is wrong, it should just be `pci` as the type of device

**Comment by martinjung7109** [comment]
> actually I just realized, you are doing
> 
> ```
> detectors:
>   coral:
>     type: edgetpu
>     device: pcie
> ```
> 
> but that is wrong, it should just be `pci` as the type of device

That was the whole problem, works as expected now. I'm sorry, I missed this. Thanks a lot!
