### ISSUE TITLE
[Support]: Issues maintaining recordings

### ISSUE THREAD

**Issue by xAcrosonicx** [blakeblackshear/frigate#7922]
### Describe the problem you are having

Hello,

First of all, I really appreciate all of the hard work and dedication put into this great project! I have been running Frigate for a few months with this exact setup and it has been working flawlessly - nothing in my environment has changed recently. However, as of a few days ago my camera suddenly started crashing (not sending frames to Frigate) anytime it detects any of the objects I specify in my config / when it starts recording. After rebooting the add-on, I am not able to view the recordings/clips in the web UI, or browse to the file(s) for viewing. 

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  host: my_IP
  user: my_user
  password: my_pass
  
database:
  path: /config/frigate.db
  
cameras:
  frontcamera:
    ffmpeg:
      input_args: -tag:v hvc1
      inputs:
        - path: rtsp://my_user:my_pass@my_ip:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
    detect:
      width: 3072
      height: 1728
      fps: 5
    zones:
      driveway:
        coordinates: 0,742,335,562,681,426,963,363,1311,312,1604,232,1991,160,2143,192,2342,242,2240,569,1973,1198,1667,1728,0,1728
        objects:
          - person
          - dog
          - car
      east_sideyard:
        coordinates: 2219,659,1962,1214,1701,1728,3072,1728,3072,662,2839,475,2465,252,2369,234
        objects:
          - person
          - dog
      west_sideyard:
        coordinates: 258,598,535,478,802,390,1026,346,1271,320,1987,146,1813,104,1411,155,908,230,748,293,409,392,0,525,0,731
        objects:
          - person
          - dog

record:
  enabled: True
  retain:
    days: 0
  events:
    required_zones:
      - driveway
      - west_sideyard
      - east_sideyard
    retain:
      default: 14
      mode: active_objects  

motion:
  mask:
    - 2620,136,2527,138,2387,142,2396,0,2663,0,2979,45,2959,127,2828,183,2672,411,2602,389
    - 628,296,698,274,809,278,868,183,809,147,717,102,631,122,590,174,606,269
    - 307,378,147,427,118,307,285,267
    
objects:
  track:
    - person
    - dog
    - car
  filters:
    person:
      min_area: 5500
    car:
      min_area: 58000

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  required_zones:
    - driveway
    - east_sideyard
    - west_sideyard
  retain:
    default: 1
    mode: motion
    objects:
      person: 14
      dog: 7
      car: 7

detectors:
  coral:
    type: edgetpu
    device: usb
```

### Relevant log output

```shell
2023-09-23 02:04:34.223224211  [INFO] Starting Frigate...
2023-09-23 02:04:35.340497255  [2023-09-22 21:04:35] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-23 02:04:35.365469983  [2023-09-22 21:04:35] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-09-23 02:04:35.370815420  [2023-09-22 21:04:35] peewee_migrate                 INFO    : Starting migrations
2023-09-23 02:04:35.379035397  [2023-09-22 21:04:35] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-23 02:04:35.395428918  [2023-09-22 21:04:35] frigate.app                    INFO    : Output process started: 300
2023-09-23 02:04:35.399327712  [2023-09-22 21:04:35] detector.coral                 INFO    : Starting detection process: 298
2023-09-23 02:04:35.417773521  [2023-09-22 21:04:35] frigate.app                    INFO    : Camera processor started for frontcamera: 306
2023-09-23 02:04:35.417777388  [2023-09-22 21:04:35] frigate.app                    INFO    : Capture process started for frontcamera: 307
2023-09-23 02:04:38.872842996  [2023-09-22 21:04:35] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-09-23 02:04:38.876091505  [2023-09-22 21:04:38] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-09-23 02:07:32.434105199  [2023-09-22 21:07:32] frigate.http                   ERROR   : ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
2023-09-23 02:07:32.434107752    built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
2023-09-23 02:07:32.434125084    configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
2023-09-23 02:07:32.434126871    libavutil      57. 28.100 / 57. 28.100
2023-09-23 02:07:32.434127808    libavcodec     59. 37.100 / 59. 37.100
2023-09-23 02:07:32.434128718    libavformat    59. 27.100 / 59. 27.100
2023-09-23 02:07:32.434129616    libavdevice    59.  7.100 / 59.  7.100
2023-09-23 02:07:32.434143006    libavfilter     8. 44.100 /  8. 44.100
2023-09-23 02:07:32.434143971    libswscale      6.  7.100 /  6.  7.100
2023-09-23 02:07:32.434144858    libswresample   4.  7.100 /  4.  7.100
2023-09-23 02:07:32.434145742    libpostproc    56.  6.100 / 56.  6.100
2023-09-23 02:07:32.434147109  [concat @ 0x561613a01a80] No files to concat
2023-09-23 02:07:32.434148094  /dev/stdin: Invalid data found when processing input
2023-09-23 02:07:32.434148999  
2023-09-23 02:07:33.035171357  Exception in thread detected_frames_processor:
2023-09-23 02:07:33.035178390  Traceback (most recent call last):
2023-09-23 02:07:33.035182011    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-09-23 02:07:33.036623147      self.run()
2023-09-23 02:07:33.036629522    File "/opt/frigate/frigate/object_processing.py", line 910, in run
2023-09-23 02:07:33.037488048      camera_state.update(
2023-09-23 02:07:33.037494463    File "/opt/frigate/frigate/object_processing.py", line 531, in update
2023-09-23 02:07:33.038134973      c(self.name, removed_obj, frame_time)
2023-09-23 02:07:33.038141062    File "/opt/frigate/frigate/object_processing.py", line 694, in end
2023-09-23 02:07:33.038916564      with open(
2023-09-23 02:07:33.038923214  OSError: [Errno 5] Input/output error: '/media/frigate/clips/frontcamera-1695434843.752936-213asm.jpg'
2023-09-23 02:07:34.666612677  [2023-09-22 21:07:34] frigate.http                   ERROR   : ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
2023-09-23 02:07:34.666614975    built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
2023-09-23 02:07:34.666620819    configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
2023-09-23 02:07:34.666621915    libavutil      57. 28.100 / 57. 28.100
2023-09-23 02:07:34.666622930    libavcodec     59. 37.100 / 59. 37.100
2023-09-23 02:07:34.666623843    libavformat    59. 27.100 / 59. 27.100
2023-09-23 02:07:34.666624737    libavdevice    59.  7.100 / 59.  7.100
2023-09-23 02:07:34.666625633    libavfilter     8. 44.100 /  8. 44.100
2023-09-23 02:07:34.666626524    libswscale      6.  7.100 /  6.  7.100
2023-09-23 02:07:34.666627415    libswresample   4.  7.100 /  4.  7.100
2023-09-23 02:07:34.666628309    libpostproc    56.  6.100 / 56.  6.100
2023-09-23 02:07:34.666629230  [concat @ 0x55b8e386ea80] No files to concat
2023-09-23 02:07:34.666630183  /dev/stdin: Invalid data found when processing input
2023-09-23 02:07:34.666631015  
2023-09-23 02:07:40.829481156  [2023-09-22 21:07:40] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:07:40.829590370  [2023-09-22 21:07:40] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:07:45.729066023  [2023-09-22 21:07:45] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:07:45.729089808  [2023-09-22 21:07:45] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:07:50.796571781  [2023-09-22 21:07:50] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:07:50.796742395  [2023-09-22 21:07:50] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:07:55.807080045  [2023-09-22 21:07:55] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:07:55.807083084  [2023-09-22 21:07:55] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:08:00.781567148  [2023-09-22 21:08:00] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:08:00.781570460  [2023-09-22 21:08:00] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:08:05.715869812  [2023-09-22 21:08:05] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:08:05.715873702  [2023-09-22 21:08:05] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:08:10.799429671  [2023-09-22 21:08:10] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:08:10.799507302  [2023-09-22 21:08:10] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:08:15.793181207  [2023-09-22 21:08:15] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:08:15.793239887  [2023-09-22 21:08:15] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:08:20.797349056  [2023-09-22 21:08:20] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:08:20.797353781  [2023-09-22 21:08:20] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:08:25.796621430  [2023-09-22 21:08:25] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:08:25.796625115  [2023-09-22 21:08:25] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:08:30.714587531  [2023-09-22 21:08:30] frigate.record                 WARNING : Unable to keep up with recording segments in cache for frontcamera. Keeping the 5 most recent segments out of 6 and discarding the rest...
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"15/1","codec_long_name":"H.265/HEVC(HighEfficiencyVideoCoding)","height":1728,"width":3072},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}}]
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest UltraHD 4K (8MP) Outdoor Security IP Turret PoE Camera

### Any other information that may be helpful

I have auto-update enabled, so I am unsure whether or not an update was pushed that could have caused this (unlikely).

After rebooting Frigate, the first detection in one of my zones causes it to crash. The "events" typically shows the snapshot, but cannot replay the footage and the event is still "In Progress" even though the camera is stating "No frames have been received"

There do not appear to be any hardware issues that I can find, Coral and host CPU are not complaining anywhere that I can tell. 

I have done the following steps, none of which resolved the issue:

- Rebooted host
- Rebooted HA
- Stopped/Started add-on
- Stopped add-on, deleted db and config files restarted add-on
- Completely uninstalled (rebooted) and reinstalled (rebooted) both add-on and integration
- Stopped Frigate, removed NAS from config, rebooted HA

**Comment by NickM-27** [comment]
> `input_args: -tag:v hvc1`

this is overwriting many input args that frigate needs to use, I'd suggest removing this line entirely and letting frigate use its default args

**Comment by xAcrosonicx** [comment]
Hi Nick,

Thanks for the quick reply! I have gone ahead and removed this from my config and rebooted Frigate, unfortunately the issue persists. See logs for reference:

> 2023-09-23 02:32:54.622373457  [INFO] Starting Frigate...
2023-09-23 02:32:55.620642983  [2023-09-22 21:32:55] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-09-23 02:32:55.641219786  [2023-09-22 21:32:55] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-09-23 02:32:55.641355573  [2023-09-22 21:32:55] peewee_migrate                 INFO    : Starting migrations
2023-09-23 02:32:55.645350583  [2023-09-22 21:32:55] peewee_migrate                 INFO    : There is nothing to migrate
2023-09-23 02:32:55.659378862  [2023-09-22 21:32:55] frigate.app                    INFO    : Output process started: 300
2023-09-23 02:32:55.663136009  [2023-09-22 21:32:55] detector.coral                 INFO    : Starting detection process: 299
2023-09-23 02:32:55.672423485  [2023-09-22 21:32:55] frigate.app                    INFO    : Camera processor started for frontcamera: 308
2023-09-23 02:32:55.673261421  [2023-09-22 21:32:55] frigate.app                    INFO    : Capture process started for frontcamera: 309
2023-09-23 02:32:59.096129328  [2023-09-22 21:32:55] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-09-23 02:32:59.100746082  [2023-09-22 21:32:59] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-09-23 02:33:49.790418925  [2023-09-22 21:33:49] frigate.http                   ERROR   : ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
2023-09-23 02:33:49.790422336    built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
2023-09-23 02:33:49.790442012    configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
2023-09-23 02:33:49.790443779    libavutil      57. 28.100 / 57. 28.100
2023-09-23 02:33:49.790444827    libavcodec     59. 37.100 / 59. 37.100
2023-09-23 02:33:49.790445828    libavformat    59. 27.100 / 59. 27.100
2023-09-23 02:33:49.790446829    libavdevice    59.  7.100 / 59.  7.100
2023-09-23 02:33:49.790459685    libavfilter     8. 44.100 /  8. 44.100
2023-09-23 02:33:49.790460723    libswscale      6.  7.100 /  6.  7.100
2023-09-23 02:33:49.790461674    libswresample   4.  7.100 /  4.  7.100
2023-09-23 02:33:49.790462602    libpostproc    56.  6.100 / 56.  6.100
2023-09-23 02:33:49.790463997  [concat @ 0x558a62595a80] No files to concat
2023-09-23 02:33:49.790465003  /dev/stdin: Invalid data found when processing input
2023-09-23 02:33:49.790465910  
2023-09-23 02:33:51.070506344  [2023-09-22 21:33:51] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:33:51.070618118  [2023-09-22 21:33:51] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:33:52.171381556  [2023-09-22 21:33:52] frigate.http                   ERROR   : ffmpeg version n5.1-2-g915ef932a3-20220731 Copyright (c) 2000-2022 the FFmpeg developers
2023-09-23 02:33:52.171385517    built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
2023-09-23 02:33:52.171391573    configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
2023-09-23 02:33:52.171392730    libavutil      57. 28.100 / 57. 28.100
2023-09-23 02:33:52.171393796    libavcodec     59. 37.100 / 59. 37.100
2023-09-23 02:33:52.171394734    libavformat    59. 27.100 / 59. 27.100
2023-09-23 02:33:52.171395676    libavdevice    59.  7.100 / 59.  7.100
2023-09-23 02:33:52.171396586    libavfilter     8. 44.100 /  8. 44.100
2023-09-23 02:33:52.171397501    libswscale      6.  7.100 /  6.  7.100
2023-09-23 02:33:52.171398419    libswresample   4.  7.100 /  4.  7.100
2023-09-23 02:33:52.171399332    libpostproc    56.  6.100 / 56.  6.100
2023-09-23 02:33:52.171400285  [concat @ 0x55ee2675aa80] No files to concat
2023-09-23 02:33:52.171401286  /dev/stdin: Invalid data found when processing input
2023-09-23 02:33:52.171402191  
2023-09-23 02:33:55.015350961  Exception in thread detected_frames_processor:
2023-09-23 02:33:55.015529848  Traceback (most recent call last):
2023-09-23 02:33:55.015753390    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-09-23 02:33:55.016120066      self.run()
2023-09-23 02:33:55.016253045    File "/opt/frigate/frigate/object_processing.py", line 910, in run
2023-09-23 02:33:55.016490766      camera_state.update(
2023-09-23 02:33:55.016529134    File "/opt/frigate/frigate/object_processing.py", line 531, in update
2023-09-23 02:33:55.016767274      c(self.name, removed_obj, frame_time)
2023-09-23 02:33:55.016836646    File "/opt/frigate/frigate/object_processing.py", line 694, in end
2023-09-23 02:33:55.016978510      with open(
2023-09-23 02:33:55.017038525  OSError: [Errno 5] Input/output error: '/media/frigate/clips/frontcamera-1695436423.107706-jcdp8e.jpg'
2023-09-23 02:33:56.058379715  [2023-09-22 21:33:56] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:33:56.058383288  [2023-09-22 21:33:56] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:34:01.057342993  [2023-09-22 21:34:01] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:34:01.057345919  [2023-09-22 21:34:01] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:34:06.072365271  [2023-09-22 21:34:06] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:34:06.072368134  [2023-09-22 21:34:06] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'
2023-09-23 02:34:11.000792629  [2023-09-22 21:34:11] frigate.record                 ERROR   : Error occurred when attempting to maintain recording cache
2023-09-23 02:34:11.000795597  [2023-09-22 21:34:11] frigate.record                 ERROR   : [Errno 5] Input/output error: '/media/frigate/recordings/2023-09-23'

**Comment by NickM-27** [comment]
it appears this is an error that happens when the volume that is being written to is out of space https://github.com/blakeblackshear/frigate/issues/7577

**Comment by xAcrosonicx** [comment]
Interestingly it was reporting that I had ~2TB of space available still. After some troubleshooting I discovered that something had corrupted my frigate folder on my NAS. 

I moved the non-Frigate data onto another drive and reformatted everything so I could start fresh and dedicate it to Frigate.

In HA (OS) I stopped frigate, removed my old NAS storage, and rebooted. After ensuring Frigate was not running I removed the frigate database and then went to add the new NAS to HA, but am receiving an error that (to me) appears to be related to the fact that there was a previous frigate mount that it is not able to update/remove and recreate. See attached screenshots, I have even gone as far as removing both the Frigate add-on and integration and rebooting to ensure there was nothing interfering.

To clarify, I am also able to add the exact NAS configuration that I want with any name other than “frigate” (I.e I have it added with “frigate_1” and it works perfectly, and I am able to manually read and write files to it but of course it must be “frigate” to work properly). 

Maybe this is something to do with HA OS not removing/updating the old mount point properly? 

![IMG_3854](https://github.com/blakeblackshear/frigate/assets/11741458/5204e6cc-014a-4776-9ade-99e128c3b3be)
![IMG_3855](https://github.com/blakeblackshear/frigate/assets/11741458/ab8a01b1-c870-4212-b669-f14df18203ca)

**Comment by NickM-27** [comment]
Have you restarted the HA OS host device? This seems like a supervisor bug, frigate does not control any of this behavior.

**Comment by xAcrosonicx** [comment]
Yes, I have also rebooted my host. I’ll close this out since you were correct with your previous comment regarding the storage device being the solution to my original issue and open a request elsewhere. 

As always, thanks for all your help!

**Comment by xAcrosonicx** [comment]
For anyone who may find this in the future, the issue was resolved in a recent update. I disabled the Frigate add-on, rebooted, updated HA, and then re-enabled the add-on and rebooted one more time.
