### ISSUE TITLE
[Support]: dev branch: Migration failed: 014_event_updates_for_fp

### ISSUE THREAD

**Issue by lkaino** [blakeblackshear/frigate#8013]
### Describe the problem you are having

I'm running dev branch on commit 9a4f970. I'm getting following error on launch:

I had the same issue on earlier commit, updated today to see if it's fixed. If this is only dev branch thing, I can wipe my database and start over.

### Version

0.13.0-9a4f970

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
2023-10-01 21:38:20.288008186  [2023-10-01 21:38:20] frigate.app                    INFO    : Starting Frigate (0.13.0-9a4f970)
2023-10-01 21:38:20.350807709  [2023-10-01 21:38:20] peewee_migrate.logs            INFO    : Starting migrations
2023-10-01 21:38:20.368946597  [2023-10-01 21:38:20] peewee_migrate.logs            INFO    : Migrate "014_event_updates_for_fp"
2023-10-01 21:38:20.369057384  [2023-10-01 21:38:20] peewee_migrate.logs            INFO    : add_column ('event', 'score', <FloatField: Event.score>)
2023-10-01 21:38:20.370463494  duplicate column name: score
2023-10-01 21:38:20.370581996  [2023-10-01 21:38:20] peewee_migrate.logs            ERROR   : Migration failed: 014_event_updates_for_fp
2023-10-01 21:38:20.370584447  Traceback (most recent call last):
2023-10-01 21:38:20.370592384    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-10-01 21:38:20.370595177      cursor.execute(sql, params or ())
2023-10-01 21:38:20.370597048  sqlite3.OperationalError: duplicate column name: score
2023-10-01 21:38:20.370599394  
2023-10-01 21:38:20.370601585  During handling of the above exception, another exception occurred:
2023-10-01 21:38:20.370620966  
2023-10-01 21:38:20.370622847  Traceback (most recent call last):
2023-10-01 21:38:20.370624975    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/router.py", line 200, in run_one
2023-10-01 21:38:20.370626538      migrator()
2023-10-01 21:38:20.370637569    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/migrator.py", line 76, in __call__
2023-10-01 21:38:20.370662713      op.run()
2023-10-01 21:38:20.370664657    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 165, in run
2023-10-01 21:38:20.370666835      self._handle_result(method(*self.args, **kwargs))
2023-10-01 21:38:20.370668824    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 159, in _handle_result
2023-10-01 21:38:20.370678207      self._handle_result(item)
2023-10-01 21:38:20.370680018    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 156, in _handle_result
2023-10-01 21:38:20.370681515      result.run()
2023-10-01 21:38:20.370683501    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 165, in run
2023-10-01 21:38:20.370685210      self._handle_result(method(*self.args, **kwargs))
2023-10-01 21:38:20.370696353    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 154, in _handle_result
2023-10-01 21:38:20.370698079      self.execute(result)
2023-10-01 21:38:20.370699935    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 150, in execute
2023-10-01 21:38:20.370701905      self.migrator.database.execute(node)
2023-10-01 21:38:20.370703743    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3259, in execute
2023-10-01 21:38:20.370705425      return self.execute_sql(sql, params)
2023-10-01 21:38:20.370707215    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-10-01 21:38:20.370719258      cursor.execute(sql, params or ())
2023-10-01 21:38:20.370721168    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3019, in __exit__
2023-10-01 21:38:20.370722864      reraise(new_type, new_type(exc_value, *exc_args), traceback)
2023-10-01 21:38:20.370724736    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
2023-10-01 21:38:20.370726416      raise value.with_traceback(tb)
2023-10-01 21:38:20.370728404    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3251, in execute_sql
2023-10-01 21:38:20.370730041      cursor.execute(sql, params or ())
2023-10-01 21:38:20.370731574  peewee.OperationalError: duplicate column name: score
2023-10-01 21:38:21.626867703  [INFO] Service Frigate exited with code 1 (by signal 0)
```

### FFprobe output from your camera

```shell
-
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

-

**Comment by NickM-27** [comment]
Did you at some point update to a dev branch and move back to 0.12?

This hasn't been an issue for users who have updated cleanly

**Comment by lkaino** [comment]
Nope, I have never downgraded my branch. I can wipe my db and carry on if it's no issue for others.

**Comment by NickM-27** [comment]
For now I think that should be fine. Will continue to monitor for other reports.
