### ISSUE TITLE
Autotracking for cameras without presets

### ISSUE THREAD

**Issue by edurenye** [blakeblackshear/frigate#8027]
**Describe what you are trying to accomplish and why in non technical terms**
I want to be able to set autotracking for my camera so that I can autotrack lol

My camera is a Imou IPC-S21FE, it has onvif protocol support and presets that I can use from the oficial app but from frigate I can PTZ but it does not detect the presets so I can not use the home option mandatory for autotracking.

**Describe the solution you'd like**
To not have home option as mandatory.

**Describe alternatives you've considered**
Add an option to set coordinates like for the (movement_weights)
Set an option for calculated possitions, something like 'middle possition' and it gets calculated during the calibration process if `calibrate_on_startup` is set to `true`.

**Additional context**
This afects the last options added here: https://deploy-preview-6262--frigate-docs.netlify.app/configuration/autotracking

**Comment by hawkeye217** [comment]
Does autotracking still work for you even if you specify a random preset name in the `return_preset` parameter?

Presets are usually one of the most basic things provided by ONVIF. If your camera's ONVIF implementation doesn't support presets, I'd be very surprised if it supports the other requirements necessary for autotracking.

Frigate will report error messages in the log if your camera's firmware doesn't support the appropriate ONVIF calls.

**Comment by edurenye** [comment]
I can't really test, when I enable it I get a 502, will check the logs when I have more time.

**Comment by edurenye** [comment]
When I just open the camera page where I can move the camera but not use zoom.
I just see this in the logs: `frigate.ptz.onvif              WARNING : Unable to get presets from camera: camera_id: Unknown error: This optional method is not implemented`

And as it says there, this method is optional.

When I have more time I'll try again to enable autotracking and find why frigate does not start when I do that.

**Comment by hawkeye217** [comment]
Sounds good. Let us know how it goes.

And for clarity - the "optional method" error is not saying that Frigate considers something "optional", rather it's an error being reported back to Frigate from the ONVIF library.

**Comment by edurenye** [comment]
From the "Imou Life" app I can set presets, eventhough there they are called as "Favorites", but they are the same thing.
Maybe that is a feature not from the camera but from the app that works preety much as I described in the alternative solutions in the description of the ticket, so basically using coordenates to set these "Favorites".
And we sould implement the same thing here for the cameras that have PTZ but do not implement 'presets'.

**Comment by edurenye** [comment]
This is the config that I have for that camera under onvif:
```
      autotracking:
        enabled: false
        calibrate_on_startup: true
        zooming: disabled
        required_zones:
        - zone_cobert
        return_preset: PRESET_1
```

I managed to debug it but there isn't much relevant info in the logs.

There was nothing in the logs when I had it on `info` so I switched to `debug` mode.

Then still nothing regarding the calibration eventhough `calibrate_on_startup` is set to `True` and no error or anything regarding that, also does not seem to calibrate since `movement_weights` where no filled.

And then when there was a person that left the scene to the left side, I was expecting the camera to move to the left side but nothing happened.

And again nothing in the logs, there is the `tracked_object start` event and the movement and object detection debuging information but nothing regarding autotracking or onvif or PTZ.
Here is the content of the log for that event:
```
2023-10-03 12:39:49.888993920  [2023-10-03 12:39:49] asyncio                        DEBUG   : Using selector: EpollSelector
2023-10-03 12:39:51.220723535  [2023-10-03 12:39:51] frigate.events.maintainer      DEBUG   : Event received: tracked_object start cobert 1696329590.91354-6nyzkx
2023-10-03 12:39:51.226505933  [2023-10-03 12:39:51] peewee.sqliteq                 DEBUG   : received query INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))
2023-10-03 12:39:51.227045734  [2023-10-03 12:39:51] peewee                         DEBUG   : ('INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))', [1696329590.91354, 'cobert', 'tracked_object', '1696329590.91354-6nyzkx', 'visible', '{"box": [0.1109375, 0.25, 0.015625, 0.06041666666666667], "label": "person", "region": [0.0, 0.0, 0.5, 0.6666666666666666]}'])
2023-10-03 12:39:53.625644107  [2023-10-03 12:39:53] frigate.events.maintainer      DEBUG   : Event received: tracked_object end cobert 1696329590.91354-6nyzkx
2023-10-03 12:39:53.633485345  [2023-10-03 12:39:53] peewee.sqliteq                 DEBUG   : received query INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))
2023-10-03 12:39:53.633798736  [2023-10-03 12:39:53] peewee                         DEBUG   : ('INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))', [1696329591.467559, 'cobert', 'tracked_object', '1696329590.91354-6nyzkx', 'gone', '{"box": [0.1109375, 0.25, 0.015625, 0.06041666666666667], "label": "person", "region": [0.0, 0.0, 0.5, 0.6666666666666666]}'])
2023-10-03 12:39:54.893201768  [2023-10-03 12:39:54] asyncio                        DEBUG   : Using selector: EpollSelector
2023-10-03 12:39:56.587304109  [2023-10-03 12:39:56] frigate.events.maintainer      DEBUG   : Event received: tracked_object start cobert 1696329596.262904-5vm9i3
2023-10-03 12:39:56.592854472  [2023-10-03 12:39:56] peewee.sqliteq                 DEBUG   : received query INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))
2023-10-03 12:39:56.593528651  [2023-10-03 12:39:56] peewee                         DEBUG   : ('INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))', [1696329596.262904, 'cobert', 'tracked_object', '1696329596.262904-5vm9i3', 'visible', '{"box": [0.115625, 0.25833333333333336, 0.0109375, 0.04791666666666667], "label": "person", "region": [0.0, 0.0, 0.5, 0.6666666666666666]}'])
2023-10-03 12:39:59.405758208  [2023-10-03 12:39:59] frigate.events.maintainer      DEBUG   : Event received: tracked_object end cobert 1696329596.262904-5vm9i3
2023-10-03 12:39:59.410587985  [2023-10-03 12:39:59] peewee.sqliteq                 DEBUG   : received query INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))
2023-10-03 12:39:59.410994451  [2023-10-03 12:39:59] peewee                         DEBUG   : ('INSERT INTO "timeline" ("timestamp", "camera", "source", "source_id", "class_type", "data") VALUES (?, ?, ?, ?, ?, json(?))', [1696329597.856961, 'cobert', 'tracked_object', '1696329596.262904-5vm9i3', 'gone', '{"box": [0.1140625, 0.2520833333333333, 0.0140625, 0.05625], "label": "person", "region": [0.0, 0.0, 0.5, 0.6666666666666666]}'])
2023-10-03 12:39:59.895699265  [2023-10-03 12:39:59] asyncio                        DEBUG   : Using selector: EpollSelector
2023-10-03 12:40:04.866280386  [2023-10-03 12:40:04] peewee                         DEBUG   : ('SELECT COUNT("t1"."id") FROM "recordings" AS "t1" WHERE (("t1"."camera" = ?) AND ("t1"."segment_size" > ?))', ['cobert', 0.0])
2023-10-03 12:40:04.870241709  [2023-10-03 12:40:04] peewee                         DEBUG   : ('SELECT AVG("t1"."segment_size" / ("t1"."end_time" - "t1"."start_time")) FROM "recordings" AS "t1" WHERE (("t1"."camera" = ?) AND ("t1"."segment_size" > ?)) LIMIT ?', ['cobert', 0.0, 100])
2023-10-03 12:40:04.871455429  [2023-10-03 12:40:04] frigate.storage                DEBUG   : cobert has a bandwidth of 0 MiB/hr.
2023-10-03 12:40:04.871704652  [2023-10-03 12:40:04] frigate.storage                DEBUG   : Default camera bandwidths: {'cobert': {'needs_refresh': True, 'bandwidth': 0}}.
2023-10-03 12:40:04.872013095  [2023-10-03 12:40:04] frigate.storage                DEBUG   : Storage cleanup check: 0 hourly with remaining storage: 11686.6.
2023-10-03 12:40:04.889548262  [2023-10-03 12:40:04] asyncio                        DEBUG   : Using selector: EpollSelector
2023-10-03 12:40:05.474143569  [2023-10-03 12:40:05] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera" FROM "event" AS "t1" WHERE (((("t1"."camera" NOT IN (?)) AND ("t1"."start_time" < ?)) AND ("t1"."label" = ?)) AND ("t1"."retain_indefinitely" = ?))', ['cobert', 1695465605.47096, 'person', False])
2023-10-03 12:40:05.477313158  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "has_clip" = ? WHERE (((("event"."camera" NOT IN (?)) AND ("event"."start_time" < ?)) AND ("event"."label" = ?)) AND ("event"."retain_indefinitely" = ?))
2023-10-03 12:40:05.477564257  [2023-10-03 12:40:05] peewee                         DEBUG   : ('UPDATE "event" SET "has_clip" = ? WHERE (((("event"."camera" NOT IN (?)) AND ("event"."start_time" < ?)) AND ("event"."label" = ?)) AND ("event"."retain_indefinitely" = ?))', [False, 'cobert', 1695465605.47096, 'person', False])
2023-10-03 12:40:05.479693358  [2023-10-03 12:40:05] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera" FROM "event" AS "t1" WHERE (((("t1"."camera" = ?) AND ("t1"."start_time" < ?)) AND ("t1"."label" = ?)) AND ("t1"."retain_indefinitely" = ?))', ['cobert', 1695465605.477137, 'person', False])
2023-10-03 12:40:05.481139166  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "has_clip" = ? WHERE (0 = 1)
2023-10-03 12:40:05.481377817  [2023-10-03 12:40:05] peewee                         DEBUG   : ('UPDATE "event" SET "has_clip" = ? WHERE (0 = 1)', [False])
2023-10-03 12:40:05.482413669  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query DELETE FROM "timeline" WHERE (0 = 1)
2023-10-03 12:40:05.482652475  [2023-10-03 12:40:05] peewee                         DEBUG   : ('DELETE FROM "timeline" WHERE (0 = 1)', [])
2023-10-03 12:40:05.485030853  [2023-10-03 12:40:05] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera" FROM "event" AS "t1" WHERE (((("t1"."camera" NOT IN (?)) AND ("t1"."start_time" < ?)) AND ("t1"."label" = ?)) AND ("t1"."retain_indefinitely" = ?))', ['cobert', 1695465605.482436, 'person', False])
2023-10-03 12:40:05.487949396  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "has_snapshot" = ? WHERE (((("event"."camera" NOT IN (?)) AND ("event"."start_time" < ?)) AND ("event"."label" = ?)) AND ("event"."retain_indefinitely" = ?))
2023-10-03 12:40:05.488275600  [2023-10-03 12:40:05] peewee                         DEBUG   : ('UPDATE "event" SET "has_snapshot" = ? WHERE (((("event"."camera" NOT IN (?)) AND ("event"."start_time" < ?)) AND ("event"."label" = ?)) AND ("event"."retain_indefinitely" = ?))', [False, 'cobert', 1695465605.482436, 'person', False])
2023-10-03 12:40:05.490462776  [2023-10-03 12:40:05] peewee                         DEBUG   : ('SELECT "t1"."id", "t1"."camera" FROM "event" AS "t1" WHERE (((("t1"."camera" = ?) AND ("t1"."start_time" < ?)) AND ("t1"."label" = ?)) AND ("t1"."retain_indefinitely" = ?))', ['cobert', 1695465605.48786, 'person', False])
2023-10-03 12:40:05.491983064  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query UPDATE "event" SET "has_snapshot" = ? WHERE (0 = 1)
2023-10-03 12:40:05.492225777  [2023-10-03 12:40:05] peewee                         DEBUG   : ('UPDATE "event" SET "has_snapshot" = ? WHERE (0 = 1)', [False])
2023-10-03 12:40:05.492950426  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query with grouped_events as (
2023-10-03 12:40:05.492956467            select id,
2023-10-03 12:40:05.492958967              label,
2023-10-03 12:40:05.492961207              camera,
2023-10-03 12:40:05.492963759              has_snapshot,
2023-10-03 12:40:05.492966051              has_clip,
2023-10-03 12:40:05.492968291              end_time,
2023-10-03 12:40:05.492970686              row_number() over (
2023-10-03 12:40:05.492973707                partition by label, camera, round(start_time/5,0)*5
2023-10-03 12:40:05.492976416                order by end_time-start_time desc
2023-10-03 12:40:05.492978760              ) as copy_number
2023-10-03 12:40:05.492980791            from event
2023-10-03 12:40:05.492982562          )
2023-10-03 12:40:05.492984228  
2023-10-03 12:40:05.492987718          select distinct id, camera, has_snapshot, has_clip from grouped_events
2023-10-03 12:40:05.492990478          where copy_number > 1 and end_time not null;
2023-10-03 12:40:05.493461893  [2023-10-03 12:40:05] peewee                         DEBUG   : ('with grouped_events as (\n          select id,\n            label,\n            camera,\n            has_snapshot,\n            has_clip,\n            end_time,\n            row_number() over (\n              partition by label, camera, round(start_time/5,0)*5\n              order by end_time-start_time desc\n            ) as copy_number\n          from event\n        )\n\n        select distinct id, camera, has_snapshot, has_clip from grouped_events\n        where copy_number > 1 and end_time not null;', [])
2023-10-03 12:40:05.495615787  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query DELETE FROM "event" WHERE (0 = 1)
2023-10-03 12:40:05.495861104  [2023-10-03 12:40:05] peewee                         DEBUG   : ('DELETE FROM "event" WHERE (0 = 1)', [])
2023-10-03 12:40:05.497220036  [2023-10-03 12:40:05] peewee.sqliteq                 DEBUG   : received query DELETE FROM "event" WHERE (("event"."has_clip" = ?) AND ("event"."has_snapshot" = ?))
2023-10-03 12:40:05.497432071  [2023-10-03 12:40:05] peewee                         DEBUG   : ('DELETE FROM "event" WHERE (("event"."has_clip" = ?) AND ("event"."has_snapshot" = ?))', [False, False])
2023-10-03 12:40:09.892309135  [2023-10-03 12:40:09] asyncio                        DEBUG   : Using selector: EpollSelector
```

**Comment by hawkeye217** [comment]
> From the "Imou Life" app I can set presets, eventhough there they are called as "Favorites", but they are the same thing. Maybe that is a feature not from the camera but from the app that works preety much as I described in the alternative solutions in the description of the ticket, so basically using coordenates to set these "Favorites". And we sould implement the same thing here for the cameras that have PTZ but do not implement 'presets'.

I'm just a contributor to the project, but I don't think the code owner is looking to maintain separate PTZ implementations for the different proprietary systems out there. ONVIF is an open standard for cameras that supports presets, and in my testing works with the camera brands that are recommended in the Frigate docs. I also don't believe any of the other maintainers have any Imou cameras, making it impossible to maintain any custom Imou code in Frigate.

But this is an open source project, so feel free to write some code and submit a PR.

**Comment by hawkeye217** [comment]
> ```
>       autotracking:
>         enabled: false
>         calibrate_on_startup: true
>         zooming: disabled
>         required_zones:
>         - zone_cobert
>         return_preset: PRESET_1
> ```
> 
> 
>     
>   
> 
> I managed to debug it but there isn't much relevant info in the logs.

You need to enable the autotracking system with `enabled: True` in order for `calibrate_on_startup` to do anything and for any autotracking debug logs to be produced.

**Comment by edurenye** [comment]
I feel stupid right now, for this test I forgot to enable it.
But firt time I tried was enabled, I disabed it because was not starting otherwise.

Will debug again.

**Comment by edurenye** [comment]
Now I get something else:
```
2023-10-03 23:33:13.650513888  [2023-10-03 23:33:13] frigate.ptz.onvif              WARNING : Unable to get presets from camera: cobert: Unknown error: This optional method is not implemented
2023-10-03 23:33:14.421076884  [2023-10-03 23:33:14] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +158, GPU +160, now: CPU 538, GPU 3216 (MiB)
2023-10-03 23:33:14.426261727  Traceback (most recent call last):
2023-10-03 23:33:14.426271987    File "/usr/local/lib/python3.9/dist-packages/zeep/xsd/valueobjects.py", line 154, in __getattribute__
2023-10-03 23:33:14.429134545      return self.__values__[key]
2023-10-03 23:33:14.429239286  KeyError: 'lower'
2023-10-03 23:33:14.429243713  
2023-10-03 23:33:14.429247620  During handling of the above exception, another exception occurred:
2023-10-03 23:33:14.429249495  
2023-10-03 23:33:14.429259026  Traceback (most recent call last):
2023-10-03 23:33:14.429811433    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-10-03 23:33:14.430773796      return _run_code(code, main_globals, None,
2023-10-03 23:33:14.430798744    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-10-03 23:33:14.431419799      exec(code, run_globals)
2023-10-03 23:33:14.431428340    File "/opt/frigate/frigate/__main__.py", line 17, in <module>
2023-10-03 23:33:14.432241013      frigate_app.start()
2023-10-03 23:33:14.432249659    File "/opt/frigate/frigate/app.py", line 610, in start
2023-10-03 23:33:14.434097612      self.start_ptz_autotracker()
2023-10-03 23:33:14.434143551    File "/opt/frigate/frigate/app.py", line 417, in start_ptz_autotracker
2023-10-03 23:33:14.434523090      self.ptz_autotracker_thread = PtzAutoTrackerThread(
2023-10-03 23:33:14.434531475    File "/opt/frigate/frigate/ptz/autotrack.py", line 136, in __init__
2023-10-03 23:33:14.435878377      self.ptz_autotracker = PtzAutoTracker(config, onvif, ptz_metrics)
2023-10-03 23:33:14.435918118    File "/opt/frigate/frigate/ptz/autotrack.py", line 189, in __init__
2023-10-03 23:33:14.436140362      self._autotracker_setup(cam, camera_name)
2023-10-03 23:33:14.436145882    File "/opt/frigate/frigate/ptz/autotrack.py", line 237, in _autotracker_setup
2023-10-03 23:33:14.436615944      self.onvif.get_camera_status(camera_name)
2023-10-03 23:33:14.436651934    File "/opt/frigate/frigate/ptz/onvif.py", line 501, in get_camera_status
2023-10-03 23:33:14.437368563      if pan_tilt_status is None or pan_tilt_status.lower() not in [
2023-10-03 23:33:14.437515702    File "/usr/local/lib/python3.9/dist-packages/zeep/xsd/valueobjects.py", line 156, in __getattribute__
2023-10-03 23:33:14.438239831      raise AttributeError(
2023-10-03 23:33:14.438614369  AttributeError: PTZMoveStatus instance has no attribute 'lower'
```
This error apears just when frigate is starting, so I guess it is the `calibrate_on_startup`.
And due to this error it does not get calibrated so it can not run afterwards.
The weird thing is that after this I do not get any more errors, but the server gets stuck and does not continue to start.
No more things in the logs except when I try to refresh the site I see the incoming conection, but no code error, it just answers with a 502 error message:
```
2023-10-03 23:35:35.972126035  source_ip - - [03/Oct/2023:23:35:35 +0200] "GET /api/config HTTP/1.1" 502 559 "http://destination_ip:5000/config" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "-"
```

**Comment by edurenye** [comment]
With the logger set to `debug` I don't get anything extra.

**Comment by edurenye** [comment]
I agree that frigate does not need to implement all the werid cameras out there.
I never coded for this project so it will take me a while to get into it, when I get some time to look into it, I will.
And I'll try to make a PR or I don't know if this could be extended with plugins or something like that.

But what should be handled better by frigate is the errors and the fact that if the camera does not support presets it should be checked, give a proper error in the logs, and skip the `autotracking` feature, but not break the server completely like it does now.
IMHO

**Comment by edurenye** [comment]
Well that error might not be related at all with tha fact that the camera does not support presets, because I connected another one that has presets and I'm having the same proble, the server breaks in the same way.

This is the error I'm seeing in the log:

```
2023-10-04 00:03:13.088133287  2023/10/04 00:03:13 [error] 161#161: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.194.9, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "192.168.194.41:5000", referrer: "http://192.168.194.41:5000/config"
2023-10-04 00:03:13.088344332  192.168.194.9 - - [04/Oct/2023:00:03:13 +0200] "GET /api/config HTTP/1.1" 502 559 "http://192.168.194.41:5000/config" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "-"
2023-10-04 00:03:13.190700459  2023/10/04 00:03:13 [error] 159#159: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.8.175, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.8.133:5000"
2023-10-04 00:03:13.191007652  192.168.8.175 - - [04/Oct/2023:00:03:13 +0200] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.9.3 aiohttp/3.8.5 Python/3.11" "-"
2023-10-04 00:03:13.824316967  Traceback (most recent call last):
2023-10-04 00:03:13.824326134    File "/opt/frigate/frigate/ptz/onvif.py", line 136, in _init_onvif
2023-10-04 00:03:13.824864998      move_request.Translation.Zoom.space = ptz_config["Spaces"][
2023-10-04 00:03:13.824872967  AttributeError: 'NoneType' object has no attribute 'Zoom'
2023-10-04 00:03:13.824874998  
2023-10-04 00:03:13.824883853  During handling of the above exception, another exception occurred:
2023-10-04 00:03:13.824886926  
2023-10-04 00:03:13.824889373  Traceback (most recent call last):
2023-10-04 00:03:13.825427561    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-10-04 00:03:13.825434957      return _run_code(code, main_globals, None,
2023-10-04 00:03:13.825437821    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-10-04 00:03:13.825590220      exec(code, run_globals)
2023-10-04 00:03:13.825742306    File "/opt/frigate/frigate/__main__.py", line 17, in <module>
2023-10-04 00:03:13.825877257      frigate_app.start()
2023-10-04 00:03:13.825882622    File "/opt/frigate/frigate/app.py", line 610, in start
2023-10-04 00:03:13.826363204      self.start_ptz_autotracker()
2023-10-04 00:03:13.826423986    File "/opt/frigate/frigate/app.py", line 417, in start_ptz_autotracker
2023-10-04 00:03:13.826891026      self.ptz_autotracker_thread = PtzAutoTrackerThread(
2023-10-04 00:03:13.827096239    File "/opt/frigate/frigate/ptz/autotrack.py", line 136, in __init__
2023-10-04 00:03:13.827627290      self.ptz_autotracker = PtzAutoTracker(config, onvif, ptz_metrics)
2023-10-04 00:03:13.827726563    File "/opt/frigate/frigate/ptz/autotrack.py", line 189, in __init__
2023-10-04 00:03:13.828168134      self._autotracker_setup(cam, camera_name)
2023-10-04 00:03:13.828175686    File "/opt/frigate/frigate/ptz/autotrack.py", line 210, in _autotracker_setup
2023-10-04 00:03:13.828492776      if not self.onvif._init_onvif(camera_name):
2023-10-04 00:03:13.828819449    File "/opt/frigate/frigate/ptz/onvif.py", line 140, in _init_onvif
2023-10-04 00:03:13.828826063      if self.config.cameras[camera_name].onvif.autotracking.zoom_relative:
2023-10-04 00:03:13.828829605  AttributeError: 'PtzAutotrackConfig' object has no attribute 'zoom_relative'
```
That is the same that I reported here https://github.com/blakeblackshear/frigate/issues/8026 And that happens also when autotracking enabled is set to false, so might not be related with the issue.

Then I get the same as before:
```
2023-10-04 00:04:04.033870257  2023/10/04 00:04:04 [error] 161#161: *3 connect() failed (111: Connection refused) while connecting to upstream, client: client_ip, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "server_ip:5000", referrer: "http://server_ip:5000/config"
2023-10-04 00:04:04.034973195  client_ip - - [04/Oct/2023:00:04:04 +0200] "GET /api/config HTTP/1.1" 502 559 "http://server_ip:5000/config" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "-"
```

**Comment by hawkeye217** [comment]
> Well that error might not be related at all with tha fact that the camera does not support presets, because I connected another one that has presets and I'm having the same proble, the server breaks in the same way.
> 
> This is the error I'm seeing in the log:
> 
> ```
> 2023-10-04 00:03:13.088133287  2023/10/04 00:03:13 [error] 161#161: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.194.9, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "192.168.194.41:5000", referrer: "http://192.168.194.41:5000/config"
> 2023-10-04 00:03:13.088344332  192.168.194.9 - - [04/Oct/2023:00:03:13 +0200] "GET /api/config HTTP/1.1" 502 559 "http://192.168.194.41:5000/config" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "-"
> 2023-10-04 00:03:13.190700459  2023/10/04 00:03:13 [error] 159#159: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.8.175, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "192.168.8.133:5000"
> 2023-10-04 00:03:13.191007652  192.168.8.175 - - [04/Oct/2023:00:03:13 +0200] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.9.3 aiohttp/3.8.5 Python/3.11" "-"
> 2023-10-04 00:03:13.824316967  Traceback (most recent call last):
> 2023-10-04 00:03:13.824326134    File "/opt/frigate/frigate/ptz/onvif.py", line 136, in _init_onvif
> 2023-10-04 00:03:13.824864998      move_request.Translation.Zoom.space = ptz_config["Spaces"][
> 2023-10-04 00:03:13.824872967  AttributeError: 'NoneType' object has no attribute 'Zoom'
> 2023-10-04 00:03:13.824874998  
> 2023-10-04 00:03:13.824883853  During handling of the above exception, another exception occurred:
> 2023-10-04 00:03:13.824886926  
> 2023-10-04 00:03:13.824889373  Traceback (most recent call last):
> 2023-10-04 00:03:13.825427561    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> 2023-10-04 00:03:13.825434957      return _run_code(code, main_globals, None,
> 2023-10-04 00:03:13.825437821    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
> 2023-10-04 00:03:13.825590220      exec(code, run_globals)
> 2023-10-04 00:03:13.825742306    File "/opt/frigate/frigate/__main__.py", line 17, in <module>
> 2023-10-04 00:03:13.825877257      frigate_app.start()
> 2023-10-04 00:03:13.825882622    File "/opt/frigate/frigate/app.py", line 610, in start
> 2023-10-04 00:03:13.826363204      self.start_ptz_autotracker()
> 2023-10-04 00:03:13.826423986    File "/opt/frigate/frigate/app.py", line 417, in start_ptz_autotracker
> 2023-10-04 00:03:13.826891026      self.ptz_autotracker_thread = PtzAutoTrackerThread(
> 2023-10-04 00:03:13.827096239    File "/opt/frigate/frigate/ptz/autotrack.py", line 136, in __init__
> 2023-10-04 00:03:13.827627290      self.ptz_autotracker = PtzAutoTracker(config, onvif, ptz_metrics)
> 2023-10-04 00:03:13.827726563    File "/opt/frigate/frigate/ptz/autotrack.py", line 189, in __init__
> 2023-10-04 00:03:13.828168134      self._autotracker_setup(cam, camera_name)
> 2023-10-04 00:03:13.828175686    File "/opt/frigate/frigate/ptz/autotrack.py", line 210, in _autotracker_setup
> 2023-10-04 00:03:13.828492776      if not self.onvif._init_onvif(camera_name):
> 2023-10-04 00:03:13.828819449    File "/opt/frigate/frigate/ptz/onvif.py", line 140, in _init_onvif
> 2023-10-04 00:03:13.828826063      if self.config.cameras[camera_name].onvif.autotracking.zoom_relative:
> 2023-10-04 00:03:13.828829605  AttributeError: 'PtzAutotrackConfig' object has no attribute 'zoom_relative'
> ```
> 
> That is the same that I reported here #8026 And that happens also when autotracking enabled is set to false, so might not be related with the issue.
> 
> Then I get the same as before:
> 
> ```
> 2023-10-04 00:04:04.033870257  2023/10/04 00:04:04 [error] 161#161: *3 connect() failed (111: Connection refused) while connecting to upstream, client: client_ip, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "server_ip:5000", referrer: "http://server_ip:5000/config"
> 2023-10-04 00:04:04.034973195  client_ip - - [04/Oct/2023:00:04:04 +0200] "GET /api/config HTTP/1.1" 502 559 "http://server_ip:5000/config" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "-"
> ```

This is fixed in https://github.com/blakeblackshear/frigate/pull/8046

**Comment by fvear** [comment]
> **Describe what you are trying to accomplish and why in non technical terms** I want to be able to set autotracking for my camera so that I can autotrack lol
> 
> My camera is a Imou IPC-S21FE, it has onvif protocol support and presets that I can use from the oficial app but from frigate I can PTZ but it does not detect the presets so I can not use the home option mandatory for autotracking.
> 
> **Describe the solution you'd like** To not have home option as mandatory.
> 
> **Describe alternatives you've considered** Add an option to set coordinates like for the (movement_weights) Set an option for calculated possitions, something like 'middle possition' and it gets calculated during the calibration process if `calibrate_on_startup` is set to `true`.
> 
> **Additional context** This afects the last options added here: https://deploy-preview-6262--frigate-docs.netlify.app/configuration/autotracking

Hi @edurenye, I am also trying to get the IPC-S21FE working with autotracking but I am experiencing the exact same problem with Frigate [0.13.0 Beta 6]. 

Did you already manage to find a solution for this?

**Comment by edurenye** [comment]
Sorry, I have not been able to continue with it becasue I had frigate on a Jetson Nano dev board and one day after restarting it it di not boot up again, I'm trying to fix it. When I get that fixed I will try again on this.

**Comment by fvear** [comment]
> Sorry, I have not been able to continue with it becasue I had frigate on a Jetson Nano dev board and one day after restarting it it di not boot up again, I'm trying to fix it. When I get that fixed I will try again on this.

Your assistance would be highly valued because I believe that once PTZ is operational in Frigate, and it is, that autotracking should also work after calibration for the IPC-S21FE.

**Comment by doreks** [comment]
hi @edurenye  

i am having some configuration problems with my imou camera model IPC-S21FE, would you mind sharing with me how you have it configured ?

thanks for your time and support!

Br

**Comment by edurenye** [comment]
I have mine set up like this, but I haven't managed to make the autotracking to work.
And I'm not sure if this is the best way to configure it.
```
go2rtc:
  streams:
    imou-hd:
      - onvif://user:password@ip_address?subtype=Profile000
      - ffmpeg:cobert-hd#audio=opus
  webrtc:
    candidates:
      - host.docker.internal:8555
      - stun:8555
cameras:
  imou:
      ffmpeg:
        output_args:
          record: preset-record-generic-audio-copy
        hwaccel_args: preset-nvidia-h264
        inputs:
          - path: rtsp://127.0.0.1:8554/imou-hd
            input_args: preset-rtsp-restream
      onvif:
        host: ip_address
        port: 80
        user: user
        password: password
```

**Comment by thewan056** [comment]
PTZ imou cameras, at least the ones I have, support presets using SmartPSS. You can use Dahua software, SmartPSS to set PTZ presets, and then use those presets in the same software. I can also confirm they stay there because you can close SmartPSS and relaunch it and the presets still work.  However I notice they don't support naming the presets, the preset saves but not the name if you name them. 

Are settings set in SmartPSS use onvif? I can tell those presets are different from the ones in the Imou Life App, because I set them in the app before trying SmartPSS and the presets in SmartPSS did nothing before I set them up again. If they are not onvif and proprietary like the app is, maybe the presets are saved in SmartPSS, not on the camera.

I think they also do not support retrieving the presets, as Frigate logs say my it is not implemented and unable to get those presets. Maybe Frigate can add the option to try to just send the preset token, not name since no name support, to the camera without attempting to retrieving them?

**Comment by hawkeye217** [comment]
Frigate doesn't implement vendor-specific hacks for a number of reasons. If your presets are not exposed via ONVIF, you could reach out to the camera manufacturer to see if they could change it with a firmware update.
