### ISSUE TITLE
Web interface inaccessible after updating to 0.8.2 armv7

### ISSUE THREAD

**Issue by S-Przybylski** [blakeblackshear/frigate#808]
**Describe the bug**
Get error when starting just created 0.8.2-armv7 built image.

**Version of frigate**
Output from `0.8.2 2021-02-17`

**Config file**
Include your full config file wrapped in triple back ticks.
```yaml
n/a
```

**Frigate container logs**
```
2021-02-17T14:06:16.041871351Z  * Starting nginx nginx
2021-02-17T14:06:16.071446023Z    ...done.
2021-02-17T14:06:17.212525606Z RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
2021-02-17T14:06:17.212595161Z Traceback (most recent call last):
2021-02-17T14:06:17.212618772Z   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-02-17T14:06:17.212641697Z     return _run_code(code, main_globals, None,
2021-02-17T14:06:17.212663178Z   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-02-17T14:06:17.212683289Z     exec(code, run_globals)
2021-02-17T14:06:17.212704030Z   File "/opt/frigate/frigate/__main__.py", line 7, in <module>
2021-02-17T14:06:17.212724770Z     from frigate.app import FrigateApp
2021-02-17T14:06:17.212744140Z   File "/opt/frigate/frigate/app.py", line 17, in <module>
2021-02-17T14:06:17.212771603Z     from frigate.config import FrigateConfig
2021-02-17T14:06:17.212792380Z   File "/opt/frigate/frigate/config.py", line 8, in <module>
2021-02-17T14:06:17.213109599Z     import matplotlib.pyplot as plt
2021-02-17T14:06:17.213152839Z   File "/usr/local/lib/python3.8/dist-packages/matplotlib/__init__.py", line 174, in <module>
2021-02-17T14:06:17.213457446Z     _check_versions()
2021-02-17T14:06:17.213489798Z   File "/usr/local/lib/python3.8/dist-packages/matplotlib/__init__.py", line 159, in _check_versions
2021-02-17T14:06:17.213942551Z     from . import ft2font
2021-02-17T14:06:17.213980236Z ImportError: numpy.core.multiarray failed to import

```

**Computer Hardware**
 - OS: Docker on RASPI 4 RASPI OS

**Comment by S-Przybylski** [comment]
Problem seems to be resolved by unpinning the version of numpy
Dockerfile.wheels:
25 RUN pip3 wheel --wheel-dir=/wheels \
26     opencv-python-headless \
27     # pinning due to issue in 1.19.5 https://github.com/numpy/numpy/issues/1$
28     numpy \

But now I have issues accessing the web interface of frigate.

**Comment by blakeblackshear** [comment]
i unpinned. see if you are still having issues

**Comment by S-Przybylski** [comment]
Dear @blakeblackshear 
I just rebuilt the docker image using make armv7_frigate by taking all other images from you out of the docker repo.

Problem 1 is gone! Thanks
Problem 2 occured again, but later on went partly away and come back:
Start is ok; standard log doesn't show anything. Last entry is, that the TPU was found.
If I open my HA dashboard, then I only can see one camera picture. The remaining five are not available then.
Then i try to open the Frigate web interface. What I can see here is, the name FRIGATE and the Logo and a loading symbol.
After 1-2 min. I can see the frames of the camera elements without any content. (Pi ~80% load as usual)
I waited 5 min.: Now I can see the cameras in HA, and Frigate is accessable as usual.
No entries in the logs!
Restarted the container: Everything is fine after starting ( tested only a short time).
Recycled the container: Start ok; then the same again! After some minutes, i see the cameras in HA, but Frigate webconsole is not responsive!

Between the testcases I openened different dashboards in HA. If I navigate between all dashboad items, showing cameras and also the debug stream for all cameras, then problem is occuring!

Conclusion: It seems that the number of parallel connetions to the webinterface (incl. debug streams) is limited somehow!

If I got back to an earlier build (also 0.8.2) using "git checkout 4df1ae9764a1bc5030796e4964f0fbbe48b07808" rebuild the docker image again, then everything is fine with the identical configuration!

My configuration:
I use six cameras, no recording, no rtmp (i prefer to work with debug mjpeg stream through your HA integration - for me its much faster then the rmtp stream - only 2-3 sec delay at all)

Any idea about that?

**Comment by S-Przybylski** [comment]
Dear @blakeblackshear 
dear @paularmstrong 
Today i installed the official master docker image for ARMv7. I fall into the same problem like yesterday with a pre build and found a simple way to reproduce the issue:
![grafik](https://user-images.githubusercontent.com/45458593/108606958-c0777700-73bd-11eb-9d2a-8d3947f3f353.png)
Restart frigate container #HA is down
Test:
open browser tab#1: http://frigate:5000/api/cam1
open browser tab#2: http://frigate:5000/api/cam2
Result: 
tab#1 works
tab#2 bad gateway 504 / loading ....
Funny: If you reload the tab#1 then tab#2 gets working and tab#1 died

Its independent if you open the same or other cameras at the same time.

If I go back to the commit https://github.com/blakeblackshear/frigate/commit/4df1ae9764a1bc5030796e4964f0fbbe48b07808 (part of 0.8.2) then I can open all 6 debug test streams at the same time!

````
2021-02-20T19:40:13.916775566Z  * Starting nginx nginx
2021-02-20T19:40:13.961513184Z    ...done.
2021-02-20T19:40:17.088036166Z Starting migrations
2021-02-20T19:40:17.088113610Z peewee_migrate                 INFO    : Starting migrations
2021-02-20T19:40:17.101277428Z There is nothing to migrate
2021-02-20T19:40:17.101360520Z peewee_migrate                 INFO    : There is nothing to migrate
2021-02-20T19:40:17.183582299Z detector.coral                 INFO    : Starting detection process: 33
2021-02-20T19:40:17.209480440Z frigate.edgetpu                INFO    : Attempting to load TPU as usb
2021-02-20T19:40:17.226134219Z frigate.app                    INFO    : Camera processor started for cam1: 35
2021-02-20T19:40:17.228546952Z frigate.app                    INFO    : Camera processor started for cam2: 37
2021-02-20T19:40:17.232266744Z frigate.app                    INFO    : Camera processor started for cam3: 39
2021-02-20T19:40:17.267704409Z frigate.app                    INFO    : Camera processor started for cam4: 41
2021-02-20T19:40:17.283086981Z frigate.app                    INFO    : Camera processor started for cam5: 42
2021-02-20T19:40:17.344145938Z frigate.app                    INFO    : Camera processor started for cam6: 44
2021-02-20T19:40:17.345339628Z frigate.app                    INFO    : Capture process started for cam1: 45
2021-02-20T19:40:17.374274717Z frigate.app                    INFO    : Capture process started for cam2: 47
2021-02-20T19:40:17.397720773Z frigate.app                    INFO    : Capture process started for cam3: 50
2021-02-20T19:40:17.471763846Z frigate.app                    INFO    : Capture process started for cam4: 55
2021-02-20T19:40:17.517036292Z frigate.app                    INFO    : Capture process started for cam5: 57
2021-02-20T19:40:17.517569990Z frigate.app                    INFO    : Capture process started for cam6: 64
2021-02-20T19:40:20.110135577Z frigate.edgetpu                INFO    : TPU found
````

````
logger:
  default: info
  logs:
    frigate.mqtt: error
database:
  path: /media/frigate/clips/frigate.db
detectors:
  coral:
    type: edgetpu
    num_threads: 3
model:
  height: 320
  width: 320
mqtt:
  host: mqtt
  port: 1883
  topic_prefix: frigate
  client_id: frigate
snapshots:
  retain:
    default: 10
    objects:
      person: 10
clips:
  max_seconds: 300
  retain:
    default: 10
    objects:
      person: 10
ffmpeg:
  global_args: -hide_banner -loglevel fatal
  hwaccel_args:
    - -c:v
    - h264_mmal
  input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  output_args: 
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
    rtmp: -c copy -f flv
objects:
  track:
    - person
  filters:
    person:
      min_area: 100
      max_area: 900000
      min_score: 0.2
      threshold: 0.6

cameras:
  cam1:	# note: cam2, cam3, cam4, cam5, cam6 identically configured
    ffmpeg:
      inputs: 
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@camera1:80/0 # 8MP 20FPS
          roles:
            - clips
        - path: rtsp://user:{FRIGATE_RTSP_PASSWORD}@camera1:80/1 # 720/480 20FPS
          roles:
            - detect
    width: 720
    height: 480
    fps: 5
    motion:
      mask: <mask_deleted>
    best_image_timeout: 10
    detect:
      enabled: True
      max_disappeared: 20
    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5
      objects:
        - person
      retain:
        default: 10
        objects:
          person: 15  
    record:
      enabled: False
      retain_days: 30
    rtmp:
      enabled: False
    snapshots:
      enabled: True
      timestamp: False
      bounding_box: False
      crop: False
      height: 175
      retain:
        default: 10
        objects:
          person: 10
    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
````

**Comment by S-Przybylski** [comment]
Dear @blakeblackshear 
dear @paularmstrong 
I checked today the new release 0.8.3 without success.
API doesn't work as expected - simple test:
open browser tab#1: http://frigate:5000/api/cam1
open browser tab#2: http://frigate:5000/api/cam2 # cam1 could also be used
Result:
 tab#1 works
 tab#2 bad gateway 502
in general the frigate web service isn't reachable while tab#1 and 2 are open

**Comment by blakeblackshear** [comment]
I think its just the mjpeg endpoint. I can view the live view of a camera in the webui in multiple tabs simultaneously.

**Comment by S-Przybylski** [comment]
Dear @blakeblackshear 
If you open the api/camera endpoint the whole frigate webserver is inaccessible then too.
For me its vital to grab the configurable mjpeg from the api for several cameras and therefore wish that the endpoint could be used in parallel again.
Which endpoint do you connect with the HA integration when RMTP is off?

**Comment by S-Przybylski** [comment]
Dear @blakeblackshear 
thanks for the fix! Its working!
I have tested it with 0.8.4-35f7335
