### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by Beardless-Beta** [blakeblackshear/frigate#8105]
### Describe the problem you are having

My instance is stuck in a restart loop, it was working fine the past few days, made some integrations into home assistant gave it a restart and now it's getting an module not found error for urllib3.

### Version

Sorry, I can't get this as i can't boot the Web UI

### Frigate config file

```yaml
mqtt:
  host: redacted
  port: redacted
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user
  password: redacted
  stats_interval: 60

######################################################################
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

objects:
  track:
    - person
    - cat

snapshots:
  enabled: true

record:
  enabled: True
  retain:
    days: 5
  events:
    retain:
      default: 21

go2rtc:
  streams:
    reolink:
      - "ffmpeg:http://redacted/flv?port=1901&app=bcs&stream=channel0_main.bcs&user=admin&password=redacted>
      - "ffmpeg:http://redacted/flv?port=1901&app=bcs&stream=channel0_ext.bcs&user=admin&password=redacted>

cameras:
  doorbell:
    enabled: True
    zones:
      front:
        coordinates: 0,720,1280,720,1280,565,1171,503,877,511,750,507,516,489,245,451,0,489
    ffmpeg:
      inputs:
        - path: rtsp://redacted:redacted@redacted:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - rtmp
        - path: rtsp://redacted:redacted@redacted:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        record: preset-record-generic-audio-copy
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-10-09 09:43:40.469377335  [INFO] Preparing go2rtc config...
2023-10-09 09:43:40.471266260  [INFO] Starting Frigate...
2023-10-09 09:43:40.473230574  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-10-09 09:43:40.574772247  [INFO] Starting go2rtc...
2023-10-09 09:43:40.645513105  09:43:40.645 INF go2rtc version 1.2.0 linux/amd64
2023-10-09 09:43:40.645676967  09:43:40.645 INF [api] listen addr=:1984
2023-10-09 09:43:40.645853510  09:43:40.645 INF [rtsp] listen addr=:8554
2023-10-09 09:43:40.645995900  09:43:40.645 INF [srtp] listen addr=:8443
2023-10-09 09:43:40.646111376  09:43:40.646 INF [webrtc] listen addr=:8555
2023-10-09 09:43:40.868557351  Traceback (most recent call last):
2023-10-09 09:43:40.868560999    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-10-09 09:43:40.868572746      return _run_code(code, main_globals, None,
2023-10-09 09:43:40.868573430    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-10-09 09:43:40.868666386      exec(code, run_globals)
2023-10-09 09:43:40.868667750    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-10-09 09:43:40.868668417      from frigate.app import FrigateApp
2023-10-09 09:43:40.868670081    File "/opt/frigate/frigate/app.py", line 24, in <module>
2023-10-09 09:43:40.868671080      from frigate.http import create_app
2023-10-09 09:43:40.868671603    File "/opt/frigate/frigate/http.py", line 38, in <module>
2023-10-09 09:43:40.868681890      from frigate.stats import stats_snapshot
2023-10-09 09:43:40.868682504    File "/opt/frigate/frigate/stats.py", line 9, in <module>
2023-10-09 09:43:40.868683292      import requests
2023-10-09 09:43:40.868684184    File "/usr/local/lib/python3.9/dist-packages/requests/__init__.py", line 43, in <module>
2023-10-09 09:43:40.868690119      import urllib3
2023-10-09 09:43:40.868690722    File "/usr/local/lib/python3.9/dist-packages/urllib3/__init__.py", line 12, in <module>
2023-10-09 09:43:40.868693014      from ._version import __version__
2023-10-09 09:43:40.868695084  ModuleNotFoundError: No module named 'urllib3._version'
2023-10-09 09:43:40.917799432  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-10-09 09:43:40.923101413  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-10-09 09:43:41.088635216  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-10-09 09:43:41.096102090  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-10-09 09:43:41.104617855  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by Beardless-Beta** [comment]
Creating a modified image, allows me to boot properly with no error, though i'm unsure what dependency issues this creates

FROM ghcr.io/blakeblackshear/frigate:stable
RUN pip install --upgrade urllib3


I've got the version number now that i've booted -- 0.12.1-367d724

**Comment by NickM-27** [comment]
weird, I've never seen an issue like that before. What is your docker compose

**Comment by Beardless-Beta** [comment]
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "250mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /media/frigate/config.yml:/config/config.yml
      - /media/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
