### ISSUE TITLE
[Detector Support]: Use a custom .tflite model

### ISSUE THREAD

**Issue by Devstored** [blakeblackshear/frigate#8111]
### Describe the problem you are having

Hi,

I'm trying to install a custom template in Frigate+ (0.13.0-beta2).

**Configuration**
- Synology DS718+ NAS (DSM 7.2-64570 Update 3)
- Google Coral USB
- Frigate+ 0.13.0-beta2 with docker-compose (Portainer)
- label-studio (to create annotations)
- Ultralytics (to train the model and generate the .tflite) with YOLOV8

**Frigate+ Docker-compose**
```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #network_mode: host
    networks:
      frigate_network:
      host_bridge:
        ipv4_address: 192.168.10.4
    image: "ghcr.io/blakeblackshear/frigate:0.13.0-beta2"
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config:/config
      - /volume1/docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "9079:5000"
      - "1935:1935/tcp"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      PGID: 100
      PUID: 1026
      TZ: Europe/Paris
      FRIGATE_RTSP_PASSWORD: "xxxxxxxx"
      PLUS_API_KEY: "xxxxxxxxxx-xxxxxxx-xxxxxx"
      LIBVA_DRIVER_NAME: "i965"
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  frigate_network:
    external: true
  host_bridge:
    external: true
```

**config.yml for Frigate+**

```mqtt:
  enabled: True
  host: 192.168.10.1
  port: 1883
  user: xxxxx
  password: xxxxxxxxxxxx
  topic_prefix: frigate

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

model:
  path: /config/models/best_full_integer_quant.tflite
  width: 640
  height: 640

cameras:
  distributeur_croquette:
    ffmpeg:
      inputs:
        - path: rtsp://bestadmin:bestpassword@192.168.50.11:554/stream1
          roles:
            - detect
    record:
      events:
        required_zones:
          - bol_croquette
    detect:
      width: 1280
      height: 720
      fps: 5
    

objects:
  track:
    - person
    - cat
    - cell phone
    - BolVide
    - Croquettes

snapshots:
  enabled: True
```

**Python script Ultralytics**

```from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch
# load a pretrained model (recommended for training)
model = YOLO("yolov8n.pt")

# Use the model
model.train(data="config.yml", epochs=100)  # train the model
metrics = model.val()  # evaluate model performance on the validation set
# export the model to ONNX format
path = model.export(format='tflite', int8=True)
```

With this Ultralytics configuration, I can generate several .tflite files:

- best_float16.tflite
- best_float32.tflite
- best_full_integer_quant.tflite
- best_int8.tflite
- best_integer_quant.tflite

According to ChatGPT it is preferable to use the "best_full_integer_quant.tflite"

I also tried using this Google Coral link to convert a .tflite file to be optimized for Edge TPU: https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb but I believe there is no need with the tflite generation of YOLOV8 : 
- best_integer_quant_edgetpu.tflite

**With this configuration, Frigate keeps restarting due to the following error**

```2023-10-09 19:43:16.443695846  [2023-10-09 19:43:13] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-09 19:43:16.446812330  [2023-10-09 19:43:16] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-10-09 19:43:16.458168524  Process detector:coral:
2023-10-09 19:43:16.459633417  Traceback (most recent call last):
2023-10-09 19:43:16.459666870    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-09 19:43:16.459669215      self.run()
2023-10-09 19:43:16.459679574    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-09 19:43:16.459681864      self._target(*self._args, **self._kwargs)
2023-10-09 19:43:16.459683944    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2023-10-09 19:43:16.459685927      detections = object_detector.detect_raw(input_frame)
2023-10-09 19:43:16.459688022    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2023-10-09 19:43:16.459689995      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-10-09 19:43:16.459737253    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 59, in detect_raw
2023-10-09 19:43:16.459740636      self.interpreter.set_tensor(self.tensor_input_details[0]["index"], tensor_input)
2023-10-09 19:43:16.459742984    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 572, in set_tensor
2023-10-09 19:43:16.459744940      self._interpreter.SetTensor(tensor_index, value)
2023-10-09 19:43:16.459747297  ValueError: Cannot set tensor: Got value of type UINT8 but expected type FLOAT32 for input 0, name: inputs_0 
2023-10-09 19:43:19.873694017  192.168.10.1 - - [09/Oct/2023:19:43:19 +0200] "GET /api/stats HTTP/1.1" 200 5026 "-" "HomeAssistant/2023.9.3 aiohttp/3.8.5 Python/3.11" "-"
2023-10-09 19:43:23.619624915  [2023-10-09 19:43:23] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
```

I tried with all the .tflite files listed above and that doesn't work either. I tried to remove the "int8=True" argument in the Ultralytics script but I still get the same error message.

I haven't seen any discussion explaining how to use a .tflite file in Frigate to date (I've looked through 100s of issues!).

I also tried with stable versions of Frigate. But the result is the same

If anyone has any answers for me on this subject I think it could be useful to a lot of people.

Last question, if I use a custom model in Frigate, will the basic model containing the detection of people, animals, etc. still be usable?

Thank you all for your help!

### Version

0.13.0-beta2

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.10.1
  port: 1883
  user: xxxxx
  password: xxxxxxxxxxxx
  topic_prefix: frigate

detectors: # <---- add detectors
  coral:
    type: edgetpu
    device: usb

model:
  path: /config/models/best_full_integer_quant.tflite
  width: 640
  height: 640

cameras:
  distributeur_croquette:
    ffmpeg:
      inputs:
        - path: rtsp://bestadmin:bestpassword@192.168.50.11:554/stream1
          roles:
            - detect
    record:
      events:
        required_zones:
          - bol_croquette
    detect:
      width: 1280
      height: 720
      fps: 5
    

objects:
  track:
    - person
    - cat
    - cell phone
    - BolVide
    - Croquettes

snapshots:
  enabled: True
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    #network_mode: host
    networks:
      frigate_network:
      host_bridge:
        ipv4_address: 192.168.10.4
    image: "ghcr.io/blakeblackshear/frigate:0.13.0-beta2"
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128
      #- /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/frigate/config:/config
      - /volume1/docker/frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "9079:5000"
      - "1935:1935/tcp"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      PGID: 100
      PUID: 1026
      TZ: Europe/Paris
      FRIGATE_RTSP_PASSWORD: "xxxxxxxx"
      PLUS_API_KEY: "xxxxxxxxxx-xxxxxxx-xxxxxx"
      LIBVA_DRIVER_NAME: "i965"
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  frigate_network:
    external: true
  host_bridge:
    external: true
```

### Relevant log output

```shell
2023-10-09 19:43:16.443695846  [2023-10-09 19:43:13] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-09 19:43:16.446812330  [2023-10-09 19:43:16] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-10-09 19:43:16.458168524  Process detector:coral:
2023-10-09 19:43:16.459633417  Traceback (most recent call last):
2023-10-09 19:43:16.459666870    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-09 19:43:16.459669215      self.run()
2023-10-09 19:43:16.459679574    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-09 19:43:16.459681864      self._target(*self._args, **self._kwargs)
2023-10-09 19:43:16.459683944    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2023-10-09 19:43:16.459685927      detections = object_detector.detect_raw(input_frame)
2023-10-09 19:43:16.459688022    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2023-10-09 19:43:16.459689995      return self.detect_api.detect_raw(tensor_input=tensor_input)
2023-10-09 19:43:16.459737253    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 59, in detect_raw
2023-10-09 19:43:16.459740636      self.interpreter.set_tensor(self.tensor_input_details[0]["index"], tensor_input)
2023-10-09 19:43:16.459742984    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 572, in set_tensor
2023-10-09 19:43:16.459744940      self._interpreter.SetTensor(tensor_index, value)
2023-10-09 19:43:16.459747297  ValueError: Cannot set tensor: Got value of type UINT8 but expected type FLOAT32 for input 0, name: inputs_0 
2023-10-09 19:43:19.873694017  192.168.10.1 - - [09/Oct/2023:19:43:19 +0200] "GET /api/stats HTTP/1.1" 200 5026 "-" "HomeAssistant/2023.9.3 aiohttp/3.8.5 Python/3.11" "-"
2023-10-09 19:43:23.619624915  [2023-10-09 19:43:23] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
```

### Operating system

Other

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
I'm confused, all of this seems completely unrelated to frigate+ 

In any case, YOLO models are not currently supported in frigate via edgetpu. They're supported via openvino and tensorrt detectors.

**Comment by Devstored** [comment]
> I'm confused, all of this seems completely unrelated to frigate+
> 
> In any case, YOLO models are not currently supported in frigate via edgetpu. They're supported via openvino and tensorrt detectors.

Thank you for your express feedback! Thanks to you, I know that we shouldn't look in that direction.

Do you know any documentation or the procedure to follow to generate .tflite custom models (with Google Coral) compatible with Frigate?

Thank you so much !

**Comment by blakeblackshear** [comment]
I would recommend following the documentation at coral.ai for creating a compatible model.
