### ISSUE TITLE
[Support]: Runtime error because of  numpy versions conflict

### ISSUE THREAD

**Issue by boerti71** [blakeblackshear/frigate#8145]
### Describe the problem you are having

Hej!
I'm getting following error:
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf 
when i start containter with docker compose up

I tried different numpy verison, but it tells me always that my version is 0xF
I tried with version 1.20.0 as also with the newest 

>>hardware är Raspi 4 with 4GB

### Version

newly installed

### Frigate config file

```yaml
mqtt:
  enabled: false

fmpeg:
  hwaccel_args: preset-rpi-64-h264 #Enable Hardware Acceleration

cameras:
  Entre: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:Duderin0@192.168.1.72:554/h264/ch2/main/av_stream # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 3840 # <---- update for your camera's resolution
      height: 2160 # <---- update for your camera's resolution
```

### Relevant log output

```shell
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service log-prepare: starting
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service frigate: starting
frigate  | s6-rc: info: service frigate successfully started
frigate  | s6-rc: info: service nginx: starting
frigate  | 2023-10-13 09:28:27.613016972  [INFO] Preparing go2rtc config...
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | s6-rc: info: service nginx successfully started
frigate  | s6-rc: info: service legacy-services: starting
frigate  | 2023-10-13 09:28:27.630513664  [INFO] Starting Frigate...
frigate  | 2023-10-13 09:28:27.634252876  [INFO] Starting NGINX...
frigate  | s6-rc: info: service legacy-services successfully started
frigate  | 2023-10-13 09:28:28.332250183  [INFO] Starting go2rtc...
frigate  | 2023-10-13 09:28:28.498276470  09:28:28.498 INF go2rtc version 1.2.0 linux/arm
frigate  | 2023-10-13 09:28:28.499527966  09:28:28.499 INF [api] listen addr=:1984
frigate  | 2023-10-13 09:28:28.500870035  09:28:28.500 INF [rtsp] listen addr=:8554
frigate  | 2023-10-13 09:28:28.502247511  09:28:28.502 INF [srtp] listen addr=:8443
frigate  | 2023-10-13 09:28:28.503540099  09:28:28.503 INF [webrtc] listen addr=:8555
frigate  | 2023-10-13 09:28:28.518232267  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
frigate  | 2023-10-13 09:28:28.518842016  Traceback (most recent call last):
frigate  | 2023-10-13 09:28:28.518862200    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
frigate  | 2023-10-13 09:28:28.520253269      return _run_code(code, main_globals, None,
frigate  | 2023-10-13 09:28:28.520274472    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
frigate  | 2023-10-13 09:28:28.520459672      exec(code, run_globals)
frigate  | 2023-10-13 09:28:28.520471431    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
frigate  | 2023-10-13 09:28:28.521481673      from frigate.app import FrigateApp
frigate  | 2023-10-13 09:28:28.521502265    File "/opt/frigate/frigate/app.py", line 17, in <module>
frigate  | 2023-10-13 09:28:28.521850296      from frigate.comms.dispatcher import Communicator, Dispatcher
frigate  | 2023-10-13 09:28:28.522192938    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
frigate  | 2023-10-13 09:28:28.522957832      from frigate.config import FrigateConfig
frigate  | 2023-10-13 09:28:28.523135348    File "/opt/frigate/frigate/config.py", line 9, in <module>
frigate  | 2023-10-13 09:28:28.523619561      import matplotlib.pyplot as plt
frigate  | 2023-10-13 09:28:28.523663116    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
frigate  | 2023-10-13 09:28:28.524048961      from . import _api, _version, cbook, _docstring, rcsetup
frigate  | 2023-10-13 09:28:28.524096312    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
frigate  | 2023-10-13 09:28:28.525057684      from matplotlib.colors import Colormap, is_color_like
frigate  | 2023-10-13 09:28:28.525323717    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
frigate  | 2023-10-13 09:28:28.525545194      from matplotlib import _api, _cm, cbook, scale
frigate  | 2023-10-13 09:28:28.525561120    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
frigate  | 2023-10-13 09:28:28.525811486      from matplotlib.ticker import (
frigate  | 2023-10-13 09:28:28.525827837    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
frigate  | 2023-10-13 09:28:28.526986465      from matplotlib import transforms as mtransforms
frigate  | 2023-10-13 09:28:28.527007872    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
frigate  | 2023-10-13 09:28:28.527340274      from matplotlib._path import (
frigate  | 2023-10-13 09:28:28.527554566  ImportError: numpy.core.multiarray failed to import
frigate  | 2023-10-13 09:28:28.667105911  [INFO] Service Frigate exited with code 1 (by signal 0)
frigate  | s6-rc: info: service legacy-services: stopping
frigate  | s6-rc: info: service legacy-services successfully stopped
frigate  | s6-rc: info: service nginx: stopping
frigate  | s6-rc: info: service go2rtc-healthcheck: stopping
frigate  | 2023-10-13 09:28:28.701874967  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
frigate  | s6-rc: info: service go2rtc-healthcheck successfully stopped
frigate  | 2023-10-13 09:28:28.770415781  [INFO] Service NGINX exited with code 0 (by signal 0)
frigate  | s6-rc: info: service nginx successfully stopped
frigate  | s6-rc: info: service nginx-log: stopping
frigate  | s6-rc: info: service frigate: stopping
frigate  | s6-rc: info: service frigate successfully stopped
frigate  | s6-rc: info: service go2rtc: stopping
frigate  | s6-rc: info: service frigate-log: stopping
frigate  | s6-rc: info: service nginx-log successfully stopped
frigate  | 2023-10-13 09:28:28.782791860  exit OK
frigate  | s6-rc: info: service frigate-log successfully stopped
frigate  | 2023-10-13 09:28:28.794877129  [INFO] The go2rtc service exited with code 0 (by signal 0)
frigate  | s6-rc: info: service go2rtc successfully stopped
frigate  | s6-rc: info: service go2rtc-log: stopping
frigate  | s6-rc: info: service go2rtc-log successfully stopped
frigate  | s6-rc: info: service log-prepare: stopping
frigate  | s6-rc: info: service s6rc-fdholder: stopping
frigate  | s6-rc: info: service log-prepare successfully stopped
frigate  | s6-rc: info: service legacy-cont-init: stopping
frigate  | s6-rc: info: service legacy-cont-init successfully stopped
frigate  | s6-rc: info: service fix-attrs: stopping
frigate  | s6-rc: info: service s6rc-fdholder successfully stopped
frigate  | s6-rc: info: service fix-attrs successfully stopped
frigate  | s6-rc: info: service s6rc-oneshot-runner: stopping
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
none
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

chinese

### Any other information that may be helpful

numpy version is:
with; **python -c "import numpy; print(numpy.__version__)"**
_Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python"
  * The NumPy version is: "1.20.0"_

my docker compose file(access to network share is working fine.)

version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb"
    devices:
      - /dev/bus/usb:/dev/bus/usb #Used for Coral if Available
      - /dev/video10 #Map the Pi hardware acceleration
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/frigate-nvr/config.yml:/config/config.yml
      - /mnt/surveillance/frigate:/media/frigate
      - type: tmpfs #Remove this if using a Pi with 2GB or Less RAM
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

**Comment by NickM-27** [comment]
this is typical when the pi is running on 32bit OS, need to update to 64bit

**Comment by boerti71** [comment]
shame on me ;-(
I thank you for your help :-)
