### ISSUE TITLE
[Config Support]: RPI4 GPUs rpi-v4l2m2m error 

### ISSUE THREAD

**Issue by HarryCover78** [blakeblackshear/frigate#8159]
### Describe the problem you are having

Hello,
I have just installed Frigate using docker-compose.

My camera tests are OK, but unfortunately the data doesn't go back to HomeAssitant.

 In System, I see :
    rpi-v4l2m2m
        There was an error getting usage stats. This does not mean hardware acceleration is not working. Either your GPU does not support this or Frigate does not have proper access to get statistics. This is expected for the Home Assistant addon.

During my tests, I noticed that the CORAL has the id 1a6e:089a when my rpi starts, frigate launches and displays the error :
ValueError: Failed to load delegate from libedgetpu.so.1.0
then restarts automatically, ending with :
[INFO] Starting go2rtc healthcheck service...
At this point, the CORAL changed its ID to 18d1:9302

I'm open to any suggestions for corrections or alternatives so that I can take full advantage of an information link between my rpi4 Frigate and my rpi hosting HA OS.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /mnt/nas

ffmpeg:
  hwaccel_args: preset-rpi-64-h264

cameras:
  Note8:
    enabled: False
    ffmpeg:
      inputs:
        - path: rtsp://viewer:camera@192.168.50.52:8080/h264_ulaw.sdp
          roles:
            - detect    
    detect:
      enabled: True
      width: 1280
      height: 720
    record:
      enabled: True
    snapshots:
      enabled: True
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
2023-10-14 00:26:47.698452579  [INFO] Preparing go2rtc config...
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-10-14 00:26:47.719022456  [INFO] Starting Frigate...
2023-10-14 00:26:47.731296902  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-10-14 00:26:48.429777277  [INFO] Starting go2rtc...
2023-10-14 00:26:48.607694325  00:26:48.607 INF go2rtc version 1.2.0 linux/arm64
2023-10-14 00:26:48.608598634  00:26:48.608 INF [api] listen addr=:1984
2023-10-14 00:26:48.609542944  00:26:48.609 INF [rtsp] listen addr=:8554
2023-10-14 00:26:48.610469420  00:26:48.610 INF [srtp] listen addr=:8443
2023-10-14 00:26:48.611427358  00:26:48.611 INF [webrtc] listen addr=:8555
2023-10-14 00:26:51.447279849  [2023-10-14 00:26:51] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-14 00:26:51.526764400  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Starting migrations
2023-10-14 00:26:51.547431394  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "001_create_events_table"
2023-10-14 00:26:51.547993799  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE TABLE IF NOT EXISTS "event" ("id" VARCHAR(30) NOT NULL PRIMARY KEY, "label" VARCHAR(20) NOT NULL, "camera" VARCHAR(20) NOT NULL, "start_time" DATETIME NOT NULL, "end_time" DATETIME NOT NULL, "top_score" REAL NOT NULL, "false_positive" INTEGER NOT NULL, "zones" JSON NOT NULL, "thumbnail" TEXT NOT NULL)',)
2023-10-14 00:26:51.549138996  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE INDEX IF NOT EXISTS "event_label" ON "event" ("label")',)
2023-10-14 00:26:51.550156953  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE INDEX IF NOT EXISTS "event_camera" ON "event" ("camera")',)
2023-10-14 00:26:51.552350681  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 001_create_events_table
2023-10-14 00:26:51.569211253  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "002_add_clip_snapshot"
2023-10-14 00:26:51.569731250  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'has_clip', <BooleanField: Event.has_clip>)
2023-10-14 00:26:51.580942150  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'has_snapshot', <BooleanField: Event.has_snapshot>)
2023-10-14 00:26:51.587296262  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 002_add_clip_snapshot2023-10-14 00:26:51.602519546  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "003_create_recordings_table"
2023-10-14 00:26:51.603049340  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE TABLE IF NOT EXISTS "recordings" ("id" VARCHAR(30) NOT NULL PRIMARY KEY, "camera" VARCHAR(20) NOT NULL, "path" VARCHAR(255) NOT NULL, "start_time" DATETIME NOT NULL, "end_time" DATETIME NOT NULL, "duration" REAL NOT NULL)',)
2023-10-14 00:26:51.604220444  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE INDEX IF NOT EXISTS "recordings_camera" ON "recordings" ("camera")',)
2023-10-14 00:26:51.605159013  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE UNIQUE INDEX IF NOT EXISTS "recordings_path" ON "recordings" ("path")',)
2023-10-14 00:26:51.606182766  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE INDEX IF NOT EXISTS "recordings_start_time_end_time" ON "recordings" (start_time, end_time)',)
2023-10-14 00:26:51.607990441  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 003_create_recordings_table
2023-10-14 00:26:51.624673532  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "004_add_bbox_region_area"
2023-10-14 00:26:51.625177326  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'region', <JSONField: Event.region>)
2023-10-14 00:26:51.631527716  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'box', <JSONField: Event.box>)
2023-10-14 00:26:51.637343979  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'area', <IntegerField: Event.area>)
2023-10-14 00:26:51.643775110  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 004_add_bbox_region_area
2023-10-14 00:26:51.660624922  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "005_make_end_time_nullable"
2023-10-14 00:26:51.661124049  [2023-10-14 00:26:51] peewee_migrate                 INFO    : drop_not_null ('event', 'end_time')
2023-10-14 00:26:51.667268125  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 005_make_end_time_nullable
2023-10-14 00:26:51.681965190  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "006_add_motion_active_objects"
2023-10-14 00:26:51.682465169  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('recordings', 'objects', <IntegerField: Recordings.objects>)
2023-10-14 00:26:51.683902068  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('recordings', 'motion', <IntegerField: Recordings.motion>)
2023-10-14 00:26:51.686033667  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 006_add_motion_active_objects
2023-10-14 00:26:51.694571304  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "007_add_retain_indefinitely"
2023-10-14 00:26:51.695073190  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'retain_indefinitely', <BooleanField: Event.retain_indefinitely>)
2023-10-14 00:26:51.702124428  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 007_add_retain_indefinitely
2023-10-14 00:26:51.716826049  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "008_add_sub_label"
2023-10-14 00:26:51.717325731  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'sub_label', <CharField: Event.sub_label>)
2023-10-14 00:26:51.719531015  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 008_add_sub_label
2023-10-14 00:26:51.727633488  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "009_add_object_filter_ratio"
2023-10-14 00:26:51.728128948  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'ratio', <FloatField: Event.ratio>)
2023-10-14 00:26:51.735188353  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 009_add_object_filter_ratio
2023-10-14 00:26:51.751705185  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "010_add_plus_image_id"
2023-10-14 00:26:51.752208757  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('event', 'plus_id', <CharField: Event.plus_id>)
2023-10-14 00:26:51.754451522  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 010_add_plus_image_id2023-10-14 00:26:51.761991072  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "011_update_indexes"
2023-10-14 00:26:51.762511254  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE INDEX "event_start_time_end_time" ON "event" ("start_time" DESC, "end_time" DESC)',)
2023-10-14 00:26:51.763661081  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('DROP INDEX recordings_start_time_end_time',)
2023-10-14 00:26:51.764608594  [2023-10-14 00:26:51] peewee_migrate                 INFO    : sql ('CREATE INDEX "recordings_end_time_start_time" ON "recordings" ("end_time" DESC, "start_time" DESC)',)
2023-10-14 00:26:51.766491435  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 011_update_indexes
2023-10-14 00:26:51.780440116  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Migrate "012_add_segment_size"
2023-10-14 00:26:51.780964298  [2023-10-14 00:26:51] peewee_migrate                 INFO    : add_column ('recordings', 'segment_size', <FloatField: Recordings.segment_size>)
2023-10-14 00:26:51.788751865  [2023-10-14 00:26:51] peewee_migrate                 INFO    : Done 012_add_segment_size
2023-10-14 00:26:51.848456398  [2023-10-14 00:26:51] frigate.app                    INFO    : Output process started: 293
2023-10-14 00:26:51.852237673  [2023-10-14 00:26:51] detector.coral                 INFO    : Starting detection process: 292
2023-10-14 00:26:51.854712937  [2023-10-14 00:26:51] frigate.app                    INFO    : Camera processor not started for disabled camera Note8
2023-10-14 00:26:51.856037115  [2023-10-14 00:26:51] frigate.app                    INFO    : Capture process not started for disabled camera Note8
2023-10-14 00:26:51.858997228  [2023-10-14 00:26:51] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-14 00:26:57.731471338  [INFO] Starting go2rtc healthcheck service...
2023-10-14 00:27:20.882951176  Process detector:coral:
2023-10-14 00:27:20.883332378  [2023-10-14 00:27:20] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-10-14 00:27:20.889969942  Traceback (most recent call last):
2023-10-14 00:27:20.890495273    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-10-14 00:27:20.890505903      delegate = Delegate(library, options)
2023-10-14 00:27:20.890838383    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-10-14 00:27:20.890847383      raise ValueError(capture.message)
2023-10-14 00:27:20.891199937  ValueError
2023-10-14 00:27:20.891553176
2023-10-14 00:27:20.891563231  During handling of the above exception, another exception occurred:
2023-10-14 00:27:20.891566657
2023-10-14 00:27:20.891867452  Traceback (most recent call last):
2023-10-14 00:27:20.892298469    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-14 00:27:20.892305395      self.run()
2023-10-14 00:27:20.892602468    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-14 00:27:20.892610116      self._target(*self._args, **self._kwargs)
2023-10-14 00:27:20.892903818    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-10-14 00:27:20.892912392      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-14 00:27:20.893207447    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-10-14 00:27:20.893215335      self.detect_api = create_detector(detector_config)
2023-10-14 00:27:20.893506908    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-10-14 00:27:20.893513908      return api(detector_config)
2023-10-14 00:27:20.893861296    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-10-14 00:27:20.893870092      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-10-14 00:27:20.894171239    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-10-14 00:27:20.894179424      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-10-14 00:27:20.894502941  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-10-14 00:27:20.894509682
2023-10-14 00:27:22.165498963  [2023-10-14 00:27:22] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-10-14 00:27:22.236882717  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-10-14 00:27:22.290755138  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
2023-10-14 00:27:22.297524961  [2023-10-14 00:27:22] frigate.app                    INFO    : Stopping...
2023-10-14 00:27:22.298704363  [2023-10-14 00:27:22] frigate.events                 INFO    : Exiting event cleanup...
2023-10-14 00:27:22.300059765  [2023-10-14 00:27:22] frigate.record                 INFO    : Exiting recording cleanup...
s6-rc: info: service nginx-log successfully stopped
2023-10-14 00:27:22.301040168  [2023-10-14 00:27:22] frigate.stats                  INFO    : Exiting stats emitter...
2023-10-14 00:27:22.301827128  [2023-10-14 00:27:22] frigate.record                 INFO    : Exiting recording maintenance...
2023-10-14 00:27:22.302457958  [2023-10-14 00:27:22] frigate.storage                INFO    : Exiting storage maintainer...
2023-10-14 00:27:22.302465588  [2023-10-14 00:27:22] frigate.watchdog               INFO    : Exiting watchdog...
2023-10-14 00:27:22.845459072  [2023-10-14 00:27:22] frigate.comms.ws               INFO    : Exiting websocket client...
2023-10-14 00:27:22.890782528  [2023-10-14 00:27:22] frigate.object_processing      INFO    : Exiting object processor...
2023-10-14 00:27:23.191893927  [2023-10-14 00:27:23] frigate.events                 INFO    : Exiting event processor...2023-10-14 00:27:23.194285028  [2023-10-14 00:27:23] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-10-14 00:27:24.987897375  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-10-14 00:27:24.996697949  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-10-14 00:27:25.008679325  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
2023-10-14 00:27:30.911746157  [INFO] Preparing go2rtc config...
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
2023-10-14 00:27:30.925756786  [INFO] Starting Frigate...
s6-rc: info: service legacy-services: starting
2023-10-14 00:27:30.933305126  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-10-14 00:27:31.602940769  [INFO] Starting go2rtc...
2023-10-14 00:27:31.780846833  00:27:31.780 INF go2rtc version 1.2.0 linux/arm64
2023-10-14 00:27:31.781789181  00:27:31.781 INF [api] listen addr=:1984
2023-10-14 00:27:31.782870473  00:27:31.782 INF [rtsp] listen addr=:8554
2023-10-14 00:27:31.783828414  00:27:31.783 INF [srtp] listen addr=:8443
2023-10-14 00:27:31.784842095  00:27:31.784 INF [webrtc] listen addr=:8555
2023-10-14 00:27:33.850005950  [2023-10-14 00:27:33] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-14 00:27:33.920542874  [2023-10-14 00:27:33] peewee_migrate                 INFO    : Starting migrations
2023-10-14 00:27:33.932505178  [2023-10-14 00:27:33] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-14 00:27:33.974427419  [2023-10-14 00:27:33] frigate.app                    INFO    : Output process started: 289
2023-10-14 00:27:33.982027240  [2023-10-14 00:27:33] frigate.app                    INFO    : Camera processor not started for disabled camera Note8
2023-10-14 00:27:33.982047574  [2023-10-14 00:27:33] frigate.app                    INFO    : Capture process not started for disabled camera Note8
2023-10-14 00:27:37.084805819  [2023-10-14 00:27:33] detector.coral                 INFO    : Starting detection process: 288
2023-10-14 00:27:37.097943731  [2023-10-14 00:27:33] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-14 00:27:37.099597298  [2023-10-14 00:27:37] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-10-14 00:27:40.929318311  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

Raspbian

### Install method

Docker

### Coral version

USB

### Any other information that may be helpful

uname -a
Linux nvrpi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

vcgencmd version
Mar 17 2023 10:50:39
Copyright (c) 2012 Broadcom
version 82f3750a65fadae9a38077e3c2e217ad158c8d54 (clean) (release) (start)

vcgencmd bootloader_version
2023/01/11 17:40:52
version 8ba17717fbcedd4c3b6d4bce7e50c7af4155cba9 (release)
timestamp 1673458852
update-time 0
capabilities 0x0000007f

vcgencmd get_mem arm
arm=768M

vcgencmd get_mem gpu
gpu=256M

v4l2-ctl -d 10 --list-formats-out
ioctl: VIDIOC_ENUM_FMT
        Type: Video Output Multiplanar

        [0]: 'H264' (H.264, compressed)
        [1]: 'MJPG' (Motion-JPEG, compressed)

vcgencmd codec_enabled H264
H264=enabled

@boot
lsusb -tv
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
    |__ Port 1: Dev 2, If 0, Class=Application Specific Interface, Driver=, 5000M
        ID 1a6e:089a Global Unichip Corp.
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        ID 2109:3431 VIA Labs, Inc. Hub

@after run Frigate
lsusb -d 18d1:9302
Bus 002 Device 003: ID 18d1:9302 Google Inc.

docker-compose.yml
     devices:
       - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions

**Comment by NickM-27** [comment]
> In System, I see :
rpi-v4l2m2m
There was an error getting usage stats. This does not mean hardware acceleration is not working. Either your GPU does not support this or Frigate does not have proper access to get statistics. This is expected for the Home Assistant addon.

the rpi does not support gpu stats so this is expected.

the coral will often take too long to initialize on the first run and when frigate restarts it is initialized correctly and things work

I don't see anything wrong here

**Comment by HarryCover78** [comment]
Thanks for your quick reply, Nick

Zut, I'm going to do without this feature.

All that's left is to connect frigate to hoas via mqtt, isn't that right?

Sorry, but I'm new to home automation.

Regards

**Comment by NickM-27** [comment]
yes https://docs.frigate.video/integrations/home-assistant

closing this as the original issue is resolved, feel free to create a new issue if something else comes up
