### ISSUE TITLE
[Detector Support]: 

### ISSUE THREAD

**Issue by zgorizzo69** [blakeblackshear/frigate#8196]
### Describe the problem you are having

frigate on unraid fail when running nvidia tensorrt with Quadro P1000

### Version

0.13.0-beta2-tensorrt

### Frigate config file

```yaml
logger:
    logs:
        frigate.detectors.plugins.tensorrt: debug

mqtt:
  host: 192.168.1.30
  user: mqtt
  password: XXXXXXXXXXXXXXXXXXXX

record:
  enabled: True
  events:
    retain:
      default: 10

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /config/trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://yolo:e2vdsvdsvsdvdsvdsXw@192.168.1.211:88/videoMain
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False       
    zones:  
      zone_garage:
        coordinates: 1241,373,1230,720,0,720,0,417,733,351  
  salon:
    ffmpeg:
      inputs:
        - path: rtsp://admin:KqD454554sdsds@192.168.1.252:554/11
          roles:
            - detect
            - rtmp
    rtmp:
      enabled: False
    zones:  
      zone_salon:
        coordinates: 1280,370,1280,720,708,720,0,720,0,87
 
ffmpeg:
  hwaccel_args: preset-nvidia-h264
 
snapshots: 
  enabled: True 
  clean_copy: True 
  timestamp: True 
  bounding_box: False 
  crop: False 
  height: 175 
  required_zones: [] 
  retain: 
    default: 5  
    objects:
      person: 15
 
detect:
  width: 1280
  height: 720
  fps: 5
  enabled: True
  max_disappeared: 25 
  stationary: 
    interval: 5 
    threshold: 50 
    max_frames: 
      default: 3000 
      objects:
        person: 1000 
objects: 
  track:
    - person 
  mask: 0,0,1000,0,1000,200,0,200 
  filters:
    person: 
      min_area: 5000 
      max_area: 100000 
      min_ratio: 0.5 
      max_ratio: 2.0 
      min_score: 0.5 threshold: 0.7 
      mask: 0,0,1000,0,1000,200,0,200
```

### docker-compose file or Docker CLI command

```yaml
docker create --name='frigate' --net='bridge' --cpuset-cpus='4,5,6,13' --privileged=true -e TZ="Europe/Paris" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Borg" -e HOST_CONTAINERNAME="frigate" -e 'FRIGATE_RTSP_PASSWORD'='XXXXX' -e 'PLUS_API_KEY'='' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:5000]' -l net.unraid.docker.icon='https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png' -p '5000:5000/tcp' -p '1935:1935/tcp' -v '/mnt/user/appdata/frigate':'/config':'rw' -v '/mnt/user/security':'/media/frigate':'rw' -v '/etc/localtime':'/etc/localtime':'rw' --runtime=nvidia --shm-size=512mb --gpus all --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 'ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt'
```

### Relevant log output

```shell
here is the error log 

s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
s6-rc: info: service go2rtc-healthcheck successfully stopped
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate successfully stopped
s6-rc: info: service trt-model-prepare: stopping
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service trt-model-prepare successfully stopped
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
2023-10-17 10:59:55.629239525  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt DEBUG   : Registered plugin creator - ::RPROI_TRT version 1
2023-10-17 10:59:55.629302186  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt DEBUG   : Registered plugin creator - ::ScatterND version 1
2023-10-17 10:59:55.629361037  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt DEBUG   : Registered plugin creator - ::SeqLen2Spatial version 1
2023-10-17 10:59:55.629421358  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt DEBUG   : Registered plugin creator - ::SpecialSlice_TRT version 1
2023-10-17 10:59:55.629479659  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt DEBUG   : Registered plugin creator - ::SplitGeLU version 1
2023-10-17 10:59:55.629532080  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt DEBUG   : Registered plugin creator - ::Split version 1
2023-10-17 10:59:55.629567840  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt DEBUG   : Registered plugin creator - ::VoxelGeneratorPlugin version 1
2023-10-17 10:59:55.659672786  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 35 MiB
2023-10-17 10:59:55.740139924  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 232, Serialized Engine Version: 213)
2023-10-17 10:59:55.747518630  [2023-10-17 10:59:55] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
2023-10-17 10:59:55.751334046  Process detector:tensorrt:
2023-10-17 10:59:55.751783913  Traceback (most recent call last):
2023-10-17 10:59:55.751797243    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-17 10:59:55.751798063      self.run()
2023-10-17 10:59:55.751798823    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-17 10:59:55.751799524      self._target(*self._args, **self._kwargs)
2023-10-17 10:59:55.751804604    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2023-10-17 10:59:55.751805344      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-17 10:59:55.751806084    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2023-10-17 10:59:55.751806784      self.detect_api = create_detector(detector_config)
2023-10-17 10:59:55.751808224    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2023-10-17 10:59:55.751810214      return api(detector_config)
2023-10-17 10:59:55.751810974    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 221, in __init__
2023-10-17 10:59:55.751823644      self.input_shape = self._get_input_shape()
2023-10-17 10:59:55.751824444    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 93, in _get_input_shape
2023-10-17 10:59:55.751840404      binding = self.engine[0]
2023-10-17 10:59:55.751846064  TypeError: 'NoneType' object is not subscriptable
2023-10-17 10:59:55.751846804  Exception ignored in: <function TensorRtDetector.__del__ at 0x15091672baf0>
2023-10-17 10:59:55.751847434  Traceback (most recent call last):
2023-10-17 10:59:55.751848184    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__
2023-10-17 10:59:55.751903585      if self.outputs is not None:
2023-10-17 10:59:55.751908465  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2023-10-17 10:59:59.772725358  172.17.0.1 - - [17/Oct/2023:10:59:59 +0200] "GET /api/stats HTTP/1.1" 200 7400 "-" "HomeAssistant/2023.10.3 aiohttp/3.8.5 Python/3.11" "-"
2023-10-17 11:00:04.257569388  [INFO] Starting go2rtc healthcheck service...
2023-10-17 11:00:04.753557383  172.17.0.1 - - [17/Oct/2023:11:00:04 +0200] "GET /api/stats HTTP/1.1" 200 7414 "-" "HomeAssistant/2023.10.3 aiohttp/3.8.5 Python/3.11" "-"
2023-10-17 11:00:09.752128995  172.17.0.1 - - [17/Oct/2023:11:00:09 +0200] "GET /api/stats HTTP/1.1" 200 7398 "-" "HomeAssistant/2023.10.3 aiohttp/3.8.5 Python/3.11" "-"
2023-10-17 11:00:14.756945066  172.17.0.1 - - [17/Oct/2023:11:00:14 +0200] "GET /api/stats HTTP/1.1" 200 7398 "-" "HomeAssistant/2023.10.3 aiohttp/3.8.5 Python/3.11" "-"
2023-10-17 11:00:15.467066099  [2023-10-17 11:00:15] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
2023-10-17 11:00:15.478741610  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2023-10-17 11:00:15.519908935  [INFO] Service NGINX exited with code 0 (by signal 0)
2023-10-17 11:00:15.521401010  [2023-10-17 11:00:15] frigate.app                    INFO    : Stopping...
2023-10-17 11:00:15.521672085  [2023-10-17 11:00:15] frigate.record.cleanup         INFO    : Exiting recording cleanup...
2023-10-17 11:00:15.522447518  [2023-10-17 11:00:15] frigate.stats                  INFO    : Exiting stats emitter...
2023-10-17 11:00:15.522767714  [2023-10-17 11:00:15] frigate.events.cleanup         INFO    : Exiting event cleanup...
2023-10-17 11:00:15.523928274  [2023-10-17 11:00:15] frigate.watchdog               INFO    : Exiting watchdog...
2023-10-17 11:00:15.523930584  [2023-10-17 11:00:15] frigate.ptz.autotrack          INFO    : Exiting autotracker...
2023-10-17 11:00:15.523931564  [2023-10-17 11:00:15] frigate.storage                INFO    : Exiting storage maintainer...
2023-10-17 11:00:15.524431092  [2023-10-17 11:00:15] frigate.object_processing      INFO    : Exiting object processor...
2023-10-17 11:00:15.612643223  [2023-10-17 11:00:15] frigate.events.maintainer      INFO    : Exiting event processor...
2023-10-17 11:00:15.799412902  [2023-10-17 11:00:15] frigate.comms.ws               INFO    : Exiting websocket client...
2023-10-17 11:00:16.282252753  [2023-10-17 11:00:16] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-10-17 11:00:16.481312552  [2023-10-17 11:00:16] watchdog.salon                 INFO    : Terminating the existing ffmpeg process...
2023-10-17 11:00:16.481406764  [2023-10-17 11:00:16] watchdog.garage                INFO    : Terminating the existing ffmpeg process...
2023-10-17 11:00:16.481467865  [2023-10-17 11:00:16] watchdog.garage                INFO    : Waiting for ffmpeg to exit gracefully...
2023-10-17 11:00:16.481532736  [2023-10-17 11:00:16] watchdog.salon                 INFO    : Waiting for ffmpeg to exit gracefully...
2023-10-17 11:00:16.482430191  [2023-10-17 11:00:16] frigate.record.maintainer      INFO    : Exiting recording maintenance...
2023-10-17 11:00:16.879576794  [2023-10-17 11:00:16] frigate.output                 INFO    : exiting output process...
2023-10-17 11:00:20.943259579  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked shared_memory objects to clean up at shutdown
2023-10-17 11:00:20.943262829    warnings.warn('resource_tracker: There appear to be %d '
2023-10-17 11:00:20.945811523  [INFO] Service Frigate exited with code 0 (by signal 0)
2023-10-17 11:00:20.947693795  exit with signal: terminated
2023-10-17 11:00:20.951436059  [INFO] The go2rtc service exited with code 0 (by signal 0)
```

```
nvidia-smi
Tue Oct 17 11:02:25 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro P1000                   Off | 00000000:2D:00.0 Off |                  N/A |
| 24%   41C    P0              N/A /  N/A |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

```
nvidia-container-runtime-hook --version
NVIDIA Container Runtime Hook version 1.14.1
commit: 6094effd58d88becdfb7900ef5df7fa274686620
```
```


### Operating system

UNRAID

### Install method

Docker CLI

### Coral version

USB

### Any other information that may be helpful

tensor models where generated (twice ..) on the same computer as decribed in the documentation 

it is working fine with OpenVINO basic config as decribed here https://docs.frigate.video/configuration/detectors#openvino-detector

```
2023-10-17 11:15:37.595951956  [INFO] Preparing Frigate...
2023-10-17 11:15:37.598165484  [INFO] Starting NGINX...
2023-10-17 11:15:37.600162798  [INFO] Preparing go2rtc config...
2023-10-17 11:15:37.617617120  [INFO] Starting Frigate...
2023-10-17 11:15:37.772427090  [INFO] Starting go2rtc...
2023-10-17 11:15:37.843202761  11:15:37.843 INF go2rtc version 1.7.1 linux/amd64
2023-10-17 11:15:37.843393824  11:15:37.843 INF [api] listen addr=0.0.0.0:1984
2023-10-17 11:15:37.843567127  11:15:37.843 INF [rtsp] listen addr=0.0.0.0:8554
2023-10-17 11:15:37.843689299  11:15:37.843 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-10-17 11:15:38.475905035  [2023-10-17 11:15:38] frigate.app                    INFO    : Starting Frigate (0.13.0-0858859)
2023-10-17 11:15:38.496477720  [2023-10-17 11:15:38] frigate.config                 WARNING : Customizing more than a detector model path is unsupported.
2023-10-17 11:15:38.503262817  [2023-10-17 11:15:38] peewee_migrate.logs            INFO    : Starting migrations
2023-10-17 11:15:38.512769701  [2023-10-17 11:15:38] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-10-17 11:15:38.518991798  [2023-10-17 11:15:38] frigate.app                    INFO    : Recording process started: 699
2023-10-17 11:15:38.520313421  [2023-10-17 11:15:38] frigate.app                    INFO    : go2rtc process pid: 97
2023-10-17 11:15:38.537901364  [2023-10-17 11:15:38] detector.ov                    INFO    : Starting detection process: 709
2023-10-17 11:15:38.552436545  [2023-10-17 11:15:38] frigate.app                    INFO    : Output process started: 711
2023-10-17 11:15:38.553517364  [2023-10-17 11:15:38] frigate.app                    INFO    : Camera processor started for garage: 716
2023-10-17 11:15:38.554063703  [2023-10-17 11:15:38] frigate.app                    INFO    : Camera processor started for salon: 718
2023-10-17 11:15:38.565629143  [2023-10-17 11:15:38] frigate.app                    INFO    : Capture process started for garage: 719
2023-10-17 11:15:38.565633923  [2023-10-17 11:15:38] frigate.app                    INFO    : Capture process started for salon: 724
2023-10-17 11:15:38.956694349  [2023-10-17 11:15:38] frigate.detectors.plugins.openvino INFO    : Model Input Shape: [1,300,300,3]
2023-10-17 11:15:38.956739359  [2023-10-17 11:15:38] frigate.detectors.plugins.openvino INFO    : Model Output-0 Shape: [1,1,100,7]
2023-10-17 11:15:38.956776490  [2023-10-17 11:15:38] frigate.detectors.plugins.openvino INFO    : Model has 1 Output Tensors
2023-10-17 11:15:40.025241591  172.17.0.1 - - [17/Oct/2023:11:15:40 +0200] "GET /api/stats HTTP/1.1" 200 7409 "-" "HomeAssistant/2023.10.3 ai
```

**Comment by NickM-27** [comment]
Your model path is incorrect `config/trt-models/yolov7-tiny-416.trt`

Please see the docs https://deploy-preview-6262--frigate-docs.netlify.app/configuration/object_detectors#generate-models

**Comment by zgorizzo69** [comment]
`config/cache/trt-models/yolov7-320.trt`  indeed works 
although I can't use the other previously generated models like yolo7-tiny-416 
I tried copy pasting the models inside the cache folder and added the `YOLO_MODELS` env

**Comment by NickM-27** [comment]
Yes that is expected, the models have changed and are no longer compatible. This is covered in the release notes. 

Feel free to create a new issue if something else comes up.
