### ISSUE TITLE
TensorRT Models not working[Detector Support]: 

### ISSUE THREAD

**Issue by PingboyZA** [blakeblackshear/frigate#8228]
### Describe the problem you are having

Good morning everyone, if you saw my other support post i recently started a very basic deployment of Frigate, and after some self imposed stupidity its now up and running with HW acceleration etc. The next step was for me to use my GPU as a detector. The GPU is obviously pulling through into the docker container as it shows up on the config page, I have followed the guide, created the trt-models passed through the directory to the docker but Frigate is throwing all kinds of errors to me that i just don't follow. I believe i have done everything correctly but i am pretty sure that i have missed something, any help would be greatly appreciated. Thank you in advance.

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: False

ffmpeg:
  hwaccel_args: preset-nvidia-h264

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

go2rtc:
  streams:
    Backyard:
      - rtsp://admin:FGNSOX@192.168.31.234:554/H.264
    Driveway:
      - rtsp://admin:ZLQGOY@192.168.31.21:554/H.264

cameras:
  Backyard:
    ffmpeg:
      inputs:
        - path: rtsp://admin:FGNSOX@192.168.31.234:554/H.264
          roles:
            - detect
            - record
            - rtmp

    detect:
      width: 1280
      height: 720
    snapshots:
      enabled: True
    record:
      enabled: True
      retain:
        days: 5
      events:
        retain:
          default: 10
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "64mb" # update for your cameras based on calculation above
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/config.yml:/config/config.yml
      - /mnt/cctvclips:/media/frigate
      - /mnt/trt-models:/trt-models/	
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "Frigate!001"
```

### Relevant log output

```shell
2023-10-19 07:28:48.498867045  [INFO] Starting Frigate...
2023-10-19 07:28:49.282649099  [2023-10-19 07:28:49] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-19 07:28:49.298079874  [2023-10-19 07:28:49] peewee_migrate                 INFO    : Starting migrations
2023-10-19 07:28:49.302281863  [2023-10-19 07:28:49] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-19 07:28:49.317992784  [2023-10-19 07:28:49] detector.tensorrt              INFO    : Starting detection process: 1212
2023-10-19 07:28:49.318720108  Process detector:tensorrt:
2023-10-19 07:28:49.319590720  Traceback (most recent call last):
2023-10-19 07:28:49.319637178    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-19 07:28:49.319638450      self.run()
2023-10-19 07:28:49.319663236    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-19 07:28:49.319664318      self._target(*self._args, **self._kwargs)
2023-10-19 07:28:49.319681871    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-10-19 07:28:49.319682833      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-19 07:28:49.319700727    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-10-19 07:28:49.319701678      self.detect_api = create_detector(detector_config)
2023-10-19 07:28:49.319718149    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-10-19 07:28:49.319718971      return api(detector_config)
2023-10-19 07:28:49.319734650    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 198, in __init__
2023-10-19 07:28:49.319735402      assert (
2023-10-19 07:28:49.319762182  AssertionError: TensorRT libraries not found, tensorrt detector not present
2023-10-19 07:28:49.319846330  Exception ignored in: <function TensorRtDetector.__del__ at 0x7fc1e461b550>
2023-10-19 07:28:49.319865325  Traceback (most recent call last):
2023-10-19 07:28:49.319882017    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2023-10-19 07:28:49.320043840      if self.outputs is not None:
2023-10-19 07:28:49.320089646  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2023-10-19 07:28:49.326358050  [2023-10-19 07:28:49] frigate.app                    INFO    : Output process started: 1214
2023-10-19 07:28:49.327303694  [2023-10-19 07:28:49] frigate.app                    INFO    : Camera processor started for Backyard: 1217
2023-10-19 07:28:49.333076288  [2023-10-19 07:28:49] frigate.app                    INFO    : Capture process started for Backyard: 1219
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by blakeblackshear** [comment]
You have to use the tensorrt variant of the image. The `stable` tag doesnt support using a GPU for detection.

**Comment by PingboyZA** [comment]
great thank you let me try that

**Comment by PingboyZA** [comment]
ok i removed my current docker, updaed my compose file 

from ->     image: ghcr.io/blakeblackshear/frigate:stable
to ->     image: ghcr.io/blakeblackshear/frigate:tensorrt

but now it wont even create the container, getting a manifest unknow error.

**Comment by NickM-27** [comment]
the correct tag is `ghcr.io/blakeblackshear/frigate:stable-tensorrt`

this is covered in the docs https://docs.frigate.video/configuration/detectors#nvidia-tensorrt-detector

**Comment by PingboyZA** [comment]
I am truly sorry for missing it! Thanks for the help. Will go ahead and close.

**Comment by NickM-27** [comment]
feel free to wait until you confirm it is working

**Comment by PingboyZA** [comment]
you are a absolute legend! Thank you lets go ahead and  close this.
