### ISSUE TITLE
[Detector Support]: usb coral - frigate stops - No EdgeTPU was detected

### ISSUE THREAD

**Issue by renaatdb** [blakeblackshear/frigate#8233]
### Describe the problem you are having

Frigate always stops.
No EdgeTPU was detected...
![fr1](https://github.com/blakeblackshear/frigate/assets/5012211/0f044f50-da6b-41ba-924e-c93b2c53a2c7)
![fr2](https://github.com/blakeblackshear/frigate/assets/5012211/5b0e76ae-7c31-4365-90e2-400b91b6af30)
![fr4](https://github.com/blakeblackshear/frigate/assets/5012211/76c6d96b-541c-4ce9-b432-40185d525dc4)
![fr6](https://github.com/blakeblackshear/frigate/assets/5012211/0257ba8a-fdf2-4ecc-a0ee-203b366e71b3)

### Version

Frigate (Full Access) Current version: 0.12.1

### Frigate config file

```yaml
host: core-mosquitto
  user: MQTT-user
  password: xxx

detectors:
  coral:
    type: edgetpu
    device: usb
    
cameras:
  Oprit:
    ffmpeg:
      inputs:
        - path: rtsp://root:xxxxxxN@192.168.1.151:554/axis-media/media.amp
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - truck
        - bicycle
        - motorcycle
        - dog
        - cat
```

### docker-compose file or Docker CLI command

```yaml
N/A
```

### Relevant log output

```shell
2023-10-19 10:56:23.546074748  [INFO] Starting Frigate...
2023-10-19 10:56:25.392002956  [2023-10-19 12:56:25] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-19 10:56:25.401573807  [2023-10-19 12:56:25] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-10-19 10:56:25.401577210  [2023-10-19 12:56:25] peewee_migrate                 INFO    : Starting migrations
2023-10-19 10:56:25.413039973  [2023-10-19 12:56:25] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-19 10:56:25.458111667  [2023-10-19 12:56:25] frigate.app                    INFO    : Output process started: 228
2023-10-19 10:56:25.463381257  [2023-10-19 12:56:25] detector.coral                 INFO    : Starting detection process: 227
2023-10-19 10:56:25.483512771  [2023-10-19 12:56:25] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-19 10:56:25.521767736  [2023-10-19 12:56:25] frigate.app                    INFO    : Camera processor started for Oprit: 231
2023-10-19 10:56:25.552250316  Process detector:coral:
2023-10-19 10:56:25.552257364  [2023-10-19 12:56:25] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-10-19 10:56:25.556927742  Traceback (most recent call last):
2023-10-19 10:56:25.556931659    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-10-19 10:56:25.556933192      delegate = Delegate(library, options)
2023-10-19 10:56:25.556934824    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-10-19 10:56:25.556938949      raise ValueError(capture.message)
2023-10-19 10:56:25.556957662  ValueError
2023-10-19 10:56:25.556959047  
2023-10-19 10:56:25.556960724  During handling of the above exception, another exception occurred:
2023-10-19 10:56:25.556962442  
2023-10-19 10:56:25.556963723  Traceback (most recent call last):
2023-10-19 10:56:25.556965280    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-19 10:56:25.556966494      self.run()
2023-10-19 10:56:25.556967865    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-19 10:56:25.556989370      self._target(*self._args, **self._kwargs)
2023-10-19 10:56:25.556990899    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-10-19 10:56:25.556992891      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-19 10:56:25.556994241    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-10-19 10:56:25.557009816      self.detect_api = create_detector(detector_config)
2023-10-19 10:56:25.557011355    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-10-19 10:56:25.557012691      return api(detector_config)
2023-10-19 10:56:25.557014138    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-10-19 10:56:25.557015517      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-10-19 10:56:25.557030506    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-10-19 10:56:25.557032000      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-10-19 10:56:25.557033303  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-10-19 10:56:25.557034485  
2023-10-19 10:56:25.588009734  [2023-10-19 12:56:25] frigate.app                    INFO    : Capture process started for Oprit: 240
```

### Operating system

Windows

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
which addon are you running?

**Comment by renaatdb** [comment]
> which addon are you running?

Sorry don't understand

**Comment by NickM-27** [comment]
in the above field you entered that you are running frigate as an addon. If this is not the case, please describe how you are running frigate

**Comment by NickM-27** [comment]
in this case it is most likely an issue with passing the USB device to the virtual machine. Windows is generally not recommended due to issues like these

**Comment by renaatdb** [comment]
Whaw .... this was the solution
many thanks

2023-10-20 12:09:19.185802370  [INFO] Starting Frigate...
2023-10-20 12:09:23.772730591  [2023-10-20 14:09:23] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-20 12:09:23.808953859  [2023-10-20 14:09:23] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-10-20 12:09:23.808957530  [2023-10-20 14:09:23] peewee_migrate                 INFO    : Starting migrations
2023-10-20 12:09:23.822422892  [2023-10-20 14:09:23] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-20 12:09:23.863270566  [2023-10-20 14:09:23] frigate.app                    INFO    : Output process started: 228
2023-10-20 12:09:23.887595505  [2023-10-20 14:09:23] frigate.app                    INFO    : Camera processor started for Oprit: 233
2023-10-20 12:09:23.931094669  [2023-10-20 14:09:23] frigate.app                    INFO    : Capture process started for Oprit: 235
2023-10-20 12:09:23.952732386  [2023-10-20 14:09:23] detector.coral                 INFO    : Starting detection process: 227
2023-10-20 12:09:23.952736025  [2023-10-20 14:09:23] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-20 12:09:28.681791818  [2023-10-20 14:09:28] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found

Regards
Renaatdb

**Comment by NickM-27** [comment]
Glad it is working, feel free to create a new issue if something else comes up
