### ISSUE TITLE
[Detector Support]: 0.13.0-beta2 Jetpack4-TensorRT fails running TRT model

### ISSUE THREAD

**Issue by klutzzykitty** [blakeblackshear/frigate#8246]
### Describe the problem you are having

Started Using the new `0.13.- beta2 jetpack4` docker image on Jetson nano 4GB (Jetpack 4.6.4) and the model conversion runs successfully, however the below exception occurs soon as CUDA tries to allocate memory to run model. 

```
2023-10-11 16:22:06.686812282  [2023-10-11 16:22:04] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +548, now: CPU 0, GPU 642 (MiB)

2023-10-11 16:22:06.686823220  [2023-10-11 16:22:06] frigate.detectors.plugins.tensorrt ERROR   : can't convert negative value to size_t

2023-10-11 16:22:06.686825772  Process detector:tensorrt:

2023-10-11 16:22:06.933594074  Traceback (most recent call last):

2023-10-11 16:22:06.933603293    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 229, in __init__

2023-10-11 16:22:06.933606054      ) = self._allocate_buffers()

2023-10-11 16:22:06.933657722    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 131, in _allocate_buffers

2023-10-11 16:22:06.933662357      err, host_mem = cuda.cuMemHostAlloc(

2023-10-11 16:22:06.933665326    File "cuda/cuda.pyx", line 14069, in cuda.cuda.cuMemHostAlloc

2023-10-11 16:22:06.933668034  OverflowError: can't convert negative value to size_t

2023-10-11 16:22:06.933688139  

2023-10-11 16:22:06.933691941  The above exception was the direct cause of the following exception:

2023-10-11 16:22:06.933693451  

2023-10-11 16:22:06.933695691  Traceback (most recent call last):

2023-10-11 16:22:06.933800849    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap

2023-10-11 16:22:06.933805641      self.run()

2023-10-11 16:22:06.933808766    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run

2023-10-11 16:22:06.933811214      self._target(*self._args, **self._kwargs)

2023-10-11 16:22:06.933814339    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector

2023-10-11 16:22:06.933817412      object_detector = LocalObjectDetector(detector_config=detector_config)

2023-10-11 16:22:06.933826944    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__

2023-10-11 16:22:06.933854340      self.detect_api = create_detector(detector_config)

2023-10-11 16:22:06.933858976    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector

2023-10-11 16:22:06.933861684      return api(detector_config)

2023-10-11 16:22:06.933866424    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 232, in __init__

2023-10-11 16:22:06.933898299      raise RuntimeError("fail to allocate CUDA resources") from e

2023-10-11 16:22:06.933930331  RuntimeError: fail to allocate CUDA resources

2023-10-11 16:22:06.934761598  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f584f9160>

2023-10-11 16:22:06.934768057  Traceback (most recent call last):

2023-10-11 16:22:06.934771442    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__

2023-10-11 16:22:06.934773630      if self.outputs is not None:

2023-10-11 16:22:06.934776651  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'

2023-10-11 16:22:16.252590429  [2023-10-11 16:22:16] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...

s6-rc: info: service legacy-services: stopping

s6-rc: info: service legacy-services successfully stopped

s6-rc: info: service nginx: stopping

s6-rc: info: service go2rtc-healthcheck: stopping
```

Was using `ghcr.io/blakeblackshear/frigate   dev-5658e5a-tensorrt-jp4 `  previously and it was working fine. 

Trying to run yolov7-640. Tried yolov7-320 and yolov4 as well and it's the same issue. 

### Version

0.13.0-beta2-tensorrt-jp4

### Frigate config file

```yaml
mqtt:
  host: xxxx
  user: xxxx
  password: xxxx
#  topic_prefix: frigate





detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov7-640.trt
  input_tensor: nchw
  width: 640
  height: 640
  input_pixel_format: rgb
  




record: 
  enabled: True
#  retain_days: 5
  events: 
    retain: 
      default: 14


snapshots: 
  enabled: True
  bounding_box: True
  crop: false
  retain: 
    default: 14




birdseye: 
  enabled: True
  width: 640
  height: 480
  mode: objects



cameras:
  BackYardCam:
    ffmpeg:
      hwaccel_args: preset-jetson-h264
      inputs:
        
        - path: rtsp://xxxx:xxxx@xxxx:554/cam/realmonitor?channel=1&subtype=0
          input_args: -re -stream_loop -1 -fflags +genpts
          roles:
            - record
            - detect
#            - record

    detect:
      width: 640
      height: 480
      fps: 6


    objects:
      track:
        - person
        - car
        - dog
        - cat
```

### docker-compose file or Docker CLI command

```yaml
version: '3'


  
services:  
####################### Mosquitto ############################

  mqtt:
    container_name: gpu_jetson_mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - /home/mosquitto/config:/mosquitto/config
      - /home/mosquitto/data:/mosquitto/data
      - /home/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

######################## jetson #################################

  jetson_frig: 
    container_name: jetson_latest_frig
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt-jp4
    privileged: true
    restart: unless-stopped
    volumes: 
      - /etc/localtime:/etc/localtime
      - /home/config/config.yml:/config/config.yml
      - /home/jetson_frig/content:/media/frigate
#     - /home/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 500000000
    ports:
      - 5000:5000
      - 18554:8554 # RTSP feeds
      - 18555:8555/tcp # WebRTC over tcp
      - 18555:8555/udp # WebRTC over udp

    runtime: nvidia
    environment:
      YOLO_MODELS: yolov7-640
```

### Relevant log output

```shell
2023-10-11 16:22:06.686812282  [2023-10-11 16:22:04] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +548, now: CPU 0, GPU 642 (MiB)

2023-10-11 16:22:06.686823220  [2023-10-11 16:22:06] frigate.detectors.plugins.tensorrt ERROR   : can't convert negative value to size_t

2023-10-11 16:22:06.686825772  Process detector:tensorrt:

2023-10-11 16:22:06.933594074  Traceback (most recent call last):

2023-10-11 16:22:06.933603293    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 229, in __init__

2023-10-11 16:22:06.933606054      ) = self._allocate_buffers()

2023-10-11 16:22:06.933657722    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 131, in _allocate_buffers

2023-10-11 16:22:06.933662357      err, host_mem = cuda.cuMemHostAlloc(

2023-10-11 16:22:06.933665326    File "cuda/cuda.pyx", line 14069, in cuda.cuda.cuMemHostAlloc

2023-10-11 16:22:06.933668034  OverflowError: can't convert negative value to size_t

2023-10-11 16:22:06.933688139  

2023-10-11 16:22:06.933691941  The above exception was the direct cause of the following exception:

2023-10-11 16:22:06.933693451  

2023-10-11 16:22:06.933695691  Traceback (most recent call last):

2023-10-11 16:22:06.933800849    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap

2023-10-11 16:22:06.933805641      self.run()

2023-10-11 16:22:06.933808766    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run

2023-10-11 16:22:06.933811214      self._target(*self._args, **self._kwargs)

2023-10-11 16:22:06.933814339    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector

2023-10-11 16:22:06.933817412      object_detector = LocalObjectDetector(detector_config=detector_config)

2023-10-11 16:22:06.933826944    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__

2023-10-11 16:22:06.933854340      self.detect_api = create_detector(detector_config)

2023-10-11 16:22:06.933858976    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector

2023-10-11 16:22:06.933861684      return api(detector_config)

2023-10-11 16:22:06.933866424    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 232, in __init__

2023-10-11 16:22:06.933898299      raise RuntimeError("fail to allocate CUDA resources") from e

2023-10-11 16:22:06.933930331  RuntimeError: fail to allocate CUDA resources

2023-10-11 16:22:06.934761598  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f584f9160>

2023-10-11 16:22:06.934768057  Traceback (most recent call last):

2023-10-11 16:22:06.934771442    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__

2023-10-11 16:22:06.934773630      if self.outputs is not None:

2023-10-11 16:22:06.934776651  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'

2023-10-11 16:22:16.252590429  [2023-10-11 16:22:16] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...

s6-rc: info: service legacy-services: stopping

s6-rc: info: service legacy-services successfully stopped

s6-rc: info: service nginx: stopping

s6-rc: info: service go2rtc-healthcheck: stopping

2023-10-11 16:22:16.709580650  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

Models get converted fine as its appearing in the log and after capture process beings, this issue appears. 
Previously used `ghcr.io/blakeblackshear/frigate:dev-5658e5a-tensorrt-jp4` (the latest one before the release of 0.13 beta 2) and everything worked fine. 

Is there something I've missed for Beta 2? I've followed the docs as I had it working in the `dev-5658e5a` image. 
Thank you  : ) 

Other info: 
Jetpack : 4.6.4
Cuda: 10.2.300
Cudnn: 8.2.1.32
Tensorrt: 8.2.1.8

**Comment by NickM-27** [comment]
CC @madsciencetist

**Comment by NickM-27** [comment]
beta1 came out after that commit, does it work? More specifically pinning down which commit is causing the issue may make it easier to figure out the problem

**Comment by NickM-27** [comment]
Wanted to note that a user with -jp4 said beta3 was working as expected for them https://github.com/blakeblackshear/frigate/issues/8491#issuecomment-1795478787

maybe this is a host config difference?

**Comment by madsciencetist** [comment]
Unfortunately I no longer have any nvidia hardware and can't be of much help ☹️

**Comment by vajonam** [comment]
I can speak re : `-tensorrt`  image. This was working with beta3, I have it running on this commit. `0.13.0-159FB51` which is post beta3

**Comment by klutzzykitty** [comment]
> beta1 came out after that commit, does it work? More specifically pinning down which commit is causing the issue may make it easier to figure out the problem

Hi @NickM-27 . Was offline for a while.
Clarifications: 
Yeah that version and previous ones before `ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt-jp4` worked fine.

Unable to get the commit info, but I hope this helps. 
Here's a link to where the image is present: https://github.com/blakeblackshear/frigate/pkgs/container/frigate/versions?filters%5Bversion_type%5D=tagged&page=11

![commit](https://github.com/blakeblackshear/frigate/assets/118447577/2084944b-154e-46d4-ab98-0266ade6ed9b)


Here's what I've used before on jetson:
```
history| grep "docker pull"
 1997  docker pull ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt-jp4
 1925  docker pull ghcr.io/blakeblackshear/frigate:dev-0858859-tensorrt-jp4
 1871  docker pull ghcr.io/blakeblackshear/frigate:dev-cfd04d1-tensorrt-jp4
 1799  docker pull ghcr.io/blakeblackshear/frigate:dev-5658e5a-tensorrt-jp4
```
0.13.0-beta2  and later versions is coming up with that error.  Including `dev-0858859-tensorrt-jp4`
Versions before this worked. 

Haven't changed anything on the host config file.

**Comment by the-master-r** [comment]
> > beta1 came out after that commit, does it work? More specifically pinning down which commit is causing the issue may make it easier to figure out the problem
> 
> Hi @NickM-27 . Was offline for a while. Clarifications: Yeah that version and previous ones before `ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt-jp4` worked fine.
> 
> Unable to get the commit info, but I hope this helps. Here's a link to where the image is present: https://github.com/blakeblackshear/frigate/pkgs/container/frigate/versions?filters%5Bversion_type%5D=tagged&page=11
> 
> ![commit](https://private-user-images.githubusercontent.com/118447577/282015878-2084944b-154e-46d4-ab98-0266ade6ed9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzg2MzIsIm5iZiI6MTcwNDEzODMzMiwicGF0aCI6Ii8xMTg0NDc1NzcvMjgyMDE1ODc4LTIwODQ5NDRiLTE1NGUtNDZkNC1hYjk4LTAyNjZhZGU2ZWQ5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxOTQ1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTQyZTAyMzM0MDU0MjY5YTRiMzA5YmE3MDhlNmMxZTI0ZGRmM2YyNWJkMGI4ZTA2NzlhYTg2ODA5NGE3ZmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TdE8eKyMNDxgWvPDim3jPaZz_yZa7n-s4xfoJJkMnME)
> 
> Here's what I've used before on jetson:
> 
> ```
> history| grep "docker pull"
>  1997  docker pull ghcr.io/blakeblackshear/frigate:0.13.0-beta2-tensorrt-jp4
>  1925  docker pull ghcr.io/blakeblackshear/frigate:dev-0858859-tensorrt-jp4
>  1871  docker pull ghcr.io/blakeblackshear/frigate:dev-cfd04d1-tensorrt-jp4
>  1799  docker pull ghcr.io/blakeblackshear/frigate:dev-5658e5a-tensorrt-jp4
> ```
> 
> 0.13.0-beta2 and later versions is coming up with that error. Including `dev-0858859-tensorrt-jp4` Same issues with `beta 3 and 4.` Versions before this worked.
> 
> Haven't changed anything on the host config file.

0858859 is working fine for me on a jetson nano 4G im however running 
yolov7-tiny-416.trt not the full size model reason: not enough ram 

i disabled the gui (jetpack operating system) 
and im now running at 2.9G ram used out of 3.9G 

im even using a h256 camera 
and running home assistant in a container next to it (noting running in home assitant yet though)
