### ISSUE TITLE
Edge TPU not being detected. 

### ISSUE THREAD

**Issue by bturrie** [blakeblackshear/frigate#8262]
### Describe the problem you are having

My Edge TPU is not being detected or so it seems. I am running this as a HA addon. I'm using HA version 2023.01.3 generic running natively on an x86-64 in an intel machine . I'm using the Full Access Addon and Protection is disabled.  This was working well on an old AMD laptop but the CPU load was quite high without recording turned on. That's why I moved Frigate with the frigate.yaml from the laptop to HA on a more powerful intel system. The new system is using the same powered usb and Edge TPU as I had used on the laptop. I tried multiple reboots of the new system to no effect.

### Version

 Full Access version 0.12.1

### Frigate config file

```yaml
mqtt:
  enabled: True
  host: 192.168.1.18
#  port: 1883
  user: homeassistant
  password: eepeeSh4Fei6taish0ichaa8yooyoo1Xai9quaeCh2eequoh8rahBo7ahpohshiy
  topic_prefix: frigate
  
detectors:
  coral:
    type: edgetpu
    device: usb
      
#logger:
#  default: info
#  logs:
#   frigate_event: debug
   

    
cameras:
  living:
    ffmpeg:
      inputs:
        - path: rtsp://admin:bdt100799969@192.168.1.168:554/h264Preview_01_main # <-- living
          roles:
            - detect
#            - record
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 10
        threshold: 50
    objects:
      track:
        - person
    record:
      enabled: false
#      retain:
#        days: 2
    snapshots:
      enabled: True
      retain: 
        default: 2
    motion:
      threshold: 25


  den:
    ffmpeg:
      inputs:
        - path: rtsp://admin:bbj4f6wa@192.168.1.157:554/h264Preview_01_main # <-- living
          roles:
            - detect
#            - record
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 10
        threshold: 50
    objects:
      track:
        - person
    record:
      enabled: false
#      retain:
#        days: 2
    snapshots:
      enabled: True
      retain: 
        default: 2
    motion:
      threshold: 25

  office:
    ffmpeg:
      inputs:
        - path: rtsp://admin:bbj4f6wa@192.168.1.194:554/h264Preview_01_main # <-- living
          roles:
            - detect
#            - record
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 10
        threshold: 50
    objects:
      track:
        - person
    record:
      enabled: False
#      retain:
#        days: 2
    snapshots:
      enabled: True
      retain: 
        default: 2
    motion:
      threshold: 25


  sunroom:
    ffmpeg:
      inputs:
        - path: rtsp://admin:bdt100799969@192.168.1.135:554/h264Preview_01_main # <-- living
          roles:
            - detect
#            - record
    detect:
      enabled: True
      width: 640
      height: 360
      fps: 5
      stationary:
        interval: 10
        threshold: 50
    objects:
      track:
        - person
    record:
      enabled: false
#      retain:
#        days: 2
    snapshots:
      enabled: True
      retain: 
        default: 2
    motion:
      threshold: 25



#go2rtc:
#  streams:
#    den:
#      - rtsp://admin:bbj4f6wa@192.168.1.157:554/h264Preview_01_main
```

### Relevant log output

```shell
2023-10-21 13:37:38.903367176  [INFO] Starting Frigate...
2023-10-21 13:37:39.955110463  [2023-10-21 08:37:39] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-21 13:37:39.979121522  [2023-10-21 08:37:39] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-10-21 13:37:39.980771303  [2023-10-21 08:37:39] peewee_migrate                 INFO    : Starting migrations
2023-10-21 13:37:39.984370668  [2023-10-21 08:37:39] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-21 13:37:39.996303072  [2023-10-21 08:37:39] detector.coral                 INFO    : Starting detection process: 299
2023-10-21 13:37:40.014561418  Process detector:coral:
2023-10-21 13:37:40.014566896  Traceback (most recent call last):
2023-10-21 13:37:40.014569147    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-10-21 13:37:40.014574574      delegate = Delegate(library, options)
2023-10-21 13:37:40.014577352    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-10-21 13:37:40.014593855      raise ValueError(capture.message)
2023-10-21 13:37:40.014595724  ValueError
2023-10-21 13:37:40.014597092  
2023-10-21 13:37:40.014599450  During handling of the above exception, another exception occurred:
2023-10-21 13:37:40.014600839  
2023-10-21 13:37:40.014602388  Traceback (most recent call last):
2023-10-21 13:37:40.014604140    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-21 13:37:40.014625977      self.run()
2023-10-21 13:37:40.014628083    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-21 13:37:40.014630050      self._target(*self._args, **self._kwargs)
2023-10-21 13:37:40.014631842    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-10-21 13:37:40.014646771      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-21 13:37:40.014648734    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-10-21 13:37:40.014650569      self.detect_api = create_detector(detector_config)
2023-10-21 13:37:40.014652366    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-10-21 13:37:40.014653987      return api(detector_config)
2023-10-21 13:37:40.014655671    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-10-21 13:37:40.014657324      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-10-21 13:37:40.014670851    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-10-21 13:37:40.014672879      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-10-21 13:37:40.014674590  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-10-21 13:37:40.014675992  
2023-10-21 13:37:40.014677626  [2023-10-21 08:37:39] frigate.app                    INFO    : Output process started: 301
2023-10-21 13:37:40.014679363  [2023-10-21 08:37:40] frigate.app                    INFO    : Camera processor started for living: 306
2023-10-21 13:37:40.014698088  [2023-10-21 08:37:40] frigate.app                    INFO    : Camera processor started for den: 307
2023-10-21 13:37:40.014700101  [2023-10-21 08:37:39] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-21 13:37:40.014703026  [2023-10-21 08:37:40] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-10-21 13:37:40.021997436  [2023-10-21 08:37:40] frigate.app                    INFO    : Camera processor started for office: 309
2023-10-21 13:37:40.025239291  [2023-10-21 08:37:40] frigate.app                    INFO    : Camera processor started for sunroom: 311
2023-10-21 13:37:40.030134755  [2023-10-21 08:37:40] frigate.app                    INFO    : Capture process started for living: 312
2023-10-21 13:37:40.035080960  [2023-10-21 08:37:40] frigate.app                    INFO    : Capture process started for den: 314
2023-10-21 13:37:40.039410314  [2023-10-21 08:37:40] frigate.app                    INFO    : Capture process started for office: 319
2023-10-21 13:37:40.044126831  [2023-10-21 08:37:40] frigate.app                    INFO    : Capture process started for sunroom: 323
```

### FFprobe output from your camera

```shell
Input #0, rtsp, from 'rtsp://admin:bdt100799969@192.168.1.168:554/h264Preview_01_main':
  Metadata:
    title           : Session streamed by "preview"
    comment         : h264Preview_01_main
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1072, 50 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: aac (LC), 16000 Hz, mono, fltp
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink E1 Pro

**Comment by NickM-27** [comment]
is it running the addon in HA OS in a VM or natively?

**Comment by bturrie** [comment]
natively
    On Saturday, October 21, 2023 at 10:22:40 AM CDT, Nicolas Mowen ***@***.***> wrote:  
 
 


is it running the addon in HA OS in a VM or natively?

**Comment by NickM-27** [comment]
Then it may be a power issue, do you not see the device in the hardware section in HA OS settings?

**Comment by bturrie** [comment]
No I don't see it.. It is plugged into a powered usb. If I move the Edge TPU and the powered usb hub to other systems it is recognized. Just not on this system. I'll tru it on another system and see where it shows up in hardware.
    On Tuesday, October 24, 2023 at 07:36:13 AM CDT, Nicolas Mowen ***@***.***> wrote:  
 
 


Then it may be a power issue, do you not see the device in the hardware section in HA OS settings?
