### ISSUE TITLE
No frames have been reveiced

### ISSUE THREAD

**Issue by radhoo2k10** [blakeblackshear/frigate#8265]
### Describe the problem you are having

Had Frigate running for a while now and without any problems. 
The power in the house went of and I had to restart portainer and now this happens:
![image](https://github.com/blakeblackshear/frigate/assets/78762281/e86df333-ca1c-4473-a1a4-301e5256245b)
It has now stopped tracking, but recording is ok.
When I start Frigate everything works, but after about 10 min or so the error occurs. 
The cameras are still streaming when I click on them:
![image](https://github.com/blakeblackshear/frigate/assets/78762281/90f1aae8-bb1d-441c-adde-e65297591135)

Docker:
services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    shm_size: "64mb"
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/terje/frigate/config.yml:/config/config.yml
      - /media/terje/record/frigate/:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935
      - 8554:8554
    environment:
      FRIGATE_RTSP_PASSWORD: "*******"

### Version

0.12.1-367D724

### Frigate config file

```yaml
ui:
  live_mode: mse

mqtt:
  host: 192.168.1.149
  user: user
  password: password

ffmpeg:
  hwaccel_args: preset-rpi-64-h264


go2rtc:
  streams:
    garasjen:
      - rtsp://*****:********@192.168.2.10:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam#audio=opus"
    garasjen_sub:
      - rtsp://*****:*********@192.168.2.10:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:rtsp_cam_sub#audio=opus"
    ytterdoren:
      - rtsp://*****:*******@192.168.2.9:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam#audio=opus"
    ytterdoren_sub:
      - rtsp://*****:******@192.168.2.9:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:rtsp_cam#audio=opus"
    gardsplassen:
      - rtsp://******:******@192.168.2.11:554/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:rtsp_cam#audio=opus"
    gardsplassen_sub:
      - rtsp://*****:*******@192.168.2.11:554/cam/realmonitor?channel=1&subtype=2
      - "ffmpeg:rtsp_cam#audio=opus"

cameras:
  garasjen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garasjen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garasjen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    record:
      enabled: True
      retain: 
        days: 3
        mode: all
        #mode: active_objects 
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3 
        post_capture: 10   
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 5
    objects:
      track:
        - person
        - dog
        - cat
        - car
      filters:
        person:
          threshold: 0.8
          min_area: 5000
          max_area: 100000
    detect:
      width: 1280
      height: 720
      fps: 15
    live:
      stream_name: garasjen_sub

  ytterdoren:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/ytterdoren
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/ytterdoren_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    record:
      enabled: True
      retain: 
        days: 3
        mode: all
        #mode: active_objects 
      events:
        retain:
          default: 5
          mode: motion
        pre_capture: 3 
        post_capture: 10  
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: True
      height: 500
      retain:
        default: 5
    objects:
      track:
        - person
        - dog
        - bicycle
        - cat
        - car
    detect:
      width: 1280
      height: 720
      fps: 15
    live:
      stream_name: ytterdoren_sub

  gardsplassen:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/gardsplassen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/gardsplassen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    record:
      enabled: True
      retain: 
        days: 3
        mode: all
        #mode: active_objects 
      events:
        retain:
          default: 5
        pre_capture: 3 
        post_capture: 10  
        required_zones:
          - gardsplass
          - utenfor_gardsplass
    snapshots:
      enabled: true
      timestamp: false
      bounding_box: true
      crop: False
      height: 500
      retain:
        default: 5
    detect:
      width: 1280
      height: 720
      fps: 15
    objects:
      track:
        - person
        - dog
        - cat
        - car
        - horse
        - bicycle
    live:
      stream_name: gardsplassen_sub
    zones:
      gardsplass:
        coordinates: 654,136,684,144,701,199,723,203,728,282,794,278,790,331,810,720,0,720,0,366,631,136
        objects:
          - person
          - dog
          - cat
          - car
          - horse
          - bicycle
        filters:
          person:
            threshold: 0.7
      utenfor_gardsplass:
        coordinates: 0,119,619,91,626,166,0,366
        objects:
          - horse
      skremme:
        coordinates: 469,201,628,201,733,209,623,165
        objects:
          - person
```

### Relevant log output

```shell
fritgate log:

2023-10-21 19:24:28.033142522  [INFO] Starting Frigate...
2023-10-21 19:24:29.089252541  [2023-10-21 19:24:29] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-21 19:24:29.118744339  [2023-10-21 19:24:29] peewee_migrate                 INFO    : Starting migrations
2023-10-21 19:24:29.136851414  [2023-10-21 19:24:29] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-21 19:24:29.151312678  [2023-10-21 19:24:29] detector.cpu                   INFO    : Starting detection process: 432
2023-10-21 19:24:29.154412860  [2023-10-21 19:24:29] frigate.app                    INFO    : Output process started: 434
2023-10-21 19:24:29.154529492  [2023-10-21 19:24:29] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-10-21 19:24:29.160203233  [2023-10-21 19:24:29] frigate.app                    INFO    : Camera processor started for garasjen: 437
2023-10-21 19:24:29.165660682  [2023-10-21 19:24:29] frigate.app                    INFO    : Camera processor started for ytterdoren: 439
2023-10-21 19:24:29.170331202  [2023-10-21 19:24:29] frigate.app                    INFO    : Camera processor started for gardsplassen: 441
2023-10-21 19:24:29.174426862  [2023-10-21 19:24:29] frigate.app                    INFO    : Capture process started for garasjen: 442
2023-10-21 19:24:29.181570209  [2023-10-21 19:24:29] frigate.app                    INFO    : Capture process started for ytterdoren: 445
2023-10-21 19:24:29.182527388  [2023-10-21 19:24:29] frigate.app                    INFO    : Capture process started for gardsplassen: 448
2023-10-21 19:26:57.199015109  Exception in thread recording_cleanup:
2023-10-21 19:26:57.199030494  Traceback (most recent call last):
2023-10-21 19:26:57.199032265    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-10-21 19:26:57.199889662      self.run()
2023-10-21 19:26:57.199892503    File "/opt/frigate/frigate/record.py", line 633, in run
2023-10-21 19:26:57.200213184      self.expire_files()
2023-10-21 19:26:57.200225969    File "/opt/frigate/frigate/record.py", line 582, in expire_files
2023-10-21 19:26:57.200483698      if p.stat().st_mtime < delete_before.get(p.parent.name, default_expire):
2023-10-21 19:26:57.200494385    File "/usr/lib/python3.9/pathlib.py", line 1221, in stat
2023-10-21 19:26:57.201208524      return self._accessor.stat(self)
2023-10-21 19:26:57.201228107  OSError: [Errno 5] Input/output error: '/media/frigate/recordings/2023-10-21/11/garasjen/13.15.mp4'
2023-10-21 19:42:38.735327581  Exception in thread detected_frames_processor:
2023-10-21 19:42:38.735330817  Traceback (most recent call last):
2023-10-21 19:42:38.735332156    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-10-21 19:42:38.736286302      self.run()
2023-10-21 19:42:38.736298803    File "/opt/frigate/frigate/object_processing.py", line 910, in run
2023-10-21 19:42:38.736782508      camera_state.update(
2023-10-21 19:42:38.736794421    File "/opt/frigate/frigate/object_processing.py", line 531, in update
2023-10-21 19:42:38.736954389      c(self.name, removed_obj, frame_time)
2023-10-21 19:42:38.736965361    File "/opt/frigate/frigate/object_processing.py", line 694, in end
2023-10-21 19:42:38.737185983      with open(
2023-10-21 19:42:38.737198067  OSError: [Errno 5] Input/output error: '/media/frigate/clips/gardsplassen-1697910130.65271-8fzjgf.jpg'
2023-10-21 19:43:28.885411541  [2023-10-21 19:43:28] frigate.http                   ERROR   : Exception on /garasjen/latest.jpg [GET]
2023-10-21 19:43:28.885419546  Traceback (most recent call last):
2023-10-21 19:43:28.885425905    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2529, in wsgi_app
2023-10-21 19:43:28.885435353      response = self.full_dispatch_request()
2023-10-21 19:43:28.885440782    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-10-21 19:43:28.885493082      rv = self.handle_user_exception(e)
2023-10-21 19:43:28.885497861    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-10-21 19:43:28.885503052      rv = self.dispatch_request()
2023-10-21 19:43:28.885508356    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-10-21 19:43:28.885570911      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-10-21 19:43:28.885575674    File "/opt/frigate/frigate/http.py", line 897, in latest_frame
2023-10-21 19:43:28.885580549      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-10-21 19:43:28.885585988  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-10-21 19:43:28.885634885  
2023-10-21 19:43:28.886838947  [2023-10-21 19:43:28] frigate.http                   ERROR   : Exception on /gardsplassen/latest.jpg [GET]
2023-10-21 19:43:28.886845257  Traceback (most recent call last):
2023-10-21 19:43:28.886850140    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2529, in wsgi_app
2023-10-21 19:43:28.886855162      response = self.full_dispatch_request()
2023-10-21 19:43:28.886860863    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-10-21 19:43:28.886865361      rv = self.handle_user_exception(e)
2023-10-21 19:43:28.886871100    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-10-21 19:43:28.886875662      rv = self.dispatch_request()
2023-10-21 19:43:28.886879418    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-10-21 19:43:28.886883043      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-10-21 19:43:28.886888167    File "/opt/frigate/frigate/http.py", line 897, in latest_frame
2023-10-21 19:43:28.886893530      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-10-21 19:43:28.886900176  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-10-21 19:43:28.886903611  
2023-10-21 19:43:28.891658156  [2023-10-21 19:43:28] frigate.http                   ERROR   : Exception on /ytterdoren/latest.jpg [GET]
2023-10-21 19:43:28.891664220  Traceback (most recent call last):
2023-10-21 19:43:28.891670118    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2529, in wsgi_app
2023-10-21 19:43:28.891674734      response = self.full_dispatch_request()
2023-10-21 19:43:28.891763141    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1825, in full_dispatch_request
2023-10-21 19:43:28.891768720      rv = self.handle_user_exception(e)
2023-10-21 19:43:28.891773952    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1823, in full_dispatch_request
2023-10-21 19:43:28.891778037      rv = self.dispatch_request()
2023-10-21 19:43:28.891783118    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1799, in dispatch_request
2023-10-21 19:43:28.891787565      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-10-21 19:43:28.891792084    File "/opt/frigate/frigate/http.py", line 897, in latest_frame
2023-10-21 19:43:28.891796701      frame = cv2.resize(frame, dsize=(width, height), interpolation=cv2.INTER_AREA)
2023-10-21 19:43:28.891802153  cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
2023-10-21 19:43:28.891805996  

go2rtc log:

2023-10-21 19:24:28.033131087  [INFO] Preparing go2rtc config...
2023-10-21 19:24:28.339027804  [INFO] Starting go2rtc...
2023-10-21 19:24:28.430850554  19:24:28.430 INF go2rtc version 1.2.0 linux/amd64
2023-10-21 19:24:28.431238096  19:24:28.431 INF [api] listen addr=:1984
2023-10-21 19:24:28.431614317  19:24:28.431 INF [rtsp] listen addr=:8554
2023-10-21 19:24:28.432038659  19:24:28.432 INF [srtp] listen addr=:8443
2023-10-21 19:24:28.432318793  19:24:28.432 INF [webrtc] listen addr=:8555
2023-10-21 19:24:29.264708061  19:24:29.264 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="exec: exit status 1" url=ffmpeg:rtsp_cam#audio=opus
2023-10-21 19:24:38.033207205  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by radhoo2k10** [comment]
Think I found the issue. I had added the mounted HD via fstab and it really messed up the ownership on the files and folders.
