### ISSUE TITLE
[Support]: Home assistant error loading frigate beta version

### ISSUE THREAD

**Issue by rsteckler** [blakeblackshear/frigate#8272]
### Describe the problem you are having

Upgraded my frigate to 13 beta 2 and now Home assistant throws the following at startup

```
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 9:09:43 AM (2 occurrences)
Last logged: 9:13:13 AM

Error setting up entry homestack-frigate-service:5000 for frigate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigate/__init__.py", line 186, in async_setup_entry
    if AwesomeVersion(server_version) <= AwesomeVersion(FRIGATE_VERSION_ERROR_CUTOFF):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 202, in __le__
    return self.__eq__(compareto) or self.__lt__(compareto)
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 176, in __lt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <unknown 0.13.0-0858859> and <SemVer 0.8.4>
```

The last line makes me think the semantic versioning in the betas might not be the same as that used in the actual releases and the home assistant integration expects it to be a semver?

### Version

0.13.0-0858859

### Frigate config file

```yaml
NA
```

### Relevant log output

```shell
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 9:09:43 AM (2 occurrences)
Last logged: 9:13:13 AM

Error setting up entry homestack-frigate-service:5000 for frigate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigate/__init__.py", line 186, in async_setup_entry
    if AwesomeVersion(server_version) <= AwesomeVersion(FRIGATE_VERSION_ERROR_CUTOFF):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 202, in __le__
    return self.__eq__(compareto) or self.__lt__(compareto)
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awesomeversion/awesomeversion.py", line 176, in __lt__
    raise AwesomeVersionCompareException(
awesomeversion.exceptions.AwesomeVersionCompareException: Can't compare <unknown 0.13.0-0858859> and <SemVer 0.8.4>
```
```


### FFprobe output from your camera

```shell
NA
```

### Frigate stats

```json
NA
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

NA

**Comment by NickM-27** [comment]
Please update to the latest version of the integration, this has already been fixed https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v5.0.0-beta.2

**Comment by rsteckler** [comment]
I'm running the latest hass integration (since months ago)
![image](https://github.com/blakeblackshear/frigate/assets/1714230/4516166b-540e-4b93-9dc4-e06d6306bd26)

Will try to remove the frigate device, hacs integration, and reinstall both.

**Comment by rsteckler** [comment]
Nevermind - realized I needed to install the latest beta and not the latest released version.
