### ISSUE TITLE
[Camera Support]: Wyze Flood Light Camera

### ISSUE THREAD

**Issue by awwbaker** [blakeblackshear/frigate#8285]
### Describe the problem you are having

I am trying to add additional wyze flood light cams to my system. I was trying to and think I was following the getting started page. I am running Docker Wyze Bridge to get the streams.

I can see the video but neither am I getting any events either.

I am sorry to bother but I just do not see where I went astray. Any guidance would be appreciated! Thank You, Anthony

### Version

 Frigate Current version: 0.12.1 (Changelog)

### Frigate config file

```yaml
mqtt:
  host: 192.168.4.23
  user: mqtt_user
  password: mqtt_user

detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    garage:
    - rtsp://192.168.4.23:8554/garage
    breezeway:
    - rtsp://192.168.4.23:8554/breezeway
    front_door:
    - rtsp://XXX:XXX@192.168.4.117:554/h264Preview_01_main

cameras:
  garage: 
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:554/rtsp
          roles:
            - detect
      detect:
        enabled: True
        width: 1920
        height: 1080
    objects:
        track:
         - person
         - car

#  breezeway: 

  
  front_door: 
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      output_args:
          record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: true
      retain:
        days: 14
        mode: all
    objects:
      track:
        - person
        - car
#    retain:
#        default: 14
    zones:
      entryway:
        coordinates: 511,720,918,720,647,538,503,526
        objects:
          - person    
    motion:
       mask:
       - 408,219,894,216,925,720,1280,720,1280,0,0,0,0,720,154,720,272,720,443,720
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2023-10-23 15:33:15.465659115  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
2023-10-23 15:33:15.473268817  [INFO] Starting Frigate...
2023-10-23 15:33:15.474322330  [INFO] Starting NGINX...
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-10-23 15:33:15.516747572  [INFO] Got IP address from supervisor: 192.168.4.23
2023-10-23 15:33:15.566002580  [INFO] Got WebRTC port from supervisor: 8555
2023-10-23 15:33:15.830643126  [INFO] Starting go2rtc...
2023-10-23 15:33:15.942589642  11:33:15.942 INF go2rtc version 1.2.0 linux/amd64
2023-10-23 15:33:15.943223102  11:33:15.942 INF [api] listen addr=:1984
2023-10-23 15:33:15.943228139  11:33:15.943 INF [rtsp] listen addr=:8554
2023-10-23 15:33:15.943601632  11:33:15.943 INF [srtp] listen addr=:8443
2023-10-23 15:33:15.943877435  11:33:15.943 INF [webrtc] listen addr=:8555
2023-10-23 15:33:16.335710907  2023/10/23 11:33:16 [error] 138#138: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.1, server: , request: "GET /api/stats HTTP/1.1", upstream: "http://127.0.0.1:5001/stats", host: "ccab4aaf-frigate:5000"
2023-10-23 15:33:16.335747694  172.30.32.1 - - [23/Oct/2023:11:33:16 -0400] "GET /api/stats HTTP/1.1" 502 157 "-" "HomeAssistant/2023.10.5 aiohttp/3.8.5 Python/3.11" "-"
2023-10-23 15:33:16.733389198  [2023-10-23 11:33:16] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-23 15:33:16.742919720  *************************************************************
2023-10-23 15:33:16.742924920  *************************************************************
2023-10-23 15:33:16.742930788  ***    Your config file is not valid!                     ***
2023-10-23 15:33:16.742933908  ***    Please check the docs at                           ***
2023-10-23 15:33:16.742936192  ***    https://docs.frigate.video/configuration/index     ***
2023-10-23 15:33:16.742965439  *************************************************************
2023-10-23 15:33:16.742967061  *************************************************************
2023-10-23 15:33:16.742968792  ***    Config Validation Errors                           ***
2023-10-23 15:33:16.742970150  *************************************************************
2023-10-23 15:33:16.742992022  1 validation error for FrigateConfig
2023-10-23 15:33:16.742993486  cameras -> garage -> ffmpeg -> detect
2023-10-23 15:33:16.742994963    extra fields not permitted (type=value_error.extra)
2023-10-23 15:33:16.743828303  Traceback (most recent call last):
2023-10-23 15:33:16.743830981    File "/opt/frigate/frigate/app.py", line 351, in start
2023-10-23 15:33:16.743832380      self.init_config()
2023-10-23 15:33:16.743834023    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-10-23 15:33:16.743835542      user_config = FrigateConfig.parse_file(config_file)
2023-10-23 15:33:16.743837182    File "/opt/frigate/frigate/config.py", line 1078, in parse_file
2023-10-23 15:33:16.743838598      return cls.parse_obj(config)
2023-10-23 15:33:16.743840270    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2023-10-23 15:33:16.743841925    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-10-23 15:33:16.743843703  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2023-10-23 15:33:16.743846208  cameras -> garage -> ffmpeg -> detect
2023-10-23 15:33:16.743847802    extra fields not permitted (type=value_error.extra)
2023-10-23 15:33:16.743876544  
2023-10-23 15:33:16.744004657  *************************************************************
2023-10-23 15:33:16.744007445  ***    End Config Validation Errors                       ***
2023-10-23 15:33:16.744009486  *************************************************************
2023-10-23 15:33:17.965590518  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-10-23 15:33:17.976015850  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-10-23 15:33:18.005622617  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-10-23 15:33:18.010257591  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-10-23 15:33:18.015941764  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
I tried to do this but get "bash: run:  command not found".  ----- I guess we better start here?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wireless

### Camera make and model

Wyze V3

### Any other information that may be helpful

I comment this out to get frigate to run.
#      detect:
#        enabled: True
#        width: 1920
#        height: 1080

I am a complete noob so still on the steep side of the curve, thank you!

**Comment by awwbaker** [comment]
Can we please start with the basics? I am getting the blow error, how do I know from the log which "inputs" it is referring to or what the error is at that input?

2023-10-23 16:34:26.675052395  *************************************************************
2023-10-23 16:34:26.675056578  *************************************************************
2023-10-23 16:34:26.675061022  ***    Your config file is not valid!                     ***
2023-10-23 16:34:26.675063147  ***    Please check the docs at                           ***
2023-10-23 16:34:26.675064626  ***    https://docs.frigate.video/configuration/index     ***
2023-10-23 16:34:26.675085374  *************************************************************
2023-10-23 16:34:26.675086848  *************************************************************
2023-10-23 16:34:26.675088662  ***    Config Validation Errors                           ***
2023-10-23 16:34:26.675090095  *************************************************************
2023-10-23 16:34:26.675091119  'inputs'
2023-10-23 16:34:26.676115067  Traceback (most recent call last):
2023-10-23 16:34:26.676119452    File "/opt/frigate/frigate/app.py", line 351, in start
2023-10-23 16:34:26.676121360      self.init_config()
2023-10-23 16:34:26.676123148    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-10-23 16:34:26.676124916      user_config = FrigateConfig.parse_file(config_file)
2023-10-23 16:34:26.676126577    File "/opt/frigate/frigate/config.py", line 1078, in parse_file
2023-10-23 16:34:26.676128414      return cls.parse_obj(config)
2023-10-23 16:34:26.676130608    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2023-10-23 16:34:26.676132703    File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-10-23 16:34:26.676134578    File "pydantic/main.py", line 1076, in pydantic.main.validate_model
2023-10-23 16:34:26.676136626    File "pydantic/fields.py", line 886, in pydantic.fields.ModelField.validate
2023-10-23 16:34:26.676138662    File "pydantic/fields.py", line 1021, in pydantic.fields.ModelField._validate_mapping_like
2023-10-23 16:34:26.676177843    File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
2023-10-23 16:34:26.676180196    File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
2023-10-23 16:34:26.676199009    File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
2023-10-23 16:34:26.676200773    File "pydantic/fields.py", line 1157, in pydantic.fields.ModelField._apply_validators
2023-10-23 16:34:26.676202898    File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
2023-10-23 16:34:26.676204896    File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
2023-10-23 16:34:26.676221094    File "/opt/frigate/frigate/config.py", line 635, in __init__
2023-10-23 16:34:26.676222684      if len(config["ffmpeg"]["inputs"]) == 1:
2023-10-23 16:34:26.676224022  KeyError: 'inputs'
2023-10-23 16:34:26.676225422  
2023-10-23 16:34:26.676227282  *************************************************************
2023-10-23 16:34:26.676228861  ***    End Config Validation Errors                       ***
2023-10-23 16:34:26.676303240  *************************************************************

**Comment by NickM-27** [comment]
I'd suggest reading Getting started docs
https://docs.frigate.video/guides/getting_started

This show the correct formatting and what needs to be done. You should check after each step that the config is working and use the config editor built in to frigate which has validation built in
