### ISSUE TITLE
[Support]:  Uploading not a motorcycle frigate+ doesn't send label

### ISSUE THREAD

**Issue by calederer** [blakeblackshear/frigate#8292]
### Describe the problem you are having

When uploading a snapshot that has a incorrectly tagged motorcycle using 'not a motorcycle' the 'not' tag is not uploaded to frigate plus 

### Version

0.13.0-0858859

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
2023-10-23 20:15:40.995453246  [2023-10-23 20:15:40] frigate.http                   ERROR   : {"errors":[{"param":"label","type":"invalid_enum_value"}]}
2023-10-23 20:15:40.995470942  Traceback (most recent call last):
2023-10-23 20:15:40.995479399    File "/opt/frigate/frigate/http.py", line 331, in false_positive
2023-10-23 20:15:40.995486986      current_app.plus_api.add_false_positive(
2023-10-23 20:15:40.995495451    File "/opt/frigate/frigate/plus.py", line 169, in add_false_positive
2023-10-23 20:15:40.995502563      raise Exception(r.text)
2023-10-23 20:15:40.995510464  Exception: {"errors":[{"param":"label","type":"invalid_enum_value"}]}
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
N/A
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

AXIS

**Comment by NickM-27** [comment]
This is expected, motorcycle is not currently a supported label in frigate+
