### ISSUE TITLE
[Config Support]: 

### ISSUE THREAD

**Issue by waleed-source** [blakeblackshear/frigate#8360]
### Describe the problem you are having

hi all ,

I'm new to Frigate,

So I apologize for the beginner questions.
I've actually been running MQTT  when I try to run frigate, I get an error message that my configuration is invalid

I have posted my frigate.yaml below
As well as the error from the log

I'm not sure where I went wrong here.
`2023-10-27 22:44:02.280570965  1 validation error for FrigateConfig
2023-10-27 22:44:02.280573774  cameras -> EZVIZ -> ffmpeg -> roles

`

I checked RSTP operation on VLC media player on port 554.
And it works.
and Frigate stats is lodging 

![Screenshot 2023-10-28 021725](https://github.com/blakeblackshear/frigate/assets/70404451/c8d0d28a-90ca-4038-9879-0b7fa702ccc3)
Cheers

### Version

 0.12.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.*.***
  user: mqtt_user
  password: password

cameras:
  EZVIZ:
    ffmpeg:
      inputs:
      - path: rtsp://admin:SJVGSC@192.168.*.***:554/H.264
      roles:
        - detect
        - rtmp
        - record
    rtmp:
      enabled: False
    detect:
        width: 1080
        height: 720
        fps: 24
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
2023-10-27 22:44:00.329262388  [INFO] Preparing go2rtc config...
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-10-27 22:44:00.338003982  [INFO] Starting Frigate...
2023-10-27 22:44:00.345885778  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-10-27 22:44:00.384788415  [INFO] Got IP address from supervisor: 192.168.0.109
2023-10-27 22:44:00.438610212  [INFO] Got WebRTC port from supervisor: 8555
2023-10-27 22:44:00.777316068  [INFO] Starting go2rtc...
2023-10-27 22:44:00.865135432  01:44:00.865 INF go2rtc version 1.2.0 linux/amd64
2023-10-27 22:44:00.866461390  01:44:00.866 INF [api] listen addr=:1984
2023-10-27 22:44:00.866863801  01:44:00.866 INF [rtsp] listen addr=:8554
2023-10-27 22:44:00.867338593  01:44:00.867 INF [srtp] listen addr=:8443
2023-10-27 22:44:00.867607479  01:44:00.867 INF [webrtc] listen addr=:8555
2023-10-27 22:44:02.272506487  [2023-10-28 01:44:02] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-27 22:44:02.280389884  *************************************************************
2023-10-27 22:44:02.280394996  *************************************************************
2023-10-27 22:44:02.280399914  ***    Your config file is not valid!                     ***
2023-10-27 22:44:02.280430101  ***    Please check the docs at                           ***
2023-10-27 22:44:02.280432270  ***    https://docs.frigate.video/configuration/index     ***
2023-10-27 22:44:02.280433993  *************************************************************
2023-10-27 22:44:02.280435704  *************************************************************
2023-10-27 22:44:02.280437680  ***    Config Validation Errors                           ***
2023-10-27 22:44:02.280477137  *************************************************************
2023-10-27 22:44:02.280570965  1 validation error for FrigateConfig
2023-10-27 22:44:02.280573774  cameras -> EZVIZ -> ffmpeg -> roles
2023-10-27 22:44:02.280604464    extra fields not permitted (type=value_error.extra)
2023-10-27 22:44:02.281893549  Traceback (most recent call last):
2023-10-27 22:44:02.281897639    File "/opt/frigate/frigate/app.py", line 351, in start
2023-10-27 22:44:02.281899360      self.init_config()
2023-10-27 22:44:02.281901095    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-10-27 22:44:02.281902773      user_config = FrigateConfig.parse_file(config_file)
2023-10-27 22:44:02.281904542    File "/opt/frigate/frigate/config.py", line 1078, in parse_file
2023-10-27 22:44:02.281906094      return cls.parse_obj(config)
2023-10-27 22:44:02.281907847    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2023-10-27 22:44:02.281912533    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2023-10-27 22:44:02.281914536  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2023-10-27 22:44:02.281916443  cameras -> EZVIZ -> ffmpeg -> roles
2023-10-27 22:44:02.281918160    extra fields not permitted (type=value_error.extra)
2023-10-27 22:44:02.281999901  
2023-10-27 22:44:02.282037845  *************************************************************
2023-10-27 22:44:02.282072568  ***    End Config Validation Errors                       ***
2023-10-27 22:44:02.282106316  *************************************************************
2023-10-27 22:44:03.522004874  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-10-27 22:44:03.535587149  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-10-27 22:44:03.591000894  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-10-27 22:44:03.595207310  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-10-27 22:44:03.601262205  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Frigate stats

```json
lodging 
```

### Operating system

Debian

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
Roles is not indented enough, Getting started
https://docs.frigate.video/guides/getting_started

**Comment by waleed-source** [comment]
> Roles is not indented enough, Getting started https://docs.frigate.video/guides/getting_started

After three days the solution was only " "

Thank you, you solved the problem
