### ISSUE TITLE
[Support]: Using coral & nvidia GPU

### ISSUE THREAD

**Issue by FigJam23** [blakeblackshear/frigate#8384]
### Describe the problem you are having

Not sure if its possible to run google coral and a NVIDIA GPU for acceleration.
i can get either one to run individual but not with bot setup i get log errors both coral and GPU CPU and coral show in ui though.
can we do this or is it one or the other thanks.

Also if we are limited to one or the other what's better for function regardless of power use GPU or Coral thanks.

### Version

na

### Frigate config file

```yaml
detectors:
  tensorrt:
    type: tensorrt
    device: 0 # This is the default, select the first GPU
  coral1:
    type: edgetpu
    device: usb
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### Relevant log output

```shell
Frigate
Frigate
Cameras
Birdseye
Events
Storage
System
Config
Logs
Documentation
GitHub
Logs
Copy to Clipboard
2023-10-30 16:03:59.503547715  [INFO] Starting Frigate...
2023-10-30 16:04:00.396124660  [2023-10-30 16:04:00] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-30 16:04:00.468466764  [2023-10-30 16:04:00] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-10-30 16:04:00.469566068  [2023-10-30 16:04:00] peewee_migrate                 INFO    : Starting migrations
2023-10-30 16:04:01.079645876  [2023-10-30 16:04:00] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-30 16:04:01.115882814  [2023-10-30 16:04:01] detector.coral1                INFO    : Starting detection process: 440
2023-10-30 16:04:03.767797597  [2023-10-30 16:04:01] frigate.app                    INFO    : Output process started: 443
2023-10-30 16:04:03.768372330  [2023-10-30 16:04:01] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-30 16:04:03.768374960  [2023-10-30 16:04:01] detector.tensorrt              INFO    : Starting detection process: 438
2023-10-30 16:04:03.768378496  [2023-10-30 16:04:01] frigate.app                    INFO    : Camera processor started for driveway_cam: 450
2023-10-30 16:04:03.768379903  [2023-10-30 16:04:01] frigate.app                    INFO    : Camera processor started for front_entry: 452
2023-10-30 16:04:03.768393493  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +536, GPU +0, now: CPU 653, GPU 541 (MiB)
2023-10-30 16:04:03.768395160  [2023-10-30 16:04:01] frigate.app                    INFO    : Camera processor started for front_deck: 454
2023-10-30 16:04:03.768396430  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 15 MiB
2023-10-30 16:04:03.768409817  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +7, GPU +8, now: CPU 704, GPU 567 (MiB)
2023-10-30 16:04:03.768411349  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 705, GPU 577 (MiB)
2023-10-30 16:04:03.768420232  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +15, now: CPU 0, GPU 15 (MiB)
2023-10-30 16:04:03.768421509  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 689, GPU 569 (MiB)
2023-10-30 16:04:03.768422634  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 689, GPU 577 (MiB)
2023-10-30 16:04:03.768430538  [2023-10-30 16:04:01] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +7, now: CPU 0, GPU 22 (MiB)
2023-10-30 16:04:03.768431410  Process detector:coral1:
2023-10-30 16:04:03.768432424  [2023-10-30 16:04:03] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-10-30 16:04:03.768433583  [2023-10-30 16:04:03] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-10-30 16:04:03.768909281  [2023-10-30 16:04:01] frigate.app                    INFO    : Camera processor started for back_shed: 455
2023-10-30 16:04:03.768911100  [2023-10-30 16:04:01] frigate.app                    INFO    : Camera processor started for sand_pit: 457
2023-10-30 16:04:03.768912280  [2023-10-30 16:04:01] frigate.app                    INFO    : Camera processor started for 360cam: 458
2023-10-30 16:04:03.768913348  [2023-10-30 16:04:01] frigate.app                    INFO    : Capture process started for driveway_cam: 459
2023-10-30 16:04:03.768914398  [2023-10-30 16:04:01] frigate.app                    INFO    : Capture process started for front_entry: 463
2023-10-30 16:04:03.768915422  [2023-10-30 16:04:01] frigate.app                    INFO    : Capture process started for front_deck: 468
2023-10-30 16:04:03.768916474  [2023-10-30 16:04:01] frigate.app                    INFO    : Capture process started for back_shed: 473
2023-10-30 16:04:03.768917297  Traceback (most recent call last):
2023-10-30 16:04:03.768918312  [2023-10-30 16:04:01] frigate.app                    INFO    : Capture process started for sand_pit: 479
2023-10-30 16:04:03.768919247    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-30 16:04:03.768920003      self.run()
2023-10-30 16:04:03.768920931    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-30 16:04:03.768921783      self._target(*self._args, **self._kwargs)
2023-10-30 16:04:03.768922695    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-10-30 16:04:03.768923600      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-30 16:04:03.768924485    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-10-30 16:04:03.768925342      self.detect_api = create_detector(detector_config)
2023-10-30 16:04:03.768926235    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-10-30 16:04:03.768927016      return api(detector_config)
2023-10-30 16:04:03.768927936    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 39, in __init__
2023-10-30 16:04:03.768928735      self.interpreter = Interpreter(
2023-10-30 16:04:03.768929691    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
2023-10-30 16:04:03.768930526      _interpreter_wrapper.CreateWrapperFromFile(
2023-10-30 16:04:03.768931387  ValueError: Model provided has model identifier '
2023-10-30 16:04:03.768932350  [2023-10-30 16:04:01] frigate.app                    INFO    : Capture process started for 360cam: 483
```

### FFprobe output from your camera

```shell
na
```

### Frigate stats

```json
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/29391962/45914195-245f-4389-b33e-2af4dbdd1ef7)

**Comment by NickM-27** [comment]
Only one detector type is supported at a time, you can still use the coral for object detection and the GPU for hwaccel (this is what I do). The detectors don't dictate detection results as much as the model does, so it just depends which model works best.

**Comment by FigJam23** [comment]
Ok cool that sounds like something I would like to do, so is there any info you can point me to so I can set it up like that. Or could you please share a sample config.yaml of how I would setup the coral for detection and gpu for hwaccel. Thank you in advance much appreciated

**Comment by NickM-27** [comment]
There's nothing special about it, just follow the docs for using a coral and the docs for setting up hwaccel with nvidia

**Comment by FigJam23** [comment]
Oh ok so I've already got my Nvidia setup for hwaccel.
So this below if I change from
detectors:
  tensorrt:
    type: tensorrt
    device: 0 # This is the default, select the first GPU
  coral1:
    type: edgetpu
    device: usb
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

And make it for detector's 

detectors:
  coral1:
    type: edgetpu
    device: usb

And leave my hwaccel like

ffmpeg:
  hwaccel_args: preset-nvidia-h264 


I'll give it ago when I get home today hopefully I understand it correctly 😄

**Comment by NickM-27** [comment]
yes indeed, that would do it

**Comment by FigJam23** [comment]
Cool thanks so no model paths needed this is done by the default config for coral I guess

**Comment by FigJam23** [comment]
Cool made changes no models seems to be working good, coral is definitely getting close to hot not sure if that's normal. Thank you for all the help much appreciated

**Comment by NickM-27** [comment]
Coral getting hot is not unexpected, that's why the usb one has a heat sink and the pcie coral supports throttling.
