### ISSUE TITLE
[Detector Support]: Coral TPU randomly stopped being detected

### ISSUE THREAD

**Issue by tf5bassist** [blakeblackshear/frigate#8394]
### Describe the problem you are having

I finally got my new Coral TPU set up last week on my Home Assistant config with a few cameras, but then today I noticed that nothing was working on my Homarr dashboard.  The Coral TPU is now not being detected by Home Assistant when I didn't change anything since it last worked (to the best of my knowledge).

### Version

0.12.1

### Frigate config file

```yaml
database:
  path: /config/frigate.db
mqtt:
  host: 192.168.0.189
  user: mqtt_broker_user
  password: ***********
cameras:
  cat-food-cam:
    ffmpeg:
      inputs:
        - path: rtsp://homeassistant.local:8554/cat-food-cam
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      width: 1280
      height: 720
      enabled: true
    snapshots:
      enabled: true
  dining-room-cam:
    ffmpeg:
      inputs:
        - path: rtsp://homeassistant.local:8554/dining-room-cam
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      # width: 1280
      # height: 720
      enabled: true
    snapshots:
      enabled: true
  litter-box-cam:
    ffmpeg:
      inputs:
        - path: rtsp://homeassistant.local:8554/litter-box-cam?mp4
          roles:
            - detect
            - record
      hwaccel_args: preset-vaapi
    detect:
      # width: 1280
      # height: 720
      enabled: true
    snapshots:
      enabled: true
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
          mode: active_objects
detectors:
  coral:
    type: edgetpu
    device: usb

go2rtc:
  streams:
    cat-food-cam:
      - rtsp://homeassistant.local:8554/cat-food-cam
    dining-room-cam:
      - rtsp://homeassistant.local:8554/dining-room-cam
    litter-box-cam:
      - rtsp://homeassistant.local:8554/litter-box-cam?mp4

birdseye:
  restream: True
```

### docker-compose file or Docker CLI command

```yaml
n/a?
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-10-31 06:00:33.932962738  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx successfully started
s6-rc: info: service go2rtc-healthcheck successfully started
2023-10-31 06:00:33.937940932  [INFO] Starting Frigate...
2023-10-31 06:00:33.939827758  [INFO] Starting NGINX...
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-10-31 06:00:33.993576175  [INFO] Got IP address from supervisor: 192.168.0.189
2023-10-31 06:00:34.047401185  [INFO] Got WebRTC port from supervisor: 8555
2023-10-31 06:00:34.453773281  [INFO] Starting go2rtc...
2023-10-31 06:00:34.583628936  23:00:34.583 INF go2rtc version 1.2.0 linux/amd64
2023-10-31 06:00:34.584153334  23:00:34.584 INF [api] listen addr=:1984
2023-10-31 06:00:34.584803437  23:00:34.584 INF [rtsp] listen addr=:8554
2023-10-31 06:00:34.585417907  23:00:34.585 INF [srtp] listen addr=:8443
2023-10-31 06:00:34.586029941  23:00:34.585 INF [webrtc] listen addr=:8555
2023-10-31 06:00:36.225559484  [2023-10-30 23:00:36] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-31 06:00:36.280534062  [2023-10-30 23:00:36] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-10-31 06:00:36.281092021  [2023-10-30 23:00:36] peewee_migrate                 INFO    : Starting migrations
2023-10-31 06:00:36.288828760  [2023-10-30 23:00:36] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-31 06:00:36.319262686  [2023-10-30 23:00:36] detector.coral                 INFO    : Starting detection process: 298
2023-10-31 06:00:36.322976093  [2023-10-30 23:00:36] frigate.app                    INFO    : Output process started: 300
2023-10-31 06:00:36.325864147  Process detector:coral:
2023-10-31 06:00:36.326473633  [2023-10-30 23:00:36] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-31 06:00:36.326844772  [2023-10-30 23:00:36] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-10-31 06:00:36.329193751  Traceback (most recent call last):
2023-10-31 06:00:36.329812159    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-10-31 06:00:36.329816899      delegate = Delegate(library, options)
2023-10-31 06:00:36.330427533    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-10-31 06:00:36.330432170      raise ValueError(capture.message)
2023-10-31 06:00:36.331052508  ValueError
2023-10-31 06:00:36.331442573  
2023-10-31 06:00:36.331447267  During handling of the above exception, another exception occurred:
2023-10-31 06:00:36.331448654  
2023-10-31 06:00:36.332008014  Traceback (most recent call last):
2023-10-31 06:00:36.332375621    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-31 06:00:36.332379113      self.run()
2023-10-31 06:00:36.332805902    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-31 06:00:36.332809724      self._target(*self._args, **self._kwargs)
2023-10-31 06:00:36.333239342    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-10-31 06:00:36.333242616      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-31 06:00:36.333660217    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-10-31 06:00:36.333663746      self.detect_api = create_detector(detector_config)
2023-10-31 06:00:36.334151117  [2023-10-30 23:00:36] frigate.app                    INFO    : Camera processor started for cat-food-cam: 305
2023-10-31 06:00:36.334502755    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-10-31 06:00:36.334507115      return api(detector_config)
2023-10-31 06:00:36.334971841    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-10-31 06:00:36.334976798      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-10-31 06:00:36.335418553    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-10-31 06:00:36.335422723      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-10-31 06:00:36.335952952  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-10-31 06:00:36.335957836  
2023-10-31 06:00:36.341544212  [2023-10-30 23:00:36] frigate.app                    INFO    : Camera processor started for dining-room-cam: 307
2023-10-31 06:00:36.349977748  [2023-10-30 23:00:36] frigate.app                    INFO    : Camera processor started for litter-box-cam: 309
2023-10-31 06:00:36.359282654  [2023-10-30 23:00:36] frigate.app                    INFO    : Capture process started for cat-food-cam: 310
2023-10-31 06:00:36.367219088  [2023-10-30 23:00:36] frigate.app                    INFO    : Capture process started for dining-room-cam: 311
2023-10-31 06:00:36.375167601  [2023-10-30 23:00:36] frigate.app                    INFO    : Capture process started for litter-box-cam: 315
2023-10-31 06:00:36.418619007  [2023-10-30 23:00:36] frigate.video                  ERROR   : cat-food-cam: Unable to read frames from ffmpeg process.
2023-10-31 06:00:36.418887160  [2023-10-30 23:00:36] frigate.video                  ERROR   : cat-food-cam: ffmpeg process is not running. exiting capture thread...
2023-10-31 06:00:43.957689457  [INFO] Starting go2rtc healthcheck service...
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

Troubleshooting steps:

- Restarted add-on, no change
- Restarted HA, no change
- Rebooted HA server, no change
- Reseated USB cable to dongle, no change
- Moved to another port, no change
- Moved from the back ports to the front, no change

**Comment by tf5bassist** [comment]
....  I think the factory cable was bad.  Same as noticed in [this other comment over at the HA forums](https://community.home-assistant.io/t/rpi-4-frigate-coral-tpu-not-detected/568161/4).  Replaced the cable with a random other cable and so far so good.  Weird.

**Comment by NickM-27** [comment]
We've seen other users report the cable being bad, I had the same issue. I'll go ahead and close this, feel free to create a new issue if something comes up
