### ISSUE TITLE
[Support]: Frigate continuous Crash / Restart. Maybe due to Edge TPU Detection.

### ISSUE THREAD

**Issue by indo419** [blakeblackshear/frigate#8418]
### Describe the problem you are having

Frigate was running well for several months.
Yesterday I did a Linux system upgrade and started having intermittent issues with crashing which seems to be caused by Edge TPU detection.
Frigate restarts and runs for ~30 seconds then restarts again.
If I restart Linux it may run for several hours then begins to crash and restart.

### Version

0.12.1-367D724

### Frigate config file

```yaml
#mqtt:
#  host: maqiatto.com
#  port: 8883
#  user: xxxxxxxxxxxxxxx@gmail.com
#  password: xxxxxxxxxxxxxxxxxxxx
#  topic_prefix: xxxxxxxxxxxxxxx@gmail.com/frigate

mqtt:
  enabled: False
  host: xxxxxxxxxxxxxxxxxx.s1.eu.hivemq.cloud
  port: 8883
  user: xxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxx


#logger:
#  # Optional: default log level (default: shown below)
#  default: debug
#  logs:
#    frigate.record: debug

database:
  path: /db/frigate.db

detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1  
#  cpu1:
#    type: cpu
#    num_threads: 3
#  cpu2:
#    type: cpu
#    num_threads: 3
#  cpu3:
#    type: cpu
#    num_threads: 3
#  cpu4:
#    type: cpu
#    num_threads: 3

#ffmpeg:
#  hwaccel_args: preset-vaapi

birdseye:
  enabled: True
  restream: False
  width: 1280
  height: 720
  quality: 8        # 1 is the highest quality, and 31 is the lowest.
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects


detect:
  enabled: True
  width: 640 # <---- update for your camera's resolution
  height: 480 # <---- update for your camera's resolution
  fps: 5
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
#    max_frames:
#      default: 3000
#      objects:
#        person: 1000


record:
  enabled: True
  expire_interval: 360
  retain:
    days: 100
    mode: all    # all, motion, and active_objects
  events:
    pre_capture: 5
    post_capture: 5
    objects:    # track all opbjects
      - person
      - car
      - bicycle
      - motorcycle
      - bus
      - cat
      - dog
      - bird
#    required_zones: []
    retain:
      default: 60
      mode: motion
      objects:
        person: 120
        car: 120
        bicycle: 120
        motorcycle: 120
        bus: 120
        cat: 120
        dog: 120
        bird: 120


snapshots:
  enabled: True
  clean_copy: True
  timestamp: True
  bounding_box: True
  crop: False
#  height: 175
#  required_zones: []
  retain:
    default: 180
    objects:
      person: 180
      car: 180
      bicycle: 180
      motorcycle: 180
      bus: 180
      cat: 180
      dog: 180
      bird: 180



timestamp_style:
  position: "tr"
  format: "%m/%d/%Y %H:%M:%S"
  color:
    red: 255
    green: 255
    blue: 100
  thickness: 1
  # Optional: Effect of lettering (default: shown below)
  #           None (No effect),
  #           "solid" (solid background in inverse color of font)
  #           "shadow" (shadow for font)
  effect: "shadow"


cameras:
  Sigma_Pallet_Wrapper: ###################################################
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://xxxxxxxxxxxxxxxxx/videoSub
          roles:
            - detect
        - path: rtsp://xxxxxxxxxxxxxxxxxxxxxx/videoMain
          roles:
            - record

    motion:
      mask:
        - 234,0,231,27,165,24,159,0

    objects:
      track:
        - person
        - car

#    snapshots:
#      enabled: True
#      timestamp: True
#      bounding_box: True
#      retain:
#        default: 5
#        objects:
#          person: 15

#    record:
#      enabled: True
#      retain:
#        days: 10
#        mode: all    # all, motion, and active_objects
#      events:
#        objects:
#          - person
#          - car
#          - bicycle
#        required_zones: []
#        retain:
#          default: 21
#          objects:
#            person: 31
#            car: 31
#            bicycle: 15
###########################################################################
```

### Relevant log output

```shell
2023-11-01 13:20:28.096062460  [INFO] Starting Frigate...
2023-11-01 13:20:28.884509923  [2023-11-01 13:20:28] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-01 13:20:28.978103799  [2023-11-01 13:20:28] peewee_migrate                 INFO    : Starting migrations
2023-11-01 13:20:28.981233963  [2023-11-01 13:20:28] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-01 13:20:28.996340788  [2023-11-01 13:20:28] detector.coral1                INFO    : Starting detection process: 432
2023-11-01 13:20:32.182050489  [2023-11-01 13:20:28] detector.coral2                INFO    : Starting detection process: 434
2023-11-01 13:20:32.185372550  [2023-11-01 13:20:28] frigate.app                    INFO    : Output process started: 438
2023-11-01 13:20:32.185535723  [2023-11-01 13:20:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb:0
2023-11-01 13:20:32.185616717  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for Sigma_Pallet_Wrapper: 449
2023-11-01 13:20:32.185620987  [2023-11-01 13:20:30] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-11-01 13:20:32.185693580  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for Sigma_701_Dome: 451
2023-11-01 13:20:32.185727436  Process detector:coral1:
2023-11-01 13:20:32.185775652  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for Sigma_700_Dome: 453
2023-11-01 13:20:32.185852493  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for Sigma_701_Lobby: 454
2023-11-01 13:20:32.185930903  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for Sigma_701_TimeClock: 455
2023-11-01 13:20:32.186008161  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for Sigma_AK_Office: 456
2023-11-01 13:20:32.186073919  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for Sigma_Tool_Room: 458
2023-11-01 13:20:32.186145952  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for ShowLow_Front: 459
2023-11-01 13:20:32.186215824  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for ShowLow_SideYard: 461
2023-11-01 13:20:32.186286174  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for ShowLow_LivingRoom: 462
2023-11-01 13:20:32.186354911  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for ShowLow_Bedroom: 464
2023-11-01 13:20:32.186417480  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_Garage: 466
2023-11-01 13:20:32.186483809  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_Kitchen: 467
2023-11-01 13:20:32.186545044  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_22: 469
2023-11-01 13:20:32.186611694  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_West_Back: 470
2023-11-01 13:20:32.186652032  Traceback (most recent call last):
2023-11-01 13:20:32.186669922    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-11-01 13:20:32.186672061      delegate = Delegate(library, options)
2023-11-01 13:20:32.186674104  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_West_Front: 472
2023-11-01 13:20:32.186676004    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-11-01 13:20:32.186680004      raise ValueError(capture.message)
2023-11-01 13:20:32.186688847  ValueError
2023-11-01 13:20:32.186695996  
2023-11-01 13:20:32.186697693  During handling of the above exception, another exception occurred:
2023-11-01 13:20:32.186699175  
2023-11-01 13:20:32.186712742  Traceback (most recent call last):
2023-11-01 13:20:32.186739312  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_Gate: 473
2023-11-01 13:20:32.186756199    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-11-01 13:20:32.186758006      self.run()
2023-11-01 13:20:32.186770121    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-11-01 13:20:32.186771770      self._target(*self._args, **self._kwargs)
2023-11-01 13:20:32.186773394    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-11-01 13:20:32.186775151      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-11-01 13:20:32.186776755    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-11-01 13:20:32.186778359      self.detect_api = create_detector(detector_config)
2023-11-01 13:20:32.186780072    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-11-01 13:20:32.186789792      return api(detector_config)
2023-11-01 13:20:32.186807525    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-11-01 13:20:32.186809462      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-11-01 13:20:32.186811196    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-11-01 13:20:32.186812803      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-11-01 13:20:32.186814403  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-11-01 13:20:32.186815621  
2023-11-01 13:20:32.186817410  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_Bar: 475
2023-11-01 13:20:32.186851549  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_Front: 476
2023-11-01 13:20:32.186926921  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_Pool: 478
2023-11-01 13:20:32.186993805  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_Patio: 479
2023-11-01 13:20:32.187062514  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_East_Back: 481
2023-11-01 13:20:32.187124716  [2023-11-01 13:20:29] frigate.app                    INFO    : Camera processor started for McBroom_East_Front: 482
2023-11-01 13:20:32.187194443  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for Sigma_Pallet_Wrapper: 484
2023-11-01 13:20:32.187261405  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for Sigma_701_Dome: 488
2023-11-01 13:20:32.187326356  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for Sigma_700_Dome: 489
2023-11-01 13:20:32.187388682  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for Sigma_701_Lobby: 494
2023-11-01 13:20:32.187446014  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for Sigma_701_TimeClock: 506
2023-11-01 13:20:32.187503308  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for Sigma_AK_Office: 513
2023-11-01 13:20:32.187550037  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for Sigma_Tool_Room: 517
2023-11-01 13:20:32.187594294  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for ShowLow_Front: 526
2023-11-01 13:20:32.187632047  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for ShowLow_SideYard: 532
2023-11-01 13:20:32.187681436  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for ShowLow_LivingRoom: 536
2023-11-01 13:20:32.187736913  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for ShowLow_Bedroom: 544
2023-11-01 13:20:32.187793720  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_Garage: 549
2023-11-01 13:20:32.187847557  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_Kitchen: 557
2023-11-01 13:20:32.187902779  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_22: 563
2023-11-01 13:20:32.187958947  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_West_Back: 571
2023-11-01 13:20:32.188014160  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_West_Front: 578
2023-11-01 13:20:32.188069616  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_Gate: 582
2023-11-01 13:20:32.188124691  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_Bar: 589
2023-11-01 13:20:32.188180031  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_Front: 602
2023-11-01 13:20:32.188235115  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_Pool: 627
2023-11-01 13:20:32.188284581  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_Patio: 634
2023-11-01 13:20:32.188339036  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_East_Back: 640
2023-11-01 13:20:32.188388389  [2023-11-01 13:20:29] frigate.app                    INFO    : Capture process started for McBroom_East_Front: 648
2023-11-01 13:20:32.188444625  [2023-11-01 13:20:28] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb:1
2023-11-01 13:20:32.188495921  [2023-11-01 13:20:32] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-11-01 13:20:34.206528954  [2023-11-01 13:20:34] frigate.video                  ERROR   : ShowLow_LivingRoom: Unable to read frames from ffmpeg process.
2023-11-01 13:20:34.206637522  [2023-11-01 13:20:34] frigate.video                  ERROR   : ShowLow_LivingRoom: ffmpeg process is not running. exiting capture thread...
2023-11-01 13:20:34.209641786  [2023-11-01 13:20:34] frigate.video                  ERROR   : ShowLow_Bedroom: Unable to read frames from ffmpeg process.
2023-11-01 13:20:34.209708448  [2023-11-01 13:20:34] frigate.video                  ERROR   : ShowLow_Bedroom: ffmpeg process is not running. exiting capture thread...
2023-11-01 13:20:34.984271716  [2023-11-01 13:20:34] frigate.video                  ERROR   : ShowLow_Front: Unable to read frames from ffmpeg process.
2023-11-01 13:20:34.984349777  [2023-11-01 13:20:34] frigate.video                  ERROR   : ShowLow_Front: ffmpeg process is not running. exiting capture thread...
2023-11-01 13:20:35.319926618  [2023-11-01 13:20:35] frigate.video                  ERROR   : Sigma_Tool_Room: Unable to read frames from ffmpeg process.
2023-11-01 13:20:35.320072196  [2023-11-01 13:20:35] frigate.video                  ERROR   : Sigma_Tool_Room: ffmpeg process is not running. exiting capture thread...
2023-11-01 13:20:35.708438915  [2023-11-01 13:20:35] frigate.video                  ERROR   : ShowLow_SideYard: Unable to read frames from ffmpeg process.
2023-11-01 13:20:35.708500262  [2023-11-01 13:20:35] frigate.video                  ERROR   : ShowLow_SideYard: ffmpeg process is not running. exiting capture thread...
2023-11-01 13:20:36.318825189  [2023-11-01 13:20:36] frigate.video                  ERROR   : Sigma_701_Dome: Unable to read frames from ffmpeg process.
2023-11-01 13:20:36.318919577  [2023-11-01 13:20:36] frigate.video                  ERROR   : Sigma_701_Dome: ffmpeg process is not running. exiting capture thread...
```

### FFprobe output from your camera

```shell
*
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

USB

### Network connection

Wired

### Camera make and model

Fiscam 9828P

### Any other information that may be helpful

xxxxxxxxxx@frigate:~$ lsusb
Bus 002 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 007: ID 18d1:9302 Google Inc. 
Bus 003 Device 006: ID 18d1:9302 Google Inc. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by indo419** [comment]
Frigate DOES NOT crash when I modify Frigate config file to:
detectors:
  coral1:
    type: edgetpu
    device: usb:1
#  coral2:
#    type: edgetpu
#    device: usb:1  

Frigate DOES crash when I modify Frigate config file to:
detectors:
  coral1:
    type: edgetpu
    device: usb:0
#  coral2:
#    type: edgetpu
#    device: usb:1  

Frigate DOES crash when I modify Frigate config file to:
detectors:
  coral1:
    type: edgetpu
    device: usb:0
  coral2:
    type: edgetpu
    device: usb:1  

I have 2 Edge TPUs connected via USB and prior to yesterday was running for several months without issue.

Could one of the Edge TPUs have failed?

**Comment by NickM-27** [comment]
The logs are saying that the coral is not found, what is `lsusb` showing?

**Comment by indo419** [comment]
Yesterday when failed:
xxxxxxxxxx@frigate:~$ lsusb
Bus 002 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 007: ID 18d1:9302 Google Inc.
Bus 003 Device 006: ID 18d1:9302 Google Inc.
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub


Today I unplugged/plugged TPUs and have new enumeration.
Both are working now.  Will see if they fail at some point.
xxxxxxxxxxxxxx@frigate:~$ lsusb
Bus 002 Device 002: ID 8087:8000 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 011: ID 18d1:9302 Google Inc. 
Bus 003 Device 009: ID 18d1:9302 Google Inc. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
