### ISSUE TITLE
[Config Support]: Camera Config Error

### ISSUE THREAD

**Issue by moomoo-ha** [blakeblackshear/frigate#8540]
### Describe the problem you are having

I am installing a Annke C800 camera using a Home Assistant Yellow server without the use of a Coral TPU. Having following the directions for the camera specific coding I keep receiving the following error:

### Version

0.12.1 

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.130
  user: mqtt-user
  password: #

cameras:
  front_house:
    ffmpeg:
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -tag:v hvc1 -bsf:v hevc_mp4toannexb -c:a aac
        rtmp: -c:v copy -c:a aac -f flv

      inputs:
        - path: rtsp://admin:$$$$$@192.168.1.@@@:554/Streaming/Channels/102
          roles:
            - detect
            - record
            - rtmp
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      width: 640 <---- update for your camera's resolution
      height: 480 <---- update for your camera's resolution
      fps: 5

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

record:
  enabled: True
  events:
    retain:
      default: 10
```

### Relevant log output

```shell
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2023-11-08 12:37:31.039102879  [INFO] Preparing go2rtc config...
2023-11-08 12:37:31.052477699  [INFO] Starting Frigate...
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-11-08 12:37:31.130787136  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-11-08 12:37:31.261377437  [INFO] Got IP address from supervisor: 192.168.1.130
2023-11-08 12:37:31.448209932  [WARN] Failed to get WebRTC port from supervisor
2023-11-08 12:37:32.338289635  [INFO] Starting go2rtc...
2023-11-08 12:37:32.558719065  12:37:32.558 INF go2rtc version 1.2.0 linux/arm64
2023-11-08 12:37:32.560292530  12:37:32.560 INF [api] listen addr=:1984
2023-11-08 12:37:32.561840235  12:37:32.561 INF [rtsp] listen addr=:8554
2023-11-08 12:37:32.563305886  12:37:32.563 INF [srtp] listen addr=:8443
2023-11-08 12:37:32.564543540  12:37:32.564 INF [webrtc] listen addr=:8555
2023-11-08 12:37:35.972807614  [2023-11-08 12:37:35] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-08 12:37:35.995182856  *************************************************************
2023-11-08 12:37:35.995311984  *************************************************************
2023-11-08 12:37:35.995409094  ***    Your config file is not valid!                     ***
2023-11-08 12:37:35.995507334  ***    Please check the docs at                           ***
2023-11-08 12:37:35.995600721  ***    https://docs.frigate.video/configuration/index     ***
2023-11-08 12:37:35.995695943  *************************************************************
2023-11-08 12:37:35.995789997  *************************************************************
2023-11-08 12:37:35.995889163  ***    Config Validation Errors                           ***
2023-11-08 12:37:35.995992791  *************************************************************
2023-11-08 12:37:35.996525119  2 validation errors for FrigateConfig
2023-11-08 12:37:35.996534841  cameras -> front_house -> detect -> height
2023-11-08 12:37:35.996537156    value is not a valid integer (type=type_error.integer)
2023-11-08 12:37:35.996548693  cameras -> front_house -> detect -> width
2023-11-08 12:37:35.996635951    value is not a valid integer (type=type_error.integer)
2023-11-08 12:37:36.003187214  Traceback (most recent call last):
2023-11-08 12:37:36.003198029    File "/opt/frigate/frigate/app.py", line 351, in start
2023-11-08 12:37:36.003200251      self.init_config()
2023-11-08 12:37:36.003202769    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-11-08 12:37:36.003205010      user_config = FrigateConfig.parse_file(config_file)
2023-11-08 12:37:36.003209547    File "/opt/frigate/frigate/config.py", line 1078, in parse_file
2023-11-08 12:37:36.003288380      return cls.parse_obj(config)
2023-11-08 12:37:36.003292120    File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 526, in parse_obj
2023-11-08 12:37:36.003295380      return cls(**obj)
2023-11-08 12:37:36.003298120    File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 341, in __init__
2023-11-08 12:37:36.003300009      raise validation_error
2023-11-08 12:37:36.003302528  pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
2023-11-08 12:37:36.003387656  cameras -> front_house -> detect -> height
2023-11-08 12:37:36.003390897    value is not a valid integer (type=type_error.integer)
2023-11-08 12:37:36.003394767  cameras -> front_house -> detect -> width
2023-11-08 12:37:36.003396916    value is not a valid integer (type=type_error.integer)
2023-11-08 12:37:36.003545747  
2023-11-08 12:37:36.003650246  *************************************************************
2023-11-08 12:37:36.003750282  ***    End Config Validation Errors                       ***
2023-11-08 12:37:36.003844244  *************************************************************
2023-11-08 12:37:37.564755670  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-11-08 12:37:37.626925428  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-11-08 12:37:37.684403626  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2023-11-08 12:37:37.700932541  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-11-08 12:37:37.717569381  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
You have `<---- update for your camera's resolution` without a `#` which makes it a comment. In this case you are trying to send that whole string as part of the width of the camera

**Comment by moomoo-ha** [comment]
> You have `<---- update for your camera's resolution` without a `#` which makes it a comment. In this case you are trying to send that whole string as part of the width of the camera

That's done it thank you! 

Separate question - if I wanted to add the main stream for recording as this is currently only using Sub. How would I do that?

**Comment by NickM-27** [comment]
This is shown in the docs https://docs.frigate.video/guides/getting_started#step-6-enable-recording-andor-snapshots
