### ISSUE TITLE
[HW Accel Support]: hwaccel_args Nvidia not working

### ISSUE THREAD

**Issue by wfio** [blakeblackshear/frigate#8603]
### Describe the problem you are having

I've implemented the accelerated hardware arguments for an Nvidia T400 (4gb) that I have passed to the unRaid docker container for Frigate. I passed it by providing the GUID. I have Nvidia drivers installed and GPU Statistics.

When I turn on the camera after enabling the hwaccel_args for Nvidia, I get some wild messages about cannot load lib.cuda and a bunch of other stuff I don't recognize. For example, it indicates that nvidia-smi is missing but it clearly is not because I can see it running in 'htop' on unRaid. And GPU statistics is working when it shows Plex transcoding a movie and using the GPU.

Affending code snippet:

```
ffmpeg:
  hwaccel_args: preset-nvidia-h264
```

### Version

0.12.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.xx.xxx

#birdseye-params

detect:
  width: 896
  height: 672
  fps: 5
  stationary:
    interval: 10

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264
 
cameras:
  doorbell:
    enabled: true
    ffmpeg:
      
      inputs:
        - path: rtsp://uname:pwd@192.168.xx.xxx:554/h264Preview_01_main
          input_args: preset-rtsp-restream
          roles:
          - record
        - path: rtsp://uname:pwd@192.168.xx.xxx:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
          
          roles:
          - detect
      output_args:
        record: preset-record-generic-audio-aac

#recording parameters
record:
     enabled: true
     retain:
       days: 30
     events:
       pre_capture: 7
       post_capture: 7
       objects:
         - person
         - cat
         - dog
       retain:
         default: 14

#object parameters
objects:
     track:
       - person
       - dog
       - cat
       - car
        
     filters:
      person:
        threshold: 0.70
      car:
        threshold: 0.70
```

### docker-compose file or Docker CLI command

```yaml
/boot/config/plugins/dockerMan/templates-user# cat my-frigate.xml 
<?xml version="1.0"?>
<Container version="2">
  <Name>frigate</Name>
  <Repository>ghcr.io/blakeblackshear/frigate:stable</Repository>
  <Registry>https://hub.docker.com/r/blakeblackshear/frigate/</Registry>
  <Network>bridge</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support>https://forums.unraid.net/topic/98064-support-blakeblackshear-frigate/</Support>
  <Project>https://frigate.video/</Project>
  <Overview>A complete and local NVR designed for Home Assistant with AI object detection. Uses OpenCV and Tensorflow to perform realtime object detection locally for IP cameras.&#xD;
&#xD;
You cas use a integrated or dedicated GPU (Intel/AMD/Nvidia) to perform the image decoding of the input streams of your cameras.&#xD;
&#xD;
Optionally (but highly recommended), you can use multiple devices to perform the object detetion, such as a Google Coral Accelerator Nvidia GPU, OpenVINO (Intel GPU) and Intel NCS2 VPU&#xD;
&#xD;
See the documentation for more details about your specific hardware and needs (https://docs.frigate.video/). This is a general templeate that aims to give a fast deoplyment for every user so check all the options carefully and remove all the configurations that you are not going to use.</Overview>
  <Category>HomeAutomation: Security:</Category>
  <WebUI>http://[IP]:[PORT:5000]</WebUI>
  <TemplateURL>https://gitlab.com/yayitazale/unraid-templates/-/raw/main/yayitazale/frigate.xml</TemplateURL>
  <Icon>https://raw.githubusercontent.com/yayitazale/unraid-templates/main/frigate.png</Icon>
  <ExtraParams>--shm-size=256mb --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 --restart unless-stopped</ExtraParams>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1699914726</DateInstalled>
  <DonateText>If you like my work please consider Donating.</DonateText>
  <DonateLink>https://paypal.me/JosebaEgiaLarrinaga</DonateLink>
  <Requires>&amp;lt;br&amp;gt;- A valid config.yml file must exist in the config directory to startup the container.&amp;lt;br&amp;gt;- If you are using a Coral Detector, you must set the container to privileged mode under advanced view&amp;lt;br&amp;gt;- If you are using a PCI Coral instead of a USB one, you must install first the needed drivers going to the CA app and searching for Coral-Driver (thanks to @ich777)&amp;lt;br&amp;gt;- If you want to use a NVidia card to image decoding and/or detection, you must first install the drivers from CA app (thanks to @ich777), add &amp;amp;quot;--runtime=nvidia&amp;amp;quot; as extra parameter under advanced view and set the &amp;amp;quot;Nvidia Visible Devices&amp;amp;quot; variable with your &amp;amp;quot;GPU UUID&amp;amp;quot; as the value.&amp;lt;br&amp;gt;- If you want to use the NVidia TensorRT Detector, you have to create the models using the &amp;amp;quot;tensorrt-models&amp;amp;quot; app from the CA app and select the correspondig branch.&amp;lt;br&amp;gt;- If you want to use a AMD GPU to image decoding you must change driver to &amp;amp;quot;radeonsi&amp;amp;quot;&amp;lt;br&amp;gt;- With some of the Intel processors, like the J4125, the default driver &amp;amp;quot;iHD&amp;amp;quot; doesn't seem to work correctly for hardware acceleration. You may need to change the driver to &amp;amp;quot;i965&amp;amp;quot;&amp;lt;br&amp;gt;- If you want to use a NCS2 as detector you have to add &amp;amp;quot;--device-cgroup-rule='c 189:\* rmw'&amp;amp;quot; as extra parameter under advanced view and install the &amp;amp;quot;udev rule&amp;amp;quot; in the unraid host.</Requires>
  <Config Name="Config Path" Target="/config" Default="/mnt/cache/appdata/frigate" Mode="rw" Description="" Type="Path" Display="always" Required="true" Mask="false">/mnt/cache/appdata/frigate</Config>
  <Config Name="Media path" Target="/media/frigate" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="true" Mask="false">/mnt/user/Media/frigate</Config>
  <Config Name="HTTP port" Target="5000" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="true" Mask="false">5000</Config>
  <Config Name="RTSP port" Target="8554" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="true" Mask="false">8554</Config>
  <Config Name="Frigate RTSP Password" Target="FRIGATE_RTSP_PASSWORD" Default="" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">enterpassword</Config>
  <Config Name="Frigate+ API key" Target="PLUS_API_KEY" Default="" Mode="" Description="Optional: Enter the frigate+ API key or remove this if you are not using it" Type="Variable" Display="always" Required="false" Mask="false"/>
  <Config Name="Coral TPU/NCS2 Mapping" Target="/dev/bus/usb" Default="" Mode="" Description="Use /dev/bus/usb for USB devices and /dev/apex_0 for PCIe devices (you must install the drivers first for PCIe devices). Remove this if you are not using it." Type="Device" Display="always" Required="false" Mask="false">/dev/bus/usb</Config>
  <Config Name="Nvidia Visible Devices" Target="NVIDIA_VISIBLE_DEVICES" Default="" Mode="" Description="This info can be found in the NVidia driver plugin.. Only for Nvidia GPU decoding and/or detection. Remove this if you are not using it." Type="Variable" Display="always" Required="false" Mask="false">GPU-xxxxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx</Config>
  <Config Name="Nvidia Driver Capabilities" Target="NVIDIA_DRIVER_CAPABILITIES" Default="" Mode="" Description="Only for Nvidia GPU decoding and/or detection. Remove this if you are not using it." Type="Variable" Display="always" Required="false" Mask="false">compute,utility,video</Config>
  <Config Name="TRT-Models path" Target="/trt-models" Default="" Mode="ro" Description="Only for TensorRT, remove this if you are not using it" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/trt-models</Config>
  <Config Name="go2rtc TCP port" Target="8555" Default="" Mode="tcp" Description="If you are not going to use MSE/WebRCT you can remove all the WebRTC entrys" Type="Port" Display="always" Required="false" Mask="false">8555</Config>
  <Config Name="go2rtc UDP port" Target="8555" Default="" Mode="udp" Description="If you are not going to use MSE/WebRCT you can remove all the WebRTC entrys" Type="Port" Display="always" Required="false" Mask="false">8555</Config>
  <Config Name="go2rtc server port" Target="1984" Default="" Mode="tcp" Description="For Home Assistant WebRTC integration. Remove this if you are not using it." Type="Port" Display="always" Required="false" Mask="false">1984</Config>
  <Config Name="Localtime" Target="/etc/localtime" Default="" Mode="rw" Description="" Type="Path" Display="advanced-hide" Required="true" Mask="false">/etc/localtime</Config>
</Container>

```

### Relevant log output

```shell
#####frigate log#####
-11-13 18:38:06.720084362  FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'
2023-11-13 18:38:06.723198943  [2023-11-13 18:38:06] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected
2023-11-13 18:38:10.447601051  [2023-11-13 18:38:10] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2023-11-13 18:38:10.447693590  [2023-11-13 18:38:10] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-13 18:38:10.447739260  [2023-11-13 18:38:10] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x56330e459f80] Cannot load libcuda.so.1
2023-11-13 18:38:10.447857317  [2023-11-13 18:38:10] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x56330e459f80] Could not dynamically load CUDA
2023-11-13 18:38:10.447872083  [2023-11-13 18:38:10] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -1.
2023-11-13 18:38:10.447983643  [2023-11-13 18:38:10] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x56330e4584c0] No device available for decoder: device type cuda needed for codec h264.
2023-11-13 18:38:10.447985873  [2023-11-13 18:38:10] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:38:13.716714164  [2023-11-13 18:38:13] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:38:13.716737556  [2023-11-13 18:38:13] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:38:20.461549794  [2023-11-13 18:38:20] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2023-11-13 18:38:20.461805686  [2023-11-13 18:38:20] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-13 18:38:20.461980819  [2023-11-13 18:38:20] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x564babdbd4c0] Cannot load libcuda.so.1
2023-11-13 18:38:20.462258950  [2023-11-13 18:38:20] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x564babdbd4c0] Could not dynamically load CUDA
2023-11-13 18:38:20.476324194  [2023-11-13 18:38:20] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -1.
2023-11-13 18:38:20.476708142  [2023-11-13 18:38:20] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x564babdbce80] No device available for decoder: device type cuda needed for codec h264.
2023-11-13 18:38:20.476856623  [2023-11-13 18:38:20] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:38:23.600848700  [2023-11-13 18:38:23] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:38:23.600852003  [2023-11-13 18:38:23] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:38:30.487777225  [2023-11-13 18:38:30] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2023-11-13 18:38:30.488020632  [2023-11-13 18:38:30] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-13 18:38:30.488325212  [2023-11-13 18:38:30] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x5575f74ba4c0] Cannot load libcuda.so.1
2023-11-13 18:38:30.488479471  [2023-11-13 18:38:30] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x5575f74ba4c0] Could not dynamically load CUDA
2023-11-13 18:38:30.488673099  [2023-11-13 18:38:30] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -1.
2023-11-13 18:38:30.488834208  [2023-11-13 18:38:30] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x5575f74c9fc0] No device available for decoder: device type cuda needed for codec h264.
2023-11-13 18:38:30.489013084  [2023-11-13 18:38:30] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:38:33.594173136  [2023-11-13 18:38:33] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:38:33.594276719  [2023-11-13 18:38:33] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:38:40.531086110  [2023-11-13 18:38:40] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2023-11-13 18:38:40.531202140  [2023-11-13 18:38:40] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-13 18:38:40.531315944  [2023-11-13 18:38:40] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x561ad65ff000] Cannot load libcuda.so.1
2023-11-13 18:38:40.531361563  [2023-11-13 18:38:40] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x561ad65ff000] Could not dynamically load CUDA
2023-11-13 18:38:40.531434032  [2023-11-13 18:38:40] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -1.
2023-11-13 18:38:40.531526864  [2023-11-13 18:38:40] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x561ad65f3e80] No device available for decoder: device type cuda needed for codec h264.
2023-11-13 18:38:40.531613040  [2023-11-13 18:38:40] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:38:43.559970805  [2023-11-13 18:38:43] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:38:43.560067652  [2023-11-13 18:38:43] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:38:50.547655408  [2023-11-13 18:38:50] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2023-11-13 18:38:50.547728858  [2023-11-13 18:38:50] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-13 18:38:50.547815331  [2023-11-13 18:38:50] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x560f6d523400] Cannot load libcuda.so.1
2023-11-13 18:38:50.547881582  [2023-11-13 18:38:50] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x560f6d523400] Could not dynamically load CUDA
2023-11-13 18:38:50.547909240  [2023-11-13 18:38:50] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -1.
2023-11-13 18:38:50.547946601  [2023-11-13 18:38:50] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x560f6d3a9e80] No device available for decoder: device type cuda needed for codec h264.
2023-11-13 18:38:50.547981838  [2023-11-13 18:38:50] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:38:53.588325052  [2023-11-13 18:38:53] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:38:53.588537234  [2023-11-13 18:38:53] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:39:00.556093991  [2023-11-13 18:39:00] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2023-11-13 18:39:00.556400295  [2023-11-13 18:39:00] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-13 18:39:00.556541661  [2023-11-13 18:39:00] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x557b46b2b6c0] Cannot load libcuda.so.1
2023-11-13 18:39:00.556782197  [2023-11-13 18:39:00] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x557b46b2b6c0] Could not dynamically load CUDA
2023-11-13 18:39:00.556956649  [2023-11-13 18:39:00] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -1.
2023-11-13 18:39:00.557148608  [2023-11-13 18:39:00] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x557b46b20e80] No device available for decoder: device type cuda needed for codec h264.
2023-11-13 18:39:00.557361229  [2023-11-13 18:39:00] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:39:04.551272231  [2023-11-13 18:39:04] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:39:04.551345504  [2023-11-13 18:39:04] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:39:09.931727566  [2023-11-13 18:39:09] asyncio                        ERROR   : Task exception was never retrieved
2023-11-13 18:39:09.931739529  future: <Task finished name='Task-8' coro=<set_gpu_stats() done, defined at /opt/frigate/frigate/stats.py:120> exception=FileNotFoundError(2, 'No such file or directory')>
2023-11-13 18:39:09.931744557  Traceback (most recent call last):
2023-11-13 18:39:09.931749763    File "/opt/frigate/frigate/stats.py", line 152, in set_gpu_stats
2023-11-13 18:39:09.931754395      nvidia_usage = get_nvidia_gpu_stats()
2023-11-13 18:39:09.931759151    File "/opt/frigate/frigate/util.py", line 940, in get_nvidia_gpu_stats
2023-11-13 18:39:09.931763008      p = sp.run(
2023-11-13 18:39:09.931767314    File "/usr/lib/python3.9/subprocess.py", line 505, in run
2023-11-13 18:39:09.931771548      with Popen(*popenargs, **kwargs) as process:
2023-11-13 18:39:09.931775933    File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
2023-11-13 18:39:09.931780110      self._execute_child(args, executable, preexec_fn, close_fds,
2023-11-13 18:39:09.931784850    File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
2023-11-13 18:39:09.931789411      raise child_exception_type(errno_num, err_msg, err_filename)


####docker container log######
```2023-11-13 18:41:00.893499419  [2023-11-13 18:41:00] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:41:04.536604542  [2023-11-13 18:41:04] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:41:04.536698003  [2023-11-13 18:41:04] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:41:10.903531505  [2023-11-13 18:41:10] watchdog.doorbell              ERROR   : Ffmpeg process crashed unexpectedly for doorbell.
2023-11-13 18:41:10.909706453  [2023-11-13 18:41:10] watchdog.doorbell              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-11-13 18:41:10.909732793  [2023-11-13 18:41:10] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x55ac723c0140] Cannot load libcuda.so.1
2023-11-13 18:41:10.909787001  [2023-11-13 18:41:10] ffmpeg.doorbell.detect         ERROR   : [AVHWDeviceContext @ 0x55ac723c0140] Could not dynamically load CUDA
2023-11-13 18:41:10.909920723  [2023-11-13 18:41:10] ffmpeg.doorbell.detect         ERROR   : Device creation failed: -1.
2023-11-13 18:41:10.910030378  [2023-11-13 18:41:10] ffmpeg.doorbell.detect         ERROR   : [h264 @ 0x55ac72258d40] No device available for decoder: device type cuda needed for codec h264.
2023-11-13 18:41:10.910032628  [2023-11-13 18:41:10] ffmpeg.doorbell.detect         ERROR   : Device setup failed for decoder on input stream #0:0 : Operation not permitted
2023-11-13 18:41:14.533610036  [2023-11-13 18:41:14] frigate.video                  ERROR   : doorbell: Unable to read frames from ffmpeg process.
2023-11-13 18:41:14.533741899  [2023-11-13 18:41:14] frigate.video                  ERROR   : doorbell: ffmpeg process is not running. exiting capture thread...
2023-11-13 18:41:16.400010094  [2023-11-13 18:41:16] asyncio                        ERROR   : Task exception was never retrieved
2023-11-13 18:41:16.400019040  future: <Task finished name='Task-14' coro=<set_gpu_stats() done, defined at /opt/frigate/frigate/stats.py:120> exception=FileNotFoundError(2, 'No such file or directory')>
2023-11-13 18:41:16.400022617  Traceback (most recent call last):
2023-11-13 18:41:16.400026243    File "/opt/frigate/frigate/stats.py", line 152, in set_gpu_stats
2023-11-13 18:41:16.400029540      nvidia_usage = get_nvidia_gpu_stats()
2023-11-13 18:41:16.400032811    File "/opt/frigate/frigate/util.py", line 940, in get_nvidia_gpu_stats
2023-11-13 18:41:16.400035598      p = sp.run(
2023-11-13 18:41:16.400038651    File "/usr/lib/python3.9/subprocess.py", line 505, in run
2023-11-13 18:41:16.400041590      with Popen(*popenargs, **kwargs) as process:
2023-11-13 18:41:16.400044781    File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
2023-11-13 18:41:16.400047831      self._execute_child(args, executable, preexec_fn, close_fds,
2023-11-13 18:41:16.400050895    File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
2023-11-13 18:41:16.400053947      raise child_exception_type(errno_num, err_msg, err_filename)
2023-11-13 18:41:16.400057193  FileNotFoundError: [Errno 2] No such file or directory: 'nvidia-smi'
2023-11-13 18:41:16.406266898  [2023-11-13 18:41:16] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected```
```

### FFprobe output from your camera

```shell
# ffprobe http://192.168.xx.xxx                             
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
http://192.168.xx.xxx: Invalid data found when processing input
```

### Operating system

UNRAID

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Reolink PoE Doorbell Cam

### Any other information that may be helpful

https://reolink.com/product/reolink-video-doorbell/

**Comment by NickM-27** [comment]
what is your unraid CLI command?

**Comment by wfio** [comment]
Apologies - I'm not sure what you mean.

**Comment by NickM-27** [comment]
unraid will show you the cli command when you save the container config, we need to see this to see what is going on.

**Comment by wfio** [comment]
I was only able to find an xml under /boot/conf/...

**Comment by NickM-27** [comment]
Your extra arguments is missing the `--gpus=all` like the docs say is needed.

**Comment by NickM-27** [comment]
runtime nvidia is old and not recommended anymore. The parameter that should be added is `--gpus=all` like it shows in https://docs.frigate.video/configuration/hardware_acceleration#docker-run-cli---nvidia-gpu

**Comment by wfio** [comment]
I think that sorted it. I now see the Frigate logo in GPU Statistics. Now I just need to figure out why I'm getting this error:

[2023-11-14 09:15:34] frigate.comms.mqtt             ERROR   : Unable to publish to doorbell/all: client is not connected

It seems like it's a very common error but I'm not seeing solutions that make sense in my situation.
