### ISSUE TITLE
[Config Support]: config.yml is a directory

### ISSUE THREAD

**Issue by matsob0123** [blakeblackshear/frigate#8670]
### Describe the problem you are having

I think that my config is ok but in the logs it says that my config is a directory but it`s not

### Version

idk cuz it won`t load (the lastest on 11/19/2023

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.124:1885
  port: 1885
  topic_prefix: frigate
  client_id: frigate
cameras:
  ipcam:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.142:8080/h264_aac.sdp
          roles:
            - rtmp
            - detect
birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
  # Optional: Restream birdseye via RTSP (default: shown below)
  # NOTE: Enabling this will set birdseye to run 24/7 which may increase CPU usage somewhat.
  restream: False
  # Optional: Width of the output resolution (default: shown below)
  width: 1920
  # Optional: Height of the output resolution (default: shown below)
  height: 1080
  # Optional: Encoding quality of the mpeg1 feed (default: shown below)
  # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
  quality: 8
  # Optional: Mode of the view. Available options are: objects, motion, and continuous
  #   objects - cameras are included if they have had a tracked object within the last 30 seconds
  #   motion - cameras are included if motion was detected in the last 30 seconds
  #   continuous - all cameras are included always
  mode: objects 
rtmp:
  # Optional: Enable the RTMP stream (default: False)
  enabled: true
mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: True
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: True
      # Optional: crop the snapshot (default: shown below)
      crop: True
      # Optional: height to resize the snapshot to (default: shown below)
      height: 270
      # Optional: jpeg encode quality (default: shown below)
      quality: 70
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      required_zones: []

ui:
      # Optional: Adjust sort order of cameras in the UI. Larger numbers come later (default: shown below)
      # By default the cameras are sorted alphabetically.
      order: 0
      # Optional: Whether or not to show the camera in the Frigate UI (default: shown below)
      dashboard: True
telemetry:
  # Optional: Enable the latest version outbound check (default: shown below)
  # NOTE: If you use the HomeAssistant integration, disabling this will prevent it from reporting new versions
  version_check: True
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-11-19 15:26:45.001527759  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-11-19 15:26:46.007997019  [INFO] Preparing go2rtc config...
2023-11-19 15:26:46.041484621  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-11-19 15:26:46.057443868  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-11-19 15:26:46.103976526  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2023-11-19 15:26:46.114841384  [INFO] The go2rtc service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-linux-init-shutdown: fatal: unable to talk to shutdownd: Operation not permitted
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
2023-11-19 15:26:51.343491594  [INFO] Preparing go2rtc config...
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-11-19 15:26:51.354950756  [INFO] Starting Frigate...
2023-11-19 15:26:51.355398100  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-11-19 15:26:51.738970854  [INFO] The go2rtc service exited with code 1 (by signal 0)
2023-11-19 15:26:52.745850098  [INFO] Preparing go2rtc config...
2023-11-19 15:26:53.035995923  *************************************************************
2023-11-19 15:26:53.036067734  *************************************************************
2023-11-19 15:26:53.036261438  ***    Your config file is not valid!                     ***
2023-11-19 15:26:53.036357908  ***    Please check the docs at                           ***
2023-11-19 15:26:53.036450796  ***    https://docs.frigate.video/configuration/index     ***
2023-11-19 15:26:53.036541709  *************************************************************
2023-11-19 15:26:53.036592227  *************************************************************
2023-11-19 15:26:53.036669502  ***    Config Validation Errors                           ***
2023-11-19 15:26:53.036752521  *************************************************************
2023-11-19 15:26:53.036808548  [Errno 21] Is a directory: '/config/config.yml'
2023-11-19 15:26:53.037692965  [2023-11-19 15:26:53] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-19 15:26:53.038248695  Traceback (most recent call last):
2023-11-19 15:26:53.038254330    File "/opt/frigate/frigate/app.py", line 351, in start
2023-11-19 15:26:53.038260604      self.init_config()
2023-11-19 15:26:53.038267525    File "/opt/frigate/frigate/app.py", line 80, in init_config
2023-11-19 15:26:53.038271746      user_config = FrigateConfig.parse_file(config_file)
2023-11-19 15:26:53.038275399    File "/opt/frigate/frigate/config.py", line 1070, in parse_file
2023-11-19 15:26:53.038316320      with open(config_file) as f:
2023-11-19 15:26:53.038319988  IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-11-19 15:26:53.038324068  
2023-11-19 15:26:53.038327440  *************************************************************
2023-11-19 15:26:53.038330665  ***    End Config Validation Errors                       ***
2023-11-19 15:26:53.038353965  *************************************************************
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 23, in <module>
    with open(config_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/config/config.yml'
2023-11-19 15:26:53.116699586  [INFO] The go2rtc service exited with code 1 (by signal 0)
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Any other information that may be helpful

idk i`m new to this

**Comment by NickM-27** [comment]
What is your docker compose? This error happens when the volume mapping is done incorrectly and docker creates a directory

**Comment by matsob0123** [comment]
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    devices:
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config/cf.yml:/config/config.yml:ro
      - /frigate/media:/media/frigate
      - /frigate/db:/db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

**Comment by NickM-27** [comment]
can you use the command line interface to go to the cf.yml file and run `pwd` then show what the output is?

**Comment by matsob0123** [comment]
can i get more instructions for this ?

**Comment by RoelAdriaans** [comment]
With ` /frigate/config/cf.yml:/config/config.yml:ro` it expects that `/frigate/config/cf.yml` on your local machine is a file.. 
Is that really the location of your config file?

**Comment by Trashmee** [comment]
Can you post

```
docker exec -it frigate bash -c "ls -lash /config/"
```

**Comment by matsob0123** [comment]
can somebody close this?   it works now
