### ISSUE TITLE
[Support]: No EdgeTPU detected when using a custom model from Frigate+

### ISSUE THREAD

**Issue by AlasdairH** [blakeblackshear/frigate#8678]
### Describe the problem you are having

When trying to use a model from Frigate+ for the first time. My Coral TPU is detected, and then not detected and an error appears in the logs.
```
2023-11-20 08:11:14.794015757  [2023-11-20 08:11:14] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-11-20 08:11:14.794039017  Process detector:coral:
2023-11-20 08:11:14.795029097  [2023-11-20 08:11:14] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-11-20 08:11:14.801646398  Traceback (most recent call last):
2023-11-20 08:11:14.801815442    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-11-20 08:11:14.801829506      self.run()
2023-11-20 08:11:14.801845370    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-11-20 08:11:14.801873612      self._target(*self._args, **self._kwargs)
2023-11-20 08:11:14.801968252    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-11-20 08:11:14.801983974      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-11-20 08:11:14.801999711    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-11-20 08:11:14.802013006      self.detect_api = create_detector(detector_config)
2023-11-20 08:11:14.802024807    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-11-20 08:11:14.802245403      return api(detector_config)
2023-11-20 08:11:14.802285465    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 39, in __init__
2023-11-20 08:11:14.802306280      self.interpreter = Interpreter(
2023-11-20 08:11:14.802321917    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
2023-11-20 08:11:14.802338759      _interpreter_wrapper.CreateWrapperFromFile(
2023-11-20 08:11:14.802519729  ValueError: Could not open 'plus://<id>'.
```

Without the custom model enabled in the config, my TPU runs just fine. Any ideas what could be going wrong?

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  # Required: host name
  host: 192.168.1.64
  # Optional: port (default: shown below)
  port: 1883

detect:
  enabled: True

rtmp:
  enabled: False

ffmpeg:
  hwaccel_args: preset-vaapi

go2rtc:
  streams:
    porch: 
      - "ffmpeg:http://192.168.1.224/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#video=copy#audio=copy#audio=opus"
    porch_sub: 
      - "ffmpeg:http://192.168.1.224/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=user&password=pass"

cameras:
  porch:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/porch?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/porch_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect
    objects:
      filters:
        car:
          mask:
            - 342,308,504,313,585,312,672,310,726,344,674,369,586,382,479,382,330,387,118,384,85,434,0,425,0,259,134,289
            - 823,720,0,720,0,502,267,456,473,465,601,478,802,490,817,574
        person:
          mask:
            - 619,343,634,343,630,384,616,383
      track:
        - person
        - bicycle
        - car
        - cat
        - dog
    record:
      enabled: True
      retain:
        days: 1
        mode: all
      events:
        pre_capture: 10
        post_capture: 5
        objects:
          - person
          - bicycle
          - car
          - cat
          - dog
        retain:
          default: 3
          mode: active_objects
          objects:
            car: 1
    zones:
      driveway:
        coordinates: 823,720,0,720,0,502,267,456,473,465,601,478,802,490,817,574
      driveway_entrance:
        coordinates: 562,430,670,433,622,488,481,473,308,450,389,437
      path:
        coordinates: 782,440,727,720,310,720,671,433
    motion:
      mask:
        - 1280,720,954,720,958,688,965,624,1011,551,1063,436,1133,411,1280,399
        - 0,720,558,720,543,664,0,661

detectors:
  coral:
    type: edgetpu
    device: usb

model:
  path: plus://<the model ID copied from F+>
```

### Relevant log output

```shell
2023-11-20 08:11:10.071230583  [INFO] Starting Frigate...
2023-11-20 08:11:11.527188520  [2023-11-20 08:11:11] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-11-20 08:11:11.553815342  [2023-11-20 08:11:11] peewee_migrate                 INFO    : Starting migrations
2023-11-20 08:11:11.558543623  [2023-11-20 08:11:11] peewee_migrate                 INFO    : There is nothing to migrate
2023-11-20 08:11:11.579192517  [2023-11-20 08:11:11] detector.coral                 INFO    : Starting detection process: 321
2023-11-20 08:11:14.788562416  [2023-11-20 08:11:11] frigate.app                    INFO    : Output process started: 323
2023-11-20 08:11:14.789516080  [2023-11-20 08:11:11] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-11-20 08:11:14.790072640  [2023-11-20 08:11:11] frigate.comms.dispatcher       INFO    : Turning on snapshots for porch
2023-11-20 08:11:14.790563662  [2023-11-20 08:11:11] frigate.app                    INFO    : Camera processor started for porch: 330
2023-11-20 08:11:14.791179970  [2023-11-20 08:11:11] frigate.app                    INFO    : Capture process started for porch: 331
2023-11-20 08:11:14.794015757  [2023-11-20 08:11:14] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-11-20 08:11:14.794039017  Process detector:coral:
2023-11-20 08:11:14.795029097  [2023-11-20 08:11:14] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-11-20 08:11:14.801646398  Traceback (most recent call last):
2023-11-20 08:11:14.801815442    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-11-20 08:11:14.801829506      self.run()
2023-11-20 08:11:14.801845370    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-11-20 08:11:14.801873612      self._target(*self._args, **self._kwargs)
2023-11-20 08:11:14.801968252    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-11-20 08:11:14.801983974      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-11-20 08:11:14.801999711    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-11-20 08:11:14.802013006      self.detect_api = create_detector(detector_config)
2023-11-20 08:11:14.802024807    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-11-20 08:11:14.802245403      return api(detector_config)
2023-11-20 08:11:14.802285465    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 39, in __init__
2023-11-20 08:11:14.802306280      self.interpreter = Interpreter(
2023-11-20 08:11:14.802321917    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 348, in __init__
2023-11-20 08:11:14.802338759      _interpreter_wrapper.CreateWrapperFromFile(
2023-11-20 08:11:14.802519729  ValueError: Could not open 'plus://<id>'.
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1920,"width":2560},{"avg_frame_rate":"0/0","codec_long_name":"AAC(AdvancedAudioCoding)"}]}},{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"20/1","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":672,"width":896}]}}]
```

### Frigate stats

```json
With `model` defined:
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"2.1"},"1":{"cpu":"0.0","mem":"0.0"},"104":{"cpu":"0.0","mem":"0.0"},"105":{"cpu":"1.7","mem":"2.0"},"117":{"cpu":"0.0","mem":"0.2"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"138":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"281":{"cpu":"0.0","mem":"1.0"},"287":{"cpu":"0.3","mem":"0.1"},"288":{"cpu":"0.0","mem":"0.0"},"29":{"cpu":"0.0","mem":"0.0"},"290":{"cpu":"0.0","mem":"1.1"},"296":{"cpu":"2.3","mem":"1.2"},"297":{"cpu":"0.0","mem":"0.2"},"298":{"cpu":"5.3","mem":"1.1"},"30":{"cpu":"0.0","mem":"0.0"},"300":{"cpu":"0.0","mem":"0.2"},"303":{"cpu":"5.6","mem":"0.4"},"309":{"cpu":"3.0","mem":"0.3"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"2.0","mem":"0.3"},"311":{"cpu":"11.0","mem":"0.4"},"32":{"cpu":"0.0","mem":"0.0"},"360":{"cpu":"0.0","mem":"0.0"},"363":{"cpu":"0.0","mem":"0.0"},"369":{"cpu":"0.3","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"5.3","mem":"0.3"},"MiB":{"cpu":"5257.2","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"1"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":288}},"gpu_usages":{"intel-vaapi":{"gpu":"1.0 %","mem":"- %"}},"porch":{"camera_fps":2.33,"capture_pid":298,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":303,"pid":296,"process_fps":0.0,"skipped_fps":0.0},"service":{"last_updated":1700468483,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":61.0,"mount_type":"tmpfs","total":67.1,"used":6.2},"/media/frigate/clips":{"free":418086.7,"mount_type":"ext4","total":491106.5,"used":47997.7},"/media/frigate/recordings":{"free":418086.7,"mount_type":"ext4","total":491106.5,"used":47997.7},"/tmp/cache":{"free":81790.0,"mount_type":"overlay","total":124896.6,"used":36714.9}},"temperatures":{},"uptime":14,"version":"0.12.1-367d724"}}

Without `model` defined:
{"cpu_usages":{"%Cpu(s):":{"cpu":"id,","mem":"0.4"},"1":{"cpu":"0.0","mem":"0.0"},"101":{"cpu":"2.3","mem":"1.7"},"104":{"cpu":"0.0","mem":"0.0"},"115":{"cpu":"0.0","mem":"0.2"},"119":{"cpu":"0.0","mem":"0.0"},"134":{"cpu":"0.0","mem":"0.1"},"135":{"cpu":"0.0","mem":"0.1"},"136":{"cpu":"0.0","mem":"0.1"},"137":{"cpu":"0.0","mem":"0.1"},"15":{"cpu":"0.0","mem":"0.0"},"16":{"cpu":"0.0","mem":"0.0"},"24":{"cpu":"0.0","mem":"0.0"},"25":{"cpu":"0.0","mem":"0.0"},"26":{"cpu":"0.0","mem":"0.0"},"27":{"cpu":"0.0","mem":"0.0"},"28":{"cpu":"0.0","mem":"0.0"},"282":{"cpu":"0.0","mem":"1.0"},"288":{"cpu":"0.0","mem":"0.1"},"289":{"cpu":"0.3","mem":"1.3"},"29":{"cpu":"0.0","mem":"0.0"},"292":{"cpu":"0.0","mem":"1.1"},"297":{"cpu":"0.0","mem":"0.2"},"298":{"cpu":"0.0","mem":"1.1"},"299":{"cpu":"0.0","mem":"1.1"},"30":{"cpu":"0.0","mem":"0.0"},"301":{"cpu":"0.0","mem":"0.2"},"307":{"cpu":"1.3","mem":"0.3"},"31":{"cpu":"0.0","mem":"0.0"},"310":{"cpu":"5.6","mem":"0.6"},"311":{"cpu":"1.7","mem":"0.3"},"312":{"cpu":"7.3","mem":"0.4"},"32":{"cpu":"0.0","mem":"0.0"},"327":{"cpu":"0.3","mem":"0.0"},"329":{"cpu":"0.0","mem":"0.0"},"330":{"cpu":"53.3","mem":"0.0"},"338":{"cpu":"0.3","mem":"0.0"},"41":{"cpu":"0.0","mem":"0.0"},"42":{"cpu":"0.0","mem":"0.0"},"80":{"cpu":"0.0","mem":"0.0"},"81":{"cpu":"0.0","mem":"0.0"},"82":{"cpu":"0.0","mem":"0.0"},"89":{"cpu":"1.0","mem":"0.2"},"MiB":{"cpu":"5294.4","mem":"avail"},"PID":{"cpu":"%CPU","mem":"%MEM"},"Tasks:":{"cpu":"stopped,","mem":"0"},"top":{"cpu":"users,","mem":"load"}},"detection_fps":0.0,"detectors":{"coral":{"detection_start":0.0,"inference_speed":10.0,"pid":289}},"gpu_usages":{"intel-vaapi":{"gpu":"0.06 %","mem":"- %"}},"porch":{"camera_fps":0.0,"capture_pid":299,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":307,"pid":298,"process_fps":0.0,"skipped_fps":0.0},"service":{"last_updated":1700468569,"latest_version":"0.12.1","storage":{"/dev/shm":{"free":66.8,"mount_type":"tmpfs","total":67.1,"used":0.3},"/media/frigate/clips":{"free":418060.7,"mount_type":"ext4","total":491106.5,"used":48023.7},"/media/frigate/recordings":{"free":418060.7,"mount_type":"ext4","total":491106.5,"used":48023.7},"/tmp/cache":{"free":81794.6,"mount_type":"overlay","total":124896.6,"used":36710.3}},"temperatures":{},"uptime":6,"version":"0.12.1-367d724"}}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Reolink Doorbell

**Comment by blakeblackshear** [comment]
Custom models in the config only work with the 0.13 beta.

**Comment by AlasdairH** [comment]
Thanks, I'll upgrade.
