### ISSUE TITLE
[Support]: Error occurred when attempting to maintain recording cache

### ISSUE THREAD

**Issue by tungmeister** [blakeblackshear/frigate#8702]
### Describe the problem you are having

I've just updated to the lastest nightly build - havn't updated in a while and I'm seeing the above in the logs, and the cameras stop streaming a few seconds after frigate starts. It's also the same with beta5.

### Version

0.13.0-07b84617

### Frigate config file

```yaml
#frigate sample config.yml
mqtt:
  # Required: host name
  host: 10.0.0.11
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  user: assistant
  # Optional: 
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  password: 1nt3rc00l3r
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

birdseye:
  enabled: false

model:
  labelmap:
    16: cat
    17: cat

#ui:
#  use_experimental: true

go2rtc:
  streams:
    Drive: 
      - ffmpeg:rtsp://admin:x@10.0.0.110:554/Streaming/Channels/101/
      - "ffmpeg:Drive#audio=opus"
    Drive_Left: 
      - rtsp://admin:x@10.0.0.100:554/Streaming/Channels/101/
      - "ffmpeg:Drive_Left#audio=opus"
    Garden: 
      - rtsp://admin:x@10.0.0.222:554/Streaming/Channels/101/
      - "ffmpeg:Garden#audio=opus"
  webrtc:
    candidates:
      - 10.0.0.10:8555
      - stun:8555

cameras:
  Drive:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 600
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      input_args: preset-rtsp-generic
      output_args:
        detect: -vf hwdownload,format=nv12 -f rawvideo -pix_fmt yuvj420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:x@10.0.0.110:554/Streaming/Channels/101/
          roles:
            - record
        - path: rtsp://admin:x@10.0.0.110:554/Streaming/Channels/103/
          roles:
            - detect
    objects:
      track:
        - person
        - car
        - cat
      filters:
        person:
          min_area: 1000
          min_score: 0.8
        car:
          min_score: 0.2
          threshold: 0.5
          mask:
#            - 2926,621,3016,867,3840,2160,3840,0,0,0,0,2160,3840,2160,2991,839,2012,649,2311,490,2308,265,2944,343
    motion:
      mask:
#4k        - 2095,173,2938,323,3071,378,3840,858,3840,0,1701,0,0,0,0,441,1114,339,1118,217
        - 0,0,0,1080,189,237,527,165,567,156,551,103,646,93,825,103,982,90,1181,102,1185,137,1484,174,1714,188,1920,1080,1920,0
    snapshots:
      required_zones:
        - entrance
        - everywhere
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      quality: 100
      height: 600
      retain:
        default: 5
    detect:
      width: 1920
      height: 1080
    record:
      enabled: True
      events:
        pre_capture: 10
        post_capture: 10
        required_zones:
          - entrance
          - everywhere
        retain:
          default: 5
          objects:
            cat: 2
    zones:
      entrance:
#4k        coordinates: 1992,642,2997,835,2941,602,2953,284,2355,209,2323,437
        coordinates: 1485,333,1134,254,1165,170,1477,223
        objects:
          - car
      everywhere:
#4k        coordinates: 2350,217,2365,461,2942,631,2949,0,3840,543,3840,2160,0,2160,0,0,1040,0,1055,331,1158,299,1142,173
        coordinates: 1920,0,1920,1080,0,1080,0,0,517,188,550,227,620,203,685,184,866,164,992,177,1108,194,1103,257,1519,359,1630,0
        objects:
          - person
          - cat
  Drive_Left:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 600
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      input_args: preset-rtsp-generic
      output_args:
        detect: -vf hwdownload,format=nv12 -f rawvideo -pix_fmt yuvj420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:x@10.0.0.100:554/Streaming/Channels/101/
          roles:
            - record
        - path: rtsp://admin:x@10.0.0.100:554/Streaming/Channels/103/
          roles:
            - detect
    objects:
      track:
        - person
        - cat
        - car
      filters:
        cat:
          min_score: 0.3
          threshold: 0.55
    snapshots:
      required_zones:
        - left_entrance
        - left_everywhere
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      quality: 100
      height: 600
      retain:
        default: 5
    detect:
      width: 1280
      height: 720
    record:
      enabled: True
      events:
        required_zones:
          - left_entrance
          - left_everywhere
        retain:
          default: 5
          objects:
            cat: 2
    motion:
      mask:
        - 731,23,538,36,87,270,0,0,1077,0,1057,79
    zones:
      left_entrance:
        coordinates: 1072,237,843,189,955,62,1086,81
        objects:
          - car
      left_everywhere:
        coordinates: 635,34,982,79,920,194,1074,228,1121,0,1280,0,1280,720,0,720,0,296,290,191
        objects:
          - person
          - cat
  Garden:
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      quality: 100
      height: 600
    ffmpeg:
      hwaccel_args: preset-intel-qsv-h264
      input_args: preset-rtsp-generic
      output_args:
        detect: -vf hwdownload,format=nv12 -f rawvideo -pix_fmt yuvj420p
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://admin:x@10.0.0.222:554/Streaming/Channels/101/
          roles:
            - record
        - path: rtsp://admin:x@10.0.0.222:554/Streaming/Channels/103/
          roles:
            - detect
    motion:
      threshold: 8
      mask:
#4k        - 0,0,0,851,571,579,953,480,1382,378,1756,370,2339,343,3052,358,3103,311,3221,276,3410,260,3410,146,3575,0
        - 0,0,0,437,116,398,315,309,386,290,591,235,866,185,1147,178,1548,184,1608,138,1722,140,1920,0
    objects:
      track:
        - person
        - cat
      filters:
        cat:
          min_score: 0.3
          threshold: 0.55
          mask:
            - 1920,1080,1549,1080,1711,876,1744,823,1920,808
            - 0,381,0,695,356,507,329,304
        person:
          min_score: 0.8
          threshold: 0.75
          min_area: 1000
          mask:
            - 412,335,449,486,495,466,461,319
    zones:
      all_garden:
#4k        coordinates: 1992,642,2997,835,2941,602,2953,284,2355,209,2323,437
        coordinates: 1920,0,0,0,0,1080,1920,1080,1920,322,1920,0,1723,520,1629,505,1640,363,1725,305,1737,492
        objects:
          - cat
          - person
      doorstep:
#4k        coordinates: 3840,1465,3398,1355,3489,819,3840,851
        coordinates: 1729,317,1634,331,1607,523,1728,526
        objects:
          - cat
          - person
    snapshots:
      quality: 100
      height: 600
      enabled: true
      timestamp: true
      bounding_box: true
      crop: true
      retain:
        default: 5
    detect:
      width: 1920
      height: 1080
    record:
      enabled: True
      events:
        retain:
          default: 5
          objects:
            cat: 2
detectors:
  coral_pci:
    type: edgetpu
    device: pci
#  cpu1:
#    type: cpu
```

### Relevant log output

```shell
2023-11-21 12:59:04.490552200  [INFO] Preparing Frigate...
2023-11-21 12:59:04.504309072  [INFO] Starting Frigate...
2023-11-21 12:59:05.673673331  [2023-11-21 12:59:05] frigate.app                    INFO    : Starting Frigate (0.13.0-07b84617)
2023-11-21 12:59:05.739696030  [2023-11-21 12:59:05] peewee_migrate.logs            INFO    : Starting migrations
2023-11-21 12:59:05.746368542  [2023-11-21 12:59:05] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-11-21 12:59:05.759821305  [2023-11-21 12:59:05] frigate.app                    INFO    : Recording process started: 593
2023-11-21 12:59:05.761753920  [2023-11-21 12:59:05] frigate.app                    INFO    : go2rtc process pid: 89
2023-11-21 12:59:05.770340012  [2023-11-21 12:59:05] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:05.770435404  [2023-11-21 12:59:05] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:05.782236403  [2023-11-21 12:59:05] detector.coral_pci             INFO    : Starting detection process: 603
2023-11-21 12:59:05.790799912  [2023-11-21 12:59:05] frigate.app                    INFO    : Output process started: 605
2023-11-21 12:59:05.796329005  [2023-11-21 12:59:05] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci
2023-11-21 12:59:05.799018424  [2023-11-21 12:59:05] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-11-21 12:59:05.842127137  [2023-11-21 12:59:05] frigate.app                    INFO    : Camera processor started for Drive: 632
2023-11-21 12:59:05.848693178  [2023-11-21 12:59:05] frigate.app                    INFO    : Camera processor started for Drive_Left: 633
2023-11-21 12:59:05.856447362  [2023-11-21 12:59:05] frigate.app                    INFO    : Camera processor started for Garden: 636
2023-11-21 12:59:05.865957729  [2023-11-21 12:59:05] frigate.app                    INFO    : Capture process started for Drive: 637
2023-11-21 12:59:05.871738202  [2023-11-21 12:59:05] frigate.app                    INFO    : Capture process started for Drive_Left: 641
2023-11-21 12:59:05.877649901  [2023-11-21 12:59:05] frigate.app                    INFO    : Capture process started for Garden: 645
2023-11-21 12:59:10.771931588  [2023-11-21 12:59:10] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:10.772018091  [2023-11-21 12:59:10] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:15.770989324  [2023-11-21 12:59:15] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:15.771057811  [2023-11-21 12:59:15] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:20.776364462  [2023-11-21 12:59:20] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:20.776374112  [2023-11-21 12:59:20] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:25.771916606  [2023-11-21 12:59:25] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:25.771981702  [2023-11-21 12:59:25] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:25.906447029  Exception in thread Thread-8:
2023-11-21 12:59:25.906449962  Traceback (most recent call last):
2023-11-21 12:59:25.906451374    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-11-21 12:59:25.906685111      self.run()
2023-11-21 12:59:25.906695194    File "/opt/frigate/frigate/video.py", line 237, in run
2023-11-21 12:59:25.906766673      latest_segment_time = self.get_latest_segment_datetime(
2023-11-21 12:59:25.906773194    File "/opt/frigate/frigate/video.py", line 309, in get_latest_segment_datetime
2023-11-21 12:59:25.906860342      _, date = basename.rsplit("@", maxsplit=1)
2023-11-21 12:59:25.906880762  ValueError: not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:25.911637061  Exception in thread Thread-8:
2023-11-21 12:59:25.911648085  Traceback (most recent call last):
2023-11-21 12:59:25.911649836    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-11-21 12:59:25.911817164      self.run()
2023-11-21 12:59:25.911824952    File "/opt/frigate/frigate/video.py", line 237, in run
2023-11-21 12:59:25.911874173      latest_segment_time = self.get_latest_segment_datetime(
2023-11-21 12:59:25.911876206    File "/opt/frigate/frigate/video.py", line 309, in get_latest_segment_datetime
2023-11-21 12:59:25.911931862      _, date = basename.rsplit("@", maxsplit=1)
2023-11-21 12:59:25.911949666  ValueError: not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:25.917929459  Exception in thread Thread-8:
2023-11-21 12:59:25.917936409  Traceback (most recent call last):
2023-11-21 12:59:25.917939774    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-11-21 12:59:25.918231643      self.run()
2023-11-21 12:59:25.918233603    File "/opt/frigate/frigate/video.py", line 237, in run
2023-11-21 12:59:25.918313548      latest_segment_time = self.get_latest_segment_datetime(
2023-11-21 12:59:25.918315498    File "/opt/frigate/frigate/video.py", line 309, in get_latest_segment_datetime
2023-11-21 12:59:25.918397008      _, date = basename.rsplit("@", maxsplit=1)
2023-11-21 12:59:25.918398926  ValueError: not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:30.770414069  [2023-11-21 12:59:30] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:30.770472643  [2023-11-21 12:59:30] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:35.770042337  [2023-11-21 12:59:35] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:35.770122953  [2023-11-21 12:59:35] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:40.770565255  [2023-11-21 12:59:40] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:40.770631355  [2023-11-21 12:59:40] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:45.778512015  [2023-11-21 12:59:45] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:45.778555581  [2023-11-21 12:59:45] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
2023-11-21 12:59:50.768865214  [2023-11-21 12:59:50] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
2023-11-21 12:59:50.768922929  [2023-11-21 12:59:50] frigate.record.maintainer      ERROR   : not enough values to unpack (expected 2, got 1)
```

### FFprobe output from your camera

```shell
N/A
```

### Operating system

UNRAID

### Install method

Docker Compose

### Coral version

M.2

### Network connection

Wired

### Camera make and model

hikvision

**Comment by NickM-27** [comment]
This isn't the latest build, and it looks like a custom build was done or something where /tmp/cache was not mounted correctly so old recording segments are being kept and not compatible with the latest changes

**Comment by tungmeister** [comment]
I'm now running beta 5 with the same results?

**Comment by NickM-27** [comment]
in general, /tmp/ should be mounted as tmpfs so that it does not survive a reboot
