### ISSUE TITLE
Frigate gives me invalid config error with hikvision camera

### ISSUE THREAD

**Issue by manuelfabrice** [blakeblackshear/frigate#8833]
### Describe the problem you are having

 This is the error that frigate gives me with the hikvision DS-2CD2046G2 camera
 

### Version

Frigate Current version: 0.12.1

### Frigate config file

```yaml
mqtt:
    enabled: false

cameras:
    entree portail:
        ffmpeg:
            inputs:
                - path: rtsp://name:password@ip:554/unicast
                  roles:
                    - detect
        detect:
            enabled: False
            width: 1280
            height: 720
```

### Relevant log output

```shell
Config Validation Errors                           ***
2023-12-02 10:38:30.423409123  *************************************************************
2023-12-02 10:38:30.424203254  1 validation error for CameraConfig
2023-12-02 10:38:30.424209254  name
2023-12-02 10:38:30.424363776    string does not match regex "^[a-zA-Z0-9_-]+$" (type=value_error.str.regex; pattern=^[a-zA-Z0-9_-]+$)
2023-12-02 10:38:30.427072413  Traceback (most recent call last):
2023-12-02 10:38:30.427078853    File "/opt/frigate/frigate/app.py", line 351, in start
2023-12-02 10:38:30.427085613      self.init_config()
2023-12-02 10:38:30.427088893    File "/opt/frigate/frigate/app.py", line 81, in init_config
2023-12-02 10:38:30.427091373      self.config = user_config.runtime_config
2023-12-02 10:38:30.427093333    File "/opt/frigate/frigate/config.py", line 940, in runtime_config
2023-12-02 10:38:30.427130214      camera_config: CameraConfig = CameraConfig.parse_obj(
2023-12-02 10:38:30.427133374    File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 526, in parse_obj
2023-12-02 10:38:30.427135534      return cls(**obj)
2023-12-02 10:38:30.427137294    File "/opt/frigate/frigate/config.py", line 646, in __init__
2023-12-02 10:38:30.427138774      super().__init__(**config)
2023-12-02 10:38:30.427140814    File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 341, in __init__
2023-12-02 10:38:30.427181414      raise validation_error
2023-12-02 10:38:30.427183894  pydantic.error_wrappers.ValidationError: 1 validation error for CameraConfig
2023-12-02 10:38:30.427185974  name
2023-12-02 10:38:30.427188294    string does not match regex "^[a-zA-Z0-9_-]+$" (type=value_error.str.regex; pattern=^[a-zA-Z0-9_-]+$)
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
feel free to create a new issue if something else comes up

**Comment by manuelfabrice** [comment]
ok
