### ISSUE TITLE
[Support]: ONVIF error The CapabilityCategory type doesn't accept collections as value

### ISSUE THREAD

**Issue by LordXaosa** [blakeblackshear/frigate#8836]
### Describe the problem you are having

Frigate won't start after added onvif section. Error: Onvif connection to back failed: Unknown error: The CapabilityCategory type doesn't accept collections as value

ONVIF device manager works ok with this camera.

### Version

0.13.0-beta3

### Frigate config file

```yaml
cameras:
  back:
    onvif:
      host: x.x.x.x
      port: 8899
      autotracking:
        enabled: True
        calibrate_on_startup: True
        zooming: disabled
        zoom_factor: 0.3
        track:
          - person
        required_zones:
          - zone_name
        return_preset: home
        timeout: 10
```

### Relevant log output

```shell
2023-12-02 20:15:04.599941039  [2023-12-02 20:15:04] frigate.ptz.onvif              ERROR   : Onvif connection to back failed: Unknown error: The CapabilityCategory type doesn't accept collections as value
2023-12-02 20:15:04.604888953  [2023-12-02 20:15:04] frigate.app                    INFO    : Recording process started: 2540
2023-12-02 20:15:04.608167320  [2023-12-02 20:15:04] frigate.app                    INFO    : go2rtc process pid: 88
2023-12-02 20:15:04.634068254  [2023-12-02 20:15:04] frigate.app                    INFO    : Output process started: 2551
2023-12-02 20:15:04.634218746  Traceback (most recent call last):
2023-12-02 20:15:04.634326621    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-12-02 20:15:04.634717556      return _run_code(code, main_globals, None,
2023-12-02 20:15:04.634779759    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-12-02 20:15:04.634988916      exec(code, run_globals)
2023-12-02 20:15:04.635048172    File "/opt/frigate/frigate/__main__.py", line 17, in <module>
2023-12-02 20:15:04.635225706      frigate_app.start()
2023-12-02 20:15:04.635312976    File "/opt/frigate/frigate/app.py", line 664, in start
2023-12-02 20:15:04.635550527      self.start_ptz_autotracker()
2023-12-02 20:15:04.635668699    File "/opt/frigate/frigate/app.py", line 443, in start_ptz_autotracker
2023-12-02 20:15:04.635933990      self.ptz_autotracker_thread = PtzAutoTrackerThread(
2023-12-02 20:15:04.636020552    File "/opt/frigate/frigate/ptz/autotrack.py", line 151, in __init__
2023-12-02 20:15:04.636183047      [2023-12-02 20:15:04] detector.cpu                   INFO    : Starting detection process: 2549
2023-12-02 20:15:04.636277830  self.ptz_autotracker = PtzAutoTracker(config, onvif, ptz_metrics)
2023-12-02 20:15:04.636360342  [2023-12-02 20:15:04] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-12-02 20:15:04.636440569    File "/opt/frigate/frigate/ptz/autotrack.py", line 204, in __init__
2023-12-02 20:15:04.636559222      self._autotracker_setup(camera_config, camera)
2023-12-02 20:15:04.636561760    File "/opt/frigate/frigate/ptz/autotrack.py", line 230, in _autotracker_setup
2023-12-02 20:15:04.636657454      if not self.onvif.cams[camera]["init"]:
2023-12-02 20:15:04.636659579  KeyError: 'back'
```

### FFprobe output from your camera

```shell
not relevant
```

### Frigate stats

```json
unhealthy
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Jooan 5MP

**Comment by NickM-27** [comment]
CC @hawkeye217

**Comment by hawkeye217** [comment]
There's a small issue that can be fixed here to prevent Frigate from not starting when autotracking is enabled and an ONVIF connection to the camera fails where it does. I'll submit a quick PR for that.

But the more significant issue is the first error that you noted. The ONVIF library that Frigate 0.13 uses seems to be problematic with your camera's ONVIF implementation. We have plans to improve this in a future version of Frigate, but at this point there is nothing that can be done.

**Comment by LordXaosa** [comment]
Thanks for instant answer! I'll wait for updates. Thanks it advance.

**Comment by UnknownUser6** [comment]
I have the same problem with my tapo c200. So there is nothing I can do to fix that right now on version 0.13.1 as well?

**Comment by hawkeye217** [comment]
Autotracking with the Tapo C200 won't work and is unsupported.

**Comment by bwaayer** [comment]
Having this same problem now, using a Dahua DH-SD42212T-HN 
using a very basic configuration.
Not too familiar with this ONVIF stuff, so not sure what to do to check/change?
