### ISSUE TITLE
[Support]: Frigate crashes if autotrack camera is not accessible on startup

### ISSUE THREAD

**Issue by evanjarrett** [blakeblackshear/frigate#8840]
### Describe the problem you are having

When starting frigate with a camera that is configured with onvif and ptz autotracking, frigate returns an error if that camera is not currently online.

In the log output below, "ptz" is what I named the camera.
looks like autotrack.py is not checking if the camera is accessible before trying to init.
```
2023-12-02 18:03:14.040315804    File "/opt/frigate/frigate/ptz/autotrack.py", line 241, in _autotracker_setup
2023-12-02 18:03:14.040366034      if not self.onvif.cams[camera]["init"]:
2023-12-02 18:03:14.040396081  KeyError: 'ptz'
```

This causes most of the UI to fail to load (I only see the navigation header and a blank page)

I'm also aware that the e1 zoom doesn't support autotracking, but when its online, it generally just sends a warning:
`frigate.ptz.autotrack          WARNING : Disabling autotracking for ptz: FOV relative movement not supported`

### Version

0.13.0-614a36a

### Frigate config file

```yaml
ptz:
        ffmpeg:
          inputs:
          - path: rtsp://127.0.0.1:8554/ptz
            roles:
              - detect
              - record
        onvif:
          host: redact
          port: 8000
          user: redact
          password: redact
          autotracking:
            enabled: True
            calibrate_on_startup: True
            zooming: disabled
            required_zones:
              - all
            return_preset: home
        zones:
          all:
            coordinates: 2560,0,2560,1920,0,1920,0,0
        detect:
          enabled: True
        snapshots:
          enabled: True
```

### Relevant log output

```shell
2023-12-02 18:02:42.304004464  [2023-12-02 18:02:42] frigate.app                    INFO    : Starting Frigate (0.13.0-614a36a)
2023-12-02 18:02:42.304446349  [2023-12-02 18:02:42] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-12-02 18:02:51.204353882  [INFO] Starting go2rtc healthcheck service...
2023-12-02 18:03:10.933471255  18:03:10.933 WRN [rtsp] error="streams: dial tcp 1<redact>:554: i/o timeout, exec: exit status 1" stream=ptz
2023-12-02 18:03:10.933722263  [rtsp @ 0x3f01b00] method DESCRIBE failed: 404 Not Found
2023-12-02 18:03:10.934583188  [ERROR:0@29.093] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2023-12-02 18:03:10.934588517  
2023-12-02 18:03:10.934599972  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://127.0.0.1:8554/ptz in function 'icvExtractPattern'
2023-12-02 18:03:10.934605454  
2023-12-02 18:03:10.934608331  
2023-12-02 18:03:10.954842765  [2023-12-02 18:03:10] peewee_migrate.logs            INFO    : Starting migrations
2023-12-02 18:03:10.957623386  [2023-12-02 18:03:10] peewee_migrate.logs            INFO    : There is nothing to migrate
2023-12-02 18:03:14.020940653  [2023-12-02 18:03:14] frigate.ptz.onvif              ERROR   : Onvif connection to ptz failed: Unknown error: HTTPConnectionPool(host='redact', port=8000): Max retries exceeded with url: /onvif/device_service (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa7c452d850>: Failed to establish a new connection: [Errno 113] No route to host'))
2023-12-02 18:03:14.021263379  [2023-12-02 18:03:14] frigate.app                    INFO    : Recording process started: 488
2023-12-02 18:03:14.022560639  [2023-12-02 18:03:14] frigate.app                    INFO    : go2rtc process pid: 89
2023-12-02 18:03:14.038225272  [2023-12-02 18:03:14] detector.coral                 INFO    : Starting detection process: 498
2023-12-02 18:03:14.039642319  Traceback (most recent call last):
2023-12-02 18:03:14.039645174    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-12-02 18:03:14.039939680      return _run_code(code, main_globals, None,
2023-12-02 18:03:14.039947325    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-12-02 18:03:14.039989125      exec(code, run_globals)
2023-12-02 18:03:14.039991764    File "/opt/frigate/frigate/__main__.py", line 17, in <module>
2023-12-02 18:03:14.040038478      frigate_app.start()
2023-12-02 18:03:14.040039804    File "/opt/frigate/frigate/app.py", line 684, in start
2023-12-02 18:03:14.040133900      self.start_ptz_autotracker()
2023-12-02 18:03:14.040135271    File "/opt/frigate/frigate/app.py", line 460, in start_ptz_autotracker
2023-12-02 18:03:14.040193537      self.ptz_autotracker_thread = PtzAutoTrackerThread(
2023-12-02 18:03:14.040197954    File "/opt/frigate/frigate/ptz/autotrack.py", line 153, in __init__
2023-12-02 18:03:14.040251609      self.ptz_autotracker = PtzAutoTracker(
2023-12-02 18:03:14.040263614    File "/opt/frigate/frigate/ptz/autotrack.py", line 215, in __init__
2023-12-02 18:03:14.040314317      self._autotracker_setup(camera_config, camera)
2023-12-02 18:03:14.040315804    File "/opt/frigate/frigate/ptz/autotrack.py", line 241, in _autotracker_setup
2023-12-02 18:03:14.040366034      if not self.onvif.cams[camera]["init"]:
2023-12-02 18:03:14.040396081  KeyError: 'ptz'
```

### FFprobe output from your camera

```shell
N/a
```

### Operating system

Other Linux

### Install method

Docker CLI

### Coral version

M.2

### Network connection

Wired

### Camera make and model

reolink e1 zoom

**Comment by hawkeye217** [comment]
This has been fixed in https://github.com/blakeblackshear/frigate/pull/8838 and will be available in the next dev/beta.

**Comment by evanjarrett** [comment]
ah, dang, didn't see the previous report in my quick issue search.
also looks like in the time it took me to gather the logs for the report this was fixed.
thanks!
