### ISSUE TITLE
[Detector Support]: dual edge tpu m.2 crash

### ISSUE THREAD

**Issue by Shiroe93** [blakeblackshear/frigate#8853]
### Describe the problem you are having

after adding a google coral dual edge tpu (m.2 format) frigate keeps crashing

### Version

0.12.1-367d724 (full access)

### Frigate config file

```yaml
mqtt:
  host: 
  port: 
  topic_prefix: frigate
  client_id: frigate
  user: 
  password: 
  stats_interval: 60

detectors:
  coral1:
    type: edgetpu
    device: pci:0
  coral2:
    type: edgetpu
    device: pci:1


go2rtc:
  streams:

    giardino_anteriore: 
      -  rtsp://admin:NaP-Re@-993@192.168.50.66:554/h265Preview_01_main
      - ffmpeg:rtsp://admin:NaP-Re@-993@192.168.50.66:554/h265Preview_01_main#audio=pcm#audio=volume

    giardino_posteriore: 
      -  rtsp://admin:NaP-Re@-993@192.168.50.67:554/h265Preview_01_main
      - ffmpeg:rtsp://admin:NaP-Re@-993@192.168.50.67:554/h265Preview_01_main#audio=pcm#audio=volume


    campanello: 
      - rtsp://admin:NaP-Re@-993@192.168.50.68:554/h265Preview_01_main
      - ffmpeg:rtsp://admin:NaP-Re@-993@192.168.50.68:554/h265Preview_01_main#audio=pcm#audio=volume

## THIS PREVENTS THE AUDIO COMING OUT FROM THE DOORBELL SOUNDING MUFFLED
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=20dB\""
  
  webrtc:
    candidates:
      - 192.168.50.46:8555
      - stun:8555


cameras:
  giardino_anteriore:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/giardino_anteriore?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - detect
        - record
      output_args:
        record: preset-record-generic-audio-copy

  giardino_posteriore:
    ffmpeg:
      inputs:
      - path: rtsp://127.0.0.1:8554/giardino_posteriore?video=copy&audio=aac
        input_args: preset-rtsp-restream
        roles:
        - detect
        - record
      output_args:
        record: preset-record-generic-audio-copy


  campanello:
    ffmpeg:
      inputs:
        - path: rtsp://admin:NaP-Re@-993@192.168.50.68:554/h265Preview_01_sub
          roles:
            - record
        - path: rtsp://admin:NaP-Re@-993@192.168.50.68:554/h265Preview_01_sub
          roles:
            - detect
      output_args:
        record: preset-record-generic-audio-copy
        
        
        
        

############################## GLOBAL CONFIG ############################################
objects:
  track:
    - person
    - dog
    - cat 
  filters:
    person:
      threshold: 0.7
detect:
  width: 2560
  height: 1440
  fps: 5
  stationary: 
    interval: 15
    threshold: 50

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 2

motion:
  threshold: 25
  improve_contrast: True

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 21
      mode: active_objects


ui:
 live_mode: webrtc
```

### docker-compose file or Docker CLI command

```yaml
home assistant add on
```

### Relevant log output

```shell
2023-12-04 20:59:16.368809533  21:59:16.368 INF [srtp] listen addr=:8443
2023-12-04 20:59:16.368949680  21:59:16.368 INF [webrtc] listen addr=:8555/tcp
2023-12-04 20:59:17.020804140  [2023-12-04 21:59:17] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-04 20:59:17.047748764  [2023-12-04 21:59:17] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-12-04 20:59:17.048882821  [2023-12-04 21:59:17] peewee_migrate                 INFO    : Starting migrations
2023-12-04 20:59:17.052474063  [2023-12-04 21:59:17] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-04 20:59:17.066631107  [2023-12-04 21:59:17] frigate.app                    INFO    : Output process started: 371
2023-12-04 20:59:17.069634107  [2023-12-04 21:59:17] detector.coral2                INFO    : Starting detection process: 370
2023-12-04 20:59:17.069929322  [2023-12-04 21:59:17] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as pci:1
2023-12-04 20:59:17.070115118  [2023-12-04 21:59:17] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-12-04 20:59:17.070896511  Process detector:coral2:
2023-12-04 20:59:17.073672908  Traceback (most recent call last):
2023-12-04 20:59:17.073676876    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-12-04 20:59:17.073691637      delegate = Delegate(library, options)
2023-12-04 20:59:17.073695762    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-12-04 20:59:17.073697457      raise ValueError(capture.message)
2023-12-04 20:59:17.073708580  ValueError
2023-12-04 20:59:17.073709656  
2023-12-04 20:59:17.073711136  During handling of the above exception, another exception occurred:
2023-12-04 20:59:17.073712531  
2023-12-04 20:59:17.073713627  Traceback (most recent call last):
2023-12-04 20:59:17.073714970    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-12-04 20:59:17.073716029      self.run()
2023-12-04 20:59:17.073717243    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-12-04 20:59:17.073733995      self._target(*self._args, **self._kwargs)
2023-12-04 20:59:17.073735290    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-12-04 20:59:17.073737044      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-12-04 20:59:17.073738196    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-12-04 20:59:17.073750135      self.detect_api = create_detector(detector_config)
2023-12-04 20:59:17.073751447    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-12-04 20:59:17.073752540      return api(detector_config)
2023-12-04 20:59:17.073753792    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-12-04 20:59:17.073754951      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-12-04 20:59:17.073766592    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-12-04 20:59:17.073767839      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-12-04 20:59:17.073768957  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-12-04 20:59:17.073769914  
2023-12-04 20:59:17.074313375  [2023-12-04 21:59:17] frigate.app                    INFO    : Camera processor started for giardino_anteriore: 377
2023-12-04 20:59:17.075402061  [2023-12-04 21:59:17] frigate.app                    INFO    : Camera processor started for giardino_posteriore: 379
2023-12-04 20:59:17.078251692  [2023-12-04 21:59:17] frigate.app                    INFO    : Camera processor started for campanello: 381
2023-12-04 20:59:17.082417276  [2023-12-04 21:59:17] frigate.app                    INFO    : Capture process started for giardino_anteriore: 382
2023-12-04 20:59:17.085849569  [2023-12-04 21:59:17] frigate.app                    INFO    : Capture process started for giardino_posteriore: 385
2023-12-04 20:59:17.090875838  [2023-12-04 21:59:17] frigate.app                    INFO    : Capture process started for campanello: 389
2023-12-04 20:59:24.402498238  172.30.32.1 - - [04/Dec/2023:21:59:24 +0100] "GET /api/stats HTTP/1.1" 200 2717 "-" "HomeAssistant/2023.11.3 aiohttp/3.8.5 Python/3.11" "-"
2023-12-04 20:59:26.025657804  [INFO] Starting go2rtc healthcheck service...
2023-12-04 20:59:32.430340285  172.30.32.1 - - [04/Dec/2023:21:59:32 +0100] "GET /api/stats HTTP/1.1" 200 2735 "-" "HomeAssistant/2023.11.3 aiohttp/3.8.5 Python/3.11" "-"
2023-12-04 20:59:37.223107062  [2023-12-04 21:59:37] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-12-04 20:59:37.239605718  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-12-04 20:59:37.261400028  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
2023-12-04 20:59:37.263542236  [2023-12-04 21:59:37] frigate.app                    INFO    : Stopping...
2023-12-04 20:59:37.264162307  [2023-12-04 21:59:37] frigate.record                 INFO    : Exiting recording maintenance...
2023-12-04 20:59:37.265202252  [2023-12-04 21:59:37] frigate.storage                INFO    : Exiting storage maintainer...
2023-12-04 20:59:37.266766736  [2023-12-04 21:59:37] frigate.events                 INFO    : Exiting event cleanup...
2023-12-04 20:59:37.266770732  [2023-12-04 21:59:37] frigate.record                 INFO    : Exiting recording cleanup...
2023-12-04 20:59:37.270018403  [2023-12-04 21:59:37] frigate.stats                  INFO    : Exiting stats emitter...
2023-12-04 20:59:37.270223891  [2023-12-04 21:59:37] frigate.watchdog               INFO    : Exiting watchdog...
2023-12-04 20:59:37.270369711  [2023-12-04 21:59:37] frigate.object_processing      INFO    : Exiting object processor...
2023-12-04 20:59:37.573060922  [2023-12-04 21:59:37] frigate.comms.ws               INFO    : Exiting websocket client...
2023-12-04 20:59:38.240145686  [2023-12-04 21:59:38] frigate.events                 INFO    : Exiting event processor...
2023-12-04 20:59:38.240477660  [2023-12-04 21:59:38] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-12-04 20:59:38.242289112  [2023-12-04 21:59:38] watchdog.campanello            INFO    : Terminating the existing ffmpeg process...
2023-12-04 20:59:38.242473937  [2023-12-04 21:59:38] watchdog.giardino_posteriore   INFO    : Terminating the existing ffmpeg process...
2023-12-04 20:59:38.242547276  [2023-12-04 21:59:38] watchdog.campanello            INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-04 20:59:38.242606242  [2023-12-04 21:59:38] watchdog.giardino_anteriore    INFO    : Terminating the existing ffmpeg process...
2023-12-04 20:59:38.242656869  [2023-12-04 21:59:38] watchdog.giardino_posteriore   INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-04 20:59:38.242704684  [2023-12-04 21:59:38] watchdog.giardino_anteriore    INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-04 20:59:38.269223641  [2023-12-04 21:59:38] watchdog.campanello            INFO    : Terminating the existing ffmpeg process...
2023-12-04 20:59:38.269320660  [2023-12-04 21:59:38] watchdog.campanello            INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-04 20:59:38.619795252  [2023-12-04 21:59:38] frigate.output                 INFO    : exiting output process...
2023-12-04 20:59:42.409052374  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 17 leaked shared_memory objects to clean up at shutdown
2023-12-04 20:59:42.409055649    warnings.warn('resource_tracker: There appear to be %d '
2023-12-04 20:59:42.410955379  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-12-04 20:59:42.412531714  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-12-04 20:59:42.416679628  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

M.2

**Comment by NickM-27** [comment]
The second coral is not detected. Can you check the HA hardware screen or us lspci to confirm both are seen

**Comment by Shiroe93** [comment]
> The second coral is not detected. Can you check the HA hardware screen or us lspci to confirm both are seen 

In the ha hardware screen how should they appear?

I tried disabling each one keeping the other active but I have the same problem

**Comment by NickM-27** [comment]
Best bet would be to get the output of lspci

**Comment by NickM-27** [comment]
okay, what about a screenshot of the hardware page?

**Comment by NickM-27** [comment]
also what device is this installed in and are you using the dual edge tpu pcie adapter?

**Comment by Shiroe93** [comment]
![Screenshot_20231204_230836_Firefox.jpg](https://github.com/blakeblackshear/frigate/assets/56954468/89883b62-0707-4802-afc8-659e0f402147)

![Screenshot_20231204_230929_Firefox.jpg](https://github.com/blakeblackshear/frigate/assets/56954468/ff429d0c-38bf-46bd-ba60-8d0a77c3ce65)

![Screenshot_20231204_230713_Firefox.jpg](https://github.com/blakeblackshear/frigate/assets/56954468/3e92c1ba-b402-4b6f-8067-5f2bd68b79dc)

The pc is an hp prodesk 400 g4 with an Intel 8500t and the dual edge tpu is mounted in the wifi slot directly on the motherboard

**Comment by NickM-27** [comment]
> dual edge tpu is mounted in the wifi slot directly on the motherboard

okay, most likely your wifi slot only supports a single BUS so only one coral can be used. You can read more about this at https://github.com/magic-blue-smoke/Dual-Edge-TPU-Adapter#why-would-i-need-an-adapter-for-coral-dual-edge-tpu

**Comment by Shiroe93** [comment]
So can I select one tpu or I've to I have to buy an adapter even if I choose to use only one of them?

**Comment by NickM-27** [comment]
you can use 1 TPU now as is without issues. If you want to use both TPUs then you must have a device that supports the hardware. One of these options is the magic blue smoke adapter

**Comment by NickM-27** [comment]
have you made sure that protected mode is disabled in the addon configuration?

**Comment by Shiroe93** [comment]
yes is the frist thing i've done

**Comment by NickM-27** [comment]
then it seems the coral is not coming online, you may need to find a way to get a shell in HA OS itself so you can run lspci

**Comment by Shiroe93** [comment]
Even when selecting one tpu I've the same issue
This is the part I changed
![Screenshot_20231204_235547_Firefox.png](https://github.com/blakeblackshear/frigate/assets/56954468/216c641c-97b5-4605-8b2c-a6c2457c5c7b)


Any ideas on how i could do this?

**Comment by Shiroe93** [comment]
Any idea on how to do this?

**Comment by Shiroe93** [comment]
> then it seems the coral is not coming online, you may need to find a way to get a shell in HA OS itself so you can run lspci

Also it doesn't seem to be the problem because it manages to work for 20 seconds before collapsing

**Comment by NickM-27** [comment]
> Also it doesn't seem to be the problem because it manages to work for 20 seconds before collapsing

frigate will work fine until the first detection is run. the logs are clear that the error is the coral is not detected

**Comment by NickM-27** [comment]
I do not know about the HA OS question, I don't use it
