### ISSUE TITLE
ffmeg error[Config Support]: 

### ISSUE THREAD

**Issue by NasKar2** [blakeblackshear/frigate#8896]
### Describe the problem you are having

I'm trying to setup frigate for my reolink doorbell camera. I have a docker compose setup in Proxmox 8.03 an LXC with 2 cores, 8 gig mem. Let me know if you need any further info. When I run the docker-compose.yaml
`version: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config:/config
      - /cctv_clips:/mnt/reolink
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password"`
I get these ffmeg errors
``frigate  | 2023-12-08 04:54:09.732279804  [2023-12-08 04:54:09] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
frigate  | 2023-12-08 04:54:09.732690469  [2023-12-08 04:54:09] peewee_migrate                 INFO    : Starting migrations
frigate  | 2023-12-08 04:54:09.733027174  [2023-12-08 04:54:09] peewee_migrate                 INFO    : There is nothing to migrate
frigate  | 2023-12-08 04:54:09.742160119  [2023-12-08 04:54:09] frigate.app                    INFO    : Output process started: 546
frigate  | 2023-12-08 04:54:09.752150162  [2023-12-08 04:54:09] frigate.app                    INFO    : Camera processor started for FrontCam: 551
frigate  | 2023-12-08 04:54:09.754593657  [2023-12-08 04:54:09] detector.cpu                   INFO    : Starting detection process: 545
frigate  | 2023-12-08 04:54:09.754988699  [2023-12-08 04:54:09] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
frigate  | 2023-12-08 04:54:09.755804864  [2023-12-08 04:54:09] frigate.app                    INFO    : Capture process started for FrontCam: 552
frigate  | 2023-12-08 04:54:12.935074612  [2023-12-08 04:54:12] frigate.video                  ERROR   : FrontCam: Unable to read frames from ffmpeg process.
frigate  | 2023-12-08 04:54:12.935447443  [2023-12-08 04:54:12] frigate.video                  ERROR   : FrontCam: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-12-08 04:54:19.076542746  [INFO] Starting go2rtc healthcheck service...
frigate  | 2023-12-08 04:54:29.788598053  [2023-12-08 04:54:29] watchdog.FrontCam              ERROR   : Ffmpeg process crashed unexpectedly for FrontCam.
frigate  | 2023-12-08 04:54:29.791770933  [2023-12-08 04:54:29] watchdog.FrontCam              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-12-08 04:54:29.791776255  [2023-12-08 04:54:29] ffmpeg.FrontCam.detect         ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
frigate  | 2023-12-08 04:54:29.791788518  [2023-12-08 04:54:29] ffmpeg.FrontCam.detect         ERROR   : Error parsing options for output file vaapi.
frigate  | 2023-12-08 04:54:29.791790630  [2023-12-08 04:54:29] ffmpeg.FrontCam.detect         ERROR   : Error opening output files: Invalid argument
frigate  | 2023-12-08 04:54:32.932659936  [2023-12-08 04:54:32] frigate.video                  ERROR   : FrontCam: Unable to read frames from ffmpeg process.
frigate  | 2023-12-08 04:54:32.933045639  [2023-12-08 04:54:32] frigate.video                  ERROR   : FrontCam: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-12-08 04:54:39.795182532  [2023-12-08 04:54:39] watchdog.FrontCam              ERROR   : Ffmpeg process crashed unexpectedly for FrontCam.
frigate  | 2023-12-08 04:54:39.798060913  [2023-12-08 04:54:39] watchdog.FrontCam              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-12-08 04:54:39.798063712  [2023-12-08 04:54:39] ffmpeg.FrontCam.detect         ERROR   : Option hwaccel (use HW accelerated decoding) cannot be applied to output url vaapi -- you are trying to a

### Version

Don't have a debug page

### Frigate config file

```yaml
mqtt:
  enabled: false
ffmpeg:
  hwaccel_args: preset-vaapi
#Global Object Settings
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
cameras:
  FrontCam:
    ffmpeg:
      inputs:
        # High Resolution Stream
        - path: rtsp://admin:password@192.168.5.36:554/h264Preview_01_main
          roles:
            - record
        # Low Resolution Stream
        - path: rtsp://admin:password@192.168.5.36:554/h264Preview_01_main
          roles:
            - detect
    detect:
      width: 480
      height: 360
      fps: 24
```

### Relevant log output

```shell
2023-12-08 05:18:19.792533622  [INFO] Starting Frigate...
2023-12-08 05:18:20.468072116  [2023-12-08 05:18:20] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-08 05:18:20.468451809  [2023-12-08 05:18:20] peewee_migrate                 INFO    : Starting migrations
2023-12-08 05:18:20.468741717  [2023-12-08 05:18:20] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-08 05:18:20.477662069  [2023-12-08 05:18:20] frigate.app                    INFO    : Output process started: 546
2023-12-08 05:18:20.494056368  [2023-12-08 05:18:20] frigate.app                    INFO    : Camera processor started for FrontCam: 550
2023-12-08 05:18:20.494059593  [2023-12-08 05:18:20] frigate.app                    INFO    : Capture process started for FrontCam: 551
2023-12-08 05:18:20.500753871  [2023-12-08 05:18:20] detector.cpu                   INFO    : Starting detection process: 545
2023-12-08 05:18:20.500759416  [2023-12-08 05:18:20] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-12-08 05:18:22.287066923  [2023-12-08 05:18:22] frigate.video                  ERROR   : FrontCam: Unable to read frames from ffmpeg process.
2023-12-08 05:18:22.287394835  [2023-12-08 05:18:22] frigate.video                  ERROR   : FrontCam: ffmpeg process is not running. exiting capture thread...
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

CPU (no coral)

**Comment by NasKar2** [comment]
I tried per your link to use this config per your link

`mqtt:
  enable: false
go2rtc:
  streams:
    your_reolink_camera: 
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus"
    your_reolink_camera_sub: 
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password"

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.5.36:8554/your_reolink_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://192.168.5.36:8554/your_reolink_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect`

but I get alot of errors 

`Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 761, in config_save
    new_yaml = FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1083, in parse_raw
    return cls.parse_obj(config)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
mqtt -> enable
  extra fields not permitted (type=value_error.extra)`

**Comment by NickM-27** [comment]
The part with the error has nothing to do with the docs. You have MQTT -> enable but it is supposed to be MQTT -> enabled

**Comment by NasKar2** [comment]
Will try again.  I read in a different thead that I need to turn on http in reolink dashboard as well as RTMP
![network](https://github.com/blakeblackshear/frigate/assets/31674727/d81c03f1-650d-405f-a1ce-6e4e9696bb66)

My docker-compose.yaml
`version: '3.9'

services:

  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb" # update for your cameras based on calculation above
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/config/:/config/
      - /cctv_clips:/mnt/reolink
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "password of reolink"`

gives this output
`root@docker-frigate:/opt# docker compose up -d
WARN[0000] The "ejStz95" variable is not set. Defaulting to a blank string. 
WARN[0000] The "yQc" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ✔ Container frigate  Started `

config file
`mqtt:
  enabled: true
  host: 192.168.5.45         # YOUR MQTT IP
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt-user               # YOUR MQTT USERNAME
  password: mqttpassword    # YOUT MQTT PASSWORD
  stats_interval: 60
ffmpeg:
  hwaccel_args:
    - -hwaccel
    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p

  global_args:
    - -hide_banner
    - -loglevel
    - debug

  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p -filter:v fps=fps=5
go2rtc:
  streams:
    your_reolink_camera: 
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=password#video=copy#audio=copy#audio=opus"
    your_reolink_camera_sub: 
      - "ffmpeg:http://reolink_ip/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=password"

cameras:
  reolink:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1/your_reolink_camera?video=copy&audio=aac
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1/your_reolink_camera_sub?video=copy
          input_args: preset-rtsp-restream
          roles:
            - detect`

logs

`2023-12-08 09:11:34.344712055  [INFO] Starting Frigate...
2023-12-08 09:11:35.038177385  [2023-12-08 09:11:35] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-08 09:11:35.038728383  [2023-12-08 09:11:35] peewee_migrate                 INFO    : Starting migrations
2023-12-08 09:11:35.038989119  [2023-12-08 09:11:35] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-08 09:11:35.050020229  [2023-12-08 09:11:35] frigate.app                    INFO    : Output process started: 547
2023-12-08 09:11:35.053614525  [2023-12-08 09:11:35] frigate.app                    INFO    : Camera processor started for reolink: 549
2023-12-08 09:11:35.056865940  [2023-12-08 09:11:35] frigate.app                    INFO    : Capture process started for reolink: 550
2023-12-08 09:11:35.080530892  [2023-12-08 09:11:35] detector.cpu                   INFO    : Starting detection process: 546
2023-12-08 09:11:35.080907373  [2023-12-08 09:11:35] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-12-08 09:11:35.090396883  [2023-12-08 09:11:35] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
2023-12-08 09:11:35.090795074  [2023-12-08 09:11:35] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
2023-12-08 09:11:55.097251191  [2023-12-08 09:11:55] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
2023-12-08 09:11:55.097254037  [2023-12-08 09:11:55] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-12-08 09:11:55.097257002  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Splitting the commandline.
2023-12-08 09:11:55.097822007  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-hide_banner' ... matched as option 'hide_banner' (do not show program banner) with argument '1'.
2023-12-08 09:11:55.097824121  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-loglevel' ... matched as option 'loglevel' (set logging level) with argument 'debug'.
2023-12-08 09:11:55.097825425  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-hwaccel' ... matched as option 'hwaccel' (use HW accelerated decoding) with argument 'vaapi'.
2023-12-08 09:11:55.097827751  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-user_agent' ... matched as AVOption 'user_agent' with argument 'FFmpeg Frigate/0.12.1-367d724'.
2023-12-08 09:11:55.097829102  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'tcp'.
2023-12-08 09:11:55.097841667  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-timeout' ... matched as AVOption 'timeout' with argument '5000000'.
2023-12-08 09:11:55.097857487  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-i' ... matched as input url with argument 'rtsp://127.0.0.1/your_reolink_camera_sub?video=copy'.
2023-12-08 09:11:55.097858921  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-r' ... matched as option 'r' (set frame rate (Hz value, fraction or abbreviation)) with argument '5'.
2023-12-08 09:11:55.097860119  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-s' ... matched as option 's' (set frame size (WxH or abbreviation)) with argument '1280x720'.
2023-12-08 09:11:55.097861248  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-f' ... matched as option 'f' (force format) with argument 'rawvideo'.
2023-12-08 09:11:55.097871489  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-pix_fmt' ... matched as option 'pix_fmt' (set pixel format) with argument 'yuv420p'.
2023-12-08 09:11:55.097872752  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option '-filter:v' ... matched as option 'filter' (set stream filtergraph) with argument 'fps=fps=5'.
2023-12-08 09:11:55.097874040  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Reading option 'pipe:' ... matched as output url.
2023-12-08 09:11:55.097875040  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Finished splitting the commandline.
2023-12-08 09:11:55.097876040  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Parsing a group of options: global .
2023-12-08 09:11:55.097888212  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Applying option hide_banner (do not show program banner) with argument 1.
2023-12-08 09:11:55.098662233  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Applying option loglevel (set logging level) with argument debug.
2023-12-08 09:11:55.098663883  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Successfully parsed a group of options.
2023-12-08 09:11:55.098665125  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Parsing a group of options: input url rtsp://127.0.0.1/your_reolink_camera_sub?video=copy.
2023-12-08 09:11:55.098666257  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Applying option hwaccel (use HW accelerated decoding) with argument vaapi.
2023-12-08 09:11:55.098667291  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Successfully parsed a group of options.
2023-12-08 09:11:55.098668331  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : Opening an input file: rtsp://127.0.0.1/your_reolink_camera_sub?video=copy.
2023-12-08 09:11:55.098669333  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] No default whitelist set
2023-12-08 09:11:55.098670344  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] Original list of addresses:
2023-12-08 09:11:55.098671344  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] Address 127.0.0.1 port 554
2023-12-08 09:11:55.098672368  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] Interleaved list of addresses:
2023-12-08 09:11:55.098673382  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] Address 127.0.0.1 port 554
2023-12-08 09:11:55.098674491  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] Starting connection attempt to 127.0.0.1 port 554
2023-12-08 09:11:55.098675634  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] Connection attempt to 127.0.0.1 port 554 failed: Connection refused
2023-12-08 09:11:55.098676792  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : [tcp @ 0x556e3f8f9cc0] Connection to tcp://127.0.0.1:554?timeout=5000000 failed: Connection refused
2023-12-08 09:11:55.098677860  [2023-12-08 09:11:55] ffmpeg.reolink.detect          ERROR   : rtsp://127.0.0.1/your_reolink_camera_sub?video=copy: Connection refused
2023-12-08 09:11:55.107891644  [2023-12-08 09:11:55] frigate.video                  ERROR   : reolink: Unable to read frames from ffmpeg process.
2023-12-08 09:11:55.108161347  [2023-12-08 09:11:55] frigate.video                  ERROR   : reolink: ffmpeg process is not running. exiting capture thread...
2023-12-08 09:12:05.109038816  [2023-12-08 09:12:05] watchdog.reolink               ERROR   : Ffmpeg process crashed unexpectedly for reolink.
2023-12-08 09:12:05.109041699  [2023-12-08 09:12:05] watchdog.reolink               ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2023-12-08 09:12:05.109042919  [2023-12-08 09:12:05] ffmpeg.reolink.detect          ERROR   : Splitting the commandline.`

**Comment by justaCasualCoder** [comment]
VAAPI seems to be failing... Although it is not a fix , you can try removing 
```yaml
ffmpeg:
  hwaccel_args: preset-vaapi
```
from the Frigate config.
