### ISSUE TITLE
[Support]: Error when trying to edit an event to Frigate+ with an unknown label

### ISSUE THREAD

**Issue by xavan83** [blakeblackshear/frigate#8961]
### Describe the problem you are having

I receive an error when I try to edit an event with an unknown label (i.e. Motorcycle):

### Version

0.13.0-614A36A (beta6)

### Frigate config file

```yaml
Unrelevant
```

### Relevant log output

```shell
2023-12-14 11:33:01.233196615  [2023-12-14 11:33:01] frigate.http                   ERROR   : {"errors":[{"param":"label","type":"invalid_enum_value"}]}
2023-12-14 11:33:01.233199996  Traceback (most recent call last):
2023-12-14 11:33:01.233201394    File "/opt/frigate/frigate/http.py", line 338, in false_positive
2023-12-14 11:33:01.233202588      current_app.plus_api.add_false_positive(
2023-12-14 11:33:01.233203830    File "/opt/frigate/frigate/plus.py", line 174, in add_false_positive
2023-12-14 11:33:01.233204912      raise Exception(r.text)
2023-12-14 11:33:01.233206091  Exception: {"errors":[{"param":"label","type":"invalid_enum_value"}]}
```

### FFprobe output from your camera

```shell
Not relevant
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Hikvision

**Comment by blakeblackshear** [comment]
This is expected. You cannot submit a label to Frigate+ that it does not support.

**Comment by xavan83** [comment]
I understand but I use the detector and model given in the documentation:
detectors:
  ov:
    type: openvino
    device: GPU #AUTO
    model:
      path: /openvino-model/ssdlite_mobilenet_v2.xml
model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

It would be a nice behavior to either display a dialog explaining that frigate+ does not support this label or better to remove the "upload to frigate +" button for unsupported label
