### ISSUE TITLE
[Config Support]: Disk I/O Errors on First Deploy

### ISSUE THREAD

**Issue by ccigas** [blakeblackshear/frigate#8996]
### Describe the problem you are having

I am working on my first install of Frigate ever, using docker compose. I want my recordings on my storage server and I am using local paths for my db and config. Whenever I start the container I am getting a disk I/O errors and I think other errors. From my research it seems like its due to the db being added to the network share. I thought this was weird since I put in a path to a local directory. Despite this, the db still went to the network share. 

I then made the frigate.db on the local path and pointed directly to that file in the compose file and I still cant get passed these errors. 

```
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "2000mb" # used the python commands in the docs, should be around 15 total cameras, most of those 4k
    #devices:
    #  - /dev/bus/usb:/dev/bus/usb
    #  - /dev/dri/card1:/dev/dri/card1 # GPU device updated
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ccigas/frigate/config.yml:/config/config.yml
      - /mnt/container_storage/frigate:/media/frigate
      - /home/ccigas/frigate/db/frigate.db:/db/frigate.db
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    ports:
      - "5000:5000" # Web GUI
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: "password"

```

### Version

stable

### Frigate config file

```yaml
mqtt:
  enabled: False

cameras:
  Doorbell: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://admin:password@172.16.3.50:554/cam/realmonitor?channel=1&subtype=1 # <----- The stream you want to use for detection
          roles:
            - rtmp
```

### Relevant log output

```shell
s6-rc: info: service frigate-log: stopping
2023-12-18 01:52:20.651008421  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-12-18 01:52:20.657553549  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2023-12-18 01:52:25.741387602  [INFO] Preparing go2rtc config...
2023-12-18 01:52:25.741893744  [INFO] Starting Frigate...
2023-12-18 01:52:25.742574482  [INFO] Starting NGINX...
s6-rc: info: service legacy-services successfully started
2023-12-18 01:52:25.770694829  2023/12/18 01:52:25 [error] 134#134: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.1.3, server: , request: "GET /api/config HTTP/1.1", upstream: "http://127.0.0.1:5001/config", host: "frigate01:5000", referrer: "http://frigate01:5000/"
2023-12-18 01:52:25.770821264  172.16.1.3 - - [18/Dec/2023:01:52:25 +0000] "GET /api/config HTTP/1.1" 502 157 "http://frigate01:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0" "-"
2023-12-18 01:52:26.022435581  [INFO] Starting go2rtc...
2023-12-18 01:52:26.123786987  01:52:26.122 INF go2rtc version 1.2.0 linux/amd64
2023-12-18 01:52:26.123794087  01:52:26.122 INF [api] listen addr=:1984
2023-12-18 01:52:26.123797514  01:52:26.122 INF [rtsp] listen addr=:8554
2023-12-18 01:52:26.123800300  01:52:26.123 INF [srtp] listen addr=:8443
2023-12-18 01:52:26.123802818  01:52:26.123 INF [webrtc] listen addr=:8555
2023-12-18 01:52:27.173628888  [2023-12-18 01:52:27] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-18 01:52:27.209843300  [2023-12-18 01:52:27] peewee_migrate                 INFO    : Starting migrations
2023-12-18 01:52:27.223425787  [2023-12-18 01:52:27] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-18 01:52:27.244101088  [2023-12-18 01:52:27] frigate.app                    INFO    : Output process started: 433
2023-12-18 01:52:27.248879658  [2023-12-18 01:52:27] detector.cpu                   INFO    : Starting detection process: 432
2023-12-18 01:52:27.249588763  [2023-12-18 01:52:27] frigate.app                    INFO    : Camera processor started for Doorbell: 436
2023-12-18 01:52:27.254986434  [2023-12-18 01:52:27] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2023-12-18 01:52:27.259108012  [2023-12-18 01:52:27] frigate.app                    INFO    : Capture process started for Doorbell: 438
2023-12-18 01:52:27.446735362  Exception in thread event_processor:
2023-12-18 01:52:27.446788417  Traceback (most recent call last):
2023-12-18 01:52:27.446790709    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3237, in execute_sql
2023-12-18 01:52:27.447856344      cursor.execute(sql, params or ())
2023-12-18 01:52:27.447885206  sqlite3.OperationalError: disk I/O error
2023-12-18 01:52:27.447887155  
2023-12-18 01:52:27.447888846  During handling of the above exception, another exception occurred:
2023-12-18 01:52:27.447890090  
2023-12-18 01:52:27.447907611  Traceback (most recent call last):
2023-12-18 01:52:27.447909398    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2023-12-18 01:52:27.448216418      self.run()
2023-12-18 01:52:27.448219118    File "/opt/frigate/frigate/events.py", line 64, in run
2023-12-18 01:52:27.448378900      Event.update(end_time=Event.start_time + 30).where(
2023-12-18 01:52:27.448382620    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 1962, in inner
2023-12-18 01:52:27.448924415      return method(self, database, *args, **kwargs)
2023-12-18 01:52:27.448928015    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2033, in execute
2023-12-18 01:52:27.449464663      return self._execute(database)
2023-12-18 01:52:27.449468244    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2552, in _execute
2023-12-18 01:52:27.450031753      return self.handle_result(database, cursor)
2023-12-18 01:52:27.450035444    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 2563, in handle_result
2023-12-18 01:52:27.450638841      return database.rows_affected(cursor)
2023-12-18 01:52:27.450642327    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3753, in rows_affected
2023-12-18 01:52:27.451518410      return cursor.rowcount
2023-12-18 01:52:27.451521874    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 94, in rowcount
2023-12-18 01:52:27.451659111      self._wait()
2023-12-18 01:52:27.451661707    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 63, in _wait
2023-12-18 01:52:27.451825758      raise self._exc
2023-12-18 01:52:27.451828111    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 178, in execute
2023-12-18 01:52:27.451972273      cursor = self.database._execute(obj.sql, obj.params, obj.commit)
2023-12-18 01:52:27.451974565    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3244, in execute_sql
2023-12-18 01:52:27.452659204      self.commit()
2023-12-18 01:52:27.452662739    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3010, in __exit__
2023-12-18 01:52:27.453302524      reraise(new_type, new_type(exc_value, *exc_args), traceback)
2023-12-18 01:52:27.453306154    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
2023-12-18 01:52:27.453387822      raise value.with_traceback(tb)
2023-12-18 01:52:27.453390398    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3237, in execute_sql
2023-12-18 01:52:27.454072095      cursor.execute(sql, params or ())
2023-12-18 01:52:27.454075477  peewee.OperationalError: disk I/O error
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

I am using portainer to help me deploy

**Comment by ccigas** [comment]
Did some more testing and for anyone that will need this, I had to add the /clips and /recordings to get this to work. 

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ccigas/frigate/config.yml:/config/config.yml
      - /mnt/container_storage/frigate/recordings:/media/frigate/recordings
      - /mnt/container_storage/frigate/clips:/media/frigate/clips
      - /home/ccigas/frigate/db/frigate.db:/db/frigate.db
```

**Comment by NickM-27** [comment]
feel free to create a new issue if something else comes up

**Comment by vazquezjm** [comment]
This worked for me as well. Thanks @ccigas
