### ISSUE TITLE
[Camera Support]: Autotracking on a Imoa (Dahua) 

### ISSUE THREAD

**Issue by EM-Tom** [blakeblackshear/frigate#9056]
### Describe the problem you are having

I suspect this isn't an actual issue and is because I am using a poor mans PT camera - but wanted to check. 

Run the useful python script, which suggests the IMOU Ranger 2C supports Relative FOV

Connected to ONVIF camera
Created media service object
Creating PTZ object
Created PTZ service object
YES - RelativeMove Pan/Tilt within the camera's field of view is supported.
NO - RelativeMove Zoom is unsupported.

However - If I start frigate with the config included, it wont start and returns the error included. Is this to be expected due to the cameras (maybe) poor ONVIF implementation? As an aside, PT works perfectly manually in Frigate. 

Thanks as always. 

### Version

13.0 B5

### Frigate config file

```yaml
#######################
  ##### INSIDE 1  ###
  #######################
  inside_1:
    onvif:
      host: http://someIP/onvif/device_service
      port: 80
      user: admin
      password: somePass
      autotracking:
        enabled: True
        calibrate_on_startup: True
        zooming: disabled
        required_zones:
          - all
        return_preset: home
    ffmpeg:
      inputs:
        - path: rtsp://admin:somePass@someIP:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
          roles:
            - detect
    detect:
      fps: 5
    objects:
      track:
        - person
        - face
    zones:
      all:
        coordinates: 89,1393,2509,1373,2482,76,0,42
    snapshots:
      enabled: True
      retain:
        default: 3
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 30
          mode: active_objects
```

### Relevant log output

```shell
2023-12-22 20:18:58.208804317  Traceback (most recent call last):

2023-12-22 20:18:58.208830529    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main

2023-12-22 20:18:58.251032090      return _run_code(code, main_globals, None,

2023-12-22 20:18:58.251035302    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code

2023-12-22 20:18:58.251369692      exec(code, run_globals)

2023-12-22 20:18:58.251372825    File "/opt/frigate/frigate/__main__.py", line 17, in <module>

2023-12-22 20:18:58.264082564      frigate_app.start()

2023-12-22 20:18:58.264086028    File "/opt/frigate/frigate/app.py", line 684, in start

2023-12-22 20:18:58.265779059      self.start_ptz_autotracker()

2023-12-22 20:18:58.265782276    File "/opt/frigate/frigate/app.py", line 460, in start_ptz_autotracker

2023-12-22 20:18:58.266015370      self.ptz_autotracker_thread = PtzAutoTrackerThread(

2023-12-22 20:18:58.266018303    File "/opt/frigate/frigate/ptz/autotrack.py", line 153, in __init__

2023-12-22 20:18:58.267091643      self.ptz_autotracker = PtzAutoTracker(config, onvif, ptz_metrics, dispatcher)

2023-12-22 20:18:58.267094620    File "/opt/frigate/frigate/ptz/autotrack.py", line 208, in __init__

2023-12-22 20:18:58.267421545      self._autotracker_setup(camera_config, camera)

2023-12-22 20:18:58.267424598    File "/opt/frigate/frigate/ptz/autotrack.py", line 263, in _autotracker_setup

2023-12-22 20:18:58.267504712      self.onvif.get_camera_status(camera)

2023-12-22 20:18:58.267519074    File "/opt/frigate/frigate/ptz/onvif.py", line 533, in get_camera_status

2023-12-22 20:18:58.268651666      if pan_tilt_status is None or pan_tilt_status.lower() not in [

2023-12-22 20:18:58.268654342    File "/usr/local/lib/python3.9/dist-packages/zeep/xsd/valueobjects.py", line 156, in __getattribute__

2023-12-22 20:18:58.268883303      raise AttributeError(AttributeError: PTZMoveStatus instance has no attribute 'lower'
```

### FFprobe output from your camera

```shell
Ffprobe Output
Stream 0:
Return Code: 0

Video:

Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Resolution: 2560x1440
FPS: 25/1

Audio:

Codec: AAC (Advanced Audio Coding)

Audio:

Codec:
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

IMOU Ranger 2c

**Comment by hawkeye217** [comment]
Even though Dahua makes Imou cameras, we've found that they purposely cripple features (including ONVIF) in firmware. From what I can recall, no user has reported success with autotracking on Imou cameras.

Frigate could better handle the error you're seeing. Some changes were made in this part of the code and pushed in 0.13-beta 6, but it isn't likely to change your outcome.

It would be interesting to see what gets reported back from your camera on startup.

Could you enable debug logging like this:

```
logger:
  default: info
  logs:
    frigate.ptz.autotrack: debug
    frigate.ptz.onvif: debug
```


Then restart, frigate, and paste the debug output here?

**Comment by EM-Tom** [comment]
Thanks a lot for your response, I guessed it's probably the case they are super cheap, I bought them to mess around with PTZ frigate config and automations. I am way out of my depth now, logs below. 

`2023-12-22 21:16:34.066920469  [2023-12-22 21:16:34] frigate.ptz.onvif              DEBUG   : Onvif configs for inside_1: {
2023-12-22 21:16:34.066923840      'Name': 'PTZ000',
2023-12-22 21:16:34.066925135      'UseCount': 2,
2023-12-22 21:16:34.066926263      'NodeToken': 'PTZ000',
2023-12-22 21:16:34.066929865      'DefaultAbsolutePantTiltPositionSpace': None,
2023-12-22 21:16:34.066931204      'DefaultAbsoluteZoomPositionSpace': None,
2023-12-22 21:16:34.066947477      'DefaultRelativePanTiltTranslationSpace': None,
2023-12-22 21:16:34.066948771      'DefaultRelativeZoomTranslationSpace': None,
2023-12-22 21:16:34.066950581      'DefaultContinuousPanTiltVelocitySpace': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
2023-12-22 21:16:34.066951787      'DefaultContinuousZoomVelocitySpace': None,
2023-12-22 21:16:34.066952843      'DefaultPTZSpeed': {
2023-12-22 21:16:34.066983405          'PanTilt': {
2023-12-22 21:16:34.066984512              'x': 0.8,
2023-12-22 21:16:34.066985521              'y': 0.8,
2023-12-22 21:16:34.066986833              'space': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace'
2023-12-22 21:16:34.066987791          },
2023-12-22 21:16:34.066999169          'Zoom': None
2023-12-22 21:16:34.067000220      },
2023-12-22 21:16:34.067001309      'DefaultPTZTimeout': datetime.timedelta(seconds=10),
2023-12-22 21:16:34.067002413      'PanTiltLimits': None,
2023-12-22 21:16:34.067003408      'ZoomLimits': None,
2023-12-22 21:16:34.067004430      'Extension': None,
2023-12-22 21:16:34.067005399      'token': 'PTZ000',
2023-12-22 21:16:34.067006406      '_attr_1': {
2023-12-22 21:16:34.067007429          'MoveRamp': '0',
2023-12-22 21:16:34.067008412          'PresetRamp': '0',
2023-12-22 21:16:34.067009455          'PresetTourRamp': '0'
2023-12-22 21:16:34.067021734      }
2023-12-22 21:16:34.067022761  }
2023-12-22 21:16:34.751131114  [2023-12-22 21:16:34] frigate.ptz.onvif              DEBUG   : Onvif config for inside_1: {
2023-12-22 21:16:34.751146601      'Spaces': {
2023-12-22 21:16:34.751147977          'AbsolutePanTiltPositionSpace': [
2023-12-22 21:16:34.751149160              {
2023-12-22 21:16:34.751150596                  'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace',
2023-12-22 21:16:34.751151721                  'XRange': {
2023-12-22 21:16:34.751152843                      'Min': -1.0,
2023-12-22 21:16:34.751153948                      'Max': 1.0
2023-12-22 21:16:34.751154933                  },
2023-12-22 21:16:34.751156029                  'YRange': {
2023-12-22 21:16:34.751157084                      'Min': -1.0,
2023-12-22 21:16:34.751158158                      'Max': 1.0
2023-12-22 21:16:34.751159151                  }
2023-12-22 21:16:34.751160141              }
2023-12-22 21:16:34.751161140          ],
2023-12-22 21:16:34.751162244          'AbsoluteZoomPositionSpace': [],
2023-12-22 21:16:34.751163354          'RelativePanTiltTranslationSpace': [
2023-12-22 21:16:34.751164304              {
2023-12-22 21:16:34.751165614                  'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace',
2023-12-22 21:16:34.751166769                  'XRange': {
2023-12-22 21:16:34.751167780                      'Min': -1.0,
2023-12-22 21:16:34.751168837                      'Max': 1.0
2023-12-22 21:16:34.751169809                  },
2023-12-22 21:16:34.751170807                  'YRange': {
2023-12-22 21:16:34.751171859                      'Min': -1.0,
2023-12-22 21:16:34.751172887                      'Max': 1.0
2023-12-22 21:16:34.751173825                  }
2023-12-22 21:16:34.751174830              },
2023-12-22 21:16:34.751175824              {
2023-12-22 21:16:34.751177087                  'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationSpaceFov',
2023-12-22 21:16:34.751178069                  'XRange': {
2023-12-22 21:16:34.751179079                      'Min': -1.0,
2023-12-22 21:16:34.751181080                      'Max': 1.0
2023-12-22 21:16:34.751182045                  },
2023-12-22 21:16:34.751183049                  'YRange': {
2023-12-22 21:16:34.751184061                      'Min': -1.0,
2023-12-22 21:16:34.751185069                      'Max': 1.0
2023-12-22 21:16:34.751187397                  }
2023-12-22 21:16:34.751188396              }
2023-12-22 21:16:34.751189334          ],
2023-12-22 21:16:34.751190464          'RelativeZoomTranslationSpace': [],
2023-12-22 21:16:34.751191503          'ContinuousPanTiltVelocitySpace': [
2023-12-22 21:16:34.751192490              {
2023-12-22 21:16:34.751220885                  'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace',
2023-12-22 21:16:34.751222006                  'XRange': {
2023-12-22 21:16:34.751223005                      'Min': -1.0,
2023-12-22 21:16:34.751223986                      'Max': 1.0
2023-12-22 21:16:34.751224944                  },
2023-12-22 21:16:34.751226091                  'YRange': {
2023-12-22 21:16:34.751227098                      'Min': -1.0,
2023-12-22 21:16:34.751228113                      'Max': 1.0
2023-12-22 21:16:34.751229076                  }
2023-12-22 21:16:34.751230033              }
2023-12-22 21:16:34.751231010          ],
2023-12-22 21:16:34.751232070          'ContinuousZoomVelocitySpace': [],
2023-12-22 21:16:34.751233176          'PanTiltSpeedSpace': [
2023-12-22 21:16:34.751234210              {
2023-12-22 21:16:34.751235484                  'URI': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace',
2023-12-22 21:16:34.751236495                  'XRange': {
2023-12-22 21:16:34.751237494                      'Min': 0.0,
2023-12-22 21:16:34.751238531                      'Max': 1.0
2023-12-22 21:16:34.751239508                  }
2023-12-22 21:16:34.751259260              }
2023-12-22 21:16:34.751260292          ],
2023-12-22 21:16:34.751261343          'ZoomSpeedSpace': [],
2023-12-22 21:16:34.751262341          'Extension': None,
2023-12-22 21:16:34.751263337          '_attr_1': None
2023-12-22 21:16:34.751264314      },
2023-12-22 21:16:34.751265334      'PTZTimeout': {
2023-12-22 21:16:34.751266433          'Min': datetime.timedelta(seconds=1),
2023-12-22 21:16:34.751267495          'Max': datetime.timedelta(seconds=10)
2023-12-22 21:16:34.751268570      },
2023-12-22 21:16:34.751269582      '_value_1': None,
2023-12-22 21:16:34.751270579      'PTControlDirection': None,
2023-12-22 21:16:34.751271577      'Extension': None,
2023-12-22 21:16:34.751272589      '_attr_1': None
2023-12-22 21:16:34.751273488  }
2023-12-22 21:16:35.027281197  [2023-12-22 21:16:35] frigate.ptz.onvif              DEBUG   : Onvif status config for inside_1: {
2023-12-22 21:16:35.027284412      'Position': {
2023-12-22 21:16:35.027285636          'PanTilt': {
2023-12-22 21:16:35.027286758              'x': 0.8,
2023-12-22 21:16:35.027287820              'y': 0.8,
2023-12-22 21:16:35.027289133              'space': 'http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace'
2023-12-22 21:16:35.027290156          },
2023-12-22 21:16:35.027291222          'Zoom': None
2023-12-22 21:16:35.027292223      },
2023-12-22 21:16:35.027293215      'MoveStatus': {
2023-12-22 21:16:35.027294242          'PanTilt': None,
2023-12-22 21:16:35.027295238          'Zoom': 'IDLE'
2023-12-22 21:16:35.027296175      },
2023-12-22 21:16:35.027297148      'Error': None,
2023-12-22 21:16:35.027298478      'UtcTime': datetime.datetime(2023, 12, 22, 21, 16, 34, tzinfo=<isodate.tzinfo.Utc object at 0x7f5460327b50>),
2023-12-22 21:16:35.027299488      '_value_1': None,
2023-12-22 21:16:35.027300465      '_attr_1': None
2023-12-22 21:16:35.027301411  }
2023-12-22 21:16:35.186631491  [2023-12-22 21:16:35] frigate.ptz.onvif              WARNING : Unable to get presets from camera: inside_1: Unknown error: This optional method is not implemented
2023-12-22 21:16:35.686374733  [2023-12-22 21:16:35] frigate.ptz.onvif              DEBUG   : Onvif service capabilities for inside_1: {
2023-12-22 21:16:35.686377730      '_value_1': None,
2023-12-22 21:16:35.686379005      'EFlip': False,
2023-12-22 21:16:35.686380206      'Reverse': False,
2023-12-22 21:16:35.686381414      'GetCompatibleConfigurations': True,
2023-12-22 21:16:35.686382553      '_attr_1': {
2023-12-22 21:16:35.686383711          'MoveStatus': 'true',
2023-12-22 21:16:35.686384863          'StatusPosition': 'true'
2023-12-22 21:16:35.686385944      }
2023-12-22 21:16:35.686387014  }
2023-12-22 21:16:35.905362685  [2023-12-22 21:16:35] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2023-12-22 21:16:35.930067153  Traceback (most recent call last):
2023-12-22 21:16:35.930070420    File "/usr/local/lib/python3.9/dist-packages/zeep/xsd/valueobjects.py", line 154, in __getattribute__
2023-12-22 21:16:35.942822922      return self.__values__[key]
2023-12-22 21:16:35.942826026  KeyError: 'lower'
2023-12-22 21:16:35.942840148  
2023-12-22 21:16:35.942841556  During handling of the above exception, another exception occurred:
2023-12-22 21:16:35.942842589  
2023-12-22 21:16:35.942843720  Traceback (most recent call last):
2023-12-22 21:16:35.942844984    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-12-22 21:16:35.951337241      return _run_code(code, main_globals, None,
2023-12-22 21:16:35.951352882    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-12-22 21:16:35.951532533      exec(code, run_globals)
2023-12-22 21:16:35.951534857    File "/opt/frigate/frigate/__main__.py", line 17, in <module>
2023-12-22 21:16:35.956191347      frigate_app.start()
2023-12-22 21:16:35.956193504    File "/opt/frigate/frigate/app.py", line 684, in start
2023-12-22 21:16:35.957380170      self.start_ptz_autotracker()
2023-12-22 21:16:35.957382518    File "/opt/frigate/frigate/app.py", line 460, in start_ptz_autotracker
2023-12-22 21:16:35.957696505      self.ptz_autotracker_thread = PtzAutoTrackerThread(
2023-12-22 21:16:35.957698955    File "/opt/frigate/frigate/ptz/autotrack.py", line 153, in __init__
2023-12-22 21:16:35.958065410      self.ptz_autotracker = PtzAutoTracker(config, onvif, ptz_metrics, dispatcher)
2023-12-22 21:16:35.958067650    File "/opt/frigate/frigate/ptz/autotrack.py", line 208, in __init__
2023-12-22 21:16:35.958184977      self._autotracker_setup(camera_config, camera)
2023-12-22 21:16:35.958200158    File "/opt/frigate/frigate/ptz/autotrack.py", line 263, in _autotracker_setup
2023-12-22 21:16:35.958350794      self.onvif.get_camera_status(camera)
2023-12-22 21:16:35.958353190    File "/opt/frigate/frigate/ptz/onvif.py", line 533, in get_camera_status
2023-12-22 21:16:35.958953338      if pan_tilt_status is None or pan_tilt_status.lower() not in [
2023-12-22 21:16:35.958955556    File "/usr/local/lib/python3.9/dist-packages/zeep/xsd/valueobjects.py", line 156, in __getattribute__
2023-12-22 21:16:35.959141826      raise AttributeError(
2023-12-22 21:16:35.959143998  AttributeError: PTZMoveStatus instance has no attribute 'lower'`

**Comment by hawkeye217** [comment]
Thanks. Your camera shows a `None` value for the `PanTilt` `MoveStatus`, which an ONVIF parameter that indicates what your pan/tilt motor is doing (usually it's `MOVING` or `IDLE`).

Frigate's autotracking relies on this parameter from your camera's firmware to be valid to determine when another movement can be made. 

Unfortunately your Imou camera is no different than the others we've seen.

**Comment by NickM-27** [comment]
At this time things are working as expected it seems so closing 👍

**Comment by EM-Tom** [comment]
There goes my £20 pipe dream! Thanks a lot for your support,  really appreciate it - as always.

**Comment by hawkeye217** [comment]
Happy to help. Keep your eye on future versions of frigate though, we're always looking for ways to support more cameras.
