### ISSUE TITLE
[Detector Support]: 

### ISSUE THREAD

**Issue by Triskelen** [blakeblackshear/frigate#9078]
### Describe the problem you are having

After installing the Usb Coral TPU on a usb 3.1 slot camera's cut out and produce the error "No frames have been received, check error logs" and the addon in HOAS crashes and the addon is responding very slugish (slow)

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:

info comes here

# Problems started after adding code below 
detectors:
  coral:
    type: edgetpu
    device: usb
# Problems stated after adding code above

environment_vars:
  LIBVA_DRIVER_NAME: i965

birdseye:
  enabled: False

cameras:
  woonkamer:
    ffmpeg:
      inputs:
        - path: cam1
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 15
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 10
        required_zones:
          - "woonkamer_area"
    mqtt:
      required_zones:
        - "woonkamer_area"
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - woonkamer_area
      retain:
        default: 15
        objects:
          person: 20
    objects:
      filters:
        person:
          mask: 1538,304,1542,429
    motion:
      mask:
        - 303,0,304,28,0,36,0,0
        - 0,801,0,1080,1920,1080,1920,792
    zones:
      woonkamer_area:
        coordinates: 0,819,1920,796,1920,73,0,70
        objects:  
          - person
        filters:
            person:
              threshold: 0.5


  keuken:
    ffmpeg:
      inputs:
        - path: cam2
          roles:
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
    record:
      enabled: true
      retain:
        days: 2
      events:
        retain:
          default: 10
        required_zones:
          - "keuken_area"
    mqtt:
      required_zones:
        - "keuken_area"
    snapshots:
      enabled: True
      clean_copy: True
      timestamp: True
      bounding_box: True
      crop: False
      required_zones:
        - keuken_area
    objects:
      filters:
        person:
          mask: 951,398,951,608,855,597,873,394
    motion:
      mask:
        - 0,0,635,0,635,1080,0,1080
        - 633,0,626,84,788,102,975,124,1212,158,1523,227,1920,129,1920,0
    zones:
      keuken_area:
        coordinates: 1920,0,1920,1080,631,1080,635,0
        objects:  
          - person
        filters:
            person:
              threshold: 0.5



objects:
  track:
    - person
  filters:
      person:
          min_area: 5000
          max_area: 100000
```

### docker-compose file or Docker CLI command

```yaml
HAOS
```

### Relevant log output

```shell
2023-12-26 16:37:28.478095844  17:37:28.478 INF [webrtc] listen addr=:8555
2023-12-26 16:37:29.858501133  [2023-12-26 17:37:29] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-12-26 16:37:29.910836439  [2023-12-26 17:37:29] frigate.app                    INFO    : Creating directory: /tmp/cache
2023-12-26 16:37:29.914031109  [2023-12-26 17:37:29] peewee_migrate                 INFO    : Starting migrations
2023-12-26 16:37:29.920721237  [2023-12-26 17:37:29] peewee_migrate                 INFO    : There is nothing to migrate
2023-12-26 16:37:29.962143409  [2023-12-26 17:37:29] frigate.app                    INFO    : Output process started: 301
2023-12-26 16:37:29.976221632  [2023-12-26 17:37:29] frigate.app                    INFO    : Camera processor started for woonkamer: 304
2023-12-26 16:37:29.982220521  [2023-12-26 17:37:29] frigate.app                    INFO    : Camera processor started for keuken: 308
2023-12-26 16:37:29.988655051  [2023-12-26 17:37:29] frigate.app                    INFO    : Capture process started for woonkamer: 310
2023-12-26 16:37:29.995931384  [2023-12-26 17:37:29] frigate.app                    INFO    : Capture process started for keuken: 312
2023-12-26 16:37:32.047500018  172.30.32.2 - - [26/Dec/2023:17:37:32 +0100] "GET // HTTP/1.1" 200 6699 "http://192.168.50.202:8123/ccab4aaf_frigate-fa" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "192.168.50.157, 172.30.32.1"
2023-12-26 16:37:32.087956657  172.30.32.2 - - [26/Dec/2023:17:37:32 +0100] "GET /api/config HTTP/1.1" 200 7945 "http://192.168.50.202:8123/api/hassio_ingress/bJvl2lU1LnZAOKnx4ThHW3RnefhTZW57CEbxT7gBNZw//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "192.168.50.157, 172.30.32.1"
2023-12-26 16:37:32.245448320  172.30.32.2 - - [26/Dec/2023:17:37:32 +0100] "GET //api/keuken/latest.jpg?h=275 HTTP/1.1" 200 6801 "http://192.168.50.202:8123/api/hassio_ingress/bJvl2lU1LnZAOKnx4ThHW3RnefhTZW57CEbxT7gBNZw//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "192.168.50.157, 172.30.32.1"
2023-12-26 16:37:32.257046224  172.30.32.2 - - [26/Dec/2023:17:37:32 +0100] "GET //api/woonkamer/latest.jpg?h=275 HTTP/1.1" 200 6801 "http://192.168.50.202:8123/api/hassio_ingress/bJvl2lU1LnZAOKnx4ThHW3RnefhTZW57CEbxT7gBNZw//" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "192.168.50.157, 172.30.32.1"
2023-12-26 16:37:36.265688840  172.30.32.1 - - [26/Dec/2023:17:37:36 +0100] "GET /api/stats HTTP/1.1" 200 2310 "-" "HomeAssistant/2023.12.3 aiohttp/3.9.1 Python/3.11" "-"
2023-12-26 16:37:37.923425475  [INFO] Starting go2rtc healthcheck service...
2023-12-26 16:37:39.052001103  172.30.32.2 - - [26/Dec/2023:17:37:39 +0100] "GET / HTTP/1.1" 200 6641 "-" "HomeAssistantSupervisor/2023.12.0 aiohttp/3.9.1 Python/3.11" "-"
2023-12-26 16:37:44.275020236  172.30.32.1 - - [26/Dec/2023:17:37:44 +0100] "GET /api/stats HTTP/1.1" 200 2324 "-" "HomeAssistant/2023.12.3 aiohttp/3.9.1 Python/3.11" "-"
2023-12-26 16:37:52.275830385  172.30.32.1 - - [26/Dec/2023:17:37:52 +0100] "GET /api/stats HTTP/1.1" 200 2312 "-" "HomeAssistant/2023.12.3 aiohttp/3.9.1 Python/3.11" "-"
2023-12-26 16:37:55.041322966  [2023-12-26 17:37:29] detector.coral                 INFO    : Starting detection process: 300
2023-12-26 16:37:55.041587666  [2023-12-26 17:37:29] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-12-26 16:37:55.041857053  [2023-12-26 17:37:55] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-12-26 16:37:55.042255679  Process detector:coral:
2023-12-26 16:37:55.044228042  Traceback (most recent call last):
2023-12-26 16:37:55.044252459    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-12-26 16:37:55.044255098      delegate = Delegate(library, options)
2023-12-26 16:37:55.044257511    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-12-26 16:37:55.044263464      raise ValueError(capture.message)
2023-12-26 16:37:55.044280056  ValueError
2023-12-26 16:37:55.044297389  
2023-12-26 16:37:55.044300135  During handling of the above exception, another exception occurred:
2023-12-26 16:37:55.044301577  
2023-12-26 16:37:55.044303272  Traceback (most recent call last):
2023-12-26 16:37:55.044344754    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-12-26 16:37:55.044347257      self.run()
2023-12-26 16:37:55.044349448    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-12-26 16:37:55.044351348      self._target(*self._args, **self._kwargs)
2023-12-26 16:37:55.044353447    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-12-26 16:37:55.044355537      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-12-26 16:37:55.044376117    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-12-26 16:37:55.044378790      self.detect_api = create_detector(detector_config)
2023-12-26 16:37:55.044380906    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-12-26 16:37:55.044382671      return api(detector_config)
2023-12-26 16:37:55.044384807    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-12-26 16:37:55.044386961      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-12-26 16:37:55.044389135    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-12-26 16:37:55.044424002      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-12-26 16:37:55.044426928  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-12-26 16:37:55.044428456  
2023-12-26 16:38:00.275672809  172.30.32.1 - - [26/Dec/2023:17:38:00 +0100] "GET /api/stats HTTP/1.1" 200 2312 "-" "HomeAssistant/2023.12.3 aiohttp/3.9.1 Python/3.11" "-"
2023-12-26 16:38:00.277365864  [2023-12-26 17:38:00] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-12-26 16:38:00.291776301  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-12-26 16:38:00.314443327  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
2023-12-26 16:38:00.317380782  [2023-12-26 17:38:00] frigate.app                    INFO    : Stopping...
2023-12-26 16:38:00.318358824  [2023-12-26 17:38:00] frigate.record                 INFO    : Exiting recording cleanup...
2023-12-26 16:38:00.318365322  [2023-12-26 17:38:00] frigate.storage                INFO    : Exiting storage maintainer...
2023-12-26 16:38:00.324390452  [2023-12-26 17:38:00] frigate.events                 INFO    : Exiting event cleanup...
2023-12-26 16:38:00.324399359  [2023-12-26 17:38:00] frigate.watchdog               INFO    : Exiting watchdog...
2023-12-26 16:38:00.324401350  [2023-12-26 17:38:00] frigate.record                 INFO    : Exiting recording maintenance...
2023-12-26 16:38:00.324403148  [2023-12-26 17:38:00] frigate.stats                  INFO    : Exiting stats emitter...
2023-12-26 16:38:00.324404877  [2023-12-26 17:38:00] frigate.object_processing      INFO    : Exiting object processor...
2023-12-26 16:38:00.644296504  [2023-12-26 17:38:00] frigate.comms.ws               INFO    : Exiting websocket client...
2023-12-26 16:38:01.306749944  [2023-12-26 17:38:01] frigate.events                 INFO    : Exiting event processor...
2023-12-26 16:38:01.307550715  [2023-12-26 17:38:01] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2023-12-26 16:38:01.313720142  [2023-12-26 17:38:01] watchdog.woonkamer             INFO    : Terminating the existing ffmpeg process...
2023-12-26 16:38:01.313844511  [2023-12-26 17:38:01] watchdog.woonkamer             INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-26 16:38:01.314100187  [2023-12-26 17:38:01] watchdog.keuken                INFO    : Terminating the existing ffmpeg process...
2023-12-26 16:38:01.314258250  [2023-12-26 17:38:01] watchdog.keuken                INFO    : Waiting for ffmpeg to exit gracefully...
2023-12-26 16:38:01.550829755  [2023-12-26 17:38:01] frigate.output                 INFO    : exiting output process...
2023-12-26 16:38:05.669851907  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked shared_memory objects to clean up at shutdown
2023-12-26 16:38:05.669859720    warnings.warn('resource_tracker: There appear to be %d '
2023-12-26 16:38:05.673706977  [INFO] Service Frigate exited with code 0 (by signal 0)
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2023-12-26 16:38:05.677027639  exit OK
s6-rc: info: service frigate-log successfully stopped
2023-12-26 16:38:05.683534982  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

**Comment by NickM-27** [comment]
Coral is not detected, which version & variant of the addon are you using

**Comment by Triskelen** [comment]
Frigate (Full Access)
Current version: 0.12.1

**Comment by NickM-27** [comment]
Is protected mode disabled?

**Comment by Triskelen** [comment]
Yes

**Comment by Triskelen** [comment]
2023-12-26 17:16:25.678567929  [2023-12-26 18:16:25] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-12-26 17:16:29.663879176  [2023-12-26 18:16:29] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found

**Comment by Triskelen** [comment]
Hmmm now i can't turn off detection it's on and it stays on

**Comment by NickM-27** [comment]
What are the current logs?

**Comment by Triskelen** [comment]
The logs don't produce any errors so far. I can turn them on and off with home assistant automation
But can't turn on/off by clicking the options below the camera frame.

![Screenshot_20231228_124841_Home Assistant](https://github.com/blakeblackshear/frigate/assets/25891156/71573fc3-bf7c-48b8-a984-c83cacc98b56)

Also is it normal that the TPU is always at 0,0% 1,4 memory ? Never seen those values change and frigate stil uses about 30-40% cpu

**Comment by NickM-27** [comment]
you are not using hwaccel_args which is why CPU usage will be higher

**Comment by Triskelen** [comment]
I tried using hardware acceleration but it did not work out at all and would brake frigate or maybe I did something wrong
