### ISSUE TITLE
[Support]: Send to Frigate+ fails 

### ISSUE THREAD

**Issue by jasonjgeiger** [blakeblackshear/frigate#9113]
### Describe the problem you are having

Using the "Send to Frigate+" button for an event returns a 400 error and the docker container log throws "Unable to refresh API token". 

<img width="397" alt="Screenshot 2023-12-28 at 10 40 27 PM" src="https://github.com/blakeblackshear/frigate/assets/448523/8790a8b4-fa38-4844-8d57-4c0e0a33cad5">

### Version

0.12.1

### Frigate config file

```yaml
N/A
```

### Relevant log output

```shell
Frigate Logs
----
2023-12-29 06:21:14.150540453  [2023-12-28 22:21:14] frigate.http                   ERROR   : Unable to refresh API token
2023-12-29 06:21:14.150543180  Traceback (most recent call last):
2023-12-29 06:21:14.150544317    File "/opt/frigate/frigate/http.py", line 229, in send_to_plus
2023-12-29 06:21:14.150545356      plus_id = current_app.plus_api.upload_image(image, event.camera)
2023-12-29 06:21:14.150547149    File "/opt/frigate/frigate/plus.py", line 86, in upload_image
2023-12-29 06:21:14.150559657      r = self._get("image/signed_urls")
2023-12-29 06:21:14.150560648    File "/opt/frigate/frigate/plus.py", line 72, in _get
2023-12-29 06:21:14.150562010      f"{self.host}/v1/{path}", headers=self._get_authorization_header()
2023-12-29 06:21:14.150563059    File "/opt/frigate/frigate/plus.py", line 67, in _get_authorization_header
2023-12-29 06:21:14.150563973      self._refresh_token_if_needed()
2023-12-29 06:21:14.150564941    File "/opt/frigate/frigate/plus.py", line 63, in _refresh_token_if_needed
2023-12-29 06:21:14.150576408      raise Exception("Unable to refresh API token")


Browser Console Log
----
index-40e1e50b.js:16 
        
POST http://local.domain/api/events/1703829564.359989-l7njek/plus 400 (BAD REQUEST)
(anonymous) @ index-40e1e50b.js:16
xhr @ index-40e1e50b.js:16
Lr @ index-40e1e50b.js:16
request @ index-40e1e50b.js:16
(anonymous) @ index-40e1e50b.js:16
(anonymous) @ index-40e1e50b.js:14
$ @ Events-b7429126.js:14
onClick @ Events-b7429126.js:14
Gn @ index-40e1e50b.js:1
index-40e1e50b.js:16 Uncaught (in promise) E {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_REQUEST"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Request failed with status code 400"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {data: {…}, status: 400, statusText: 'BAD REQUEST', headers: Tt, config: {…}, …}stack: "AxiosError: Request failed with status code 400\n    at qa (http://local.domain/assets/index-40e1e50b.js:16:947)\n    at XMLHttpRequest.d (http://local.domain/assets/index-40e1e50b.js:16:4043)"[[Prototype]]: Error
$ @ Events-b7429126.js:14
await in $ (async)
onClick @ Events-b7429126.js:14
Gn @ index-40e1e50b.js:1
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

M.2

### Any other information that may be helpful

Docker-compose.yml
----
version: "3.7"

services:
  frigate:
    container_name: frigate-12
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.12.1
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml
      - /mnt/frigate_data:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "80:5000"
      - "1935:1935" # RTMP feeds
    environment:
      FRIGATE_RTSP_PASSWORD: "nunya"
      PLUS_API_KEY: "aa..."
      TZ: "America/Los_Angeles"

**Comment by blakeblackshear** [comment]
Does this always happen or just occasionally?

**Comment by jasonjgeiger** [comment]
Every time. Woke this morning with the thought that the only thing I didn't try was refreshing my API key in Frigate+ again. Regenerated a new key, updated docker-compose and it's working and no error.s

I'll reopen if the issue comes back.
