### ISSUE TITLE
[Support]: Frigate add-on not working on Home Assistant

### ISSUE THREAD

**Issue by drmauro82** [blakeblackshear/frigate#9130]
### Describe the problem you are having

After installing Frigate v0.12.1 as add-on, it doesn’t start. Log is the following:

### Version

0.12.1

### Frigate config file

```yaml
mqtt:
  host: core-mosquitto
  user: mqtt-user
  password: xxxxxxxxxx

detectors:
  cpu:
    type: cpu
      num_threads: 2
      
cameras:
  soggiorno:
    ffmpeg:
      inputs:
        path: rtsp://rtsp:XIkyo7XX@192.168.1.159:554/av_stream/ch0
        roles:
        - detect
        - record
        - rtmp
    rtmp:
      enabled: True
    record:
      enabled: True
    snapshots:
      enabled: True
    detect:
      enabled: True
      width: 1280
      height: 720
      fps: 5
    objects:
      track:
        - person
```

### Relevant log output

```shell
2023-12-30 12:58:38.609405172  [INFO] Starting Frigate...
s6-rc: info: service legacy-services successfully started
2023-12-30 12:58:39.001030483  [INFO] Got IP address from supervisor: 192.168.1.155
2023-12-30 12:58:39.240706020  [INFO] Got WebRTC port from supervisor: 8555
2023-12-30 12:58:40.729928016  RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
2023-12-30 12:58:40.730303084  Traceback (most recent call last):
2023-12-30 12:58:40.730321510    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-12-30 12:58:40.731914339      return _run_code(code, main_globals, None,
2023-12-30 12:58:40.731932913    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
2023-12-30 12:58:40.732282741      exec(code, run_globals)
2023-12-30 12:58:40.732342852    File "/opt/frigate/frigate/__main__.py", line 9, in <module>
2023-12-30 12:58:40.732577700      from frigate.app import FrigateApp
2023-12-30 12:58:40.732631125    File "/opt/frigate/frigate/app.py", line 17, in <module>
2023-12-30 12:58:40.732866196      from frigate.comms.dispatcher import Communicator, Dispatcher
2023-12-30 12:58:40.732925640    File "/opt/frigate/frigate/comms/dispatcher.py", line 9, in <module>
2023-12-30 12:58:40.733859182      from frigate.config import FrigateConfig
2023-12-30 12:58:40.733876459    File "/opt/frigate/frigate/config.py", line 9, in <module>
2023-12-30 12:58:40.733885607      import matplotlib.pyplot as plt
2023-12-30 12:58:40.733905089    File "/usr/local/lib/python3.9/dist-packages/matplotlib/__init__.py", line 113, in <module>
2023-12-30 12:58:40.735070702      from . import _api, _version, cbook, _docstring, rcsetup
2023-12-30 12:58:40.735187459    File "/usr/local/lib/python3.9/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
2023-12-30 12:58:40.735685637      from matplotlib.colors import Colormap, is_color_like
2023-12-30 12:58:40.735790951    File "/usr/local/lib/python3.9/dist-packages/matplotlib/colors.py", line 56, in <module>
2023-12-30 12:58:40.736553736      from matplotlib import _api, _cm, cbook, scale
2023-12-30 12:58:40.736664271    File "/usr/local/lib/python3.9/dist-packages/matplotlib/scale.py", line 22, in <module>
2023-12-30 12:58:40.737187560      from matplotlib.ticker import (
2023-12-30 12:58:40.737294707    File "/usr/local/lib/python3.9/dist-packages/matplotlib/ticker.py", line 138, in <module>
2023-12-30 12:58:40.738044400      from matplotlib import transforms as mtransforms
2023-12-30 12:58:40.738140639    File "/usr/local/lib/python3.9/dist-packages/matplotlib/transforms.py", line 49, in <module>
2023-12-30 12:58:40.738679039      from matplotlib._path import (
2023-12-30 12:58:40.738863499  ImportError: numpy.core.multiarray failed to import
2023-12-30 12:58:41.021128854  [INFO] Service Frigate exited with code 1 (by signal 0)
Traceback (most recent call last):
  File "/usr/local/go2rtc/create_config.py", line 27, in <module>
    config: dict[str, any] = yaml.safe_load(raw_config)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
s6-rc: info: service legacy-services: stopping
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.9/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 9, column 18:
          num_threads: 2
                     ^
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2023-12-30 12:58:41.146192382  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2023-12-30 12:58:41.285101156  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
2023-12-30 12:58:41.290112418  [INFO] The go2rtc service exited with code 1 (by signal 0)
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
na
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

na

**Comment by NickM-27** [comment]
What device did you install this on? This is usually a problem when installing frigate on a pi or some other device that runs 32 bit OS which is no longer supported.

**Comment by drmauro82** [comment]
Rpi 4 32 bit… anything I could do?

**Comment by NickM-27** [comment]
You could reinstall a 64 bit OS but that's it

**Comment by drmauro82** [comment]
ok thanks!
