### ISSUE TITLE
Can't get Frigate to record & Coral TCU to work

### ISSUE THREAD

**Issue by tboonstl** [blakeblackshear/frigate#9209]
### Describe the problem you are having

Okay, this is a bit embarrassing.  I have tried to duplicate other sample config and docker-compose files but still cannot get Frigate to record events.  Camera works okay.  I've tried different resolutions.  

Also, I can't seem to get the Coral TCU to work.  Any help would be GREATLY appreciated.

### Version

0.12.1-367d724

### Frigate config file

```yaml
mqtt:
  enabled: False

detectors:
  coral1:
    type: edgetpu
    device: usb:0

cameras:
  Camera1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://<name>:<password>@192.x.x.x:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - record
    objects:
      track:
        - person
    
    detect:    
      width: 2304
      height: 1296
    record:
      enabled: True
      retain: 
        days: 10
        mode: all
```

### Relevant log output

```shell
Seems to be ready to record:
2024-01-04 10:38:56.818246165  [INFO] Starting Frigate...
2024-01-04 10:39:00.949242023  [2024-01-04 10:39:00] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2024-01-04 10:39:00.996351226  [2024-01-04 10:39:00] peewee_migrate                 INFO    : Starting migrations
2024-01-04 10:39:01.008033120  [2024-01-04 10:39:01] peewee_migrate                 INFO    : There is nothing to migrate
2024-01-04 10:39:01.056657827  [2024-01-04 10:39:01] frigate.app                    INFO    : Output process started: 293
2024-01-04 10:39:01.058131888  [2024-01-04 10:39:01] detector.cpu                   INFO    : Starting detection process: 291
2024-01-04 10:39:01.064971863  [2024-01-04 10:39:01] frigate.detectors              WARNING : CPU detectors are not recommended and should only be used for testing or for trial purposes.
2024-01-04 10:39:01.086504742  [2024-01-04 10:39:01] frigate.app                    INFO    : Camera processor started for Camera1: 296
2024-01-04 10:39:01.109890012  [2024-01-04 10:39:01] frigate.app                    INFO    : Capture process started for Camera1: 298
2024-01-04 10:39:01.515264896  [2024-01-04 10:39:01] frigate.app                    WARNING : The current SHM size of 67.1MB is too small, recommend increasing it to at least 68.7MB.
```

### FFprobe output from your camera

```shell
[rtsp @ 0x55801839e0] max delay reached. need to consume packet
[rtsp @ 0x55801839e0] RTP: missed 15 packets
[h264 @ 0x55801878b0] concealing 9302 DC, 9302 AC, 9302 MV errors in P frame
[rtsp @ 0x55801839e0] max delay reached. need to consume packet
[rtsp @ 0x55801839e0] RTP: missed 29 packets
[h264 @ 0x55801878b0] concealing 24370 DC, 24370 AC, 24370 MV errors in P frame
[rtsp @ 0x55801839e0] max delay reached. need to consume packet
[rtsp @ 0x55801839e0] RTP: missed 34 packets
[rtsp @ 0x55801839e0] max delay reached. need to consume packet
[rtsp @ 0x55801839e0] RTP: missed 436 packets
Input #0, rtsp, from 'rtsp://<name>:<password>@192.x.x.x:554':
  Metadata:
    title           : Media Server
  Duration: N/A, start: 0.050000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 3840x2160, 20 fps, 100 tbr, 90k tbn
```

### Frigate stats

```json
Not sure how to do this.
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Amcrest IP8M-T2669EW-AI

### Any other information that may be helpful

I'm using a PI4 Model B Rev 1.5.  Raspberry PI OS.

**Comment by NickM-27** [comment]
no logs or information has been provided, also you should definitely be using a substream for object detection especially on an rpi

**Comment by tboonstl** [comment]
Other than from the Frigate container Logs, where might other logs be?
I had originally used a substream but took it out to first get a recording.  Even if it uses a lot of CPU, shouldn't it record?

In any event, something like this?

cameras:
  camera1:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/test_cam # <--- the name here must match the name of the camera in restream
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/test_cam_sub # <--- the name here must match the name of the camera_sub in restream
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: rtsp_cam_sub

**Comment by NickM-27** [comment]
the logs don't contain any errors so it is not clear why you think the coral is not working. 

Given that you are not using go2rtc it would look like this

```
cameras:
  Camera1:
    ffmpeg:
      inputs:
        - path: rtsp://<name>:<password>@192.x.x.x:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://<name>:<password>@192.x.x.x:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:    
      width: 640
      height: 480
    objects:
      track:
        - person
```

**Comment by tboonstl** [comment]
Yes, I guess I don't know if the Coral is working or not without recordings to see the boxes.
I added the detect path and resolution.  Still does not record.  I think there is another issue.

Below is a config error report when I restart the container.  

Config Error:

Traceback (most recent call last):
  File "/opt/frigate/frigate/http.py", line 761, in config_save
    new_yaml = FrigateConfig.parse_raw(new_config)
  File "/opt/frigate/frigate/config.py", line 1082, in parse_raw
    config = load_config_with_no_duplicates(raw_config)
  File "/opt/frigate/frigate/util.py", line 78, in load_config_with_no_duplicates
    return yaml.load(raw_config, PreserveDuplicatesLoader)
  File "/usr/local/lib/python3.9/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/opt/frigate/frigate/util.py", line 63, in map_constructor
    vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
  File "/opt/frigate/frigate/util.py", line 63, in <listcomp>
    vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/opt/frigate/frigate/util.py", line 63, in map_constructor
    vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
  File "/opt/frigate/frigate/util.py", line 63, in <listcomp>
    vals = [loader.construct_object(node, deep=deep) for _, node in node.value]
  File "/usr/local/lib/python3.9/dist-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/opt/frigate/frigate/util.py", line 68, in map_constructor
    raise ValueError(
ValueError: Config input detect is defined multiple times for the same field, this is not allowed.

**Comment by NickM-27** [comment]
what is your current config?

also you can watch the debug live view to see what is detected

**Comment by tboonstl** [comment]
Below is the current config with the detect substream.  Is there a "barebones" docker-compose and config file?  I've been trying to minimize/simplify until I get motion events.  Then, I can add individual parameters back in to get a full system.
  
I am not familiar with the "debug live view" but did add the following to the config file.  Where is the output?
logger:
  default: info

mqtt:
  enabled: False

detectors:
  coral1:
    type: edgetpu
    device: usb:0

cameras:
  Camera1: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://<name>:<password>@192.x.x.x:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
        - path: rtsp://<name>:<password>@192.x.x.x:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    detect:
      width: 640
      height: 480

    objects:
      track:
        - person
    
    detect:    
      width: 2304
      height: 1296
    record:
      enabled: True
      retain: 
        days: 10
        mode: all

**Comment by tboonstl** [comment]
Here is a log.  Does this tell you anything?

2024-01-04 13:56:33.479824245  172.19.0.1 - - [04/Jan/2024:13:56:33 -0600] "GET /api/events?before=1704434399&after=1704348000&camera=Camera1&has_clip=1&include_thumbnails=0&limit=5000 HTTP/1.1" 200 3 "http://0.0.0.0:5000/recording/Camera1" "Mozilla/5.0 (X11; Linux aarch64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"
2024-01-04 13:56:35.268577117  172.19.0.1 - - [04/Jan/2024:13:56:35 -0600] "GET /api/logs/frigate HTTP/1.1" 200 476 "http://0.0.0.0:5000/logs" "Mozilla/5.0 (X11; Linux aarch64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"
2024-01-04 13:56:35.299030133  172.19.0.1 - - [04/Jan/2024:13:56:35 -0600] "GET /api/logs/go2rtc HTTP/1.1" 200 266 "http://0.0.0.0:5000/logs" "Mozilla/5.0 (X11; Linux aarch64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"
2024-01-04 13:56:35.304441025  172.19.0.1 - - [04/Jan/2024:13:56:35 -0600] "GET /api/logs/nginx HTTP/1.1" 200 2687 "http://0.0.0.0:5000/logs" "Mozilla/5.0 (X11; Linux aarch64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"
2024-01-04 13:56:39.067382278  172.19.0.1 - - [04/Jan/2024:13:56:39 -0600] "GET /api/logs/frigate HTTP/1.1" 200 476 "http://0.0.0.0:5000/logs" "Mozilla/5.0 (X11; Linux aarch64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"
2024-01-04 13:56:39.096473178  172.19.0.1 - - [04/Jan/2024:13:56:39 -0600] "GET /api/config HTTP/1.1" 200 4630 "http://0.0.0.0:5000/logs" "Mozilla/5.0 (X11; Linux aarch64; rv:121.0) Gecko/20100101 Firefox/121.0" "-"

**Comment by NickM-27** [comment]
you defined `detect` twice which is not allowed.

**Comment by tboonstl** [comment]
Thank you for your help.  It certainly was an issue that cleared up an error message but Frigate will still not record anything.  I've probably made at least 100 adjustments to both the config and docker compose file in the last month and the friggin' program just will not work.  I keep trying to simplify and no dice.  I've event waved my hand over the camera in case it was a sensitivity issue.

Just don't know what to do anymore . . . out of options.

**Comment by NickM-27** [comment]
Start by checking the debug live view and see if you are detected.

**Comment by tboonstl** [comment]
This came up:  2024/01/04 19:38:42 [error] 129#129: *56 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 172.19.0.1, server: , request: "GET /vod/2024-01/04/10/Camera1/America,Chicago/master.m3u8 HTTP/1.1", host: "0.0.0.0:5000", referrer: "http://0.0.0.0:5000/recording/Camera1"

Not sure what it means.  BTW, I have an SSD named with a space (the default).  Would that be the problem?  I am going to try to rename it without the space.

**Comment by NickM-27** [comment]
If there was a problem with recordings there would be errors in the logs.

**Comment by NickM-27** [comment]
By debug live view I am talking about the camera live view in debug mode

**Comment by tboonstl** [comment]
I think the problem was the docker compose volume path to the SSD as I was able to get the first recording (although jerky).  By default, the SSD had a space in its name (T7_Shieldpath) and somehow in the docker compose file volume, the space was missing.

Regardless, I got my first video!!

I was able to add the space to the docker compose file and restart the contianer, however, it is probably better "form" to rename the SSD without a space, correct?

BTW, the video had high resolution but was jerky.   May I ask what variables you might change e.g., the SHM size, fps, etc.?

Thank you again!

**Comment by NickM-27** [comment]
Frigate copies the streams directly from the camera for recordings, the ffprobe shows considerable packet loss, is this a WiFi camera?

**Comment by tboonstl** [comment]
It is a wired Amcrest.

**Comment by NickM-27** [comment]
Can you show a screenshot of the encoding settings on the camera

**Comment by tboonstl** [comment]
![240104 Amcrest configuration](https://github.com/blakeblackshear/frigate/assets/100491057/4443e127-14e1-4470-9163-75d368a416aa)
Wow, I see what you mean.  The settings on the camera are very high.  Did not realize Frigate went right to the camera stream so the stream dictates resolution, etc. 
Do you think a more intensive video should use Go2RTC?  I want to string/concatenate the videos into one video.  Isn't ffmpeg better for that?
