### ISSUE TITLE
[HW Accel Support]: Frigate fatally crashes version 0.13rc1 using tensorrt.

### ISSUE THREAD

**Issue by austindetzel** [blakeblackshear/frigate#9418]
### Describe the problem you are having

Frigate fatally crashes version 0.13rc1 using tensorrt. Nothing changed in the docker config between stable and the new version. Refer to the log file, crashes as soon as there is something to detect. Looking for help on why this may be. Thank You

### Version

0.13rc1

### Frigate config file

```yaml
# yaml-language-server: $schema=http://192.168.40.10:5000/api/config/schema.json

#logger:
  #logs:
    #frigate.record: debug
    
database:
  path: /config/frigate.db

mqtt:
  # Optional: Enable mqtt server (default: shown below)
  enabled: False

#mqtt:
#  host: 192.168.40.10
#  port: 1883

#detectors:
#  cpu1:
#    type: cpu
#    num_threads: 4

detectors:
  tensorrt:
    type: tensorrt
    device: 0 #This is the default, select the first GPU

model:
  path: /trt-models/yolov4-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

motion:
  threshold: 20


record:
    enabled: True
    retain:
        days: 28
        mode: all

detect:
  enabled: True

birdseye:
  enabled: True
  restream: True
  width: 1920 #1280
  height: 1080 #720
  quality: 25

snapshots:
  enabled: False
  clean_copy: False
  

            
objects:
  track:
    - person
    - car
    - cat
    - dog
    - bird
  

go2rtc:
  #log:
  #  level: "trace"
  streams:
    Front_Door: 
      - rtsp://username:password@192.168.40.22/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - "ffmpeg:Front_Door#audio=opus"
    Front_Yard:
      - rtsp://username:password@192.168.40.23/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Front_Yard#audio=opus"
    Shed_Camera:
      - rtsp://username:password@192.168.40.21/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Shed_Camera#audio=opus"
    Driveway_Doorbell:
      - rtsp://username:password@192.168.40.24/cam/realmonitor?channel=1&subtype=0#backchannel=0
      - "ffmpeg:Driveway_Doorbell#audio=opus"
    Living_Room:
      - rtsp://username:password@192.168.40.20/live
      - "ffmpeg:Front_Door#audio=opus"
    Barn:
      - rtsp://username:password@192.168.40.25/cam/realmonitor?channel=1&subtype=0
      - "ffmpeg:Driveway_Doorbell#audio=opus"
    Barn_Sub:
      - rtsp://username:password@192.168.40.25/cam/realmonitor?channel=1&subtype=1
      - "ffmpeg:Driveway_Doorbell#audio=opus"
    Septic_Shed:
      - http://192.168.40.26/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password
      - "ffmpeg:Septic_Shed#audio=opus"
    Septic_Shed_Sub:
      - "ffmpeg:http://192.168.40.26/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=username&password=password"  
    Septic_Driveway:
      - http://192.168.40.28/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password
      - "ffmpeg:Septic_Driveway#audio=opus"
    Septic_Driveway_Sub:
      - "ffmpeg:http://192.168.40.28/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=username&password=password"  
    Septic_Inside:
      - http://192.168.40.27/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=username&password=password
      - "ffmpeg:Septic_Inside#audio=opus"
    Septic_Inside_Sub:
      - "ffmpeg:http://192.168.40.27/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=username&password=password"    


ffmpeg:
  hwaccel_args: -c:v h264_cuvid 
  output_args:
    record: preset-record-generic-audio-copy

cameras:
    Front_Door:
        ffmpeg:
            inputs:                
                - path:  rtsp://127.0.0.1:8554/Front_Door
                  input_args: preset-rtsp-restream
                  roles:
                    - record
                - path: rtsp://username:password@192.168.40.22/cam/realmonitor?channel=1&subtype=1
                  roles:
                    - detect
        detect:
            width: 640 
            height: 480 
        zones:
          front_sidewalk:
            coordinates: 886,1080,1806,1080,1441,1050,1146,821,1016,755,871,703,870,757,870,825
          road:
            coordinates: 858,489,1806,516,1808,533,855,509
          front_yard_north:
            coordinates: 1556,521,1834,533,1738,1043,1462,1080,1096,783,856,711,868,517

    Front_Yard:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/Front_Yard
                  input_args: preset-rtsp-restream
                  roles:
                    - record
                  hwaccel_args: preset-nvidia-h265
                - path: rtsp://username:password@192.168.40.23/cam/realmonitor?channel=1&subtype=1
                  roles:
                    - detect
        detect:
            width: 640
            height: 480
        
        zones:
          front_yard_north:
            coordinates: 1302,540,1468,543,1740,567,1853,566,1920,566,1920,1080,0,1080,0,496,972,505
          front_sidewalk:
            coordinates: 1828,571,1774,481,1415,465,1412,536

        

    Shed_Camera:
        ffmpeg:    
            inputs:
                - path: rtsp://127.0.0.1:8554/Shed_Camera
                  input_args: preset-rtsp-restream-low-latency
                  roles:
                    - record
                - path: rtsp://username:password@192.168.40.21/cam/realmonitor?channel=1&subtype=1
                  roles:
                    - detect
        detect:
            width: 704 
            height: 480 

        zones:
          pool:
            coordinates: 0,2160,3840,2160,3840,1631,2513,663,1087,699,0,1272
          backyard:
            coordinates: 2513,666,3840,1607,3840,682,3179,530,2632,468,2390,504,1702,630,958,573,0,887,0,1310,1106,699,1496,687,1876,682,2069,675,2311,659
          driveway:
            coordinates: 1051,559,904,523,737,561,309,609,183,651,402,654,0,825,0,892
          road:
            coordinates: 0,654,868,466,863,509,0,704
          front_yard_south:
             coordinates: 0,801,290,711,385,647,157,659,0,706
          deck:
            coordinates: 2321,361,2335,556,1831,621,1555,625,1082,587,1094,418
          front_yard_north:
           coordinates: 851,499,849,561,659,599,316,618

    Driveway_Doorbell:
        ffmpeg:     
            inputs:
                - path: rtsp://127.0.0.1:8554/Driveway_Doorbell 
                  input_args: preset-rtsp-restream
                  roles:
                    - record
                - path: rtsp://username:password@192.168.40.24/cam/realmonitor?channel=1&subtype=0
                  roles:
                    - detect
        detect:
            width: 640 
            height: 480       
        zones:
          driveway:
            coordinates: 1920,1080,1920,640,1447,694,911,673,496,674,837,741,449,1080
          road:
            coordinates: 1305,603,1920,592,1920,612,1291,627
          front_yard_south:
            coordinates: 1537,618,1920,608,1920,638,1776,674,1439,698,1125,693,930,671
          backyard:
            coordinates: 498,676,546,641,202,618,0,699,0,883,506,1022,823,744

    Living_Room:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/Living_Room
                  input_args: preset-rtsp-restream
                  roles:
                    - detect
                    - record
        detect:
            enabled: False
            width: 1920 
            height: 1080 
        birdseye:
          enabled: False

    Barn:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/Barn
                  input_args: preset-rtsp-restream-low-latency
                  roles:
                    - record
                - path: rtsp://127.0.0.1:8554/Barn_Sub
                  roles:
                    - detect
        detect:
            width: 704
            height: 480
        birdseye:
          mode: continuous
        zones:
          driveway:
            coordinates: 2056,1920,2560,1920,2560,1084,2286,1078,1968,1138,1360,1120,492,1006,354,1040,1332,1214,1766,1466
          road:
            coordinates: 1926,724,2014,762,0,1094,0,1014
          front_yard_south:
            coordinates: 0,1920,2064,1920,1708,1432,1226,1196,304,1036,0,1086
          front_yard_north:
            coordinates: 1786,802,2156,834,2158,974,1974,1142,566,1024,556,998

    Septic_Shed:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/Septic_Shed
                  input_args: preset-rtsp-restream-low-latency
                  roles:
                    - record
                - path: rtsp://127.0.0.1:8554/Septic_Shed_Sub
                  roles:
                    - detect
        detect:
            width: 640 
            height: 480 

    Septic_Driveway:
        ffmpeg:      
            inputs:
                - path: rtsp://127.0.0.1:8554/Septic_Driveway
                  input_args: preset-rtsp-restream
                  roles:
                    - record
                - path: rtsp://127.0.0.1:8554/Septic_Driveway_Sub
                  roles:
                    - detect
        detect:
            width: 640 
            height: 480 
        
    Septic_Inside:
        ffmpeg:
            inputs:
                - path: rtsp://127.0.0.1:8554/Septic_Inside
                  input_args: preset-rtsp-restream-low-latency
                  roles:
                    - record
                - path: rtsp://127.0.0.1:8554/Septic_Inside_Sub
                  roles:
                    - detect
        detect:
            width: 640 
            height: 480
```

### docker-compose file or Docker CLI command

```yaml
n/a
```

### Relevant log output

```shell
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
s6-rc: info: service go2rtc-healthcheck successfully stopped
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate successfully stopped
s6-rc: info: service trt-model-prepare: stopping
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service trt-model-prepare successfully stopped
s6-rc: info: service frigate-log successfully stopped
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
2024-01-22 19:52:57.553965579  [2024-01-22 19:52:57] watchdog.Septic_Shed           ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-01-22 19:52:57.553966889  [2024-01-22 19:52:57] ffmpeg.Septic_Shed.detect      ERROR   : rtsp://127.0.0.1:8554/Septic_Shed_Sub: Invalid data found when processing input
2024-01-22 19:52:57.565287584  [2024-01-22 19:52:57] watchdog.Septic_Driveway       ERROR   : Ffmpeg process crashed unexpectedly for Septic_Driveway.
2024-01-22 19:52:57.571342869  [2024-01-22 19:52:57] watchdog.Septic_Driveway       ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-01-22 19:52:57.571347329  [2024-01-22 19:52:57] ffmpeg.Septic_Driveway.detect  ERROR   : rtsp://127.0.0.1:8554/Septic_Driveway_Sub: Invalid data found when processing input
2024-01-22 19:52:57.698875580  [2024-01-22 19:52:57] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
2024-01-22 19:52:57.717740852  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
2024-01-22 19:52:57.745294234  [INFO] Service NGINX exited with code 0 (by signal 0)
2024-01-22 19:52:57.746954195  [2024-01-22 19:52:57] frigate.app                    INFO    : Stopping...
2024-01-22 19:52:57.802891255  [2024-01-22 19:52:57] frigate.stats                  INFO    : Exiting stats emitter...
2024-01-22 19:52:57.802899625  [2024-01-22 19:52:57] frigate.events.cleanup         INFO    : Exiting event cleanup...
2024-01-22 19:52:57.802901075  [2024-01-22 19:52:57] frigate.record.cleanup         INFO    : Exiting recording cleanup...
2024-01-22 19:52:57.802901975  [2024-01-22 19:52:57] frigate.storage                INFO    : Exiting storage maintainer...
2024-01-22 19:52:57.802902645  [2024-01-22 19:52:57] frigate.watchdog               INFO    : Exiting watchdog...
2024-01-22 19:52:57.820729583  [2024-01-22 19:52:57] frigate.ptz.autotrack          INFO    : Exiting autotracker...
2024-01-22 19:52:57.820734243  [2024-01-22 19:52:57] frigate.object_processing      INFO    : Exiting object processor...
2024-01-22 19:52:58.140506313  [2024-01-22 19:52:58] frigate.comms.ws               INFO    : Exiting websocket client...
2024-01-22 19:52:58.738486212  [2024-01-22 19:52:58] frigate.events.maintainer      INFO    : Exiting event processor...
2024-01-22 19:52:58.738606521  [2024-01-22 19:52:58] peewee.sqliteq                 INFO    : writer received shutdown request, exiting.
2024-01-22 19:52:58.741985342  [2024-01-22 19:52:58] watchdog.Barn                  INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.741987192  [2024-01-22 19:52:58] watchdog.Barn                  INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.741988272  [2024-01-22 19:52:58] watchdog.Septic_Driveway       INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.741989192  [2024-01-22 19:52:58] watchdog.Septic_Driveway       INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.741990062  [2024-01-22 19:52:58] watchdog.Septic_Shed           INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.741990872  [2024-01-22 19:52:58] watchdog.Septic_Shed           INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.741992222  [2024-01-22 19:52:58] watchdog.Front_Yard            INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.741993082  [2024-01-22 19:52:58] watchdog.Front_Yard            INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.742633148  [2024-01-22 19:52:58] watchdog.Driveway_Doorbell     INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.742812387  [2024-01-22 19:52:58] watchdog.Driveway_Doorbell     INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.743214505  [2024-01-22 19:52:58] watchdog.Septic_Driveway       INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.743216515  [2024-01-22 19:52:58] watchdog.Septic_Driveway       INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.743504913  [2024-01-22 19:52:58] watchdog.Shed_Camera           INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.743506763  [2024-01-22 19:52:58] watchdog.Septic_Inside         INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.743860631  [2024-01-22 19:52:58] watchdog.Shed_Camera           INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.743912891  [2024-01-22 19:52:58] watchdog.Septic_Inside         INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.744020970  [2024-01-22 19:52:58] watchdog.Septic_Shed           INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.744022830  [2024-01-22 19:52:58] watchdog.Septic_Shed           INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.744253759  [2024-01-22 19:52:58] watchdog.Front_Door            INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.744255549  [2024-01-22 19:52:58] watchdog.Front_Door            INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.750165335  [2024-01-22 19:52:58] watchdog.Living_Room           INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.750169225  [2024-01-22 19:52:58] watchdog.Living_Room           INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:58.955563740  [2024-01-22 19:52:58] watchdog.Front_Door            INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:58.955567930  [2024-01-22 19:52:58] watchdog.Front_Door            INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:59.021046965  [2024-01-22 19:52:59] watchdog.Septic_Inside         INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:59.021052165  [2024-01-22 19:52:59] watchdog.Septic_Inside         INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:59.044979618  [2024-01-22 19:52:59] watchdog.Shed_Camera           INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:59.045657385  [2024-01-22 19:52:59] watchdog.Shed_Camera           INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:59.046712178  [2024-01-22 19:52:59] watchdog.Barn                  INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:59.046775038  [2024-01-22 19:52:59] watchdog.Barn                  INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:59.062951295  [2024-01-22 19:52:59] watchdog.Front_Yard            INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:59.062955745  [2024-01-22 19:52:59] watchdog.Front_Yard            INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:59.079203312  [2024-01-22 19:52:59] watchdog.Driveway_Doorbell     INFO    : Terminating the existing ffmpeg process...
2024-01-22 19:52:59.079208562  [2024-01-22 19:52:59] watchdog.Driveway_Doorbell     INFO    : Waiting for ffmpeg to exit gracefully...
2024-01-22 19:52:59.352522229  [2024-01-22 19:52:59] frigate.video                  INFO    : Septic_Shed: exiting subprocess
2024-01-22 19:52:59.352758407  [2024-01-22 19:52:59] frigate.video                  INFO    : Septic_Driveway: exiting subprocess
2024-01-22 19:52:59.664610313  [2024-01-22 19:52:59] frigate.video                  INFO    : Living_Room: exiting subprocess
2024-01-22 19:52:59.953673559  [2024-01-22 19:52:59] frigate.output                 INFO    : exiting output process...
2024-01-22 19:53:03.113634590  /usr/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 52 leaked shared_memory objects to clean up at shutdown
2024-01-22 19:53:03.113638070    warnings.warn('resource_tracker: There appear to be %d '
2024-01-22 19:53:03.115298211  [INFO] Service Frigate exited with code 0 (by signal 0)
2024-01-22 19:53:03.116485884  exit with signal: terminated
2024-01-22 19:53:03.119301658  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service trt-model-prepare: starting
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
No models to convert.
s6-rc: info: service trt-model-prepare successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-01-22 19:53:14.598350614  [INFO] Preparing Frigate...
2024-01-22 19:53:14.599087579  [INFO] Starting NGINX...
2024-01-22 19:53:14.600550421  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-01-22 19:53:14.607294203  [INFO] Starting Frigate...
2024-01-22 19:53:14.892035254  [INFO] Starting go2rtc...
2024-01-22 19:53:14.948129503  19:53:14.948 INF go2rtc version 1.8.4 linux/amd64
2024-01-22 19:53:14.948592050  19:53:14.948 INF [api] listen addr=:1984
2024-01-22 19:53:14.948731109  19:53:14.948 INF [rtsp] listen addr=:8554
2024-01-22 19:53:14.948955378  19:53:14.948 INF [webrtc] listen addr=:8555
2024-01-22 19:53:15.602019212  [2024-01-22 19:53:15] frigate.app                    INFO    : Starting Frigate (0.13.0-49814b3)
2024-01-22 19:53:15.719087942  [2024-01-22 19:53:15] peewee_migrate.logs            INFO    : Starting migrations
2024-01-22 19:53:15.759126163  [2024-01-22 19:53:15] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-01-22 19:53:15.768503609  [2024-01-22 19:53:15] frigate.app                    INFO    : Recording process started: 593
2024-01-22 19:53:15.770702956  [2024-01-22 19:53:15] frigate.app                    INFO    : go2rtc process pid: 98
2024-01-22 19:53:15.794863888  [2024-01-22 19:53:15] frigate.app                    INFO    : Output process started: 604
2024-01-22 19:53:15.877625385  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Front_Door: 614
2024-01-22 19:53:15.897201133  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Front_Yard: 617
2024-01-22 19:53:15.904807009  [2024-01-22 19:53:15] detector.tensorrt              INFO    : Starting detection process: 602
2024-01-22 19:53:15.905158607  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Shed_Camera: 619
2024-01-22 19:53:15.913266951  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Driveway_Doorbell: 622
2024-01-22 19:53:15.922048341  [2024-01-22 19:53:15] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 12 MiB
2024-01-22 19:53:15.957554087  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Living_Room: 624
2024-01-22 19:53:15.958158724  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Barn: 627
2024-01-22 19:53:15.976021892  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Septic_Shed: 630
2024-01-22 19:53:15.983941537  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Septic_Driveway: 632
2024-01-22 19:53:15.983946766  [2024-01-22 19:53:15] frigate.app                    INFO    : Camera processor started for Septic_Inside: 635
2024-01-22 19:53:15.983951386  [2024-01-22 19:53:15] frigate.app                    INFO    : Capture process started for Front_Door: 637
2024-01-22 19:53:15.991363284  [2024-01-22 19:53:15] frigate.app                    INFO    : Capture process started for Front_Yard: 638
2024-01-22 19:53:16.000753600  [2024-01-22 19:53:15] frigate.app                    INFO    : Capture process started for Shed_Camera: 640
2024-01-22 19:53:16.010139027  [2024-01-22 19:53:16] frigate.app                    INFO    : Capture process started for Driveway_Doorbell: 647
2024-01-22 19:53:16.024512464  [2024-01-22 19:53:16] frigate.app                    INFO    : Capture process started for Living_Room: 654
2024-01-22 19:53:16.032928086  [2024-01-22 19:53:16] frigate.app                    INFO    : Capture process started for Barn: 660
2024-01-22 19:53:16.051567620  [2024-01-22 19:53:16] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 232, Serialized Engine Version: 213)
2024-01-22 19:53:16.053077241  [2024-01-22 19:53:16] frigate.app                    INFO    : Capture process started for Septic_Shed: 682
2024-01-22 19:53:16.071143788  [2024-01-22 19:53:16] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
2024-01-22 19:53:16.072658579  Process detector:tensorrt:
2024-01-22 19:53:16.073622353  [2024-01-22 19:53:16] frigate.app                    INFO    : Capture process started for Septic_Driveway: 694
2024-01-22 19:53:16.074482258  Traceback (most recent call last):
2024-01-22 19:53:16.074691137    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-01-22 19:53:16.074693467      self.run()
2024-01-22 19:53:16.074914536    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-01-22 19:53:16.074916456      self._target(*self._args, **self._kwargs)
2024-01-22 19:53:16.075117005    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-01-22 19:53:16.075118685      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-01-22 19:53:16.075314404    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-01-22 19:53:16.075316014      self.detect_api = create_detector(detector_config)
2024-01-22 19:53:16.075511023    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-01-22 19:53:16.075512473      return api(detector_config)
2024-01-22 19:53:16.075702852    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 221, in __init__
2024-01-22 19:53:16.075704492      self.input_shape = self._get_input_shape()
2024-01-22 19:53:16.075981180    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 93, in _get_input_shape
2024-01-22 19:53:16.075982650      binding = self.engine[0]
2024-01-22 19:53:16.076200569  TypeError: 'NoneType' object is not subscriptable
2024-01-22 19:53:16.076402597  Exception ignored in: <function TensorRtDetector.__del__ at 0x14b4143be3a0>
2024-01-22 19:53:16.076569026  Traceback (most recent call last):
2024-01-22 19:53:16.076736915    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__
2024-01-22 19:53:16.077035084      if self.outputs is not None:
2024-01-22 19:53:16.077208463  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2024-01-22 19:53:16.093965697  [2024-01-22 19:53:16] frigate.app                    INFO    : Capture process started for Septic_Inside: 704
```

### FFprobe output from your camera

```shell
n/a
```

### Operating system

UNRAID

### Install method

Docker CLI

### Network connection

Wired

### Camera make and model

Amcrest and Reolink

**Comment by NickM-27** [comment]
> Nothing changed in the docker config between stable and the new version

That would be why it's failing, like it says in the release notes the models must be regenerated and the config must be changed

**Comment by austindetzel** [comment]
Solved, I missed some information in the docs
