### ISSUE TITLE
[Detector Support]: Using an older GPU

### ISSUE THREAD

**Issue by WilliamVenner** [blakeblackshear/frigate#9434]
### Describe the problem you are having

Hi there, I was wondering how I might go about using Frigate with an older GPU? Namely, I have a spare GTX 770 collecting dust and it would be cool to use it for object detection.

However, given its age, the compute capability is only 3.0. This means I have to use TensorRT 7.0.0, via the `nvcr.io/nvidia/tensorrt:20.03-py3` image.

This was fine when generating the TensorRT models, I simply changed the image in the command:

```
sudo docker run -e USE_FP16=False --gpus=all --rm -it -v `pwd`/trt-models:/tensorrt_models -v `pwd`/tensorrt_models.sh:/tensorrt_models.sh nvcr.io/nvidia/tensorrt:20.03-py3 /tensorrt_models.sh
```

I also had to tweak the version of the `protobuf` pip package.

However, upon starting Frigate using my generated models, I encounter this error:

```
2024-01-24 22:52:30.014301652  [2024-01-24 22:52:30] frigate.detectors.plugins.tensorrt ERROR   : ERROR: failed to load libraries. libnvinfer.so.7: cannot open shared object file: No such file or directory
2024-01-24 22:52:30.047105128  [2024-01-24 22:52:30] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +1, GPU +0, now: CPU 55, GPU 38 (MiB)
2024-01-24 22:52:30.054643327  [2024-01-24 22:52:30] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 23 MiB
2024-01-24 22:52:30.068112349  [2024-01-24 22:52:30] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::35] Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 0, Serialized Engine Version: 89)
2024-01-24 22:52:30.075088185  Process detector:tensorrt:
2024-01-24 22:52:30.075166486  [2024-01-24 22:52:30] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
2024-01-24 22:52:30.075582352  Traceback (most recent call last):
2024-01-24 22:52:30.075590089    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-01-24 22:52:30.075591020      self.run()
2024-01-24 22:52:30.075592037    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-01-24 22:52:30.075592974      self._target(*self._args, **self._kwargs)
2024-01-24 22:52:30.075593914    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2024-01-24 22:52:30.075605222      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-01-24 22:52:30.075611083    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2024-01-24 22:52:30.075612360      self.detect_api = create_detector(detector_config)
2024-01-24 22:52:30.075613762    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2024-01-24 22:52:30.075614816      return api(detector_config)
2024-01-24 22:52:30.075616129    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 220, in __init__
2024-01-24 22:52:30.075617588      self.input_shape = self._get_input_shape()
2024-01-24 22:52:30.075619089    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 92, in _get_input_shape
2024-01-24 22:52:30.075620908      binding = self.engine[0]
2024-01-24 22:52:30.075622121  TypeError: 'NoneType' object is not subscriptable
2024-01-24 22:52:30.075629926  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f97e8131160>
2024-01-24 22:52:30.075631243  Traceback (most recent call last):
2024-01-24 22:52:30.075632582    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2024-01-24 22:52:30.075737099      if self.outputs is not None:
2024-01-24 22:52:30.075738934  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
```

It's trying to load libnvinfer.so.7, which I don't have. Notably, I do have libnvinfer.so.8, but obviously there's a version mismatch here.

I believe I need to change this as well:

https://github.com/blakeblackshear/frigate/blob/dev/docker/tensorrt/Dockerfile.base#L6

Unfortunately I am not so experienced with Docker and am not really sure how I would go about doing this.

Am I SOL, or can I wrangle Frigate to support my dusty GPU? Any pointers would be greatly appreciated.

Thanks

### Version

0.12.1-367D724

### Frigate config file

```yaml
mqtt:
  enabled: false
cameras:
  garage:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: XXX
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - fox
        - rat
        - mouse
        - bird
        - bicycle
        - car
        - motorcycle
        - rodent
        - motorbike
    detect:
      width: 2560
      height: 1440
      fps: 25
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
  garden:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: XXX
          roles:
            - detect
            - record
    objects:
      track:
        - person
        - dog
        - fox
        - rat
        - mouse
        - bird
        - bicycle
        - car
        - motorcycle
        - rodent
        - motorbike
    detect:
      width: 2560
      height: 1440
      fps: 25
    record:
      enabled: True
      retain:
        days: 7
        mode: motion
detectors:
  tensorrt:
    type: tensorrt
    device: 0
model:
  path: /trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: false
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "132mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /frigate/config/config.yml:/config/config.yml
      - /frigate/media:/media/frigate
      - /frigate/trt-models/trt-models:/trt-models
      - type: tmpfs # 1GB of memory
        target: /tmp/cache
        tmpfs:
          size: 1073741824
    ports:
      - "5000:5000" # Port used by the Web UI
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

### Relevant log output

```shell
2024-01-24 23:05:20.182934944  [INFO] Starting Frigate...
2024-01-24 23:05:21.113481494  [2024-01-24 23:05:21] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2024-01-24 23:05:21.134701326  [2024-01-24 23:05:21] peewee_migrate                 INFO    : Starting migrations
2024-01-24 23:05:21.137778772  [2024-01-24 23:05:21] peewee_migrate                 INFO    : There is nothing to migrate
2024-01-24 23:05:21.149608374  [2024-01-24 23:05:21] frigate.app                    INFO    : Output process started: 434
2024-01-24 23:05:21.153807372  [2024-01-24 23:05:21] frigate.app                    INFO    : Camera processor started for garage: 437
2024-01-24 23:05:21.157924147  [2024-01-24 23:05:21] frigate.app                    INFO    : Camera processor started for garden: 439
2024-01-24 23:05:21.162242555  [2024-01-24 23:05:21] frigate.app                    INFO    : Capture process started for garage: 440
2024-01-24 23:05:21.166751938  [2024-01-24 23:05:21] frigate.app                    INFO    : Capture process started for garden: 444
2024-01-24 23:05:21.361548042  [2024-01-24 23:05:21] detector.tensorrt              INFO    : Starting detection process: 432
2024-01-24 23:05:21.374277677  [2024-01-24 23:05:21] frigate.detectors.plugins.tensorrt ERROR   : ERROR: failed to load libraries. libnvinfer.so.7: cannot open shared object file: No such file or directory
2024-01-24 23:05:21.407000864  [2024-01-24 23:05:21] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +1, GPU +0, now: CPU 55, GPU 38 (MiB)
2024-01-24 23:05:21.414449466  [2024-01-24 23:05:21] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 23 MiB
2024-01-24 23:05:21.427865858  [2024-01-24 23:05:21] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::35] Error Code 1: Serialization (Serialization assertion safeVersionRead == safeSerializationVersion failed.Version tag does not match. Note: Current Version: 0, Serialized Engine Version: 89)
2024-01-24 23:05:21.434060243  [2024-01-24 23:05:21] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
2024-01-24 23:05:21.434815288  Process detector:tensorrt:
2024-01-24 23:05:21.435338323  Traceback (most recent call last):
2024-01-24 23:05:21.435346293    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-01-24 23:05:21.435347234      self.run()
2024-01-24 23:05:21.435348254    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-01-24 23:05:21.435349151      self._target(*self._args, **self._kwargs)
2024-01-24 23:05:21.435350116    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2024-01-24 23:05:21.435361636      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-01-24 23:05:21.435362713    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2024-01-24 23:05:21.435364016      self.detect_api = create_detector(detector_config)
2024-01-24 23:05:21.435368898    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2024-01-24 23:05:21.435369762      return api(detector_config)
2024-01-24 23:05:21.435370728    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 220, in __init__
2024-01-24 23:05:21.435371583      self.input_shape = self._get_input_shape()
2024-01-24 23:05:21.435372591    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 92, in _get_input_shape
2024-01-24 23:05:21.435373405      binding = self.engine[0]
2024-01-24 23:05:21.435374269  TypeError: 'NoneType' object is not subscriptable
2024-01-24 23:05:21.435379255  Exception ignored in: <function TensorRtDetector.__del__ at 0x7ff0c97a6160>
2024-01-24 23:05:21.435380103  Traceback (most recent call last):
2024-01-24 23:05:21.435384505    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 238, in __del__
2024-01-24 23:05:21.435484304      if self.outputs is not None:
2024-01-24 23:05:21.435486139  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2024-01-24 23:05:22.697375821  [2024-01-24 23:05:22] frigate.video                  ERROR   : garden: Unable to read frames from ffmpeg process.
2024-01-24 23:05:22.697467020  [2024-01-24 23:05:22] frigate.video                  ERROR   : garden: ffmpeg process is not running. exiting capture thread...
2024-01-24 23:05:22.750299171  [2024-01-24 23:05:22] frigate.video                  ERROR   : garage: Unable to read frames from ffmpeg process.
2024-01-24 23:05:22.750442100  [2024-01-24 23:05:22] frigate.video                  ERROR   : garage: ffmpeg process is not running. exiting capture thread...
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

Other

### Any other information that may be helpful

```
Wed Jan 24 23:06:33 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.223.02   Driver Version: 470.223.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 N/A |                  N/A |
|  0%   29C    P0    N/A /  N/A |      0MiB /  1998MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by NickM-27** [comment]
Like it says in the docs compute 5.0 is needed. It's maybe possible that you could rewrite a lot of things and get it working but I'm not totally sure and in any case support for that isn't going to be provided. 

You could use the GPU for encode / decode and get a coral or use OpenVINO if your system has an intel iGPU.
