### ISSUE TITLE
[Support]: after update to Version 0.13, Frigate no Longer Starting! 

### ISSUE THREAD

**Issue by merlin2105** [blakeblackshear/frigate#9516]
### Describe the problem you are having

after update to Version 0.13, Frigate no Longer Starting! 

### Version

0.13.0

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.73
  user: mqtt-user
  password: xxxx

####### Global Settings  #######

ffmpeg:
  hwaccel_args: -c:v h264_qsv
  
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3

birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 8
  mode: continuous
  
live:
  height: 640
  quality: 1  

####### Camera Carport  #######

cameras:
    Carport:
      ffmpeg:
        hwaccel_args: preset-vaapi ##-hwaccel_output_format qsv -c:v h264_qsv
        input_args:
          - -avoid_negative_ts
          - make_zero
          - -fflags
          - +genpts+discardcorrupt
          - -flags
          - low_delay
          - -strict
          - experimental
          - -analyzeduration
          - 1000M
          - -probesize
          - 1000M
          - -rw_timeout
          - "5000000"
        inputs:
        - path: http://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx
          roles:
            - record
            - rtmp

        - path: http://192.168.1.20/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
          roles:
            - detect
      rtmp:
        enabled: false

      detect:   
        enabled: True
        stationary:
         threshold: 50
         max_frames:
           default: 3000
           objects:
             person: 1000

        width: 1920
        height: 1080
        fps: 24

####### Objekte #####
       
      objects:
        track:
          - person
          - car
          - motorcycle
          #- dog

        filters:
          person:
            min_area: 5000
            max_area: 100000
            #min_ratio: 0.5
            #max_ratio: 2.0
            threshold: 0.8
            min_score: 0.7
          car:  
             mask:  0,1080,1920,1080,1920,345,1721,322,1510,304,1284,280,1035,276,824,278,642,290,460,297,0,315
          motorcycle: 
             mask:  0,1080,1920,1080,1920,345,1721,322,1510,304,1284,280,1035,276,824,278,642,290,460,297,0,315

             
      zones:
        zone_1:
         coordinates: 1008,0,1920,0,1920,555,1920,1080,0,1080,0,691,0,642,0,558,0,517,0,0
         objects:
          - person
         filters:
          person:
            min_area: 5000
            max_area: 100000
            #min_ratio: 0.5
            #max_ratio: 2.0
            threshold: 0.6
            min_score: 0.6

        strasse:
          coordinates: 0,329,877,294,1234,296,1552,312,1708,326,1844,342,1920,353,1920,0,0,0
          objects:
          - car
          - motorcycle
          - person
          



####### Snapshot  #######         
      snapshots:
        required_zones:
           - zone_1
           - strasse
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 1

####### Recording  #######
      record:
        enabled: true
        retain:
          days: 1
          mode: motion
        events:
          pre_capture: 5
          post_capture: 5
          retain:
            default: 1
            mode: active_objects
            objects:
             car: 1
             person: 1
             motorcycle: 1

          required_zones:
           - zone_1
           - strasse

####### Camera Werkstatt  #######


    Werkstatt:
      ffmpeg:
        hwaccel_args: preset-vaapi ##-hwaccel_output_format qsv -c:v h264_qsv
        input_args:
          - -avoid_negative_ts
          - make_zero
          - -fflags
          - +genpts+discardcorrupt
          - -flags
          - low_delay
          - -strict
          - experimental
          - -analyzeduration
          - 1000M
          - -probesize
          - 1000M
          - -rw_timeout
          - "5000000"
        inputs:
        - path: http://192.168.1.21/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx
          roles:
            - record
            - rtmp

        - path: http://192.168.1.21/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
          roles:
            - detect

      rtmp:
        enabled: false
      detect:                 
        width: 1920
        height: 1080
        fps: 24
      objects:
        track:
          - person
          #- dog

        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
            min_score: 0.7

      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 3


####### Recording  #######
      record:
        enabled: true
        retain:
          days: 1
          mode: motion
        events:
          pre_capture: 5
          post_capture: 5
          retain:
            default: 1
            mode: active_objects
            objects:
             person: 1

             

          
####### Camera Terasse  #######

    Terasse:
      ffmpeg:
        hwaccel_args: preset-vaapi ##-hwaccel_output_format qsv -c:v h264_qsv
        inputs:
        - path: rtsp://admin:merlin2105@192.168.1.22:554/h264Preview_01_main 
          input_args: preset-rtsp-restream
        #- path: http://192.168.1.23/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx
          roles:
            - record
            - rtmp
        - path: rtsp://admin:merlin2105@192.168.1.22:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
        #- path: http://192.168.1.23/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
          roles:
            - detect

      rtmp:
        enabled: False
      detect:                 
        width: 1920
        height: 1080
        fps: 24


      objects:
        track:
          - person
          #- dog

        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
            min_score: 0.7

      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 1


####### Recording  #######
      record:
        enabled: true
        retain:
          days: 1
          mode: motion
        events:
          pre_capture: 5
          post_capture: 5
          retain:
            default: 1
            mode: active_objects
            objects:
             person: 1
             



####### Camera Front  #######

    Front:
      ffmpeg:
        hwaccel_args: preset-vaapi ##-hwaccel_output_format qsv -c:v h264_qs
        inputs:
          
        - path: rtsp://admin:merlin2105@192.168.1.23:554/h264Preview_01_main 
          input_args: preset-rtsp-restream
        #- path: http://192.168.1.23/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx
          roles:
            - record
            - rtmp
        - path: rtsp://admin:merlin2105@192.168.1.23:554/h264Preview_01_sub
          input_args: preset-rtsp-restream
        #- path: http://192.168.1.23/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
          roles:
            - detect

      rtmp:
        enabled: false
      detect:                 
        width: 1920
        height: 1080
        fps: 24



      objects:
        track:
          - person
          - car
          - motorcycle
          #- dog

        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
            min_score: 0.7

      zones:
        zone_2:
         coordinates: 280,203,502,163,706,152,876,134,1014,119,1140,124,1326,118,1812,154,1920,179,1920,1080,0,1080,0,251
         objects:
          - person
         filters:
          person:
            min_area: 5000
            max_area: 100000
            #min_ratio: 0.5
            #max_ratio: 2.0
            threshold: 0.6
            min_score: 0.7

        strasse1:
          coordinates: 1754,0,1753,86,1750,176,1636,174,1507,172,1360,132,1240,128,1133,118,1022,125,873,139,694,148,502,159,271,193,0,242,0,0
          objects:
          - car
          - motorcycle
          - person


####### Snapshot  #######            
      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 1



####### Recording  #######                      
      record:
        enabled: true
        retain:
          days: 1
          mode: motion
        events:
          pre_capture: 5
          post_capture: 5
          retain:
            default: 1
            mode: active_objects
            
          required_zones:
           - zone_2
           - strasse1
   
####### Camera Grundstück  #######


    Grundstueck:
      ffmpeg:
        hwaccel_args: preset-vaapi ##-hwaccel_output_format qsv -c:v h264_qsv
        input_args:
          - -avoid_negative_ts
          - make_zero
          - -fflags
          - +genpts+discardcorrupt
          - -flags
          - low_delay
          - -strict
          - experimental
          - -analyzeduration
          - 1000M
          - -probesize
          - 1000M
          - -rw_timeout
          - "5000000"
        inputs:
        - path: http://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=xxxx
          roles:
            - record
            - rtmp

        - path: http://192.168.1.24/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=xxxx
          roles:
            - detect

      rtmp:
        enabled: False
      detect:                 
        width: 1920
        height: 1080
        fps: 24
      objects:
        track:
          - person
          #- dog

        filters:
          person:
            min_area: 5000
            max_area: 100000
            threshold: 0.6
            min_score: 0.7

      snapshots:
        enabled: true
        timestamp: false
        bounding_box: true
        retain:
          default: 3


####### Recording  #######
      record:
        enabled: true
        retain:
          days: 1
          mode: motion
        events:
          pre_capture: 5
          post_capture: 5
          retain:
            default: 3
            mode: active_objects
            objects:
             person: 1
```

### Relevant log output

```shell
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-01-31 12:29:35.997950156  [INFO] Preparing Frigate...
2024-01-31 12:29:35.999135210  [INFO] Starting NGINX...
2024-01-31 12:29:36.001227567  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-01-31 12:29:36.010423880  [INFO] Starting Frigate...
2024-01-31 12:29:36.036144627  [INFO] Got IP address from supervisor: 192.168.1.73
2024-01-31 12:29:36.059832212  [INFO] Got WebRTC port from supervisor: 8555
2024-01-31 12:29:36.298137540  [INFO] Starting go2rtc...
2024-01-31 12:29:36.351830284  09:29:36.351 INF go2rtc version 1.8.4 linux/amd64
2024-01-31 12:29:36.352117173  09:29:36.352 INF [api] listen addr=:1984
2024-01-31 12:29:36.352141148  09:29:36.352 INF [rtsp] listen addr=:8554
2024-01-31 12:29:36.352258447  09:29:36.352 INF [webrtc] listen addr=:8555
2024-01-31 12:29:37.030152289  [2024-01-31 09:29:37] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
2024-01-31 12:29:37.030214363  [2024-01-31 09:29:37] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-01-31 12:29:37.101023936  [2024-01-31 09:29:37] peewee_migrate.logs            INFO    : Starting migrations
2024-01-31 12:29:37.112706712  [2024-01-31 09:29:37] peewee_migrate.logs            INFO    : Migrate "014_event_updates_for_fp"
2024-01-31 12:29:37.112903878  [2024-01-31 09:29:37] peewee_migrate.logs            INFO    : add_column ('event', 'score', <FloatField: Event.score>)
2024-01-31 12:29:37.113765663  duplicate column name: score
2024-01-31 12:29:37.114009327  [2024-01-31 09:29:37] peewee_migrate.logs            ERROR   : Migration failed: 014_event_updates_for_fp
2024-01-31 12:29:37.114010529  Traceback (most recent call last):
2024-01-31 12:29:37.114012604    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
2024-01-31 12:29:37.114013931      cursor.execute(sql, params or ())
2024-01-31 12:29:37.114014942  sqlite3.OperationalError: duplicate column name: score
2024-01-31 12:29:37.114016089  
2024-01-31 12:29:37.114017018  During handling of the above exception, another exception occurred:
2024-01-31 12:29:37.114027065  
2024-01-31 12:29:37.114027909  Traceback (most recent call last):
2024-01-31 12:29:37.114028955    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/router.py", line 200, in run_one
2024-01-31 12:29:37.114029730      migrator()
2024-01-31 12:29:37.114030692    File "/usr/local/lib/python3.9/dist-packages/peewee_migrate/migrator.py", line 76, in __call__
2024-01-31 12:29:37.114042206      op.run()
2024-01-31 12:29:37.114043218    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
2024-01-31 12:29:37.114044328      self._handle_result(method(*self.args, **kwargs))
2024-01-31 12:29:37.114045295    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 156, in _handle_result
2024-01-31 12:29:37.114054213      self._handle_result(item)
2024-01-31 12:29:37.114055245    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 153, in _handle_result
2024-01-31 12:29:37.114056021      result.run()
2024-01-31 12:29:37.114056968    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 162, in run
2024-01-31 12:29:37.114057813      self._handle_result(method(*self.args, **kwargs))
2024-01-31 12:29:37.114066014    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 151, in _handle_result
2024-01-31 12:29:37.114066840      self.execute(result)
2024-01-31 12:29:37.114067773    File "/usr/local/lib/python3.9/dist-packages/playhouse/migrate.py", line 147, in execute
2024-01-31 12:29:37.114068659      self.migrator.database.execute(node)
2024-01-31 12:29:37.114069574    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3260, in execute
2024-01-31 12:29:37.114070358      return self.execute_sql(sql, params)
2024-01-31 12:29:37.114071253    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
2024-01-31 12:29:37.114081084      cursor.execute(sql, params or ())
2024-01-31 12:29:37.114082031    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3020, in __exit__
2024-01-31 12:29:37.114082859      reraise(new_type, new_type(exc_value, *exc_args), traceback)
2024-01-31 12:29:37.114083724    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
2024-01-31 12:29:37.114084626      raise value.with_traceback(tb)
2024-01-31 12:29:37.114085566    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3252, in execute_sql
2024-01-31 12:29:37.114086396      cursor.execute(sql, params or ())
2024-01-31 12:29:37.114087231  peewee.OperationalError: duplicate column name: score
2024-01-31 12:29:38.254453571  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-01-31 12:29:38.260710977  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-01-31 12:29:38.288588223  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
s6-rc: info: service nginx-log successfully stopped
2024-01-31 12:29:38.290005974  exit with signal: terminated
s6-rc: info: service frigate-log successfully stopped
2024-01-31 12:29:38.292621733  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### FFprobe output from your camera

```shell
ffprobe <camera_url>
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

### Network connection

Wired

### Camera make and model

Reolink

**Comment by NickM-27** [comment]
did you previously update to 0.13 then downgrade? This indicates that the field exists already which isn't possible if this is a clean update
