### ISSUE TITLE
[Camera Support]: ONVIF/PTV feedback for Jennov camera

### ISSUE THREAD

**Issue by ptruman** [blakeblackshear/frigate#9526]
### Describe the problem you are having

More for update than an issue (so the supported cameras page can be updated)
I have a Jennov 5MP PTZ - used to use rudimentary PTZ in Zoneminder.
Camera/stream is fine in Frigate, but Onvif fails.
Moved ONVIF to port 1000 (was port 80) to separate from other web traffic - still doesn't work.
Camera offers HIK/DAHUA ports also, which don't work.

Error reported on startup is:
"Onvif connection to Driveway failed: Unknown error: The CapabilityCategory type doesn't accept collections as value"

### Version

0.13.0-01E2D20

### Frigate config file

```yaml
onvif:
      host: 10.74.60.4
      port: 1000
```

### Relevant log output

```shell
2024-01-31 13:39:25.972891541  [2024-01-31 13:39:25] frigate.app                    INFO    : Starting Frigate (0.13.0-01e2d20)
2024-01-31 13:39:26.051723562  [2024-01-31 13:39:26] peewee_migrate.logs            INFO    : Starting migrations
2024-01-31 13:39:26.060045941  [2024-01-31 13:39:26] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-01-31 13:39:26.448968306  [2024-01-31 13:39:26] frigate.ptz.onvif              ERROR   : Onvif connection to Driveway failed: Unknown error: The CapabilityCategory type doesn't accept collections as value
2024-01-31 13:39:26.456124956  [2024-01-31 13:39:26] frigate.app                    INFO    : Recording process started: 441
2024-01-31 13:39:26.460928773  [2024-01-31 13:39:26] frigate.app                    INFO    : go2rtc process pid: 89
2024-01-31 13:39:26.499155457  [2024-01-31 13:39:26] detector.coral1                INFO    : Starting detection process: 450
```

### FFprobe output from your camera

```shell
[{"return_code":0,"stderr":"","stdout":{"programs":[],"streams":[{"avg_frame_rate":"0/0","bit_rate":"64000","codec_long_name":"PCMmu-law/G.711mu-law"},{"avg_frame_rate":"0/0","codec_long_name":"H.264/AVC/MPEG-4AVC/MPEG-4part10","height":1944,"width":2592}]}}]
```

### Frigate stats

```json
{"cameras":{"Driveway":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":15.1,"capture_pid":462,"detection_enabled":1,"detection_fps":36.0,"ffmpeg_pid":471,"pid":459,"process_fps":15.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"15":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"17":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"24":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"25":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"26":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"27":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"28":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"29":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"30":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"31":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"32":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"41":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"42":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"80":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"81":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"82":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"89":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"4.3","cpu_average":"4","mem":"0.1"},"103":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"106":{"cmdline":"python3 -u -m frigate","cpu":"8.2","cpu_average":"5","mem":"2.0"},"119":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.1"},"145":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"146":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"147":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"148":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"154":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"164":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"184":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"206":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"234":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"439":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.6"},"441":{"cmdline":"frigate.recording_manager","cpu":"5.4","cpu_average":"3","mem":"0.9"},"449":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(41)","cpu":"0.5","cpu_average":"0","mem":"0.1"},"450":{"cmdline":"frigate.detector.coral1","cpu":"27.2","cpu_average":"21","mem":"0.9"},"452":{"cmdline":"frigate.output       ","cpu":"3.3","cpu_average":"2","mem":"0.8"},"456":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 2592x1944 -i pipe: -f mpegts -s 2592x1944 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"459":{"cmdline":"frigate.process:Driveway","cpu":"109.0","cpu_average":"87","mem":"1.1"},"461":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.1"},"462":{"cmdline":"frigate.capture:Driveway","cpu":"27.7","cpu_average":"26","mem":"0.8"},"471":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel cuda -hwaccel_output_format cuda -user_agent FFmpeg Frigate/0.13.0-01e2d20 -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -timeout 5000000 -use_wallclock_as_timestamps 1 -i rtsp://*:*@127.0.0.1:8554/driveway_cam?video&audio -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/Driveway@%Y%m%d%H%M%S%z.mp4 -r 15 -vf fps=15,scale_cuda=w=2592:h=1944:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"64.3","cpu_average":"62","mem":"2.3"},"1221":{"cmdline":"/bin/bash","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1301":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":36.0,"detectors":{"coral1":{"detection_start":1706708865.651345,"inference_speed":10.34,"pid":450}},"gpu_usages":{"Quadro P1000":{"dec":"5.0%","enc":"0.0%","gpu":"2.0%","mem":"8.39%"}},"processes":{"go2rtc":{"pid":89},"logger":{"pid":439},"recording":{"pid":441}},"service":{"last_updated":1706708865,"latest_version":"0.13.0","storage":{"/dev/shm":{"free":233.5,"mount_type":"tmpfs","total":256.0,"used":22.5},"/media/frigate/clips":{"free":1045762.8,"mount_type":"ext4","total":1876558.3,"used":830779.5},"/media/frigate/recordings":{"free":1045762.8,"mount_type":"ext4","total":1876558.3,"used":830779.5},"/tmp/cache":{"free":1045762.8,"mount_type":"overlay","total":1876558.3,"used":830779.5}},"temperatures":{},"uptime":499,"version":"0.13.0-01e2d20"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

Jennov 5MP (see info below)

### Any other information that may be helpful

https://jennov.com/product/5mp-poe-ip-security-camera/
I can't see "new" firmware but have asked :)

**Comment by ptruman** [comment]
By way of update, this seems to have changed slightly (after I enabled ONVIF auth on the camera)

2024-02-04 16:55:44.431193034  [2024-02-04 16:55:44] frigate.ptz.onvif              WARNING : Unable to get status from camera: Driveway: Unknown error: 
2024-02-04 16:55:44.518807185  [2024-02-04 16:55:44] frigate.http                   ERROR   : Exception on /Driveway/ptz/info [GET]
2024-02-04 16:55:44.518817928  Traceback (most recent call last):
2024-02-04 16:55:44.518828294    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
2024-02-04 16:55:44.518833431      response = self.full_dispatch_request()
2024-02-04 16:55:44.518838079    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
2024-02-04 16:55:44.518843128      rv = self.handle_user_exception(e)
2024-02-04 16:55:44.518847150    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
2024-02-04 16:55:44.518879750      rv = self.dispatch_request()
2024-02-04 16:55:44.518884711    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
2024-02-04 16:55:44.518920319      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-02-04 16:55:44.518924430    File "/opt/frigate/frigate/http.py", line 1414, in camera_ptz_info
2024-02-04 16:55:44.518928555      return jsonify(current_app.onvif.get_camera_info(camera_name))
2024-02-04 16:55:44.518932176    File "/opt/frigate/frigate/ptz/onvif.py", line 485, in get_camera_info
2024-02-04 16:55:44.518955738      self._init_onvif(camera_name)
2024-02-04 16:55:44.518960103    File "/opt/frigate/frigate/ptz/onvif.py", line 187, in _init_onvif
2024-02-04 16:55:44.518963393      ] = preset["token"]
2024-02-04 16:55:44.518967339  TypeError: 'NoneType' object is not subscriptable

**Comment by bobloadmire** [comment]
@ptruman I bought the 5ghz wifi jennov camera. It says it support rtsp/ptz but I can't for the life of me figure out the url. i've tried tons of combinations of rtsp://admin:@192.168.0.37:554/stream0 or rtsp://admin:@192.168.0.37:554/ch0_1.264 nothing works. Any ideas? Thanks

**Comment by ptruman** [comment]
It worked with netcat onvif under zoneminder for ptz, and even onvif device
manager figures it out, but it's not "standard".

If you just mean the high and low Def streams, I have those if you want
them

**Comment by ptruman** [comment]
So, for the streams, you will need:

rtsp://user:pass@your.cam.ip:554/stream0
rtsp://user:pass@your.cam.ip:554/stream1

You will need to set a user account up in the camera UI

I've got HQ video and audio working via Frigate nicely ("ffmpeg:rtsp_cam#audio=aac" / preset-nvidia-h264) - camera set to output as follows:

![Image](https://github.com/user-attachments/assets/4b3ef51d-d678-4050-88fe-838f9c683a2c)

![Image](https://github.com/user-attachments/assets/dfe4224c-203e-4d1b-bbf8-fef0d0cf9191)

**Comment by bobloadmire** [comment]
Well maybe that's the problem. There's no way to setup a user account in the UI and there's no web interface I can access as far as I can tell. A bunch of Amazon reviews mention the Rtsp works great but I have a feeling Jennov swapped out the camera on a listing with old reviews for an old product....

**Comment by ptruman** [comment]
Necro thread :)
Back, as I'm playing with a new frigate instance.

Still no PTZ, but Frigate now says this in logs:

`Error during ONVIF initialization for Driveway: 'NoneType' object has no attribute 'Name'`

I've moved to a Debian desktop (from Windows) and got "onvif viewer" running to the camera.  It controls the PTZ ok.
It returns my Jennov PTZ URL as : http://10.74.60.4/onvif/PTZ


onvif-utils however returns:
```
    name:   ONVIF_ICAMERA MSTAR_IPNC

get capabilities
  event_service:   POST /onvif/events HTTP/1.1

  imaging_service: POST /onvif/imaging HTTP/1.1

  media_service:   POST /onvif/imaging HTTP/1.1

  ptz_service:     POST /onvif/imaging HTTP/1.1


```
Useful bits of "dump" show:

```
Capabilities.PTZ.XAddr=http://10.74.60.4:80/onvif/ptz

Profile.PTZConfiguration.token=ptz0
Profile.PTZConfiguration.Name=ptz0
Profile.PTZConfiguration.UseCount=2
Profile.PTZConfiguration.NodeToken=ptz0
Profile.PTZConfiguration.DefaultAbsolutePantTiltPositionSpace=http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace
Profile.PTZConfiguration.DefaultAbsoluteZoomPositionSpace=http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace
Profile.PTZConfiguration.DefaultRelativePanTiltTranslationSpace=http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace
Profile.PTZConfiguration.DefaultRelativeZoomTranslationSpace=http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace
Profile.PTZConfiguration.DefaultContinuousPanTiltVelocitySpace=http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace
Profile.PTZConfiguration.DefaultContinuousZoomVelocitySpace=http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace
Profile.PTZConfiguration.DefaultPTZSpeed.PanTilt.x=1
Profile.PTZConfiguration.DefaultPTZSpeed.PanTilt.y=1
Profile.PTZConfiguration.DefaultPTZSpeed.PanTilt.space=http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace
Profile.PTZConfiguration.DefaultPTZSpeed.Zoom.x=1
Profile.PTZConfiguration.DefaultPTZSpeed.Zoom.space=http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace
Profile.PTZConfiguration.DefaultPTZTimeout=PT00H01M00S
Profile.PTZConfiguration.PanTiltLimits.Range.URI=http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace
Profile.PTZConfiguration.PanTiltLimits.Range.XRange.Min=-1
Profile.PTZConfiguration.PanTiltLimits.Range.XRange.Max=1
Profile.PTZConfiguration.PanTiltLimits.Range.YRange.Min=-1
Profile.PTZConfiguration.PanTiltLimits.Range.YRange.Max=1
Profile.PTZConfiguration.ZoomLimits.Range.URI=http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace
Profile.PTZConfiguration.ZoomLimits.Range.XRange.Min=-1
Profile.PTZConfiguration.ZoomLimits.Range.XRange.Max=1
```
