### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by imatech** [blakeblackshear/frigate#9583]
### Describe the problem you are having

just getting started and it's not working.  getting fatal time outs. and 505 bad gateway errors

### Version

Current version: 0.13.1

### Frigate config file

```yaml
qtt:
  host: localhost
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: cam
  password: camino123
  stats_interval: 60

  detectors:
    cpu1:
      type: cpu
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
2024-02-01 21:10:03.678474352  [INFO] Preparing new go2rtc config...
2024-02-01 21:10:03.714024853  [INFO] Got IP address from supervisor: 10.0.0.29
2024-02-01 21:10:03.749238674  [INFO] Got WebRTC port from supervisor: 8555
2024-02-01 21:10:03.988673457  [INFO] Starting go2rtc...
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
2024-02-01 21:10:04.009796627  [INFO] Preparing Frigate...
2024-02-01 21:10:04.018183691  [INFO] Starting Frigate...
2024-02-01 21:10:04.068176117  13:10:04.068 INF go2rtc version 1.8.4 linux/amd64
2024-02-01 21:10:04.068613214  13:10:04.068 INF [rtsp] listen addr=:8554
2024-02-01 21:10:04.068653823  13:10:04.068 INF [api] listen addr=:1984
2024-02-01 21:10:04.069016833  13:10:04.068 INF [webrtc] listen addr=:8555
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
2024-02-01 21:10:04.419024851  [INFO] Starting NGINX...
s6-rc: info: service go2rtc-healthcheck successfully started
2024-02-01 21:10:04.717180739  2024/02/01 13:10:04 [error] 156#156: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2024-02-01 21:10:07.888558782  [2024-02-01 13:10:07] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-01 21:10:07.888632153  [2024-02-01 13:10:07] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-02-01 21:10:07.892577331  *************************************************************
2024-02-01 21:10:07.892581396  *************************************************************
2024-02-01 21:10:07.892585631  ***    Your config file is not valid!                     ***
2024-02-01 21:10:07.892587976  ***    Please check the docs at                           ***
2024-02-01 21:10:07.892589473  ***    https://docs.frigate.video/configuration/index     ***
2024-02-01 21:10:07.892610627  *************************************************************
2024-02-01 21:10:07.892612439  *************************************************************
2024-02-01 21:10:07.892614417  ***    Config Validation Errors                           ***
2024-02-01 21:10:07.892615846  *************************************************************
2024-02-01 21:10:07.892666126  2 validation errors for FrigateConfig
2024-02-01 21:10:07.892667566  mqtt -> detectors
2024-02-01 21:10:07.892668867    extra fields not permitted (type=value_error.extra)
2024-02-01 21:10:07.892669935  cameras
2024-02-01 21:10:07.892671168    field required (type=value_error.missing)
2024-02-01 21:10:07.893514271  Traceback (most recent call last):
2024-02-01 21:10:07.893516396    File "/opt/frigate/frigate/app.py", line 645, in start
2024-02-01 21:10:07.893517563      self.init_config()
2024-02-01 21:10:07.893518847    File "/opt/frigate/frigate/app.py", line 112, in init_config
2024-02-01 21:10:07.893520126      user_config = FrigateConfig.parse_file(config_file)
2024-02-01 21:10:07.893521460    File "/opt/frigate/frigate/config.py", line 1333, in parse_file
2024-02-01 21:10:07.893522645      return cls.parse_obj(config)
2024-02-01 21:10:07.893523957    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2024-02-01 21:10:07.893525275    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2024-02-01 21:10:07.893526694  pydantic.error_wrappers.ValidationError: 2 validation errors for FrigateConfig
2024-02-01 21:10:07.893528409  mqtt -> detectors
2024-02-01 21:10:07.893529648    extra fields not permitted (type=value_error.extra)
2024-02-01 21:10:07.893557885  cameras
2024-02-01 21:10:07.893559551    field required (type=value_error.missing)
2024-02-01 21:10:07.893560581  
2024-02-01 21:10:07.893569976  *************************************************************
2024-02-01 21:10:07.893571503  ***    End Config Validation Errors                       ***
2024-02-01 21:10:07.893572775  *************************************************************
```

### FFprobe output from your camera

```shell
no cameras connected yet
```

### Frigate stats

```json
not sure where I'd find this
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

HiSeeYou and Reaoto

**Comment by NickM-27** [comment]
the config is not formatted correctly, `detectors` is indented too much

**Comment by imatech** [comment]
thank you, fixed it.  I'm still having issues though.  Do you know how to find the RTSP syntax for my hiseeu cameras?
[logs.txt](https://github.com/blakeblackshear/frigate/files/14143847/logs.txt)
[frigate.yml.txt](https://github.com/blakeblackshear/frigate/files/14143848/frigate.yml.txt)

**Comment by NickM-27** [comment]
I would suggest creating a new issue
