### ISSUE TITLE
[Support]: Error while running recording_cleanup seconds after startup

### ISSUE THREAD

**Issue by trunet** [blakeblackshear/frigate#9617]
### Describe the problem you are having

When starting frigate, I'm getting the error shown on the log below.

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
record:
  enabled: true
  retain:
    days: 5
  events:
    pre_capture: 5
    post_capture: 5
    retain:
      default: 14
      mode: active_objects
      objects:
        person: 30
```

### Relevant log output

```shell
2024-02-03 00:08:41.915091387  Exception in thread recording_cleanup:
2024-02-03 00:08:41.915094649  Traceback (most recent call last):
2024-02-03 00:08:41.915112245    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2024-02-03 00:08:41.915278203      self.run()
2024-02-03 00:08:41.915279737    File "/opt/frigate/frigate/record/cleanup.py", line 200, in run
2024-02-03 00:08:41.915352493      self.expire_recordings()
2024-02-03 00:08:41.915354788    File "/opt/frigate/frigate/record/cleanup.py", line 60, in expire_recordings
2024-02-03 00:08:41.915386329      Path(recording.path).unlink(missing_ok=True)
2024-02-03 00:08:41.915394077    File "/usr/lib/python3.9/pathlib.py", line 1343, in unlink
2024-02-03 00:08:41.915523940      self._accessor.unlink(self)
2024-02-03 00:08:41.915539284  IsADirectoryError: [Errno 21] Is a directory: '.'
```

### FFprobe output from your camera

```shell
N/A
```

### Frigate stats

```json
{"cameras":{"cam04":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":1579,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1591,"pid":1566,"process_fps":5.0,"skipped_fps":0.0},"doorbell":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":7.1,"capture_pid":1576,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":1584,"pid":1564,"process_fps":7.1,"skipped_fps":0.0},"frontyard":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":5.0,"capture_pid":1568,"detection_enabled":1,"detection_fps":0.1,"ffmpeg_pid":1573,"pid":1561,"process_fps":5.0,"skipped_fps":0.0},"garden":{"audio_dBFS":0.0,"audio_rms":0.0,"camera_fps":6.1,"capture_pid":1572,"detection_enabled":1,"detection_fps":0.0,"ffmpeg_pid":1577,"pid":1562,"process_fps":6.1,"skipped_fps":0.0}},"cpu_usages":{"1":{"cmdline":"/package/admin/s6/command/s6-svscan -d4 -- /run/service","cpu":"0.0","cpu_average":"0","mem":"0.0"},"954":{"cmdline":"s6-supervise s6-linux-init-shutdownd","cpu":"0.0","cpu_average":"0","mem":"0.0"},"955":{"cmdline":"/package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B","cpu":"0.0","cpu_average":"0","mem":"0.0"},"963":{"cmdline":"s6-supervise s6rc-oneshot-runner","cpu":"0.0","cpu_average":"0","mem":"0.0"},"964":{"cmdline":"s6-supervise s6rc-fdholder","cpu":"0.0","cpu_average":"0","mem":"0.0"},"965":{"cmdline":"s6-supervise frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"966":{"cmdline":"s6-supervise frigate-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"967":{"cmdline":"s6-supervise go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"968":{"cmdline":"s6-supervise go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"969":{"cmdline":"s6-supervise go2rtc-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"970":{"cmdline":"s6-supervise nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"971":{"cmdline":"s6-supervise nginx-log","cpu":"0.0","cpu_average":"0","mem":"0.0"},"980":{"cmdline":"/package/admin/s6-2.11.3.2/command/s6-fdholderd -1 -i data/rules","cpu":"0.0","cpu_average":"0","mem":"0.0"},"981":{"cmdline":"/package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../.. --","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1019":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1020":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/go2rtc","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1021":{"cmdline":"s6-log -b -- T 1 n0 s10000000 T /dev/shm/logs/frigate","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1028":{"cmdline":"/usr/local/go2rtc/bin/go2rtc -config=/dev/shm/go2rtc.yaml","cpu":"3.7","cpu_average":"3","mem":"0.0"},"1036":{"cmdline":"bash ./run.user go2rtc-healthcheck","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1037":{"cmdline":"python3 -u -m frigate","cpu":"1.4","cpu_average":"3","mem":"0.6"},"1043":{"cmdline":"nginx: master process nginx","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1084":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1085":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1086":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1090":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1101":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1116":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1138":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1165":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1192":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1226":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1263":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1298":{"cmdline":"nginx: worker process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1339":{"cmdline":"nginx: cache manager process","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1524":{"cmdline":"frigate.logger       ","cpu":"0.0","cpu_average":"0","mem":"0.2"},"1526":{"cmdline":"frigate.recording_manager","cpu":"2.6","cpu_average":"1","mem":"0.3"},"1535":{"cmdline":"/usr/bin/python3 -c from multiprocessing.resource_tracker import main;main(51)","cpu":"0.2","cpu_average":"0","mem":"0.0"},"1536":{"cmdline":"frigate.detector.coral","cpu":"0.0","cpu_average":"0","mem":"0.3"},"1538":{"cmdline":"frigate.output       ","cpu":"0.6","cpu_average":"0","mem":"0.3"},"1544":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 704x480 -i pipe: -f mpegts -s 1056x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1545":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1546":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1547":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 640x480 -i pipe: -f mpegts -s 960x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1548":{"cmdline":"ffmpeg -f rawvideo -pix_fmt yuv420p -video_size 1280x720 -i pipe: -f mpegts -s 1280x720 -codec:v mpeg1video -q 8 -bf 0 pipe:","cpu":"0.0","cpu_average":"0","mem":"0.0"},"1561":{"cmdline":"frigate.process:frontyard","cpu":"0.9","cpu_average":"3","mem":"0.3"},"1562":{"cmdline":"frigate.process:garden","cpu":"0.6","cpu_average":"3","mem":"0.3"},"1564":{"cmdline":"frigate.process:doorbell","cpu":"1.1","cpu_average":"1","mem":"0.3"},"1566":{"cmdline":"frigate.process:cam04","cpu":"0.5","cpu_average":"3","mem":"0.3"},"1568":{"cmdline":"frigate.capture:frontyard","cpu":"0.5","cpu_average":"0","mem":"0.3"},"1572":{"cmdline":"frigate.capture:garden","cpu":"0.3","cpu_average":"0","mem":"0.3"},"1573":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontyardsd -r 5 -vf fps=5,scale_vaapi=w=704:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.6","cpu_average":"0","mem":"0.1"},"1576":{"cmdline":"frigate.capture:doorbell","cpu":"0.6","cpu_average":"0","mem":"0.3"},"1577":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gardensd -r 6 -vf fps=6,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.8","cpu_average":"0","mem":"0.1"},"1579":{"cmdline":"frigate.capture:cam04","cpu":"0.5","cpu_average":"0","mem":"0.3"},"1584":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbellsd?video=copy -r 7 -vf fps=7,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.9","cpu_average":"0","mem":"0.1"},"1588":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/frontyardhd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/frontyard@%Y%m%d%H%M%S%z.mp4","cpu":"0.5","cpu_average":"0","mem":"0.0"},"1590":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/gardenhd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/garden@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.0"},"1591":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam04sd -r 5 -vf fps=5,scale_vaapi=w=640:h=480:format=nv12,hwdownload,format=nv12,format=yuv420p -threads 2 -f rawvideo -pix_fmt yuv420p pipe:","cpu":"0.5","cpu_average":"0","mem":"0.1"},"1594":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.179.65/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=*&password=* -c copy -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/cea87fa54daf523cf9a39313973a0b40","cpu":"0.5","cpu_average":"0","mem":"0.1"},"1597":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/doorbellhd?video=copy&audio=aac -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac /tmp/cache/doorbell@%Y%m%d%H%M%S%z.mp4","cpu":"1.7","cpu_average":"1","mem":"0.1"},"1598":{"cmdline":"ffmpeg -hide_banner -loglevel warning -threads 2 -hwaccel_flags allow_profile_mismatch -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -user_agent FFmpeg Frigate/0.13.1-34fb1c2 -rtsp_transport tcp -timeout 5000000 -i rtsp://127.0.0.1:8554/cam04hd -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an /tmp/cache/cam04@%Y%m%d%H%M%S%z.mp4","cpu":"0.3","cpu_average":"0","mem":"0.0"},"1599":{"cmdline":"ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -i https://192.168.179.65/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=*&password=* -map 0:v:0? -c:v:0 copy -map 0:a:0? -c:a:0 copy -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/ca54e9d4c332ba4f5a31d668c460b060","cpu":"1.2","cpu_average":"0","mem":"0.1"},"2671":{"cmdline":"sleep 30s","cpu":"0.0","cpu_average":"0","mem":"0.0"}},"detection_fps":0.2,"detectors":{"coral":{"detection_start":0.0,"inference_speed":4.88,"pid":1536}},"gpu_usages":{"intel-vaapi":{"gpu":"0.38%","mem":"-%"}},"processes":{"go2rtc":{"pid":1028},"logger":{"pid":1524},"recording":{"pid":1526}},"service":{"last_updated":1706919041,"latest_version":"0.13.1","storage":{"/dev/shm":{"free":507.7,"mount_type":"tmpfs","total":512.0,"used":4.3},"/media/frigate/clips":{"free":1113803.0,"mount_type":"nfs4","total":2560000.0,"used":1446197.0},"/media/frigate/recordings":{"free":1113803.0,"mount_type":"nfs4","total":2560000.0,"used":1446197.0},"/tmp/cache":{"free":35322.7,"mount_type":"overlay","total":49932.0,"used":14609.3}},"temperatures":{},"uptime":180,"version":"0.13.1-34fb1c2"}}
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Wired

### Camera make and model

multiple

**Comment by NickM-27** [comment]
please provide your full config and full copy of logs
