### ISSUE TITLE
[Config Support]: Invalid Config

### ISSUE THREAD

**Issue by Frazou1** [blakeblackshear/frigate#9660]
### Describe the problem you are having

After upgrading to 13.0 add on wont start

### Version

13.0 / 13.1

### Frigate config file

```yaml
mqtt:
  host: 192.168.2.65
  user: cameramqtt
  password: xxxx

# Optional: Detectors configuration. Defaults to a single CPU detector
detectors:
  cpu1:
    type: cpu
    num_threads: 3
  cpu2:
    type: cpu
    num_threads: 3
  cpu3:
    type: cpu
    num_threads: 3
  cpu4:
    type: cpu
    num_threads: 3

birdseye:
  enabled: True
  width: 1080
  height: 1920
  quality: 1
  mode: objects

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 2
    mode: all
  events:
    pre_capture: 3
    post_capture: 3
    objects:
      - person
      - car
    retain:
      default: 5
      mode: motion

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  crop: True
  retain:
    default: 5
    objects:
      person: 5
      car: 5
      dog: 5

detect:
  max_disappeared: 25
  stationary:
    interval: 0
    threshold: 50
    max_frames:
      default: 3000
      objects:
        person: 1000
        car: 5000
objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person
    - car
    - dog
    - cat
  filters:
    person:
      min_area: 5000
      max_area: 100000
      min_ratio: 0.5
      max_ratio: 2.0
      min_score: 0.8
      threshold: 0.65
    car:
      min_area: 5000
      max_area: 100000
      min_score: 0.6


# Optional: Motion configuration
# NOTE: Can be overridden at the camera level
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: 30)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 15 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 30
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 50)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense
  # of higher CPU usage. Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 50
  # Optional: improve contrast (default: shown below)
  # Enables dynamic contrast improvement. This should help improve night detections at the cost of making motion detection more sensitive
  # for daytime.
  improve_contrast: False
  # Optional: Delay when updating camera motion through MQTT from ON -> OFF (default: shown below).
  mqtt_off_delay: 30


cameras:
  Cam_Ext_Arriere: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.2.128:554/stream1
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,0,0,40,406,39,409,0
        - 466,0,0,0,0,296
        - 0,720,274,720,0,346
        - 1280,720,1062,720,1280,470
        - 1280,0,1061,0,943,0,1280,291
    zones:
      arriere_motion_area:
        coordinates: 411,0,395,40,330,45,141,270,28,397,269,720,1052,720,1280,468,1280,297,961,0
    objects:
      filters:
        cat:
          mask:
            - 0,0,0,40,406,39,409,0
            - 169,0,0,0,0,148
            - 0,720,274,720,0,346
            - 1280,720,1062,720,1280,470
            - 1280,0,1061,0,943,0,1280,291
        dog:
          mask:
            - 0,0,0,40,406,39,409,0
            - 169,0,0,0,0,148
            - 0,720,274,720,0,346
            - 1280,720,1062,720,1280,470
            - 1280,0,1061,0,943,0,1280,291
        person:
          mask:
            - 0,0,0,40,406,39,409,0
            - 169,0,0,0,0,148
            - 0,720,274,720,0,346
            - 1280,720,1062,720,1280,470
            - 1280,0,1061,0,943,0,1280,291
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: True
  Camera_Stationnement: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxxx:xxx@192.168.2.201:554/stream1
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,0,0,40,406,39,409,0
        - 359,0,0,244,0,0
        - 1195,0,360,0,0,0,0,162,159,144,273,37,1030,94,1188,209
    zones:
      stationnement_motion_area:
        coordinates: 0,720,1280,720,1280,111,466,42,287,44,0,362
    objects:
      filters:
        car:
          mask:
            - 0,0,0,40,406,39,409,0
            - 359,0,0,244,0,0
            - 1195,0,360,0,0,0,0,162,159,144,273,37,1030,94,1188,209
        cat:
          mask:
            - 0,0,0,40,406,39,409,0
            - 359,0,0,244,0,0
            - 1195,0,360,0,0,0,0,162,159,144,273,37,1030,94,1188,209
        dog:
          mask:
            - 0,0,0,40,406,39,409,0
            - 359,0,0,244,0,0
            - 1195,0,360,0,0,0,0,162,159,144,273,37,1030,94,1188,209
        person:
          mask:
            - 0,0,0,40,406,39,409,0
            - 359,0,0,244,0,0
            - 1195,0,360,0,0,0,0,162,159,144,273,37,1030,94,1188,209
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: True
 
  Cam_Avant: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.2.244:554/stream1
          roles:
            - detect
            - record
    motion:
      mask:
        - 1280,0,1280,720,989,720,980,167,376,104,218,238,0,388,0,0
        - 0,720,253,720,175,531,0,386
    zones:
      avant_motion_area:
        coordinates: 1016,177,1098,720,419,720,244,720,166,590,174,516,25,429,430,102
    objects:
      filters:
        cat:
          mask:
            - 1280,0,1280,720,989,720,980,167,376,104,218,238,0,388,0,0
            - 0,720,253,720,175,531,0,386
        dog:
          mask:
            - 1280,0,1280,720,989,720,980,167,376,104,218,238,0,388,0,0
            - 0,720,253,720,175,531,0,386
        person:
          mask:
            - 1280,0,1280,720,989,720,980,167,376,104,218,238,0,388,0,0
            - 0,720,253,720,175,531,0,386
        car:
          mask:
            - 1280,0,1280,720,989,720,980,167,376,104,218,238,0,388,0,0
            - 0,720,253,720,175,531,0,386
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: True
  Cam_Cours: # <------ Name the camera
    ffmpeg:
      inputs:
        - path: rtsp://xxx:xxx@192.168.2.193:554/stream1
          roles:
            - detect
            - record
    motion:
      mask:
        - 0,116,513,112,528,160,600,173,652,169,679,0,0,0
        - 1090,171,1280,80,1280,0,1114,0
        - 0,720,173,720,0,486
    zones:
      cours_motion_area:
        coordinates: 0,474,45,614,95,631,205,720,1280,720,1280,73,1098,142,670,93,649,170,586,142,540,134,522,109,0,121
    objects:
      filters:
        cat:
          mask:
            - 0,116,513,112,528,160,600,173,652,169,679,0,0,0
            - 1090,171,1280,80,1280,0,1114,0
            - 0,720,173,720,0,486
        dog:
          mask:
            - 0,116,513,112,528,160,600,173,652,169,679,0,0,0
            - 1090,171,1280,80,1280,0,1114,0
            - 0,720,173,720,0,486
        person:
          mask:
            - 0,116,513,112,528,160,600,173,652,169,679,0,0,0
            - 1090,171,1280,80,1280,0,1114,0
            - 0,720,173,720,0,486
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
    detect:
      enabled: True
  Cam_Sonette: # <------ Name the camera
    ffmpeg:
      input_args: preset-http-reolink
      inputs:
        - path: http://192.168.2.65:43330/hls/Sonette.m3u8
          roles:
            - detect
            - record
            - rtmp
    detect:
      enabled: True
    record:
      enabled: True
    motion:
      mask:
        - 55,68,470,69,465,29,57,28
        - 953,378,1034,669,1174,720,1280,457,1243,32,494,21,468,376
    zones:
      sonnette_motion_area:
        coordinates: 490,720,1014,720,1008,507,954,389,465,388
    objects:
      filters:
        cat:
          mask:
            - 55,68,470,69,465,29,57,28
            - 953,378,1034,669,1174,720,1280,457,1243,32,494,21,468,376
        dog:
          mask:
            - 55,68,470,69,465,29,57,28
            - 953,378,1034,669,1174,720,1280,457,1243,32,494,21,468,376
        person:
          mask:
            - 55,68,470,69,465,29,57,28
            - 953,378,1034,669,1174,720,1280,457,1243,32,494,21,468,376
    rtmp:
      enabled: False # <-- RTMP should be disabled if your stream is not H264
```

### Relevant log output

```shell
s6-rc: info: service s6rc-fdholder: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service s6rc-fdholder successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service log-prepare: starting
s6-rc: info: service log-prepare successfully started
s6-rc: info: service nginx-log: starting
s6-rc: info: service go2rtc-log: starting
s6-rc: info: service frigate-log: starting
s6-rc: info: service nginx-log successfully started
s6-rc: info: service go2rtc-log successfully started
s6-rc: info: service go2rtc: starting
s6-rc: info: service frigate-log successfully started
s6-rc: info: service go2rtc successfully started
s6-rc: info: service go2rtc-healthcheck: starting
s6-rc: info: service frigate: starting
s6-rc: info: service go2rtc-healthcheck successfully started
s6-rc: info: service frigate successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
2024-02-05 01:49:51.171216791  [INFO] Starting NGINX...
2024-02-05 01:49:51.173397683  [INFO] Preparing Frigate...
2024-02-05 01:49:51.178551698  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-02-05 01:49:51.226923603  [INFO] Starting Frigate...
2024-02-05 01:49:51.290932669  [INFO] Got IP address from supervisor: 192.168.2.65
2024-02-05 01:49:51.393430395  [WARN] Failed to get WebRTC port from supervisor
2024-02-05 01:49:51.924133940  [INFO] Starting go2rtc...
2024-02-05 01:49:52.062313207  20:49:52.062 INF go2rtc version 1.8.4 linux/amd64
2024-02-05 01:49:52.062953365  20:49:52.062 INF [api] listen addr=:1984
2024-02-05 01:49:52.063138817  20:49:52.062 INF [rtsp] listen addr=:8554
2024-02-05 01:49:52.063400025  20:49:52.063 INF [webrtc] listen addr=:8555
2024-02-05 01:49:54.245737767  [2024-02-04 20:49:54] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-05 01:49:54.246419113  [2024-02-04 20:49:54] frigate.app                    INFO    : Creating directory: /tmp/cache
2024-02-05 01:49:54.275379797  *************************************************************
2024-02-05 01:49:54.275388155  *************************************************************
2024-02-05 01:49:54.275397215  ***    Your config file is not valid!                     ***
2024-02-05 01:49:54.275402866  ***    Please check the docs at                           ***
2024-02-05 01:49:54.275406090  ***    https://docs.frigate.video/configuration/index     ***
2024-02-05 01:49:54.275459046  *************************************************************
2024-02-05 01:49:54.275500936  *************************************************************
2024-02-05 01:49:54.275504062  ***    Config Validation Errors                           ***
2024-02-05 01:49:54.275506840  *************************************************************
2024-02-05 01:49:54.275725976  1 validation error for FrigateConfig
2024-02-05 01:49:54.275729587  detect -> stationary -> interval
2024-02-05 01:49:54.275732668    ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)
2024-02-05 01:49:54.276613738  Traceback (most recent call last):
2024-02-05 01:49:54.276617662    File "/opt/frigate/frigate/app.py", line 645, in start
2024-02-05 01:49:54.276620205      self.init_config()
2024-02-05 01:49:54.276622936    File "/opt/frigate/frigate/app.py", line 112, in init_config
2024-02-05 01:49:54.276625621      user_config = FrigateConfig.parse_file(config_file)
2024-02-05 01:49:54.276628570    File "/opt/frigate/frigate/config.py", line 1333, in parse_file
2024-02-05 01:49:54.276631072      return cls.parse_obj(config)
2024-02-05 01:49:54.276633891    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2024-02-05 01:49:54.276639222    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2024-02-05 01:49:54.276642438  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2024-02-05 01:49:54.276645451  detect -> stationary -> interval
2024-02-05 01:49:54.276648517    ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)
2024-02-05 01:49:54.276739461  
2024-02-05 01:49:54.276742768  *************************************************************
2024-02-05 01:49:54.276745548  ***    End Config Validation Errors                       ***
2024-02-05 01:49:54.276793451  *************************************************************
2024-02-05 01:49:55.716913585  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
s6-rc: info: service go2rtc-healthcheck: stopping
2024-02-05 01:49:55.765358030  [INFO] The go2rtc-healthcheck service exited with code 256 (by signal 15)
s6-rc: info: service go2rtc-healthcheck successfully stopped
2024-02-05 01:49:55.803050118  [INFO] Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service nginx-log: stopping
s6-rc: info: service frigate: stopping
s6-rc: info: service frigate successfully stopped
s6-rc: info: service go2rtc: stopping
s6-rc: info: service frigate-log: stopping
2024-02-05 01:49:55.816603341  exit with signal: terminated
s6-rc: info: service nginx-log successfully stopped
s6-rc: info: service frigate-log successfully stopped
2024-02-05 01:49:55.830345999  [INFO] The go2rtc service exited with code 0 (by signal 0)
s6-rc: info: service go2rtc successfully stopped
s6-rc: info: service go2rtc-log: stopping
s6-rc: info: service go2rtc-log successfully stopped
s6-rc: info: service log-prepare: stopping
s6-rc: info: service s6rc-fdholder: stopping
s6-rc: info: service log-prepare successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service s6rc-fdholder successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

CPU (no coral)

**Comment by NickM-27** [comment]
0 is not a valid value for stationary interval.  That part should be removed from the config so the default is used.

**Comment by Frazou1** [comment]
Im looking on the documention and i put at the same way. So i not sure where to put the 0 on the config. 
![image](https://github.com/blakeblackshear/frigate/assets/89617565/b150bd76-9ac9-4465-83c3-2a716c6b7763)

**Comment by Frazou1** [comment]
Sorry, you said 0 is not a valid value for stationary interval.  If i looking on the documention and my own config file are set the same. So im not sure what i need to change on my config file ? 
![image](https://github.com/blakeblackshear/frigate/assets/89617565/b2a58f17-6cf6-4a99-b5fc-2efa08724faf)

**Comment by NickM-27** [comment]
they are not set the same, you have a 0 there and the docs have a 50

**Comment by Frazou1** [comment]
Is working now. I will need to understand again the stationnary how they work :S  Thanks !
