### ISSUE TITLE
[Support]: updated and now won't run

### ISSUE THREAD

**Issue by amkrafie** [blakeblackshear/frigate#9713]
### Describe the problem you are having

Updated my frigate stack (using containers on a proxmox) and now it won't start

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
mqtt:
  enabled: true
  host: x
  user: x
  password: x
  port: x


detectors:
  coral:
    type: edgetpu
    device: usb

  #deepstack:
  #  api_url: http://x/v1/vision/detection
  #  type: deepstack
  #  api_timeout: 0.1 # seconds

rtmp:
  enabled: false


birdseye:
  enabled: True
  mode: continuous


ffmpeg:
  hwaccel_args: preset-vaapi



objects:
    track:
    - person
    - car
    - dog
    - cat

snapshots:
  # Optional: Enable writing jpg snapshot to /media/frigate/clips (default: shown below)
  # This value can be set via MQTT and will be updated in startup based on retained value
  enabled: True
  # Optional: print a timestamp on the snapshots (default: shown below)
  timestamp: True
  # Optional: draw bounding box on the snapshots (default: shown below)
  bounding_box: True
  # Optional: crop the snapshot (default: shown below)
  crop: False
  # Optional: height to resize the snapshot to (default: original size)
  #height: 175
  # Optional: Restrict snapshots to objects that entered any of the listed zones (default: no required zones)
  #required_zones: []
  # Optional: Camera override for retention settings (default: global values)
  retain:
    # Required: Default retention days (default: shown below)
    default: 5
    # Optional: Per object retention days
    objects:
      person: 5
      car: 3
      

record:
  enabled: True
  retain:
    days: 5
    mode: motion
  events:
    retain:
      default: 5
      mode: active_objects


go2rtc:
  streams:
    diningrecord:
     #- rtsp://x/cam/realmonitor?channel=1&subtype=0
      - rtsp://x/cam/realmonitor?channel=1&subtype=0
      - ffmpeg:diningrecord#audio=opus
    
   #diningdetect:
     #  - rtsp://x/cam/realmonitor?channel=1&subtype=1
    livingrecord:
     - rtsp://x/stream2
     - tapo://x
     # - ffmpeg:livingrecord#audio=opus
   #livingdetect:
     #  - rtsp://x/stream2
    xrecord:
     - rtsp://x/stream2
     - tapo://x
    xxrecord:
      - rtsp:/X/stream1
      - tapo://x
     # - ffmpeg:xxrecord#audio=opus
    #xxdetect:
     #  - rtsp://x/stream2
    #garagerecord:
     #  - rtsp://x/h264Preview_01_main
     #  - ffmpeg:your_reolink_camera#audio=opus
    garagerecord:
      #  - rtsp://x/h264Preview_01_sub
       - http://x/flv?port=x&app=bcs&stream=channel0_main.bcs&user=admin&password=x
       - ffmpeg:rtsp://x/h264Preview_01_sub#audio=pcm#audio=volume
       #- ffmpeg:garagerecord#audio=opus 
    frontrecord:
      - rtsp://x/Streaming/Channels/101
      - isapi://x/
     # - ffmpeg:frontrecord#audio=opus
  ffmpeg:
    bin: ffmpeg
    volume: "-af \"volume=30dB\""


cameras:
  dining:
    ffmpeg:
      #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      #output_args:
      #  record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -tag:v hvc1 -c:a aac
      #  rtmp: -c copy -f flv -tag:v hvc1
      #  detect: -f rawvideo -pix_fmt yuv420p      
      inputs:
        - path: rtsp://x/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
            - detect
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 2688
      height: 1520
    record:
      enabled: true
    #motion: 
      #enabled: true
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots by(default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1520
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
    live:
      stream_name: diningrecord
    
  living:
    ffmpeg:
      #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://127.0.0.1:8554/livingrecord
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/livingrecord
          roles:
            - record           
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 2688
      height: 1520
    record:
      enabled: true
    #motion: 
      #enabled: true
    live:
      stream_name: livingrecord
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1520
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
  x:
    ffmpeg:
      #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://127.0.0.1:8554/xrecord
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/xrecord
          roles:
            - record           
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 2688
      height: 1520
    record:
      enabled: true
    #motion: 
      #enabled: true
    live:
      stream_name: xrecord
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1520
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
  xx:
    ffmpeg:
      #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://127.0.0.1:8554/xxrecord
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/xxrecord
          roles:
            - record           
      output_args:
       detect: -f rawvideo -pix_fmt yuv420p
       record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 2304
      height: 1296
    record:
      enabled: true
    #motion: 
      #enabled: true
    live:
      stream_name: xxrecord
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1296
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
  garage:
    ffmpeg:
      #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://127.0.0.1:8554/garagerecord
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/garagerecord
          input_args: preset-rtsp-restream
          roles:
            - record
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 2560 
      height: 1920
    record:
      enabled: true
    #motion: 
      #enabled: true
    live:
      stream_name: garagerecord
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 1920
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []
  front:
    ffmpeg:
      #input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      inputs:
        - path: rtsp://127.0.0.1:8554/frontrecord
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/frontrecord
          roles:
            - record
      output_args:
        detect: -f rawvideo -pix_fmt yuv420p
        record: -f segment -segment_time 15 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -c:a aac
    detect:
      width: 3840
      height: 2160
    record:
      enabled: true
    #motion: 
      #enabled: true
    live:
      stream_name: frontrecord
    mqtt:
      # Optional: Enable publishing snapshot via mqtt for camera (default: shown below)
      # NOTE: Only applies to publishing image data to MQTT via 'frigate/<camera_name>/<object_name>/snapshot'.
      # All other messages will still be published.
      enabled: True
      # Optional: print a timestamp on the snapshots (default: shown below)
      timestamp: false
      # Optional: draw bounding box on the snapshots (default: shown below)
      bounding_box: false
      # Optional: crop the snapshot (default: shown below)
      crop: false
      # Optional: height to resize the snapshot to (default: shown below)
      height: 2160
      # Optional: jpeg encode quality (default: shown below)
      quality: 100
      # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
      #required_zones: []  

 # Optional: logger verbosity settings
logger:
  # Optional: Default log verbosity (default: shown below)
  default: info
  # Optional: Component specific logger overrides
  logs:
    frigate.event: debug     

#database:
  # The path to store the SQLite DB (default: shown below)
 # path: /media/NAS/frigate.db


#ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
#  global_args: -hide_banner -loglevel warning -threads 2
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
#  hwaccel_args: []
  # Optional: global input args (default: shown below)
#  input_args: preset-rtsp-generic
  # Optional: global output args
#  output_args:
    # Optional: output args for detect streams (default: shown below)
#    detect: -threads 2 -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
#    record: preset-record-generic
    # Optional: output args for rtmp streams (default: shown below)
#    rtmp: preset-rtmp-generic
```

### Relevant log output

```shell
2024-02-07 00:09:14.438045064  [INFO] Preparing Frigate...
2024-02-07 00:09:14.438671240  [INFO] Starting NGINX...
2024-02-07 00:09:14.439129826  [INFO] Preparing new go2rtc config...
s6-rc: info: service legacy-services successfully started
2024-02-07 00:09:14.449221430  [INFO] Starting Frigate...
2024-02-07 00:09:14.591664489  [INFO] Starting go2rtc...
2024-02-07 00:09:14.656797722  00:09:14.656 INF go2rtc version 1.8.4 linux/amd64
2024-02-07 00:09:14.657165545  00:09:14.657 INF [rtsp] listen addr=:8554
2024-02-07 00:09:14.657189831  00:09:14.657 INF [api] listen addr=:1984
2024-02-07 00:09:14.657319701  00:09:14.657 INF [webrtc] listen addr=:8555
2024-02-07 00:09:15.064883531  [2024-02-07 00:09:15] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-07 00:09:15.105804495  [2024-02-07 00:09:15] peewee_migrate.logs            INFO    : Starting migrations
2024-02-07 00:09:15.649702256  [2024-02-07 00:09:15] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-07 00:09:15.702096639  [2024-02-07 00:09:15] frigate.app                    INFO    : Recording process started: 728
2024-02-07 00:09:15.703048509  [2024-02-07 00:09:15] frigate.app                    INFO    : go2rtc process pid: 88
2024-02-07 00:09:15.713760219  [2024-02-07 00:09:15] detector.coral                 INFO    : Starting detection process: 738
2024-02-07 00:09:15.714507088  [2024-02-07 00:09:15] frigate.app                    INFO    : Output process started: 740
2024-02-07 00:09:18.353620843  [2024-02-07 00:09:15] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-02-07 00:09:18.355989640  [2024-02-07 00:09:18] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-02-07 00:09:24.438447517  [INFO] Starting go2rtc healthcheck service...
2024-02-07 00:09:24.512910009  192.168.1.123 - - [07/Feb/2024:00:09:24 +0300] "GET / HTTP/1.1" 200 10672 "-" "HomeAssistantSupervisor/2024.01.1 aiohttp/3.9.3 Python/3.12" "172.30.32.2"
2024-02-07 00:09:25.747212295  Exception in thread Thread-1:
2024-02-07 00:09:25.747215049  Traceback (most recent call last):
2024-02-07 00:09:25.747216082    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3193, in connect
2024-02-07 00:09:25.747371542      self._state.set_connection(self._connect())
2024-02-07 00:09:25.747374540    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3540, in _connect
2024-02-07 00:09:25.747517982      self._add_conn_hooks(conn)
2024-02-07 00:09:25.747519792    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqlite_ext.py", line 1030, in _add_conn_hooks
2024-02-07 00:09:25.747525892      super(SqliteExtDatabase, self)._add_conn_hooks(conn)
2024-02-07 00:09:25.747526867    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3550, in _add_conn_hooks
2024-02-07 00:09:25.747741208      self._set_pragmas(conn)
2024-02-07 00:09:25.747742999    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3565, in _set_pragmas
2024-02-07 00:09:25.747877166      cursor.execute('PRAGMA %s = %s;' % (pragma, value))
2024-02-07 00:09:25.747878854  sqlite3.OperationalError: locking protocol
2024-02-07 00:09:25.747879612  
2024-02-07 00:09:25.747880406  During handling of the above exception, another exception occurred:
2024-02-07 00:09:25.747883456  
2024-02-07 00:09:25.747884049  Traceback (most recent call last):
2024-02-07 00:09:25.747884938    File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
2024-02-07 00:09:25.747920175      self.run()
2024-02-07 00:09:25.747921172    File "/usr/lib/python3.9/threading.py", line 892, in run
2024-02-07 00:09:25.747993722      self._target(*self._args, **self._kwargs)
2024-02-07 00:09:25.747995536    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 263, in run
2024-02-07 00:09:25.747996399      writer.run()
2024-02-07 00:09:25.747997269    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqliteq.py", line 127, in run
2024-02-07 00:09:25.748004939      conn = self.database.connection()
2024-02-07 00:09:25.748011670    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3233, in connection
2024-02-07 00:09:25.748184448      self.connect()
2024-02-07 00:09:25.748186201    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3196, in connect
2024-02-07 00:09:25.748330332      self._initialize_connection(self._state.conn)
2024-02-07 00:09:25.748332066    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3020, in __exit__
2024-02-07 00:09:25.748431695      reraise(new_type, new_type(exc_value, *exc_args), traceback)
2024-02-07 00:09:25.748432775    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 192, in reraise
2024-02-07 00:09:25.748446417      raise value.with_traceback(tb)
2024-02-07 00:09:25.748447301    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3193, in connect
2024-02-07 00:09:25.748627011      self._state.set_connection(self._connect())
2024-02-07 00:09:25.748628778    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3540, in _connect
2024-02-07 00:09:25.748751108      self._add_conn_hooks(conn)
2024-02-07 00:09:25.748752153    File "/usr/local/lib/python3.9/dist-packages/playhouse/sqlite_ext.py", line 1030, in _add_conn_hooks
2024-02-07 00:09:25.748808192      super(SqliteExtDatabase, self)._add_conn_hooks(conn)
2024-02-07 00:09:25.748809115    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3550, in _add_conn_hooks
2024-02-07 00:09:25.748966206      self._set_pragmas(conn)
2024-02-07 00:09:25.748967086    File "/usr/local/lib/python3.9/dist-packages/peewee.py", line 3565, in _set_pragmas
2024-02-07 00:09:25.749132340      cursor.execute('PRAGMA %s = %s;' % (pragma, value))
2024-02-07 00:09:25.749135677  peewee.OperationalError: locking protocol
2024-02-07 00:09:29.483503262  2024/02/07 00:09:29 [error] 141#141: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
2024-02-07 00:09:44.543085495  2024/02/07 00:09:44 [error] 142#142: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /api/version HTTP/1.1", upstream: "http://127.0.0.1:5001version", host: "127.0.0.1:5000"
```

### FFprobe output from your camera

```shell
NA
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

Tapo,Reolink

**Comment by NickM-27** [comment]
what is your docker compose

**Comment by coldkevin** [comment]
Im experiecing this aswell. Updated two days ago and sometime today frigate went down and the container will not start now.

**Comment by carchuleta** [comment]
well I am glad I am not the only one. I have tried removing the integration and reinstalling it but no luck.. I still get Failed to setup.

**Comment by lanefloch** [comment]
Same here

**Comment by amkrafie** [comment]
> Same here. Deleted Frigate.db and now it works fine

I tried that but it didn't work, I ended up changing all the storage locations, and just copied my files (media and config) over to that location and it worked

**Comment by amkrafie** [comment]
I ended up changing all the storage locations, and just copied my files (media and config) over to that location and it worked
