### ISSUE TITLE
[Bug]: /stat not accesible

### ISSUE THREAD

**Issue by tomhub** [blakeblackshear/frigate#9719]
### Describe the problem you are having

Here's an error I get based on dev-9e72f88, see the log

### Version

0.14 unstable (dev-9e72f88)

### Frigate config file

```yaml
na
```

### Relevant log output

```shell
frigate  | 2024-02-07 07:58:57.888975899  [2024-02-07 07:58:57] frigate.http                   ERROR   : Exception on /stats [GET]
frigate  | 2024-02-07 07:58:57.888979173  Traceback (most recent call last):
frigate  | 2024-02-07 07:58:57.888980556    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2190, in wsgi_app
frigate  | 2024-02-07 07:58:57.888981793      response = self.full_dispatch_request()
frigate  | 2024-02-07 07:58:57.888983046    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1486, in full_dispatch_request
frigate  | 2024-02-07 07:58:57.888984083      rv = self.handle_user_exception(e)
frigate  | 2024-02-07 07:58:57.888985384    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1484, in full_dispatch_request
frigate  | 2024-02-07 07:58:57.888986356      rv = self.dispatch_request()
frigate  | 2024-02-07 07:58:57.888987547    File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1469, in dispatch_request
frigate  | 2024-02-07 07:58:57.888988643      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
frigate  | 2024-02-07 07:58:57.888989718    File "/opt/frigate/frigate/http.py", line 1580, in stats
frigate  | 2024-02-07 07:58:57.888990645      return jsonify(stats)
frigate  | 2024-02-07 07:58:57.888991833    File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 170, in jsonify
frigate  | 2024-02-07 07:58:57.888992902      return current_app.json.response(*args, **kwargs)
frigate  | 2024-02-07 07:58:57.888994056    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 215, in response
frigate  | 2024-02-07 07:58:57.888995149      f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
frigate  | 2024-02-07 07:58:57.888996366    File "/usr/local/lib/python3.9/dist-packages/flask/json/provider.py", line 180, in dumps
frigate  | 2024-02-07 07:58:57.888997300      return json.dumps(obj, **kwargs)
frigate  | 2024-02-07 07:58:57.888998398    File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
frigate  | 2024-02-07 07:58:57.888999313      return cls(
frigate  | 2024-02-07 07:58:57.889000362    File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
frigate  | 2024-02-07 07:58:57.889001389      chunks = self.iterencode(o, _one_shot=True)
frigate  | 2024-02-07 07:58:57.889002471    File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
frigate  | 2024-02-07 07:58:57.889003416      return _iterencode(o, 0)
frigate  | 2024-02-07 07:58:57.889004479  TypeError: '<' not supported between instances of 'str' and 'PosixPath'
frigate  | 2024-02-07 07:58:57.926455359  [2024-02-07 07:58:57] frigate.record.maintainer      ERROR   : Error occurred when attempting to maintain recording cache
frigate  | 2024-02-07 07:58:57.926487043  [2024-02-07 07:58:57] frigate.record.maintainer      ERROR   : startswith first arg must be str or a tuple of str, not PosixPath
```

### FFprobe output from your camera

```shell
na
```

### Operating system

Other Linux

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

na

**Comment by tomhub** [comment]
seems to be resolved in dev-f6a4c2a
