### ISSUE TITLE
adding onvif camera causes config errors 

### ISSUE THREAD

**Issue by ardenking** [blakeblackshear/frigate#9783]
### Describe the problem you are having

Trying to add an onvif camera but when I do get the following error below 

Camera works fine with  rtsp in frigate and onvif in other apps 

can you please tell me what I'm doing wrong in config as going round in circles

Arden  

### Version

13

### Frigate config file

```yaml
mqtt:
  host: 192.168.1.193
  user: Arden
  password: xxx
  
  
cameras:

  
  Back:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.1.2:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
    motion:
      mask:
        - 0,720,517,720,535,667,0,657
  
  Front:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxxx@192.168.1.3:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
            - rtmp
    
    motion:
      mask:
        - 0,720,525,720,525,665,0,660
        
    zones:
      Front_Stones:
        coordinates: 1092,720,1035,591,961,588,888,596,823,591,734,591,627,588,468,571,143,522,0,547,8,720         
            
  Garage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.107:554/
          roles:
            - detect
            - rtmp
    
      

    
    motion:
      mask:
        - 961,39,1280,33,1280,0,944,0 
        
        
        
  Drive:
    ffmpeg:
      inputs:
        - path: rtsp://admin:admin@192.168.1.238:554/live/ch1
          roles:
            - detect
            - rtmp
            
    motion:
      mask:
        - 1280,0,1280,44,875,28,880,0        

  Garden:
    ffmpeg:
    onvif:
      host: 192.168.1.112
      port: 8899
      user: xxc
      password: xxxxx
```

### Relevant log output

```shell
024-02-10 19:29:22.853722453  *************************************************************
2024-02-10 19:29:22.853734885  *************************************************************
2024-02-10 19:29:22.853746409  ***    Your config file is not valid!                     ***
2024-02-10 19:29:22.853753952  ***    Please check the docs at                           ***
2024-02-10 19:29:22.853759679  ***    https://docs.frigate.video/configuration/index     ***
2024-02-10 19:29:22.853819743  *************************************************************
2024-02-10 19:29:22.853825051  *************************************************************
2024-02-10 19:29:22.853870239  ***    Config Validation Errors                           ***
2024-02-10 19:29:22.853875897  *************************************************************
2024-02-10 19:29:22.853880576  1 validation error for FrigateConfig
2024-02-10 19:29:22.853884767  cameras -> Garden
2024-02-10 19:29:22.853890005    'NoneType' object is not subscriptable (type=type_error)
2024-02-10 19:29:22.855624963  Traceback (most recent call last):
2024-02-10 19:29:22.855637255    File "/opt/frigate/frigate/app.py", line 645, in start
2024-02-10 19:29:22.855642004      self.init_config()
2024-02-10 19:29:22.855647382    File "/opt/frigate/frigate/app.py", line 112, in init_config
2024-02-10 19:29:22.855652620      user_config = FrigateConfig.parse_file(config_file)
2024-02-10 19:29:22.855658278    File "/opt/frigate/frigate/config.py", line 1333, in parse_file
2024-02-10 19:29:22.855663027      return cls.parse_obj(config)
2024-02-10 19:29:22.855668265    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2024-02-10 19:29:22.855673503    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2024-02-10 19:29:22.855680767  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2024-02-10 19:29:22.855687891  cameras -> Garden
2024-02-10 19:29:22.855693129    'NoneType' object is not subscriptable (type=type_error)
2024-02-10 19:29:22.855790769  
2024-02-10 19:29:22.855796915  *************************************************************
2024-02-10 19:29:22.855801664  ***    End Config Validation Errors                       ***
2024-02-10 19:29:22.855884917  ***************************************
```

### FFprobe output from your camera

```shell
not avail in ha cmd ?
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Network connection

Mixed

### Camera make and model

mixed

**Comment by hawkeye217** [comment]
You need to specify ffmpeg input parameters like your other cameras do. And then your `onvif:` section should be under that.

For example:

```
  Garden:
    ffmpeg:
      inputs:
        - path: rtsp://admin:xxxx@192.168.1.112:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    onvif:
      host: 192.168.1.112
      port: 8899
      user: xxc
      password: xxxxx
```

Have a look at [the configuration reference](https://docs.frigate.video/configuration/reference) for more.

**Comment by ardenking** [comment]
Thank you working now 
just need to figure out why left and right seems to be reversed

**Comment by hawkeye217** [comment]
Depending on how you have the camera mounted, left/right might be reversed.
