### ISSUE TITLE
[HW Accel Support]: Nvidia Decoder Error

### ISSUE THREAD

**Issue by hfbauman22** [blakeblackshear/frigate#9807]
### Describe the problem you are having

I'm heading towards trying to get a GPU detector set up, but was running into errors that I thought were related to not decoding the video on that device. In trying to just get hardware acceleration set up, I'm running into the errors shown. Not sure what to do about them. If I remove the hwaccel_args, I get output from the camera in the WebUI. Enabling the option gives the "No frames received, check error logs" message.

### Version

0.13.1

### Frigate config file

```yaml
mqtt:
  host: homeassistant.*****.ts.net
  port: 1883
  user: *******
  password: *******
  topic_prefix: frigate

objects:
  track:
    - person
    - bicycle
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe

  filters:
    person:
      min_area: 5000
      max_area: 100000

cameras:
  front-yard-cam: # <------ Name the camera
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://bauman-hpenvy.*******.ts.net:8556/front-yard-cam # <----- The stream you want to use for detection
          roles:
            - detect
            - record
    detect:
      width: 1920 # <---- update for your camera's resolution
      height: 1080 # <---- update for your camera's resolution
    record:
      enabled: True
    snapshots:
      enabled: True

logger:
  default: info
  logs:
    frigate.mqtt: debug
```

### docker-compose file or Docker CLI command

```yaml
version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "64mb" # update for your cameras based on calculation above
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - \\wsl$$\Ubuntu\etc\localtime:/etc/localtime:ro
      - \\wsl$$\Ubuntu\home\ringofowl\frigate\config:/config/
      - \\wsl$$\Ubuntu\home\ringofowl\frigate\clips:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      - YOLO_MODELS=yolov7-320
      #- USE_FP16=false
      #- FRIGATE_RTSP_PASSWORD: "password"
```

### Relevant log output

```shell
2024-02-11 15:52:08 2024-02-11 15:52:08.119554858  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f8148008980] moov atom not found
2024-02-11 15:52:08 2024-02-11 15:52:08.121116775  [ERROR:0@6.599] global cap.cpp:164 open VIDEOIO(CV_IMAGES): raised OpenCV exception:
2024-02-11 15:52:08 2024-02-11 15:52:08.121121075  
2024-02-11 15:52:08 2024-02-11 15:52:08.121123775  OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
2024-02-11 15:52:08 2024-02-11 15:52:08.121125575  
2024-02-11 15:52:08 2024-02-11 15:52:08.121127275  
2024-02-11 15:52:08 2024-02-11 15:52:08.172306714  [2024-02-11 15:52:08] frigate.record.maintainer      WARNING : Failed to probe corrupt segment /tmp/cache/front-yard-cam@20240211155205-0500.mp4
2024-02-11 15:52:08 2024-02-11 15:52:08.173661928  [2024-02-11 15:52:08] frigate.record.maintainer      WARNING : Discarding a corrupt recording segment: /tmp/cache/front-yard-cam@20240211155205-0500.mp4
2024-02-11 15:52:08 2024-02-11 15:52:08.262061159  [INFO] Starting go2rtc healthcheck service...
2024-02-11 15:52:23 2024-02-11 15:52:23.536020982  [2024-02-11 15:52:23] watchdog.front-yard-cam        ERROR   : Ffmpeg process crashed unexpectedly for front-yard-cam.
2024-02-11 15:52:23 2024-02-11 15:52:23.536026382  [2024-02-11 15:52:23] watchdog.front-yard-cam        ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
2024-02-11 15:52:23 2024-02-11 15:52:23.536029182  [2024-02-11 15:52:23] ffmpeg.front-yard-cam.detect   ERROR   : [h264 @ 0x560e7dc9ea40] Hardware is lacking required capabilities
2024-02-11 15:52:23 2024-02-11 15:52:23.536112483  [2024-02-11 15:52:23] ffmpeg.front-yard-cam.detect   ERROR   : [h264 @ 0x560e7dc9ea40] Failed setup for format cuda: hwaccel initialisation returned error.
2024-02-11 15:52:23 2024-02-11 15:52:23.536130983  [2024-02-11 15:52:23] ffmpeg.front-yard-cam.detect   ERROR   : Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
2024-02-11 15:52:23 2024-02-11 15:52:23.536133583  [2024-02-11 15:52:23] ffmpeg.front-yard-cam.detect   ERROR   : Error reinitializing filters!
2024-02-11 15:52:23 2024-02-11 15:52:23.536158383  [2024-02-11 15:52:23] ffmpeg.front-yard-cam.detect   ERROR   : Failed to inject frame into filter network: Function not implemented
2024-02-11 15:52:23 2024-02-11 15:52:23.536162883  [2024-02-11 15:52:23] ffmpeg.front-yard-cam.detect   ERROR   : Error while processing the decoded data for stream #0:0
2024-02-11 15:52:25 2024-02-11 15:52:25.217223303  [2024-02-11 15:52:25] frigate.video                  ERROR   : front-yard-cam: Unable to read frames from ffmpeg process.
```

### FFprobe output from your camera

```shell
# ffprobe rtsp://bauman-hpenvy.********.ts.net:8556/front-yard-cam
ffprobe version n5.1-2-g915ef932a3-20220731 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20220731
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[rtsp @ 0x55a802b22140] method SETUP failed: 461 Unsupported Transport
Input #0, rtsp, from 'rtsp://bauman-hpenvy.*******.ts.net:8556/front-yard-cam':
  Metadata:
    title           : No Name
  Duration: N/A, start: -0.521711, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1920x1080, 20 fps, 20 tbr, 90k tbn
#
```

### Operating system

Windows

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

Wyze Cam Pan v3

### Any other information that may be helpful

![image](https://github.com/blakeblackshear/frigate/assets/98182193/2eceb29f-14c7-43f2-9530-b7badf22ca7a)

**Comment by NickM-27** [comment]
Seems that the nvidia toolkit or driver isn't setup correctly on the host. Can you run nvidia-smi on the host and show the output

**Comment by hfbauman22** [comment]
![Screenshot_20240211_161745_AVNC.jpg](https://github.com/blakeblackshear/frigate/assets/98182193/0ded0e5c-388e-4bc9-9ac6-6b4d95fc0f73)

**Comment by hfbauman22** [comment]
@NickM-27 Just in case you didn't see the above.

**Comment by NickM-27** [comment]
So you are running frigate in a VM? it seems that maybe the VM doesn't have the GPU setup correctly. I don't know much about this type of setup especially with windows which isn't recommended

**Comment by hfbauman22** [comment]
I'm running frigate in Docker on Windows, using WSL2. The GPU seemed to at least be partially passed through to the container, since training TensorRT happens successfully. However, trying to run with the GPU detector or use the GPU for hardware decoding doesn't seem to work.

**Comment by NickM-27** [comment]
can you show a full copy of the logs?

**Comment by kdill00** [comment]
I think your card is too old/not enough vram to run tensorrt.   At the minimum you need to set USE_FP16=false to see if it will. The log is complaining about trying to use features the card does not have. Compute 5.0 with tensorrt is deprecated/potentially already removed. If the above doesnt work, try downgrading your cuda version to 12.2 and use a tiny model as there is no way it will run the full yolo models.

**Comment by kdill00** [comment]
Maybe verify the codec on that stream. Your card can’t decode h265 and may have problems with h264 if its the “high” profile.   Is it a wyze camera?  There may be something with the input stream that your card cant handle. especially if it works on cpu/software decode.  Also i dont know how ffmpeg is compiled with frigate. But you may need a custom ffmpeg install to build it for lower than compute 52. I think the newest nvidia ffmpeg requires compute 5.2. Or the second generation maxwell architecture. Your card is 5.0. Just some rambling thoughts

**Comment by gregewing** [comment]
I'm getting similar errors.  my platform is Ubuntu with docker and the tensorrt image.  I decode all the h264 video streams, at least so I can see them in the frigate UI, and recordings work, but I get no object detection whatsoever.  I can see the detection red boxes on the debug view for each camera, but it wont perform object detection.

I'll keep an eye on this and a couple similar issues, and not raise my own just yet.

**Comment by hfbauman22** [comment]
@NickM-27 see below. Sorry for the radio silence, I ran out of time to debug for the last couple weeks.

```
2024-02-28 14:11:37.021384004  [INFO] Preparing Frigate...
2024-02-28 14:11:37.107250649  [INFO] Starting Frigate...
2024-02-28 14:11:49.032369467  [2024-02-28 14:11:49] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-28 14:11:49.522208222  [2024-02-28 14:11:49] peewee_migrate.logs            INFO    : Starting migrations
2024-02-28 14:11:49.534177135  [2024-02-28 14:11:49] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-28 14:11:49.542348695  [2024-02-28 14:11:49] frigate.app                    INFO    : Recording process started: 232
2024-02-28 14:11:49.557394194  [2024-02-28 14:11:49] frigate.app                    INFO    : go2rtc process pid: 106
2024-02-28 14:11:49.619838101  [2024-02-28 14:11:49] frigate.app                    INFO    : Output process started: 243
2024-02-28 14:11:49.667633346  [2024-02-28 14:11:49] frigate.app                    INFO    : Camera processor started for front-yard-cam: 249
2024-02-28 14:11:49.735296039  [2024-02-28 14:11:49] frigate.app                    INFO    : Capture process started for front-yard-cam: 251
2024-02-28 14:11:50.541560322  [2024-02-28 14:11:49] detector.tensorrt              INFO    : Starting detection process: 242
2024-02-28 14:11:50.990446369  [2024-02-28 14:11:50] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 140 MiB
2024-02-28 14:11:52.005784996  [2024-02-28 14:11:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 264, GPU 515 (MiB)
2024-02-28 14:11:52.033312856  [2024-02-28 14:11:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +8, now: CPU 266, GPU 523 (MiB)
2024-02-28 14:11:52.044397087  [2024-02-28 14:11:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +139, now: CPU 0, GPU 139 (MiB)
2024-02-28 14:11:52.052709060  [2024-02-28 14:11:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 126, GPU 515 (MiB)
2024-02-28 14:11:52.097415817  [2024-02-28 14:11:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 126, GPU 523 (MiB)
2024-02-28 14:11:52.106356949  [2024-02-28 14:11:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +29, now: CPU 0, GPU 168 (MiB)
2024-02-28 14:11:52.335342245  Process camera_processor:front-yard-cam:
2024-02-28 14:11:52.335347045  Traceback (most recent call last):
2024-02-28 14:11:52.335349745    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-02-28 14:11:52.335385649      self.run()
2024-02-28 14:11:52.335391149    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-02-28 14:11:52.335393449      self._target(*self._args, **self._kwargs)
2024-02-28 14:11:52.335408551    File "/opt/frigate/frigate/video.py", line 436, in track_camera
2024-02-28 14:11:52.335411251      process_frames(
2024-02-28 14:11:52.335413451    File "/opt/frigate/frigate/video.py", line 689, in process_frames
2024-02-28 14:11:52.335415851      detect(
2024-02-28 14:11:52.335417952    File "/opt/frigate/frigate/video.py", line 474, in detect
2024-02-28 14:11:52.335420452      region_detections = object_detector.detect(tensor_input)
2024-02-28 14:11:52.335422552    File "/opt/frigate/frigate/object_detection.py", line 225, in detect
2024-02-28 14:11:52.335485958      (self.labels[int(d[0])], float(d[1]), (d[2], d[3], d[4], d[5]))
2024-02-28 14:11:52.336254429  KeyError: -14
2024-02-28 14:13:04.578015053  [2024-02-28 14:13:04] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front-yard-cam. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-02-28 14:13:14.575578484  [2024-02-28 14:13:14] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front-yard-cam. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-02-28 14:13:24.575644711  [2024-02-28 14:13:24] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front-yard-cam. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-02-28 14:13:34.577771040  [2024-02-28 14:13:34] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front-yard-cam. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-02-28 14:13:44.575550255  [2024-02-28 14:13:44] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front-yard-cam. Keeping the 6 most recent segments out of 7 and discarding the rest...
2024-02-28 14:13:54.577238659  [2024-02-28 14:13:54] frigate.record.maintainer      WARNING : Unable to keep up with recording segments in cache for front-yard-cam. Keeping the 6 most recent segments out of 7 and discarding the rest...
```

**Comment by hfbauman22** [comment]
@kdill00 I had similar thoughts. I've tried to compile ffmpeg from source using the cuda libraries, which seems to have completed. However, when I try to add to to the Docker container for use with Frigate, I get:
```3:20 ffmpeg: error while loading shared libraries: libavdevice.so.60: cannot open shared object file: No such file or directory```

I suspect that I'm not properly mounting all the directories that Frigate needs to access the custom installation, but I'm not sure what to mount where so that Frigate can find it.

**Comment by NickM-27** [comment]
Frigate expects statically linked ffmpeg builds

**Comment by hfbauman22** [comment]
> Frigate expects statically linked ffmpeg builds

Any tips on which flags I need to pass to the ./configure to statically link? Some Internet searching gives me really complicated suggestions, which I suspect are overkill.

**Comment by spattinson** [comment]
> Frigate expects statically linked ffmpeg builds

Static ffmpeg is not mentioned https://docs.frigate.video/configuration/advanced/#custom-ffmpeg-build
I am using a self built dynamically linked ffmpeg on rockchip platforms without issue.
I have the following in my docker run:

`-v /home/scott/ffbuild:/usr/lib/btbn-ffmpeg:ro \
-e LD_LIBRARY_PATH=/usr/lib/btbn-ffmpeg/lib \`

Am I missing anything? I noticed @MarcA711 also went to lengths to generate a static ffmpeg for rockchip. My ffmpeg is cut down to suit my needs, the default config has a lot of build options that I think nobody would use?

**Comment by spattinson** [comment]
> > Frigate expects statically linked ffmpeg builds
> 
> Any tips on which flags I need to pass to the ./configure to statically link? Some Internet searching gives me really complicated suggestions, which I suspect are overkill.

Compiling ffmpeg statically is not trivial, many of the libraries do not have static versions by default, so they will all need to be build from source after modifying the build scripts to generate them. The default ffmpeg config in  frigate has numerous options included, many I cant see anyone needing, eg X11 frame grab. This adds a lot to the burden of building it. I gave up trying to do it and built a cut down ffmpeg dynamically linked instead. See my other comment.

**Comment by MarcA711** [comment]
When using dynamically linked FFmpeg, you have to make sure that you provide all necessary dependencies (.so files etc) to the container and that the system correctly finds and loads them.

I wanted to stay close to the default frigate and therefore chose to use the same configuration (+ Rockchip specific options), so the rockchip image is compatible to the default image. Since the resulting static FFmpeg file is just 80mb in size, I didn't think that long about further optimizations.

**Comment by MarcA711** [comment]
@hfbauman22 
> Any tips on which flags I need to pass to the ./configure to statically link? Some Internet searching gives me really complicated suggestions, which I suspect are overkill.

You can use this repo as a starting point: https://github.com/BtbN/FFmpeg-Builds

It builds all dependencies statically.

You can also have a look at my fork where I added some dependencies and built a static custom FFmpeg: https://github.com/MarcA711/Rockchip-FFmpeg-Builds

Here are the changes I made: https://github.com/BtbN/FFmpeg-Builds/compare/master...MarcA711:Rockchip-FFmpeg-Builds:master
