### ISSUE TITLE
[Support]: Frigate+ upload SSL Error

### ISSUE THREAD

**Issue by raphaelcouzet** [blakeblackshear/frigate#9831]
### Describe the problem you are having

Unable to upload snapshots to Frigate+. Logs return following error:

ERROR   : HTTPSConnectionPool(host='api.frigate.video', port=443): Max retries exceeded with url: /v1/auth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))

Frigate is setup in an LXC on proxmox with HA in a VM on the same host.
Everything else works as intended and has been for over a year without errors

My network set up is very simple. Using nabucasa to expose HA and therefore Frigate (through Frigate Proxy add-on)

If this is purely related to my network setup and not Frigate, I would be grateful for any pointers on where I can start learning,

Many thanks! 

### Version

0.13.1-34fb1c2

### Frigate config file

```yaml
# Reference configuration https://docs.frigate.video/configuration/

############################### MQTT ###############################
mqtt:
  host: 192.168.xxx.xxx
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: user
  password: password
  stats_interval: 60
############################### GLOBAL CONFIG ###############################
ui:
  # Optional: Set the default live mode for cameras in the UI (default: shown below)
  live_mode: webrtc

detectors:
  coral:
    type: edgetpu
    device: usb
    
rtmp: 
    enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

# Include all cameras by default in Birdseye view
birdseye:
  enabled: true
  mode: continuous
  #continuous: All cameras are always included
  #motion: Cameras that have detected motion within the last 30 seconds are included
  #objects: Cameras that have tracked an active object within the last 30 seconds are included

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  width: 640
  height: 480
  fps: 5

# Optional: Object configuration
# NOTE: Can be overridden at the camera level  
objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - cat
    - dog
    - mouse
    - bird
  filters:
    person:
      threshold: 0.75
    car:
      threshold: 0.75
    motorcycle:
      threshold: 0.8
    bicycle:
      threshold: 0.8
    cat:
      threshold: 0.8
    dog:
      threshold: 0.8
    mouse:
      threshold: 0.8
    bird:
      threshold: 0.8
    
# Optional: Record configuration
# NOTE: Can be overridden at the camera level
record:
  enabled: true
  retain:
    days: 7
    mode: motion

  events:
    retain:
      default: 14
      mode: active_objects

# Optional: Configuration for the jpg snapshots written to the clips directory for each event
# NOTE: Can be overridden at the camera level
snapshots:
    enabled: true
    bounding_box: true

# Optional: Restream configuration
# Uses https://github.com/AlexxIT/go2rtc (v1.2.0)       
go2rtc:
  streams:
    Front:
      - rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/
    East:
      - rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/
    Back:
      - rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/
    West:
      - rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/
    Garage:
      - rtsp://x:x@192.168.xx.xx/stream1
    #   - "ffmpeg:tapo_test#audio=aac"
  webrtc:
    candidates:
      - 192.168.xx.xx:8555
      - stun:8555

############################### INDIVIDUAL CAMERAS ###############################
cameras:
############################### FRONT ###############################
  Front:
    ui:
      order: 1
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/102/ 
          roles:
            - detect
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/ 
          roles:
            - record
            # - rtmp
    motion:
      improve_contrast: true
    record:
      events:
        required_zones:
          - Driveway_and_garden
          - Council_Strip
    snapshots:
      required_zones:
          - Driveway_and_garden
          - Council_Strip
    zones:
      Driveway_and_garden:
        coordinates: 575,225,640,148,412,94,86,293,181,480,337,480
      Council_strip:
        coordinates: 0,330,0,274,427,47,455,66
      Street:
        coordinates: 512,0,304,0,0,132,0,272
    

############################### SIDE EAST ###############################
  East:
    ui:
      order: 4
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/102/ 
          roles:
            - detect
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/ 
          roles:
            - record
            # - rtmp
    motion: 
      mask: 640,0,640,251,640,229,433,300,372,0
      improve_contrast: true
############################### BACK GARDEN ###############################
  Back:
    ui:
      order: 2
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/102/ 
          roles:
            - detect
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/ 
          roles:
            - record
            # - rtmp
    motion:
      improve_contrast: true

############################### SIDE WEST ###############################
  West:
    ui:
      order: 3
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/102/ 
          roles:
            - detect
        - path: rtsp://x:x@192.168.xx.xx:554/Streaming/Channels/101/ 
          roles:
            - record
            # - rtmp
    motion:
      improve_contrast: true
      mask: 282,0,0,0,0,480,223,480

############################### GARAGE ###############################
  Garage:
    ui:
      order: 5
    ffmpeg:
      inputs:
        - path: rtsp://x:x@192.168.xx.xx/stream2
          #input_args: preset-rtsp-restream
          roles:
            - detect
        # - path: rtsp://x:x@192.168.xx.xx/stream1
        #   #input_args: preset-rtsp-restream
        #   roles:
            # - rtmp
    record:
      enabled: false
    motion:
      improve_contrast: true
```

### Relevant log output

```shell
2024-02-12 23:52:29.821863600  [INFO] Preparing Frigate...
2024-02-12 23:52:29.910708259  [INFO] Starting Frigate...
2024-02-12 23:52:31.869917848  [2024-02-12 23:52:31] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-12 23:52:31.939949744  [2024-02-12 23:52:31] peewee_migrate.logs            INFO    : Starting migrations
2024-02-12 23:52:31.945695436  [2024-02-12 23:52:31] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-12 23:52:31.951283532  [2024-02-12 23:52:31] frigate.app                    INFO    : Recording process started: 285
2024-02-12 23:52:31.954393096  [2024-02-12 23:52:31] frigate.app                    INFO    : go2rtc process pid: 92
2024-02-12 23:52:32.011061778  [2024-02-12 23:52:32] frigate.app                    INFO    : Output process started: 296
2024-02-12 23:52:32.027526731  [2024-02-12 23:52:32] detector.coral                 INFO    : Starting detection process: 295
2024-02-12 23:52:32.027901930  [2024-02-12 23:52:32] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2024-02-12 23:52:32.092778917  [2024-02-12 23:52:32] frigate.app                    INFO    : Camera processor started for Front: 306
2024-02-12 23:52:32.113818075  [2024-02-12 23:52:32] frigate.app                    INFO    : Camera processor started for East: 307
2024-02-12 23:52:32.136828122  [2024-02-12 23:52:32] frigate.app                    INFO    : Camera processor started for Back: 311
2024-02-12 23:52:32.179275163  [2024-02-12 23:52:32] frigate.app                    INFO    : Camera processor started for West: 313
2024-02-12 23:52:32.199011984  [2024-02-12 23:52:32] frigate.app                    INFO    : Camera processor started for Garage: 315
2024-02-12 23:52:32.223677374  [2024-02-12 23:52:32] frigate.app                    INFO    : Capture process started for Front: 321
2024-02-12 23:52:32.236798685  [2024-02-12 23:52:32] frigate.app                    INFO    : Capture process started for East: 324
2024-02-12 23:52:32.246359604  [2024-02-12 23:52:32] frigate.app                    INFO    : Capture process started for Back: 327
2024-02-12 23:52:32.267397021  [2024-02-12 23:52:32] frigate.app                    INFO    : Capture process started for West: 332
2024-02-12 23:52:32.296962006  [2024-02-12 23:52:32] frigate.app                    INFO    : Capture process started for Garage: 341
2024-02-12 23:52:34.716557011  [2024-02-12 23:52:34] frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found
2024-02-12 23:55:15.965196627  [2024-02-12 23:55:15] frigate.http                   ERROR   : HTTPSConnectionPool(host='api.frigate.video', port=443): Max retries exceeded with url: /v1/auth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
2024-02-12 23:55:15.965204041  Traceback (most recent call last):
2024-02-12 23:55:15.965205977    File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 467, in _make_request
2024-02-12 23:55:15.965207856      self._validate_conn(conn)
2024-02-12 23:55:15.965209458    File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
2024-02-12 23:55:15.965217136      conn.connect()
2024-02-12 23:55:15.965218656    File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 653, in connect
2024-02-12 23:55:15.965231678      sock_and_verified = _ssl_wrap_socket_and_match_hostname(
2024-02-12 23:55:15.965233241    File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
2024-02-12 23:55:15.965234772      ssl_sock = ssl_wrap_socket(
2024-02-12 23:55:15.965236208    File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
2024-02-12 23:55:15.965245117      ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
2024-02-12 23:55:15.965246573    File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
2024-02-12 23:55:15.965247989      return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2024-02-12 23:55:15.965249235    File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
2024-02-12 23:55:15.965250422      return self.sslsocket_class._create(
2024-02-12 23:55:15.965259972    File "/usr/lib/python3.9/ssl.py", line 1040, in _create
2024-02-12 23:55:15.965261155      self.do_handshake()
2024-02-12 23:55:15.965262427    File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
2024-02-12 23:55:15.965263593      self._sslobj.do_handshake()
2024-02-12 23:55:15.965265155  ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2024-02-12 23:55:15.965266202  
2024-02-12 23:55:15.965267479  During handling of the above exception, another exception occurred:
2024-02-12 23:55:15.965279083  
2024-02-12 23:55:15.965280330  Traceback (most recent call last):
2024-02-12 23:55:15.965281741    File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 793, in urlopen
2024-02-12 23:55:15.965282852      response = self._make_request(
2024-02-12 23:55:15.965284258    File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 491, in _make_request
2024-02-12 23:55:15.965285449      raise new_e
2024-02-12 23:55:15.965299387  urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
2024-02-12 23:55:15.965300396  
2024-02-12 23:55:15.965301571  The above exception was the direct cause of the following exception:
2024-02-12 23:55:15.965302509  
2024-02-12 23:55:15.965303703  Traceback (most recent call last):
2024-02-12 23:55:15.965304942    File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 486, in send
2024-02-12 23:55:15.965305959      resp = conn.urlopen(
2024-02-12 23:55:15.965307276    File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 847, in urlopen
2024-02-12 23:55:15.965308299      retries = retries.increment(
2024-02-12 23:55:15.965335788    File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 515, in increment
2024-02-12 23:55:15.965337159      raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-02-12 23:55:15.965339247  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.frigate.video', port=443): Max retries exceeded with url: /v1/auth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
2024-02-12 23:55:15.965340338  
2024-02-12 23:55:15.965341557  During handling of the above exception, another exception occurred:
2024-02-12 23:55:15.965342582  
2024-02-12 23:55:15.965343723  Traceback (most recent call last):
2024-02-12 23:55:15.965344938    File "/opt/frigate/frigate/http.py", line 257, in send_to_plus
2024-02-12 23:55:15.965346191      plus_id = current_app.plus_api.upload_image(image, event.camera)
2024-02-12 23:55:15.965347407    File "/opt/frigate/frigate/plus.py", line 101, in upload_image
2024-02-12 23:55:15.965348550      r = self._get("image/signed_urls")
2024-02-12 23:55:15.965364504    File "/opt/frigate/frigate/plus.py", line 80, in _get
2024-02-12 23:55:15.965365834      f"{self.host}/v1/{path}", headers=self._get_authorization_header()
2024-02-12 23:55:15.965367071    File "/opt/frigate/frigate/plus.py", line 75, in _get_authorization_header
2024-02-12 23:55:15.965368212      self._refresh_token_if_needed()
2024-02-12 23:55:15.965369417    File "/opt/frigate/frigate/plus.py", line 69, in _refresh_token_if_needed
2024-02-12 23:55:15.965370741      r = requests.get(f"{self.host}/v1/auth/token", auth=(parts[0], parts[1]))
2024-02-12 23:55:15.965372016    File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 73, in get
2024-02-12 23:55:15.965373400      return request("get", url, params=params, **kwargs)
2024-02-12 23:55:15.965374709    File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
2024-02-12 23:55:15.965375938      return session.request(method=method, url=url, **kwargs)
2024-02-12 23:55:15.965377243    File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 589, in request
2024-02-12 23:55:15.965378389      resp = self.send(prep, **send_kwargs)
2024-02-12 23:55:15.965379738    File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 703, in send
2024-02-12 23:55:15.965380839      r = adapter.send(request, **kwargs)
2024-02-12 23:55:15.965382121    File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 517, in send
2024-02-12 23:55:15.965383299      raise SSLError(e, request=request)
2024-02-12 23:55:15.965385255  requests.exceptions.SSLError: HTTPSConnectionPool(host='api.frigate.video', port=443): Max retries exceeded with url: /v1/auth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
```

### FFprobe output from your camera

```shell
no issues with cameras
```

### Frigate stats

```json
Docker compose / portainer stack

##########################FRIGATE
services:
  frigate:
    container_name: frigate
    privileged: true
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: always
    devices:
     - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/frigate/:/config/
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_RTSP_PASSWORD: "xxxxxx"
      PLUS_API_KEY: xxxxxx
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

### Network connection

Wired

### Camera make and model

hikvision, tapo

**Comment by blakeblackshear** [comment]
I am definitely not using self signed certificates. This seems to indicate that you may have a DNS resolution issue. It's as if the dns request is resolving to something other than the frigate+ api.

**Comment by raphaelcouzet** [comment]
I've changed DNS servers from Cloudflare (1.1.1.1) to Google (8.8.8.8 and 4.4.4.4) to my ISP assigned DNS servers and keep getting this error without being able to upload to Frigate+

I'm generally able to figure things out but networking is like voodoo magic to me. 
Any other suggestions of where else I can poke around, or any docs to help me narrow this down?

**Comment by blakeblackshear** [comment]
Try running wget or something on that endpoint inside and outside of the container.

**Comment by raphaelcouzet** [comment]
I can run wget from the docker "host" (in this case a Proxmox LXC)
Tested using:
**root@docker ~# wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip**
Results in the file downloading

But cannot run  wget from inside the frigate container
Tested by getting shell access to container with :
**docker run -it --entrypoint /bin/bash ghcr.io/blakeblackshear/frigate:stable**
and again running: 
**root@docker ~# wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip**
This time with error:
--2024-02-14 12:29:39--  http://speedtest.wdc01.softlayer.com/downloads/test500.zip
Resolving speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)... 169.54.48.218, 2607:f0d0:3006:154::3
Connecting to speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)|169.54.48.218|:80... connected.
HTTP request sent, awaiting response... 404 File not found
2024-02-14 12:29:39 ERROR 404: File not found.

It says file not found but the IP 169.54.48.218 is correct. Not sure what this indicates

**Comment by blakeblackshear** [comment]
Just to clarify, the IP address that is resolved inside the container matches the IP address from the host?

**Comment by raphaelcouzet** [comment]
Yes same IP address
Here is the output of wget from Host

root@docker ~# wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip
--2024-02-14 12:53:03--  http://speedtest.wdc01.softlayer.com/downloads/test500.zip
Resolving speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)... 169.54.48.218, 2607:f0d0:3006:154::3
Connecting to speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)|169.54.48.218|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 524288000 (500M) [application/zip]
Saving to: '/dev/null'

/dev/null                               100%[===============================================================================>] 500.00M  12.4MB/s    in 43s     

2024-02-14 12:53:47 (11.6 MB/s) - '/dev/null' saved [524288000/524288000]

**Comment by raphaelcouzet** [comment]
Looks like they are hitting different servers


From host: 
root@docker ~# wget --server-response -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip
--2024-02-14 13:44:42--  http://speedtest.wdc01.softlayer.com/downloads/test500.zip
Resolving speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)... 169.54.48.218, 2607:f0d0:3006:154::3
Connecting to speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)|169.54.48.218|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Wed, 14 Feb 2024 13:44:43 GMT
  **Server: Apache/2.4.6 (CentOS) PHP/5.4.16**
  Last-Modified: Sun, 30 Dec 2012 04:47:38 GMT
  ETag: "1f400000-4d20a98912e80"
  Accept-Ranges: bytes
  Content-Length: 524288000
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Content-Type: application/zip
Length: 524288000 (500M) [application/zip]
Saving to: '/dev/null'

/dev/null                               100%[===============================================================================>] 500.00M  9.45MB/s    in 57s     

2024-02-14 13:45:40 (8.74 MB/s) - '/dev/null' saved [524288000/524288000]




From container:
root@df511d5c5b2f:/opt/frigate# wget --server-response -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip
--2024-02-14 13:46:43--  http://speedtest.wdc01.softlayer.com/downloads/test500.zip
Resolving speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)... 169.54.48.218, 2607:f0d0:3006:154::3
Connecting to speedtest.wdc01.softlayer.com (speedtest.wdc01.softlayer.com)|169.54.48.218|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.0 404 File not found
  **_Server: SimpleHTTP/0.6 Python/3.9.2_**
  Date: Wed, 14 Feb 2024 13:46:43 GMT
  Connection: close
  Content-Type: text/html;charset=utf-8
  Content-Length: 469
2024-02-14 13:46:43 ERROR 404: File not found.

**Comment by raphaelcouzet** [comment]
The results in previous post seem to suggest that the docker container is not able to access internet through the LXC hence the SSL error.
I'm able to access all other parts of frigate so I'm a bit confused why it can't publish to frigate+ api.
Is it an outbound vs inbound thing?
Is there a firewall I need to configure either in Proxmox or in docker?

Thanks in advance for any pointers

**Comment by blakeblackshear** [comment]
This indicates that there is something intercepting your outbound network traffic from within the container. It's odd that it's a python simple http server. It's probably something you configured at some point, but this is what a man in the middle attack would look like. It's exactly the kind of thing using TLS/SSL is designed to protect against.

You could try running a route trace to see where the request is being sent.

**Comment by raphaelcouzet** [comment]
Couldn't figure it out so ended up nuking everything and starting from a brand new LXC.
Was pretty quick since I backup al my config files
And now i can upload to Frigate+ !!
Thansk for the hlpe along the way. I will close this issue.

**Comment by nglessner** [comment]
I know this is marked as completed - but I am coming across this error when I'm explicitly disallowing internet access from my camera's vlan.  Which... makes total sense!
