### ISSUE TITLE
[Config Support]: Shows V12.1 in GUI an not 13

### ISSUE THREAD

**Issue by FigJam23** [blakeblackshear/frigate#9834]
### Describe the problem you are having

Thought I was running version 13 but GUI says 12.1 yet my docker image is for the latest stable like image: ghcr.io/blakeblackshear/frigate:stable-tensorrt

### Version

13

### Frigate config file

```yaml
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt  #ghcr.io/blakeblackshear/frigate:0.12.1 #ghcr.io/blakeblackshear/frigate:stable # blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
 
              capabilities: [gpu]
 # deploy:    # <------------- Add this section
    shm_size: "550mb" # update for your cameras based on calculation
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/mike/frigate/frigate.yml:/config/config.yml
      - /mnt/hubfiles:/media/frigate
      - /home/mike/frigate:/db
      - /home/mike/frigate/trt-models:/trt-models
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554"
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
```

### Relevant log output

```shell
2024-02-13 17:20:50.306992803  [INFO] Starting Frigate...
2024-02-13 17:20:51.593629987  [2024-02-13 17:20:51] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2024-02-13 17:20:51.666023969  [2024-02-13 17:20:51] peewee_migrate                 INFO    : Starting migrations
2024-02-13 17:20:51.691194436  [2024-02-13 17:20:51] peewee_migrate                 INFO    : There is nothing to migrate
2024-02-13 17:20:51.707446657  [2024-02-13 17:20:51] frigate.app                    INFO    : Output process started: 439
2024-02-13 17:20:51.715509611  [2024-02-13 17:20:51] frigate.app                    INFO    : Camera processor started for driveway_cam: 442
2024-02-13 17:20:51.717636291  [2024-02-13 17:20:51] detector.tensorrt              INFO    : Starting detection process: 437
2024-02-13 17:20:51.796407085  [2024-02-13 17:20:51] frigate.app                    INFO    : Camera processor started for front_entry: 446
2024-02-13 17:20:51.796503969  [2024-02-13 17:20:51] frigate.app                    INFO    : Camera processor started for front_deck: 448
2024-02-13 17:20:51.796582608  [2024-02-13 17:20:51] frigate.app                    INFO    : Camera processor started for back_shed: 449
2024-02-13 17:20:51.796602602  [2024-02-13 17:20:51] frigate.app                    INFO    : Camera processor started for sand_pit: 451
2024-02-13 17:20:51.796662999  [2024-02-13 17:20:51] frigate.app                    INFO    : Camera processor started for 360cam: 452
2024-02-13 17:20:51.796686416  [2024-02-13 17:20:51] frigate.app                    INFO    : Capture process started for driveway_cam: 454
2024-02-13 17:20:51.796714315  [2024-02-13 17:20:51] frigate.app                    INFO    : Capture process started for front_entry: 457
2024-02-13 17:20:51.796745423  [2024-02-13 17:20:51] frigate.app                    INFO    : Capture process started for front_deck: 462
2024-02-13 17:20:51.796818155  [2024-02-13 17:20:51] frigate.app                    INFO    : Capture process started for back_shed: 468
2024-02-13 17:20:51.796820020  [2024-02-13 17:20:51] frigate.app                    INFO    : Capture process started for sand_pit: 474
2024-02-13 17:20:51.796856558  [2024-02-13 17:20:51] frigate.app                    INFO    : Capture process started for 360cam: 479
2024-02-13 17:20:52.076626903  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init CUDA: CPU +536, GPU +0, now: CPU 661, GPU 342 (MiB)
2024-02-13 17:20:52.117235593  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 15 MiB
2024-02-13 17:20:52.148961839  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 711, GPU 368 (MiB)
2024-02-13 17:20:52.152472284  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 713, GPU 378 (MiB)
2024-02-13 17:20:52.156948201  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +15, now: CPU 0, GPU 15 (MiB)
2024-02-13 17:20:52.157015229  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 697, GPU 370 (MiB)
2024-02-13 17:20:52.157039610  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 697, GPU 378 (MiB)
2024-02-13 17:20:52.157116248  [2024-02-13 17:20:52] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +7, now: CPU 0, GPU 22 (MiB)
```

### Frigate stats

```json
{"return_code":0,"stderr":"","stdout":"vainfo:VA-APIversion:1.17(libva2.10.0)nvainfo:Driverversion:InteliHDdriverforIntel(R)GenGraphics-23.1.1()nvainfo:SupportedprofileandentrypointsnVAProfileNone:tVAEntrypointVideoProcnVAProfileNone:tVAEntrypointStatsnVAProfileMPEG2Simple:tVAEntrypointVLDnVAProfileMPEG2Simple:tVAEntrypointEncSlicenVAProfileMPEG2Main:tVAEntrypointVLDnVAProfileMPEG2Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointVLDnVAProfileH264Main:tVAEntrypointEncSlicenVAProfileH264Main:tVAEntrypointFEInVAProfileH264Main:tVAEntrypointEncSliceLPnVAProfileH264High:tVAEntrypointVLDnVAProfileH264High:tVAEntrypointEncSlicenVAProfileH264High:tVAEntrypointFEInVAProfileH264High:tVAEntrypointEncSliceLPnVAProfileVC1Simple:tVAEntrypointVLDnVAProfileVC1Main:tVAEntrypointVLDnVAProfileVC1Advanced:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointVLDnVAProfileJPEGBaseline:tVAEntrypointEncPicturenVAProfileH264ConstrainedBaseline:tVAEntrypointVLDnVAProfileH264ConstrainedBaseline:tVAEntrypointEncSlicenVAProfileH264ConstrainedBaseline:tVAEntrypointFEInVAProfileH264ConstrainedBaseline:tVAEntrypointEncSliceLPnVAProfileVP8Version0_3:tVAEntrypointVLDnVAProfileVP8Version0_3:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointVLDnVAProfileHEVCMain:tVAEntrypointEncSlicenVAProfileHEVCMain:tVAEntrypointFEInVAProfileHEVCMain10:tVAEntrypointVLDnVAProfileHEVCMain10:tVAEntrypointEncSlicenVAProfileVP9Profile0:tVAEntrypointVLDnVAProfileVP9Profile2:tVAEntrypointVLD"}
```

### Operating system

Debian

### Install method

Docker Compose

### Coral version

USB

### Any other information that may be helpful

why am I not on verion13 when my image is already the stable ghcr.io/blakeblackshear/frigate:stable-tensorrt
GUI says I'm still version 12.1.
is my config wrong for tensorrt version 13 or is it not supported in 13 for GPU usage?

**Comment by blakeblackshear** [comment]
Make sure you read the release notes. I can see at a glance that your config mapping needs to be updated. https://github.com/blakeblackshear/frigate/releases/tag/v0.13.0

**Comment by FigJam23** [comment]
Ah right, thanks for lettme know.

**Comment by FigJam23** [comment]
ok after waiting it loaded up. 13 now as i can see the export button. ive got some errors in log 
```
2024-02-14 18:47:42.055029838  [INFO] Preparing Frigate...
2024-02-14 18:47:42.069530821  [INFO] Starting Frigate...
2024-02-14 18:47:42.948802624  [2024-02-14 18:47:42] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-14 18:47:43.059488915  [2024-02-14 18:47:43] peewee_migrate.logs            INFO    : Starting migrations
2024-02-14 18:47:43.068077418  [2024-02-14 18:47:43] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-14 18:47:43.068116982  [2024-02-14 18:47:43] frigate.app                    INFO    : Recording process started: 455
2024-02-14 18:47:43.069753854  [2024-02-14 18:47:43] frigate.app                    INFO    : go2rtc process pid: 98
2024-02-14 18:47:43.089136479  [2024-02-14 18:47:43] detector.tensorrt              INFO    : Starting detection process: 464
2024-02-14 18:47:43.095636210  [2024-02-14 18:47:43] frigate.app                    INFO    : Output process started: 466
2024-02-14 18:47:43.126010610  [2024-02-14 18:47:43] frigate.app                    INFO    : Camera processor started for driveway_cam: 482
2024-02-14 18:47:43.134622257  [2024-02-14 18:47:43] frigate.app                    INFO    : Camera processor started for front_entry: 491
2024-02-14 18:47:43.142652321  [2024-02-14 18:47:43] frigate.app                    INFO    : Camera processor started for front_deck: 492
2024-02-14 18:47:43.152746857  [2024-02-14 18:47:43] frigate.app                    INFO    : Camera processor started for back_shed: 497
2024-02-14 18:47:43.167608394  [2024-02-14 18:47:43] frigate.app                    INFO    : Camera processor started for sand_pit: 507
2024-02-14 18:47:43.175777724  [2024-02-14 18:47:43] frigate.app                    INFO    : Camera processor started for 360cam: 510
2024-02-14 18:47:43.184145833  [2024-02-14 18:47:43] frigate.app                    INFO    : Capture process started for driveway_cam: 512
2024-02-14 18:47:43.194899540  [2024-02-14 18:47:43] frigate.app                    INFO    : Capture process started for front_entry: 517
2024-02-14 18:47:43.201388145  [2024-02-14 18:47:43] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 15 MiB
2024-02-14 18:47:43.206335709  [2024-02-14 18:47:43] frigate.app                    INFO    : Capture process started for front_deck: 521
2024-02-14 18:47:43.221328756  [2024-02-14 18:47:43] frigate.app                    INFO    : Capture process started for back_shed: 527
2024-02-14 18:47:43.233792762  [2024-02-14 18:47:43] frigate.app                    INFO    : Capture process started for sand_pit: 533
2024-02-14 18:47:43.247322765  [2024-02-14 18:47:43] frigate.app                    INFO    : Capture process started for 360cam: 538
2024-02-14 18:47:43.324031287  [2024-02-14 18:47:43] frigate.detectors.plugins.tensorrt ERROR   : 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 232, Serialized Engine Version: 213)
2024-02-14 18:47:43.335672454  Process detector:tensorrt:
2024-02-14 18:47:43.335871639  [2024-02-14 18:47:43] frigate.detectors.plugins.tensorrt ERROR   : 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
2024-02-14 18:47:43.336192683  Traceback (most recent call last):
2024-02-14 18:47:43.336194446    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-02-14 18:47:43.336195402      self.run()
2024-02-14 18:47:43.336196451    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-02-14 18:47:43.336197360      self._target(*self._args, **self._kwargs)
2024-02-14 18:47:43.336198992    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-02-14 18:47:43.336201593      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-02-14 18:47:43.336214004    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-02-14 18:47:43.336215062      self.detect_api = create_detector(detector_config)
2024-02-14 18:47:43.336216008    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-02-14 18:47:43.336229060      return api(detector_config)
2024-02-14 18:47:43.336230147    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 221, in __init__
2024-02-14 18:47:43.336231108      self.input_shape = self._get_input_shape()
2024-02-14 18:47:43.336232060    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 93, in _get_input_shape
2024-02-14 18:47:43.336239777      binding = self.engine[0]
2024-02-14 18:47:43.336240709  TypeError: 'NoneType' object is not subscriptable
2024-02-14 18:47:43.336265443  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f2563083160>
2024-02-14 18:47:43.336266492  Traceback (most recent call last):
2024-02-14 18:47:43.336267449    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__
2024-02-14 18:47:43.336292914      if self.outputs is not None:
2024-02-14 18:47:43.336294099  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2024-02-14 18:47:43.469314736  [2024-02-14 18:47:43] frigate.app                    WARNING : The current SHM size of 550.0MB is too small, recommend increasing it to at least 566.3MB.
```

i will increase this 550.0MB is too small, recommend increasing it to at least 566.3MB
but im unsure about other errors

**Comment by FigJam23** [comment]
looks like its updating all the old camera clips and footage maybe being impatient how long should I wait until restarting docker?
is there away to tell frigate has finished rebuilding the database

**Comment by FigJam23** [comment]
ok, I can't get parts this error now could someone try to point me in the correct direction?

model:
  path: trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416

```
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt #ghcr.io/blakeblackshear/frigate:0.13.0-tensorrt #ghcr.io/blakeblackshear/frigate:stable-tensorrt  #ghcr.io/blakeblackshear/frigate:0.12.1 #ghcr.io/blakeblackshear/frigate:stable # blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
 
              capabilities: [gpu]
 # deploy:    # <------------- Add this section
    shm_size: "1000mb" # update for your cameras based on calculation
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/mike/frigate/:/config
      - /mnt/hubfiles:/media/frigate:rw
    #  - /home/mike/frigate:/db
      - /home/mike/frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000      
      
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554"
    environment:
     # - FRIGATE_RTSP_PASSWORD: "1234"  #modify to whatever if using rtsp  
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

      - PLUS_API_KEY=f9be1e69-c600-4c0b-915b-489bb82cc4d2:c2fea8c97fc3784e6a7491338c21040b14ff9587
 ```
```
2024-02-14 19:23:28.867963808  [INFO] Preparing Frigate...
2024-02-14 19:23:28.883370091  [INFO] Starting Frigate...
2024-02-14 19:23:29.892125929  [2024-02-14 19:23:29] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-14 19:23:29.979661484  [2024-02-14 19:23:29] peewee_migrate.logs            INFO    : Starting migrations
2024-02-14 19:23:29.982756594  [2024-02-14 19:23:29] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-14 19:23:29.989213165  [2024-02-14 19:23:29] frigate.app                    INFO    : Recording process started: 456
2024-02-14 19:23:29.990784511  [2024-02-14 19:23:29] frigate.app                    INFO    : go2rtc process pid: 98
2024-02-14 19:23:30.015064899  [2024-02-14 19:23:30] frigate.app                    INFO    : Output process started: 468
2024-02-14 19:23:30.023115923  [2024-02-14 19:23:30] detector.tensorrt              INFO    : Starting detection process: 466
2024-02-14 19:23:30.092462146  Process detector:tensorrt:
2024-02-14 19:23:30.092949693  Traceback (most recent call last):
2024-02-14 19:23:30.093012611    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-02-14 19:23:30.093014001      self.run()
2024-02-14 19:23:30.093061944    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-02-14 19:23:30.093063251      self._target(*self._args, **self._kwargs)
2024-02-14 19:23:30.093081056    File "/opt/frigate/frigate/object_detection.py", line 102, in run_detector
2024-02-14 19:23:30.093082173      object_detector = LocalObjectDetector(detector_config=detector_config)
2024-02-14 19:23:30.093096096    File "/opt/frigate/frigate/object_detection.py", line 53, in __init__
2024-02-14 19:23:30.093097129      self.detect_api = create_detector(detector_config)
2024-02-14 19:23:30.093143749    File "/opt/frigate/frigate/detectors/__init__.py", line 18, in create_detector
2024-02-14 19:23:30.093144905      return api(detector_config)
2024-02-14 19:23:30.093160095    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 220, in __init__
2024-02-14 19:23:30.093161100      self.engine = self._load_engine(detector_config.model.path)
2024-02-14 19:23:30.093172985    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 88, in _load_engine
2024-02-14 19:23:30.093174011      with open(model_path, "rb") as f, trt.Runtime(self.trt_logger) as runtime:
2024-02-14 19:23:30.093199127  FileNotFoundError: [Errno 2] No such file or directory: 'trt-models/yolov7-tiny-416.trt'
2024-02-14 19:23:30.093262805  Exception ignored in: <function TensorRtDetector.__del__ at 0x7f32447383a0>
2024-02-14 19:23:30.093291673  Traceback (most recent call last):
2024-02-14 19:23:30.093315045    File "/opt/frigate/frigate/detectors/plugins/tensorrt.py", line 239, in __del__
2024-02-14 19:23:30.093448881      if self.outputs is not None:
2024-02-14 19:23:30.093490377  AttributeError: 'TensorRtDetector' object has no attribute 'outputs'
2024-02-14 19:23:30.094976190  [2024-02-14 19:23:30] frigate.app                    INFO    : Camera processor started for driveway_cam: 476
2024-02-14 19:23:30.105362276  [2024-02-14 19:23:30] frigate.app                    INFO    : Camera processor started for front_entry: 477
2024-02-14 19:23:30.105623282  [2024-02-14 19:23:30] frigate.app                    INFO    : Camera processor started for front_deck: 478
2024-02-14 19:23:30.107023823  [2024-02-14 19:23:30] frigate.app                    INFO    : Camera processor started for back_shed: 483
2024-02-14 19:23:30.107027606  [2024-02-14 19:23:30] frigate.app                    INFO    : Camera processor started for sand_pit: 485
2024-02-14 19:23:30.107032833  [2024-02-14 19:23:30] frigate.app                    INFO    : Camera processor started for 360cam: 487
2024-02-14 19:23:30.115488028  [2024-02-14 19:23:30] frigate.app                    INFO    : Capture process started for driveway_cam: 492
2024-02-14 19:23:30.115493331  [2024-02-14 19:23:30] frigate.app                    INFO    : Capture process started for front_entry: 495
2024-02-14 19:23:30.115874027  [2024-02-14 19:23:30] frigate.app                    INFO    : Capture process started for front_deck: 501
2024-02-14 19:23:30.124408907  [2024-02-14 19:23:30] frigate.app                    INFO    : Capture process started for back_shed: 505
2024-02-14 19:23:30.134431675  [2024-02-14 19:23:30] frigate.app                    INFO    : Capture process started for sand_pit: 511
2024-02-14 19:23:30.143170598  [2024-02-14 19:23:30] frigate.app                    INFO    : Capture process started for 360cam: 516

```

**Comment by FigJam23** [comment]
I've temperaly disable the models and using my  Coral and working good no errors yet, seem like everything is good using coral, but I want to use my gpu as I believe it has better detection and I don't care about power.
So how should I be updating my model files in config as it looks like this is my issue

**Comment by FigJam23** [comment]
![Screenshot_20240214_200019_Chrome](https://github.com/blakeblackshear/frigate/assets/29391962/d096e593-c7cb-43d9-ab3c-9096ffc67b98)

Looks like the coral and gpu working together in this image,  with out model library config. I didn't think it worked running both the coral and nvida?

**Comment by NickM-27** [comment]
you are using the coral for object detection and the gpu for decoding which is recommended

**Comment by FigJam23** [comment]
I'd prefer to use my gpu for object detection like I hade  on 12.before moving to 13 and  using  tensor models library as it has worked better for my setup. The only info I can find after hours going through docs and issues forum is that the yolo libraries don't work on 13 and you need to do some changes or change dir in config I'm unsure.

**Comment by NickM-27** [comment]
The release notes covered this. You just need to follow the docs and change your config so a new model is generated for you https://docs.frigate.video/configuration/object_detectors#nvidia-tensorrt-detector

**Comment by FigJam23** [comment]
OK so I would update  my cofig
From : trt-models/yolov7-tiny-416.trt
To: /config/model_cache/yolov7-tiny-416.trt
If I'm correct it will automatically generate the 
yolov7-tiny-416.trt model into the /config/model_cache dir is that correct or do I need to add the yolo file to that dir?

**Comment by NickM-27** [comment]
you'll need to change the env var, the model that is made by default is

```
model:
  path: /config/model_cache/tensorrt/yolov7-320.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 320
  height: 320
```

**Comment by FigJam23** [comment]
Thank you for your help, really appreciated. Just to be 100 percent  sure i do this and understand correctly if I change the 
/yolov7-320.trt. to another model that's avaliable frigate will automatically download the model I specified and put it into the config/model_cache/tensorrt/ 
Folder/DIR

**Comment by NickM-27** [comment]
You have to change the config and the environment variable

**Comment by FigJam23** [comment]
so Ive done this 
```
 environment:
     # - FRIGATE_RTSP_PASSWORD: "1234"  #modify to whatever if using rtsp  
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - YOLO_MODELS=yolov7x-640
```
and 
```
model:
  path: /config/model_cache/tensorrt/yolov7x-640.trt     #trt-models/yolov7-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416
```

but im getting this in error logs omg

```
frigate$ docker-compose logs
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service trt-model-prepare: starting
frigate  | s6-rc: info: service log-prepare: starting
frigate  | Generating the following TRT Models: yolov7x-640
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | Downloading yolo weights
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-02-15 16:11:37.667092006  [INFO] Preparing new go2rtc config...
frigate  | 2024-02-15 16:11:37.879292168  [INFO] Starting go2rtc...
frigate  | 2024-02-15 16:11:37.931854683  16:11:37.931 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-02-15 16:11:37.932302635  16:11:37.932 INF [api] listen addr=:1984
frigate  | 2024-02-15 16:11:37.932376863  16:11:37.932 INF [rtsp] listen addr=:8554
frigate  | 2024-02-15 16:11:37.932486068  16:11:37.932 INF [webrtc] listen addr=:8555
frigate  | 
frigate  | Creating yolov7x-640.cfg and yolov7x-640.weights
frigate  | 
frigate  | Done.
frigate  | 2024-02-15 16:11:47.665477908  [INFO] Starting go2rtc healthcheck service...
frigate  | 
frigate  | Generating yolov7x-640.trt. This may take a few minutes.
frigate  | 
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:147: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
frigate  |   builder.max_batch_size = MAX_BATCH_SIZE
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:149: DeprecationWarning: Use set_memory_pool_limit instead.
frigate  |   config.max_workspace_size = 1 << 30
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:172: DeprecationWarning: Use build_serialized_network instead.
frigate  |   engine = builder.build_engine(network, config)


```

**Comment by FigJam23** [comment]
now because I keep getting this error I reverted back to my working config and now frigate won't start and still get this error.
so now everything is broken as Frigate doesn't seem to be able to pull the default model file and even if I add YOLO_MODELS=""
to the end it just hangs i don't know what to do now omg 
```
docker-compose logs
frigate  | s6-rc: info: service s6rc-fdholder: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner: starting
frigate  | s6-rc: info: service s6rc-oneshot-runner successfully started
frigate  | s6-rc: info: service fix-attrs: starting
frigate  | s6-rc: info: service s6rc-fdholder successfully started
frigate  | s6-rc: info: service fix-attrs successfully started
frigate  | s6-rc: info: service legacy-cont-init: starting
frigate  | s6-rc: info: service legacy-cont-init successfully started
frigate  | s6-rc: info: service trt-model-prepare: starting
frigate  | s6-rc: info: service log-prepare: starting
frigate  | Generating the following TRT Models: yolov7-320
frigate  | Downloading yolo weights
frigate  | s6-rc: info: service log-prepare successfully started
frigate  | s6-rc: info: service nginx-log: starting
frigate  | s6-rc: info: service go2rtc-log: starting
frigate  | s6-rc: info: service frigate-log: starting
frigate  | s6-rc: info: service nginx-log successfully started
frigate  | s6-rc: info: service go2rtc-log successfully started
frigate  | s6-rc: info: service go2rtc: starting
frigate  | s6-rc: info: service frigate-log successfully started
frigate  | s6-rc: info: service go2rtc successfully started
frigate  | s6-rc: info: service go2rtc-healthcheck: starting
frigate  | s6-rc: info: service go2rtc-healthcheck successfully started
frigate  | 2024-02-15 17:43:37.725544850  [INFO] Preparing new go2rtc config...
frigate  | 2024-02-15 17:43:37.929703130  [INFO] Starting go2rtc...
frigate  | 2024-02-15 17:43:37.981624034  17:43:37.981 INF go2rtc version 1.8.4 linux/amd64
frigate  | 2024-02-15 17:43:37.982020482  17:43:37.981 INF [api] listen addr=:1984
frigate  | 2024-02-15 17:43:37.982022143  17:43:37.981 INF [rtsp] listen addr=:8554
frigate  | 2024-02-15 17:43:37.982160709  17:43:37.982 INF [webrtc] listen addr=:8555
frigate  | 
frigate  | Creating yolov7-320.cfg and yolov7-320.weights
frigate  | 
frigate  | Done.
frigate  | 2024-02-15 17:43:47.720917256  [INFO] Starting go2rtc healthcheck service...
frigate  | 
frigate  | Generating yolov7-320.trt. This may take a few minutes.
frigate  | 
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:147: DeprecationWarning: Use network created with NetworkDefinitionCreationFlag::EXPLICIT_BATCH flag instead.
frigate  |   builder.max_batch_size = MAX_BATCH_SIZE
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:149: DeprecationWarning: Use set_memory_pool_limit instead.
frigate  |   config.max_workspace_size = 1 << 30
frigate  | /usr/local/src/tensorrt_demos/yolo/onnx_to_tensorrt.py:172: DeprecationWarning: Use build_serialized_network instead.
frigate  |   engine = builder.build_engine(network, config)
mike@mike-System-Product-Name:~/frigate$ 


```
```
version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt #ghcr.io/blakeblackshear/frigate:0.13.0-tensorrt #ghcr.io/blakeblackshear/frigate:stable-tensorrt  #ghcr.io/blakeblackshear/frigate:0.12.1 #ghcr.io/blakeblackshear/frigate:stable # blakeblackshear/frigate:stable
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # this is only needed when using multiple GPUs
 
              capabilities: [gpu]
 # deploy:    # <------------- Add this section
    shm_size: "1000mb" # update for your cameras based on calculation
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/mike/frigate/:/config
      - /mnt/hubfiles:/media/frigate:rw
    #  - /home/mike/frigate:/db
     # - /home/mike/frigate/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000      
      
    ports:
      - "5000:5000"
      - "1935:1935"
      - "8554:8554"
    environment:
     # - FRIGATE_RTSP_PASSWORD: "1234"  #modify to whatever if using rtsp  
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
     # - YOLO_MODELS=""
```
```
detectors:
#  tensorrt:
  #  type: tensorrt
  #  device: 0 # This is the default, select the first GPU
  coral1:
    type: edgetpu
    device: usb
#model:
 # path: /config/model_cache/tensorrt/yolov7-320.trt    #trt-models/yolov7-tiny-416.trt
 # input_tensor: nchw
 # input_pixel_format: rgb
 # width: 320
  #height: 320```

**Comment by FigJam23** [comment]
No mater what if I manually set the yolo version under the  environment . it says it's downloading in logs and says done then errors . But no yolo  file is populated in the models dir.  the only file in the Dir isbthe default one frigate downloads if nothing is specific under environment options.

**Comment by FigJam23** [comment]
Randomly started generating other Yolo files very strange. Spent hours and hours to get these models to generate. I guess maybe the yolo file server may have been done

**Comment by NickM-27** [comment]
Going to close this as the original issue is solved. Feel free to create a new issue if something else comes up
