### ISSUE TITLE
[HW Accel Support]: RKNN error reported during startup

### ISSUE THREAD

**Issue by liwei19920307** [blakeblackshear/frigate#9840]
### Describe the problem you are having

RKNN error

I compiled armbian for ha green (rk3566 cpu) and enabled npu to test frigate, but encountered an error during startup

### Version

stable-rk

### Frigate config file

```yaml
mqtt:
  enabled: false

detectors:
  rknn:
    type: rknn
    core_mask: 0

model:
  path: /config/model_cache/yolov8n-320x320-rk3566.rknn
  width: 320
  height: 320
  input_pixel_format: bgr
  input_tensor: nhwc

cameras:
  camera:
    ffmpeg:
      inputs:
        - path: rtsp://xxx
          hwaccel_args: preset-rk-h264
          roles:
            - detect
    objects:
      track:
        - person
    detect:
      width: 640
      height: 360
      fps: 10
      enabled: true
```

### docker-compose file or Docker CLI command

```yaml
frigate:
    image: ghcr.io/blakeblackshear/frigate:stable-rk
    container_name: frigate
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/frigate/conf:/config
      - /opt/frigate/data:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1gb
    environment:
      - TZ=Asia/Shanghai
      - FRIGATE_RTSP_PASSWORD=frigate
    network_mode: host
    restart: always
    privileged: true
    shm_size: 512mb
```

### Relevant log output

```shell
2024-02-13 20:50:00.753782103  I RKNN: [20:50:00.753] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
2024-02-13 20:50:00.753909854  I RKNN: [20:50:00.753] RKNN Driver Information: version: 0.9.2
2024-02-13 20:50:00.755526866  I RKNN: [20:50:00.755] RKNN Model Information: version: 6, toolkit version: 1.6.0+81f21f4d(compiler version: 1.6.0 (585b3edcf@2023-12-11T07:56:14)), target: RKNPU lite, target platform: rk3566, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
2024-02-13 20:50:00.755548449  W RKNN: [20:50:00.755] RKNN Model version: 1.6.0 not match with rknn runtime version: 1.5.2
2024-02-13 20:50:02.256494329  Process detector:rknn:
2024-02-13 20:50:02.276772600  Traceback (most recent call last):
2024-02-13 20:50:02.276789808    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-02-13 20:50:02.276792434      self.run()
2024-02-13 20:50:02.276795642    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-02-13 20:50:02.276798267      self._target(*self._args, **self._kwargs)
2024-02-13 20:50:02.276801475    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2024-02-13 20:50:02.276814600      detections = object_detector.detect_raw(input_frame)
2024-02-13 20:50:02.276881684    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2024-02-13 20:50:02.276886643      return self.detect_api.detect_raw(tensor_input=tensor_input)
2024-02-13 20:50:02.276890143    File "/opt/frigate/frigate/detectors/plugins/rknn.py", line 205, in detect_raw
2024-02-13 20:50:02.276949643      return self.postprocess(output[0])
2024-02-13 20:50:02.276954310    File "/opt/frigate/frigate/detectors/plugins/rknn.py", line 154, in postprocess
2024-02-13 20:50:02.276958101      results = np.transpose(results[0, :, :, 0])  # array shape (2100, 84)
2024-02-13 20:50:02.276961310  IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
2024-02-13 20:50:21.632808948  [2024-02-13 20:50:21] frigate.watchdog               INFO    : Detection appears to be stuck. Restarting detection process...
2024-02-13 20:50:21.667513157  [2024-02-13 20:50:21] detector.rknn                  INFO    : Starting detection process: 414
2024-02-13 20:50:22.370137105  I RKNN: [20:50:22.369] RKNN Runtime Information: librknnrt version: 1.5.2 (c6b7b351a@2023-08-23T15:28:22)
2024-02-13 20:50:22.370594442  I RKNN: [20:50:22.370] RKNN Driver Information: version: 0.9.2
2024-02-13 20:50:22.371269655  I RKNN: [20:50:22.371] RKNN Model Information: version: 6, toolkit version: 1.6.0+81f21f4d(compiler version: 1.6.0 (585b3edcf@2023-12-11T07:56:14)), target: RKNPU lite, target platform: rk3566, framework name: ONNX, framework layout: NCHW, model inference type: static_shape
2024-02-13 20:50:22.371281322  W RKNN: [20:50:22.371] RKNN Model version: 1.6.0 not match with rknn runtime version: 1.5.2
2024-02-13 20:50:22.509468153  Process detector:rknn:
2024-02-13 20:50:22.512580259  Traceback (most recent call last):
2024-02-13 20:50:22.513047804    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2024-02-13 20:50:22.513060637      self.run()
2024-02-13 20:50:22.513163013    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2024-02-13 20:50:22.513167971      self._target(*self._args, **self._kwargs)
2024-02-13 20:50:22.513275597    File "/opt/frigate/frigate/object_detection.py", line 125, in run_detector
2024-02-13 20:50:22.513280556      detections = object_detector.detect_raw(input_frame)
2024-02-13 20:50:22.513354931    File "/opt/frigate/frigate/object_detection.py", line 75, in detect_raw
2024-02-13 20:50:22.513359890      return self.detect_api.detect_raw(tensor_input=tensor_input)
2024-02-13 20:50:22.513430473    File "/opt/frigate/frigate/detectors/plugins/rknn.py", line 205, in detect_raw
2024-02-13 20:50:22.513434848      return self.postprocess(output[0])
2024-02-13 20:50:22.513552974    File "/opt/frigate/frigate/detectors/plugins/rknn.py", line 154, in postprocess
2024-02-13 20:50:22.513558224      results = np.transpose(results[0, :, :, 0])  # array shape (2100, 84)
2024-02-13 20:50:22.513698517  IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed
2024-02-13 20:50:31.653725181  [2024-02-13 20:50:31] frigate.watchdog               INFO    : Detection appears to have stopped. Exiting Frigate...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
```

### FFprobe output from your camera

```shell
unable to start
```

### Operating system

Other Linux

### Install method

Docker Compose

### Network connection

Wired

### Camera make and model

hikvision

**Comment by liwei19920307** [comment]
It seems that the Docker image version does not match the model, which caused me to modify it to the 1.5.2 model and it will work

**Comment by MarcA711** [comment]
Hey @liwei19920307 
Yes, the frigate docker image uses rknn_toolkit_lite2 V1.5.2 currently.

I work on updating the toolkit to v1.6.0 and hope to get it merged in the next couple of days.
