### ISSUE TITLE
[Config Support]: Config formatting issue

### ISSUE THREAD

**Issue by fetalp** [blakeblackshear/frigate#9854]
### Describe the problem you are having

I am not sure what extra field not permitted, I am at a lost and could use anyone's help. 

Thank you in advanced

### Version

8.1.4

### Frigate config file

```yaml
##########################################################
## Driveway
##########################################################

cameras:
  #simple camera example
  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass!@192.168.1.63:554/h264Preview_01_main
          roles:
            - record
            - detect 
    detect: 
      height: 720
      fps: 5
 
objects: 
  track:
    - person
    - dog
    - cat  
  filters:
    person:
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 0
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 100000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.5
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7

record:
      enabled: True
      retain:
        days: 1
        mode: motion
      events:
#        max_seconds: 240 Deprecated in 0.11
        pre_capture: 5
        post_capture: 5
        retain:
          default: 2
          mode: active_objects
        objects:
          - person
          - car
          - cat
          - dog

snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False
      retain:
        default: 7

#########################################################
## Living Room
#########################################################

living_room_cam:
    ffmpeg:
      inputs:
        - path: rtsp://user:pass@192.168.1.211/live
          roles:
            - detect
            - record

    objects:
      track:
        - person
      filters:
        person:

    detect:
      width: 1920
      height: 1080
      fps: 10
      enabled: True

    record:
      enabled: True
      retain:
        days: 1
        # mode: active_objects
      events:
#        max_seconds: 240
        pre_capture: 5
        post_capture: 5
        retain:
          default: 2
          mode: active_objects
        objects:
          - person

#########################################################
## Global
#########################################################

mqtt:
  host: homeassistant.local
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: mqtt_user
  password: hidden
  stats_interval: 60
  

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p

detectors:
  coral:
    type: edgetpu
    device: usb

database:
  path: /db/frigate.db
```

### Relevant log output

```shell
2024-02-14 12:30:57.545557783  *************************************************************
2024-02-14 12:30:57.545560686  ***    Your config file is not valid!                     ***
2024-02-14 12:30:57.545562576  ***    Please check the docs at                           ***
2024-02-14 12:30:57.545563821  ***    https://docs.frigate.video/configuration/index     ***
2024-02-14 12:30:57.545580943  *************************************************************
2024-02-14 12:30:57.545582175  *************************************************************
2024-02-14 12:30:57.545583709  ***    Config Validation Errors                           ***
2024-02-14 12:30:57.545584905  *************************************************************
2024-02-14 12:30:57.546170821  1 validation error for FrigateConfig
2024-02-14 12:30:57.546172770  living_room_cam
2024-02-14 12:30:57.546173986    extra fields not permitted (type=value_error.extra)
2024-02-14 12:30:57.546452201  Traceback (most recent call last):
2024-02-14 12:30:57.546454086    File "/opt/frigate/frigate/app.py", line 645, in start
2024-02-14 12:30:57.546455152      self.init_config()
2024-02-14 12:30:57.546456309    File "/opt/frigate/frigate/app.py", line 112, in init_config
2024-02-14 12:30:57.546457387      user_config = FrigateConfig.parse_file(config_file)
2024-02-14 12:30:57.546458522    File "/opt/frigate/frigate/config.py", line 1333, in parse_file
2024-02-14 12:30:57.546459549      return cls.parse_obj(config)
2024-02-14 12:30:57.546460677    File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
2024-02-14 12:30:57.546461797    File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
2024-02-14 12:30:57.546462934  pydantic.error_wrappers.ValidationError: 1 validation error for FrigateConfig
2024-02-14 12:30:57.546465074  living_room_cam
2024-02-14 12:30:57.546466173    extra fields not permitted (type=value_error.extra)
2024-02-14 12:30:57.546494448  
2024-02-14 12:30:57.546495753  *************************************************************
2024-02-14 12:30:57.546496859  ***    End Config Validation Errors                       ***
2024-02-14 12:30:57.546510863  *************************************************************
2024-02-14 12:30:58.725971655  [INFO] Service Frigate exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
```

### Operating system

Proxmox

### Install method

Docker Compose

### Coral version

USB

**Comment by NickM-27** [comment]
your config is not formatted correctly, the indentation is wrong. I would suggest using the getting started guide https://docs.frigate.video/guides/getting_started#configuring-frigate

**Comment by fetalp** [comment]
Ok, I will go over those again. I can get it to work with 1 cam but as soon as I add the second a myriad of errors but I'll figure it out. Thanks

**Comment by supermarkert** [comment]
It would seem that all of your cameras need to be defined under the "cameras:" section, not just your Driveway.  
You have a head section called "living_room_cam:" which doesn't belong there.  Move it up with your driveway cam, at the same indent level.

**Comment by fetalp** [comment]
I thought it was under the cameras:
I tried one and 2 indentations with different errors coming up. I’ll take a more in depth look. Thanks for the heads up been at this for two days now. I think I’ve fried my brain or something

**Comment by supermarkert** [comment]
Look at your 2 headings labeled "Driveway" and "Living Room". You've defined your cameras differently. Regardless, you can't separate them like that anyway. All your cameras need to be under one heading, "cameras:". See the master config example.

**Comment by bob454522** [comment]
also you should use the Built in config editor in the frigate Web Gui as it will show you where the errors are located.  (you may have to upgrade to a newer version of frigate to get this  though).

However I'm assuming you currently cannot start frigate to even get into the Web GUI, in which case I'm sure there are online YAML configuration validators (pasting your config into one of these should show where the error can formatting only lies.)  An offline alternative would be to use something like notepad plus plus and set the language to YAML (This may highlight or make visible where any layout or indication errors exist).

(In terms of online web submitted validators - you May want to consider the safety of pasting in passwords or any publicly accessible data into an online YAML validator - thus If you're paranoid / or publicly accessible -  X out any credentials before pasting)
