### ISSUE TITLE
[Config Support]: Low resolution video to birdseye and high CPU usage/disk usage?

### ISSUE THREAD

**Issue by futuredj** [blakeblackshear/frigate#9864]
### Describe the problem you are having

Since upgrading to v13, I've been experiencing poor performance to the point it makes other applications on the system unusable. This could be due to high disk usage as I was seeing 800mb write constantly from frigate but that might be normal. For now, I think its high CPU as I looked through the issues forum and found the pined thread: https://github.com/blakeblackshear/frigate/issues/7828 

I already had detect resolution setup for each camera at 1080p 25fps. Of course, this is very high resolution, so I've setup substreams from each camera and lowered the resolution, which has helped CPU usage, but it is still causing poor performance, which was not apparent in v12.

Regardless, this was an improvement and made the system more usable, but now all live streams and birdseye are at low resolution. Recording is working fine at high resolution, but I have birdseye streaming to a display and it has noticeably dropped in quality.

I looked through the docs and found the live -> stream_name option. I added that, but it hasn't made a difference. 

nvidia-smi is showing all streams and tensorrt processes, just like before on v12, yet it _feels_ like the CPU is doing a lot of work all of a sudden... Top is showing a lot of processes for frigate.output, frigate.process, frigate.detection and a ton of ffmpeg processes that I had never noticed before.

I haven't made many changes to the configuration since upgrading. All that has changed is: regenerating tensorrt models; adding substreams at lower resolution for detection; and adding the live stream name option. Maybe I missed something I needed to update or change when updating to v13?

Any help is appreciated. Loving v13's features so far!

### Version

0.13.1-34FB1C2

### Frigate config file

```yaml
mqtt:
  host: mqtt.server.com

go2rtc:
  streams:
    lilly:
      - rtsp://####@192.168.40.105:554/stream1
      - "ffmpeg:lilly#audio=aac#hardware=cuda"
    lilly_sub:
      - rtsp://####@192.168.40.105:554/stream2
      - "ffmpeg:lilly_sub#audio=aac#hardware=cuda"
    boys:
      - rtsp://####@192.168.40.247:554/stream1
      - "ffmpeg:boys#audio=aac#hardware=cuda"
    boys_sub:
      - rtsp://####@192.168.40.247:554/stream2
      - "ffmpeg:boys_sub#audio=aac#hardware=cuda"
    garden:
      - rtsp://####@192.168.40.40:554/stream1
      - "ffmpeg:garden#audio=aac#hardware=cuda"
    garden_sub:
      - rtsp://####@192.168.40.40:554/stream2
      - "ffmpeg:garden_sub#audio=aac#hardware=cuda"
    driveway:
      - rtsp://####@192.168.40.39:554/stream1
      - "ffmpeg:driveway#audio=aac#hardware=cuda"
    driveway_sub:
      - rtsp://####@192.168.40.39:554/stream2
      - "ffmpeg:driveway_sub#audio=aac#hardware=cuda"
    kitchen:
      - rtsp://####@192.168.40.226:554/stream1
      - "ffmpeg:kitchen#audio=aac#hardware=cuda"
    kitchen_sub:
      - rtsp://####@192.168.40.226:554/stream2
      - "ffmpeg:kitchen_sub#audio=aac#hardware=cuda"
    frontdoor:
      - rtsp://####@192.168.40.98:554/h264Preview_01_main
      - "ffmpeg:frontdoor#audio=opus#hardware=cuda"
    frontdoor_sub:
      - rtsp://127.0.0.1:8554/frontdoor
      - "ffmpeg:frontdoor_sub#audio=aac#hardware=cuda"
    rotate: ffmpeg:rtsp://127.0.0.1:8554/birdseye#video=h264#rotate=90#hardware=cuda
    rotateaudio:
      - rtsp://127.0.0.1:8554/rotate
      - rtsp://127.0.0.1:8554/boys#audio=copy
      - rtsp://127.0.0.1:8554/lilly#audio=copy
      - "ffmpeg:rotateaudio#audio=aac#hardware=cuda"

objects:
  track:
    - person
    - car
    - bird
    - motorcycle
    - cat
    - dog

cameras:
  Kitchen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    live:
      stream_name: kitchen
  Lilly:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/lilly
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/lilly_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      mode: continuous
    detect:
      width: 640
      height: 360
      fps: 5
    live:
      stream_name: lilly
  Boys:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/boys
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/boys_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    birdseye:
      mode: continuous
    detect:
      width: 640
      height: 360
      fps: 25
    live:
      stream_name: boys
  Garden:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/garden
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garden_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    live:
      stream_name: garden
  Driveway:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/driveway
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/driveway_sub
          roles:
            - detect
    detect:
      width: 640
      height: 360
      fps: 5
    live:
      stream_name: driveway
  Frontdoor:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
        rtmp: -c:v copy -c:a aac -f flv
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/frontdoor_sub
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 29
    live:
      stream_name: frontdoor

record:
  enabled: True
  retain:
    days: 14
    mode: motion
  events:
    retain:
      default: 14
      mode: motion

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
    detect: -f rawvideo -pix_fmt yuv420p
    rtmp: -c:v copy -c:a aac -f flv
  
birdseye:
  enabled: True
  restream: True
  width: 1080
  height: 1920
  quality: 4
  mode: objects

#detectors:
#  cpu:
#    type: cpu
#    num_threads: 10

detectors:
  tensorrt:
    type: tensorrt

model:
  path: /config/model_cache/tensorrt/yolov4-tiny-416.trt
  input_tensor: nchw
  input_pixel_format: rgb
  width: 416
  height: 416






#s
```

### Relevant log output

```shell
2024-02-15 12:08:21.600444238  [INFO] Preparing Frigate...
2024-02-15 12:08:21.615586187  [INFO] Starting Frigate...
2024-02-15 12:08:23.297253175  [2024-02-15 12:08:23] frigate.app                    INFO    : Starting Frigate (0.13.1-34fb1c2)
2024-02-15 12:08:23.463261266  [2024-02-15 12:08:23] peewee_migrate.logs            INFO    : Starting migrations
2024-02-15 12:08:23.469093497  [2024-02-15 12:08:23] peewee_migrate.logs            INFO    : There is nothing to migrate
2024-02-15 12:08:23.476200446  [2024-02-15 12:08:23] frigate.app                    INFO    : Recording process started: 893
2024-02-15 12:08:23.479554832  [2024-02-15 12:08:23] frigate.app                    INFO    : go2rtc process pid: 109
2024-02-15 12:08:23.512178346  [2024-02-15 12:08:23] frigate.app                    INFO    : Output process started: 904
2024-02-15 12:08:23.519290266  [2024-02-15 12:08:23] detector.tensorrt              INFO    : Starting detection process: 902
2024-02-15 12:08:23.597066049  [2024-02-15 12:08:23] frigate.app                    INFO    : Camera processor started for Kitchen: 917
2024-02-15 12:08:23.598524074  [2024-02-15 12:08:23] frigate.app                    INFO    : Camera processor started for Lilly: 919
2024-02-15 12:08:23.606281598  [2024-02-15 12:08:23] frigate.app                    INFO    : Camera processor started for Boys: 923
2024-02-15 12:08:23.614599936  [2024-02-15 12:08:23] frigate.app                    INFO    : Camera processor started for Garden: 938
2024-02-15 12:08:23.619750402  [2024-02-15 12:08:23] frigate.detectors.plugins.tensorrt INFO    : Loaded engine size: 39 MiB
2024-02-15 12:08:23.623461521  [2024-02-15 12:08:23] frigate.app                    INFO    : Camera processor started for Driveway: 940
2024-02-15 12:08:23.632971514  [2024-02-15 12:08:23] frigate.app                    INFO    : Camera processor started for Frontdoor: 953
2024-02-15 12:08:23.641310797  [2024-02-15 12:08:23] frigate.app                    INFO    : Capture process started for Kitchen: 960
2024-02-15 12:08:23.651357055  [2024-02-15 12:08:23] frigate.app                    INFO    : Capture process started for Lilly: 964
2024-02-15 12:08:23.660571642  [2024-02-15 12:08:23] frigate.app                    INFO    : Capture process started for Boys: 968
2024-02-15 12:08:23.667794972  [2024-02-15 12:08:23] frigate.app                    INFO    : Capture process started for Garden: 970
2024-02-15 12:08:23.677921448  [2024-02-15 12:08:23] frigate.app                    INFO    : Capture process started for Driveway: 980
2024-02-15 12:08:23.685689076  [2024-02-15 12:08:23] frigate.app                    INFO    : Capture process started for Frontdoor: 985
2024-02-15 12:08:23.776029150  [2024-02-15 12:08:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +6, GPU +8, now: CPU 156, GPU 85 (MiB)
2024-02-15 12:08:23.781849975  [2024-02-15 12:08:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 158, GPU 95 (MiB)
2024-02-15 12:08:23.793389689  [2024-02-15 12:08:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +40, now: CPU 0, GPU 40 (MiB)
2024-02-15 12:08:23.794246248  [2024-02-15 12:08:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 118, GPU 87 (MiB)
2024-02-15 12:08:23.794395500  [2024-02-15 12:08:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 118, GPU 95 (MiB)
2024-02-15 12:08:23.794593994  [2024-02-15 12:08:23] frigate.detectors.plugins.tensorrt INFO    : [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +13, now: CPU 0, GPU 53 (MiB)
2024-02-15 12:08:26.041781259  [2024-02-15 12:08:26] frigate.comms.mqtt             ERROR   : Unable to publish to Frontdoor/all: client is not connected
2024-02-15 12:08:26.041917282  [2024-02-15 12:08:26] frigate.comms.mqtt             ERROR   : Unable to publish to Frontdoor/motion: client is not connected
2024-02-15 12:08:26.302724262  [2024-02-15 12:08:26] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/all: client is not connected
2024-02-15 12:08:26.302817284  [2024-02-15 12:08:26] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/motion: client is not connected
2024-02-15 12:08:27.048015212  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Driveway/all: client is not connected
2024-02-15 12:08:27.048090447  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Driveway/motion: client is not connected
2024-02-15 12:08:27.564519318  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:27.580631781  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Frontdoor/car/snapshot: client is not connected
2024-02-15 12:08:27.580730476  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Frontdoor/car: client is not connected
2024-02-15 12:08:27.580822198  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Frontdoor/all: client is not connected
2024-02-15 12:08:27.582005931  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:27.586371175  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:27.599525061  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Driveway/car/snapshot: client is not connected
2024-02-15 12:08:27.599661120  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Driveway/car: client is not connected
2024-02-15 12:08:27.599870115  [2024-02-15 12:08:27] frigate.comms.mqtt             ERROR   : Unable to publish to Driveway/all: client is not connected
2024-02-15 12:08:32.100160743  [2024-02-15 12:08:32] frigate.comms.mqtt             ERROR   : Unable to publish to Lilly/all: client is not connected
2024-02-15 12:08:32.100270270  [2024-02-15 12:08:32] frigate.comms.mqtt             ERROR   : Unable to publish to Lilly/motion: client is not connected
2024-02-15 12:08:32.107735432  [2024-02-15 12:08:32] frigate.comms.mqtt             ERROR   : Unable to publish to Kitchen/all: client is not connected
2024-02-15 12:08:32.107882556  [2024-02-15 12:08:32] frigate.comms.mqtt             ERROR   : Unable to publish to Kitchen/motion: client is not connected
2024-02-15 12:08:32.115358127  [2024-02-15 12:08:32] frigate.comms.mqtt             ERROR   : Unable to publish to Boys/all: client is not connected
2024-02-15 12:08:32.115522902  [2024-02-15 12:08:32] frigate.comms.mqtt             ERROR   : Unable to publish to Boys/motion: client is not connected
2024-02-15 12:08:32.994572922  [2024-02-15 12:08:32] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:35.166084554  [2024-02-15 12:08:35] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:35.177198396  [2024-02-15 12:08:35] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/person/snapshot: client is not connected
2024-02-15 12:08:35.177322000  [2024-02-15 12:08:35] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/person: client is not connected
2024-02-15 12:08:35.177488002  [2024-02-15 12:08:35] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/all: client is not connected
2024-02-15 12:08:37.624023652  [2024-02-15 12:08:37] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:39.021985115  [2024-02-15 12:08:39] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:39.419410328  [2024-02-15 12:08:39] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:40.090094886  [2024-02-15 12:08:40] frigate.comms.mqtt             ERROR   : Unable to publish to Driveway/car/snapshot: client is not connected
2024-02-15 12:08:40.430349464  [2024-02-15 12:08:40] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:41.035376783  [2024-02-15 12:08:41] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:41.040157373  [2024-02-15 12:08:41] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:45.285241375  [2024-02-15 12:08:45] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:45.650344559  [2024-02-15 12:08:45] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:49.249761445  [2024-02-15 12:08:49] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:49.439117774  [2024-02-15 12:08:49] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/all: client is not connected
2024-02-15 12:08:49.439316434  [2024-02-15 12:08:49] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/person: client is not connected
2024-02-15 12:08:49.443937513  [2024-02-15 12:08:49] frigate.comms.mqtt             ERROR   : Unable to publish to Garden/person/snapshot: client is not connected
2024-02-15 12:08:50.403816128  [2024-02-15 12:08:50] frigate.comms.mqtt             ERROR   : Unable to publish to events: client is not connected
2024-02-15 12:08:50.810712112  [2024-02-15 12:08:50] ws4py                          ERROR   : Error when terminating the connection: [Errno 32] Broken pipe
2024-02-15 12:08:53.715128830  Traceback (most recent call last):
2024-02-15 12:08:53.715133719    File "/usr/lib/python3.9/wsgiref/handlers.py", line 138, in run
2024-02-15 12:08:53.715135140      self.finish_response()
2024-02-15 12:08:53.715136738    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 87, in finish_response
2024-02-15 12:08:53.715141202      self.request_handler.server.link_websocket_to_server(ws)
2024-02-15 12:08:53.715162749    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 129, in link_websocket_to_server
2024-02-15 12:08:53.715164522      self.manager.add(ws)
2024-02-15 12:08:53.715165951    File "/usr/local/lib/python3.9/dist-packages/ws4py/manager.py", line 253, in add
2024-02-15 12:08:53.715167512      logger.info("Managing websocket %s" % format_addresses(websocket))
2024-02-15 12:08:53.715169014    File "/usr/local/lib/python3.9/dist-packages/ws4py/__init__.py", line 61, in format_addresses
2024-02-15 12:08:53.715182344      peer = ws.peer_address
2024-02-15 12:08:53.715183880    File "/usr/local/lib/python3.9/dist-packages/ws4py/websocket.py", line 164, in peer_address
2024-02-15 12:08:53.715185665      self._peer_address = self.sock.getpeername()
2024-02-15 12:08:53.715186968  OSError: [Errno 107] Transport endpoint is not connected
2024-02-15 12:08:53.715238751  ----------------------------------------
2024-02-15 12:08:53.715274562  Exception occurred during processing of request from ('127.0.0.1', 48872)
2024-02-15 12:08:53.716656638  Traceback (most recent call last):
2024-02-15 12:08:53.716675034    File "/usr/lib/python3.9/wsgiref/handlers.py", line 138, in run
2024-02-15 12:08:53.716676519      self.finish_response()
2024-02-15 12:08:53.716678082    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 87, in finish_response
2024-02-15 12:08:53.716679476      self.request_handler.server.link_websocket_to_server(ws)
2024-02-15 12:08:53.716681091    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 129, in link_websocket_to_server
2024-02-15 12:08:53.716682261      self.manager.add(ws)
2024-02-15 12:08:53.716683682    File "/usr/local/lib/python3.9/dist-packages/ws4py/manager.py", line 253, in add
2024-02-15 12:08:53.716685028      logger.info("Managing websocket %s" % format_addresses(websocket))
2024-02-15 12:08:53.716686484    File "/usr/local/lib/python3.9/dist-packages/ws4py/__init__.py", line 61, in format_addresses
2024-02-15 12:08:53.716687664      peer = ws.peer_address
2024-02-15 12:08:53.716689144    File "/usr/local/lib/python3.9/dist-packages/ws4py/websocket.py", line 164, in peer_address
2024-02-15 12:08:53.716690411      self._peer_address = self.sock.getpeername()
2024-02-15 12:08:53.716701926  OSError: [Errno 107] Transport endpoint is not connected
2024-02-15 12:08:53.716703110  
2024-02-15 12:08:53.716704425  During handling of the above exception, another exception occurred:
2024-02-15 12:08:53.716705440  
2024-02-15 12:08:53.716706612  Traceback (most recent call last):
2024-02-15 12:08:53.716726884    File "/usr/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
2024-02-15 12:08:53.716728261      self.process_request(request, client_address)
2024-02-15 12:08:53.716729619    File "/usr/lib/python3.9/socketserver.py", line 347, in process_request
2024-02-15 12:08:53.716730898      self.finish_request(request, client_address)
2024-02-15 12:08:53.716732185    File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
2024-02-15 12:08:53.716733427      self.RequestHandlerClass(request, client_address, self)
2024-02-15 12:08:53.716734741    File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
2024-02-15 12:08:53.716735869      self.handle()
2024-02-15 12:08:53.716737265    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 105, in handle
2024-02-15 12:08:53.716738463      handler.run(self.server.get_app())
2024-02-15 12:08:53.716745035    File "/usr/lib/python3.9/wsgiref/handlers.py", line 145, in run
2024-02-15 12:08:53.716746136      self.handle_error()
2024-02-15 12:08:53.716747466    File "/usr/lib/python3.9/wsgiref/handlers.py", line 382, in handle_error
2024-02-15 12:08:53.716748601      self.finish_response()
2024-02-15 12:08:53.716750075    File "/usr/local/lib/python3.9/dist-packages/ws4py/server/wsgirefserver.py", line 80, in finish_response
2024-02-15 12:08:53.716751276      SimpleHandler.finish_response(self)
2024-02-15 12:08:53.716752639    File "/usr/lib/python3.9/wsgiref/handlers.py", line 184, in finish_response
2024-02-15 12:08:53.716753761      self.write(data)
2024-02-15 12:08:53.716755097    File "/usr/lib/python3.9/wsgiref/handlers.py", line 288, in write
2024-02-15 12:08:53.716756208      self.send_headers()
2024-02-15 12:08:53.716757543    File "/usr/lib/python3.9/wsgiref/handlers.py", line 345, in send_headers
2024-02-15 12:08:53.716758771      if not self.origin_server or self.client_is_modern():
2024-02-15 12:08:53.716760135    File "/usr/lib/python3.9/wsgiref/handlers.py", line 358, in client_is_modern
2024-02-15 12:08:53.716761408      return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
2024-02-15 12:08:53.716762589  TypeError: 'NoneType' object is not subscriptable
2024-02-15 12:08:53.716770507  ----------------------------------------
2024-02-15 12:08:55.279413807  [2024-02-15 12:08:55] ws4py                          ERROR   : Error when terminating the connection: [Errno 32] Broken pipe
```

### Operating system

HassOS

### Install method

HassOS Addon

### Coral version

USB

### Any other information that may be helpful

![Screenshot 2024-02-15 145547](https://github.com/blakeblackshear/frigate/assets/9522017/093ca2a3-14ed-45b8-b319-719c7403c383)
![Screenshot 2024-02-15 145628](https://github.com/blakeblackshear/frigate/assets/9522017/6a88fbab-8c03-4012-8adf-1bd05d0c5009)

**Comment by futuredj** [comment]
> There's no reason to run detect at fps that high, 5 is the default and id recommend 10 at max

Detect is running at 5. I was running it at 25 on v12 and everything was ok. It runs ok at 5 on lows res but now birdseye and liveview are at low res and low fps which is not good enough for viewing. What have I missed?

**Comment by futuredj** [comment]
![Screenshot 2024-02-15 153043](https://github.com/blakeblackshear/frigate/assets/9522017/ab261606-93e1-48fa-804b-bac08ebaa0d2)

10 mins of frigate running. Now believe this is why performance is bad. Any ideas why? Is this normal?

**Comment by NickM-27** [comment]
Your detect fps is not at 5

```
    detect:
      width: 640
      height: 480
      fps: 29
    live:
      stream_name: frontdoor
```

```
    detect:
      width: 640
      height: 360
      fps: 25
    live:
      stream_name: boys
```

Birdseye runs on the decoded stream (this is required) so it will always use what comes from detect.

**Comment by futuredj** [comment]
> Your detect fps is not at 5
> 
> ```
>     detect:
>       width: 640
>       height: 480
>       fps: 29
>     live:
>       stream_name: frontdoor
> ```
> 
> ```
>     detect:
>       width: 640
>       height: 360
>       fps: 25
>     live:
>       stream_name: boys
> ```
> 
> Birdseye runs on the decoded stream (this is required) so it will always use what comes from detect.

I know I noticed this and corrected already and it has made 0 difference. Do you have any other suggestions? Even running at these lower resolutions the system is unbearably slow. Would a different codec help? V12 didn't have this problem...

**Comment by NickM-27** [comment]
Can you send a screenshot of the system page

**Comment by futuredj** [comment]
![Screenshot 2024-02-17 090127](https://github.com/blakeblackshear/frigate/assets/9522017/fb3fce38-1132-4724-9831-6c556cdcd264)
![Screenshot 2024-02-17 090151](https://github.com/blakeblackshear/frigate/assets/9522017/51fb9ded-3cc2-4a0e-9588-f91628fe5e49)

**Comment by NickM-27** [comment]
everything here looks like CPU usage is very low, so I am not sure where you are seeing high cpu usage

**Comment by NickM-27** [comment]
by the way there is no reason to have `#hardware=cuda` when you are doing audio transcoding, that will not do anything
